### ISSUE TITLE
Comment & Close allows duplicate POSTs

### ISSUE THREAD

**Issue by DisruptiveMind** [gitlabhq/gitlabhq#10006]
I was using the GitLab.com hosted service this morning and double clicked the `Comment & close` button for an issue and managed to duplicate the POST request.

**Comment by rymai** [comment]
Thanks @DisruptiveMind,

You are right, we should probably disable the button once you clicked it and re-enable it once we get a response back.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
