### ISSUE TITLE
Relative URL breaks avatar image for commit tooltip on network graph.

### ISSUE THREAD

**Issue by devsr** [gitlabhq/gitlabhq#10003]
Configuring Gitlab to use a relative url breaks avatar images for commit tools tips on the project network graph that use gravatar.

If using gravatar as an avatar source, then broken links are produced that look like <relative-path-part><gravatar-uri>

Example : /gitlabhttps://secure.gravatar.com/avatar/b2ee5980501f21314923f751e4740446?s=40&d=identicon

Notice the '/gitlab' part that shouldn't be there.

The offending line of code: [app/assets/javascripts/branch-graph.js.coffee @ 290.](https://github.com/gitlabhq/gitlabhq/blob/master/app/assets/javascripts/branch-graph.js.coffee#L290)

I believe this commit 5b123dbf fixed relative url links but broke gravatar links.

Similar issue #7270 dealing with other UI components that render avatars.

**Comment by devsr** [comment]
Seems like this would be addressed by pull request #7173 which was closed without being merged. Not sure if that PR got superseded by something else, but not everything in it got applied.

**Comment by rymai** [comment]
@devsr It looks like it has been fixed by f2a817f040315f5defaa4c9cf32b1a4455fe6df5 but [not in the tooltip](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/assets/javascripts/branch-graph.js.coffee#L290).

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
