### ISSUE TITLE
Suggestion: Use label to mark duplicated on gitlab

### ISSUE THREAD

**Issue by AdrieanKhisbe** [gitlabhq/gitlabhq#10008]
Little suggestion passing by: 

Would be nice both on user, and probably maintener perspective to label issues that are on gitlab.
(and why not also adding a link to the gitlab issue)
cf  https://github.com/gitlabhq/gitlabhq/issues/9376

:smiley:

**Comment by rymai** [comment]
Thanks for the suggestion @AdrieanKhisbe!

I've created the `duplicate` label, that should be enough (in the case of a duplicate on GitLab.com, we can just add the link to the issue in a comment).

**Comment by AdrieanKhisbe** [comment]
@rymai, you're welcome :smiley:
