### ISSUE TITLE
Sprockets Error on Ubuntu Trusty couldn't find file 'jquery-ui/datepicker'

### ISSUE THREAD

**Issue by caplod** [gitlabhq/gitlabhq#10000]
I just upgraded my gitlab-ce installation to version 8.4.0-ce.0 via apt-get upgrade

Now I get a sprockets error 
couldn't find file 'jquery-ui/datepicker'
in /opt/gitlab/embedded/service/gitlab-rails/app/assets/stylesheets/application.scss:5

how can I fix this?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
