### ISSUE TITLE
tag statistic error!

### ISSUE THREAD

**Issue by walkthetalk** [gitlabhq/gitlabhq#10013]
on header bar, the tags number is 38, but below it says no tag, why?

the repository is generated in gitlab, bug modified config for mirror of external repo, and use sudo -ugitlab git remote update --prune.

the config file content:
[core]
        repositoryformatversion = 0
        filemode = true
        bare = true
        autocrlf = input
[remote "origin"]
        url = https://github.com/qtproject/qtgraphicaleffects.git
        fetch = +refs/*:refs/*
        mirror = true

![tags](https://cloud.githubusercontent.com/assets/980420/12743070/f7ed544c-c982-11e5-8713-098a7a800978.png)

**Comment by stanhu** [comment]
I wonder if this is a caching issue. Does running `sudo gitlab-rake cache:clear` fix things?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
