### ISSUE TITLE
an easier way to find an issue by issue number

### ISSUE THREAD

**Issue by alexkb** [gitlabhq/gitlabhq#10019]
Sometimes developers talk about issues by issue number, and want an easy way to access the issue.

One way is to click on an issue and then change the number at the end of the URL. Is there another way?

If there aren't, would it be possible to allow the filter box at the top of the issue list to filter by issue number too (githubs issue list filter supports this). This seems like a more intuitive way to find the issue rather than playing with URL's.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
