### ISSUE TITLE
printing/exporting issue lists

### ISSUE THREAD

**Issue by alexkb** [gitlabhq/gitlabhq#10010]
From a developers perspective, we really love gitlab. From our managers point of view though, they can't stand it. Basically all they're after is the ability to generate reports (printing the current issue list would suffice) of the issue lists. By default, if you try print the issue list, it's a mess so this could probably be easily fixed with a print stylesheet.

Has anyone else given this any thought already? Are there any plugins out there to do this kind of thing, perhaps to export in other formats. Thanks.

**Comment by JobV** [comment]
I'll resist the urge to comment on people printing things.

@alexkb We're working on the ability to export a project or just the issues:

- entire project: https://gitlab.com/gitlab-org/gitlab-ce/issues/3050
- issues as csv https://gitlab.com/gitlab-org/gitlab-ce/issues/5747

That said, I think it's not super hard either to have a print stylesheet in rails:
http://stackoverflow.com/questions/19145065/how-to-use-print-styles-in-css-with-rails-4

@alexkb If you'd be interested in contributing a print stylesheet, that'd be great. Do you think the other solutions (export to csv, print that) would work for you?

**Comment by dosire** [comment]
I would love to see a print stylesheet.

**Comment by alexkb** [comment]
@JobV a colleague here @tallsam pointed me to this neat little script by this fellow @raisoman:
https://gitlab.com/raisoman/gitlab-sandbox/blob/master/gitlab-ticket-table.html

After editing the hostname to be our own gitlab server, it worked perfectly. Be great to get this baked into the gitlab interface, so it was easy for non-techies to use.

**Comment by randx** [comment]
@alexkb its JS via API. I think we should solve it in simple way via print stylesheet. I created an issue - https://gitlab.com/gitlab-org/gitlab-ce/issues/13608 cc @dosire @JobV

**Comment by alexkb** [comment]
@randx a print stylesheet assumes the content the user wants is on the page. As others have pointed out, it's actually an _export_ feature that people need. The _JS via API_ solution by @raisoman was handy because it had a lot of columns not visible (and therefore not available if a print stylesheet approach was taken) in the issue queue listing.

**Comment by randx** [comment]
@alexkb in this case its not printing but export feature.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
