### ISSUE TITLE
cloning through SSH doesn't work when gitlab and nginx are installed on different machine!

### ISSUE THREAD

**Issue by fnstlmm** [gitlabhq/gitlabhq#10012]
gitlab and nginx are installed on different machine,I can visit gitlab by the machine's IP which nginx is installed on.
I can clone project  through HTTP,but I can't clone project  through SSH！
when gitlab and nginx are installed on the same machine,I can clone through either SSH or HTTP!
Is anyone can tell me why?Thanks!

**Comment by stanhu** [comment]
SSH shouldn't be affected by nginx. Are you sure your host is connecting to the right SSH server in the first place (i.e. not the box that has nginx)?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
