### ISSUE TITLE
Installing GitLab clobbers existing user

### ISSUE THREAD

**Issue by ctag** [gitlabhq/gitlabhq#10014]
I have a remote server with existing private git projects on it, managed by the user `git`. I'd also like to have separate git projects for a different organization hosted on GitLab.

After installing GitLab from the [download page's instructions](https://about.gitlab.com/downloads/#debian7), I found that it had hijacked my user and made connecting to this remote with existing projects inoperable.

Perhaps include a message during install when the system is about to modify an existing user rather than create a new one? Or if there is a warning, maybe make it more salient.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
