### ISSUE TITLE
Tag on Merge (merge request)

### ISSUE THREAD

**Issue by MeirionHughes** [gitlabhq/gitlabhq#10015]
Given you refuse to use fast-forward...  (https://github.com/gitlabhq/gitlabhq/issues/2324)

can you add on the ability to tag the resulting merge commit? i.e. when accepting a merge request, have option to specify a tag to apply to merge commit.

I'm doing Continuous integration off my master branches that requires the commit to he tagged with the version number. 

There is no easy way to do this quickly enough in the web browser (do the merge, then create the tag before the automatic build pulls the repository).

**Comment by MadhavGitlab** [comment]
You can write up a script to use GitLab API to accept a merge request, get the commit of the merge and then tag that commit.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Comment by k127** [comment]
(http://stackoverflow.com/questions/39159789/how-to-create-tag-automatically-upon-accepted-merge-request-in-gitlab)

**Comment by DD-Jeroen** [comment]
See also https://about.gitlab.com/2016/08/19/applying-gitlab-labels-automatically/.
