### ISSUE TITLE
Wiki : delete button too close from edit button

### ISSUE THREAD

**Issue by arthur-c** [gitlabhq/gitlabhq#10026]
Hi,

It's easier to trigger the delete button than the edit button when you are working on wiki pages.  It's red and visible but when you are in the process of writing/preview/save/edit/repeat it's easy to click 1cm to the right. The delete button should be elsewhere, far from the edit button and the circle edit/preview/save/edit... (like the cancel button)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
