### ISSUE TITLE
config external_url not working

### ISSUE THREAD

**Issue by kitingChris** [gitlabhq/gitlabhq#10021]
Although external_url is set in gitlab.rb it does not show up in gitlab. Also pushing is not possible!

        ## Latest options listed at https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template

        external_url 'https://gitlab.mydomain.net'

        # Disable the built-in nginx
        nginx['enable'] = false

        # Disable the built-in unicorn
        unicorn['enable'] = false

        # Set the internal API URL
        gitlab_rails['internal_api_url'] = 'https://gitlab.mydomain.net'

        gitlab_rails['gitlab_ssh_host'] = 'mydomain.net'

        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'gitlab@mydomain.net'
        gitlab_rails['gitlab_email_reply_to'] = 'gitlab@mydomain.net'

        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.googlemail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "root@mydomain.net"
        gitlab_rails['smtp_password'] = "*********"
        gitlab_rails['smtp_domain'] = "mydomain.net"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'

        git_data_dir "/srv/git"
        ruby git_data_dir "/srv/git"

Although I executed 

       sudo gitlab-ctl reconfigure
       sudo gitlab-ctl restart

nothing happened...

Looks still like this: [screenshot](https://dl.dropboxusercontent.com/u/2979601/gitlab-screen.png)

Trying to push (with ssh) results in this error:

       $ git push -u origin master
       GitLab: API is not accessible
       fatal: Could not read from remote repository.
       
       Please make sure you have the correct access rights
       and the repository exists.

Permissions on the custom git-data:      

       # ls -laH /srv/git
       total 16
       drwx------ 4 git   git   4096 Feb  7 01:00 .
       drwxr-xr-x 8 root  root  4096 Jan 19 21:07 ..
       drwxrws--- 4 git   git   4096 Feb  7 02:01 repositories

Anyone an idea what I can do to fix this issue?

**Comment by stanhu** [comment]
Perhaps it's a caching issue? You may want to run `sudo gitlab-rake cache:clear`.

**Comment by kitingChris** [comment]
Thanks that helped.

**Comment by stanhu** [comment]
@kitingChris I'm a little confused how that happened because doing a `sudo gitlab-ctl reconfigure` after changing `/etc/gitlab/gitlab.rb` should clear the cache.

**Comment by kitingChris** [comment]
Well I did also a reboot so not really sure if the reboot did it or the clear cache command.
