### ISSUE TITLE
fatal: Not a git repository when clicking on "Help"

### ISSUE THREAD

**Issue by raduab** [gitlabhq/gitlabhq#10037]
After clicking "help" from menu, on the first row it says:

"GitLab Community Edition 8.4.4 fatal: Not a git repository (or any of the parent directories): .git"

the rest of information is ok, the documentation is there, the status messages are shown etc. The problem is just the appearance of the error message.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
