### ISSUE TITLE
8.5: Missing section on 8.4-to-8.5.md

### ISSUE THREAD

**Issue by davrodpin** [gitlabhq/gitlabhq#10031]
The _Init script_ section is missing on the update documentation, leading to errors while checking the application status.

I have a patch almost ready (https://github.com/davrodpin/gitlabhq/commit/ad500117e1bf968d7cba5c95b1b9c8c6f9d56564)  (pull request #10033) , but I don't have much knowledge on gitlab to come up with what the actual changes mean.

I'll be happy to open a merge request if anyone can provide that description.

Changes made on the init script since 8.4:

```diff
$ git diff origin/8-4-stable:lib/support/init.d/gitlab origin/8-5-stable:lib/support/init.d/gitlab
diff --git a/origin/8-4-stable:lib/support/init.d/gitlab b/origin/8-5-stable:lib/support/init.d/gitlab
index 1633891..d95e702 100755
--- a/origin/8-4-stable:lib/support/init.d/gitlab
+++ b/origin/8-5-stable:lib/support/init.d/gitlab
@@ -38,7 +38,7 @@ web_server_pid_path="$pid_path/unicorn.pid"
 sidekiq_pid_path="$pid_path/sidekiq.pid"
 mail_room_enabled=false
 mail_room_pid_path="$pid_path/mail_room.pid"
-gitlab_workhorse_dir=$(cd $app_root/../gitlab-workhorse && pwd)
+gitlab_workhorse_dir=$(cd $app_root/../gitlab-workhorse 2> /dev/null && pwd)
 gitlab_workhorse_pid_path="$pid_path/gitlab-workhorse.pid"
 gitlab_workhorse_options="-listenUmask 0 -listenNetwork unix -listenAddr $socket_path/gitlab-workhorse.socket -authBackend http://1
 gitlab_workhorse_log="$app_root/log/gitlab-workhorse.log"
@@ -49,7 +49,7 @@ test -f /etc/default/gitlab && . /etc/default/gitlab

 # Switch to the app_user if it is not he/she who is running the script.
 if [ `whoami` != "$app_user" ]; then
-  eval su - "$app_user" -s $shell_path -c $(echo \")$0 "$@"$(echo \"); exit;
+  eval su - "$app_user" -c $(echo \")$shell_path -l -c \'$0 "$@"\'$(echo \"); exit;
 fi

 # Switch to the gitlab path, exit on failure.
@@ -219,7 +219,7 @@ start_gitlab() {
     echo "The Unicorn web server already running with pid $wpid, not restarting."
   else
     # Remove old socket if it exists
-    rm -f "$socket_path"/gitlab.socket 2>/dev/null
+    rm -f "$rails_socket" 2>/dev/null
     # Start the web server
     RAILS_ENV=$RAILS_ENV bin/web start
   fi
```

**Comment by stanhu** [comment]
Can you explain why these changes to the init script were necessary? I can imagine the `-l` option may be helpful in `su`, but other than that, do any of the other changes help things?

**Comment by stanhu** [comment]
Oh, I see, your diff is just listing the changes between 8.4 and 8.5. I think we can either leave the description of the changes out or mention that the differences are minor revisions.

**Comment by davrodpin** [comment]
> Oh, I see, your diff is just listing the changes between 8.4 and 8.5. I think we can either leave the description of the changes out or mention that the differences are minor revisions.

Thanks for the info @stanhu. I'll open a pull request.

**Comment by stanhu** [comment]
Closing in favor of merge request here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2815
