### ISSUE TITLE
update gitlab from 7.6 to 7.7.2 : ActionView::Template::Error (undefined method `developers_can_push' 

### ISSUE THREAD

**Issue by vmintam** [gitlabhq/gitlabhq#10032]
Dear guys,

 current, i'm using GitLab Community Edition version 7.6 (with PostgreSQL DB).
 I have just upgrade to gitlab 7.7.2, but something error.

in web GUI, when i choose **settings in projects, click to protected_branches --> 500 error.**
in git client, when i push to master branch, i catch error : 

**remote: GitLab: API is not accessible
To git@xxx.xx:my-projects/test.git
 ! [remote rejected] master -> master (pre-receive hook declined)**

when i check log in my server, i see : 

**Processing by Projects::ProtectedBranchesController#index as HTML
  Parameters: {"project_id"=>"vmsclients/vms_ott_android_v2"}
Completed 500 Internal Server Error in 27ms

ActionView::Template::Error (undefined method `developers_can_push' for #<ProtectedBranch:0x007f79f2a28b40>):
    27:         Developers can push
    28:       .col-sm-10
    29:         .checkbox
    30:           = f.check_box :developers_can_push**

**I have checked info and status, everything fine.
bundle exec rake gitlab:check RAILS_ENV=production
bundle exec rake db:migrate:status RAILS_ENV=production**

thanks!

**Comment by stanhu** [comment]
That sounds like the `developers_can_push` column may not be in the `protected_branches` table but the migration appears to have bene applied. Can you try the following?

```
$ sudo gitlab-rails dbconsole
gitlabhq_production=# \d protected_branches
                                          Table "public.protected_branches"
       Column        |            Type             |                            Modifiers                            
---------------------+-----------------------------+-----------------------------------------------------------------
 id                  | integer                     | not null default nextval('protected_branches_id_seq'::regclass)
 project_id          | integer                     | not null
 name                | character varying(255)      | not null
 created_at          | timestamp without time zone | 
 updated_at          | timestamp without time zone | 
 developers_can_push | boolean                     | not null default false
Indexes:
    "protected_branches_pkey" PRIMARY KEY, btree (id)
    "index_protected_branches_on_project_id" btree (project_id)
```

If the `developers_can_push` column is not there, I'd try to reapply the migration:

```
sudo gitlab-rake db:migrate:redo VERSION=20141226080412
```

**Comment by vmintam** [comment]
Hi Stanhu,

 thanks for reply!

 but i use **none gitlab-rails**. I have updated from this link: 
**https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/7.6-to-7.7.md
**
when i access to postgreSQL, i see: 

```
gitlabhq_production=# \d protected_branches
                                     Table "public.protected_branches"
   Column   |            Type             |                            Modifiers                 
           
------------+-----------------------------+------------------------------------------------------
-----------
 id         | integer                     | not null default nextval('protected_branches_id_seq':
:regclass)
 project_id | integer                     | not null
 name       | character varying(255)      | not null
 created_at | timestamp without time zone | 
 updated_at | timestamp without time zone | 
Indexes:
    "protected_branches_pkey" PRIMARY KEY, btree (id)
    "index_protected_branches_on_project_id" btree (project_id)
gitlabhq_production=# \d protected_branches
                                     Table "public.protected_branches"
   Column   |            Type             |                            Modifiers                 
           
------------+-----------------------------+------------------------------------------------------
-----------
 id         | integer                     | not null default nextval('protected_branches_id_seq':
:regclass)
 project_id | integer                     | not null
 name       | character varying(255)      | not null
 created_at | timestamp without time zone | 
 updated_at | timestamp without time zone | 
Indexes:
    "protected_branches_pkey" PRIMARY KEY, btree (id)
    "index_protected_branches_on_project_id" btree (project_id)
```


like you mentioned, _developers_can_push_ column is not there.

but, how to I reapply the migration to VERSION=20141226080412 ?

**Comment by stanhu** [comment]
If you're installing from source, you can reapply that migration like so:

```
cd /home/git/gitlab
sudo -u git -H bundle exec rake db:migrate:redo VERSION=20141226080412 RAILS_ENV=production
```

**Comment by vmintam** [comment]
Hi Stanhu,

 I have run:
`bundle exec rake db:migrate:status RAILS_ENV=production
`output:
```
..................
  up     20141205134006  Add locked at to merge request
   up     20141216155758  Create doorkeeper tables
   up     20141217125223  Add owner to application
   up     20141223135007  Add import data to project table
   up     20141226080412  Add developers can push to protected branches
   up     20150108073740  Create application settings
   up     20150116234544  Add home page url for application settings
......................
```
and try run **db:migrate:redo**

`bundle exec rake db:migrate:redo VERSION=20150116234544 RAILS_ENV=production
`
but when** i start gitlab,** and access to **postgreSQL**, nothing happen:

```
psql gitlabhq_production
psql (9.3.6)
Type "help" for help.

gitlabhq_production=> \d protected_branches;
                                     Table "public.protected_branches"
   Column   |            Type             |                            Modifiers                 
           
------------+-----------------------------+------------------------------------------------------
-----------
 id         | integer                     | not null default nextval('protected_branches_id_seq':
:regclass)
 project_id | integer                     | not null
 name       | character varying(255)      | not null
 created_at | timestamp without time zone | 
 updated_at | timestamp without time zone | 
Indexes:
    "protected_branches_pkey" PRIMARY KEY, btree (id)
    "index_protected_branches_on_project_id" btree (project_id)
```

I have check and see, when i run migrate,  **db/schema.rb** file   don't have _developers_can_push_ column.

**Comment by stanhu** [comment]
I don't think you ran redo on the right revision. You should use `VERSION=20141226080412` as I said.

**Comment by stanhu** [comment]
I'm not sure what is going on with your `db/schema.rb`. It seems that your database and source code state are off. I highly recommend moving to the omnibus package once you straighten this out.

**Comment by vmintam** [comment]
I know you mean.

i have altered table **protected_branches** manual in postgreSQL, and everything is OK.

i think that, the problem is command:

```
bundle exec rake db:migrate:status RAILS_ENV=production

```
don't already migrate database, i have checked postgreDB, nothing updated.

If i want to upgrate to new version, will be difficult.

**Comment by stanhu** [comment]
You should check the `schema_migrations` table. It lists the migrations that have been applied already. The `db:migrate` command won't do anything if all entries are present.

**Comment by vmintam** [comment]
thanks you.
i will recheck this table.
