### ISSUE TITLE
wiki page display an error clone url after switching

### ISSUE THREAD

**Issue by sxi3265** [gitlabhq/gitlabhq#10034]
In wiki page,the clone url is displayed after switching is wrong

**Comment by stanhu** [comment]
If you run `sudo gitlab-rake cache:clear`, does it help?

**Comment by sxi3265** [comment]
The official website also has the same problem

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
