### ISSUE TITLE
gitlab side panel scroll bar wrong placement

### ISSUE THREAD

**Issue by vasukolli** [gitlabhq/gitlabhq#10049]
When I try to hover on menu after  closing and opening the gitlab side panel in admin page the scroll bar location changed.

Gitlab version:  8.5.0

![gitlab-scroll bar](https://cloud.githubusercontent.com/assets/9819197/13247102/909dc3c8-da3d-11e5-8b8b-867a0201e53f.png)

Thanks,
Vasu.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
