### ISSUE TITLE
Can not start service when i use '/sbin/nologin' shell at 8.5.0

### ISSUE THREAD

**Issue by warmwinter** [gitlabhq/gitlabhq#10048]
I upgraded my gitlab from 8.4.0 to 8.5.0.
When finished, i restart service ,but occur error with "This account is currently not available" message.
I search the resolve method by google, change shell from "/sbin/nologin" to "/bin/bash".
Now i restart service success.
My operation system info:
Linux 3.10.0-327.10.1.el7.x86_64
CentOS 7

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
