### ISSUE TITLE
Accessing raw file produces a blank page since 8.5.0

### ISSUE THREAD

**Issue by PascalAnimateur** [gitlabhq/gitlabhq#10046]
## Summary

Accessing a raw file produces a blank page since updating to GitLab 8.5.0-ce. Everything was working fine with 8.4.x

Checking the environment using `sudo gitlab-rake gitlab:check SANITIZE=true` indicates that everything is OK.

`sudo gitlab-rake gitlab:env:info` returns the following:

> System information
> System:		LinuxMint 17.2
> Current User:	git
> Using RVM:	no
> Ruby Version:	2.1.8p440
> Gem Version:	2.5.1
> Bundler Version:1.10.6
> Rake Version:	10.5.0
> Sidekiq Version:4.0.1
> 
> GitLab information
> Version:	8.5.0
> Revision:	a513e09
> Directory:	/opt/gitlab/embedded/service/gitlab-rails
> DB Adapter:	postgresql
> URL:		http://gitlab.tesla
> HTTP Clone URL:	http://gitlab.tesla/some-group/some-project.git
> SSH Clone URL:	git@gitlab.tesla:some-group/some-project.git
> Using LDAP:	no
> Using Omniauth:	no
> 
> GitLab Shell
> Version:	2.6.10
> Repositories:	/var/opt/gitlab/git-data/repositories
> Hooks:		/opt/gitlab/embedded/service/gitlab-shell/hooks/
> Git:		/opt/gitlab/embedded/bin/git

**Comment by stanhu** [comment]
I just tested this and didn't have any issues. Did you restart all the processes, particularly gitlab-workhorse? I know there was a bug in an earlier version.

**Comment by PascalAnimateur** [comment]
Thanks I got it working by configuring gitlab-workhorse to listen on TCP port 8181 and adjusting my apache reverse proxy settings accordingly. It turns out my /etc/gitlab/gitlab.rb was outdated as it still used `gitlab_git_http_server`, and the section was all commented out.
