### ISSUE TITLE
cnetos 7 reconfigure error

### ISSUE THREAD

**Issue by hhy5861** [gitlabhq/gitlabhq#10045]
![11](https://cloud.githubusercontent.com/assets/8274977/13219911/f387670e-d9ad-11e5-9c76-3e69841aaff6.png)

**Comment by stanhu** [comment]
This looks like an invalid `external_url` in `/etc/gitlab/gitlab.rb`. Can you include the content?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
