### ISSUE TITLE
Issue while Merging in GitLab

### ISSUE THREAD

**Issue by Petchimuthu** [gitlabhq/gitlabhq#10047]
We are using the GitLab 8.2.3 version.

While submitting the merge request  from GitLab the following message appears :

This merge request contains merge conflicts

Please resolve these conflicts or ask someone with write access to this repository to merge this request manually.

But when we try to merge the same in local via command it merges without any conflicts.

Please help me to find out the issue.

Thanks,
Muthu.

**Comment by stanhu** [comment]
Is there a `.gitattributes` file in the main directory?

**Comment by kalesastha** [comment]
Hi Stanhu,

Above mentioned file (.gitattributes) present under /home/git/gitlab/ and the file content is given below :-1: 

CHANGELOG merge=union

Thanks,
Kalee Sastha

**Comment by kalesastha** [comment]
@stanhu  Any update reg the issues .???

**Comment by stanhu** [comment]
@kalesastha Yes, this issue is actively being worked on, but it is pending a number of changes to be released in libgit2. See https://gitlab.com/gitlab-org/gitlab-ce/issues/2315 for more details. I'll close this issue in favor of that one.
