### ISSUE TITLE
merge request   compare  500

### ISSUE THREAD

**Issue by adaiguoguo** [gitlabhq/gitlabhq#10052]
forked repo merge into target repo  merge request compare  return 500.
but I create a new branch to merge.It's OK.
My version is 8.4.2

`ActionView::Template::Error (Revspec '187b063be3a82b3939e86b8c0f732e7a5f07a883' not found.):
16: .files
17: - diff_files.each_with_index do |diff_file, index|
18: - diff_commit = commit_for_diff(diff_file)
19: - blob = project.repository.blob_for_diff(diff_commit, diff_file)
20: - next unless blob
21: 22: = render 'projects/diffs/file', i: index, project: project,
app/models/repository.rb:266:in method_missing' app/models/repository.rb:278:inblob_at'
app/models/repository.rb:437:in blob_for_diff' app/views/projects/diffs/_diffs.html.haml:19:inblock in _app_views_projects_diffsdiffshtml_haml3384797993644695964_53246440'
app/views/projects/diffs/_diffs.html.haml:17:in each' app/views/projects/diffs/_diffs.html.haml:17:ineach_with_index'
app/views/projects/diffs/_diffs.html.haml:17:in _app_views_projects_diffs__diffs_html_haml___3384797993644695964_53246440' app/views/projects/merge_requests/_new_submit.html.haml:41:in_app_views_projects_merge_requestsnewsubmit_html_haml1804198646061164243_57900140'
app/views/projects/merge_requests/new.html.haml:5:in `_app_views_projects_merge_requests_new_html_haml___526966976154867927_58073020'`

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
