### ISSUE TITLE
`/var/log/gitlab/reconfigure/` needs to be manually created (gitlab/gitlab-ce 8.5)

### ISSUE THREAD

**Issue by magthe** [gitlabhq/gitlabhq#10055]
In order to get *gitlab/gitlab-ce:8.5.1-ce.0* to start I needed to manually create the folder `logs/reconfigure/`.  Without it only `sshd` starts.

`docker log gitlab` shows what's needed:

```
Preparing services...
Starting services...
Configuring GitLab...
/opt/gitlab/embedded/bin/runsvdir-start: line 34: ulimit: max user processes: cannot modify limit: Operation not permitted
/opt/gitlab/embedded/bin/runsvdir-start: line 37: /proc/sys/fs/file-max: Read-only file system
[2016-02-25T14:05:19+00:00] FATAL: Failed to open or create log file at /var/log/gitlab/reconfigure/1456409119.log: Errno::ENOENT (No such file or directory @ rb_sysopen - /var/log/gitlab/reconfigure/1456409119.log)
[2016-02-25T14:05:19+00:00] FATAL: Aborting due to invalid 'log_location' configuration
```

**Comment by stanhu** [comment]
This looks like your filesystem got into read-only mode. I'm not sure if this is a disk or a Docker issue. Can you run `mount` to check that it isn't in read-only?

**Comment by magthe** [comment]
Nope, it's RW:

    /dev/mapper/kalman--vg-root on /var/log/gitlab type ext4 (rw,relatime,errors=remount-ro,data=ordered)

This particular folder is mounted in as a volume when starting the Docker instance (I'm following the steps documented by gitlab). I suspect it's a case of trying to open a file in a folder that doesn't exist ;)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
