### ISSUE TITLE
Progress bar is too thin, presenting accessibility issues

### ISSUE THREAD

**Issue by iamsteadman** [gitlabhq/gitlabhq#10056]
Hi. I'm enjoying GitLab a lot, but the (relatively) new progress bar at the top of the page is almost unusable if you can't see the whole screen. I'm visually impaired and it's not until someone pointed out the 1-pixel-high progress bar at the top of the page, that I realised that the software was already working on the request and needed more time.

It needs wider discussion than a PR, but it absolutely needs bringing up as it's an accessibility concern. Obviously I now know it's there, but there'll be plenty of other people who won't (and not necessarily those with a visual impairment), so I'd suggest that it might be worth looking into at some point in the near future.

Hope that's constructive rather than just whiny :)

**Comment by stanhu** [comment]
Seems like a reasonable request. The only question: how much should it increase to balance viewability and real estate? It's just a matter of tweaking the CSS:

https://github.com/caarlos0/nprogress-rails

/cc: @jschatz1, @creamzy

**Comment by iamsteadman** [comment]
Great question @stanhu. I think the key thing is not just the thickness of the progress bar, but what's done to the rest of the page to indicate that something's happening.

Does Rails add any classes to the body tag - for example - that could be used to signal in CSS that a long-running action is taking place? Something like that, along with a thicker bar would help the visual cue be a little more obvious.

I understand, after a chat with a friend that this isn't actually GitLab's responsibility, rather a problem with the opinionated nature of Rails. But if it's customisable, I think it would be worth exploring a solution.

Perhaps a short-term fix would involve using a thicker - 7px? - bright orange bar. I work for a UX-focused design agency so am trying not to think of something ugly... which is why I thought lightening/darkening the rest of the page as opposed to making the progress bar more harsh would be a better fit.

OK, enough rambling.

**Comment by jschatz1** [comment]
I agree! I think the key @iamsteadman is that the real problem is that there is no normal feedback when the page is loading. We need something that shows that the page is loading (similar to the spinner that appears in place of the favicon.

**Comment by creamzy** [comment]
@jschatz1 but logo animation!

**Comment by stanhu** [comment]
@creamzy Right! @iamsteadman, does the logo animation help you?

![image](https://gitlab.com/gitlab-org/gitlab-ce/uploads/ff048fd2e56a6dcae8801f998b484623/logo-sweep.gif)

**Comment by iamsteadman** [comment]
I think that's a great idea; I just wonder whether replacing it with an AJAX spinner in the GitLab colours would work? Definitely appreciate the consideration here.

**Comment by stanhu** [comment]
@iamsteadman The animated logo is already in GitLab 8.5: 

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2277

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
