### ISSUE TITLE
Respect .editorconfig settings

### ISSUE THREAD

**Issue by adrianblynch** [gitlabhq/gitlabhq#10057]
Not to be a github-do-it-so-you-should-too request, but respecting a .editorconfig file would mean being able to set tab widths when viewing code.

It would mean tabs going from the default width of 8:

<img width="528" alt="screen shot 2016-02-26 at 23 12 25" src="https://cloud.githubusercontent.com/assets/4160967/13367970/964aa950-dcde-11e5-9822-720ec8ef6720.png">

To a more reasonable 4:

<img width="531" alt="screen shot 2016-02-26 at 23 13 22" src="https://cloud.githubusercontent.com/assets/4160967/13367969/964506a8-dcde-11e5-9f12-9b68524cae4e.png">

Or what ever the .editorconfig is set to. Your code, your choice! :dancers:

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
