### ISSUE TITLE
Activity of dashboard not update

### ISSUE THREAD

**Issue by leavesbnw** [gitlabhq/gitlabhq#10051]
According to previous issues,thinking the problem is gitlab shell can not connect to redis server,But   I checked gitlab-shell,and show below:
```shell
leaves@localhost:~/git/gitlab-shell$ bin/check 
Check GitLab API access: OK
Check directories and files: 
        /home/leaves/git/repositories: OK
        /home/leaves/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.17
Send ping to redis server: PONG
```
gitlab version is 8-5-stable.
gitlab shell version is new

Can you help find the place where the problem is?

**Comment by leavesbnw** [comment]
I found it.It happend when mysql default character set was  not `utf8`

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
