### ISSUE TITLE
No chance to view icon titles when not full screen

### ISSUE THREAD

**Issue by vikkysmile** [gitlabhq/gitlabhq#10068]
I don't have any chance to expand menu and view icon titles when using Safari sidebar... In this case I have no option to expand/collapse menu width (arrow at the bottom of menu is hidden) and have to guess the meanings for non-obvious icons...
The same problem exists when I change the width of browser window.
If it's really a feature (I can guess it is, because even animation is used to hide that "arrow") - it's a very strange one that makes end user frustrated when using Gitlab.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
