### ISSUE TITLE
Account Confirmation Link not work

### ISSUE THREAD

**Issue by NewzerChina** [gitlabhq/gitlabhq#10065]
After signing up an account in my Gitlab CE 8.1.3 , 
I have to confirm the account by clicking the link in my email.
The thing is , the link didn't work .
the browser shows the information below:
"
could not connect to the server.
NSURLErrorDomain
"
how can i solve this problem.
sorry for my poor english.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
