### ISSUE TITLE
gitlab in subdirectory redirects at sign out to false directory

### ISSUE THREAD

**Issue by secustor** [gitlabhq/gitlabhq#10066]
I am not sure if this is intended behavior.

behavior:
On sign-out gitlab redirects to / and not to /gitlab/.
This will occure if there is no "After sign out path" set.

setup:
GitlabCE 8.5.2 at subdirectory /gitlab
OS: Ubuntu 14.04
nginx 1.4.6 non-bundled

from access.log of nginx:
10.22.40.105 - - [03/Mar/2016:09:16:18 +0100] "POST /gitlab/users/sign_out HTTP/1.1" 302 82 "https://kis-vm01/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
10.22.40.105 - - [03/Mar/2016:09:16:18 +0100] "GET / HTTP/1.1" 200 396 "https://kis-vm01/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"

workaround: 
Set your subdirectory as "After sign out path" at "Admin Area" -> "Settings"

greetings 
secustor

**Comment by artem-sidorenko** [comment]
@secustor I can't reproduce this on a fresh 8.5.2 CE omnibus installation on centos

```
==> /var/log/gitlab/nginx/gitlab_access.log <==
10.0.2.2 - - [03/Mar/2016:12:21:50 +0000] "POST /gitlab/users/sign_in HTTP/1.1" 302 95 "http://localhost:2082/gitlab/users/sign_in" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
10.0.2.2 - - [03/Mar/2016:12:21:50 +0000] "GET /gitlab/ HTTP/1.1" 200 3888 "http://localhost:2082/gitlab/users/sign_in" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
10.0.2.2 - - [03/Mar/2016:12:21:53 +0000] "POST /gitlab/users/sign_out HTTP/1.1" 302 108 "http://localhost:2082/gitlab/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
10.0.2.2 - - [03/Mar/2016:12:21:53 +0000] "GET /gitlab/users/sign_in HTTP/1.1" 200 2912 "http://localhost:2082/gitlab/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
```

external url is configured like this
```bash
$ grep ^external /etc/gitlab/gitlab.rb 
external_url 'http://localhost:2082/gitlab
```

There is no `After sign out path` configured

Could you please crosscheck your configuration, espessialy the nginx? Can you reproduce it with bundled nginx?

**Comment by secustor** [comment]
@artem-sidorenko 
I can reproduce with the (untouched) bundled nginx version 
set in gitlab.rb:
`external_url 'http://kis-vm01:3200/gitlab`

same behavior:
10.22.40.99 - - [03/Mar/2016:14:05:24 +0100] "POST /gitlab/users/sign_out HTTP/1.1" 302 86 "http://kis-vm01:3200/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
10.22.40.99 - - [03/Mar/2016:14:05:24 +0100] "GET / HTTP/1.1" 403 135 "http://kis-vm01:3200/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"

**Comment by artem-sidorenko** [comment]
@secustor Hm...

I'm doing following steps
- I have a fresh installation without any data or special configuration. The only one change is the external_url configuration in gitlab.rb
- Cleaning the browser cache
- Opening the main page, in my case `http://localhost:2082/gitlab`
- Login as root
- Logout

Is here something different to your steps?

**Comment by secustor** [comment]
@artem-sidorenko 

- I have used my already installed version of gitlab and simply enabled the bundled nginx, which I have not modified.

- done

- done

- I have deleted root, but I logged in as my personal account (admin)

- done

but I have found something interesting in the logs, when I use the bundled nginx:

==> /var/log/gitlab/gitlab-workhorse/current <==
2016-03-04_10:38:08.87487 kis-vm01:3200 @ - - [2016-03-04 11:38:08.819614141 +0100 CET] "POST /gitlab/users/sign_out HTTP/1.1" 302 86 "http://kis-vm01:3200/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0" 0.055202

==> /var/log/gitlab/nginx/gitlab_access.log <==
10.14.193.4 - - [04/Mar/2016:11:38:08 +0100] "POST /gitlab/users/sign_out HTTP/1.1" 302 86 "http://kis-vm01:3200/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"

 ==> /var/log/gitlab/nginx/gitlab_error.log <== 
2016/03/04 11:38:08 [error] 5038#0: *34 directory index of "/opt/gitlab/embedded/service/gitlab-rails/public/" is forbidden, client: 10.14.193.4, server: kis-vm01, request: "GET / HTTP/1.1", host: "kis-vm01:3200", referrer: "http://kis-vm01:3200/gitlab/" 

==> /var/log/gitlab/nginx/gitlab_access.log <==
10.14.193.4 - - [04/Mar/2016:11:38:08 +0100] "GET / HTTP/1.1" 403 135 "http://kis-vm01:3200/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"


### as comparison with the non-bundled nginx : 
==> /var/log/gitlab/gitlab-workhorse/current <==
2016-03-04_10:44:31.57901 kis-vm01 @ - - [2016-03-04 11:44:31.449985535 +0100 CET] "GET /gitlab/ HTTP/1.1" 200 12008 "https://kis-vm01/gitlab/users/sign_in" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0" 0.128959

==> /var/log/gitlab/gitlab-rails/production.log <==
Started DELETE "/gitlab/users/sign_out" for 127.0.0.1 at 2016-03-04 11:44:37 +0100
Processing by SessionsController#destroy as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]"}
Redirected to https://kis-vm01
Completed 302 Found in 41ms (ActiveRecord: 5.7ms)

==> /var/log/gitlab/gitlab-workhorse/current <==
2016-03-04_10:44:37.06996 kis-vm01 @ - - [2016-03-04 11:44:37.01584562 +0100 CET] "POST /gitlab/users/sign_out HTTP/1.1" 302 82 "https://kis-vm01/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0" 0.054046

nginx: 
10.14.193.4 - - [04/Mar/2016:11:44:31 +0100] "POST /gitlab/users/sign_in HTTP/1.1" 302 90 "https://kis-vm01/gitlab/users/sign_in" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
10.14.193.4 - - [04/Mar/2016:11:44:31 +0100] "GET /gitlab/ HTTP/1.1" 200 12021 "https://kis-vm01/gitlab/users/sign_in" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
10.14.193.4 - - [04/Mar/2016:11:44:37 +0100] "POST /gitlab/users/sign_out HTTP/1.1" 302 82 "https://kis-vm01/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
10.14.193.4 - - [04/Mar/2016:11:44:37 +0100] "GET / HTTP/1.1" 200 396 "https://kis-vm01/gitlab/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"

greetings 
secustor

**Comment by artem-sidorenko** [comment]
> I have used my already installed version of gitlab and simply enabled the bundled nginx, which I have not modified.
@secustor I see the problem in your logs, but I can't reproduce it. can you try to reproduce it on a fresh installation?

**Comment by secustor** [comment]
with a fresh installation after 
`apt-get purge gitlab-ce`
with several errors and manually deleting the left files.

- install gitlab-ce from package

- gitlab-ctl reconfigure

- change external_url to "http://kis-vm01/gitlab"

- gitlab-ctl reconfigure

- login with root

- change password

- logout 

- and it redirects to /gitlab as it should

In my opinion there went something wrong with the upgade process between 8.5.0 and 8.5.1 or 8.5.1 and 8.5.2. 

greetings 
secustor

**Comment by artem-sidorenko** [comment]
@secustor yes, there some additional [steps](https://gitlab.com/gitlab-org/omnibus-gitlab#uninstalling-omnibus-gitlab) required for a full uninstallation. This is a known problem as far I remember, but its not really easy to resolve it

> In my opinion there went something wrong with the upgade process between 8.5.0 and 8.5.1 or 8.5.1 and 8.5.2.

Do you have a DB dump/backup of old "broken" installation? If yes, I would take a look to the DB scheme and ask you for some DB dumps of gitlab settings table.

**Comment by secustor** [comment]
@artem-sidorenko 
Update to the problem...

The problem is back.
what I have did to this point:

- creating users and passwords for them ( all with german non ascii chars like ä,ö,ü) 

- deactivating gravatar, twitter, sign-up enabled, User OAuth applications

I will try every step seperatly tomorrow.

greetings
secustor

**Comment by artem-sidorenko** [comment]
@secustor thx! I could reproduce it on gitlab 8.5.4 on ubuntu 14.04:

- Fresh installation with relative URL setup in `/gitlab` (`external_url 'http://localhost:2080/gitlab`)
- Admin area -> Settings -> Just click Save (without to change anything)
- Sign-out redirect is redirecting to `/` instead of `/gitlab`

My assumption is:
 - On a fresh installation we probably do not have any value for "After sign out path" in the settings table
 - When "Save" is invoked we get a value like "empty string"
 - This empty string is used [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/fe9a445faaaa5a90c9308b01877aadc1984a111b/app/controllers/application_controller.rb#L110) in order to build the "broken" redirect (I'm not a Rails expert, but I guess it is the right place)

I do not have time to verify the above assumption, to test the change and provide MR in the next 2 weeks:\

As this issue can be reproduced easily now, maybe somebody from Gitlab could have a look? /cc @rymai

**Comment by secustor** [comment]
Perfect!
Nice, that we could find the bug after all.

greetings 
secustor

**Comment by ayapapa** [comment]
I think following function is to be modified for this issue, maybe.  
app/controllers/application_controller.rb 's function:  
``` ruby
  def after_sign_out_path_for(resource)
    current_application_settings.after_sign_out_path || new_user_session_path
  end
```
I tried to modify like following, and worked fine.
``` ruby
  def after_sign_out_path_for(resource)
    path = current_application_settings.after_sign_out_path
    (path == nil or path == "") ? new_user_session_path : path
  end
```
thank you.

**Comment by axilleas** [comment]
@maxlazio @jacobvosmaer can you chime in this issue? Reproducible steps at https://github.com/gitlabhq/gitlabhq/issues/10066#issuecomment-193901097

**Comment by jacobvosmaer** [comment]
@axilleas I am not an expert on this part of the app (Rails controller redirects etc.). The steps to reproduce sound sane, I think someone should create an issue on https://gitlab.com/gitlab-org/gitlab-ce/issues for this.

**Comment by artem-sidorenko** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3989
