### ISSUE TITLE
[feature] Hide groups: private / internal / public groups as for projects

### ISSUE THREAD

**Issue by Leryan** [gitlabhq/gitlabhq#10067]
Hi,

For some reason, I need to completely hide groups from the "explore" page.

Inside them, there are only private projects, but they are still visible from the explore page (and empty of course).

May this be added for a next release?

**Comment by Leryan** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/13998

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
