### ISSUE TITLE
Activity & Project options overlaid on left hand navigation pane on 8.5.1

### ISSUE THREAD

**Issue by artlepool** [gitlabhq/gitlabhq#10062]
Since upgrading to GitLab 8.5.1, on the left hand navigation pane, the options for Project and Activity are overlaid.

When you hover the mouse over the link, it changes to Project, you can click on it and you go to the Project page.  However, I can't access the Activity page now.

![screen shot 2016-03-02 at 09 20 58](https://cloud.githubusercontent.com/assets/8647257/13455891/1d0402bc-e058-11e5-8805-3110eecf8c4e.png)

**Comment by rymai** [comment]
@artlepool As far as we know, this bug was only in `master` and `8-5-stable` during the last few days but it's now [resolved in these two branches](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3043). It should not be in any tagged release.

**Comment by artlepool** [comment]
Thanks @rymai 

I applied the changes from that merge request to check whether it fixes the issue, but I'm afraid it doesn't.

It seems to be the fact that the "home" class is applied to the Project sidebar link. When I remove this class in my browser dev tools, then the Project and Activity links separate out correctly as expected and I can click on both of them

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
