### ISSUE TITLE
Update wiki or put a more descriptive message for importing local projects

### ISSUE THREAD

**Issue by apohllo** [gitlabhq/gitlabhq#10064]
The wiki says that when you want to import a local repo to gitlab, you should load it to `/home/git/repositiries`. When  I look to the rake task I see that it mentions the same path. But the real path for my installation is `/var/opt/gitlab/git-data/repositories/`. Moreover the repository has to end with `.git` which is not obvious. A better description should be provided in the wiki and maybe a message indicating which directory is processed. This would make the import process much easier and straightforward.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
