### ISSUE TITLE
Fixed versions and auto-migration

### ISSUE THREAD

**Issue by wernight** [gitlabhq/gitlabhq#10079]
Using this image on a Kubernetes cluster or actually in many other cases has the issue that it may just get a newer version automatically.

This would be good if at start time it called **`gitlab-rake db:migrate` automatically**.

Another thing that could be done to fix/improve are **tagged** version on Docker hub.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
