### ISSUE TITLE
Cannot display link in nested list of markdown when list level > 4

### ISSUE THREAD

**Issue by cybertk** [gitlabhq/gitlabhq#10073]
Please see the follow list, if you copy it in a GitLab's markdown page. the link in Level 5 will not be displayed

```
- Level 1: this is a [link](http://gitlab.com)
    - Level 2: this is a [link](http://gitlab.com)
        - Level 3: this is a [link](http://gitlab.com)
            - Level 4: this is a [link](http://gitlab.com)
                - Level 5: this is a [link](http://gitlab.com)
                    - Level 6: this is a [link](http://gitlab.com)
```

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
