### ISSUE TITLE
Free automated SSL/TLS certificate generation

### ISSUE THREAD

**Issue by timkoers** [gitlabhq/gitlabhq#10075]
I have just discovered this website: https://letsencrypt.org/
It allows certificate renweal and installation trough the command line.
And the best part:
It is completely free.

Maybe a good idea for GitLab?

**Comment by stanhu** [comment]
Yes, LetsEncrypt is fantastic; is there anything specific that needs to be done with GitLab here?

**Comment by timkoers** [comment]
Yes, I think it would fit the omnibus package if you would have the option to auto generate a certificate as well.
And maybe add a auto generate option when updating gitlab omnibus.

**Comment by stanhu** [comment]
Thanks for the suggestion, but I think generating SSL certs is beyond the scope of the omnibus-gitlab package. Many users may have their own SSL certs already or use wildcard certificates. Last I checked LetsEncrypt does not support the latter.
