### ISSUE TITLE
Unable to stop impersonating user when 2FA is required and not set up for said user

### ISSUE THREAD

**Issue by veloxy** [gitlabhq/gitlabhq#10074]
## Summary

When impersonating a user and 2FA is required, you are not able to stop impersonating that user using the "stop impersonating" button in the top right corner when that user has not yet set up their two factor auth. Instead, it just keeps redirecting you to the 2FA setup page.

## Steps to reproduce

Have 2FA required for all users and impersonate an account which has not setup 2FA yet.

![](https://sourcebox-screenshots.s3.eu-central-1.amazonaws.com/Screen%20Shot%202016-03-09%20at%2016.52.12.png)

## Expected behavior

Should stop impersonating the user.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
