### ISSUE TITLE
centos7 yum update errror.

### ISSUE THREAD

**Issue by kalsolio** [gitlabhq/gitlabhq#10070]
Updating   : gitlab-ce-8.5.3-ce.0.el7.x86_64                                                                                                          1/2 
Error unpacking rpm package gitlab-ce-8.5.3-ce.0.el7.x86_64
error: unpacking of archive failed on file /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gemojione-2.2.1/assets/images/1F482-1F3FF.png;56da86b8: cpio: read
gitlab-ce-8.5.0-ce.1.el7.x86_64 was supposed to be removed but is not!
  Verifying  : gitlab-ce-8.5.0-ce.1.el7.x86_64                                                                                                          1/2 
  Verifying  : gitlab-ce-8.5.3-ce.0.el7.x86_64

**Comment by kalsolio** [comment]
Resolving Dependencies
--> Running transaction check
---> Package gitlab-ce.x86_64 0:8.5.0-ce.1.el7 will be updated
---> Package gitlab-ce.x86_64 0:8.5.3-ce.0.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================
 Package                             Arch                             Version                                     Repository                           Size
============================================================================================================================================================
Updating:
 gitlab-ce                           x86_64                           8.5.3-ce.0.el7                              gitlab-ce                           162 M

Transaction Summary
============================================================================================================================================================
Upgrade  1 Package

Total download size: 162 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for gitlab-ce
gitlab-ce-8.5.3-ce.0.el7.x86_64.rpm                                                                                                  | 162 MB  00:06:40     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
gitlab preinstall: Backing up GitLab SQL database (excluding Git repositories, uploads)
I, [2016-03-05T02:41:28.798112 #13031]  INFO -- : ** [Raven] Raven 0.15.4 ready to catch errors
Dumping database ... 
Dumping PostgreSQL database gitlabhq_production ... [DONE]
done
Dumping repositories ...
[SKIPPED]
Dumping uploads ... 
[SKIPPED]
Dumping builds ... 
[SKIPPED]
Dumping artifacts ... 
[SKIPPED]
Dumping lfs objects ... 
[SKIPPED]
Creating backup archive: 1457163693_gitlab_backup.tar ... done
Uploading backup archive to remote storage  ... skipped
Deleting tmp directories ... done
done
Deleting old backups ... skipping
  Updating   : gitlab-ce-8.5.3-ce.0.el7.x86_64                                                                                                          1/2 
Error unpacking rpm package gitlab-ce-8.5.3-ce.0.el7.x86_64
error: unpacking of archive failed on file /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gemojione-2.2.1/assets/images/1F482-1F3FF.png;56da8d92: cpio: read
gitlab-ce-8.5.0-ce.1.el7.x86_64 was supposed to be removed but is not!
  Verifying  : gitlab-ce-8.5.0-ce.1.el7.x86_64                                                                                                          1/2 
  Verifying  : gitlab-ce-8.5.3-ce.0.el7.x86_64                                                                                                          2/2 

Failed:
  gitlab-ce.x86_64 0:8.5.0-ce.1.el7                                            gitlab-ce.x86_64 0:8.5.3-ce.0.el7                                           

Complete!

**Comment by davidCarlos** [comment]
+1
