### ISSUE TITLE
Profile avatar not shown while group avatars are working

### ISSUE THREAD

**Issue by RalfEggert** [gitlabhq/gitlabhq#10071]
I am running GitLab 8.5.4 and have a problem with the profile avatar. It neither works for an uploaded file nor for the gravatar for the email address of the profile. 

In contrast to this all group avatars work with no problems at all.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
