### ISSUE TITLE
Incorrect parameter's description [docs]

### ISSUE THREAD

**Issue by littleguga** [gitlabhq/gitlabhq#10076]
[In projects docs](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md) it's said that parameter name should be `visibility`, but I get 500 error if set this parameter. But if set it to `visibility_level` everything is ok.

**Comment by Razer6** [comment]
I'm not sure. I think `visability` was added by intention in https://github.com/gitlabhq/gitlabhq/commit/11797df1af483156b8cf11290c49c3f4d6089d99

**Comment by littleguga** [comment]
@Razer6 I tested with gitlab.com

test case:

``` 
$ curl -H "PRIVATE-TOKEN: [my-token-here]" "https://gitlab.com/api/v3/proj
ects/?visibility=0"
result: {"message":"500 Internal Server Error"}
```
```
$ curl -H "PRIVATE-TOKEN: [my-token-here]" "https://gitlab.com/api/v3/proj
ects/?visibility_level=0"
result: {json object with my projects}
```

**Comment by joshfng** [comment]
Hmm, we're searching for `params[:visibility]` https://github.com/gitlabhq/gitlabhq/blob/29ac9f64ea6d0a9e5a7615a9597c668dd129f5ae/lib/api/helpers.rb#L268

This was tested with a user and released long ago. I'll double check.

**Comment by joshfng** [comment]
I found the issue. You need to be using strings to determine the visibility for the project ie `public` `private` "https://gitlab.com/api/v3/projects/?visibility=public"

I'm not sure why the first part of the docs lists the integer values or when that part was added. Please see the `visibility` options for the call https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md#list-projects

**Comment by littleguga** [comment]
@joshfng Thank you very much for help and sorry for useless panic.
