### ISSUE TITLE
Rack::Attack not configurable in GitLab CE Omnibus

### ISSUE THREAD

**Issue by arun-instructor** [gitlabhq/gitlabhq#10083]
I am using GitLab as an API only through cURL. The issue is that all requests are coming from the same IP (my server) and Rack::Attack is blocking the requests after 10 of them.

I don't see a way to either turn off or alter the protected_paths in /etc/gitlab/gitlab.rb. If I try to alter /var/opt/gitlab/gitlab-rails/etc/rack_attack.rb directly it gets reset on reconfigure.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
