### ISSUE TITLE
Is there an API to get "global snippets"?

### ISSUE THREAD

**Issue by Jinjiang** [gitlabhq/gitlabhq#10084]
The "global snippets" means [this](https://github.com/gitlabhq/gitlabhq/issues/1644)

I only found the docs for [getting snippets of a certain project](http://doc.gitlab.com/ce/api/project_snippets.html) but no about global snippets.

Thanks.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
