### ISSUE TITLE
Project API getting avatars as binary

### ISSUE THREAD

**Issue by Bonscho** [gitlabhq/gitlabhq#10088]
Offering the avatar_url in the results of project API as described in the [API docs](http://doc.gitlab.com/ee/api/projects.html#list-projects) does not make sense, if there is no possibility to load data from this resource on non public projects. 

There should be an API method to get the avatar data as binary – maybe as Base64 encoded source plus some meta information like the MIME type.

**Comment by werksjan** [comment]
... Or the `avatar_url` should accept the `PRIVATE-TOKEN` header like the API does to make the data accessible without the overhead.

**Comment by Bonscho** [comment]
+1.

**Comment by Bonscho** [comment]
Anyone?

**Comment by Razer6** [comment]
I'll look into it in the coming days

**Comment by Bonscho** [comment]
Do you already had a look? This problem is a gamebreaker for us …

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
