### ISSUE TITLE
Configuring secondary LDAP server causes malfunctions

### ISSUE THREAD

**Issue by RevChas** [gitlabhq/gitlabhq#10081]
My company set up a new GitLab 7.10.4 server on a Centos 7 server from the Crntos YUM repos.

I first noticed a problem when trying to ass an SSH key. The sidekiq job that was supposed to add the key got stuck in the queue and never run.

When I tried to reconfigure and restart the GitLab instance, it would not connect properly to the socket at /var/opt/gitlab/gitlab-rails/sockets/gitlab.socket. Then I shutdown the GitLab server and removed the socket file and it wasn't recreated.

Working with one of your expert volunteers we tried to look at some configuration info and saw this at the start of the output:

`# gitlab-rake gitlab:env:info
rake aborted!
Devise::OmniAuth::StrategyNotFound: Could not find a strategy with name Ldapsecondary'. Please ensure it is required or explicitly set it using the :strategy_class option. `

I deleted the 2 LDAP servers that were configured in /etc/gitlab/gitlab.rb and restarted the GitLab instance with no problems. Apparently, configuring 2 LDAP servers causes problems.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
