### ISSUE TITLE
Displaying wrong name of user that started a discussion

### ISSUE THREAD

**Issue by carlospaulischen** [gitlabhq/gitlabhq#10080]
In a diff discussion the name of contributor that started it was incorrect. 

The name displayed was of the guy that did commit the file. 

But the picture is correct. As you can see on the image below.
![captura_de_tela](https://cloud.githubusercontent.com/assets/4353995/13704100/f12d42c0-e778-11e5-89ee-4dc6fabfb58a.png)

The user Eduardo Schroder did commit the file, but he didn't do the comment on diff.

**Comment by stanhu** [comment]
Do you have any idea how we might be able to reproduce this?

**Comment by carlospaulischen** [comment]
It seems that happens when the author of the merge request changes the source code, then answers the question done by another user on this snippet.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
