### ISSUE TITLE
project > services > jenkins CI throws 500 when testing (nothing in logs)

### ISSUE THREAD

**Issue by crucidal** [gitlabhq/gitlabhq#10095]
## Summary

When testing the jenkins ci without additional certificates configured in Gitlab, a message is returned:
"We tried to send a request to the provided URL but an error occurred: SSL_connect returned=1 errno=0 state=error: certificate verify failed.

With the proper root.ca in place the test still fails but returns an internal 500 error.
Nothing concerning the error can be found in the logs except for the message that an internal 500 page was served.
 
## Steps to reproduce

1. Insert pem in /embedded/ssl/certs/
2. create symoblic link.
3. restart gitlab
4. go to a project > services > jenkins CI > test settings > 500

note: the cursor shows as a "not allowed sign" when hovering over the test settings button in the last scenario

## Expected behavior

Either cerficate verify success or a message of what went wrong.

## Relevant logs and/or screenshots

this is the problem, we've got none. (tailed all the logs and we see nothing regarding the issue)

### Results of GitLab Application Check

Not showing all of the result output because it's simply too much:

Checking GitLab Shell ...

GitLab Shell version >= 2.6.10 ? ... OK (2.6.10)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
hooks directories in repos are links: ...

Running /opt/gitlab/embedded/service/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
        /var/opt/gitlab/git-data/repositories: OK
        /var/opt/gitlab/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.21
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking Reply by email ...

Reply by email is disabled in config/gitlab.yml

Checking Reply by email ... Finished

Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)
Server: ldapmain

Checking LDAP ... Finished
Checking GitLab ...
Git configured with autocrlf=input? ... yes
Database config exists? ... yes
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Uploads directory setup correctly? ... yes
Init script exists? ... skipped (omnibus-gitlab has no init script)
Init script up-to-date? ... skipped (omnibus-gitlab has no init script)
projects have namespace: ...

....

Redis version >= 2.8.0? ... yes
Ruby version >= 2.1.0 ? ... yes (2.1.8)
Your git bin path is "/opt/gitlab/embedded/bin/git"
Git version >= 1.7.10 ? ... yes (2.6.2)
Active users: 1256

Checking GitLab ... Finished

### Results of GitLab Environment Info

System information
System:
Current User:   git
Using RVM:      no
Ruby Version:   2.1.8p440
Gem Version:    2.5.1
Bundler Version:1.10.6
Rake Version:   10.5.0
Sidekiq Version:4.0.1

GitLab information
Version:        8.5.1-ee
Revision:       55338b6
Directory:      /opt/gitlab/embedded/service/gitlab-rails
DB Adapter:     postgresql
URL:            obfuscated
HTTP Clone URL: obfuscated
SSH Clone URL:  obfuscated
Using LDAP:     yes
Using Omniauth: no

GitLab Shell
Version:        2.6.10
Repositories:   /var/opt/gitlab/git-data/repositories
Hooks:          /opt/gitlab/embedded/service/gitlab-shell/hooks/
Git:            /opt/gitlab/embedded/bin/git

## Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
