### ISSUE TITLE
GitLab Merge Request didn't show full file diff

### ISSUE THREAD

**Issue by kalesastha** [gitlabhq/gitlabhq#10098]
Team,

In Gitlab 8.5.7 ( Community Edition ) , Merge Requests didn't show the list of files even i clicked " Reload with FullDiff option " . How to see the list of files which is modified .? 

Your suggestion would be highly appreciated .

Thanks,
Kaleeswaran N

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
