### ISSUE TITLE
 When updating from  6.7.5 to 6.9.0 in centos6.5 64 bit, merge_requests opened all return 500 

### ISSUE THREAD

**Issue by jacksonzhai** [gitlabhq/gitlabhq#10091]
Started GET "/android/ifengnews_android_phone/merge_requests?assignee_id=&label_name=&milestone_id=&scope=all&sort=newest&state=all" for 127.0.0.1 at 2016-03-18 18:29:19 +0800
Processing by Projects::MergeRequestsController#index as HTML
  Parameters: {"assignee_id"=>"", "label_name"=>"", "milestone_id"=>"", "scope"=>"all", "sort"=>"newest", "state"=>"all", "project_id"=>"android/ifengnews_android_phone"}
Completed 500 Internal Server Error in 1793ms

ActionView::Template::Error (invalid value for Float(): "1. \xE7\xBE\x8E\xE5\xA5\xB3\xE3\x80\x81\xE6\xAE\xB5\xE5\xAD\x90\xE3\x80\x81\xE8\x90\x8C\xE5\xAE\xA0\xE9\xA2\x91\xE9\x81\x93\xE4\xBD\xBF\xE7\x94\xA8gifview\xEF\xBC\x8C\xE5\x85\x81\xE8\xAE\xB8gif\xE5\x9B\xBE\xEF\xBC\x9B\n2. \xE8\xBF\x87\xE6\xBB\xA4\xE6\x8E\x89\xE4\xBD\x8E\xE7\xAB\xAF\xE6\x9C\xBA\xE7\x9A\x84gif\xE6\x96\xB0\xE9\x97\xBB\xEF\xBC\x9B\n3"):
    22:     - if merge_request.notes.any?
    23:       %span
    24:         %i.icon-comments
    25:         = merge_request.mr_and_commit_notes.count
    26:     - if merge_request.milestone_id?
    27:       %span
    28:         %i.icon-time
  app/models/merge_request_diff.rb:52:in `commits'
  app/models/merge_request.rb:37:in `commits'
  app/models/merge_request.rb:188:in `mr_and_commit_notes'
  app/views/projects/merge_requests/_merge_request.html.haml:25:in `_app_views_projects_merge_requests__merge_request_html_haml__4274127097517878046_48502060'
  app/views/projects/merge_requests/index.html.haml:66:in `_app_views_projects_merge_requests_index_html_haml___156216590846778204_101915860'
  app/controllers/application_controller.rb:59:in `set_current_user_for_thread'

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
