### ISSUE TITLE
Can't download the zip files

### ISSUE THREAD

**Issue by geekwolf** [gitlabhq/gitlabhq#10097]
1.  gitlab-version: 8.5.1
2.  when i visit the repo download zip or tar.gz or tar :
http://git.mle.com/Lordly/mlz/repository/archive.zip?ref=master

{"RepoPath":"/data/gitlab-8.5.1-0/apps/gitlab/repositories/Lordly/mlz.git","ArchivePrefix":"mlz-master-d800db728ec54cfa653b83ff4e43175177938a75","ArchivePath":"/data/gitlab-8.5.1-0/apps/gitlab/htdocs/shared/cache/archive/mlz.git/mlz-master-d800db728ec54cfa653b83ff4e43175177938a75.zip","CommitId":"d800db728ec54cfa653b83ff4e43175177938a75"}
Has anyone encountered  this problem ?

**Comment by grzesiek** [comment]
@geekwolf This may happen if you do not use GitLab Workhorse. We suggest upgrading GitLab to the new version. If using workhorse does not resolve this problem for you, feel free to resubmit this issue to a tracker we use at gitlab.com/gitlab-org/gitlab-ce/issues. Thanks!

**Comment by geekwolf** [comment]
gitlab-version:8.2.0 test ok! but 8.5.1 not

**Comment by geekwolf** [comment]
@grzesiek  gitlab-version:8.2.0 test ok! but 8.5.1 not

**Comment by chrismccoy** [comment]
i've had this issue, clear your browsers cache, and try the download link again.

**Comment by geekwolf** [comment]
@chrismccoy  the same results

**Comment by chrismccoy** [comment]
did you update your gitlab init script and the apache/nginx config? they were both updated im pretty sure

**Comment by geekwolf** [comment]
@chrismccoy Can you send me  the latest configuration？
