### ISSUE TITLE
Markdown for snippets not working on Wiki pages

### ISSUE THREAD

**Issue by shanept** [gitlabhq/gitlabhq#10096]
I am on GitLab 8.5.3. When creating/editing a wiki page, I am trying to reference snippet 4. Your documentation tells me that simply $4 will suffice, however it does not link, it stays as the literal text $4.

**Comment by gamb** [comment]
Also getting that on 8.6.5

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
