### ISSUE TITLE
How to set CAS login without provide email and just provide username

### ISSUE THREAD

**Issue by xkeyideal** [gitlabhq/gitlabhq#10094]
How to set CAS login without provide email and just provide username?

Now the gitlab must provide username and email if we want to use cas loign

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
