### ISSUE TITLE
Configure user permissions for internal projects

### ISSUE THREAD

**Issue by LukasVice** [gitlabhq/gitlabhq#10103]
It would be great if you could configure the user permissions for internal projects.
We would like all users to have guest permissions and only users who are assigned to a group or a project can see/pull the code.
The external user feature from the latest update is very useful though.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
