### ISSUE TITLE
http push get 500 error

### ISSUE THREAD

**Issue by moueimei** [gitlabhq/gitlabhq#10101]
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
POST git-receive-pack (2229284 bytes)

fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly

error: RPC failed; result=22, HTTP code = 500

Pushing to http://git.zzz.com/framework/play.git
Everything up-to-date

Completed with errors, see above.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
