### ISSUE TITLE
GitLab Merge Request didn't show full file diff

### ISSUE THREAD

**Issue by Kaleesastha** [gitlabhq/gitlabhq#10104]
Team,

       In Gitlab 8.5.7 ( Community Edition ) , Merge Requests didn't show the list of files even i clicked " Reload with FullDiff option " . How to see the list of files which is modifed .? 
       Your suggestion would be highly appreciated .

Thanks,
Kaleeswaran N

**Comment by axilleas** [comment]
Please don't open duplicate issues https://github.com/gitlabhq/gitlabhq/issues/10098
