### ISSUE TITLE
Weird aspect ratio when uploading a 9:16 profile picture image

### ISSUE THREAD

**Issue by timkoers** [gitlabhq/gitlabhq#10105]
Today I felt like changing my profile picture as it will look a bit more professional. The only picture that I had was a picture with a resolution of 1162x2052. 

I set that picture as profile image and the picture gets scaled in a certain way that the whole aspect ratio is messed up. Maybe their should be some kind of cropping mechanism such as the ones Google and Whatsapp web are using.

GitLab version 8.6.1

**Comment by stanhu** [comment]
Yes, cropping and scaling will be added in GitLab 8.7:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3270
