### ISSUE TITLE
Error 500 on gitlab-ce-8.0.4-ce.1.el6.x86_64

### ISSUE THREAD

**Issue by yuexiwei** [gitlabhq/gitlabhq#10106]
OS: CentOS release 6.6 (Final) X86_64
Gitlab: gitlab-ce-8.0.4-ce.1.el6.x86_64

Error 500 got when I visit the gitlab homepage, with my server power off unexpected.
Also only one repo can't be pull or push.

**/var/log/gitlab/nginx/gitlab_error.log**
2016/03/25 11:48:49 [error] 11176#0: *52 connect() to unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.25.137, server: 192.168.25.146, request: "GET / HTTP/1.1", upstream: "http://unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket:/", host: "192.168.25.146:81"
2016/03/25 11:49:25 [error] 11176#0: *52 connect() to unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.25.137, server: 192.168.25.146, request: "GET / HTTP/1.1", upstream: "http://unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket:/", host: "192.168.25.146:81"
2016/03/25 13:09:11 [error] 26295#0: *1 connect() to unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.25.137, server: 192.168.25.146, request: "GET / HTTP/1.1", upstream: "http://unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket:/", host: "192.168.25.146:81"
2016/03/25 13:09:15 [error] 26295#0: *1 connect() to unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.25.137, server: 192.168.25.146, request: "GET / HTTP/1.1", upstream: "http://unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket:/", host: "192.168.25.146:81"

**/var/log/gitlab/gitlab-rails/production.log**

Started GET "/Java/***.git/info/refs?service=git-upload-pack" for 192.168.25.146 at 2016-03-24 09:16:45 +0800
...skipping...
  app/views/shared/projects/_project.html.haml:10:in `block (2 levels) in _app_views_shared_projects__project_html_haml___1828905730670935342_53194620'
  app/views/shared/projects/_project.html.haml:7:in `block in _app_views_shared_projects__project_html_haml___1828905730670935342_53194620'
  app/views/shared/projects/_project.html.haml:6:in `_app_views_shared_projects__project_html_haml___1828905730670935342_53194620'
  app/views/shared/projects/_list.html.haml:8:in `block in _app_views_shared_projects__list_html_haml___4318969241085700057_45037360'
  app/views/shared/projects/_list.html.haml:6:in `_app_views_shared_projects__list_html_haml___4318969241085700057_45037360'
  app/views/dashboard/projects/_projects.html.haml:10:in `_app_views_dashboard_projects__projects_html_haml___1042628836233059936_45856540'
  app/views/dashboard/projects/index.html.haml:14:in `_app_views_dashboard_projects_index_html_haml__876340444275158582_44281700'
  app/controllers/dashboard/projects_controller.rb:9:in `index'
  app/controllers/root_controller.rb:13:in `index'

Started GET "/" for 127.0.0.1 at 2016-03-25 13:28:20 +0800
Processing by RootController#index as HTML
Read fragment views/groups/23-20151013090931646462000/projects/19-20160325033352452439000/root/index/v2.1/882ea452743d178b81d681e93a7f77ca (0.2ms)
Read fragment views/groups/21-20151013091117605501000/projects/15-20160325033130583717000/root/index/v2.1/882ea452743d178b81d681e93a7f77ca (0.1ms)
Read fragment views/groups/40-20151110032104775817000/projects/17-20160324092217614170000/root/index/v2.1/882ea452743d178b81d681e93a7f77ca (0.1ms)
Read fragment views/groups/21-20151013091117605501000/projects/9-20160324014839482841000/root/index/v2.1/882ea452743d178b81d681e93a7f77ca (0.1ms)
Completed 500 Internal Server Error in 35ms (ActiveRecord: 5.8ms)

ActionView::Template::Error (Object not found - failed to find pack entry (3c43a27e0f9dcf185fcfac19cbc4b5dd43252bb7)):
     7:     = link_to project_path(project), class: dom_class(project) do
     8:       - if avatar
     9:         .dash-project-avatar
    10:           = project_icon(project, alt: '', class: 'avatar project-avatar s46')
    11:       %span.project-full-name
    12:         %span.namespace-name
    13:           - if project.namespace
  app/models/repository.rb:16:in `new'
  app/models/repository.rb:16:in `initialize'
  app/models/project.rb:268:in `new'
  app/models/project.rb:268:in `repository'
  app/models/project.rb:454:in `avatar_in_git'
  app/models/project.rb:463:in `avatar_url'
  app/helpers/application_helper.rb:43:in `project_icon'
  app/views/shared/projects/_project.html.haml:10:in `block (2 levels) in _app_views_shared_projects__project_html_haml___1828905730670935342_115619800'
  app/views/shared/projects/_project.html.haml:7:in `block in _app_views_shared_projects__project_html_haml___1828905730670935342_115619800'
  app/views/shared/projects/_project.html.haml:6:in `_app_views_shared_projects__project_html_haml___1828905730670935342_115619800'
  app/views/shared/projects/_list.html.haml:8:in `block in _app_views_shared_projects__list_html_haml___4318969241085700057_115868480'
  app/views/shared/projects/_list.html.haml:6:in `_app_views_shared_projects__list_html_haml___4318969241085700057_115868480'
  app/views/dashboard/projects/_projects.html.haml:10:in `_app_views_dashboard_projects__projects_html_haml___1042628836233059936_115978340'
  app/views/dashboard/projects/index.html.haml:14:in `_app_views_dashboard_projects_index_html_haml__876340444275158582_116201520'
  app/controllers/dashboard/projects_controller.rb:9:in `index'
  app/controllers/root_controller.rb:13:in `index'

(END)

**Comment by yuexiwei** [comment]
I also tried to reinstall gitlab-ce-8.6.0-ce.0.el7.x86_64 on Centos 7 X86_64, the same issues happened as before after I copy the old gitlab server **/var/opt/gitlab/git-data/repositories/** directory to the current brand new server and run the command **gitlab-rake gitlab:import:repos**.

tks.

**Comment by yuexiwei** [comment]
**This is the new server check error log**

**gitlab-rake gitlab:check --trace
**
Java / lsp ... rake aborted!
Rugged::OdbError: Failed to inflate loose object.
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:71:in `target'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:71:in `block in branch_count'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:69:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:69:in `count'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:69:in `branch_count'
/opt/gitlab/embedded/service/gitlab-rails/app/models/repository.rb:75:in `block in has_visible_content?'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:299:in `block in fetch'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:585:in `block in save_block_result_to_cache'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:547:in `block in instrument'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:547:in `instrument'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:584:in `save_block_result_to_cache'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:299:in `fetch'
/opt/gitlab/embedded/service/gitlab-rails/lib/repository_cache.rb:19:in `fetch'
/opt/gitlab/embedded/service/gitlab-rails/app/models/repository.rb:74:in `has_visible_content?'
/opt/gitlab/embedded/service/gitlab-rails/app/models/project.rb:679:in `empty_repo?'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:468:in `block in check_repos_hooks_directory_is_link'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `block in find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:50:in `find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/querying.rb:9:in `find_each'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:464:in `check_repos_hooks_directory_is_link'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:348:in `block (3 levels) in <top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/gitlab/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/opt/gitlab/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `load'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => gitlab:check => gitlab:gitlab_shell:check
[root@gitlab202 ~]#

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
