### ISSUE TITLE
Wrong asset links in CSS file

### ISSUE THREAD

**Issue by Hoeze** [gitlabhq/gitlabhq#10117]
Hi,
yesterday I set up your gitlab/gitlab-ce docker container with a relative url:

> external_url 'https://xxxxxx/gitlab/'

Until now it was working great, but suddenly there are no more icons.
The css files' links are OK:

> https://xxxxxx/gitlab/assets/application-xxxx.css

But the asset links in the css files are wrong:

> /assets/jquery-ui/ui-bg_glass_xxxx

should be:

> /gitlab/assets/jquery-ui/ui-bg_glass_xxxx

I ran gitlab-ctl reconfigure multiple times, i also created a new instance with my config, but it did not help to fix the asset links.

Gitlab version: 8.6.4

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
