### ISSUE TITLE
All groups are now public

### ISSUE THREAD

**Issue by offlinehoster** [gitlabhq/gitlabhq#10113]
This is an incredible feature, i have to click 174 groups by hand to set them "back" to private or internal?

SRSLY?

Running newest GitLab 8.6.2 and not proud of this new default setting!

**Comment by Razer6** [comment]
@offlinehoster Before 8.6 all groups were public by default. With 8.6 groups have the same visibility settings as projects (public/internal/private).

**Comment by offlinehoster** [comment]
I cant remember that the groups where public visible before....even if the projects have been private or internal?

**Comment by Razer6** [comment]
Yes. The group names were leaking through the `/explore` page for anonymous users although a group only contained private projects.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
