### ISSUE TITLE
URLs in wiki links not getting escaped properly

### ISSUE THREAD

**Issue by nfirvine** [gitlabhq/gitlabhq#10112]
In a markdown wiki document, I had this:

    ![daemon: octets](fig/git=d79bd7c,n=600/octets-daemon.png)

Attempting to inline an image. The link looked fine but yielded a 404. (Gollum itself handles this fine.)

As a workaround, I removed the URL-escapable characters:

    ![daemon: octets](fig/git-d79bd7c_n-600/octets-daemon.png)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
