### ISSUE TITLE
support nested (chapters) like wiki pages

### ISSUE THREAD

**Issue by domnulnopcea** [gitlabhq/gitlabhq#10114]
It would be great to group pages in a parent-child relationship like here for example https://confluence.atlassian.com/jira/browsing-a-project-185729593.html

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
