### ISSUE TITLE
Shibboleth Omniauth not redirecting correctly to GitLab

### ISSUE THREAD

**Issue by coonsmatthew** [gitlabhq/gitlabhq#10119]
Hello, 

I'm having issues setting up Shibboleth as an Omniauth provider in GitLab. 

I've successfully followed the documentation on how to set up Shibboleth with GitLab here: 
- https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc//integration/shibboleth.md
- http://doc.gitlab.com/ce/integration/shibboleth.html

There is a "sign in with shibboleth" button on the login page now, and if I have a saved cookie from my local SP, I am logged into Gitlab without issues. However, if I do not have a cached cookie, things go wrong. 

Here's what happens: 

1. Click on "Sign in with Shibboleth" button
2. I get redirected to my local SP and enter valid username/password combination
3. I get directed back to a page on GitLab `https://server.domain.com/Shibboleth.sso/SAML2/POST` This page provides me with a 404, "the pate you're looking for could not be found" error. 

This seems to be related to how gitlab receives the response from the SP? I've got the webserver running on Apache 2.2 as well as following Gitlab suggested apache configurations for a instance using Shibboleth. 

I'm running version 8.6.1, and the documentation that I was using for the webserver set up seemed to have been created for version 8.2....but I would not think it would be that much different? Perhaps I am incorrect? 

I viewed the web error logs and there is no page not found error in the logs, suggesting that the GitLab application is displaying a 404 error incorrectly...

Whatever help that anybody can provide would be awesome. 

I also tailed the gitlab error logs and did not see any obvious errors. 

Thank You.

**Comment by coonsmatthew** [comment]
@jacobvosmaer Any ideas? It seems as if Gitlab is not properly handling the redirection from my SP once I authenticate.

**Comment by jacobvosmaer** [comment]
@coonsmatthew I don't know much about shibboleth and I am also not sure this is the best place to ask for help. Have you looked at https://about.gitlab.com/getting-help/ ?

**Comment by coonsmatthew** [comment]
Thank you.
