### ISSUE TITLE
When deleting a project fork the red banner tellling the project is in queue for deletion may appears in the original project

### ISSUE THREAD

**Issue by invenis-paris** [gitlabhq/gitlabhq#10111]
I have forked a project to do some tests, then I have deleted this forked. It tells me that the project was in queue for deleting it (ok good).
This banner appears when I was on this fork project page (still good).
But then, I have visited the original project page and the same banner was displayed (FEAR !).
Refreshing the page make it disappears (sometimes) but some seconds after I have return to that page and the banner was here again (FEAR and I hoped that the original project would not be deleted with the fork!).

After some times only the fork was deleted (fortunately) but it scared me.

Version:	8.6.0-rc5
Revision:	939f306

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
