### ISSUE TITLE
Feature Request: Encrypted strings for gitlab-ci.yml

### ISSUE THREAD

**Issue by gregf** [gitlabhq/gitlabhq#10124]
It would be nice if I could encryption a string in my gitlab-ci.yml to be exported as env variable during runs. I want to automate my packer deployments to the docker registry, but I need a secure way of passing credentials.

**Comment by grzesiek** [comment]
@gregf What about a secure variables we currently have in GitLab? If this doesn't solve your problem, please resubmit this feature proposal in GitLab issue tracker at gitlab.com/gitlab-org/gitlab-ce/issues (we do not user GitHub tracker now).

**Comment by gregf** [comment]
I couldn't find any information about them in the docs. Could you possibly link me? I'm sure this will be fine.

**Comment by gregf** [comment]
Figured it out, Gitlab is amazing. Every time I think a feature is missing I find out it exists. Thanks for the help!

**Comment by grzesiek** [comment]
@gregf It is great you like GitLab! Thanks for your support.
