### ISSUE TITLE
No spaces in merge request changelog preview

### ISSUE THREAD

**Issue by leemalmac** [gitlabhq/gitlabhq#10126]
So, when I look a changelog in a merge request there is no white spaces in the preview, but they exist in code.

**Comment by rymai** [comment]
Hi @leemalmac! Thanks for the report, this is a bug in GitLab 8.7.0-rc2, this is fixed in 8.7.0-rc3 which should be deployed today to GitLab.com.

**Comment by rymai** [comment]
I'm speaking about the diff, but that might also fix an issue in the preview (I wasn't aware of this issue).

**Comment by leemalmac** [comment]
Great! It looks awesome again. Thanks!
