### ISSUE TITLE
SignIn form does not trim "Username of email field"

### ISSUE THREAD

**Issue by sjlamekhov** [gitlabhq/gitlabhq#10121]
SignIn form at /users/sign_in does not treat "somebody@email.com " and "somebody@email.com" in the same way, but "Create user account" at the same page does.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
