### ISSUE TITLE
Gitlab API - Can't lookup milestones by their iid anymore.

### ISSUE THREAD

**Issue by yasserhussain1110** [gitlabhq/gitlabhq#10122]
Earlier, for the **`Gitlab API`** I would make a request like - **GET** `/projects/:id/milestones?iid=42` and I would get **only** the issue with *iid* of 42.  But now when I make the **same** request I get *all* the `milestones` for the project and  I have to loop through the milestones, to get to the milestone I really wanted.   

Please `confirm` that this is an issue.

**Comment by Razer6** [comment]
@yasserhussain1110 I think I found the issue. However, are you sure this ever worked?

**Comment by yasserhussain1110** [comment]
@Razer6 Yeah I think it worked earlier. I could be wrong about that though. My mind could be playing tricks with me.
