### ISSUE TITLE
Repository empty after push

### ISSUE THREAD

**Issue by kerberjg** [gitlabhq/gitlabhq#10127]
Seems like it's happening again, this time with a clean install of 8.6.4

I can clone the repo from both SSH and HTTP, the files show properly in the git-data folder, but the web UI of Gitlab claims the repo is empty. It happens to every new project I create on this instance on Gitlab.

EDIT:
Software versions:
Ubuntu Server 14.04 LTS
GitLab 8.6.4
GitLab Shell 2.6.12
GitLab API v3
Git 2.7.4
Ruby 2.1.8p440
Rails 4.2.5.2
PostgreSQL 9.2.15

**Comment by kerberjg** [comment]
This is related to two repos, the first one suddenly "fixed" itself after a few days and several reconfigures unrelated to git itself (nginx and SMTP), while the second does not seem to react to any of these.

**Comment by kerberjg** [comment]
UPDATE: the broken repository was fixed after an update to 8.6.5, but when creating a new repo and pushing to it, the problem repeats

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
