### ISSUE TITLE
problem with latest docker image

### ISSUE THREAD

**Issue by denouche** [gitlabhq/gitlabhq#10128]
Hi!

I just wanted to update my docker image today, based on https://hub.docker.com/r/gitlab/gitlab-ce/tags/

And as the docker tags page show, the latest tag should be the same that the 8.3.7-ce.0.
But after the docker pull, I realized that the lastest tag does not refer to the latest stable version, but to the latest RC version.

Take a look:
```bash
$ docker images | grep gitlab
gitlab/gitlab-ce                     8.7.0-rc3.ce.0      799d23f44dc3        23 hours ago        1.077 GB
gitlab/gitlab-ce                     latest              799d23f44dc3        23 hours ago        1.077 GB
gitlab/gitlab-ce                     rc                  799d23f44dc3        23 hours ago        1.077 GB
gitlab/gitlab-ce                     8.3.7-ce.0          2b5e468453e4        34 hours ago        1.336 GB
```

Is it normal ?
Thanks

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
