### ISSUE TITLE
cool urls don't change, but https://gitlab.com/profile/keys/new did

### ISSUE THREAD

**Issue by joeyh** [gitlabhq/gitlabhq#10138]
The git-annex webapp points users to https://gitlab.com/profile/keys/new to add a ssh key. Unfortunately, this url has stopped working at some point.

While I've updated the git-annex webapp to use the new url, https://gitlab.com/profile/keys, this doesn't help with versions of the webapp shipped in linux distros, already deployed etc.

Could you please make the old url redirect to the new url so that git-annex's gitlab repository adding UI will work again?

**Comment by rymai** [comment]
Thanks @joeyh, you're right, this should be fixed!

**Comment by rymai** [comment]
I submitted a fix at https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3717.

**Comment by rymai** [comment]
@joeyh The fix has been merged, thanks!
