### ISSUE TITLE
Cannot start the gitlab server

### ISSUE THREAD

**Issue by yasserhussain1110** [gitlabhq/gitlabhq#10135]
When I run command `./run`, I get the following error - 

```sh
 16:22:59 rails-background-jobs.1 | bundler: command not found: sidekiq
 16:22:59 rails-web.1             | bundler: command not found: unicorn_rails
 16:22:59 rails-background-jobs.1 | Install missing gem executables with `bundle install`
 16:22:59 rails-web.1             | Install missing gem executables with `bundle install`
```

Running `bundle install` gives - 
```sh
Could not locate Gemfile or .bundle/ directory
```

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
