### ISSUE TITLE
How to restrict public user pages

### ISSUE THREAD

**Issue by cloud-rocket** [gitlabhq/gitlabhq#10130]
Is there any way to restrict public access to Gitlab user pages  (i.e.  u/username) ?

It is a serious flow that all users are publicly visible....

Thanks

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
