### ISSUE TITLE
Docker Gitlab can't clone project over http (13: Permission Denied)

### ISSUE THREAD

**Issue by fehergeri13** [gitlabhq/gitlabhq#10137]
I install Gitlab to my cloud server, I create a simple `foo` project with a Readme file initialized, and I try to clone it via http, and I get this:

```
$ git clone http://<-my--virtual-machine-ip->:8090/root/foo.git
Cloning into 'foo'...
fatal: unable to access 'http://<-my--virtual-machine-ip->:8090/root/foo.git/': transfer closed with 310 bytes remaining to read
```

```
==> /var/log/gitlab/nginx/gitlab_error.log <==
2016/04/13 14:25:36 [alert] 243#0: *62 readv() failed (13: Permission denied) while reading upstream, client: <-my--local-machine-ip->, server: <-my--virtual-machine-ip->, request: "GET /root/foo.git/info/refs?service=git-upload-pack HTTP/1.1", upstream: "http://unix:/var/opt/gitlab/gitlabworkhorse/socket:/root/foo.git/info/refs?service=git-upload-pack", host: "<-my--virtual-machine-ip->:8090"
```

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
