### ISSUE TITLE
Close issue on commit do not work anymore

### ISSUE THREAD

**Issue by DjLeChuck** [gitlabhq/gitlabhq#10134]
It worked last week. I have no custom issue closing pattern.

Now, when I want to close an issue with a commit, the issue is updated with `mentioned in commit a3b5aa6d` but do not close.

Version : GitLab Community Edition 8.6.5 e63f120

**Comment by connorshea** [comment]
Have you tried this with 8.7.0?

**Comment by DjLeChuck** [comment]
It worked again a few days later: https://gitlab.com/gitlab-org/gitlab-ce/issues/15171#note_4820921
