### ISSUE TITLE
Get project info without using the API

### ISSUE THREAD

**Issue by alecpl** [gitlabhq/gitlabhq#10131]
Is it at all possible to get (public) project information without a need to have an account in gitlab? I'd like to allow composer users to install packages without gitlab's API use. See https://github.com/composer/composer/issues/4744

**Comment by alecpl** [comment]
The information we need is at least is http_url_to_repo, ssh_url_to_repo, default_branch, web_url.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
