### ISSUE TITLE
New project leads to 404 page. Cannot delete project.

### ISSUE THREAD

**Issue by IniZio** [gitlabhq/gitlabhq#10139]
I made a new project under group. However the project only redirects to 404 telling me that the project does not exist. Also I cannot delete the project.

**Comment by connorshea** [comment]
Was there a project of the same name that had recently been deleted?

**Comment by IniZio** [comment]
It is accessible and can be deleted now, but that was a new project with new name.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
