### ISSUE TITLE
Merge request informations are not always correct

### ISSUE THREAD

**Issue by smeeckaert** [gitlabhq/gitlabhq#10146]
Version : GitLab Community Edition 8.7.0-rc1 152b582

There is a bug that is really annoying, sometimes when changing between two merge requests, you are left with the "Accept merge" container of an other merge request.

A simple way to see the bug, is to go to a merge request, put the WIP tag and change to an other merge request, you will have the message that the second merge request is in WIP even though it was the first one, when you refresh the page everything works normally again.

The bug is even more problematic when you, for instance, remove the WIP tag from a merge request, and jump to another merge request, if you try to merge the second one it will actually merge the first one because the "Accept merge" block is still somehow related to the former MR.

**Comment by rymai** [comment]
Thanks for the report @smeeckaert, this issue was [fixed in 8.7.0-rc2](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3582), sorry about that!
