### ISSUE TITLE
gitlab 8.7 wrong version check

### ISSUE THREAD

**Issue by colttt** [gitlabhq/gitlabhq#10145]
Hello, 
I installed gitlab version  8.7.0-rc5 rev 83e7e5c
when i run a check it said i need a newer redis server but i've the newest one:
```
sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
[...]
Redis version >= 2.8.0? ... no
  Try fixing it:
  Update your redis server to a version >= 2.8.0
  For more information see:
  gitlab-public-wiki/wiki/Trouble-Shooting-Guide in section sidekiq
  Please fix the error above and rerun the checks.
Ruby version >= 2.1.0 ? ... yes (2.1.2)
Your git bin path is "/usr/bin/git"
Git version >= 2.7.3 ? ... yes (2.8.1)

redis-server --version
Redis server v=2.8.23 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=bc139fdb5003672d
```

an other issue is that if I run info he said I need gitlab-shell 2.7.2 but it dont exist!
```
sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production
WARNING: This version of GitLab depends on gitlab-shell 2.7.2, but you're running 2.7.0. Please update gitlab-shell.
[...]
sudo -u git -H git checkout v2.7.2
error: pathspec 'v2.7.2' did not match any file(s) known to git.
```

**Comment by stanhu** [comment]
What happens if you run `redis-cli --version`?

I just pushed the latest tags for gitlab-shell. For future reference, I suggest pulling from the main repo:

https://gitlab.com/gitlab-org/gitlab-shell

**Comment by colttt** [comment]
ok, i forgott to copy the new version redis-cli to the right place, now its works correct:
```
before:
redis-cli --version
redis-cli 2.2.12

after;
redis-cli --version
redis-cli 2.8.23
```

i try to upgrade the gitlab-shell described in the doc (sorry I'm not a git expert):
```
cd /home/git/gitlab-shell
sudo -u git -H git fetch --all
sudo -u git -H git checkout v2.7.2
error: pathspec 'v2.7.2' did not match any file(s) known to git.
```

**Comment by stanhu** [comment]
Sounds like the `git fetch` did not pull down the tags.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
