### ISSUE TITLE
reCAPTCHA not Work on SSL Site

### ISSUE THREAD

**Issue by first087** [gitlabhq/gitlabhq#10144]
I config my **http** site. It not problem.

![http site](https://gist.githubusercontent.com/first087/4cd35d1244e4b54fbb49ae4c850717f2/raw/2b3d1a73a326696f4174ee00330940c66b3382e2/GitLab-reCAPTCHA-http.png)

But, my **https** site found this problem.
![http site](https://gist.githubusercontent.com/first087/4cd35d1244e4b54fbb49ae4c850717f2/raw/2b3d1a73a326696f4174ee00330940c66b3382e2/GitLab-reCAPTCHA-https.png)

I known GitLab use reCAPTCHA helper from https://github.com/ambethia/recaptcha

For enable SSL, must set `config.use_ssl_by_default` is `true`
_Ref1._ https://github.com/ambethia/recaptcha#recaptcha_tags
_Ref2._ https://github.com/ambethia/recaptcha/blob/master/test/helper.rb#L20

For GitLab, I not found this config.

https://github.com/gitlabhq/gitlabhq/blob/master/lib/gitlab/recaptcha.rb#L8

Please fix it.

**Comment by stanhu** [comment]
HTTPS and reCAPTCHA works fine on GitLab.com. Are you sure your system clock is in sync?

https://github.com/ambethia/recaptcha/blob/master/README.md#recaptcha_tags

**Comment by first087** [comment]
OK. I re-config hwclock. It work!!. Thank.

```
# hwclock --systohc --localtime
```

http://docs.slackware.com/howtos:hardware:syncing_hardware_clock_and_system_local_time
