### ISSUE TITLE
Issue while Merging in GitLab

### ISSUE THREAD

**Issue by Petchimuthu** [gitlabhq/gitlabhq#10142]
We are using the GitLab 8.6.4 version.

While submitting the merge request from GitLab the following message appears :

This merge request contains merge conflicts

Please resolve these conflicts or ask someone with write access to this repository to merge this request manually.

But when we try to merge the same in local via command it merges without any conflicts.

Please help me to find out the issue.

Thanks,
Muthu.

**Comment by Petchimuthu** [comment]
Any update?

We are updated to 8.7.2. Still the issue not fixed.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
