### ISSUE TITLE
Multi file snippets

### ISSUE THREAD

**Issue by sergeifilippov** [gitlabhq/gitlabhq#10141]
It would be fantastic go be able to have snippets that could consist of multiple files.

Similar to  when you make a [Github Gist](https://gist.github.com).

## Current

Snippet entry view can only accept a single file with a single content area.

## Proposed

Snippet entry area has a `Add Another File` action button.

Clicking said button, shows another entry form to accept filename (for highlights and reference) and a content texture element.

@stanhu Could you review and add the `feature proposal` label if you think this is an idea worth doing. 

Much appreciated and keep up the great work!

**Comment by arif-ali** [comment]
👍

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
