### ISSUE TITLE
Gitlab.com deployment is down for deployment

### ISSUE THREAD

**Issue by loint** [gitlabhq/gitlabhq#10148]
Hi everyone,

Gitlab (http://gitlab.com) is deploying. Should we keep it with zero downtime or just 1-2s, I see the deployment is slow ? 
Can not access service :( 

<img width="1151" alt="screen shot 2016-04-20 at 5 45 36 pm" src="https://cloud.githubusercontent.com/assets/5317864/14672086/cc9b4558-071f-11e6-8a9f-3dc8269db745.png">

**Comment by Razer6** [comment]
Deployment finished. https://twitter.com/gitlabstatus provides the status of deployment.
