### ISSUE TITLE
Is gitlab vulnerable to a host header attack?

### ISSUE THREAD

**Issue by thestick613** [gitlabhq/gitlabhq#10143]
```
GET /dashboard/ HTTP/1.1
Host: 1.2.3.4
X-Forwarded-Host: spoofed.com:443
```
will return 

```
HTTP/1.1 302 Found
Server: nginx
Date: Thu, 17 Apr 2016 13:17:40 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 302 Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Location: http://spoofed.com:443/users/sign_in
Cache-Control: no-cache
Set-Cookie: _gitlab_session=xxxxxxxxxxxxxxxxxxxxxx; path=/; expires=xxxxxx; HttpOnly X-Request-Id: xxxxx
X-Runtime: 0.010452
```

Is this right? I'm using gitlab version 8.2.3-ce.0.

**Comment by connorshea** [comment]
Would you mind sending this to security@gitlab.com?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
