### ISSUE TITLE
Redis namespace support option

### ISSUE THREAD

**Issue by virtuman** [gitlabhq/gitlabhq#10152]
Since open source redis doesn't support the database name (instead it accesses them by number) it would be nice to utilize namespace feature or at least the database number within redis. 

Most of the applications don't explicitly specify DB number and if you have 1 shared instance of REDIS a lot of your applications will tend to use DB0 as it is the default DB number.

Current Redis implementation already supports namespaces. But since Redis doesn't really penalize for additional levels of enclosure of namespaces (except for extra characters in key names), and to allow for a little bit of flexibility of what is mentioned above - all that needs to be done is add a prefix to all redis key commands that is configurable via gitlab options.

**Current naming of redis keys:**
```
db0:
  cache:
     ..
  resque:
     ..
  session:
     ..
```

**Proposed change:**
1. add configurable option for redis key prefix, with empty default value (for backwards compatibility)
2. add the value of #1 as prefix to all keys (or commands that handle redis communications):
```
db0:
  **namespace:**
      cache:
         ..
      resque:
         ..
      session:
         ..
```

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
