### ISSUE TITLE
Project limit

### ISSUE THREAD

**Issue by Arvi89** [gitlabhq/gitlabhq#10151]
Hello,

I just downloaded the last docker image for gitlab-ce (v8.6.7), and the project limit is 10. I tried to change in the settings, 0, 50, 100, even restarted the container, but it always shows "You can create up to 10 projects."

**Comment by david10sing** [comment]
Settings will change the default projects limit for new user. If you want to change your projects limit, go to admin > users > click on the edit button next to the user you want to edit, scroll down and you will see Projects Limit under the Access section. Cheers

**Comment by axilleas** [comment]
Like @david10sing wrote, after the change, it will be available to new users. For existing ones you'll have to use the Admin area.

**Comment by Arvi89** [comment]
OK, thank you :)
(but that would be awesome if that were automatic for existing users too :p)
