### ISSUE TITLE
[feature request] Graphical option in compare view for ignoring whitespaces (?w=1)

### ISSUE THREAD

**Issue by hmeiser** [gitlabhq/gitlabhq#10150]
Hi,
if you are in the in the compare view, you can add ?w=1 to the URL, which forces gitlab to ignore all whitespace by comparing different files. That works pretty well. Unfortunately it takes a lot of time to manipulate the URL every time you made a comparison between files. Could you please add a graphical option like a dropdown/checkbox/button for switching between ignoring whitespaces and evaluating whitespaces in the current view? That would be excellent.

HM

**Comment by stanhu** [comment]
Yes, I believe this will be available in GitLab 8.7 due out in a day!

**Comment by hmeiser** [comment]
Hi,
I have taken a look into changelog (https://github.com/gitlabhq/gitlabhq/blob/master/CHANGELOG) and I have found no really entry that fits this request. Does this option maybe belongs to one of these changes here?

- Implement 'Groups View' as an option for dashboard preferences !3379 (Elias W.)
- Diff design updates (colors, button styles, etc)

**Comment by stanhu** [comment]
Sorry, it looks like this is still in progress!

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3367
