### ISSUE TITLE
centos packages broken in repo

### ISSUE THREAD

**Issue by teadur** [gitlabhq/gitlabhq#10155]
all the rpm package links give download error:

https://packages.gitlab.com/gitlab/gitlab-ce
https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/gitlab-ce-8.7.0-ce.0.el7.x86_64.rpm

**Comment by MrChrisW** [comment]
Thanks, this is discussed here: https://gitlab.com/gitlab-com/operations/issues/211

In the meantime, it appears you can append /download to download the package directly (e.g. https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/gitlab-ce-8.7.0-ce.0.el7.x86_64.rpm/download).

Thanks

**Comment by teadur** [comment]
Ty for the link, it seems that the issue is resolved now.
