### ISSUE TITLE
Indicate which merge requests has my own like

### ISSUE THREAD

**Issue by povi** [gitlabhq/gitlabhq#10157]
It would be really helpful to see which merge requests I personally liked in merge request list, especially when merge request list is long. Perhaps color thumbs up icon in green?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
