### ISSUE TITLE
openssl certificate verify failed

### ISSUE THREAD

**Issue by songnous** [gitlabhq/gitlabhq#10315]
I config the cas in gitlab.rb for sso,but when sign in to gitlab ,I get 500 error.
because the ca in cas is tomcat keytool made ,so i want to change code in gitlab source to trust ssl certificate. could anyone tell me where and how to change code in gitlab and reconfigure?

**Comment by uyson** [comment]
你在说是ssl证书吗？

**Comment by uyson** [comment]
你在说ssl证书吗？

**Comment by songnous** [comment]
恩，是的，cas是用自己生成的ssl证书，但是gitlab不信任，报错

**Comment by uyson** [comment]
你用的是哪个版本？ 我用docker 母机用nginx反向代理， 在母机加了ssl

**Comment by uyson** [comment]
这里有说明文档， https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/nginx.md

**Comment by uyson** [comment]
自己生成的ssl会浏览器提示不信任 ， 你用 letsencrypt.org 或者 https://buy.wosign.com/free/?lan=en 第三方机构证书就不会提示 了

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
