### ISSUE TITLE
hook trigger jenkins 403

### ISSUE THREAD

**Issue by hhy5861** [gitlabhq/gitlabhq#10318]
![34](https://cloud.githubusercontent.com/assets/8274977/14941771/c0cdb4c2-0fda-11e6-96a9-f36da52fa212.png)

![12](https://cloud.githubusercontent.com/assets/8274977/14941754/1256ece2-0fda-11e6-8d62-0415dc35cca2.png)

this is what causes?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
