### ISSUE TITLE
Add reporters to repository API

### ISSUE THREAD

**Issue by 0xABAB** [gitlabhq/gitlabhq#10314]
I would like to use the API to add users (currently just as a "Reporter") to one of my repositories. In general, I want to be able to do everything I can do via the web-interface via an API. 

The web-interface for bulk adding of users (e.g. separated by comma's or something like that) also doesn't seem to exist.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
