### ISSUE TITLE
Strange logic in merge_request_widget

### ISSUE THREAD

**Issue by vadim-plaksin** [gitlabhq/gitlabhq#10313]
```
      if @firstCICheck
        @firstCICheck = false
        @opts.ci_status = data.status

      if @opts.ci_status is ''
        @opts.ci_status = data.status
        return

      if data.status isnt @opts.ci_status and data.status?
        @showCIStatus data.status
```
If the CI build has already been completed when this script loads and always returns the same status, for instance 'success' then the widget status will never change and will always show 'Checking CI status for ...' 

Basically the widget status will change only if more than one status is received from the CI during the session.

**Comment by dotpot** [comment]
👍

**Comment by Paulius-Maruska** [comment]
I can confirm, that this is how GitLab behaving right now.
We use GitLab version 8.7.0 f2a3f70, our CI is TeamCity 9.1.
If I open any old merge request where CI build has already completed - GitLab is showing "Checking CI status" message forever.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
