### ISSUE TITLE
Permission denied (publickey) when cloning project

### ISSUE THREAD

**Issue by fandy** [gitlabhq/gitlabhq#10325]
I'm having troubles cloning Gitlab:

I used: `git clone --mirror git@gitlab.com:andyfang/galaxy-ui.git`

and got:

```
Cloning into bare repository 'galaxy-ui.git'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
