### ISSUE TITLE
Build erlang apps

### ISSUE THREAD

**Issue by abhi1693** [gitlabhq/gitlabhq#10328]
Is there a way to build `Erlang` apps using `Gitlab Runners`?

**Comment by connorshea** [comment]
You should be able to, since you can download arbitrary packages, although I'm not sure of the specifics.

**Comment by abhi1693** [comment]
I want the specifics because even when my erlang application crashes the gitlab ci shows that the build succeeded.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
