### ISSUE TITLE
Gitlab configuring emails to go over a relay

### ISSUE THREAD

**Issue by fatagun** [gitlabhq/gitlabhq#10323]
Hello,

I want to use a Relay server in our org. even though I make changes to /etc/gitlab/gitlab.rb, i still cant send emails. Below are the changes 

gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "172.18.100.100"
gitlab_rails['smtp_port'] = 25
gitlab_rails['smtp_user_name'] = "gitlab@foo.gov"
gitlab_rails['smtp_password'] = ""
gitlab_rails['smtp_domain'] = "gitlab.foo.gov"
gitlab_rails['smtp_authentication'] = "login"
gitlab_rails['smtp_enable_starttls_auto'] = true
gitlab_rails['smtp_tls'] = true

Do i need to make changes in other places as well? My network team is saying that packets are not going to relay.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
