### ISSUE TITLE
OTRS integration

### ISSUE THREAD

**Issue by roo7break** [gitlabhq/gitlabhq#10327]
Hi,

Do you have plans to integrate to OTRS? It would be of real help if you could support OTRS considering its open source and hence to be used in multiple small scale businesses.

If not could you publish info on how we can integrate using API calls.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
