### ISSUE TITLE
GitLab API merge request status and changes are incorrect

### ISSUE THREAD

**Issue by MadhavGitlab** [gitlabhq/gitlabhq#10335]
Iam using GitLab API 8.7.2 to submit a merge request and then accept it based on its "merge_status" and "changes" fields. When i submit a new merge request using the API, the merge_status and changes fields are incorrect. It always shows the changes as "null" and 'merge_status' as "unchecked", but if i go to GitLab -> Merge Requests section i see that the merge request status is - "Accept MergeRequest". Is it a bug in the API that it always shows the status and changes fields incorrectly?

On the other side, if i close the merge request and reopen it, the merge_status and changes fields show correct values.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
