### ISSUE TITLE
No validation while adding project members

### ISSUE THREAD

**Issue by webofnithin** [gitlabhq/gitlabhq#10332]
no validation is there on the new project member adding form. The 'add member' button is is clickable even if no members are selected .

I have fixed the issue and raised a pull request #10331 

![screenshot from 2016-05-07 12 10 12](https://cloud.githubusercontent.com/assets/1277421/15090797/07b4aed8-1452-11e6-9126-aaa4198ecb74.png)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
