### ISSUE TITLE
Can we use link_to to replace link_to_gfm in _issue.html.haml

### ISSUE THREAD

**Issue by yhl3692319** [gitlabhq/gitlabhq#10339]
`technical debt`
i have discovered that if i replace link_to_gfm with link_to method in
https://github.com/gitlabhq/gitlabhq/blob/master/app/views/projects/issues/_issue.html.haml#L9
`= link_to_gfm issue.title, issue_path(issue)`

The time of show issue.title will reduce to 1ms, while using link_to_gfm, it takes 10ms

so the whole issues_page will reduce about 200ms to load

**Comment by connorshea** [comment]
Unfortunately [the `link_to_gfm` method](https://github.com/gitlabhq/gitlabhq/blob/master/app/helpers/gitlab_markdown_helper.rb#L13) is used for handling inline links within issue titles. It may not be worth the performance trade-off if we can prove in testing that it really does decrease load time for a given issue list by ~180ms.

This *is* worth considering though. Did you test this with issue titles that have links in them?

**Comment by yhl3692319** [comment]
@connorshea yes, if the issue.title has links, the time of each issue to load is 1ms too, but the link in issue title is disabled.

## my test step
1. render plain each class (`.issue-title.title`、`.issue-info`) load time in https://github.com/gitlabhq/gitlabhq/blob/master/app/views/projects/issues/_issue.html.haml
2.  and replace link_to_gfm with link_to
3. compare the results

## other
in some cases, when the issue title has links, it will make me confused when i want to click into the issue but not the links

**Comment by connorshea** [comment]
There's currently an open Merge Request for this on GitLab.com, thanks for the suggestion :)

**Comment by yhl3692319** [comment]
my pleasure
