### ISSUE TITLE
Broken Link in Help Section of gitlab.com

### ISSUE THREAD

**Issue by joncalhoun** [gitlabhq/gitlabhq#10334]
https://gitlab.com/help/ci%2Fquick_start/README links to Runners in the first line and the link is broken.

https://gitlab.com/help/runners/README.md is the broken link
I think it should be: https://gitlab.com/help/ci/runners/README.md

I believe the underlying README w/ the link comes from here: https://github.com/gitlabhq/gitlabhq/blob/178dfb191798701be59a0a1c7a988565e437abc0/doc/ci/quick_start/README.md

But oddly the link works in the README inside of github, otherwise I would have submitted a PR to fix this rather than an issue.

**Comment by axilleas** [comment]
Yep, see https://gitlab.com/gitlab-org/gitlab-ce/issues/14869 and https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3561. I'll close this as duplicate. @joncalhoun thanks for reporting!
