### ISSUE TITLE
Button instead of link for canceling a build

### ISSUE THREAD

**Issue by hyeomans** [gitlabhq/gitlabhq#10333]
Hello,

When on `/builds` page and the build is running, it was really confusing the cross mark, I thought it failed.
Is it good to change it to a Cancel button and the `fa fa-repeat` link to something like Re-run?

Here is the view in question https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/builds/_build.html.haml#L68

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
