### ISSUE TITLE
switch placment of UI buttons for "dialog boxes"

### ISSUE THREAD

**Issue by logicminds** [gitlabhq/gitlabhq#10347]
I have setup gitlab for several of my clients and it never fails that when new users try and close an issue or merge request they end up clicking "the wrong button".  Sometimes several times in a row! They know exactly what they did wrong and the big question is why they clicked the "wrong button" if they know what they wanted to accomplish.   

Good usability practice states that color and position of buttons can make a huge difference in human readability and awareness .  Red meaning cancel and green meaning the action that most uses will want to take. 

<img width="377" alt="screenshot 2016-05-23 11 22 55" src="https://cloud.githubusercontent.com/assets/563900/15475715/6c24eea8-20d9-11e6-8696-be667bb2bba9.png">

In this example above the "cancel" button is on the right while the "correct button" is on the left.  Most users will instinctively click the right button because that is how we think.   We read from left to right. The current implementation confuses the user and makes them second guess the button's meaning as the dialog flows in the opposite expectation.  Additionally, every user has to memorize gitlab's special UI button placement.

http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/

 Don't think this is an issue?  When you leave work, take a second to look at button placement every time you pick up your phone, make a phone call, purchase something at any retail outlet.  What I think you will find is that the majority of our lives are filled with things flowing to the right (green button).  We get very use to this design because it makes sense.  

And when you find that odd credit card machine with buttons in the opposite flow.  I would imagine you get pissed off or confused because you know that you are "smarter than that" after clicking the wrong button on the right side.

![machine](http://www.creditcardchaser.com/wp-content/uploads/2010/01/mcdonalds-credit-card-machine.jpg)

![phone](http://iosguides.net/wp-content/uploads/2014/01/iOS-7-beta-3-phone-call.jpg)

![trying-to-press-red-button-dont-know-what-red-is](https://cloud.githubusercontent.com/assets/563900/15476544/9096c456-20dd-11e6-9670-114cf2ff94cc.jpg)

Please fix this annoying design issue and put the green buttons on the right side.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Comment by logicminds** [comment]
Yea, I thought I was on gitlab when I made this.  Then I realized what I did and created it again on gitlab tracker. @connorshea

**Comment by connorshea** [comment]
@logicminds thanks :)
