### ISSUE TITLE
webhook return code feature request

### ISSUE THREAD

**Issue by Gollam** [gitlabhq/gitlabhq#10344]
Hi,
Webhooks could be more useful, if their HTTP response code wouldn't be ignored. For example if I want to decline a push, my webhook would return 304 Forbidden, and if it allows the push, it would return 200 OK.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
