### ISSUE TITLE
gitlab push hang after showing total when gitlab server execute a post-receive

### ISSUE THREAD

**Issue by rangochan** [gitlabhq/gitlabhq#10342]
When I run "git push" for my gitlab repository on my mac machine, terminal will hang after showing "Total...".  ps: gitlab server configurated a post-receive hook which will fork a child process to run a rsync job which includes "verbose" namely "-v" parameter for this repository.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
