### ISSUE TITLE
[Feature-Request] Protecting Branches with RegEx

### ISSUE THREAD

**Issue by N3XT0R** [gitlabhq/gitlabhq#10345]
Hello Guys,

at the current time it is possible to protect selected branches in the project settings. 
For a later time it would be great, when it would be possible to protect automatically branches that have a specific name. 

at example:
1. Configuration:
all branches with name deploy-*-* should be protected

2. 
master:
a master push the branch deploy-xyz-1 (branch will be created as protected branch)

developer:
a developer tries to push into branch deploy-xyz-1 (not possible)
or a developer tries to create branch deploy-xyz-1 (should also be not possible)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
