### ISSUE TITLE
Search is incredible slow with GitLab 8.7.1 and 8.7.5

### ISSUE THREAD

**Issue by offlinehoster** [gitlabhq/gitlabhq#10343]
We're running omnibus installtion on centos6 with gitlab 8.7.5 (updated a few minutes ago).

While searching inside an existing gitlab project, the search result needs up to 70 seconds for a round about 5MB big git repo.

With the default unicorn settings, 2 Worker and timeout on 60 seconds we receive a 502 after that timeout.

We're using now  4 Workers and 120 seconds timeout. But it is still slow.

Searching a word with 4 letters is fast, for example searching for "test". While searching for a word like "Zeitraum" (a german word) it takes up to 70 seconds and the results are 3 hits, one is inside a very large xml file? Can this be the problem? 

This problem exists already with 8.7.1 and now with 8.7.5 too.

Any other ideas?

Cheers
Christian

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
