### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by wirehack7** [gitlabhq/gitlabhq#10348]
In [/doc/update/8.7-to-8.8.md](https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/8.7-to-8.8.md#5-update-gitlab-workhorse) the code should be changed to:

```bash
cd /home/git/gitlab-workhorse
sudo -u git -H git fetch --all
sudo -u git -H git checkout v0.7.1
sudo -u git -H make clean
sudo -u git -H make
```

So old generated files will be deleted and the error ```make: Nothing to be done for `all'.``` won't appear.

Referencing @123Haynes here.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
