### ISSUE TITLE
Diffs with many deleted files don't load

### ISSUE THREAD

**Issue by Brobin** [gitlabhq/gitlabhq#10341]
It would be nice If you could truncate the diff on a merge request with many deleted files. For example, I have a merge request with 4000+ deleted files and a few changed files. If it simply said "file x was deleted" instead of showing the entire diff, you would still be able to see the files that were actually changed.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
