### ISSUE TITLE
not able to merge

### ISSUE THREAD

**Issue by anandkumarmatta** [gitlabhq/gitlabhq#10349]
Hi All,
I am not able to merge my pull request.

It is showing Hang in there while we check the branch's status.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
