### ISSUE TITLE
Error 502 when enabled Gitlab Docker Registry at GitLab 8.8

### ISSUE THREAD

**Issue by netandreus** [gitlabhq/gitlabhq#10356]
I installed gitlab 8.8 from packages on ubuntu 16.04 following this manual. https://about.gitlab.com/downloads/#ubuntu1604

When I add line
`registry_external_url 'https://gitlab.example.com:4567'`
to my  /etc/gitlab/gitlab.rb and reconfiguring gitlab I seen this error:
Error 502 Bad Gateway.

Try to delete this line and all fine. How can I setup Gitlab docker registry properly?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
