### ISSUE TITLE
Disable Auto-Merge in Pull

### ISSUE THREAD

**Issue by hamidyfine** [gitlabhq/gitlabhq#10350]
How can I disable auto-merge when pull project?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
