### ISSUE TITLE
BountySource: Configurable JIRA integration

### ISSUE THREAD

**Issue by mrts** [gitlabhq/gitlabhq#10359]
This is a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/5541 so that I can create a bounty for it at Bountysource.

---

# Description

The current GitLab JIRA integration logs both **commit** and **merge request** events as comments in JIRA. This is not optimal as an issue with many related commits creates a lot of comment noise in JIRA.

Merge request event comments are useful separately in JIRA, so configuration is needed to turn them on separately.

# Acceptance criteria

In GitLab JIRA integration page under _Project settings > Services > JIRA_ there is a new configuration section with a list of checkboxes which configures which integration features are enabled:

> JIRA integration features:
> 
> * [ ] Publish mentions in commits as comments in issues
> * [ ] Publish mentions in merge requests as comments in issues
> * [ ] Enable closing of issues

Also, unit tests and documentation are updated accordingly.

I hope that the feature descriptions are clear enough as a spec, please ask if not.

**Comment by mrts** [comment]
Link to the Bountysource bounty: https://www.bountysource.com/issues/34850573-bountysource-configurable-jira-integration

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by mrts** [comment]
@jvanbaarsen I am aware that you are closing down the GitHub issue tracker, that's why the original issue is filed at GitLab. However, I am not aware of any way to publish Bountysource bounties for issues via GitLab. Don't you think it makes sense to keep issues with bounties open in GitHub tracker (as Bountysouce integration works here)? If not, how should one go about publishing bounties for GitLab issues?

**Comment by connorshea** [comment]
I agree with @mrts, I think we should leave this open for the time being.

**Comment by mrts** [comment]
Thanks :)!

**Comment by dosire** [comment]
GitLab team member Felipe A. will be working on this for 8.13 or 8.14, see https://gitlab.com/gitlab-org/gitlab-ce/issues/5541

I'll close this issue since it is unlikely someone will pick it up in the meantime.

**Comment by mrts** [comment]
@dosire, sounds good but not that there are 2 bounties in BountySource for this, how should we proceed with those?

**Comment by dosire** [comment]
@mrts close the bounties? I say someone took up one of them but this person is working on 6 bounties at the same time so I hope there is no effort spend on this yet.

**Comment by mrts** [comment]
I did get in touch with Bountysource support to close the bounties. *guugle27* seems to be a spammer, so no effort lost.
