### ISSUE TITLE
Jenkins service not supported from api?

### ISSUE THREAD

**Issue by nenf** [gitlabhq/gitlabhq#10361]
Hello!
I did not find jenkins service on http://docs.gitlab.com/ce/api/services.html page

I send PUT request on http://aktiv-scm//api/v3/projects/9/services/jenkins with parameters:
{"username": "user", "project_name": "project", "tag_push_events": "0", "push_events": "1", "jenkins_url": "my_jenkins", "merge_requests_events": "1", "password": "pass"}

Jenkins service is activated, but any  checkbox (like push_events) is not activated.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
