### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ranzhe** [gitlabhq/gitlabhq#10362]

**Comment by Razer6** [comment]
@ranzhe Please email security@gitlab.com to report any potential security vulnerabilities.

**Comment by jvanbaarsen** [comment]
@Razer6 Can you make sure the original issue is created as a confidential issue on GL.com?

**Comment by Razer6** [comment]
@jvanbaarsen It is created as a confidential issue.

**Comment by jvanbaarsen** [comment]
:+1:
