### ISSUE TITLE
Cannot use ip:port to access GitLab with Docker

### ISSUE THREAD

**Issue by zepouet** [gitlabhq/gitlabhq#10377]
Hello,

I would like to use Gitlab with a different port than 80 because I have another business application onto (not nginx or other http server...)

So I would like to reach it though : http://192.168.50.4:480 for example.
Previously I could with such configuration 

```
    docker run --detach \
	--hostname gitlab.cloudunit.dev \
	--publish 4443:443 \
	--publish 480:80 \
	--publish 222:22 \
        --name gitlab \
        --restart always \
        --volume /home/vagrant/gitlab_home/config:/etc/gitlab \
        --volume /home/vagrant/gitlab_home/logs:/var/log/gitlab \
        --volume /home/vagrant/gitlab_home/data:/var/opt/gitlab \
        gitlab/gitlab-ce:$GL_MAJOR
```

With the last release 8.10.1-ce.0, it is not possible.
If I remove the hosname parameter, I have this redirection after boot : **http://882973a1652c/users/sign_in**

**882973a1652c** is the container id.

It would be nice to have a new parameter **hostip** or to be able to use ip:port into hostname.

Thanks a lot. Best regards

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
