### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by mapio** [gitlabhq/gitlabhq#10376]
The link in https://github.com/gitlabhq/gitlabhq/wiki/VirtualBox-Image is broken (leads to non-existent https://github.com/gitlabhq/gitlab-vagrant-vm

**Comment by Devinsuit** [comment]
Try this https://github.com/kouno/gitlab-vagrant-vm

**Comment by connorshea** [comment]
I've disabled the GitHub repo's wiki now since its very outdated at this point.

docs.gitlab.com is where you should go for documentation :) Tell me if you have any other concerns.

**Comment by connorshea** [comment]
If you're interested in setting up a dev environment, see the [GitLab Development Kit](https://gitlab.com/gitlab-org/gitlab-development-kit), I don't think VirtualBox is supported for hosting GitLab in a production environment, though I could be wrong.
