### ISSUE TITLE
Jenkins CI run using GIT hub for Specific Project

### ISSUE THREAD

**Issue by dhamu2622** [gitlabhq/gitlabhq#10388]
Am new to jenkins and GIThub configuration, My requirement is i need to trigger the Jenkin job once if new job is pushed in Git hub.

1) copied the hook url from jenkins http://http://10.251.236.139:8080//github-webhook/ and added in GIThub's Webhooks / Manage webhook .

2)jenkins Source code mgmt git->repositary url : git https://github.myserver.com/APS-CODS/GIT_SVN_MIGRATION.git

3)Branch Specifier (blank for 'any'): */develop

4)Build Triggers : Build when a change is pushed to GitHub

i think the above setup is fine.if it is wrongly kindly guide me.

My questions :

1)I have list of projects under my develop/* branch in githup then how jenkins identify which job need to run?

2)Second thing i push the code in github by user1 and i configured my job under default jenkins admin user is there any conflict ?

My jenkins job not triggered automatically while i push the codes under project1 in git hub.

I tryed to run mannualy in build now option in jenkins i got an error as follows: ERROR: Error fetching remote repo 'origin'

+refs/heads/:refs/remotes/origin/" returned status code 128: stdout: stderr: fatal: I don't handle protocol 'git https'

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
