### ISSUE TITLE
An error occurred while installing rugged (0.24.0), and Bundler cannot continue.

### ISSUE THREAD

**Issue by jd2017** [gitlabhq/gitlabhq#10393]
My environment : OS X El Capitan 10.11.13;
bash-3.2$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15.3.0]
bash-3.2$ gem -v
2.6.7
## After executing 'gem install rugged -v '0.24.0'', the following error occurred; please tell me how to fix it? thanks

bash-3.2$ gem install rugged -v '0.24.0'
Building native extensions.  This could take a while...
ERROR:  Error installing rugged:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/rugged-0.24.0/ext/rugged
/usr/local/bin/ruby -r ./siteconf20161018-19039-5897tb.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--use-system-libraries
extconf.rb:13:in `sys': ERROR: 'cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"' failed (RuntimeError)
	from extconf.rb:70:in `block (2 levels) in <main>'
	from extconf.rb:69:in `chdir'
	from extconf.rb:69:in `block in <main>'
	from extconf.rb:66:in `chdir'
	from extconf.rb:66:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/rugged-0.24.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3.0/gems/rugged-0.24.0 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/rugged-0.24.0/gem_make.out

**Comment by grzesiek** [comment]
@jd2017 This looks like a problem with missing dependencies needed to build native extensions. Did you install `build-essential` package (if using ubuntu/debian)?
