### ISSUE TITLE
Denpendency issue

### ISSUE THREAD

**Issue by N3XT0R** [gitlabhq/gitlabhq#10398]
Hello Guys,
there is a Dependency issue in the newest Version of Gitlab. Gitlab in Version 8.13 requires gitlab-shell in Version 3.6.6, but this version is not released yet as a tag.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by 123Haynes** [comment]
To answer your question: gitlab-shell 3.6.6 has been released, but the tags on github.com haven't been updated. Please take a look at this repo to find them: https://gitlab.com/gitlab-org/gitlab-shell/tags
