### ISSUE TITLE
composer cant download yii2 source files

### ISSUE THREAD

**Issue by woshka** [gitlabhq/gitlabhq#10394]
[root@box322 balasgro]# composer create-project --prefer-dist yiisoft/yii2-app-basic basic44
Installing yiisoft/yii2-app-basic (2.0.10)
  - Installing yiisoft/yii2-app-basic (2.0.10)
    Downloading: Failed
    Downloading: Failed
    Downloading: Failed
    Failed to download yiisoft/yii2-app-basic from dist: The "https://api.github.com/repos/yiisoft/yii2-app-basic/zipball/fd3391bbcdcd59d41de3dabf2aef6926046a0b81" file could not be downloaded: failed to open stream: Connection refused
    Now trying to download from source
  - Installing yiisoft/yii2-app-basic (2.0.10)
    Cloning fd3391bbcdcd59d41de3dabf2aef6926046a0b81

  [RuntimeException]
  Failed to clone https://github.com/yiisoft/yii2-app-basic.git via https, ssh protocols, aborting.
  - https://github.com/yiisoft/yii2-app-basic.git
    error: Failed connect to github.com:443; Operation now in progress while accessing https://github.com/yiisoft/yii2-app-basic.git/info/refs

    fatal: HTTP request failed
  - git@github.com:yiisoft/yii2-app-basic.git
    ssh: connect to host github.com port 22: Connection timed out
    fatal: The remote end hung up unexpectedly

**Comment by jvanbaarsen** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it in our issue tracker on GitLab.com. You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
