### ISSUE TITLE
API：the result of /api/v3/projects search project by name is diffrent with the method which is client.projects.search of node-gitlab

### ISSUE THREAD

**Issue by emily-meng** [gitlabhq/gitlabhq#10402]
the result are diffrent, maybe the problem is the permission are diffrent.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
