### ISSUE TITLE
How to migrate gitlab issue tracker to github issue tracker

### ISSUE THREAD

**Issue by harigaranrbt** [gitlabhq/gitlabhq#10408]

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
