### ISSUE TITLE
[remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by fail2010** [gitlabhq/gitlabhq#10405]
hello, 
I upgrade my git use  git sources 
but found one error when i push my project in protect branch

my project branch set proted  for master can push ,
then unproject branch can push ,

last I upgrade gitlab in last stable , still push failed!

error message: 
```
 GitLab: You are not allowed to force push code to a protected branch on this project.
 ! [remote rejected] master -> master (pre-receive hook declined)
error: 无法推送一些引用到 'git@git.cc/coola/me.git'
```

**Comment by martin-paulus** [comment]
Please read https://gitlab.com/gitlab-org/gitlab-ce/issues/25301
