### ISSUE TITLE
how to create gitlab in mac osx?

### ISSUE THREAD

**Issue by holyen** [gitlabhq/gitlabhq#10418]
We’re closing our issue tracker on GitHub so we can focus on the GitLab.com project and respond to issues more quickly.

We encourage you to open an issue on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log into GitLab.com using your GitHub account.

**Comment by Razer6** [comment]
Please file bugs/features on gitlab.com. For general questions to gitlab please refer to the support forum or stackoverflow.
