### ISSUE TITLE
Pushing problem in git 

### ISSUE THREAD

**Issue by Devops9AM** [gitlabhq/gitlabhq#10417]
git push origin master
remote: Permission to Devops9AM/Devops9am.git denied to ThotaThanish.
fatal: unable to access 'https://github.com/Devops9AM/Devops9am.git/': The requested URL returned error: 403

Please can you help on above issue.
Thanks & Reg

**Comment by Devops9AM** [comment]
HI Pls help on above issue.

**Comment by 123Haynes** [comment]
@Devops9AM The github issue tracker is not being used anymore. Please open an issue at the gitlab.com issue tracker next time.

That being said, your problem likely is because of a protected branch. (in the project->settings->protected branches)
