### ISSUE TITLE
calling /api/v3/projects/:project_id/builds/:build_id/play returns 400

### ISSUE THREAD

**Issue by sachin42hertz** [gitlabhq/gitlabhq#10411]
I'm trying to play a build using the API. But I'm constantly getting a 400 response.
`curl -X POST -H "PRIVATE-TOKEN: ry_K3gS64iBfNx7TS6L4" "https://gitlab.com/api/v3/projects/2129024/builds/8367492/play"`

returns
```
{
  "message": "400 (Bad request) \"Unplayable Build\" not given"
}
```
Could you guys look into this please?

**Comment by Razer6** [comment]
It seems this build is not playable. Can you play that build in the web UI? Please raise future issues on gitlab.com
