### ISSUE TITLE
Merge requests state title for opened is 'Open' instead of 'Opened'

### ISSUE THREAD

**Issue by vsambor** [gitlabhq/gitlabhq#10431]
I think the correct state name in the navigator should be 'Opened' not Open. 
When I see 'Open' to me is like an action, it seams that I'm going to open a merge request on click, instead of vizualizing the opened merge requests.
Thank you.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
