### ISSUE TITLE
Little feature - add a color marker in calendars to display the current day

### ISSUE THREAD

**Issue by erwinronco** [gitlabhq/gitlabhq#10438]
It should be nice if we had a color marker in calendars to display the current day.
I think that for example in the issue page, for "due date" calendar.
Thanks a lot.

/label ~"feature proposal"

**Comment by randx** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

I believe the similar issue can be found at https://gitlab.com/gitlab-org/gitlab-ce/issues/32169.
