### ISSUE TITLE
http protocol port change

### ISSUE THREAD

**Issue by taozi34** [gitlabhq/gitlabhq#10433]
i change gitlab http port from 80 to 8080 in /var/opt/gitlab/gitlab-rails/etc/gitlab.yml,then exec "gitlab-ctl restart" command, the http default port change to 8080, but when gitlab service restart, the http port use default 80. so, how to stay http port change ?

gitlab version:9.1.0
run in docker

thanks

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
