### ISSUE TITLE
Failed gem install charlock_holmes any version in ubuntu server 14.04

### ISSUE THREAD

**Issue by ichromanrd** [gitlabhq/gitlabhq#10439]
Hi. My problem seems similar with [#issue 1952](https://github.com/gitlabhq/gitlabhq/issues/1952). My machine is ubuntu server 14.04 LTS. The package name is **libicu-dev**. It's already installed, along with **patch** and **g++**, but it keep failing when I want to install charlock_holmes. Please help me. Error message:

`Building native extensions. This could take a while...`
`ERROR:`
`Error installing charlock_holmes: ERROR: Failed to build gem native extension.`
`current directory: /var/lib/gems/2.3.0/gems/charlock_holmes-0.6.9.4/ext/charlock_holmes /usr/bin/ruby2.3 -r ./siteconf20170704-1873-733mkr.rb extconf.rb mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h`
`extconf failed, exit code 1`
`Gem files will remain installed in /var/lib/gems/2.3.0/gems/charlock_holmes-0.6.9.4 for inspection. Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/charlock_holmes-0.6.9.4/gem_make.out`

**Comment by ichromanrd** [comment]
Sorry, it's solved. I had to install ruby2.3-dev first. Thanks.

**Comment by tarvit** [comment]
I got situation when it failed with `ruby2.3-dev` and `libicu-dev` installed. But worked after `sudo apt-get upgrade`
