### ISSUE TITLE
using ldap account sign-in failed, access denid

### ISSUE THREAD

**Issue by taozi34** [gitlabhq/gitlabhq#10432]
environment"
1.run gitlab in docker
2.gitlab version : 9.1.0

steps:
1.use root sign-in gitlab, in standard label
2.config ldap info,and restart gitlab
3.use ldap account1 sign-in gitlab, it's ok
4.uncheck "Sign-up enabled" in gitlab Setting page, then save change
5.use ldap account2 sign-in gitlab, get error:access denid
6.administrator add account2 to gitlab, then account2 try sign-in again, result succeed

so, if i want cut sign-up label in index page, and use ldap account sign-in gitlab, what can i do?!

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab using your GitHub account if you'd like to contribute an issue.
