### ISSUE TITLE
report 500 error when access commits page

### ISSUE THREAD

**Issue by peterpar1984** [gitlabhq/gitlabhq#10441]
Encoding::CompatibilityError (incompatible character encodings: ASCII-8BIT and UTF-8):
  app/views/projects/commits/show.html.haml:19:in `_app_views_projects_commits_show_html_haml__2061915603265574773_70012643710960'
  app/controllers/projects/commits_controller.rb:18:in `show'

Completed 500 Internal Server Error in 218ms (Views: 9.0ms | ActiveRecord: 6.8ms)

**Comment by godfat** [comment]
We're no longer using this issue tracker, so please open the issue at https://gitlab.com/gitlab-org/gitlab-ce/issues and provide detail about your installation version, environments, etc. Thanks!
