### ISSUE TITLE
Could not authenticate you from Ldapmain because "Invalid credentials"

### ISSUE THREAD

**Issue by kedarshastry** [gitlabhq/gitlabhq#10440]
Cannot login to Gitlab using LDAP: 

gitlab-rake gitlab:ldap:check was successful and  lists 100 users from LDAP,  but when I try to login I get "Could not authenticate you from Ldapmain because "Invalid credentials" 

I find below message in production log

-----------------------------------------------

Completed 200 OK in 56ms (Views: 35.1ms | ActiveRecord: 10.1ms)
Completed 200 OK in 58ms (Views: 39.0ms | ActiveRecord: 10.3ms)
Started POST "/users/auth/ldapmain/callback" for x.x.x.x at 2017-08-13 21:49:26
 +0000
Processing by OmniauthCallbacksController#failure as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"GvrLlXFHNnik0sKf8PPsEp66ohF+iI
v7pTrrnsScyR4uJ1QKJksjBXv532/4Y1kKMdH/EwWOLLrG4dzLwJhYYg==", "username"=>"UID", "password"=>"[FILTERED]"}
--------------------------------------------------------------------------

Below is the LDAP setting in gitlab.rb

 gitlab_rails['ldap_enabled'] = true
 gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' # remember to close this block with 'EOS' below
   main: # 'main' is the GitLab 'provider ID' of this LDAP server
     label: 'LDAP'
     host: 'hostname.x.y.z'
     port: 389
     uid: 'uid'
     method: 'plain' # "tls" or "ssl" or "plain"
     bind_dn: 'MYDN'
     password: 'MYPASSWORD'
     base: 'DC=XYZ,DC=net'
EOS
---------------------------

Appreciate all help & support

**Comment by rajp0801** [comment]
Please can someone help as I am facing the same problem
