### ISSUE TITLE
A question about Gitlab. 

### ISSUE THREAD

**Issue by mndvn** [gitlabhq/gitlabhq#10456]
Hi, 
I have created an account on Gitlab. Because, Github is not open source. I think it is weird that a company come up with an idea of making software world more open. But it is not open-source. 

That was not my question. I would like to ask ppl. Why Gitlab does not have a open source account on Gitlab?

I support Gitlab. But it is very slow. I think it stems from the back-end of it. I am not sure. I believe it is not good in terms of user experience. I mean being slow.

**Comment by axilleas** [comment]
> Why Gitlab does not have a open source account on Gitlab?

I don't get that question. You can find GitLab's projects under https://gitlab.com/gitlab-org/.

> I support Gitlab. But it is very slow. I think it stems from the back-end of it. I am not sure. I believe it is not good in terms of user experience. I mean being slow.

This is being worked on both from backend and infra perspective. You can take a look at the performance labeled issues https://gitlab.com/groups/gitlab-org/issues?label_name%5B%5D=performance.
