### ISSUE TITLE
Feature Request: Commit Individual Branch (Without Committing the whole master)

### ISSUE THREAD

**Issue by jtelleria** [gitlabhq/gitlabhq#10470]
# Description

Lately I've been doing some work with a project which lives on Gitlab. Last week I found a bug, so I put together a patch.

Since the package lives on Gitlab, I followed instructions to put together a "pull request":

- I forked the main branch to my own Gitlab account.
- I checked out my fork.
- I fixed the bug, and submitted the pull request.

Then I felt good about myself, and continued on with my work. Today I tracked down another bug, unrelated to the previous one. I know enough about git to know that I shouldn't commit this fix to my fork, because it would then become part of the previous pull request.

So I created a branch within my fork, and committed the change there. But Gitlab provides no way to create a pull request that only includes the new stuff! Every attempt I made would have included everything from both bug fixes.

I've read online about creating a new branch based on the master copy, and "cherry picking" just the final change: But it required the command line, and was not easy enough.

Okay, I know the solution: I need to burn the whole thing down. I'll just create a new fork, and put the new bug fix in a branch there.

I can't! I don't know if this is a Git restriction or a Gitlab restriction, but it won't let me create a new fork without deleting the old one. I don't know if deleting the previous fork would also delete the previous PR, so I'm not going to do this.

This is ridiculous! It is such an easy concept: I want to take the diff between my most recent commit and the one before, and send that diff to the owners of the master copy. This should be a trivial (and it is in svn).

# Proposal

Thant Gitlab offers the possibility to commit individual branches without the need to commit the whole forked Master Project.

**Comment by jtelleria** [comment]
The very complex process to achieve the above would be as follows:

1)  Via GUI: fork or clone at gitlab so that you have URL to use in 2)

2)  Run
      git clone giturl....
    to fetch local instance

3)  Run
      git checkout -b feature/new_thing_a

4)  Edit, save, compile, test, revise, ... leading to 1 or more commits

5)  Run
      git push origin
    standard configuration should have remote branch follow local branch, I
    think the "long form" is
      git push --set-upstream origin feature/new_thing_a

6)  Run
      git checkout -
    or
      git checkout master
    and you are back in master. Now you can restart at my 3) above for
    branches b, c, d and create independent pull requests

I find it really to have a bash prompt that shows the branch:

```
edd@rob:~$ cd git/rcpp
edd@rob:~/git/rcpp(master)$ git checkout -b feature/new_branch_to_show
Switched to a new branch 'feature/new_branch_to_show'
edd@rob:~/git/rcpp(feature/new_branch_to_show)$ git checkout -
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
edd@rob:~/git/rcpp(master)$ git branch -d feature/new_branch_to_show
Deleted branch feature/new_branch_to_show (was 5b25fe62).
edd@rob:~/git/rcpp(master)$
```
If only this could be made easier in Gitlab's GUI, would be very appreciated :)

**Comment by godfat** [comment]
We're not using this issue tracker, so could you please file the issue at https://gitlab.com/gitlab-org/gitlab-ce/issues ?

Also on the topic, I think you could go to your fork, on the master branch (assuming you're not committing to master directly), make update on another branch. You could perfectly do this via web UI, having multiple patching branches.

If you don't know how to do this, perhaps you could try https://forum.gitlab.com/ to ask for help.
