### ISSUE TITLE
Where is personal token?

### ISSUE THREAD

**Issue by FiW** [gitlabhq/gitlabhq#10475]
Hello.

I have GitLab Community Edition 10.4.3 183dd5d as docker image.

I can't find any personal token content after creation in 'Access tokens' page.

![image](https://user-images.githubusercontent.com/1755384/36016198-45bf92d6-0d8b-11e8-99d1-8faa36e587f8.png)

**Comment by vsizov** [comment]
You can only see it when you create it. Please use https://gitlab.com/gitlab-org/gitlab-ce/issues for future reports

**Comment by FiW** [comment]
oh, thanks, I have found it in FireFox! But I never seen it in Chrome.
