### ISSUE TITLE
Support Forum: Account suspended and I did not do anything! How can that be?

### ISSUE THREAD

**Issue by AlexL777** [gitlabhq/gitlabhq#10487]
Hello developers,
What kind of support forum is this if you get locked after the first question? I need help because Gitlab ee does not work and there you just lock my account in the forum. For support forums are there to get help or I understand that wrong?

Now I can no longer answer or ask questions and need timely assistance with "redis.socket", which can not be created. Several times Gitlab-ee reinstalled, but redis still does not start. So what else can I do.

Thank you.

**Comment by mkozono** [comment]
Please note that GitLab does not monitor this mirror or its issue tracker (on GitHub). There are a variety of ways to get help with GitLab https://about.gitlab.com/getting-help/, and in particular see how to reach support here https://about.gitlab.com/support/.
