### ISSUE TITLE
Add me to gitlabhq GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [gitlabhq/gitlabhq#10481]
Hey,

I am really excited about the active development and wanted to be a part of the **gitlabhq** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is **YoginthS**

Thanks, Yoginth

**Comment by mkozono** [comment]
Please check out https://about.gitlab.com/contributing/

Thank you!
