### ISSUE TITLE
Hooks being called many times

### ISSUE THREAD

**Issue by jizaymes** [gitlabhq/gitlabhq#3794]
Hello,

I have a simple hook using the gitlab-campfire-hook project. When I issue a push to a repo, the expected behavior is for the hook to be called once, and to post a message in Campfire about it. Since upgrading to 5.1 (previously 3.1), this action triggers up to 10 times at random intervales since the initial commitment. I suspect this to be a gitlab thing more than a gitlab-campfire-hook thing since it seems like it appears to be a matter of queuing. Any ideas how to troubleshoot this to stop this inconvenient but not super critical behavior?

9:00 AM
API U.	Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019
Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019
Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019
9:05 AM
API U.	Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019
Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019
9:10 AM
API U.	Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019
9:25 AM
API U.	Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019
9:50 AM
API U.	Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019
10:30 AM
API U.	Changes pushed to Customer LB Configs - HAProxy::master by cust-lb with message: updated maxconn to 4 per ticket 216019

**Comment by L0rD59** [comment]
Hi all,

same issue, here, but i thinks it's do to a long time process, i execute a bash, with many command, and one of them take a long time, if i remove it, it's work.

**Comment by ngeorgieff** [comment]
I have the same problem with version 7.8.4. It's randomly firing the web hooks multiple times after with or without any push.

![screen shot 2015-06-02 at 3 59 42 pm](https://cloud.githubusercontent.com/assets/2789581/7949232/c584ae36-0940-11e5-926b-6d91086f7acf.png)

**Comment by rinasek** [comment]
Hi there,

Same issue with 7.10.4. I fire hook on merge request to execute build for testing purposes. 

This  has become problem as hook started build during client review (i forgot that this is happening). Any thoughts what could be causing problems?

Thanks

**Comment by kolomiichenko** [comment]
You are need send HTTP Status code 200 OK because when ProjectWebHookWorker failed his - trying after few minutes. You can look thin in sidekiq.log

**Comment by mkeremguc** [comment]
issue still exists. no matter i respond with 200 OK or increase webhook_timeout. actually it completes the hook successfully but calls the hook randomly again and again

**Comment by GameCharmer** [comment]
I'm running 7.12.2 and it's still an issue.

I gave up on this being fixed and decided to write a small handler connected to a database.  Commits come in, it checks to see if it's already fired, and if not, it'll trip the proper web hook.  It sucks that I had to write a tool to deal with something like this, but so far it's been the only way over the past couple years to keep stuff from firing multiple times.

**Comment by ngeorgieff** [comment]
Anyone with idea or workaround?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
