### ISSUE TITLE
Pushing big commits over HTTPS gives a 502

### ISSUE THREAD

**Issue by foux** [gitlabhq/gitlabhq#3882]
Hello,
I'm using github 5.1 with Apache.
Pushing via ssh works like a charm, but when I try to push large commits via https, I've got this problem :+1: 

    Counting objects: 45514, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (11158/11158), done.
    Writing objects: 100% (45514/45514), 21.16 MiB | 135 KiB/s, done.
    Total 45514 (delta 33925), reused 45323 (delta 33776)
    error: RPC failed; result=22, HTTP code = 502
    fatal: The remote end hung up unexpectedly
    fatal: The remote end hung up unexpectedly
    Everything up-to-date

My apache error logs prints this : 
    (103)Software caused connection abort: proxy: pass request body failed to 127.0.0.1:3000 (127.0.0.1)
    proxy: pass request body failed to 127.0.0.1:3000 (127.0.0.1) from 2.12.157.247 ()

I've got nothing in my application log, nor in the puma logs.

Any idea on how to solve this?
Thanks

**Comment by faridskyman** [comment]
wanted to update, i tried 'drmonty' suggestion::

git config --global http.postBuffer 524288000

It works and now i can PUSH,

thx

**Comment by mckaygerhard** [comment]
this bug its a pain! if user has a different version of git, that also happened with ALL cloning! including SSH clones!

the problem when i change the value, if this not return to a more little this happened:

git-remote-https(52011,0x7fff7011acc0) malloc: ***
mmap(size=18446744071938875392) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
git-remote-https(52011,0x7fff7011acc0) malloc: ***
mmap(size=18446744071938875392) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
fatal: Out of memory, malloc failed (tried to allocate
18446744071938872320 bytes)

so the value set must be retunr to default (1M) or to a more little...

BUT IF USERS MADE THAT AS ROOT CLONE OR PUSH ARE DONE! try to swicht to root (not using sudo) with su, and made a clone and everithing its works! of course that its not ideal case!

**Comment by fibric** [comment]
On each developers machine, we executed `git config --global http.postBuffer 524288000` and now nobody has any push issue anymore.

**Comment by Petrox** [comment]
Let's make this clear: http.postBuffer being small is just one way to produce this issue, so if it solves that for you, that's fine, but probably the timeout limit is the other problem.


Also some users have problems after raising that limit over 500megabytes, even when the push would be just 20mbytes... 

This bug even affects http://gitlab.com 

```
POST /xxx/yyy.git/git-receive-pack HTTP/1.1
Authorization: Basic xxx
User-Agent: git/1.9.1
Host: gitlab.com
Accept-Encoding: gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Content-Length: 28291994

* The requested URL returned error: 500 Internal Server Error
* Closing connection 1
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
Command exited with non-zero status 1
1.94user 0.30system 2:33.97elapsed 1%CPU (0avgtext+0avgdata 41192maxresident)k
0inputs+0outputs (0major+12620minor)pagefaults 0swaps
```
 
I'd like to note, that HTTP 500 is an "Internal server error", that is not an acceptable answer in any usecase. https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error

(Sometimes I get 502, with the same commandline)

Please let me know when this is fixed, as it's currently a blocking problem.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Comment by mojca** [comment]
I opened the ticket here: https://gitlab.com/gitlab-org/gitlab-ce/issues/17917

Please excuse me, I wasn't sure which details to copy over. Feel free to add or edit whatever seems appropriate.

**Comment by rapsys** [comment]
This comes from this bug still not fixed !!! :
https://bz.apache.org/bugzilla/show_bug.cgi?id=45449
http://svn.haxx.se/users/archive-2003-08/0763.shtml
http://svn.haxx.se/users/archive-2006-03/0549.shtml

Quickfix is test how behave your server with :
export GIT_CURL_VERBOSE=1
Look last failing move urls (both MOVE url and Destination header of the request).

Then test with :
curl --user 'user:pass' --basic -X MOVE --header 'Destination:DEST_URI' 'MOVE_URI'

See result.

If it works by replacing https: with http: in Destination it is that bug, I have it with latest apache 2.4.20 and git 2.9.0, still not fixed...

A workaround from 2008 :
RequestHeader edit Destination ^https: http: early

**Comment by kneufeld** [comment]
Make sure your webserver isn't out of disk space. That was my issue.

**Comment by pietroaragona** [comment]
This configuration:
git config --global http.postBuffer 524288000

works for me.
Thanks @mrohnstock
