### ISSUE TITLE
I cannot Enter Chinese title in wiki inside gitlab

### ISSUE THREAD

**Issue by jw2007like** [gitlabhq/gitlabhq#3913]
I cannot Enter Chinese title in wiki inside gitlab.

I was a programmer in mainland China. My mother language is Chinese.

Our team is migrating from svn to git. Many colleagues are learning git. I try to use gitlab set up a git server. I found a problem, is wiki system inside gitlab, can not enter the Chinese title. For example, I wanted to write a "How to setup” document. How to setup in Chinese is “如何安装”。

1.I try enter “如何安装”in wiki.
![01](https://f.cloud.github.com/assets/4402641/491348/3a820bbc-ba19-11e2-8a22-54a98bbe8c61.jpg)

2.wiki 404 error
![02](https://f.cloud.github.com/assets/4402641/491349/90b0d0ae-ba19-11e2-9fd2-dd918153a384.jpg)

3.I can write English title in wiki inside gitlab.
![03](https://f.cloud.github.com/assets/4402641/491350/97b0f0c8-ba19-11e2-8130-96be09af58ec.jpg)

4.It works
![04](https://f.cloud.github.com/assets/4402641/491351/9ccddd0a-ba19-11e2-8368-6f2cb3fae34b.jpg)

1.I use wiki in http://bitbucket.org/。enter Chinese title. It works.
![05](https://f.cloud.github.com/assets/4402641/491352/a3bdd552-ba19-11e2-8f4f-d97d0f2758bc.jpg)

2.wiki system in bitbucket.org .Enter Chinese title.It works.
![06](https://f.cloud.github.com/assets/4402641/491353/a6a56b22-ba19-11e2-9c5d-55a14633bbb9.jpg)

question

 I use gitlab version 5.0.How can I enter Chinese title in wiki inside gitlab?

**Comment by 0oneo** [comment]
any plan to solve this?

**Comment by JiffsMaverick** [comment]
Same issue for Russian language on 7.9-stable and 7.10-stable.

**Comment by toplinuxsir** [comment]
Same issue for gitlab 8.5.3!
The problem still exist!

**Comment by lightinen** [comment]
8.5.4 the same

**Comment by stanhu** [comment]
This is fixed in GitLab 8.6.

**Comment by jyunfan2015** [comment]
yes,i try to use,it works. My gitlab version is 

System information
System:         Ubuntu 16.04
Current User:   git
Using RVM:      no
Ruby Version:   2.3.3p222
Gem Version:    2.6.6
Bundler Version:1.13.7
Rake Version:   10.5.0
Sidekiq Version:4.2.7

GitLab information
Version:        8.15.2

![01](https://cloud.githubusercontent.com/assets/12136292/21579767/2adec716-cffc-11e6-92a8-c6c3efe33755.png)
