### ISSUE TITLE
Importing existing repositories directly from the repositories path requires clarification.

### ISSUE THREAD

**Issue by tnarik** [gitlabhq/gitlabhq#4137]
Related to #3693, #3297, #2932, #3636, #3926 and https://github.com/gitlabhq/gitlabhq/wiki/Import-existing-repositories-into-GitLab.

The way I see it:

1. Bare repositories copied to /home/git/repositories and imported with 5.x are not copied but just created inside the 'admin' namespace
  For instance: ```/home/git/repositories/repo.git``` will be left there and a new and empty ```/home/git/repositories/admin/repo.git``` will be created.
2. Instead, if #2932 is used to patch the system, the repository will be used as is.
  For instance: ```/home/git/repositories/repo.git``` will be added to GitLab and files will be available.
3. ```rake gitlab:import:repos``` (from 5.2) only works from /home/git/repositories, not any subfolder, so without any changes, it will create empty repos under the 'admin' namespace.
Then the existing repositories can be moved on top of the new ones, replacing for instance the empty ```/home/git/repositories/admin/repo.git``` with the contents of ```/home/git/repositories/repo.git```, which will make files available.

It would be great if the wiki is updated to reflect the current solution (which as far as I know is as described in 3.) and additionally the way forward is described (commit 5f9d78fdff746a0b50313cf415acac809569a186 is meant to allow importing of repositories inside namespaces [and it works in spite of displaying an error because it cannot create the 'admin' group], but it doesn't seem to take care of the global namespace, for what I saw).

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
