### ISSUE TITLE
Deleting user deletes should not delete...

### ISSUE THREAD

**Issue by mvrhov** [gitlabhq/gitlabhq#4295]
Thanks to this bug I just lost about 40 tickets :-1: 

When user is deleted the tickets assigned to him should just lost the assignee.

IMO something like that should also apply to the tickets created by a user which is about to be deleted.

**Comment by dosire** [comment]
@randx I think that when you delete a user there should be a big warning that any content would be deleted and that it is advised to block them. Or we need a ghost user.

**Comment by dosire** [comment]
@randx I think that when you delete a user there should be a big warning that any content would be deleted and that it is advised to block them. Or we need a ghost user.

**Comment by 123Haynes** [comment]
@dosire I think we need the ghost user anyway.  
Otherwise you will loose data when a user decides to delete himself.  
In that case he probably won't care about a warning.

**Comment by dosire** [comment]
@123Haynes that makes sense to me

**Comment by randx** [comment]
I agree we should keep issues and merge requests but replace author and assingee of removed user to something else. 

I like idea of `ghost` user since it will allow us to place minimal changes in code base. Not sure how to deal with cases when username for `ghost` user is already taken :)  
Anyway it looks pretty simple to me: 
* create a migration with ghost user
* add ghost user to fixtures for new installations
* remove dependent destroy for issue/merge request in User model
* when deleted -> replace author_id with ghost user and assignee_id with nil

__It would be great if someone could contribute this improvement - otherwise we will do in 7.9 or 7.10__

**Comment by bbodenmiller** [comment]
How about just removing the ability to delete an account or converting the current blocked functionality to delete? Essentially allow accounts to be deleted but don't actually delete the account just mark it as inactive. Then give admins the ability to restore accounts.

**Comment by randx** [comment]
Disabling a user is also an option. Instead of `Delete account` use `Disable account`. Lets see what others think

**Comment by dosire** [comment]
@randx with disable you mean block, right?

**Comment by bbodenmiller** [comment]
Assuming @randx means the same thing with disable and block, I do think disable is better naming.

**Comment by 123Haynes** [comment]
if we go with disabled, I think we should mark these users somehow so other people know they won't repsond anymore.
Maybe another color of the username or add "(deleted)" at the end of the name or something like that.
The disabled user mustn't receive emails for mentions anymore either.

**Comment by Razer6** [comment]
[https://github.com/ghost](https://github.com/ghost) is the user GitHub maps all deleted users to.

**Comment by vsizov** [comment]
I think we should avoid the user deletion. it is conventional. But  locked
users shoud be marked with icon or something like that.

**Comment by 123Haynes** [comment]
I actually prefer the ghost user solution.
That way people who want to delete their account also delete their personal data.
There isn't really much value in keeping the deleted accounts and it'll allow a cleaner user management.

Imagine a university using gitlab for example. 
Every semester a lot of students will get access to gitlab, but also a lot of students leave so they delete the accounts. If we only disable the accounts the database will only get bigger and bigger with lots of dead accounts that noone really needs anymore.

**Comment by bbodenmiller** [comment]
I disagree. If a user deletes their account I still want to know where the data originated from. I agree we can hide their email, profile, prevent tagging, etc. but I'd still like issues, comments, etc. to show who originally made them. Additionally let's say they leave the company or university for awhile and then return, I'd like to reenable their previous account rather than create a new one.

**Comment by dblessing** [comment]
@123haynes I worked with online course management systems in my previous job. They all take the approach that users can't be deleted. Comments, submissions, etc should continue to be attributed to the user that created them. It's perfectly reasonable to delete private content - repos and things when disabling. I don't think a growing database should be a concern.

**Comment by 123Haynes** [comment]
@dblessing @bbodenmiller Ok... I get you point.
It's still different from blocking a user when we delete things like mails or private repos.
I also think that deleting a user is somewhat final. Even if we keep the account, I don't think we need to add the ability to revive it.
The user can just create a new account.
In case they want to use their old username, the admin could simply change it on the old account.
This case won't occur very often so I don't think it's worth the hassle of implementing a revive function.

I'd like to make it clear to the admin that deleting a user is different from blocking them.
 * Blocking
    * retains all data
    * prevents access 
    * can be reverted
 * Deleting
    * deletes private data
    * prevents access
    * can't be reverted.

**Comment by randx** [comment]
I think that for private instances users are managed by companies and as a company you don't want user to remove account with all data. I don't even think it makes sense to have block/remove feature available for user. The only difference is GitLab.com where I have no idea yet. Wondering how services like dropbox handle i.

**Comment by dosire** [comment]
I agree with @123Haynes, blocking is reversible, deleting removes the name of the user everywhere. I think we should have a setting where you prevent users from deleting themselves, some enterprises might want want this for traceability.

**Comment by randx** [comment]
With current behavior user can remove himself only if signup enabled.  

We anyway need ghost user for instances like GitLab.com. We dont want to loose issues and merge requests when user removes himself.

**Comment by bbodenmiller** [comment]
I still disagree that delete & block should be different (e.g. Delete profile on Facebook is a reversible action, delete branch on GitHub is reversible, etc.) however I can live with that. That being said in the delete scenario I'd still like to see names remain with the public content (issues, comments, etc.). Many other systems treat writing & author name as irreversible once wrote:
* Facebook comments remain in original form on account deletion
* Sent emails remain in original form on account deletion
* git commits remain
* Books & papers cannot be unwrote

**Comment by 123Haynes** [comment]
@bbodenmiller I think the deleting is important for privacy reasons. It doesn't make much sense for companies, but for instances like gitlab.com it may attract more people if they know that they are able to delete their private data.
But I'm ok with keeping the name. So delete could be:
 * Delete everything in the personal namespace of that user and all private projects where noone else has access
 * Delete his mail addresses/ replace with a dummy mail
 * Disable all notifications in the settings of that user
 * Delete his ssh keys
 * Delete his authorized applications
 * Prevent access (maybe block the user, but add a deleted flag?)
 * Make it known to other people that this account is deleted (i.e. with an icon)

Like this it would be like blocking a user, but the user doesn't have to manually delete all his private data.

**Comment by bbodenmiller** [comment]
@123Haynes Sounds good. I'd like to see an option to disable the delete feature however.

**Comment by 123Haynes** [comment]
@bbodenmiller I guess we could add an option to the settings page in the admin area to enable/disable this instead of reusing the signup enabled setting.

**Comment by JobV** [comment]
We're now accepting MRs for this feature: http://feedback.gitlab.com/forums/176466-general/suggestions/9001993-keep-issues-and-merge-requests-when-user-is-remove

**Comment by sclarson** [comment]
This also deletes owned groups and projects which can be an even greater data loss.

**Comment by randx** [comment]
@sclarson it deletes only user project like `:username/:project`which makes sense. Groups are not deleted.

**Comment by Blazeflack** [comment]
Has this been addressed yet?

I see @randx mentioned it would be done in 7.10 or 7.11, but I was unable to find any mention of it in the changelog. This ticket is also still open which indicates that it may not have been fixed yet, but I would like to know for sure.

I'm part of a community where we need people to be able to sign up on their own, so we don't have the option of disabling sign up to prevent them from deleting their own user.

I appreciate any information you can give me on this matter.

Thank you.

**Comment by DouweM** [comment]
@Blazeflack The issue has not yet been addressed. I've created an issue on our canonical tracker at https://gitlab.com/gitlab-org/gitlab-ce/issues and scheduled for 8.6: https://gitlab.com/gitlab-org/gitlab-ce/issues/12726

**Comment by Blazeflack** [comment]
@DouweM Thanks for clarifying it for me, and thanks for the link. I can now keep track of the progress :).

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
