### ISSUE TITLE
mail send wrong merge request id after upgrade to 6.1

### ISSUE THREAD

**Issue by justlaputa** [gitlabhq/gitlabhq#5303]
Hi,
  I have upgraded gitlab to 6.1 last week, but now I met some problem.

  The merge request and issue ids are changed to internal id, and they works well in gitlab web page. But when I create new Merge Request, in the email sent by gitlab, the url of merge request is wrong. Here is the latest of my email of new merge request:

project    MR id in mail URL
A             150
A             151
A             152  before upgrade
A             153  --------
A             154  after upgrade
A             105
A             106
A             157
A             108
A             159
A             110
B             161
B             162
B             163

  But when I add comment on the newly created MR, the mail for comment has right merge request id.

  I'm confused about this problem, does anyone met the same? Or can you tell me which part of my configuration could be wrong?

Thanks very much!

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
