### ISSUE TITLE
git account locked preventing interaction through ssh

### ISSUE THREAD

**Issue by williamledoux** [gitlabhq/gitlabhq#5304]
1. **Summary:** After following the (awesome) 6.1 installation guide, user git was locked ( `!` as password in the `/etc/shadow` file ) thus preventing interaction through ssh.
2. **Steps to reproduce:** I assume installing gitlab on an elementary OS Luna (ubuntu based) distribution
3. **Expected behavior:** interaction through ssh work, or some error appears in the checks 
4. **Observed behavior**: All checks are ok, but push through ssh will fail with a `Permission denied (publickey)` and `/vat/log/auth.log` saying `User git not allowed because account is locked`
5. **Relevant logs and/or screenshots:** 
6. **Output of checks**

		System information
		System:		elementary OS 0.2
		Current User:	git
		Using RVM:	no
		Ruby Version:	2.0.0p247
		Gem Version:	2.0.3
		Bundler Version:1.3.5
		Rake Version:	10.1.0

		GitLab information
		Version:	6.1.0
		Revision:	b595503
		Directory:	/home/git/gitlab
		DB Adapter:	mysql2
		URL:		https://gitlab.CENSORED.fr
		HTTP Clone URL:	https://gitlab.CENSORED.fr/some-project.git
		SSH Clone URL:	ssh://git@gitlab.CENSORED.fr:PORT/some-project.git
		Using LDAP:	no
		Using Omniauth:	no

		GitLab Shell
		Version:	1.7.1
		Repositories:	/home/git/repositories/
		Hooks:		/home/git/gitlab-shell/hooks/
		Git:		/usr/bin/git

And

		Checking Environment ...

		Git configured for git user? ... yes
		Has python2? ... yes
		python2 is supported version? ... yes

		Checking Environment ... Finished

		Checking GitLab Shell ...

		GitLab Shell version >= 1.7.1 ? ... OK (1.7.1)
		Repo base directory exists? ... yes
		Repo base directory is a symlink? ... no
		Repo base owned by git:git? ... yes
		Repo base access is drwxrws---? ... yes
		update hook up-to-date? ... yes
		update hooks in repos are links: ... 
		IMA / AAE ... ok

		Checking GitLab Shell ... Finished

		Checking Sidekiq ...

		Running? ... yes

		Checking Sidekiq ... Finished

		Checking GitLab ...

		Database config exists? ... yes
		Database is SQLite ... no
		All migrations up? ... yes
		GitLab config exists? ... yes
		GitLab config outdated? ... no
		Log directory writable? ... yes
		Tmp directory writable? ... yes
		Init script exists? ... yes
		Init script up-to-date? ... yes
		projects have namespace: ... 
		IMA / AAE ... yes
		Projects have satellites? ... 
		IMA / AAE ... yes
		Redis version >= 2.0.0? ... yes
		Your git bin path is "/usr/bin/git"
		Git version >= 1.7.10 ? ... yes (1.8.4)

		Checking GitLab ... Finished

**Possible fixes**: 

* replace password by `*` (disabled) instead of `!` (locked) in `/etc/shadow`
* detect it and show it in the post installation gitlab checks

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
