### ISSUE TITLE
[5-4-stable to 6-0-stable]: rake migrate_global_projects fails when target directory not empty

### ISSUE THREAD

**Issue by Philzen** [gitlabhq/gitlabhq#5372]
When the target directory `{OWNER_NAMESPACE}/{PROJECT_DIR}` already contains a repository the rake task will just respond with `Cannot move project. \nF`. No error information is displayed or found in the log.

_Solution_: rename or remove the target-empty directory to make way. Rake task will complete successfully after that.

Possibly related to #4979

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
