### ISSUE TITLE
6.2.1 LDAP user initial login

### ISSUE THREAD

**Issue by animedbz16** [gitlabhq/gitlabhq#5490]
When a new user logs into GitLab via LDAP.

They receive an email such as:
~~~~~
Welcome firstname_lastname@domain.com!

You can confirm your account through the link below:

Confirm my account
~~~~~

However, when clicking on this link does not confirm the account but prompts to a page to send out a new confirmation. When entering your email address, GitLab informs you that this account was already confirmed.

Probably because the user was created via LDAP and would not need confirmation.

This should probably be updated to not send a account confirmation email, but a generic welcome email.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
