### ISSUE TITLE
Charset windows-1251

### ISSUE THREAD

**Issue by dyadyaMisha** [gitlabhq/gitlabhq#5493]
How can I fix this?

![2013-10-31_161707](https://f.cloud.github.com/assets/964288/1444016/8020cae4-41fc-11e3-8c2d-63d51e77998f.png)

**Comment by xRayDev** [comment]
@dyadyaMisha 
fix in comment https://github.com/gitlabhq/gitlabhq/issues/5493#issuecomment-27467819 
still work but files for pathing in new version github here
/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/encoding_helper.rb
/gem/ruby/2.1.0/gems/gitlab-grit-2.6.12/lib/grit_ext.rb

Fix method still same.

Probably we will not see a fix as their ears. And we will apply the patch with the release of each version. :(

**Comment by XVilka** [comment]
Can someone prepare the tests, but not in the test repository format but something like:
"bytestream" => decoded text?
To try to go deeper through gitlab and even charlock_homes - directly to the ICU?

**Comment by exuperok** [comment]
@xRayDev i have tried to apply this patch to the files that you mentionned in my GitLab 7.7.2 install and all i get is an error 502 page.

**Comment by xRayDev** [comment]
@exuperok I not try this fix on Gitlab version 7.7.2. My GitLab version 7.7.0.

**Comment by xRayDev** [comment]
@XVilka I can post file from my repo with windows-1251 cyrillic encoding

**Comment by exuperok** [comment]
that will be helpful, thank you for your answer

**Comment by exuperok** [comment]
@xRayDev did you post them on your blog or on a git repository that i can look into?

**Comment by xRayDev** [comment]
@exuperok Of Course. Here diff https://github.com/xRayDev/gitlab_windows1251/commit/ac65ae9bbafe528566324e6065bf867658ec4dec for Installed gitlab_7.7.1-omnibus.5.4.1.ci-1_amd64.deb

**Comment by xRayDev** [comment]
@XVilka Here sample thah bug
Origianl files https://gist.github.com/xRayDev/e1421f9505c6a1fa29db
Files in repo https://github.com/xRayDev/gitlab_windows1251/commit/6ff819a87b364ec7d572a06ba78dc0f2bca86b6b

**Comment by gsbelarus** [comment]
I think automatic recognition will work only on specific set of cases. The easiest solution is to add a parameter "Default codepage" to a repository's settings page. Then use specified codepage every time while converting non UTF-8 data.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
