### ISSUE TITLE
User management issues when using multirealm authentication provider

### ISSUE THREAD

**Issue by safar** [gitlabhq/gitlabhq#5495]
This is a follow up on issue #5464 and problems discovered after update to 6.2.
###  Environment description
I have setup GitLab 6.2 with omniauth-shibboleth authentication provider. It currently operates inside a federation consisting of 230 different Identity Providers.

The problem I have discovered is caused by the fact that username must be unique per authentication provider, which in my case is shibboleth. Technically speaking provider is shibboleth, but in most cases shibboleth is used in federated SSO (Single sign-on) communities so it consists of many different identity providers. Shibboleth is just a "proxy" between them. This multi-realm nature of federated SSO communities causes the problem. 

User IDs in our federation are created by this simple rule: `first letter of the name + surname@realm.tld` , i.e. `jdoe@realm.tld`

### Scenario
Let's take this scenario as an example:
<table>
<tr><th>Realm:</th><th>realm1.tld</th><th>realm2.tld</th><th>realm3.tld</th></tr>
<tr><th>SSO Uid</th><td>jdoe@realm1.tld</td><td>jdoe@realm2.tld</td><td>fbar@realm3.tld</td></tr>
<tr><th>E-mail</th><td>john.doe@realm1.tld</td><td>john.doe@realm2.tld</td><td>foo.bar@realm3.tld</td></tr>
<tr><th>Generated GitLab username</th><td>john.doe</td><td>john.doe</td><td>foo.bar</td></tr>
<tr><th>Provider</th><td>shibboleth</td><td>shibboleth</td><td>shibboleth</td></tr>
</table>

John Doe can be the same person, but also it can be two different persons with the same first and last name the behaviour will be the same. <ol><li>When John Doe from realm1 logs into GitLab, it creates username john.doe by parsing first part of his email address.</li><li>When John Doe from realm2 now tries to log into GitLab it will get error 422 and production log will have an entry like this: `ActiveRecord::RecordInvalid (Validation failed: Username has already been taken, Username already exist):`</li>
<li>When Foo Bar logs in it will be successfully created since his email is unique and username still doesn't exist for provider shibboleth.</li>
</ol>

### Code responsible
[app/models/user.rb](https://github.com/gitlabhq/gitlabhq/blob/master/app/models/user.rb#L102)

```ruby
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
  validates :bio, length: { within: 0..255 }
  validates :extern_uid, allow_blank: true, uniqueness: {scope: :provider}
  validates :projects_limit, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :username, presence: true, uniqueness: true,
            exclusion: { in: Gitlab::Blacklist.path },
            format: { with: Gitlab::Regex.username_regex,
                      message: "only letters, digits & '_' '-' '.' allowed. Letter should be first" }

```

[lib/gitlab/oauth/user.rb](https://github.com/gitlabhq/gitlabhq/blob/master/lib/gitlab/oauth/user.rb#L60)

```ruby
        def username
          email.match(/^[^@]*/)[0]
        end
```

### Proposed solution

Instead of parsing email to get username when using oauth providers, username should be equal to extern uid. This solution requires change in username validator since only letters, digits & '_' '-' '.' are allowed. In case of John Doe from realm1 log in, his username should equal jdoe@realm1.tld. That way when another user from realm2 with the same name logs in it won't have a problem since its user name will be jdoe@realm2.tld and will still be unique.

Or maybe it can even be an SHA hash of extern uid so username validator doesn't have to be changed.

Just a thought but is username even necessary for users authenticated by oauth providers?

**Comment by DanScharon** [comment]
what is the status of this? does this mean that John Doe from realm2 still couldn't log in because the Generated GitLab username is identical to John Doe's from realm1?

**Comment by dosire** [comment]
@DanScharon Thanks for asking.

@jacobvosmaer What do you think about this?

**Comment by jacobvosmaer** [comment]
Issue: auto-creating users via omniauth can fail if unique attributes (e.g. username, email) are already taken

Workaround: with some identity providers, you can first create the gitlab user (via self sign-up or the admin panel) and then associate the external identity. (Not for LDAP I think.)

Possible solutions: automatically tack data (e.g. a number) onto the gitlab username (e.g. `johndoe123` if `johndoe` is taken). Or present a form to the user where they can pick a username.

BTW if we would go the first route (appending e.g. a number to the username) the user can still go into their account settings and choose a nicer username.

Adding the realm (when applicable) to the username sounds more difficult to me. `jdoe@realm1.tld` is not a valid gitlab username ATM.

**Comment by DanScharon** [comment]
> Adding the realm (when applicable) to the username sounds more difficult to me. jdoe@realm1.tld is not a valid gitlab username ATM.

what about replacing '@' with an underscore to separate the realm from the local part? Wouldn't that leave us with a valid gitlab username and be unique among realms at the same time?

**Comment by jacobvosmaer** [comment]
I think exactly how to change the username is a detail for the developers. But I would rather make sure there is a sequence of possible suffixes (like 1,2,3) to empower GitLab to avoid clashes than to create a 'nice' suffix and hope it is unique.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
