### ISSUE TITLE
Gitlab 6.0 - Cannot select namespace unless...

### ISSUE THREAD

**Issue by endzyme** [gitlabhq/gitlabhq#5540]
Gitlab 6.0 - Cannot select namespace unless you've created a group or are true owner of a group. 

Even if you are listed as an owner of a group the Namespace dropdown doesn't show up unless you've created a group and are the true owner (in db) of that group. 

Replicate: 

create 2 users
login as User1 and make two groups add a project to each group
Using User1 - add User2 as owner in those groups
login as User2 and try to add a repo to those namespaces (dropdown won't appear)
Using User1 - transfer the group to User2.
Login as User2 and add repo to namespace - both groups show up in the namespace dropdown.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
