### ISSUE TITLE
Cannot save whole bio on Edit-Profile-Page when entering 'special' characters

### ISSUE THREAD

**Issue by pmuens** [gitlabhq/gitlabhq#5625]
## Summary:
When I add a special character (such as '<') in the bio-Field on the Edit-Profile-Page and click 'save', my bio gets truncated.

## Steps to reproduce:
Open the Edit-Profile-Page. Type in the string 'I <3 programming'. and click 'save'

## Expected behavior:
The string gets stored in the database and will be displayed after the save in the text box for the bio.

## Observed behavior:
The string gets only stored up to the first occurrence of '<'. only 'I ' gets stored. What is more confusing is, that when one replace the character '<' with '>' ('I >3 programming') , '>' gets replaced with '&gt'.

I'm using your GitLab cloud.

Great job BTW!

**Comment by jvanbaarsen** [comment]
Still in 7.10.4-ee d17bba9
