### ISSUE TITLE
Orphan Deploy keys

### ISSUE THREAD

**Issue by floreal** [gitlabhq/gitlabhq#5685]
Hello,
I found out that when a deploy key is removed from the only project it is attached to, it is impossible to re-attach it to any project.
I think It would be great if it is possible:
1. to let this key appear in any project as available
2. to forbid removal of the key
3. or to remove it from keys table
Because project-less deploy key are neither usable nor recreatable (because of it's unique trait in the table structure).
Cheers,
Floreal

**Comment by rhilenova** [comment]
There is a general problem of adding duplicate deploy keys, even if it isn't orphaned. If you're trying to add a deploy key for a shared resource, but aren't a member of any project currently using the key, there is no way for you to add the key. You can't even see who is already using it to contact them.

**Comment by nyoxi** [comment]
This seems to be fixed in 7.11.2.

**Comment by jvanbaarsen** [comment]
@nyoxi Thanks for reporting back
