### ISSUE TITLE
"Project was moved" notification only shows new group/name

### ISSUE THREAD

**Issue by YenZi** [gitlabhq/gitlabhq#5723]
When user moves a project to another group, all members of that project get a notification mail. Unfortunately, this mail does not show the original name/group of that project. E.g.

group1/projFoo moves to barGroup/projNewName

The notification mail only says this : 

---

**GitLab | barGroup / projNewName**

Project was moved to another location

The project is now located under  barGroup / projNewName

To update the remote url in your local repository run:

git remote set-url origin git@gitlab.myserver.com:barGroup/projNewName.git

---

But it really should say : 

Project **group1/projFoo** was moved to another location

So the user has a chance to identify the project and knows where he should call the ```git remote set-url origin```

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
