### ISSUE TITLE
LDAP fails on long results

### ISSUE THREAD

**Issue by volfco** [gitlabhq/gitlabhq#5734]
I am working on getting GitLab setup in a university environment, and I am having trouble getting LDAP login to work. There are two types of accounts, Student and Service accounts. I am able to login with a service account, but I am not able with a student account. With the student account, I get an error upon entering my credentials "(ldap) account must provide an uid and email address." I have no such problem with the service accounts. Both types of accounts provide an email address in the response and work on other services, so the only think I can think is that GitLab is choking up on the length of the response.

ldap config is as follows:
`  ldap:
    enabled: true
    host: 'ldap.theuni.edu'
    base: 'ou=people,dc=theuni,dc=edu'
    port: 636
    uid: 'uid' #'sAMAccountName'
    method: 'ssl' # "ssl" or "plain"
    allow_username_or_email_login: true
    email_domain: 'theuni.edu'
`

Here is a dump from both types of accounts.
Student account:
`{'uniEduStudent': ['0000-XXXX-000-000', '0000-XXXX-000-00', '0000-XXXX-000-00', '0000-XXXX-000-00', '0000-XXXX-000-00', '0000-XXXX-000-00', '0000-XXXX-000-00', '0000-XXXX-000-00', '0000-XXXX-000-00', '0000-XXXX-000-00', '0000-XXXX-000-00', 'registered:current'], 'uniEduVanityName': ['colum'], 'displayName': ['Colum Mcgaley (Student)'], 'uid': ['cxm0000'], 'uniEduAccountType': ['Student'], 'title': ['Student'], 'objectClass': ['uniObject', 'uniEduIdentity', 'inetOrgPerson', 'person', 'organizationalPerson', 'uniEduEnrollment', 'uniEduOrganization', 'posixAccount', 'uniEduAuth'], 'loginShell': ['/bin/tcsh'], 'uniEduAffiliation': ['XXXXXXXXX', XXXXXXXXX', 'XXXXX', 'XXXXXXXX', 'XXXXX', 'XXXXXXXXXXXXXXXXX', 'Student', 'XXXXXXXX', 'XXXXXXXX'], 'uniEduPrimaryAffiliation': ['Student'], 'uidNumber': ['00000'], 'initials': ['CM'], 'mobile': ['900-5555-0000'], 'gidNumber': ['0000'], 'sn': ['Mcgaley'], 'homeDirectory': ['/home/cxm0000'], 'mail': ['cxm0000@uni.edu'], 'ou': ['Student'], 'givenName': ['Colum'], 'cn': ['Colum Mcgaley']}`

Service Account
`{'departmentNumber': ['undefined'], 'displayName': ['Colum McGaley'], 'cn': ['Colum McGaley'], 'uniEduAccountType': ['Studemp'], 'uniEduPrimaryAffiliation': ['Student'], 'objectClass': ['uniObject', 'uniEduIdentity', 'inetOrgPerson', 'person', 'organizationalPerson', 'uniEduEnrollment', 'posixAccount', 'uniEduAuth', 'uniEduOrganization'], 'uniEduAffiliation': ['Admissions', XXXXXXXX', 'XXXXX', 'XXXXXXXX', 'XXXXXX', 'XXXXXXXXXXXXXXXXX', 'XXXXXXX', 'XXXXXXXX', 'XXXXXXXX'], 'uidNumber': ['0000'], 'initials': ['CM'], 'mobile': ['000-000-0000'], 'gidNumber': ['0000'], 'sn': ['McGaley'], 'homeDirectory': ['/home/xxxxxx'], 'mail': ['something@uni.edu'], 'ou': ['Studemp'], 'givenName': ['Colum'], 'uid': ['something']}`

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues). Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
