### ISSUE TITLE
merge request on fork can be changed to MR for upstream. fails

### ISSUE THREAD

**Issue by Popl7** [gitlabhq/gitlabhq#5800]
When I fork a project on GL and I make a merge request on this fork I can first save this as a MR for the fork. (this was by accident)
I then changed the MR to be for the upstream project.
It is now listed as MR #1 on the upstream project.

This was on GL-cloud on the Cookbook project.
see: https://gitlab.com/gitlab-org/cookbook-gitlab/merge_requests
MRs #1 and #12

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
