### ISSUE TITLE
Don't receive notifications  (version:6.2)

### ISSUE THREAD

**Issue by booxood** [gitlabhq/gitlabhq#5837]
In "Profile settings" -> "Notifications" ->"Notifications settings" -> " Global setting"
I configuring "Watch".
`Watch – You will receive all notifications from projects in which you participate`

But,in my project,I add "New issue" or commit,don't receive email.

When add issue,is nothing.
When commit,"sidekiq.log" have add log:
`2013-12-13T04:18:48Z 27645 TID-owtolpfl4 PostReceive JID- INFO: start
2013-12-13T04:18:48Z 27645 TID-owtolpfl4 PostReceive JID- INFO: done: 0.096 sec`

P.S: Can receive reset password email,and change "Notifications settings" alse can receive email " access to project was granted ".

This is bug or configuring problem?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
