### ISSUE TITLE
Commit history repeats/skips days

### ISSUE THREAD

**Issue by awkay** [gitlabhq/gitlabhq#5863]
Running Gitlab 6.3 (had the same problem in 5.3). When I browse to the commits tab it lists the chronological history of commits. When I scroll down far enough to trigger the load of the "next page", it loads an overlapping range. If I then scroll further, it skips some days (as if it perhaps had not overlapped).

This makes historical code review a bit difficult.

Hard to get a screenshot, but I'll attach one. The dates on this list were, in order, Dec 16, Dec 13, Dec 12, Dec 11, Dec 11 (This looks to be the second "half" of the dec 11 commits...the pagination was clipped between the two), Dec 10, Dec 9, Dec 11 (repeat of the "continuation" of Dec 11 content), Dec 10, Dec 9, Dec 4, Dec 4, ...

It is not uncommon for us to have 20-30 commits a day...I'm guessing that when it breaks up a day of commits at a "pagination" boundary it get confused about where to resume.
  
![overlap](https://f.cloud.github.com/assets/1177083/1760394/ec3f5ffc-66ae-11e3-903c-78e35c4ad501.png)

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
