### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by sanledi-buli** [gitlabhq/gitlabhq#5904]
![screen shot 2013-12-23 at 2 07 52 am](https://f.cloud.github.com/assets/1153416/1798268/88f198ce-6b3c-11e3-8888-b628f6ad7ee3.png)
user developer cannot remove unprotected branch, on gitlab 6.3

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
