### ISSUE TITLE
SIGTERM - Sidekiq won't start

### ISSUE THREAD

**Issue by lolostates** [gitlabhq/gitlabhq#5949]
Hello all,

Following successive update from 6.0.0 to 6.4, i have several problems with sidekiq. This item refuse to start properly.
I try to start him manualy with : 
```ruby
sudo -u git -H bundle exec rake sidekiq:start RAILS_ENV=production
```
And i have this result: 

```ruby
rake aborted!
SIGTERM
/home/git/gitlab/lib/tasks/sidekiq.rake:9:in `system'
/home/git/gitlab/lib/tasks/sidekiq.rake:9:in `block (2 levels) in <top (required)>'
Tasks: TOP => sidekiq:start
(See full trace by running task with --trace)
```

I don't understand what is "system", a new gems ? 
I have no ideas how to start this module to launch finaly gitlab.

Thanks in advance,
Best regards.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
