### ISSUE TITLE
500 accidently on issue create/assign

### ISSUE THREAD

**Issue by oscx** [gitlabhq/gitlabhq#6004]
The error appears irregular which makes the conflict hard to reproduce. Do you have an idea what the root of mistake in this case? production.log:

Gitlab v.6.4.3

<pre>
Completed 200 OK in 93ms (Views: 0.4ms | ActiveRecord: 6.9ms)
Started GET "/meprogrp/mepasrc/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=" for 127.0.0.1 at 2014-01-08 08:41:36 +0100
Processing by Projects::IssuesController#new as HTML
Parameters: {"issue"=>{"assignee_id"=>"", "milestone_id"=>""}, "project_id"=>"meprogrp/mepasrc"}
Rendered projects/issues/_form.html.haml (262.1ms)
Rendered projects/issues/new.html.haml within layouts/projects (265.7ms)
Rendered layouts/_head.html.haml (2.6ms)
Rendered layouts/_broadcast.html.haml (2.8ms)
Rendered layouts/_search.html.haml (470.2ms)
Rendered layouts/_head_panel.html.haml (482.7ms)
Rendered layouts/_init_auto_complete.html.haml (0.9ms)
Rendered layouts/_flash.html.haml (0.3ms)
Rendered shared/_no_ssh.html.haml (2.8ms)
Rendered layouts/nav/_project.html.haml (21.9ms)
Completed 200 OK in 884ms (Views: 758.6ms | ActiveRecord: 36.8ms)
Started GET "/meprogrp/mepasrc/autocomplete_sources" for 127.0.0.1 at 2014-01-08 08:41:37 +0100
Processing by ProjectsController#autocomplete_sources as JSON
Parameters: {"id"=>"meprogrp/mepasrc"}
Completed 200 OK in 112ms (Views: 12.1ms | ActiveRecord: 9.8ms)
Started GET "/meprogrp/mepasrc/autocomplete_sources" for 127.0.0.1 at 2014-01-08 08:41:37 +0100
Processing by ProjectsController#autocomplete_sources as JSON
Parameters: {"id"=>"meprogrp/mepasrc"}
Completed 200 OK in 116ms (Views: 12.2ms | ActiveRecord: 9.3ms)
Started GET "/meprogrp/mepasrc/autocomplete_sources" for 127.0.0.1 at 2014-01-08 08:41:41 +0100
Processing by ProjectsController#autocomplete_sources as JSON
Parameters: {"id"=>"meprogrp/mepasrc"}
Completed 200 OK in 282ms (Views: 195.5ms | ActiveRecord: 8.0ms)
Started HEAD "/" for 127.0.0.1 at 2014-01-08 08:41:48 +0100
Processing by DashboardController#show as HTML
Completed 401 Unauthorized in 2ms
Started POST "/meprogrp/mepasrc/issues" for 127.0.0.1 at 2014-01-08 08:42:03 +0100
Processing by Projects::IssuesController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"vXp+funQnUNb3zD9jkBxZpMGrcw3kxm39aF7rxy30PE=", "issue"=>{"title"=>"cellaMonde()", "assignee_id"=>"8", "milestone_id"=>"", "label_list"=>"prio_normal", "description"=>"yet another short issue description...?"}, "project_id"=>"meprogrp/mepasrc"}
Completed 500 Internal Server Error in 1075ms
ArgumentError (invalid byte sequence in UTF-8):
app/controllers/projects/issues_controller.rb:61:in `create'
app/controllers/application_controller.rb:57:in `set_current_user_for_thread'
Started POST "/meprogrp/mepasrc/issues" for 127.0.0.1 at 2014-01-08 08:42:08 +0100
Processing by Projects::IssuesController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"vXp+funQnUNb3zD9jkBxZpMGrcw3kxm39aF7rxy30PE=", "issue"=>{"title"=>"cellaMonde()", "assignee_id"=>"8", "milestone_id"=>"", "label_list"=>"prio_normal", "description"=>"yet another short issue description...?"}, "project_id"=>"meprogrp/mepasrc"}
Completed 500 Internal Server Error in 778ms
</pre>

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
