### ISSUE TITLE
[6.4 stable] documentation: smtp settings clarification

### ISSUE THREAD

**Issue by samrocketman** [gitlabhq/gitlabhq#6023]
It seems very often we get people in IRC asking about email, how it is configured, or how gitlab handles it.  I think we need better documentation on it in two ways.  The first is an explanation of how the email in gitlab works on a very high level.  Example in my own words,

> Gitlab uses the system configured [sendmail](https://github.com/gitlabhq/gitlabhq/blob/6-4-stable/config/environments/production.rb#L75) to issue emails to users.  The recommended method is to configure your host sendmail so that it properly works and then Gitlab will successfully email as a result.
> 
> If configuring sendmail is not desirable, then Gitlab provides [`smtp_settings.rb`](https://github.com/gitlabhq/gitlabhq/blob/6-4-stable/config/initializers/smtp_settings.rb.sample) which can be used to override default Gitlab email settings.  This uses [`ruby net::smtp`](http://www.ruby-doc.org/stdlib-2.1.0/libdoc/net/smtp/rdoc/Net/SMTP.html) to configure email.  In order to properly configure it one must know the available `SMTP AUTH` methods allowed by their mail provider.  `ruby net::smtp` supports only three auth schemes: `PLAIN`, `LOGIN`, and `CRAM MD5`.

I think documenting this will remove a significant support burden when it comes to configuring Gitlab email so users aren't left to figure it out.  

And the second is including a link to `ruby net::smtp` documentation within `smtp_settings.rb`.

Just my 2c.

SAM

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
