### ISSUE TITLE
ghostery and gravatar

### ISSUE THREAD

**Issue by CircleCode** [gitlabhq/gitlabhq#6036]
when ghostery blocks gravatar, the layout seems a little bit unreadable (at least un merge requests), because of the alt positioned on gravatar image (the alt attributes contains the entire gravatar hash) going "under" commit message

![capture d cran de 2014-01-13 16 50 38](https://f.cloud.github.com/assets/668738/1901842/7cb2456a-7c6a-11e3-833c-5ddcb10918b2.png)

alt tag should be short for gravatar images…

**Comment by csware** [comment]
Cross-ref: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/503

**Comment by 123Haynes** [comment]
The fix from @csware has been merged into master and will be release with 7.10.
https://gitlab.com/gitlab-org/gitlab-ce/commit/63f0f6f31508c96f12e6e5c63af500b8cac6d13a
