### ISSUE TITLE
Unwanted Notifcation mails on merge commits

### ISSUE THREAD

**Issue by forki** [gitlabhq/gitlabhq#6044]
We are gettings tons of unwanted mails from gitlab.

![image](https://f.cloud.github.com/assets/57396/1910221/964d9202-7d11-11e3-8298-bd2ae1a3672d.png)

but commit ec9307 is a merge and no real person commented.

![image](https://f.cloud.github.com/assets/57396/1910236/cb7a6068-7d11-11e3-883d-5c007f80a08f.png)

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
