### ISSUE TITLE
6.4 Web Editor - 2 people using web gui to edit same file

### ISSUE THREAD

**Issue by mhoskiso** [gitlabhq/gitlabhq#6059]
Summary: If two people edit the same file with the web editor, the person who commits last removes all the changes the first committer made because the file is no longer current. I remember an error message in previous versions that the changes couldn't be saved because the file has changed. Can I enable this behavior?

Steps to reproduce: User 1 & 2 browse to the same file and use the web editor. User 1 edits and commits, then User 2 commits the old file with different edits.

Expected behavior: An error message pop up saying changes can't be commited because the file has changed when User 2 tries to commit the same file User 1 edited..

Observed behavior: The person that hits the commit button last removes all the changes of the first commit that occured while two people are using the web gui to edit the same file.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
