### ISSUE TITLE
"Create Merge Request" button is displayed after merge request is closed.

### ISSUE THREAD

**Issue by dpursehouse** [gitlabhq/gitlabhq#6070]
1. Checkout the master branch (assuming it's up to date with latest head of master on remote):

``git checkout master``

2. Push a new branch to the remote at gitlab:

``git push origin master:new-branch``

Note that this new branch should be the same as master, with no new commits.

3. On the project page, it shows that you've created the branch and shows the "Create Merge Request" link.

4. Create the merge request and note that it is showing nothing to merge.

5. On the local repository fetch the new branch, check it out, and push a new commit to the new branch on the remote:

``git fetch origin
git checkout origin/new-branch
touch test.txt
git add test.txt
git commit -m "New commit"
git push origin HEAD:refs/heads/new-branch``

6. Refresh the merge request page and see that it now shows the commit that you just pushed.

7.  Close the merge request (without actually merging).

8.  Go back to the project home page and see that it shows the "Create Merge Request" button again for the commit that was pushed at step 5.

Note: This is possibly same as (or similar to) #6034

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
