### ISSUE TITLE
ERROR -> Grit::Git::GitTimeout

### ISSUE THREAD

**Issue by sinaci** [gitlabhq/gitlabhq#6090]
I have successfully installed GitLab with this manual:
https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/installation.md

Everything is allright except the web edit functionality. When I try to edit a file from the web interface, write the commit message and hit to Commit Changes button; it waits for a while (10 seconds?) and says "your changes could not be committed because the file has been changed". The only error log I can see is "ERROR -> Grit::Git::GitTimeout" from githost.log.

I have tried to increase the timeout from gitlab.yml, but it did not work.

I have had a look at all related issues (204, 205, 815), but I could not find a solution.

**Comment by jbrooksuk** [comment]
@Razer6 when did GitLab move away from this? As of 7.6.2 I'm getting `Grit::Git::GitTimeout` error.

**Comment by Razer6** [comment]
Sorry, not GitLab went away from Grit only gitlab_git. GitLab still has calls to grit

**Comment by mantasradzevicius** [comment]
+1

any news?

**Comment by ayr-ton** [comment]
You guys can try to increase the timeout at gitlab.yml. The 7.0 and above has support to this.

**Comment by jbrooksuk** [comment]
Tried that. DInd't work.

**Comment by jbrooksuk** [comment]
What worked for me was running `git fetch` on the satellite repo.

**Comment by mantasradzevicius** [comment]
ok what worked for me was removing the according satellite, and using creating it freshly using command line ;)
