### ISSUE TITLE
Access denied to repositories after upgrade to GitLab 6.5.1

### ISSUE THREAD

**Issue by jirihnidek** [gitlabhq/gitlabhq#6138]
Hi, I upgraded Gitlab to 6.5.1 with upgrade script:

https://github.com/gitlabhq/gitlabhq/blob/v6.5.1/doc/update/upgrader.md

After upgrade any user is not able to do git pull/push command. The command is terminated with error:

    Access denied.
    fatal: The remote end hung up unexpectedly

At GitLab server I can see errors in `gitlab-shell.log`:

    D, [2014-01-23T11:54:05.356528 #26839] DEBUG -- : Performing GET https://gitlab.company.com//api/v3/internal/allowed?key_id=6&action=git-upload-pack&ref=_any&project=my_group/my_repo
    D, [2014-01-23T11:54:05.518040 #26839] DEBUG -- : Received response 200 => <false>.
    W, [2014-01-23T11:54:05.518279 #26839]  WARN -- : gitlab-shell: Access denied for git command <git-upload-pack 'my_group/my_repo.git'> by user with key key-6.

We uses LDAP authentication.

The command `/home/git/gitlab-shell/bin/check` returns 3 OKs.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
