### ISSUE TITLE
Project Sort

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#6148]
**Summary:**
i have a feeling that recent update and last update isn't doing what it should do, due to wrong information showing if I am right....

**Screenshot:**
![rawr34](https://f.cloud.github.com/assets/4362134/1992369/e4790744-84ba-11e3-8388-a69ca0d05678.png)

**Comment by Razer6** [comment]
This was heavily refactored. Closing for now.
