### ISSUE TITLE
Enable SSL peer verification for webhooks

### ISSUE THREAD

**Issue by harbulot** [gitlabhq/gitlabhq#6162]
The latest commit on branch 6-4-stable (317362666be9358a8fccb4e0e9c4640bb1a2ef71) disables SSL peer verification for all webhooks.

Unfortunately, this makes the connection vulnerable to MITM attacks. The new behaviour of HTTParty was addressing this problem. Re-introducing a potential vulnerability explicitly when it has been fixed by an underlying library doesn't seem great.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by harbulot** [comment]
@jvanbaarsen Fair enough. It was the latest release at the time. Looking at the latest code (commit 35729671fb3a123ddeb7b2b1cda446fd661bd4e6), the problem is still there:

https://github.com/gitlabhq/gitlabhq/blob/master/app/models/hooks/web_hook.rb#L42

I'm not sure what sort of debugging information you're after here. There's nothing specific to say, just don't use `verify: false`, it introduces a security vulnerability. That's all.
