### ISSUE TITLE
issue list is empty for non-member of internal project

### ISSUE THREAD

**Issue by Ahti** [gitlabhq/gitlabhq#6174]
I have an internal project with some issues.

For non-member (logged in users), the issues tab appears and shows the issue count badge. The user can also see milestones and access individual issues via the milestones.

If the user goes to the issue list, however, it is empty.

This is, imho, due to the `FilteringService` selecting the issues belonging to the user and then filtering them by project. It should select all issues of the project for internal projects, ignoring wether they are in the users issues or not.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
