### ISSUE TITLE
LDAP login in 6.5 not working if user in LDAP does not have email address

### ISSUE THREAD

**Issue by RaymiiOrg** [gitlabhq/gitlabhq#6180]
Issue: After the upgrade to 6.5 all users in LDAP without an email address attribute are unable to login. We have some users who do need access to gitlab but do not have an email address attribute in Active Directory (2008). This was working with 6.4.

Expected behaviour: users without email address attribute should be able to login to gitlab.

Workaround: adding the email address attribute to the AD account works, after that the user can login. When the email address is removed from AD the user cannot login anymore.

production.log:

	Processing by OmniauthCallbacksController#failure as HTML

	Parameters: {"utf8"=>"✓", "authenticity_token"=>"-", "username"=>"user@example.tld", "password"=>"[FILTERED]"}

	Redirected to https://<gitlab>.tld/users/sign_in

	Completed 302 Found in 84ms (ActiveRecord: 0.0ms)

	Started GET "/users/sign_in" for 127.0.0.1 at 2014-01-28 10:19:10 +0100

unicorn.stdout.log:

    E, [2014-01-28T10:20:23.289767 #30850] ERROR -- omniauth: (ldap) Authentication failure! ldap_error: OmniAuth::Error, (LDAP) Account must provide an uid and email address
    I, [2014-01-28T10:23:28.844448 #30850]  INFO -- omniauth: (ldap) Callback phase initiated.

Relevant config:

	  ldap:
	    enabled: true
	    host: '<ip>'
	    base: 'CN=Users,DC=example,DC=tld'
	    port: 389
	    uid: 'sAMAccountName'
	    method: 'plain' 
	    bind_dn: 'CN=Gitlab LDAP,CN=Users,DC=Example,DC=tld'
	    password: 'password'
	    allow_username_or_email_login: true

`bundle exec rake gitlab:check RAILS_ENV=production` returns LDAP users, even the ones without email address attributes. All other checks pass.

Information:

	bundle exec rake gitlab:env:info RAILS_ENV=production

	System information
	System:		Ubuntu 12.04
	Current User:	git
	Using RVM:	no
	Ruby Version:	2.0.0p353
	Gem Version:	2.0.14
	Bundler Version:1.3.5
	Rake Version:	10.1.0

	GitLab information
	Version:	6.5.1
	Revision:	6f6f158
	Directory:	/home/git/gitlab
	DB Adapter:	mysql2
	URL:		https://<gitlab>.tld
	HTTP Clone URL:	https://<gitlab>.tld/some-project.git
	SSH Clone URL:	git@<gitlab>.tld:some-project.git
	Using LDAP:	yes
	Using Omniauth:	no

	GitLab Shell
	Version:	1.8.0
	Repositories:	/home/git/repositories/
	Hooks:		/home/git/gitlab-shell/hooks/
	Git:		/usr/bin/git

**Comment by sagadave** [comment]
+1 for @neandrake's suggestion. We're trying to get gitlab to authenticate against an existing Open Directory LDAP server, and this does not contain *mail*, *email* or *userPrincipalName* attributes.

**Comment by rhew** [comment]
+1

**Comment by balamurugan99** [comment]
I do have the same issue . Is this fixed?

Thanks,
Bala

System information
System:         CentOS 6.5
Current User:   git
Using RVM:      no
Ruby Version:   2.1.4p265
Gem Version:    2.2.1
Bundler Version:1.5.3
Rake Version:   10.3.2
Sidekiq Version:2.17.8

GitLab information
Version:        7.7.2
Revision:       bd98290
Directory:      /opt/gitlab/embedded/service/gitlab-rails
DB Adapter:     postgresql
URL:            http://xxxx.com
HTTP Clone URL: http://xxxx.com/some-project.git
SSH Clone URL:  git@xxxx.com:some-project.git
Using LDAP:     yes
Using Omniauth: no

GitLab Shell
Version:        2.4.2
Repositories:   /data/repositories
Hooks:          /opt/gitlab/embedded/service/gitlab-shell/hooks/
Git:            /opt/gitlab/embedded/bin/git

**Comment by sohooo** [comment]
+1, same behaviour with OpenLDAP: `(LDAP) Account must provide an uid and email address`

**Comment by simshi** [comment]
I met a ldap issue similar though they're not same: https://gitlab.com/gitlab-org/gitlab-ce/issues/1286

**Comment by dnepangue** [comment]
Is this still an issue with current 7.10 release? I am trying to authenticate via an existing openldap with no mail or email attribute. The users can login but it get stuck on their profile page not unless I will edit their email manually from “ temp-email-for-oauth-<userid>@gitlab.localhost” .

**Comment by fumiyas** [comment]
FYI. With GitLab CE Omnibus 7.11.2, I've put the following Ruby snippet into
`/opt/gitlab/embedded/service/gitlab-rails/config/initializers/local.rb` to set a default email address.

```ruby
module OmniAuth
  module Strategies
    class LDAP
      class << self
        alias_method :map_user_orig, :map_user
      end

      def self.map_user(mapper, object)
        object['mail'] += ["#{object['uid'].first}@example.co.jp"]
        self.map_user_orig(mapper, object)
      end
    end
  end
end
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
