### ISSUE TITLE
repository is empty after update to 6.5

### ISSUE THREAD

**Issue by adrien59cadri** [gitlabhq/gitlabhq#6191]
Hello

I have an issue that looks like #5101 https://github.com/gitlabhq/gitlabhq/issues/5101

I updated from 5.1 to 6.0 and to 6.5.
I had all my repositories in non-global namespace.

At the end, everything went fine, except that when running `gitlab:check` task I get an output like this `MyNamespace / MyRepo ... repository is empty`.
These projects can not be browsed from the web interface, although the repositories do exist on the filesystem.

Some projects of the same namespace are fine, also several projects of various namespaces seems to be affected.
Most projects are fine, and I browse those on gitlab interface.
The repositories are in the right folder with the same rights than the others.
Another intersting thing is that for the same projects, the `gitlab:check` says that the namespace and sattelites are OK.

Do you have any idea to restore access to these projects from gitlab?

One solution I consider currently is to reimport those projects but I don't know if I could use the same project name (I wonder if it would confuse gitlab)

Thank you for your help

**EDIT : workaround**

For your information, If I do:

1. Go on the web interface of Gitlab,
2. go into one of this empty repository, Gitlab give me an option to create the repository (like after a fresh project creation).
3. click on edit
4. go in the setting tab
5. change the default branch of the project and save
6. change back the default branch and save

*everything is back to normal*

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
