### ISSUE TITLE
Performance issue with big diff

### ISSUE THREAD

**Issue by Ninir** [gitlabhq/gitlabhq#6193]
HI everyone.

First of all, I would like to thank you for the great work made over gitlab.
I'm facing an annoying issue with big diff.

Sometimes, you are in a case when a work can take some time (days, weeks). A lot of commits are in the pipe, and additions/deletions are important.

For example, I have a diff taking 59 commits, changing 121 files. Gitlab is showing a message regarding performance diff.

Commenting on the code is tough, because comment forms are taking seconds to load/display and then to create a message on the diff. Scrolling is slow, etc..

Is there a way to improve performances? is it in the pipe? it is quite annoying to make reviews on this.

Would be glad to help if you show me the light... ! :smile:

**Comment by Yety** [comment]
This is still an issue for me. Using 7.9.1 in Chrome and Safari. 

I have a diff which has the following stats:
"Showing 18 changed files with 547 additions and 15 deletions"

Scrolling get's slower the more downwards I go. Also the side-by-side view has better performance. If I disable JavaScript everything is smooth, but I can't comment particular lines anymore. 

I used the chrome developer tools to profile a bit and found out that there are two functions which seem to consume the most performance: 
*4031.6 ms30.87 %	4031.6 ms30.87 %	application-5ec…56308b0ed.js:4se.fn.extend.offset	
*4031.6 ms30.87 %	4031.6 ms30.87 %	application-5ec…6308b0ed.js:12A	
*4031.6 ms30.87 %	4031.6 ms30.87 %	application-5ec…6308b0ed.js:12D	
*4021.6 ms30.79 %	4021.6 ms30.79 %	application-5ec…56308b0ed.js:2se.event.dispatch	
*10.0 ms0.08 %	10.0 ms0.08 %	application-5ec…6308b0ed.js:12A

and 
*1356.6 ms10.39 %	1356.6 ms10.39 %	application-5ec…56308b0ed.js:4(anonymous function)	
*1356.6 ms10.39 %	1356.6 ms10.39 %	application-5ec…56308b0ed.js:2se.access	
*1356.6 ms10.39 %	1356.6 ms10.39 %	application-5ec…56308b0ed.js:4se.fn.(anonymous function)	
*1356.6 ms10.39 %	1356.6 ms10.39 %	application-5ec…6308b0ed.js:12D	
*1356.6 ms10.39 %	1356.6 ms10.39 %	application-5ec…56308b0ed.js:2se.event.dispatch	
*1356.6 ms10.39 %	1356.6 ms10.39 %	application-5ec…56308b0ed.js:2

I'm definetly not an expert in JS... Anybody out there who has an idea, what might be going on here?

**Comment by Ninir** [comment]
@randx Could we label this one as important please?
I'll have a look at the JS code, trying to find the issue.

**Comment by Yety** [comment]
Hey, I was already able to find some more details about it:
.add-diff-note in notes.scss seems to be one of the big perfomance eaters. If one comments out the lines 
```
position: absolute;
```
and 
```
    // transition: all 0.2s ease;
    //
    // "hide" it by default
    //opacity: 0.0;
    //filter: alpha(opacity=0);
```
there's already a noticeable perfomance improvement.

**Comment by Yety** [comment]
Seems as if it has been fixed recently:  c543cd1ed384b7b4f4f45e70e9e028a5db822671 For me it works fine now. Can you confirm it?

**Comment by Ninir** [comment]
@Yety Will check on the next release ;) (around April 22th)

**Comment by Ninir** [comment]
This is way better. Still some work to do to get faster, but the big diffs are now in better shape! :+1:

**Comment by Yety** [comment]
When I open a huge commit with approx 5k changed lines an several binaries changed I can scroll through the source code pretty smoothly now. But as soon as I enter the region where the blocks for the binaries with the description "No preview for this file type" browsing gets extremely slow again. Any ideas?

**Comment by randx** [comment]
@Yety can you make a sample repo for reproduce?

**Comment by Yety** [comment]
Yepp, will do it soon. But might take some days till I find time to create a sample repo. I can't use my current repo, because it contains proprietary code.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
