### ISSUE TITLE
Gitlab [6.5.1] Fails update metadata on moved repository

### ISSUE THREAD

**Issue by johnjelinek** [gitlabhq/gitlabhq#6206]
We had trouble downloading a repo via HTTP that was ~667MB, so we decided to go in an rewrite history to remove some binaries. To do this, we moved the gitlab repo, and pushed a version of the repo with history rewritten to the existing location. When I browse both repos in gitlab, I see the same number of branches in the dropdown on the files page and the home page of the repos present the same filesize (although it is really much smaller since we removed the binaries from history). Please let me know if you have any questions.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
