### ISSUE TITLE
Fork fails if namespace does not exist yet

### ISSUE THREAD

**Issue by nudgegoonies** [gitlabhq/gitlabhq#6228]
Trying to fork a project while the user hasn't created project yet, fails with the following message in the gitlab-shell log:
```
E, [2014-02-03T09:38:57.590259 #15146] ERROR -- : fork-project failed: destination namespace </var/lib/gitlab/repositories/USERNAME> does not exist.
I, [2014-02-03T09:38:58.193282 #15153]  INFO -- : Removing project USERNAME/PROJECT.wiki.git from </var/lib/gitlab/repositories/USERNAME/PROJECT.wiki.git>.
I, [2014-02-03T09:38:58.222668 #15151]  INFO -- : Removing project USERNAME/PROJECT.git from </var/lib/gitlab/repositories/USERNAME/PROJECT.git>.
```
After creating a new project the fork works.

My environment is this:
```
System:		Debian 7.1
Current User:	git
Using RVM:	no
Ruby Version:	1.9.3p194
Gem Version:	1.8.23
Bundler Version:1.1.4
Rake Version:	10.1.0

GitLab information
Version:	6.5.1
Revision:	9c8f584
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	1.8.0
Git:		/usr/bin/git
```

**Comment by Murazaki** [comment]
Guys, that's annoying and could surely be solved easily... Can't we create the folder if it doesn't exists when forking ? Also isn't the folder created when the user/group is ?

**Comment by Murazaki** [comment]
If gitlab-shell is the one that should create the folder, then you should check around here :
https://gitlab.com/gitlab-org/gitlab-shell/blob/master/spec/gitlab_projects_spec.rb#L118
https://gitlab.com/gitlab-org/gitlab-shell/blob/master/spec/gitlab_projects_spec.rb#L303

**Comment by bartoszcisek** [comment]
Unfortunately bug is still present in 7.5.3, creating own repository or simple mkdir works as workaround.

GitLab 7.5.3
GitLab Shell 2.2.0
GitLab API v3
Ruby 2.1.4p265
Rails 4.1.1

**Comment by per-garden** [comment]
This is a gitlab-shell issue really. The problem persists also in the latest Gitlab (7.11) and corresponding shell (2.6.3).

I've created a fix and corresponding pull request here: https://github.com/gitlabhq/gitlab-shell/pull/226

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
