### ISSUE TITLE
Not uploading a big project!

### ISSUE THREAD

**Issue by ncostis** [gitlabhq/gitlabhq#6240]
Trying to push a project of 100 mb i get the following error.
I am using gitlab 6.5.1 with git version 1.8.4, redis 2.6.14 and gitlab shell 1.8.0.

Counting objects: 1225, done.
Delta compression using up to 4 threads.
Total 1225 (delta 910), reused 1065 (delta 795)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; result=22, HTTP code = 411
Everything up-to-date
Done

Any ideas?

Thank you

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
