### ISSUE TITLE
Cannot Create & Update Groups after Upgrade from 6-5-stable to 6-6-pre

### ISSUE THREAD

**Issue by eRQee** [gitlabhq/gitlabhq#6255]
### With Gitlab 6.6.0-pre, I cannot create and edit groups anymore.

I've been checked out the branch master for testing purpose only with my current GitLab. 
Previous version applied was 6-5-stable. In the upgrade process , i found the error message that said **Could not find posix-spawn-0.3.8 in any of the sources** and **Could not find gitlab-grit-2.6.4 in any of the sources**. And according to some stackoverflow chit-chat I'd follow the recommendation to install that gems.

What I did:

``` bash
service gitlab stop && service nginx stop
cd /home/git/gitlab
gem install posix-spawn -v '0.3.8'
gem install gitlab-grit -v '2.6.4'
bundle install
sudo -u git -H git pull
sudo -u git -H git checkout master
service gitlab start && service nginx start
sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production
```

Later, GitLab branch 6.6-pre was successfully running well.

Unfortunately there still  : 
1. The picture chosen from local file won't show up on the picturebox area.
2. The groups cannot be updated anymore. Save button wont work and returned 500 Internal Server Error
3. Now I cannot create any more groups in my instance.

I do not know how to trace the error log beside this production.log tell me this:

```
Started POST "/admin/groups" for 36.75.245.197 at 2014-02-06 05:50:21 +0700
Processing by Admin::GroupsController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"aAwDNWIkR064lhutyxkjBJnmxKGDxsJ9/NvYlfDAnOc=", "group"=>{"name"=>"Snack Development", "description"=>"Workspace project-project kategory ringan, untuk peregangan jari dan/atau praktikum kecil2an."}}
Completed 500 Internal Server Error in 8ms
NoMethodError (undefined method `avatar_changed?' for #<Group:0x007fe2fb9e4180>):
app/models/group.rb:24:in `block in <class:Group>'
app/controllers/admin/groups_controller.rb:24:in `create'
app/controllers/application_controller.rb:57:in `set_current_user_for_thread'
```

May be anyone can check what the error is and fix it to bring a stable 6.6 release. :grinning:

**Comment by Razer6** [comment]
hope to be fixed
