### ISSUE TITLE
Group Avatar not working

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#6281]
**Summary:**
For some reasons, I can't see the group avatar i uploaded.
I check the image via right click and open image to another tab
the link given was `http://example.com/uploads/group/avatar/5/megane.jpg`.
then I checked my gitlab server and went to the path the link says. And this what I found
```
[git@Neko 5]$ pwd
/home/git/gitlab/public/uploads/group/avatar/5
[git@Neko 5]$ ls
megane.jpg
[git@Neko 5]$
```
**Screenshots:**![rawr45](https://f.cloud.github.com/assets/4362134/2119766/2d50e6e8-9187-11e3-83ca-207c228aab62.png)
![rawr46](https://f.cloud.github.com/assets/4362134/2119790/e9816bec-9189-11e3-8473-72e4c154830c.png)

**Logs:**
```
112.207.7.177 - - [09/Feb/2014:20:41:18 +0800] "GET /uploads/group/avatar/5/megane.jpg HTTP/1.1" 404 357
```

**Comment by jpscharf** [comment]
I was able to resolve the group avatar issue by updating my nginx config so the root folder was set correctly. Nginx was not basically failing at all requests, including request for static files and forwarding them to the ruby.

**Comment by Razer6** [comment]
Closing for now because seems to be fixed
