### ISSUE TITLE
Gitlab [6.5.1] Unable to view Merge Request I've submitted as a guest

### ISSUE THREAD

**Issue by johnjelinek** [gitlabhq/gitlabhq#6293]
When I create a merge request to a public repository where I am a guest, my merge request is created, but I cannot see it in the list (but the number of open MRs increases) in the parent repository.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
