### ISSUE TITLE
Commits that have been done after a merge request is not listed in this merge request but they are taken into account when accepting the merge request (but not listed in the closed merge request)

### ISSUE THREAD

**Issue by Poil** [gitlabhq/gitlabhq#6300]
1- have a project "A"
2- fork project "A" to "B"
3- commit/push a change to project "B"
4- do a merge request from "B" to "A"
5- commit/push a change to project "B"
6- view the merge request "4"
6-1 we can see the diff of the commit we did in 3 (not the step 5 one)
6-2 accept the merge request : commit 3 AND 5 is merged

Why commit "5" which is not part of the merge request has been taken into account ?

Best regards,

**Comment by fvztdk** [comment]
:+1: I close and reopen a merge request every time, to make sure it's has the most recent commits
