### ISSUE TITLE
Merge Requests are not intelligent on if another MR is referencing the same source branch

### ISSUE THREAD

**Issue by thomasbiddle** [gitlabhq/gitlabhq#6303]
There are times where someone may want to create a merge request to merge a branch into two branches, rather than just one. Workflow would state that we create two merge requests.

Example:

my_new_feature -> releases/v1.2
my_new_feature -> master

Currently, if someone goes to merge in the changes into one of these branches - they're given the option to "Delete the source branch". If the user marks this, then it will destroy the possibility of merging in the changes into the other branch.

I propose that we add logic to check the other open merge requests in the project to see if any of them reference the same source branch. If this is the case, the option to delete the branch should not be available and should instead state that another MR is referencing this branch.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
