### ISSUE TITLE
init script fails when run from within puppet on RHEL derivatives

### ISSUE THREAD

**Issue by deasmi** [gitlabhq/gitlabhq#6309]
When the supplied init script lib/support/init.d/gitlab is run from within puppet it can fail silently due to use of sudo. 

Tested on Centos 6.5 but believed to be the case on any RHEL derivative.

After adding debugging to capture the output of the init script running under puppet it transpired that sudo was refusing to run due to the lack of a tty.

On RHEL and derivatives the default /etc/sudoers includes
> Defaults    requiretty

which prevents this init script working under puppet. 

Commenting this line out makes everything work as expected.

Given that init scripts are typically/always run by root wouldn't using su be a safe alternative in this instance ?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
