### ISSUE TITLE
Gitlab states that it 'cannot connect to gitlab-ci server' but when pressing 'test settings' in Project => Services => GitlabCI the tests execute

### ISSUE THREAD

**Issue by shicholas** [gitlabhq/gitlabhq#6329]
From Gitlab-CI, there is a valid integration with Gitlab, but not from Gitlab's perspective.

Please let me know what you want like me to run to better report this.

I also made this comment on Gitlab at https://gitlab.com/gitlab-org/gitlab-ce/issues/69

**Comment by allan-simon** [comment]
+1 i have gitlab  7.9.1 and gitlab-ci 5.4.2 and I also have the same error message without any way for the moment to reproduct the bug in a rational way,  sometimes squashing commit and push --force "unblock" it 

as for the others, gitlab-ci by itself works fine, using the manual test button from gitlab also works , just that from times to times it will "break" on a commit

**Comment by vsizov** [comment]
What the status of the build on CI? I fixed similar bug (already in master ) - it is related to canceled builds.

**Comment by allan-simon** [comment]
master got no problem so far, 

for the status of the build on CI, well the specific commit at the time of this message appears does not appear in gitlab-ci side (i.e no build is triggered which seems consistent with the message 'cannot connect' ) 

the status of the previous commit seems to have no impact ( i got this bug appearing after pushing a new commit to fix a build on a MR , or just after pushing  changelog change in a build success MR )

**Comment by jvanbaarsen** [comment]
CI is now integrated in Gitlab. Closing this issue
