### ISSUE TITLE
Note diff count is not increased when new note is added via Ajax

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#6352]
For example, on the following screenshot, there are 3 comments, but the count is only 1, because I added 2 comments without reloading the page.

![screenshot from 2014-02-18 20 01 54 comment count](https://f.cloud.github.com/assets/1429315/2198986/a8be402e-98cf-11e3-8d5c-b99e77bc16fb.png)

**Comment by jvanbaarsen** [comment]
This issue has been fixed in a newer version
