### ISSUE TITLE
Allow Merge pull requests but forbid pushing

### ISSUE THREAD

**Issue by darinkes** [gitlabhq/gitlabhq#6432]
Hi,

Is it possible in a group project to give members the ability to create&merge 
pull requests, but forbid to directly push into the repo. Target is that all changes have to
be submitted via a Pull Request to enforce a review.

Also a nice Option would be to enforce the person who accepts the pull request is not
the creator of the pull request.

I've checked https://github.com/gitlabhq/gitlabhq/blob/master/app/models/ability.rb, but
there seems to be no role for this.

Thanks in advance

**Comment by cjbush** [comment]
I'd also like a feature like this. Even if a developer has to go into some kind of elevated mode to accept a merge request.

**Comment by leonkyr** [comment]
+1

**Comment by reardonm** [comment]
+1

**Comment by stevebaxter** [comment]
+1

**Comment by noqcks** [comment]
+1

**Comment by Alexssssss** [comment]
+1

**Comment by MartyvdB** [comment]
+1

**Comment by jde** [comment]
+1

**Comment by kuddl** [comment]
+1

**Comment by jancoliq** [comment]
+1
That would be an awesome feature!

**Comment by jotaen** [comment]
+1

**Comment by Masadow** [comment]
:+1:

**Comment by bsingr** [comment]
+1

**Comment by renatomjr** [comment]
+1

**Comment by kelvingl** [comment]
+1

**Comment by CaioCesarDev** [comment]
+1

**Comment by rhagni** [comment]
+1

**Comment by TomSouza** [comment]
+1

**Comment by Alexandreh** [comment]
+1

**Comment by flixi** [comment]
+40 ;)

**Comment by nf-contribute** [comment]
+1

**Comment by danielaborg** [comment]
@darinkes Hi darinkes, can you reopen this issue so it can be tracked and maybe implemented? We're also very interested in this feature, although I wouldn't say that it's necessary that reviewer != developer.

**Comment by loebble** [comment]
+1

**Comment by aalibaabaa** [comment]
+1

**Comment by kuddl** [comment]
+1

**Comment by Pittiplatsch** [comment]
+1

**Comment by perrupa** [comment]
I think protected branches is very close to what you wanted as well as what I wanted. A protected branch blocks *force* pushes to itself, just not 'normal' pushes.

We've fully embraced the Pull request workflow at my company, but there doesn't seem to be any way to enforce that PRs be the only way code can get into a repo or branch. If any collaborator can merge a pull request, they also have the permissions to push any code they want to any branch. Only force pushes can be controlled/limited...

This a big pain for our large team of devs who we trust to do reviews, but are a little unfamiliar with using git with multiple remotes. 

### I just want to disable all pushes to our central repo (not forks of it)

:point_up: This would force all changes to go through a PR, but there is no mechanism to do this in GitHub so far :disappointed:

**Comment by banro21** [comment]
+1. I am also supportive of a feture to make sure that the person merging the pull request is not the person creating the pull request. It just enforces the concept of peer reviews.

**Comment by ChrisBAshton** [comment]
+1. [Protected branches](https://help.github.com/articles/configuring-protected-branches/) is a good start (preventing force pushes and deletions) but what we really want is something which prevents us from directly pushing to the branch, forcing us to open a PR.

**Comment by sierraechobravo** [comment]
+1

**Comment by wk001** [comment]
+1

**Comment by opynios** [comment]
+1

**Comment by mmmpop** [comment]
+1

**Comment by reicheltp** [comment]
+1

**Comment by integratedforpublishers** [comment]
+1

**Comment by arunbhat** [comment]
+1

**Comment by arunbhat** [comment]
+1

**Comment by shwetabhgarg** [comment]
+1

**Comment by mauriciocoelho** [comment]
+1

**Comment by aransfor** [comment]
+1

**Comment by sandeep15390** [comment]
+1

**Comment by matthewcbaker** [comment]
+1

This was the first thing I wanted. I agree protected branches is a good start but it doesn't go far enough. I want to be able to allow everyone to merge pull requests to master using the web, but not even me using the command line to prevent accidents and enforce procedure.

Having the merger different from requester is equivalent to forcing a review by x people (where x is 1), which I also want to do.  I think this is achievable using hooks but is only partially useful if people don't need to create a PR to commit.

**Comment by hoto** [comment]
+1

**Comment by eshenayo** [comment]
This is marked as closed, but it doesn't seem that a resolution was ever reached. Regardless, I agree this feature would be useful.

**Comment by darinkes** [comment]
You are right, I will reopen it :)

**Comment by hoto** [comment]
The only workaround I found is to create separate users with `Master`  privileges so accidental pushes never happen. But it would be nice to have a checkbox beside protected branches `no direct pushes allowed, ever` ;)

**Comment by PapaNappa** [comment]
Maybe it suffices if there there is an additional role "Contributor" which is Reporter + "Create new merge request" privilege. Then contributors could only create merge requests, but neither accept them nor push to any branch. In particular, they could not create any *new* branches at their will (then the merge request must origin from a forked repo, of course).
At least, that "Contributor" role will suite my needs best. :)

Of course, this does not address the feature of requiring a different developer to accept the merge.

**Comment by andretietz** [comment]
+1

**Comment by aberonni** [comment]
+10!

**Comment by shahp00ja** [comment]
we too need to protect a branch from pushing code directly and forcing for raise a PR

**Comment by doeiqts** [comment]
+1

**Comment by ramzysa** [comment]
+1

**Comment by guevaraf** [comment]
+1

**Comment by axilleas** [comment]
@darinkes et al, can you create an issue in https://gitlab.com/gitlab-org/gitlab-ce/issues in order to vote there? On GitLab.com this will get more attention. When done, please link here and close this one :)

**Comment by aseychell** [comment]
+1!

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Comment by zyv** [comment]
FYI, this issue is now tracked at https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4220 on the GitLab tracker.

**Comment by rrezino** [comment]
+1

**Comment by barrett-rob** [comment]
+1

**Comment by shams-ali** [comment]
+1

**Comment by kchan628** [comment]
+1

**Comment by AdrienChampion** [comment]
+1

**Comment by Errore418** [comment]
+1

**Comment by PeterGhimself** [comment]
:+1:

**Comment by kpartlow** [comment]
It would be nice to also support a configurable number of approvals before a pull request can be merged into master.  protected branches doesn't give us that.

**Comment by axilleas** [comment]
@kpartlow that's possible with MR approvals https://docs.gitlab.com/ee/user/project/merge_requests/merge_request_approvals.html
