### ISSUE TITLE
Error 500 when creating an issue

### ISSUE THREAD

**Issue by enumag** [gitlabhq/gitlabhq#6443]
Hi, one of the users of my gitlab installation is getting error 500 when creating a new issue. First time he gets error 500 and when trying again, it works. This process is repeated for every new issue.

For me it always works fine, I have admin (owner) privileges to repository in question though. Not sure if that's relevant.

There are no clear steps to reproduce the error unfortunatelly, or none that we are aware of except clicking new issue button, putting sth in the form and submitting it. Which is probably not very helpful.

Gitlab version: 6.6.4 (the error was present in older versions as well but the user told me that it threw 404 http code instead of 500 in the past)

Output from check:
```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.7.9 ? ... OK (1.8.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 

--- "ok" for all repositories except some "repository is empty"

Running /www/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/www/git/repositories: OK
	/www/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.6
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 

--- "yes" for all repositories

Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/local/bin/git"
Git version >= 1.7.10 ? ... yes (1.8.3)

Checking GitLab ... Finished
```

The home directory of my git user is different than usual - /www/git instead of /home/git. Not sure if relevant. Of course I've modified all config files and /etc/init.d/gitlab file accordingly in the past.

My setup:
```
System information
System:		Debian 6.0.9
Current User:	git
Using RVM:	no
Ruby Version:	1.9.3p429
Gem Version:	1.8.23
Bundler Version:1.3.5
Rake Version:	10.1.1

GitLab information
Version:	6.6.4
Revision:	42e34ae
Directory:	/www/git/gitlab
DB Adapter:	mysql2
URL:		*censored*
HTTP Clone URL:	*censored*/some-project.git
SSH Clone URL:	git@*censored*:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	1.8.0
Repositories:	/www/git/repositories/
Hooks:		/www/git/gitlab-shell/hooks/
Git:		/usr/local/bin/git
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
