### ISSUE TITLE
500 Encoding Error

### ISSUE THREAD

**Issue by dreamsxin** [gitlabhq/gitlabhq#6446]
Started GET "/liguodong/travel/notes?target_id=5&target_type=issue" for 127.0.0.1 at 2014-03-01 17:46:37 +0800
Processing by Projects::NotesController#index as JSON
  Parameters: {"target_id"=>"5", "target_type"=>"issue", "project_id"=>"liguodong/travel"}
  Rendered projects/notes/_note.html.haml (15.0ms)
  Rendered projects/notes/_note.html.haml (13.7ms)
Completed 200 OK in 88ms (Views: 1.2ms | ActiveRecord: 10.1ms)

Encoding::CompatibilityError (incompatible character encodings: UTF-8 and ASCII-8BIT):
  app/models/commit.rb:136:in `method_missing'
  app/models/commit.rb:64:in `diff_suppress?'
  app/controllers/projects/commit_controller.rb:18:in `show'
  app/controllers/application_controller.rb:57:in `set_current_user_for_thread'

  Rendered errors/encoding.html.haml within layouts/errors (0.2ms)
  Rendered layouts/_head.html.haml (1.3ms)
  Rendered layouts/_search.html.haml (1.2ms)
  Rendered layouts/_head_panel.html.haml (10.1ms)
  Rendered layouts/_flash.html.haml (0.2ms)
Completed 500 Internal Server Error in 2315ms (Views: 12.5ms | ActiveRecord: 8.5ms)
Started GET "/assets/icon-search.png" for 127.0.0.1 at 2014-03-01 17:46:38 +0800

**Comment by DouweM** [comment]
A fix to this issue has been merged and will be in version 7.9. Please reopen this issue if the problem persists after upgrading to 7.9.
