### ISSUE TITLE
[6.6.4] 403 error when removing a user from a group

### ISSUE THREAD

**Issue by jaugustin** [gitlabhq/gitlabhq#6448]
Hi,

I upgrade my gitlab to 6.6.4 and I can't remove a user from a group with my admin account, owner of the group, I alway got a 403 error.

In the production log I got this :

```
Started DELETE "/groups/mygroup/users_groups/8" for 192.168.0.5 at 2014-03-01 17:13:27 +0100
Processing by UsersGroupsController#destroy as JS
Parameters: {"group_id"=>"mygroup", "id"=>"8"}
Completed 403 Forbidden in 12ms (ActiveRecord: 1.6ms)
```

gitlab:check all green except init-script (beacuse I am on centos)

Env :

```
System information
System:         CentOS 6.5
Current User:   git
Using RVM:      yes
RVM Version:    1.24.7
Ruby Version:   1.9.3p484
Gem Version:    2.1.11
Bundler Version:1.3.5
Rake Version:   10.1.1

GitLab information
Version:        6.6.4
Revision:       32bfc4b
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            http://192.168.0.7:8383
HTTP Clone URL: http://192.168.0.7:8383/some-project.git
SSH Clone URL:  git@192.168.0.7:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.8.0
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
