### ISSUE TITLE
Add System Admin User

### ISSUE THREAD

**Issue by wdamien** [gitlabhq/gitlabhq#6483]
Admin users do not have access to create projects in any Namespace, only the ones they are owners of.

Steps to reproduce: 
1) Sign in to your gitlab instance with an admin account
2) Open the admin area and select "New Project"
3) In the namespace dropdown is only "Administrator" visible. You cannot search for different namespaces, that you are not an owner of.

Expected behaviour:
As an admin I should see all the namespaces for my gitlab install.

Workaround
1) Visit /admin/projects/NAMESPACE/PROJECT_NAME/, look under under the Transfer project section, you can browse all the namespaces.  Then transfer your project to the correct namespace that way.  However if an admin can see all the namespaces here, why not in add project?
2) Add the admin as an owner of the namespace in question.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
