### ISSUE TITLE
"Pull project code" and "Create new merge request" should be the same permission.

### ISSUE THREAD

**Issue by joehillen** [gitlabhq/gitlabhq#6485]
"Pull project code" and "Create new merge request" should be the same permissions.

There seems to be a gap in reasoning about permissions. 

Why can a user fork a project but then not open a merge request for that project? What is the use forking if you can't contribute back? What is the use of merge requests if you already have commit access?

I've found myself in this position several times. There is an existing project, and I haven't been given commit access to that project yet (usually because of an admin oversight). I want to make a simple change and ask the owner to merge it. I don't necessarily need or want commit access to do this, since the owner can review and merge my patch for me. I fork the project, push the changes to my fork, but then I can't open a merge request.

One solution would be to allow merge requests for "Reporters" but I propose a simpler solution. 

**Forking** doesn't makes sense without **merge requests**, and **merge requests** don't make sense without **forking**; they should be the same permission.

**Comment by schmittner** [comment]
I agree, there should be a permission level which grants merge request but disallows pushing to the original repository. However, I don't think that forking and merge requests should be the same. Maybe you don't want anyone who can access your code be able to propose changes. (Consider the example of a student getting pull permission to perform some task but shouldn't contribute back to the project.)
Instead, I'd rather create a new permission level **Contributor** that is permission level **Reporter** + **merge request**.

**Comment by samrocketman** [comment]
@schmittner that does not grok with how I typically interact with projects.  In that scenario, I would let the student fork the project and do whatever they want.  If they open a merge request I have no obligation to merge it into the main code base.  Furthermore, a simple verbal contract can be made to say, "don't submit merge requests."  I think separating the permissions doesn't make sense.  Allowing forks without the ability to create merge requests makes even *less* sense.

**Comment by schmittner** [comment]
@samrocketman I see that there might not be a one-size-fits-all solution.
However, I think a permission system should reflect what an account is allowed to do/not to do without the need for a verbal agreement. And as I mentioned there are (admittedy rare) use cases where one can want finer control. How about an option to create custom permission levels? (even though that might be a bit overkill)

As for now, making Reporter be able to create merge requests seems to be the best and quickest fix in my opinion.

**Comment by mathstuf** [comment]
I agree with @samrocketman. If you don't want folks making merge requests, just turn that off.

That said, in our 7.8.1 install, I had no problems forking and creating a merge request without developer permissions. My reading from that behavior is that "create merge requests" is that it controls the ability to open a merge request *from* that repository, not *to* it. Wording the permission that makes that clearer would be an improvement.

**Comment by samrocketman** [comment]
Keep in mind this issue may no longer be relevant.  It pertains to the 6.x series of GitLab and they're well into 7.x series.  I'm commenting with the knowledge of 6.x because that's my last interaction with GitLab.  It sounds like @mathstuf has more recent info?  Would you agree that this issue is out of date?

**Comment by mathstuf** [comment]
Based on observations, I'd say it currently does what I would expect (if you can view, you can clone[1] and open merge requests). If anything, the permission could be worded better.

[1]Up to your repo quota at least, which is how we plan on managing external contributors' repos.

**Comment by samrocketman** [comment]
Then I'd say this ticket can be resolved as fixed if it behaves that way @axilleas @maxlazio .

Regarding repo quotas and managing external contributors' repos I tend to side with collaboration over control.  The tooling should be there to promote the collaboration, not get in the way.  So if you make your quotas unreasonable then what will end up happening is users will have to throw away their repositories (changes merged or not) when they reach their quota but still want to contribute to other repositories.  I likely wouldn't implement quotas.  Just my 2c on the matter.

**Comment by axilleas** [comment]
I got bit by that one myself in the past. You don't see the **New Merge Request** button if you don't have the right privileges, but you do see it in your fork from where you can submit an MR to the upstream project.

The way MRs work:

When creating a **New Merge Request**, the source branch is always the repo from which you made the MR. So, if you don't have the right privileges to a project you are not entitled to do so, thus the button is hidden. But on your fork you are free to do whatever you want, so you get to see the button.

Compared to how GitHub implements it, I think we do a better job as now I could go to any public project on Github and create a PR without even having forked the project.

That said, I believe current implementation is correct. Fixes to the documentation are much appreciated, though.

**Comment by mathstuf** [comment]
On Fri, Feb 27, 2015 at 19:57:45 -0800, Sam Gleske wrote:
> Regarding repo quotas and managing external contributors' repos I tend
> to side with collaboration over control.  The tooling should be there
> to promote the collaboration, not get in the way.  So if you make your
> quotas unreasonable then what will end up happening is users will have
> to throw away their repositories (changes merged or not) when they
> reach their quota but still want to contribute to other repositories.
> I likely wouldn't implement quotas.  Just my 2c on the matter.

I agree, but it isn't my call. We do have a process for contributors to
bump their quota though, so it isn't completely locked down.

If there were a way for forks to not count towards quotas, I don't think
there'd be any problem (we just don't want users creating arbitrary
repos on our instance). I'll open an issue for that.
