### ISSUE TITLE
fix grep while it matches in binary files

### ISSUE THREAD

**Issue by qqshfox** [gitlabhq/gitlabhq#6487]
FYI

The gitlab search snapshots:

before

![2014-03-07 12 24 07](https://f.cloud.github.com/assets/459733/2347966/a06766aa-a552-11e3-9621-7a6dc36064fb.png)

after

![2014-03-07 1 11 24](https://f.cloud.github.com/assets/459733/2347967/a64bf504-a552-11e3-930e-e6bf72a25976.png)

gitlabhq/grit#39

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
