### ISSUE TITLE
Production server changed : git pull impossible

### ISSUE THREAD

**Issue by davidterranova** [gitlabhq/gitlabhq#6514]
Hi,
I am experiencing some problems since i switched my prod server.
It has the same hostname as the old one.

I am running the last Gitlab version 6.6.5

I have re-created a new ssh-key on my server, removed old deeply ssh-key from gitlab and add the new one.
The new key is present into the file `/home/git/.ssh/authorized_keys`

I am able to clone and pull the project from other servers with other hostnames.
Since i try to pull / clone from this one (tried with others keys/users), i got a password prompt from the command line.

Does switching from one server to another with the same fqdn can drives into this kind of error ?

It is quite annoying since i can't deploy new versions of my app.

regards

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
