### ISSUE TITLE
Gitlab backup fails to backup all directories

### ISSUE THREAD

**Issue by spuder** [gitlabhq/gitlabhq#6536]
If you use the rake:bakup utility, empty repositories are not backed up. 
If you restore from a backup, then any repos that were empty will not be recreated. 

As a result, the empty repo will show in the web interface, but will not be present in /home/git/repositories. The user will get the following error when they try and push to the repo.

```
git push origin master

fatal: '/home/git/repositories/sowen/foo.git' does not appear to be a git repository
fatal: Could not read from remote repository.
```

And the directory does not exist
```
 ls -latr /home/git/repositories/sowen/ | grep foo | wc -l
0
```

Steps to reproduce:

Create new project in gitlab
Backup gitlab
Restore gitlab backup to new machine
Attempt to push code to the empty repo
You will get an error the repository does not exist

Tested on 6-5-stable

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
