### ISSUE TITLE
GitLab 6.6.5 83eb5f3 does not escape in commit messages

### ISSUE THREAD

**Issue by Happy86** [gitlabhq/gitlabhq#6549]
It seems like commit messages are not or not properly escaped when displayed in GitLab. 

I have **not** tried injecting JavaScript yet but things like 
```
&auml;
``` 
are shown as 'ä' if GitLab displays the commit message. 

Is this behaviour intended? 

> System information
> System:         Debian 7.4
> Current User:   git
> Using RVM:      no
> Ruby Version:   2.0.0p353
> Gem Version:    2.0.14
> Bundler Version:1.5.3
> Rake Version:   10.1.1
> 
> GitLab information
> Version:        6.6.5
> Revision:       83eb5f3
> Directory:      /home/git/gitlab
> DB Adapter:     postgresql
> URL:            https://$FQDN
> HTTP Clone URL: https://$FQDN/some-project.git
> SSH Clone URL:  git@$FQDN:some-project.git
> Using LDAP:     yes
> Using Omniauth: no
> 
> GitLab Shell
> Version:        1.8.0
> Repositories:   /home/git/repositories
> Hooks:          /home/git/gitlab-shell/hooks/
> Git:            /usr/bin/git

**Comment by Razer6** [comment]
Still in 7.9.2 https://gitlab.com/test-repositories/test-escape-commit-message/commits/master

**Comment by Razer6** [comment]
Stil in 7.14

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by beat** [comment]
Re-opened on https://gitlab.com/gitlab-org/gitlab-ce/issues/4707 as it is a potential security issue.

**Comment by jvanbaarsen** [comment]
@beat Thanks
