### ISSUE TITLE
Webhook not firing, http 500 error (using 'Test Hook' from project)

### ISSUE THREAD

**Issue by mdk999** [gitlabhq/gitlabhq#6552]
I've created a webhook in my project (a push hook). when I click on the 'Test Hook' link nothing happens. Tracing it down it tries to load a url 'hooks/2/test' which gives a http 500 error. Below are the system and gitlab specs along with an error from the log file.

System:
Ubuntu 13.10 (GNU/Linux 3.11.0-18-generic x86_64)

Gitlab:
GitLab 6.6.5

GitLab Shell 1.8.0

GitLab API v3

Ruby 2.0.0p247

Rails 4.0.3

This is the error from the log

Started GET "/jenkins/jenkins-test/hooks/2/test" for 127.0.0.1 at 2014-03-18 11:39:10 -0700
Processing by Projects::HooksController#test as HTML
Parameters: {"project_id"=>"jenkins/jenkins-test", "id"=>"2"}
Redirected to
Completed 500 Internal Server Error in 240ms
ActionController::RedirectBackError (No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].):
app/controllers/projects/hooks_controller.rb:29:in `test'
app/controllers/application_controller.rb:57:in `set_current_user_for_thread'

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
