### ISSUE TITLE
Complex markdown links are not rendering correctly

### ISSUE THREAD

**Issue by samrocketman** [gitlabhq/gitlabhq#6567]
Right now Gitlab can't handle complex markdown links.  It used to work in GitLab 6.4 and prior but stopped working in GitLab 6.5 and GitLab 6.6 (current stable versions).

# Correct Rendering

## 1. Escaping back ticks

Markdown

    [\`some code\` some text](http://example.com)

Result

    <a href="http://example.com">`some code` some text</a>

## 2. Inline code in link

Markdown

    [`some code` some text](http://example.com)

Result

    <a href="http://example.com"><code>some code</code> some text</a>

# Current GitLab behavior and bad rendering

## 1. Escaping back ticks (works)

Markdown

    [\`some code\` some text](http://example.com)

Result

    <a href="http://example.com">`some code` some text</a>

## 2. Inline code in link (broken)

Markdown

    [`some code` some text](http://example.com)

Result

    <a href="http://example.com">&lt;code&gt;some code&lt;/code&gt; some text</a>

# Screenshot comparison between GitHub and GitLab

Screenshot of correct render (GitHub)

![GitHub screenshot rendering markdown](https://f.cloud.github.com/assets/875669/2461432/e1488ef0-af76-11e3-84fa-84cfce250219.png)

Screenshot of render bug (GitLab)

![GitLab screenshot rendering markdown bug](https://f.cloud.github.com/assets/875669/2461465/2d6d7156-af77-11e3-857f-93d9028c41f2.png)

**Comment by Razer6** [comment]
Fixed in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/619
