### ISSUE TITLE
Some reopened merge request don't receive updates

### ISSUE THREAD

**Issue by jacob-carlborg** [gitlabhq/gitlabhq#6574]
We're having some problems with merge requests that don't get any new updates when pushed. The commits are properly pushed and we can inspect them via Gitlab. But the merge request is not updated. So far it's happened twice and only for merge requests that were accidentally closed and then reopened.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by jacob-carlborg** [comment]
Ok... that's an interesting way to close bugs.

**Comment by jvanbaarsen** [comment]
@jacob-carlborg Sorry, if you still think this is an issue can you please open it at: https://gitlab.com/gitlab-org/gitlab-ce/issues We are slowly working towards closing the issue tracker here.
