### ISSUE TITLE
API | Project Events need a timestamp

### ISSUE THREAD

**Issue by valeriomazzeo** [gitlabhq/gitlabhq#6591]
A timestamp of when the event of a project happened it is really needed to be able to sort them in a way that they make sense to the user.

Also an event id would be useful to have.

**Comment by jubianchi** [comment]
I just checked this against the master branch: this issue seem to have been partially resolved in [6.8.0](https://github.com/gitlabhq/gitlabhq/blob/master/CHANGELOG#L393) by 0da8428f8efb7af188deb3e85ca911efbfb0e59e. Here is a typical response from the API:

```
GET /api/v3/projects/root%2Ftesting/events?private_token=kjdxipPkx2fuVTx-UpTx

[
	{
		title: null,
		project_id: 9,
		action_name: "joined",
		target_id: null,
		target_type: null,
		author_id: 1,
		data: null,
		target_title: null,
		created_at: "2015-01-18T17:24:08.471Z",
		author_username: "root"
	}
]
```

I don't think the id would be useful here as the API provides nothing to access a single event.

**Comment by valeriomazzeo** [comment]
agree for the date.

event id is necessary in order for a client to perform proper data persistency and avoid duplicates.

**Comment by jubianchi** [comment]
@valeriomazzeo what about using a composed-key of `created_at` + `project_id` + `action_name` ?

**Comment by valeriomazzeo** [comment]
this is what I am doing at the moment, but obviously would be nicer (and faster) to have a proper id for this use.
