### ISSUE TITLE
New Line Behavior Totally Messed Up Old Issue/Comments

### ISSUE THREAD

**Issue by diablo2man** [gitlabhq/gitlabhq#6608]
we need a way to retroactively change all the previous issue/comment/commit to meet the new standard. Otherwise it is impossible to manually change all thousands of existing issues.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
