### ISSUE TITLE
500 error if issue tracker is not correctly configured

### ISSUE THREAD

**Issue by hithwen** [gitlabhq/gitlabhq#6616]
gitlab version: 6.6.4
If my issue tracker (redmine) is not correctly configured (I'm assuming that the reason) I get a 500 error when visiting a projecct

    Started GET "/root/corporate" for 127.0.0.1 at 2014-03-18 12:28:32 +0100
    Processing by ProjectsController#show as HTML
      Parameters: {"id"=>"root/corporate"}
      Rendered projects/_dropdown.html.haml (1.4ms)
      Rendered projects/_home_panel.html.haml (2.3ms)
      Rendered projects/show.html.haml within layouts/projects (2.6ms)
    Completed 500 Internal Server Error in 27ms
    
    ActionView::Template::Error (undefined method `gsub' for nil:NilClass):
         5:     %ul.dropdown-menu
         6:       - if @project.issues_enabled && can?(current_user, :write_issue, @project)
         7:         %li
         8:           = link_to url_for_new_issue, title: "New Issue" do
         9:             New issue
        10:       - if @project.merge_requests_enabled && can?(current_user, :write_merge_request, @project)
        11:         %li
      app/helpers/issues_helper.rb:35:in `url_for_new_issue'
      app/views/projects/_dropdown.html.haml:8:in `app_views_projects__dropdown_html_haml___2253923643819089116_66646100'
      app/views/projects/_home_panel.html.haml:13:in `_app_views_projects__home_panel_html_haml__4106456017662476184_66232860'
      app/views/projects/show.html.haml:1:in `_app_views_projects_show_html_haml___1195922579372123442_64762500'
      app/controllers/projects_controller.rb:73:in `block (2 levels) in show'
      app/controllers/projects_controller.rb:65:in `show'
      app/controllers/application_controller.rb:57:in `set_current_user_for_thread'

I solved it putting gitlab as issue tracker again, but I dont think this should cause a 500 err

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
