### ISSUE TITLE
Merge requests disappear from list of open merge requests, possibly triggered by failed attempts to merge them

### ISSUE THREAD

**Issue by woodbusy** [gitlabhq/gitlabhq#6621]
(Edited to follow issue guidelines)

1. **Summary:** Some merge requests disappear from the "open" and "closed" filters, even though the code has not been merged and the MR's page still shows it as open.
2. **Steps to reproduce:** Unfortunately, we're not able to reproduce it at will. However, it has happened to at least three MRs in the past two weeks.
3. **Expected behavior:** Merge requests will remain open and visible on the merge requests page until they are merged or closed. Once they are merged, the changes will be merged into the target branch and the MR will be closed.
4. **Observed behavior:** In four cases, merge requests no longer appear on the default, (i.e. "Everyone's", "Open") merge requests list and do not appear on the list of closed MRs either. They *do* appear in the "All" list. On the page for the MR itself, the request shows up as being open but the button to merge is no longer there. In at least three of the cases, this happened after attempting to merge the request through the UI; later we noticed that the changes had not been merged but that the MRs had disappeared.
5. **Screenshots:**
One of the MRs in question:

![gl_ss4](https://cloud.githubusercontent.com/assets/1714986/2531731/cfbda7c8-b535-11e3-9889-2c218729b440.png)

The default MRs list (MR 1235 does not appear):
![gl_ss1](https://cloud.githubusercontent.com/assets/1714986/2531733/e0eb19ae-b535-11e3-83f2-8c762dfbe82a.png)

The MR list with the "closed" filter (MR 1235 does not appear):
![gl_ss2](https://cloud.githubusercontent.com/assets/1714986/2531737/f1a652c2-b535-11e3-9dde-4e769ab7f15c.png)

The MR list with the "all" filter (MR 1235 *does* appear):
![gl_ss3](https://cloud.githubusercontent.com/assets/1714986/2531743/fdcc54ca-b535-11e3-8175-d5c51fe32142.png)
6. **Output of checks:** 
*Results of GitLab Application Check:*

```
System information
System:   CentOS release 6.3 (Final)
Current User: git
Using RVM:  no
Ruby Version: 1.9.3p194
Gem Version:  1.8.25
Bundler Version:1.2.3
Rake Version: 10.1.1

GitLab information
Version:  6.6.5
Revision: 8f48f38
Directory:  /home/git/gitlab
DB Adapter: mysql2
URL:    https://git.domain.removed
HTTP Clone URL: https://git.domain.removed/some-project.git
SSH Clone URL:  git@git.domain.removed:some-project.git
Using LDAP: yes
Using Omniauth: no

GitLab Shell
Version:  1.8.0
Repositories: /home/git/repositories/
Hooks:    /home/git/gitlab-shell/hooks/
Git:    /usr/bin/git
```
* *Version of GitLab you are running:* 6.6.5 8f48f38 (I think also with 6.6.4)
* *Describe your setup:*
```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.7.9 ? ... OK (1.8.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 
[Repository list removed. All repos are "ok", except for eight "repository is empty"]
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
  /home/git/repositories: OK
  /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.4.10
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)
[LDAP results removed]

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 
[Repository list removed. All repos are "yes", except for three "can't create, repository is empty"]
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.12)

Checking GitLab ... Finished
```

**Comment by bbodenmiller** [comment]
Looks like the fixing of https://gitlab.com/gitlab-org/gitlab-ce/issues/542 may have fixed this. Also see https://gitlab.com/gitlab-org/gitlab-ce/issues/348.

**Comment by bbodenmiller** [comment]
@sytses finally fixed now that https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/526 has merged.

**Comment by zxqfox** [comment]
@bbodenmiller Thanks!

**Comment by dosire** [comment]
@bbodenmiller great!
