### ISSUE TITLE
git via http is slow and ustable

### ISSUE THREAD

**Issue by limansky** [gitlabhq/gitlabhq#6649]
Hi.

  After upgrade to gitlab 6.7 git http connection became slow (I mean huge delay before start doing something) and unstable. I increased timeout in unicorn.rb to 120 seconds (else I was not able to clone at all). After what I successfully cloned one of the repos, but got error for the other one:

Cloning into 'harvester'...
remote: Counting objects: 2871, done.
remote: Compressing objects: 100% (2054/2054), done.
fatal: The remote end hung up unexpectedlyMiB | 455.00 KiB/s    
fatal: early EOF
fatal: index-pack failed

I am using apache with mod_proxy on Gentoo linux.

**Comment by Razer6** [comment]
This will be fixed with the upcoming git-http-server in 8.0
