### ISSUE TITLE
If I click "Test Hook" twice on Web Hooks configuration page, infinite redirection loop results.

### ISSUE THREAD

**Issue by crocket** [gitlabhq/gitlabhq#6657]
If I click it once, visit another page, revisit Web Hook configuration page, and click it again, there is no such bug.

However, if I click it twice in a row, it is redirected repetitively until my web browser(chrome) stops redirection.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
