### ISSUE TITLE
Display problems with 6.7.1 (since upgrade)

### ISSUE THREAD

**Issue by MensSana** [gitlabhq/gitlabhq#6665]
DIsplay problems. Simply upgrade to 6.7.1 from 6.5 using auto-upgrade script to reproduce. Screenshots follows:

Only default theme is viewable, others are too dark (text on background). Colors should be contrast adapted to background color.

Header alignment of website is messed up:
![2014-03-31_1012](https://cloud.githubusercontent.com/assets/312318/2568526/3cec0c94-b8e3-11e3-8133-76e498e16e1d.png)

Line numbers are messed up when previewing files:
![2014-03-31_1016](https://cloud.githubusercontent.com/assets/312318/2568545/5b630e48-b8e3-11e3-850f-155a23e8b8f8.png)

Also, even though I'm a bit irrelevant, editing files directly from the GitLab web interface, modifications are saved on the git repository but website reports an error and does not show modifications...

Being irrelevant, there's also syntax highlighting that should read first line of unknown text filetypes to detect script types (perl, bash, python, etc) so it could highlight correctly more filetypes...

#### bundle exec rake gitlab:check RAILS_ENV=production
```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.9.1 ? ... OK (1.9.1)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 

[...] ALL ok [...]

Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/home/git/repositories: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.8
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 

[...] ALL yes [...]

Projects have satellites? ... 

[...] ALL yes [...]

Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.1)

Checking GitLab ... Finished
```
#### bundle exec rake gitlab:info RAILS_ENV=production
```
System information
System:         Ubuntu 12.04
Current User:   git
Using RVM:      yes
RVM Version:    1.25.14
Ruby Version:   2.0.0p247
Gem Version:    2.2.2
Bundler Version:1.5.2
Rake Version:   10.2.1

GitLab information
Version:        6.7.2
Revision:       dbbf4ea
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            http://git.celibec.com
HTTP Clone URL: http://git.celibec.com/some-project.git
SSH Clone URL:  gitlab:some-project
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.9.1
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
