### ISSUE TITLE
load different assets when run gitlab in different port 

### ISSUE THREAD

**Issue by poc7667** [gitlabhq/gitlabhq#6669]
Because my gitlab's layout is totally broken, 

So I decided run by manually in stead of ``

At first , my gitlab works fine, but crashed when I do ` rake assets:clean assets:precompile cache:clear RAILS_ENV=production`, `service gitlab restart`

I used the Nginx to forward port 1987 to my gitlab app folder.

So I could access my gitlab site by http://localhost:1987

Now, I disabled the Nginx to forward the port 1987 to my gitlab app.

but  `rails s -p 1987 -e production` stills shows the broken layout

if I run the server on other ports it works correctly excepts can not load avatar image

`rails s -p 1999 -e production`

![enter image description here][1]

![enter image description here][2]

  [1]: http://i.stack.imgur.com/ozKb1.png
  [2]: http://i.stack.imgur.com/CuzNA.png

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
