### ISSUE TITLE
Drop branch with opened merge request causes to strange side-effects

### ISSUE THREAD

**Issue by zxqfox** [gitlabhq/gitlabhq#6673]
How to reproduce:
- Push some branch with one more commit from master.
- Open MR branch→master
- Drop branch with git push origin :branch

And here we have several scenarios:
1. Open your MR in browser
- Open MR in browser — right message
- Push new branch — if something went right you will see new treeish and all is fine. But not each time, can't provide more info about it atm. ;-(
2. Wrong treeish in MR
- Push another treeish to that branch
- Open your MR in browser — old treeish instead of new one or closed MR with branch dropped message

Probably 1 can be splitted.

Something is wrong here, right?
According to 1 it should update MR on branch push, not on browser loads MR. Seems like it's close to force pushes.

Version: 6.7.2 community

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
