### ISSUE TITLE
Gitlab With Atlassian Crowd: https Clone not working

### ISSUE THREAD

**Issue by simkin** [gitlabhq/gitlabhq#6677]
I enabled omniauth_crowd using this guide: http://blog.hudecof.net/posts/2014/02/26/gitlab-with-atlassian-crowd.html

I am able to login to Gitlab with my Crowd credentials but cloning is not working
**fatal: Authentication failed for**

I added the Crowd user as a member for the test project.

The log files do not log anything, could someone advise how this can be properly debugged?

**Comment by Razer6** [comment]
With GitLab 8.0 we add official Crowd support.

**Comment by hudecof** [comment]
great, thanks a lot. It was pain to allways patch the gitlab a try to solve the issues like adding CSFR ;)
There are related issues

- https://github.com/gitlabhq/gitlabhq/issues/1240
- https://github.com/gitlabhq/gitlabhq/issues/9337
