### ISSUE TITLE
API - Can't get permission of Group if I only have permission to Project

### ISSUE THREAD

**Issue by blablup** [gitlabhq/gitlabhq#6678]
Unable to get the permissions of a group (which users have which access level) [GET /groups/:id/members] if I have only access to a project of that group. If i try to get theese Permissons from the Project I only get directly linked users. 

Expected behavior

THat I could see the Group members like I can on the website.

Observed behavior

403 Permission denied.

Example:

(in ruby with gitlab gem)
gl_client = Gitlab.client(:endpoint => gitlab_api , :private_token => auth)
irb(main):007:0> gl_client.groups
=> []
irb(main):012:0> gl_client.project(104)
=> #<Gitlab::ObjectifiedHash:0x0000000152ed50 @data={"id"=>104, "description"=>"Repo of Server lbm000d64.intra.lan (created by chef)", "default_branch"=>nil, "public"=>false, "visibility_level"=>0, "ssh_url_to_repo"=>"git@git.intra.lan:server/lbm000d64-intra-lan.git", "http_url_to_repo"=>"https://git.intra.lan/server/lbm000d64-intra-lan.git", "web_url"=>"https://git.intra.lan/server/lbm000d64-intra-lan", "owner"=>#<Gitlab::ObjectifiedHash:0x0000000152eb70 @data={"id"=>18, "name"=>"server", "created_at"=>"2013-10-21T07:50:54.000Z"}>, "name"=>"lbm000d64.intra.lan", "name_with_namespace"=>"server / lbm000d64.intra.lan", "path"=>"lbm000d64-intra-lan", "path_with_namespace"=>"server/lbm000d64-intra-lan", "issues_enabled"=>true, "merge_requests_enabled"=>true, "wall_enabled"=>true, "wiki_enabled"=>true, "snippets_enabled"=>false, "created_at"=>"2014-02-05T13:48:10.000Z", "last_activity_at"=>"2014-04-01T09:35:11.000Z", "namespace"=>#<Gitlab::ObjectifiedHash:0x0000000152e8a0 @data={"id"=>18, "name"=>"server", "path"=>"server", "owner_id"=>2, "created_at"=>"2013-10-21T07:50:54.000Z", "updated_at"=>"2013-10-21T07:50:54.000Z", "description"=>""}>}>
irb(main):028:0> gl_client.team_members(104)
=> [#<Gitlab::ObjectifiedHash:0x0000000221cad0 @data={"id"=>1, "username"=>"root", "email"=>"admin@local.host", "name"=>"Administrator", "state"=>"active", "created_at"=>"2013-07-05T23:07:42.000Z", "access_level"=>40}>, #<Gitlab::ObjectifiedHash:0x0000000221c648 @data={"id"=>25, "username"=>"lbm000d64.intra.lan", "email"=>"root@lbm000d64.intra.lan", "name"=>"root@lbm000d64.intra.lan", "state"=>"active", "created_at"=>"2014-02-03T13:31:29.000Z", "access_level"=>40}>]
irb(main):029:0> gl_client.project(104).namespace.id
=> 18

irb(main):029:0>  gl_client.group_members(18)
Gitlab::Error::Forbidden: Server responded with code 403, message: 403 Forbidden - lbm000d64.intra.lan lacks sufficient access to server. Request URI: https://git.intra.lan/api/v3/groups/18/members

Relevant logs and/or screenshots
![bildschirmfoto von 2014-04-01 16 44 26](https://cloud.githubusercontent.com/assets/688968/2588117/f435c4d4-ba33-11e3-92c8-9d100f1134de.png)
![bildschirmfoto von 2014-04-01 16 43 44](https://cloud.githubusercontent.com/assets/688968/2588118/f9d9d876-ba33-11e3-91e1-073b2dd8cdc4.png)
![bildschirmfoto von 2014-04-01 16 43 29](https://cloud.githubusercontent.com/assets/688968/2588119/fe596ca4-ba33-11e3-92e0-639d473e3de3.png)

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
