### ISSUE TITLE
Projects are not visible in group page

### ISSUE THREAD

**Issue by thewholelifetolearn** [gitlabhq/gitlabhq#6743]
I did some research on my issue but didn't find something related. If I missed a issue similar, please forgive me.

**Summary:**

When looking on a group page, public or protected projects are not visible. Only those where user has worked on are shown.
I think all projects should be visible depending on its visibility level off course.

**Steps to reproduce:**
Go on a project page where there are projects you work on.

**Expected behavior:**
On the project page, there should be all projects visible depending on their privacy level (public/protected/private)

**Observed behavior:**
Only projects that you are currently working with are shown

**Screenshots:**
View of the group page:
![empty_group_project](https://cloud.githubusercontent.com/assets/823564/2665821/89fece6a-c093-11e3-9927-76048f80d5e0.png)
View of the group page in the admin back-end:
![admin_group_project](https://cloud.githubusercontent.com/assets/823564/2665820/89fe7a64-c093-11e3-803d-c7ce457e4d91.png)

**Checks:**
```
Checking Environment ...

Git configured for git user? ... yes
Has python2? ... yes
python2 is supported version? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.7.9 ? ... OK (1.8.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 
xxxxxx ... ok
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/home/git/repositories: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.4.10
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... no
  Try fixing it:
  Redownload the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.
projects have namespace: ... 
xxxxxxx ... yes
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/local/bin/git"
Git version >= 1.7.10 ? ... yes (1.8.4)

Checking GitLab ... Finished
```

**Info:**

```
System information
System:		CentOS 6.4
Current User:	git
Using RVM:	no
Ruby Version:	2.0.0p247
Gem Version:	2.0.3
Bundler Version:1.3.5
Rake Version:	10.1.0

GitLab information
Version:	6.5.1 (The problem has been also encountered on Gitlab v6.4.x)
Revision:	6f6f158
Directory:	/home/git/gitlab
DB Adapter:	postgresql
URL:		https://xxxx.yyyy.zzz
HTTP Clone URL:	https://xxxx.yyyy.zzz/some-project.git
SSH Clone URL:	git@xxxx.yyyy.zzz:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	1.8.0
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/local/bin/git
```

**Comment by thewholelifetolearn** [comment]
Come back on the subject. Gitlab is now in 7.6.2 and the problem still occurs! The same problem happens on the Projects page.

As I understand:
* public projects are visible to everyone, registered and unregistered users of the Gitlab instance.
* internal projects are visible to registered users of the Gitlab instance
* private projects are visible to registered users of the Gitlab instance that are members of the project.

This doesn't happen on the Group and Projects pages. Am I wrong somewhere?

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
