### ISSUE TITLE
New comment on merge request do not trigger web hook

### ISSUE THREAD

**Issue by blackeyedboy** [gitlabhq/gitlabhq#6745]
**Summary :** when a user add a comment to a merge request, the web hook is not triggered for a merge_request event.

**Steps to reproduce :** open a merge request (the web hook is triggered), add a comment to this merge request (the web hook is NOT triggered).

**Expected behavior :** trigger the web hook when any user add a comment to a merge_request !
Note that if I add a comment through a `POST /projects/:id/merge_request/:merge_request_id/comments` API call, the merge_request web hook is correctly triggered on the comment add !

**Possible fixes :** I've little or no experience with ruby nor gitlab internal architecture, but maybe just a `execute_hooks(merge_request)` with the relevant `merge_request` on which the comment has been posted in the [app/observers/note_observer.rb](https://github.com/gitlabhq/gitlabhq/blob/master/app/observers/note_observer.rb) ?

I've seen in the [app/observers](https://github.com/gitlabhq/gitlabhq/commits/master/app/observers) folder history that the observers get removed one by one (mergerequest, keys, emails, issue, etc...), so maybe you are getting to a new way of triggering web hooks that I don't see for now, and my "possible fix" just sucks.

I'm sorry to say I haven't managed to find out how the `note.save` in [lib/api/merge_requests.rb](https://github.com/gitlabhq/gitlabhq/blob/master/lib/api/merge_requests.rb) trigger the web hook.

**Checks :** GitLab 6.7.3 f88d30f with tests full ok, see below.
```
System information
System:		
Current User:	git
Using RVM:	no
Ruby Version:	1.9.3p194
Gem Version:	1.8.23
Bundler Version:1.6.1
Rake Version:	10.1.1
```
```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.9.1 ? ... OK (1.9.1)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 
XXX / Testing Purpose ... ok
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/home/git/repositories: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.4.14
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 
XXX / Testing Purpose ... yes
Projects have satellites? ... 
XXX / Testing Purpose ... yes
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.10)

Checking GitLab ... Finished
```

**Just a side note :** *Gitlab rocks !*

**Comment by mathstuf** [comment]
The way I read the docs, the hook is doing as designed. Adding another hook for merge request and issue comments would certainly be appreciated though.

**Comment by tophsic** [comment]
:+1: on creating another web hook or change actual merge and issue webhooks behaviors.

**Comment by daynasym** [comment]
:+1: for allowing a comment to trigger a merge request event.  Our team wants all members to have visibility to what is being said in a review and would love the ability to notify everyone in a group when a comment is added to a merge request, regardless of their level of participation.

**Comment by stanhu** [comment]
This feature should be easy to implement, since the structures are all there when I added support for comment notifications in HipChat and Slack. I'll work on this for the next release.

**Comment by mathstuf** [comment]
I have a patch for it on my fork. I need to sort the branch out for making MRs though (feel free to grab them though; I won't get to it until Monday).

**Comment by stanhu** [comment]
First pass is working. Now to add tests and documentation:

https://gitlab.com/stanhu/gitlab-ce/commit/c57565769a17f4b8c8726024d6136f2c6c113bb4

**Comment by mathstuf** [comment]
One problem we had when implementing it is that only the merge request event is race-free to get the commit at the top of the merge request, so we added notes as an additional trigger for issues and merge requests.

**Comment by stanhu** [comment]
@mathstuf I'm not quite sure if I understand--can you explain this issue?

I've submitted a merge request here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/673

**Comment by mathstuf** [comment]
The only way to figure out the hash for an MR is to either listen to the event or to look up the branches on the source project and then look up the hash there. The second has a larger chance for a race (which we would like to avoid).

**Comment by Razer6** [comment]
Implemented and will be available in GitLab 7.12

**Comment by blackeyedboy** [comment]
@stanhu did it ! That's absolutely awesome, and I do thank you for this.
A beer for you next time I get to SF :beers:

Another process has just been automated ! And my 200 lines of Node.js to simulate this now gets trashed :)

**Comment by stanhu** [comment]
@blackeyedboy Great--glad to hear this helps! I know how much I wanted this feature for Slack, which is what got me started with working on GitLab in the first place.
