### ISSUE TITLE
Graph doesn't render at all with encoding error

### ISSUE THREAD

**Issue by ikari-pl** [gitlabhq/gitlabhq#6790]
I have no idea what exactly caused the issue. I imported a huge repository with a lot of various people commits just to see the graphs page, actually. 

In the production log:
```
Rendered projects/graphs/show.js.haml (3.8ms)
Completed 500 Internal Server Error in 2483ms
ActionView::Template::Error (invalid byte sequence in UTF-8):
13: $("#brush_change").change( function () {
14: controller.change_date_header()
15: controller.redraw_authors()
16: })
17: - else
18: :plain
19: $('.stat-graph').replaceWith('<div class="alert alert-danger">Failed to load graph</div>')
app/views/projects/graphs/show.js.haml:16:in `_app_views_projects_graphs_show_js_haml__1033386058975393792_78425800'
app/controllers/application_controller.rb:58:in `set_current_user_for_thread'
```

By the way, the page doesn't even mention the error:
I am on 6.7.5 (upgraded from 6.7.4 just 5 minutes ago, which didn't fix the problem).
![it just described the graph it didn't output](http://i.imgur.com/I6Rq4Yt.png)

**Comment by DouweM** [comment]
A fix to this issue has been merged and will be in version 7.9. Please reopen this issue if the problem persists after upgrading to 7.9.
