### ISSUE TITLE
gitlab with Active Directory

### ISSUE THREAD

**Issue by geeth4sg** [gitlabhq/gitlabhq#6794]
I've installed gitlab 6.7.5 on Ubuntu 12.04 and db is mysql.

root@ubuntu:/home/git/gitlab# cat VERSION 
6.7.5

root@ubuntu:/home/git/gitlab# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.4 LTS"

I referred the below site and configured gitlab , could login with admin@local.host

https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/installation.md

I need to integrate the gitlab and Active Directory as we are many users. The below is my config/gitlab.yml file(ldap section)

ldap:
    enabled: true
    host: '192.168.0.222'
    port: 389
    base: 'DC=ads,DC=com'
    uid: 'sAMAccountName'
    method: 'plain' # "tls" or "ssl" or "plain"
    bind_dn: 'CN=administrator,DC=ads,DC=com'
    password: 'p@55w0rd'

root@ubuntu:/home/git/gitlab# bundle exec rake gitlab:ldap:check RAILS_ENV=production
 Warning 
  You are running as user root, we hope you know what you are doing.
  Things may work/fail for the wrong reasons.
  For correct results you should run this as user git.

Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)

Checking LDAP ... Finished

I am getting the error   "Could not authorize you from LDAP because "Invalid credentials".

production log:

Started POST "/users/auth/ldap/callback" for 127.0.0.1 at 2014-04-16 15:08:18 +0530
Processing by OmniauthCallbacksController#failure as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"bMr7E8XFxKJJtMW+x4xN1WOfwIH5B4VlNXgFrStZdRg=", "username"=>"administrator", "password"=>"[FILTERED]"}
Redirected to http://192.168.0.184/users/sign_in

I've referred so many links, but no clue

If changed port number, getting connection reset peer error or could not connect server from 636 port.

I've downgraded the gitlab version to 5.4.0 and tried as I am getting same error.
http://blog.dimaj.net/content/updated-howto-enable-ldap-filters-gitlab

I've tried with administrator password of ADS server, still getting same error.

Please any one help me.

ref links:
https://raymii.org/s/tutorials/Gitlab_and_Active_Directory_LDAP_Authentication.html
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config/gitlab.yml.example#L126
http://comments.gmane.org/gmane.comp.version-control.gitlab/787
https://github.com/syndicut/omniauth-ldap/commit/b524feb63048591a20de0f70c2d597f0b9d6a156

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
