### ISSUE TITLE
File containing a single character shows as binary file independent of extension.

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#6798]
Weirdly, this only appears to happen if the files has exactly one character, not two or zero.

It prevents users from viewing markdown files rendered, and from editing those files.

https://gitlab.com/cirosantilli/test0/blob/f7e1b7184ba64cee8771519bc368e26c3d7f1270/single_char

https://gitlab.com/cirosantilli/test0/blob/f7e1b7184ba64cee8771519bc368e26c3d7f1270/single_char.md

https://gitlab.com/cirosantilli/test0/blob/master/empty.rb

https://gitlab.com/cirosantilli/test0/blob/f7e1b7184ba64cee8771519bc368e26c3d7f1270/two_chars

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
