### ISSUE TITLE
Parallel Diff feature broken for multiple files

### ISSUE THREAD

**Issue by GeorgeDewar** [gitlabhq/gitlabhq#6800]
Hi all,

If I get a chance, I will raise a pull request to fix this.

I've noticed that my changes to the Parallel Diff function have introduced a bug. It no longer works for multiple files. This is because a jQuery handler for the scroll event scrolls ALL of the files to do the scrolling synchronization when you scroll one.

I thought I'd better raise it so you're aware.

It looks like fixing it is just a case of using $(this).siblings instead of $ inside the javascript section of _parallel_view.haml.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
