### ISSUE TITLE
Diff on modified merge request should allow to see diff between commits

### ISSUE THREAD

**Issue by nruffel** [gitlabhq/gitlabhq#6801]
Project A
Project B is a fork from Project A

You do a merge request from B to A
Some nasty dev does some nasty comment on the beautiful code in the MR... You commit a fix and now, the MR has two commits.
The diff is only showing differences between A and the "new" B

It would be very interesting to allow to show only the diff between the two commits in the MR, allowing the nasty reviewer to validate easily that his recommandations have been implemented.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
