### ISSUE TITLE
500 error when I add a comment with file path

### ISSUE THREAD

**Issue by chzju** [gitlabhq/gitlabhq#6818]
after I leave a review comment in a merge request, the diff page(like https://git.xxxxx.com/vip/mail/merge_requests/22/diffs) will be broken and report 500.

the raw review comment is like this:
```
ERROR [14.03.22 08:37:47][com.aowcan.com]: /com/aowcan/mail
```

How could I fix this issue?

my gitlab log is like following:
```
Completed 500 Internal Server Error in 378ms

ActionView::Template::Error (Object not found - failed to find pack entry (e19feb5fee53630c1c1d4b03444ce0746fc81966)):
    31:   .note-body
    32:     .note-text
    33:       = preserve do
    34:         = markdown(note.note, {no_header_anchors: true})
    35:
    36:     .note-edit-form
    37:       = form_for note, url: project_note_path(@project, note), method: :put, remote: true, authenticity_token: true do |f|
  app/models/repository.rb:152:in `method_missing'
  app/models/repository.rb:162:in `blob_at'
  app/helpers/gitlab_markdown_helper.rb:171:in `file_exists?'
  app/helpers/gitlab_markdown_helper.rb:147:in `relative_file_path'
  app/helpers/gitlab_markdown_helper.rb:127:in `rebuild_path'
  app/helpers/gitlab_markdown_helper.rb:72:in `block in create_relative_links'
  app/helpers/gitlab_markdown_helper.rb:70:in `each'
  app/helpers/gitlab_markdown_helper.rb:70:in `create_relative_links'
  lib/redcarpet/render/gitlab_html.rb:52:in `preprocess'
  app/helpers/gitlab_markdown_helper.rb:51:in `render'
  app/helpers/gitlab_markdown_helper.rb:51:in `markdown'
  app/views/projects/notes/_note.html.haml:34:in `block in _app_views_projects_notes__note_html_haml___23577799234584145_70106593954200'
  app/views/projects/notes/_note.html.haml:33:in `_app_views_projects_notes__note_html_haml___23577799234584145_70106593954200'
  app/views/projects/notes/_diff_notes_with_reply.html.haml:11:in `_app_views_projects_notes__diff_notes_with_reply_html_haml__4166919278140910445_70106596174240'
  app/views/projects/notes/_discussion_diff.html.haml:25:in `block in _app_views_projects_notes__discussion_diff_html_haml___2921055492455687737_70106594456980'
  app/helpers/commits_helper.rb:43:in `block in each_diff_line_near'
  app/helpers/commits_helper.rb:20:in `block in each_diff_line'
  lib/gitlab/diff_parser.rb:41:in `block in each'
  lib/gitlab/diff_parser.rb:18:in `each'
  lib/gitlab/diff_parser.rb:18:in `each'
  app/helpers/commits_helper.rb:19:in `each_diff_line'
  app/helpers/commits_helper.rb:30:in `each_diff_line_near'
  app/views/projects/notes/_discussion_diff.html.haml:13:in `_app_views_projects_notes__discussion_diff_html_haml___2921055492455687737_70106594456980'
  app/views/projects/notes/_discussion.html.haml:39:in `_app_views_projects_notes__discussion_html_haml___4092529718163607957_70106594189980'
  app/views/projects/notes/_notes.html.haml:7:in `block in _app_views_projects_notes__notes_html_haml___380688995549475090_70106593925300'
  app/views/projects/notes/_notes.html.haml:2:in `each'
  app/views/projects/notes/_notes.html.haml:2:in `_app_views_projects_notes__notes_html_haml___380688995549475090_70106593925300'
  app/views/projects/notes/_notes_with_form.html.haml:2:in `_app_views_projects_notes__notes_with_form_html_haml___1307046066054194964_70106593881760'
  app/views/projects/merge_requests/_show.html.haml:33:in `_app_views_projects_merge_requests__show_html_haml__3085060765401066599_70106554294620'
  app/views/projects/merge_requests/diffs.html.haml:1:in `_app_views_projects_merge_requests_diffs_html_haml___1050651612343146530_70106554602220'
  app/controllers/projects/merge_requests_controller.rb:54:in `diffs'
  app/controllers/application_controller.rb:58:in `set_current_user_for_thread'
```

**Comment by ywf1215** [comment]
the same problem with up

**Comment by danger89** [comment]
Same kind of issue when loading the dashboard:

    Started GET "/assets/jquery-ui/ui-bg_flat_75_ffffff_40x100-fe45a1c365adbf8c376fabb6588282ca.png" for 81.20.68.186 at 2015-07-10 14:36:08 +0200                                                                     
    Started GET "/dashboard?limit=20&offset=0" for 81.20.68.186 at 2015-07-10 14:36:08 +0200                                                                                                                           
    Processing by DashboardController#show as JSON                                                                                                                                                                     
      Parameters: {"limit"=>"20", "offset"=>"0"}                                                                                                                                                                       
      Cache digest for app/views/events/_commit.html.haml: 2c2acac0d4b9b4335145af56040e8cb4                                                                                                                            
      Cache digest for app/views/events/event/_push.html.haml: 4910c64eb752cf79c51d399d56da283b                                                                                                                        
      Cache digest for app/views/events/event/_note.html.haml: 162b7179c9930a62ae6d9597f292420b                                                                                                                        
      Cache digest for app/views/events/event/_created_project.html.haml: ff50ddf92a21d2a4c239f1ac535524f6                                                                                                             
      Cache digest for app/views/events/event/_common.html.haml: 50f5e319066a4a693a45072729d273b3                                                                                                                      
      Cache digest for app/views/events/_event.html.haml: 7e62b68fcef4cf62eedde7d695e3e883                                                                                                                             
    Read fragment views/events/38-20150709224902134605000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.4ms)                                                                                     
    Read fragment views/events/37-20150709224356957568000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.6ms)                                                                                     
    Read fragment views/events/36-20150709223823918165000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.6ms)                                                                                     
    Read fragment views/events/35-20150709223740961975000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.5ms)                                                                                     
    Read fragment views/events/34-20150709223028219147000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/33-20150709222948732284000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/32-20150709222843449629000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/31-20150709222806314169000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/30-20150709222501261577000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/29-20150709222418279397000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/28-20150709222358473428000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/27-20150709222236964915000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/24-20150709220447744612000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/23-20150709220358609800000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/22-20150709220047283080000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/21-20150709215944932403000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/20-20150709215840264780000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.3ms)                                                                                     
    Read fragment views/events/19-20150709215817963323000/users/2-20150710083026771165000/7e62b68fcef4cf62eedde7d695e3e883 (0.2ms)                                                                                     
    Completed 500 Internal Server Error in 5829ms (ActiveRecord: 28.3ms)                                                                                                                                               
                                                                                                                                                                                                                       
    ActionView::Template::Error (Object not found - failed to find pack entry (57fd2f7f1680b4b200cadb1d1e99f5afac66a217)):                                                                                             
        2:   .commit-row-title                                                                                                                                                                                         
        3:     = link_to truncate_sha(commit[:id]), namespace_project_commit_path(project.namespace, project, commit[:id]), class: "commit_short_id", alt: ''                                                          
        4:     &nbsp;                                                                                                                                                                                                  
        5:     = gfm event_commit_title(commit[:message]), project: project                                                                                                                                            
      app/models/repository.rb:11:in `new'                                                                                                                                                                             
      app/models/repository.rb:11:in `initialize'                                                                                                                                                                      
      app/models/project.rb:263:in `new'                                                                                                                                                                               
      app/models/project.rb:263:in `repository'                                                                                                                                                                        
      lib/gitlab/markdown/relative_link_filter.rb:124:in `repository'                                                                                                                                                  
      lib/gitlab/markdown/relative_link_filter.rb:32:in `linkable_files?'                                                                                                                                              
      lib/gitlab/markdown/relative_link_filter.rb:16:in `call'                                                                                                                                                         
      lib/gitlab/markdown.rb:82:in `gfm_with_options'                                                                                                                                                                  
      lib/gitlab/markdown.rb:31:in `gfm'                                                                                                                                                                               
      app/views/events/_commit.html.haml:5:in `_app_views_events__commit_html_haml___3977622765486768930_113443200'                                                                                                    
      app/views/events/event/_push.html.haml:18:in `block in _app_views_events_event__push_html_haml___3573280661966887616_52793140'                                                                                   
      app/views/events/event/_push.html.haml:17:in `each'                                                                                                                                                              
      app/views/events/event/_push.html.haml:17:in `_app_views_events_event__push_html_haml___3573280661966887616_52793140'                                                                                            
      app/views/events/_event.html.haml:10:in `block in _app_views_events__event_html_haml__3440528103303886514_49432140'                                                                                              
      app/views/events/_event.html.haml:6:in `_app_views_events__event_html_haml__3440528103303886514_49432140'                                                                                                        
      app/views/events/_events.html.haml:1:in `_app_views_events__events_html_haml___2576839205690425981_48054560'                                                                                                     
      app/controllers/application_controller.rb:229:in `pager_json'                                                                                                                                                    
      app/controllers/dashboard_controller.rb:16:in `block (2 levels) in show'                                                                                                                                         
      app/controllers/dashboard_controller.rb:11:in `show'

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
