### ISSUE TITLE
Editor highlighting doesn't work after upgrading to 6.8

### ISSUE THREAD

**Issue by BaBL86** [gitlabhq/gitlabhq#6850]
When I try to edit code from browser, I have no highlighting. There is an error in browser console:

```
GET http://gitdev.ascottgroup.eu/assets/ace/mode-php.js 404 (Not Found) application-c829d5570fd54ca20cb3a55ba2620093.js:21
```

please, fix this.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
