### ISSUE TITLE
Missing support of umlauts (or accented characters) in project- and groupnames

### ISSUE THREAD

**Issue by bspinner** [gitlabhq/gitlabhq#6865]
Unfortunately support for umlauts `ä`, `ö`, `ü` and the *scharfes S* `ß` (and other characters unused in the English language) is missing for project names and group names.

Please add this, so we don't have to spell our customer's company names wrong. :)

**Comment by TamasBarta** [comment]
Why validate the name at all? It's only important to sanitize it, when creating a path from it. The name should be able to be anything, even emoji.

Here's the very obvious part of the problem: (I see, that it tries to enforce that a name shouldn't start with a dash, but this also makes no sense)
https://github.com/gitlabhq/gitlabhq/blob/13581528480fe63c4f5cd76f7a6844624881ab4a/lib/gitlab/regex.rb#L14

@Razer6 , please respond, this is a very frustrating issue, and at first sight, it looks super easy to fix. I'm not a Ruby developer, but if you tell me that fixing the regex won't break the sanitizer, I'll even send a PR, so this issue can be closed.

**Comment by Razer6** [comment]
This is fixed on master.

**Comment by TamasBarta** [comment]
Thank you so much! Is master included in the next release?

**Comment by Razer6** [comment]
yes :)
