### ISSUE TITLE
Error creating a new label

### ISSUE THREAD

**Issue by eic** [gitlabhq/gitlabhq#6867]
I am getting an 500 error when i try to create a new label during creating a new issue.
Same behavior when i try to create a new label in project settings.

Using version 6.8, the log tell me:
```
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 22):
  app/services/issues/update_service.rb:13:in `execute'
  app/controllers/projects/issues_controller.rb:77:in `update'
  app/controllers/application_controller.rb:59:in `set_current_user_for_thread'
```

**Comment by stanhu** [comment]
@Razer6 This can be closed out now. Fix is here:

https://gitlab.com/gitlab-org/gitlab-ce/commit/2f4426b7e4830f4ec9c318c944c0b53c8af261ab
