### ISSUE TITLE
GitLab API - Pre-confirm accounts

### ISSUE THREAD

**Issue by jbrooksuk** [gitlabhq/gitlabhq#6895]
We're using the API to generate a GitLab account for each user within our internal CRM. They never need to know about this since we're simply asking them for the content (we're generating the title) and posting it as an issue.

During testing of user creation, apart from #6878, the API should be able to be able to bypass the confirmation email, so that they don't know about it.

**Comment by frankscholten** [comment]
+1

**Comment by leecade** [comment]
:+1:   This should be an option.

Many users feedback login failed, because then didn't care confirm email,
we really don't need confirm it.

**Comment by NARKOZ** [comment]
Closed via 5f682094d9b7c985ad62ebe29664bb6fe87b54be
