### ISSUE TITLE
Suggest that the bottom scrollbar on the "Files" page should be always in the screen 

### ISSUE THREAD

**Issue by TurnOffNOD** [gitlabhq/gitlabhq#6903]
When we check the files in a project, often there are very long lines. At this time we need bottom scrollbar to scroll left and right. But now the bottom scrollbar is at the very end of the page, thus it is very inconvenient.

So my suggestion is to keep scrollbar in the bottom of the screen all the time so we can use it at any time.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
