### ISSUE TITLE
Gitlab API Access Connection timed out

### ISSUE THREAD

**Issue by ThibaudDauce** [gitlabhq/gitlabhq#6942]
Hi,

I just installed Gitlab and I have an error during the gitlab-shell self check.

The command returns : 
root@git:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.9.3 ? ... OK (1.9.3)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 
Thibaud / thibaud-dauce ... repository is empty
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection timed out - connect(2) (Errno::ETIMEDOUT)
	from /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /usr/local/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:76:in `get'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:43:in `check'
	from /home/git/gitlab-shell/bin/check:11:in `<main>'
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /home/git/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 
Thibaud / thibaud-dauce ... yes
Projects have satellites? ... 
Thibaud / thibaud-dauce ... can't create, repository is empty
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.10)

Checking GitLab ... Finished

Of course, Gitlab is running :
root@git:/home/git/gitlab# service gitlab status
The GitLab Unicorn web server with pid 1543 is running.
The GitLab Sidekiq job dispatcher with pid 1736 is running.
GitLab and all its components are up and running.

And my config file :
root@git:/home/git/gitlab# sudo -u git -H cat /home/git/gitlab-shell/config.yml
 # GitLab user. git by default
user: git

 # Url to gitlab instance. Used for api calls. Should end with a slash.
gitlab_url: "http://git.thibaud-dauce.fr/"

http_settings:
 #  user: someone
 #  password: somepass
 #  ca_file: /etc/ssl/cert.pem
 #  ca_path: /etc/pki/tls/certs
  self_signed_cert: false

 #  Repositories path
 #  Give the canonicalized absolute pathname,
 #  REPOS_PATH MUST NOT CONTAIN ANY SYMLINK!!!
 #  Check twice that none of the components is a symlink, including "/home".
repos_path: "/home/git/repositories"

 #  File used as authorized_keys for gitlab user
auth_file: "/home/git/.ssh/authorized_keys"

 #  Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/bin/redis-cli
  host: 89.234.146.59
  port: 6379
  # socket: /tmp/redis.socket # Only define this if you want to use sockets
  namespace: resque:gitlab

 #  Log file.
 #  Default is gitlab-shell.log in the root directory.
 #  log_file: "/home/git/gitlab-shell/gitlab-shell.log"

 # Log level. INFO by default
log_level: INFO

 #  Audit usernames.
 #  Set to true to see real usernames in the logs instead of key ids, which is easier to follow, but
 #  incurs an extra API call on every gitlab-shell command.
audit_usernames: false

I already try to replace in Redis conf host: 127.0.0.1 to host: 89.234.146.59
I also try to add  89.234.146.59	git.thibaud-dauce.fr in /etc/hosts

I have a server running Debian 7 32bits with a container LXC for Gitlab, Ruby is version 2.0.0. I have the same error when I try to push a repo (but I can create one online with the web app)

Do you have any idea ? I really look everywhere and found no solution... :(

Thanks a lot

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
