### ISSUE TITLE
Unwanted syntax highlighting

### ISSUE THREAD

**Issue by fenhl** [gitlabhq/gitlabhq#6960]
The docs say:

> Only the fenced code blocks support syntax highlighting.

However, as you can see on [this wiki page](https://gitlab.com/fenhl/jqsh/wikis/filter#command), which uses indented code blocks, this is not true. This is especially jarring for this project, since it is a language.

[The project's license](https://gitlab.com/fenhl/jqsh/blob/master/LICENSE) is also being highlit, even though it is a plain text file with no extension.

I think syntax highlighting should only be applied to files with an appropriate extension, or, within markdown, fenced code blocks with a language annotation.

**Comment by Razer6** [comment]
This is fixed by https://github.com/gitlabhq/gitlabhq/pull/8425
