### ISSUE TITLE
Is there any reason why importing repos from command line won't work?

### ISSUE THREAD

**Issue by trusktr** [gitlabhq/gitlabhq#6983]
I'm trying to do what it says here:
https://github.com/gitlabhq/gitlabhq/wiki/Import-existing-repositories-into-GitLab

It worked for one repository, then I copied a whole bunch over, then when I tried `bundle exec rake gitlab:import:repos RAILS_ENV=production` the second it wouldn't import any repos.

The output isn't useful, only showing that it skipped existing repos:

```
┌─[16:12:44/hypership/git//usr/share/webapps/gitlab]
└─╼ bundle exec rake gitlab:import:repos RAILS_ENV=production
fatal: Not a git repository (or any of the parent directories): .git
Processing trusktr/sk8earth.git
 * sk8earth (trusktr/sk8earth.git) exists
Processing trusktr/sk8earth.wiki.git
 * Skipping wiki repo
Processing trusktr/hp-dsat.git
 * hp-dsat (trusktr/hp-dsat.git) exists
Processing trusktr/hp-dsat.wiki.git
 * Skipping wiki repo
Processing trusktr/webmanager2.wiki.git
 * Skipping wiki repo
Processing trusktr/webmanager2.git
 * webmanager2 (trusktr/webmanager2.git) exists
Processing pocket-protectors/hp-dsat.wiki.git
 * Skipping wiki repo
Processing pocket-protectors/hp-dsat.git
 * HP DSAT (pocket-protectors/hp-dsat.git) exists
Processing hero/hp-dsat.git
 * hp-dsat (hero/hp-dsat.git) exists
Processing bickerin/hp-dsat.git
 * HP DSAT (bickerin/hp-dsat.git) exists
Processing csc250/voting-system-5000.git
 * Voting System 5000 (csc250/voting-system-5000.git) exists
Processing csc250/voting-system-5000.wiki.git
 * Skipping wiki repo
Processing betta-footwear/website.git
 * website (betta-footwear/website.git) exists
Processing betta-footwear/website.wiki.git
 * Skipping wiki repo
Processing buzztrax/website.wiki.git
 * Skipping wiki repo
Processing buzztrax/website.git
 * website (buzztrax/website.git) exists
Done!
```

It doesn't show any output regarding the new repositories that I've pasted. I've triple checked that the repos are owned by the `git` user (i'm using `git` instead of `gitlab`) and that the permission allow for `git` to read/write all files.

Are there any specific reasons why import might now work?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
