### ISSUE TITLE
Race condition in web editor / generates bad commits.

### ISSUE THREAD

**Issue by gbb** [gitlabhq/gitlabhq#7000]
Hi guys, an easy to trigger race condition in the web file editor. (Gitlab version: 6.7.2)

We have a page for meeting minutes (attached at bottom). When two or more people try to write their weekly notes at the same time, one set of notes is lost. This is because the commit generated by the second person reverts the text of the first person's committed changes. The problem becomes worse with more people. 

Pattern: 

Person1 opens the edit page and begins adding their notes.
Person2 opens the edit page and begins adding their notes.
Person1 saves and commits their notes.
Person2 saves and commits their notes. This silently reverts the text from Person1. 

There needs to be a merge here which isn't happening. The editor should make a note of the version of the file when the edit page is opened - so that the commit can be with respect to the *latest version at the time of opening* and not the *latest version at the time of commit*.

Example text template as seen by Person2 before their commit:

    Person1
    -     
    -

    Person2
    - My stuff 
    - More stuff

    Person3    
    -
    -

Example text template as seen by Gitlab before Person 2's commit.

    Person1
    - My thing
    - My other thing

    Person2
    - 
    - 

    Person3
    -
    -

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
