### ISSUE TITLE
CI Status Not Allowing Unknown

### ISSUE THREAD

**Issue by bassrock** [gitlabhq/gitlabhq#7047]
Hi,

I am developing a plugin for a new ci service and while going through how Gitlab, connects to GItlab CI I see it allows an unknown state. This however is not allowed in the page that gets displayed to the user in merge requests and instead the user sees an unable to connect to CI error, when really it should be an "Unallowed state" error.

Either way in this section: https://github.com/gitlabhq/gitlabhq/blob/7c6a58a756cc3bff78a6d0a0ca8abfe9b2c147da/app/assets/javascripts/merge_request.js.coffee#L91     

It should allow an unknown state since Gitlab CI allows it.

**Comment by pmalek** [comment]
:+1: (long time and no one has responded to this issue)

**Comment by brauliobo** [comment]
+1

**Comment by ihrwein** [comment]
+1

**Comment by Kurry** [comment]
+1

**Comment by berni2288** [comment]
+1

**Comment by cnelsonsic** [comment]
:+1:

**Comment by CodingMinds** [comment]
+1

**Comment by eugalata4** [comment]
+1

**Comment by bdandoy** [comment]
+1

**Comment by frvge** [comment]
+1

**Comment by bsingr** [comment]
+1

**Comment by thatarchguy** [comment]
+1

**Comment by mariane-sm** [comment]
+1

**Comment by nervo** [comment]
:+1:

**Comment by AndreaGiardini** [comment]
+1

**Comment by wikiwi** [comment]
+1

**Comment by kalibyrn** [comment]
There is now a "not_found" state...  Does that work?

https://github.com/gitlabhq/gitlabhq/blob/05fdd12fd984ffee0b2c9be3821fbc9a67abc6d4/app/assets/javascripts/merge_request_widget.js.coffee#L40

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
