### ISSUE TITLE
Mardown Inline HTML not working in Wiki

### ISSUE THREAD

**Issue by fspreiss** [gitlabhq/gitlabhq#7066]
1. **Summary**: The use of raw HTML in Markdown does not work (in the Wiki). This issue was observed in version 6.8.1.

2. **Steps to reproduce**: Create/edit a Wiki page and enter some raw/inline HTML, such as the definition lists described in the Markdown documentation at [github.com][1] or [gitlab.com][2]:
   ```HTML
   <dl>
     <dt>Definition list</dt>
     <dd>Is something people use sometimes.</dd>

     <dt>Markdown in HTML</dt>
     <dd>Does *not* work **very** well. Use HTML <em>tags</em>.</dd>
   </dl>
   ```
   The same problem occurs when using other HTML tags such as a \<table\> tags.

3. **Expected behavior**: The HTML is rendered correctly as seen in the Markdown documentation at [github.com][1] and in the following image:
![md-inlinehtml-correct](https://cloud.githubusercontent.com/assets/3296673/3157823/03d738bc-eafb-11e3-9e0b-6791d3df0305.png)

4. **Observed behavior**: The output is rendered incorrectly as seen in the Markdown documentation at [gitlab.com][2] and in the following image:
![md-inlinehtml-incorrect](https://cloud.githubusercontent.com/assets/3296673/3157827/12acedd2-eafb-11e3-8323-e4829e64ad53.png)

[1]: https://github.com/gitlabhq/gitlabhq/blob/master/doc/markdown/markdown.md#inline-html
[2]: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/markdown/markdown.md#inline-html

**Comment by siancu** [comment]
Any status on this one? Will it get merged or not?
