### ISSUE TITLE
[Feature Request] Add option to re-enable spacebar heating

### ISSUE THREAD

**Issue by teuneboon** [gitlabhq/gitlabhq#7072]
From the changelog:
```
v 7.0.0
  - The CPU no longer overheats when you hold down the spacebar
```

This change breaks my workflow. I was holding down the spacebar to keep warm in the winter. Can you please add an option to re-enable this behavior?

**Comment by dosire** [comment]
WONTFIX

**Comment by jvanbaarsen** [comment]
WUT? :cry:

**Comment by dosire** [comment]
@jvanbaarsen it will be an Enterprise Edition only feature, sorry
