### ISSUE TITLE
[Flowdock] Link to commit is not working (results in 500 error)

### ISSUE THREAD

**Issue by simkin** [gitlabhq/gitlabhq#7080]
**I linked one of my projects with Flowdock and sumbitted a file:**
```
lmolenaar@test-server:~/lm-test2> git add README
lmolenaar@test-server:~/lm-test2> git commit -m 'flowdock test'
[master (root-commit) abb1bd3] flowdock test
 1 file changed, 1 insertion(+)
 create mode 100644 README
lmolenaar@test-server:~/lm-test2> git push -u origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 224 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To git@gitlab.servername.nl:lmolenaar/lm-test2.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
```
**I see the expected popup in flowcdock:**
![screenshot_6](https://cloud.githubusercontent.com/assets/958263/3184459/a6314d8e-ec84-11e3-9121-1bf7a6aefd10.png)

**But when I click the link:**
``
https://gitlab.servername.nl/lmolenaar/lm-test2/compare/0000000000000000000000000000000000000000...abb1bd32845c18ac14e683203adc267c3b44ae6f 
``
![image](https://cloud.githubusercontent.com/assets/958263/3184474/e06add12-ec84-11e3-8c05-023f3376aa93.png)

**The file has been committed correctly:**
![image](https://cloud.githubusercontent.com/assets/958263/3184508/7d4430c0-ec85-11e3-9aa0-a8ba797d5c3d.png)

![image](https://cloud.githubusercontent.com/assets/958263/3184511/8fcd97a4-ec85-11e3-91b7-5fe939b66ad5.png)

Is this a bug or am I doing something wrong?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
