### ISSUE TITLE
[GEM UPDATE] charlock_holmes >= 0.7

### ISSUE THREAD

**Issue by ghost** [gitlabhq/gitlabhq#7104]
Hi,

a gem version update for charlock_holmes to version >= 0.7 would be a great enhancement, since it would fix some charlock_holmes problems e.g. when it is installed on rpm-based x86_64-systems, see bugfix [here](https://github.com/brianmario/charlock_holmes/issues/58).

*gitlab-linguist*/*gitlab-grit* also includes this charlock_holmes dependency (< 0.7), so an update to the latest 0.7 series of charlock_holmes in *gitlab-linguist* should be done there, too.

Many thanks in advance,

Stefan

**Comment by stefan-it** [comment]
Short update on that - with:

```bash
env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
bundle install --deployment --without development test postgres aws
```

the *old* charlock_holmes version `0.6.9.4`  (currently used version in GitLab) is working on *openSUSE* 13.1/13.2 -> but it's only a workaround to get the bundle process sucessfully done.

*gem* update to a version >= 0.7 would be really appreciated!

**Comment by stefan-it** [comment]
Another update on that:

```bash
unset CONFIG_SITE
```

seems to work on openSUSE 13.2 - as mentioned [here](https://github.com/brianmario/charlock_holmes/issues/93) :)

**Comment by Razer6** [comment]
Closing so far since issues are not reproducible.

**Comment by thomasschaeferm** [comment]
Please reopen it, or solve the issue.

**Comment by thomasschaeferm** [comment]
This variable `CONFIG_SITE` is set by the package `site-config`.

Summary: Site Paths Configuration for autoconf Based configure Scripts
Description :
Site configuration for autoconf based configure scripts provides smart
defaults for paths that are not specified.

The old `charlock_holmes` gem has a verified problem. It is solved in higher versions.

**Comment by stanhu** [comment]
Yeah, it looks like all the other gems (gitlab-grit, gitlab-linguist) currently depend on 0.6.x. I don't see any documentation indicating moving to 0.7.x would cause any breaking changes, though.
