### ISSUE TITLE
No way to change a branch of created merge request

### ISSUE THREAD

**Issue by Olegas** [gitlabhq/gitlabhq#7105]
GitLab 6.9.2

In 6.2 while edit merge request, there was ability to change a source/target branch. Now I can't do this.

**Comment by berni2288** [comment]
:+1:

**Comment by teerapap** [comment]
:+1:

**Comment by johgoe** [comment]
+1

**Comment by Ch00k** [comment]
:+1:

**Comment by carlosparamio** [comment]
:+1:

**Comment by mrts** [comment]
:+1:

**Comment by mrts** [comment]
As GitLab devs don't trace GitHub issue tracker any more, please upvote https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/130 instead of this issue.

**Comment by Grokzen** [comment]
:+1:

**Comment by mrts** [comment]
Gentlemen, I'm pleased to announce that the bounty is up both for backers and developers at https://www.bountysource.com/issues/2589028-no-way-to-change-a-branch-of-created-merge-request. If you want this issue fixed but have no skills to do it yourself, please consider backing the bounty in Bountysource.

**Comment by ixisio** [comment]
+1

**Comment by stanhu** [comment]
I need to feed my family. Here you go:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/738
