### ISSUE TITLE
Couldn't find file 'underscore' browser error, 404 on /users/sign_out

### ISSUE THREAD

**Issue by emcniece** [gitlabhq/gitlabhq#7124]
I am not able to browser to `/users/sign_out` - it throws a 404 and dumps this to `log/production.log`:

	Started GET "/users/sign_out" for 127.0.0.1 at 2014-06-12 11:51:49 -0700
	Processing by ProjectsController#show as HTML
	  Parameters: {"id"=>"users/sign_out"}
	Filter chain halted as :project rendered or redirected
	Completed 404 Not Found in 39ms (Views: 30.6ms | ActiveRecord: 0.8ms)
	Started GET "/static.css" for 127.0.0.1 at 2014-06-12 11:51:49 -0700
	Processing by NamespacesController#show as HTML
	  Parameters: {"id"=>"static.css"}
	Completed 404 Not Found in 74ms (Views: 6.4ms | ActiveRecord: 2.6ms)

In addition, the browser javascript console is throwing the following error:

	Uncaught Error: Sprockets::FileNotFound: couldn't find file 'underscore' (in /home/git/gitlab/app/assets/javascripts/application.js.coffee:29) 

Setup was performed by following https://github.com/gitlabhq/gitlab-recipes/tree/master/install/centos - I cloned the master branch instead of 6.9 however.

I have tried altering various files through the following issues:
* https://github.com/gitlabhq/gitlabhq/issues/6396
* https://github.com/gitlabhq/gitlabhq/issues/7110#issuecomment-45811086
* http://stackoverflow.com/questions/6567863/no-route-matches-get-users-sign-out
* http://stackoverflow.com/questions/21040168/rails-devise-error-no-route-matches-get-users-sign-out

No luck yet on this problem.

Output of `sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production`:

	System information
	System:         CentOS 6.5
	Current User:   git
	Using RVM:      no
	Ruby Version:   1.9.3p194
	Gem Version:    2.1.2
	Bundler Version:1.3.5
	Rake Version:   10.3.2
	Sidekiq Version:2.17.0

	GitLab information
	Version:        7.0.0.pre
	Revision:       11e1c01
	Directory:      /home/git/gitlab
	DB Adapter:     mysql2
	URL:            http://gitlab.develapache
	HTTP Clone URL: http://gitlab.develapache/some-project.git
	SSH Clone URL:  git@gitlab.develapache:some-project.git
	Using LDAP:     no
	Using Omniauth: no

	GitLab Shell
	Version:        1.9.5
	Repositories:   /home/git/repositories/
	Hooks:          /home/git/gitlab-shell/hooks/
	Git:            /usr/bin/git

Output of `sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production`:

	Checking Environment ...

	Git configured for git user? ... yes

	Checking Environment ... Finished

	Checking GitLab Shell ...

	GitLab Shell version >= 1.9.4 ? ... OK (1.9.5)
	Repo base directory exists? ... yes
	Repo base directory is a symlink? ... no
	Repo base owned by git:git? ... yes
	Repo base access is drwxrws---? ... yes
	Satellites access is drwxr-x---? ... yes
	update hook up-to-date? ... yes
	update hooks in repos are links: ... can't check, you have no projects
	Running /home/git/gitlab-shell/bin/check
	Check GitLab API access: OK
	Check directories and files:
			/home/git/repositories/: OK
			/home/git/.ssh/authorized_keys: OK
	Test redis-cli executable: redis-cli 2.4.10
	Send ping to redis server: PONG
	gitlab-shell self-check successful

	Checking GitLab Shell ... Finished

	Checking Sidekiq ...

	Running? ... yes
	Number of Sidekiq processes ... 1

	Checking Sidekiq ... Finished

	Checking LDAP ...

	LDAP is disabled in config/gitlab.yml

	Checking LDAP ... Finished

	Checking GitLab ...

	Database config exists? ... yes
	Database is SQLite ... no
	All migrations up? ... yes
	Database contains orphaned UsersGroups? ... no
	GitLab config exists? ... yes
	GitLab config outdated? ... no
	Log directory writable? ... yes
	Tmp directory writable? ... yes
	Init script exists? ... yes
	Init script up-to-date? ... no
	  Try fixing it:
	  Redownload the init script
	  For more information see:
	  doc/install/installation.md in section "Install Init Script"
	  Please fix the error above and rerun the checks.
	projects have namespace: ... can't check, you have no projects
	Projects have satellites? ... can't check, you have no projects
	Redis version >= 2.0.0? ... yes
	Your git bin path is "/usr/bin/git"
	Git version >= 1.7.10 ? ... yes (1.8.3)

	Checking GitLab ... Finished

Does anybody have an idea of where I can continue troubleshooting? Thanks for taking a look :S

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
