### ISSUE TITLE
Upgrade gitlab 4.2 to 5.0 error wiki migrate incompatible character encodings utf-8 and ascii-8bit

### ISSUE THREAD

**Issue by maykel535** [gitlabhq/gitlabhq#7138]
Hi, I migrated gitlab 4.1 to 4.2 works very well. But, when I'm going to migrate gitlab 4.2 to 5.0 received this error when migrate wiki:

root@gitlab:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:wiki:migrate RAILS_ENV=production

Migrating Wiki for 'diego/bankinter-brokertouch'
Creating page 'README'...
Failed to create page 'home' [FAILED]
Project 'diego/bankinter-brokertouch' migrated. [OK]

Migrating Wiki for 'diego/alsa-html5'
Creating page 'Índice'...
Failed to create page 'home' [FAILED]
Project 'diego/alsa-html5' migrated. [OK]

Migrating Wiki for 'eva.madrazo/sdk-ads'
Creating page 'Descripción de la librería'...
Failed to create page 'home' [FAILED]
Project 'eva.madrazo/sdk-ads' migrated. [OK]

Migrating Wiki for 'diego/carrefour-alimentacion'
Creating page 'Cheques ahorro'...
Failed to create page 'Cheques-ahorro' [FAILED]
Creating page 'Códigos de cupón'...
Failed to create page 'Códigos-de-cupón' [FAILED]
Creating page 'Ayuda'...
rake aborted!
incompatible character encodings: UTF-8 and ASCII-8BIT
/home/git/gitlab/vendor/bundle/ruby/1.9.1/bundler/gems/grit-c40a32432616/lib/grit/index.rb:176:in %' /home/git/gitlab/vendor/bundle/ruby/1.9.1/bundler/gems/grit-c40a32432616/lib/grit/index.rb:176:inblock in write_tree'
/home/git/gitlab/vendor/bundle/ruby/1.9.1/bundler/gems/grit-c40a32432616/lib/grit/index.rb:171:in each' /home/git/gitlab/vendor/bundle/ruby/1.9.1/bundler/gems/grit-c40a32432616/lib/grit/index.rb:171:inwrite_tree'
/home/git/gitlab/vendor/bundle/ruby/1.9.1/bundler/gems/grit-c40a32432616/lib/grit/index.rb:123:in commit' /home/git/gitlab/vendor/bundle/ruby/1.9.1/bundler/gems/gollum-5dcd3c8c8f68/lib/gollum/committer.rb:163:incommit'
/home/git/gitlab/vendor/bundle/ruby/1.9.1/bundler/gems/gollum-5dcd3c8c8f68/lib/gollum/wiki.rb:327:in write_page' /home/git/gitlab/app/models/gollum_wiki.rb:74:increate_page'
/home/git/gitlab/app/models/wiki_page.rb:168:in save' /home/git/gitlab/app/models/wiki_page.rb:127:increate'
/home/git/gitlab/lib/wiki_to_gollum_migrator.rb:71:in create_page_and_revisions' /home/git/gitlab/lib/wiki_to_gollum_migrator.rb:52:inblock in create_pages'
/home/git/gitlab/lib/wiki_to_gollum_migrator.rb:51:in each' /home/git/gitlab/lib/wiki_to_gollum_migrator.rb:51:increate_pages'
/home/git/gitlab/lib/wiki_to_gollum_migrator.rb:19:in block in migrate!' /home/git/gitlab/lib/wiki_to_gollum_migrator.rb:16:ineach'
/home/git/gitlab/lib/wiki_to_gollum_migrator.rb:16:in migrate!' /home/git/gitlab/lib/tasks/gitlab/migrate_wiki.rake:23:inblock (3 levels) in '
Tasks: TOP => gitlab:wiki:migrate
(See full trace by running task with --trace)

I follow this upgrade guide:

https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/4.2-to-5.0.md

I have this version:

root@gitlab:/home/git/gitlab# bundle exec rake gitlab:env:info RAILS_ENV=production

System information
System: Debian 6.0.7
Current User: root
Using RVM: no
Ruby Version: 1.9.3p327
Gem Version: 1.8.23
Bundler Version:1.2.4
Rake Version: 10.0.3

GitLab information
Version: 5.0.1
Revision: 0702bd6
Directory: /home/git/gitlab
DB Adapter: mysql2
URL: http://gitlab.mo2o.com
HTTP Clone URL: http://gitlab.mo2o.com/some-project.git
SSH Clone URL: git@gitlab.mo2o.com:some-project.git
Using LDAP: no
Using Omniauth: no

GitLab Shell
Version: 1.1.0
Repositories: /home/git/repositories/
Hooks: /home/git/gitlab-shell/hooks/
Git: /usr/bin/git

I think the error is reported in gitlab forum, but I ' can't resolved it...I follow this solutions but not work for me...

Can I help me please?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
