### ISSUE TITLE
Require Administrative Approval 

### ISSUE THREAD

**Issue by Meatballs1** [gitlabhq/gitlabhq#7207]
https://github.com/Meatballs1/gitlabhq/tree/admin_user_auth

The above diff initializes new users in a blocked state. An administrator has to unblock them after initial registration.

Current bugs - if a new deployment is used it blocks the root/admin user.

**Comment by tebruno99** [comment]
It is a shame they seem to have completely ignored this.  This is a fantastic feature and much needed than the all or nothing configuration provided.

**Comment by Meatballs1** [comment]
I should probably do a proper pull request but was too much like hard work to drag from internal environment :)

**Comment by matthewcordaro** [comment]
Feature request found [here](http://feedback.gitlab.com/forums/176466-general/suggestions/6069583-add-approval-system-for-user-signup).  Vote it up!

**Comment by wuebbel** [comment]
Is that diff really working? I'm trying to understand the code. I figure that the old initial value should be :active, not :blocked as quoted in the diff for user.rb?

I don't wish to mess with the code too much, so if the only change I make is changing :active to :blocked in that very line in user.rb, all new users will be inactive, only I don't get a mail, right?

**Comment by Meatballs1** [comment]
@weubbel ah yes I probably diff'd from some code I had already modified :)

`state_machine :state, initial: :blocked` would work, email notifications are handy though ;)

**Comment by Meatballs1** [comment]
I uploaded to a proper branch:

https://github.com/Meatballs1/gitlabhq/tree/admin_user_auth

However, testing on a new install it blocks the `root` account on deployment :)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
