### ISSUE TITLE
gitlab backup restore fails on notes… syntax error, unexpected $undefined ip + \“:\” + scope.function_hiera(

### ISSUE THREAD

**Issue by pcbadger** [gitlabhq/gitlabhq#7209]
I've built a new server for gitlab 5.1 (actually, I built 2 just to be sure, I had a few hiccups with the first one) I'm trying to restore a backup from another server. I followed these instructions with mysql https://github.com/gitlabhq/gitlabhq/blob/5-1-stable/doc/install/installation.md

(the only deviation was that I had to edit the gemfile to replace modernizer 2.6.2 with modernizer-rails 2.7.1 as that gem is no longer available)

I ran this command to restore

<pre> sudo -u git bundle exec rake gitlab:backup:restore RAILS_ENV=production --trace </pre>
and it craps out with this error

<pre> notes ... rake aborted!
(erb):103939: syntax error, unexpected $undefined
ip + \":\" + scope.function_hiera([...
      ^</pre> 
(full trace available here http://pastebin.com/cX5kTTzu )

Our repos contain a lot of puppet code with hiera data and it looks like it's somehow trying to interpret that and i really don't know what to do about it.

Here's my sysinfo

System information

System: Ubuntu 12.04
Current User: git
Using RVM: no
Ruby Version: 1.9.3p392
Gem Version: 1.8.23
Bundler Version:1.6.3
Rake Version: 10.0.3

GitLab information
Version:    5.0.1
Revision:   951273f
Directory:  /home/git/gitlab
DB Adapter: mysql2
URL:        http://localhost
HTTP Clone URL: http://localhost/some-project.git
SSH Clone URL:  git@localhost:some-project.git
Using LDAP: no
Using Omniauth: no

GitLab Shell
Version:    1.3.0
Repositories:   /home/git/repositories/
Hooks:      /home/git/gitlab-shell/hooks/
Git:        /usr/bin/git
The status check shows the repos as created, but empty. Oddly it tells me I need to upgrade to git shell 1.1.0, so I might try that for a giggle

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
