### ISSUE TITLE
Additional filtering for commit page

### ISSUE THREAD

**Issue by tomplast** [gitlabhq/gitlabhq#7219]
In addition to today's ability to filter the commit history on branch the following would also be nice to have:
- Filter on commit date interval, maybe using two datepickers?
- Filter commits from a specific (or many) author(s).
- Filter commits based on the commit message.

I wouldn't mind get my hands dirty and try to implement this myself, but is there anyone else who would feel that they would benefit from these suggestions?

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
