### ISSUE TITLE
Masters of Groups have no more rights than Developers of Groups !!!

### ISSUE THREAD

**Issue by iKiKi** [gitlabhq/gitlabhq#7290]
You have introduced permissions at `Group` level, but the matrix is too restrictive in my opinion.

I don't understand why `Masters` of `Groups` have the same permissions like `Developers`.
I would recommend to give the following permissions to `Masters` at `Group` Level :
* Edit group
* Manage group members

It would lead to this new matrix :

![matrix](https://cloud.githubusercontent.com/assets/2060917/3536954/a4d4563e-0818-11e4-8627-cf08459c838e.png)

These new permissions mean that :
* only `Owners` would be able to create `Projects` inside the `Group` or remove the `Group`.
* `Masters` can also (like `Owners`) edit `Group` (change the image of the `Group`...) and manage `Group` members (avoiding to add multiple times users in some `Projects` of the `Group`).

I think this is more logical and flexible (a better usage of permissions at `Group`level) :-)

**Comment by pjweisberg** [comment]
Why would <code>Master</code> not be allowed to create new projects?  (For that matter, shouldn't <code>Developer</code> also be able to create new projects?)

**Comment by iKiKi** [comment]
In my company, it makes sense that `Master` don't have permission to create new projects. But other contexts could give this permission.

That's why I raised [this suggestion](http://feedback.gitlab.com/forums/176466-general/suggestions/6844285-ability-to-configure-permissions-table) and I recommend to make the permission table configurable.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
