### ISSUE TITLE
Add support for importing from ssh urls

### ISSUE THREAD

**Issue by fastest963** [gitlabhq/gitlabhq#7307]
I wanted to import a private github repo into gitlab and couldn't because neither https or git support ssh keys. I edited app/models/project.rb to allow ssh urls then imported: `ssh://git@github.com/githubuser/repo.git` and everything worked fine. Is there a specific reason that ssh protocol isn't supported?

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
