### ISSUE TITLE
Make Graphs distinct by mail

### ISSUE THREAD

**Issue by kaystrobach** [gitlabhq/gitlabhq#7315]
this report is regarding : http://host/group/project/graphs/master

if you have people who use always the same e-mail address, but sometimes different clear names the grouping may fail, as you get the same user with different names, but same e-mail address.

![image](https://cloud.githubusercontent.com/assets/1185776/3598790/cbca808c-0ce7-11e4-8dfc-28e93170d7d2.png)

In the example the user used the same e-mail address, but different values for the name.

The Repo is imported from github, so not all users in the list may have an account on in this particular gitlab.

**Comment by lordloh** [comment]
I am using GitLab 7.4.2 477743a. I have two different names and two different emali address. Both the emails are registered in my account. It would make sense to club all commits by account - inclusive of all email addresses registered it the account.

**Comment by rumpelsepp** [comment]
> For consideration:
>   * I think we should use GitLab names, not commit names
>   * Users can have multiple email addresses in GitLab that should be combined

* Consider honoring `.mailmap`: http://git-scm.com/docs/git-shortlog#_mapping_authors

**Comment by Razer6** [comment]
This will finally be fixed by https://gitlab.com/gitlab-org/gitlab-ce/issues/3254. Closing here and move discussion to the MR
