### ISSUE TITLE
Merge Request Comments: how should they work?

### ISSUE THREAD

**Issue by darinkes** [gitlabhq/gitlabhq#7342]
Hi,

Setup: GitLab 7.0.0 de9bf7d

When a merge request gets opened, and some devs discuss about a line of code
in the merge request, a new Discussion about this line gets opened, e.g.:

Stefan Rinkes started a discussion on this merge request diff README.md:L19

Now the dev fixes the line of code and pushes the fixed commit with force (git push -f) to the merge request.

But some other dev also doesn't like the fix in the updated merge request and wants
to comment the current line of code. This comment gets attached to discussion about the
old line of code. I don't think this is the wanted behavior.
Since this behavior makes it impossible to discuss a line of code in an updated merge
request.

Quite complicated to describe :/
I hope I didn't missed the point :)

**Comment by senthilkumar-kj** [comment]
We're using GitLab 7.0 and we have the same issue. With 6.x, even when we do force push, comments were preserved in the merge request and it was hugely helpful. With 7 they just disappear.

**Comment by senthilkumar-kj** [comment]
No, I take it back. The behavior HAS NOT changed. (The developer had commented on the commit instead of changes).
