### ISSUE TITLE
Image attachments download instead of being viewed in the browser

### ISSUE THREAD

**Issue by bobrovnikov** [gitlabhq/gitlabhq#7352]
As far as I remember, images attached to the posts were available to see inside browser window, when the link opened with target="_blank". However, after recent updates images are downloaded instead of being viewed directly. And this type of behaviour is rather inconvenient. Is there any config I can change to fix this?

**Comment by Razer6** [comment]
Implemented with https://github.com/gitlabhq/gitlabhq/commit/0a9cab4ee65f2b42c56989698c401cab60d68b53
