### ISSUE TITLE
Creating tag in gitlab UI does not fire web hook

### ISSUE THREAD

**Issue by lbdroid** [gitlabhq/gitlabhq#7357]
I have created a web hook for tag push events, which calls on a gitlab-ci instance.

When I create and push a tag using commandline/ssh, the tag is created and the web hook to gitlab-ci is called, triggering a build of the project.

When I create a tag using the browser/ui, the tag is created, but the web hook is *not* called.

**Comment by kylekatarnls** [comment]
Very interessted in this. Any news?

**Comment by bmartus** [comment]
Also finding this issue ..  

Just updated GitLab:
```
GitLab 7.7.2
GitLab Shell 2.4.2
GitLab API v3
Ruby 2.1.4p265
Rails 4.1.1
```

The hook works if I use the 'Test Hook' button on the Web Hook setup page, but it won't fire when I tag the repo.  Firing this off when tagging via the UI would be nice.

**Comment by sas05** [comment]
I found this bug on previous version of gitlab, but after upgrading gitlab I'm still having this. gitlab version is GitLab 7.7.2

**Comment by qwe2003** [comment]
+1

**Comment by leafymind** [comment]
+1

**Comment by cjpabloL** [comment]
+1

**Comment by geoffwhittington** [comment]
+1

**Comment by fiddyspence** [comment]
+1

**Comment by alan-schwarzenberger** [comment]
Was this fixed by Was fixed in 7.9.0 by https://github.com/gitlabhq/gitlabhq/commit/b8f5e23f270df85b32baa1fd6912b6a5eb334755 as per the description in that commit which went into 7.9.0? I'll test tomorrow.

**Comment by Razer6** [comment]
@alan-schwarzenberger Thanks for reporting back. I just tested this on gitlab.com with version 8.2 and can confirm this working.

**Comment by alan-schwarzenberger** [comment]
Also confirmed working in version 7.10.4
