### ISSUE TITLE
[Gitlab 7.1] 422 when trying to transfer project to other namespace

### ISSUE THREAD

**Issue by Wachiwi** [gitlabhq/gitlabhq#7370]
**Summary:** Getting a 422 (The change you wanted was rejected.) when transfering a project to other namespace after upgrade to 7.1

**Steps to reproduce:**
1. Create a project in Gitlab 7.0 with the visibility *internal*
2. Upgrade to Gitlab 7.1
3. Try to transfer the project via adminarea to other namespace

**Expected behavior:** The project should be transferred to the other namespace as planned

**Observed behavior:** When trying to transfer the project to the new namespace, I recieve a 422 (see below)

![capture](https://cloud.githubusercontent.com/assets/4199845/3698659/fd6732d0-13c6-11e4-80c9-d8113541a731.PNG)

If I create a new project in Gitalb 7.1 with visibility *internal* I can transfer it.

**Relevant logs and/or screenshots:**
* nginx logs have nothing special
* production/application/sattelites have nothing special

**Output of checks:**

```
[root] bundle exec rake gitlab:env:info RAILS_ENV=production

System information
System:         CentOS 6.5
Current User:   root
Using RVM:      no
Ruby Version:   2.1.2p95
Gem Version:    2.4.1
Bundler Version:1.5.3
Rake Version:   10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:        7.1.0
Revision:       68a9203
Directory:      /var/lib/git/gitlab
DB Adapter:     mysql2
URL:            https://example.com
HTTP Clone URL: https://example.com/some-project.git
SSH Clone URL:  git@example.com:some-project.git
Using LDAP:     yes
Using Omniauth: no

GitLab Shell
Version:        1.9.6
Repositories:   /path/to/repos
Hooks:          /var/lib/git/gitlab-shell/hooks/
Git:            /usr/local/bin/git
```

```
[root] sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.9.6 ? ... OK (1.9.6)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ...

<projects: all ok>

Running /var/lib/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
        /path/to/repo: OK
        /var/lib/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.4.10
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

<removed ldap users>

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ...

<projects: all ok>

Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/local/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.0)

Checking GitLab ... Finished
```

**Possible Fixes:**

IfI change the visibility from *internal* to *private* and try to transfer again it works!

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
