### ISSUE TITLE
Side-by-side diff displays all lines in file

### ISSUE THREAD

**Issue by jameshfisher** [gitlabhq/gitlabhq#7397]
It appears that when using the "Side-by-side Diff" view, all lines in the whole file are displayed. This is in contrast to the behavior in the "Inline Diff" view, where only the changed hunks and six lines of context are shown.

This behavior should be consistent.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
