### ISSUE TITLE
Impossible to set Default Branch on repo with one non-master branch

### ISSUE THREAD

**Issue by jmontleon** [gitlabhq/gitlabhq#7401]
Opening against 7.1.1 since #7325 was closed.
gitlab-7.1.1_omnibus-1.el6.x86_64

Create a new project, defaultbranchtest
git clone git@$hostname:$user/defaultbranchtest.git
cd defaultbranchtest/
git checkout -b foo
echo 123 > README
git add README
git commit -m "initial commit" .
git push --set-upstream origin foo

Try over and over and over in the WebUI to set the Default Branch to foo but HEAD still reads: ref: refs/heads/master

git branch bar
git checkout bar
git push --set-upstream origin bar

Now in the UI I can switch between branches and HEAD gets updated.

**Comment by nysthee** [comment]
I cannot reproduce this in GitLab 7.8.2 17ea015 (what we have in production). This can be closed I guess?

**Comment by stanhu** [comment]
Thanks! I think 03138a3c72 may also help this case in GitLab v7.12 to be released on June 22.
