### ISSUE TITLE
gitlab stops triggering gitlab-ci when gitlab-ci is restarted

### ISSUE THREAD

**Issue by n-e-g** [gitlabhq/gitlabhq#7412]
Starting components in order:
1) gitlab-ci
2) gitlab
makes thw whole environment working

When, due to some issue gitlab-ci must be restarted, gitlab stops triggering builds.

**Comment by DuLerWeil** [comment]
same issue.
GitLab CI 5.4.2 8ba2fc2
GitLab 7.7.2 ec15723
installed on th same machine.
one start later, would kill the other's sidekiq instance and start it's own.

**Comment by DuLerWeil** [comment]
[root@repos ~]# service gitlab_ci start
Starting both the GitLab CI Unicorn and Sidekiq.
The GitLab CI Unicorn web server with pid 14669 is running.
The GitLab CI Sidekiq job dispatcher with pid 14677 is running.
GitLab CI and all its components are up and running.
[root@repos ~]# ps afx|grep git
14726 ?        Ss     0:00  \_ postgres: git gitlab_ci_production [local] idle                 
14727 ?        Ss     0:00  \_ postgres: git gitlab_ci_production [local] idle                 
14729 pts/0    S+     0:00          \_ grep git
14669 ?        Sl     0:03 unicorn_rails master -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                               
14690 ?        Sl     0:00  \_ unicorn_rails worker[0] -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                            
14693 ?        Sl     0:00  \_ unicorn_rails worker[1] -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                            
14677 ?        Sl     0:03 sidekiq 2.17.0 gitlab-ci [0 of 25 busy]                                                                                                                                                   
[root@repos ~]# service gitlab start
Starting unicorn:                                          [  OK  ]
Starting sidekiq:                                          [  OK  ]
[root@repos ~]# ps afx|grep git
14726 ?        Ss     0:00  \_ postgres: git gitlab_ci_production [local] idle                 
14727 ?        Ss     0:00  \_ postgres: git gitlab_ci_production [local] idle                 
14805 ?        Ss     0:00  \_ postgres: git gitlabhq_production [local] idle                  
14836 pts/0    S+     0:00          \_ grep git
14669 ?        Sl     0:03 unicorn_rails master -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                               
14690 ?        Sl     0:00  \_ unicorn_rails worker[0] -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                            
14693 ?        Sl     0:00  \_ unicorn_rails worker[1] -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                            
14762 ?        Sl     0:10 unicorn_rails master -D -c /home/git/gitlab/config/unicorn.rb -E production                                            
14769 ?        Sl     0:00  \_ unicorn_rails worker[0] -D -c /home/git/gitlab/config/unicorn.rb -E production                                         
14772 ?        Sl     0:00  \_ unicorn_rails worker[1] -D -c /home/git/gitlab/config/unicorn.rb -E production                                         
14792 ?        Sl     0:10 sidekiq 2.17.8 gitlab [0 of 25 busy]                                                                                                                                                                                                                      
[root@repos ~]#

**Comment by DuLerWeil** [comment]
[root@repos ~]# service gitlab_ci start
Starting both the GitLab CI Unicorn and Sidekiq.
The GitLab CI Unicorn web server with pid 14669 is running.
The GitLab CI Sidekiq job dispatcher with pid 14677 is running.
GitLab CI and all its components are up and running.
[root@repos ~]# ps afx|grep git
14726 ?        Ss     0:00  \_ postgres: git gitlab_ci_production [local] idle                 
14727 ?        Ss     0:00  \_ postgres: git gitlab_ci_production [local] idle                 
14729 pts/0    S+     0:00          \_ grep git
14669 ?        Sl     0:03 unicorn_rails master -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                               
14690 ?        Sl     0:00  \_ unicorn_rails worker[0] -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                            
14693 ?        Sl     0:00  \_ unicorn_rails worker[1] -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                            
14677 ?        Sl     0:03 sidekiq 2.17.0 gitlab-ci [0 of 25 busy]                                                                                                                                                   
[root@repos ~]# service gitlab start
Starting unicorn:                                          [  OK  ]
Starting sidekiq:                                          [  OK  ]
[root@repos ~]# ps afx|grep git
14726 ?        Ss     0:00  \_ postgres: git gitlab_ci_production [local] idle                 
14727 ?        Ss     0:00  \_ postgres: git gitlab_ci_production [local] idle                 
14805 ?        Ss     0:00  \_ postgres: git gitlabhq_production [local] idle                  
14836 pts/0    S+     0:00          \_ grep git
14669 ?        Sl     0:03 unicorn_rails master -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                               
14690 ?        Sl     0:00  \_ unicorn_rails worker[0] -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                            
14693 ?        Sl     0:00  \_ unicorn_rails worker[1] -D -c /home/git/gitlab-ci/config/unicorn.rb -E production                                            
14762 ?        Sl     0:10 unicorn_rails master -D -c /home/git/gitlab/config/unicorn.rb -E production                                            
14769 ?        Sl     0:00  \_ unicorn_rails worker[0] -D -c /home/git/gitlab/config/unicorn.rb -E production                                         
14772 ?        Sl     0:00  \_ unicorn_rails worker[1] -D -c /home/git/gitlab/config/unicorn.rb -E production                                         
14792 ?        Sl     0:10 sidekiq 2.17.8 gitlab [0 of 25 busy]                                                                                                                                                                                                                      
[root@repos ~]#

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
