### ISSUE TITLE
please split init.d script into two

### ISSUE THREAD

**Issue by klaernie** [gitlabhq/gitlabhq#7445]
Hi there,

I am using gitlab 7.1 (since 4.x times) with Phusion Passenger as backend instead of Unicorn. Unfortunately the init script does not allow disabling the unicorn component without complaining or mayor code rewrite.

As both components are started pretty much the same (with only some name changes between each of them) it should be pretty straight forward to split them in two. Alternatively /etc/default/gitlab should allow a safe way to disable unicorn.

BTW: Gitlab runs awesome under Passenger, it might be worth offering it as an official deployment option.

Thanks and kind regards,
Andre

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
