### ISSUE TITLE
Add "create merge request" button to older pushes in activity list

### ISSUE THREAD

**Issue by sewi-cpan** [gitlabhq/gitlabhq#7541]
The ability to create a new branch out of the latest push is a nice feature, but the button (or a link) should also show up on every "pushed to branch" activity list entry.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
