### ISSUE TITLE
upgrading from old 6.6.5 to latest 7.2

### ISSUE THREAD

**Issue by nidheeshdas** [gitlabhq/gitlabhq#7603]
I've an old installation of 6.6.5 using DigitalOcean's image using mysql. I want to upgrade to the newer 7.2. Is there any easier path, or do I need to create all new setup and migrate each repository ?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
