### ISSUE TITLE
v7.2 show the wrong ruby version in the admin page

### ISSUE THREAD

**Issue by Sispheor** [gitlabhq/gitlabhq#7604]
The gitlab admin page show Ruby version 2.1.1p76 but I installed 2.1.2.

The check command (sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production) give this output :
``` 
Ruby version >= 2.0.0 ? ... yes (2.1.2)
```
And the linux command "ruby -v" give that
```
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
```

Not a big deal but just to warn the dev team. Good job by the way for this program !

**Comment by Razer6** [comment]
I cannot reprodice this. This is maybe due to multiple installs of ruby. Report back if the error still exists.
