### ISSUE TITLE
Gravatar path is wrong

### ISSUE THREAD

**Issue by hugelgupf** [gitlabhq/gitlabhq#7650]
I followed the instructions in the config about setting a relative path. My relative path happens to be /git. 

The following is HTML I copied out of the Network Graph page with Google Chrome:
```
<image x="170" y="160" width="20" height="20" preserveAspectRatio="none" xlink:href="/githttps://secure.gravatar.com/avatar/XXXX" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></image>
```

I've removed the actual gravatar link for anonymity.

GitLab 7.2, PostgreSQL. Have run the whole assets:clean assets:precompile cache:clean deal, doesn't help.

**Comment by stanhu** [comment]
I believe this should be fixed in GItLab 8.0, so I'm closing this for now.
