### ISSUE TITLE
Wrong Hover Commit Time on Project Activity Page

### ISSUE THREAD

**Issue by rnveach** [gitlabhq/gitlabhq#7702]
When I hover over the text, "X hours ago" of a commit, I expect to see the actual time of the commit on the project activity page (Ex: http://host/gitlab/ssa/project). I also expect to see the same time when viewing the contents of the commit (Ex: http://host/gitlab/ssa/project/commit/commitid).

What I get is 2 different times on the different pages. Both say 8 hours ago, but one says 10pm (project activity) while the other says 6pm (commit contents). The 6pm one is correct.

I am on 7.1.1 but I have seen the same issue in 6.8.1.

![project activity](https://cloud.githubusercontent.com/assets/5427943/4174382/1cdc18d0-358a-11e4-9530-8dbda0c3dcaf.gif)
![commit details](https://cloud.githubusercontent.com/assets/5427943/4174383/20fecbd8-358a-11e4-8caf-75fd2bff00d4.gif)

System information
System:		Ubuntu 12.04
Current User:	git
Using RVM:	no
Ruby Version:	2.0.0p353
Gem Version:	2.0.14
Bundler Version:1.6.2
Rake Version:	10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:	7.1.1
Revision:	facfec4

GitLab Shell
Version:	1.9.6

**Comment by change2hao** [comment]
I came across the same question, I amend the ` #time_zone: 'UTC'` to  time_zone: 'Beijing` in gitlab.yml and restart gitlab, then I commit some message to gitlab,but the time is also slower 8 hours than current time. who can help me?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
