### ISSUE TITLE
Default labels for new projects

### ISSUE THREAD

**Issue by Eloo** [gitlabhq/gitlabhq#7718]
Hi folks,

i would like to have a feature or setting where i can specify some labels which are created by default for new projects.
I think this is not a big thing to implement and i hope some other guys support my feature request.
So what do you think? Is this possible?

Regards, Eloo

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
