### ISSUE TITLE
Cannot commit any files via web interface or merge any requests due to partial use of system Ruby - GitLab 7.2.1

### ISSUE THREAD

**Issue by sammcj** [gitlabhq/gitlabhq#7729]
Whenever editing files via the web interface and try to commit them, we are presented with the following error:

```"Your changes could not be committed. Maybe the file was changed by another process or there was nothing to commit?"```

Nothing shows up in the logs other than:
```==> production.log <==
Completed 200 OK in 142ms (Views: 21.2ms | ActiveRecord: 6.9ms)```

I saw issue #7647 but I do not think they are related.
It's almost as if the web interface is not saving / adding the file to be committed prior to running git commit.

This is also preventing any merge requests from working.

```
Debian 7.6 AMD64
GitLab 7.2.1
GitLab Shell 1.9.4
GitLab API v3
Ruby 2.1.2p95
Rails 4.1.1
```

Gitlab installed using https://github.com/sbadia/puppet-gitlab

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
