### ISSUE TITLE
decide on consistent button capitalization

### ISSUE THREAD

**Issue by bbodenmiller** [gitlabhq/gitlabhq#7789]
The following pages contain buttons that are all capitalized while other pages contain buttons where some words are not capitalized. Which is prefered?

https://github.com/gitlabhq/gitlabhq/blob/c5678d4ecb9e557c9e70ddddbef493470d2fc229/app/views/profiles/keys/index.html.haml#L4
https://github.com/gitlabhq/gitlabhq/blob/c5678d4ecb9e557c9e70ddddbef493470d2fc229/app/views/profiles/groups/index.html.haml#L7
https://github.com/gitlabhq/gitlabhq/blob/c5678d4ecb9e557c9e70ddddbef493470d2fc229/app/views/admin/hooks/index.html.haml#L21
https://github.com/gitlabhq/gitlabhq/blob/c5678d4ecb9e557c9e70ddddbef493470d2fc229/app/views/admin/groups/index.html.haml#L3
https://github.com/gitlabhq/gitlabhq/blob/c5678d4ecb9e557c9e70ddddbef493470d2fc229/app/views/admin/users/index.html.haml#L35
https://github.com/gitlabhq/gitlabhq/blob/c5678d4ecb9e557c9e70ddddbef493470d2fc229/app/views/admin/projects/index.html.haml#L68
https://github.com/gitlabhq/gitlabhq/blob/c5678d4ecb9e557c9e70ddddbef493470d2fc229/app/views/admin/dashboard/index.html.haml

/cc @dosire

**Comment by Razer6** [comment]
Closing for now.
