### ISSUE TITLE
7.3 Upgrade: Redis changes should be first

### ISSUE THREAD

**Issue by michelkaeser** [gitlabhq/gitlabhq#7825]
If the redis-server changes are not made before running the migration/cleanup tasks, the following error encounters:

```
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
rake aborted!
URI::InvalidURIError: bad URI(is not URI?): 
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/redis-store-1.1.4/lib/redis/store/factory.rb:63:in `extract_host_options_from_uri'
/home/git/gitlab/config/application.rb:87:in `<class:Application>'
/home/git/gitlab/config/application.rb:9:in `<module:Gitlab>'
/home/git/gitlab/config/application.rb:8:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
