### ISSUE TITLE
invoke merge request events when push new commit to MR

### ISSUE THREAD

**Issue by zlx** [gitlabhq/gitlabhq#7843]
Hi, guys

I want to check the code when create MR or push new commit to an exist MR.

I find a MR hook can notify me when new MR is created, but when push new commit to an exist MR, only invoke push events hook, so I cannot distinguish it with push normal commit. 

How can I get notified  only when push new commit to an exist MR? Maybe I missing somethings.

**Comment by mathstuf** [comment]
I haven't seen a way. This seems like it belongs with MR hooks (versus comments which is more arguably a separate hook).

**Comment by mathstuf** [comment]
Requested as a feature here: http://feedback.gitlab.com/forums/176466-general/suggestions/7197934-merge-request-event

**Comment by DavidBadura** [comment]
:+1: Github have for this a action with the name "synchronize"

**Comment by mathstuf** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/commit/a927bf56b16c10bafc5bd9a14d034d2898b45c8e or a927bf56b16c10bafc5bd9a14d034d2898b45c8e

**Comment by DavidBadura** [comment]
thank you!

http://feedback.gitlab.com/forums/176466-general/suggestions/7197934-merge-request-event should be closed :)

**Comment by mathstuf** [comment]
I can't close this issue (but I'll have to remember my login for the feedback site…).

**Comment by mathstuf** [comment]
@jvanbaarsen This can be closed too (fixed upstream).

**Comment by mathstuf** [comment]
Also, if you have powers on the feedback site, if the linked suggestion could be closed, that'd be great. I don't see a way to do so from my end?

**Comment by jvanbaarsen** [comment]
@mathstuf Thanks for letting us know :-)
