### ISSUE TITLE
Upgrade 7.3 - Redis in gitlab-shell/config.yml

### ISSUE THREAD

**Issue by Eloo** [gitlabhq/gitlabhq#7845]
Hi folks,
today I updated to the latest tag 7.3.1 an ran directly into an issue with the upgrade instructions.
The following line doens't change the redis config in the gitlab-shell config for my instance.

    sudo -u git -H sed -i 's|^  # socket.*|  socket: /var/run/redis/redis.sock|' /home/git/gitlab-shell/config.yml

And yes I changed the path to match to my system but I had to change the redis config manually.

Maybe change the instruction for this point to change it manually.

Regards, Eloo

**Comment by Razer6** [comment]
Closing as seems to be fixed
