### ISSUE TITLE
Notifications sent to a user no more part of a private repository/group

### ISSUE THREAD

**Issue by rtripault** [gitlabhq/gitlabhq#7867]
Not really a bug but rather some kind of "logic"...

* if the repository is **private**
* **and** if the user is no more member of the repository
* then the email notification (ie. comment in an issue) should not be sent to that user

Hope it makes sense

**Comment by wevtimoteo** [comment]
+1

User Dmitry (@message) in GitlabHQ is receiving notifications about our comments.
But we're just commenting about code not about an user (that is not part of our team):

![screen shot 2015-05-22 at 9 58 26 pm](https://cloud.githubusercontent.com/assets/645452/7781799/57986518-00ce-11e5-81bd-0ecd096c648f.png)

**Comment by stanhu** [comment]
You may want to upgrade to GitLab v7.11. I think this was fixed in d0b1993bf8.

**Comment by wevtimoteo** [comment]
This is happening in Gitlab.com, not a self-hosted. :(
