### ISSUE TITLE
6.0 -> 7.3  hooks symlinks are not created 

### ISSUE THREAD

**Issue by allan-simon** [gitlabhq/gitlabhq#7884]
When migrating from 6.0 to 7.3 , the new symlinks to  post-receive and pre-receive are not created in gitlab-satellites 

I've fixed this problem by doing this small shell script , so I dont know if its something missing in the documentation to migrate from 6.0 to 7.3 or a step that I've forgotten to do 
```
SHELL_HOOKS=/home/git/gitlab-shell/hooks
for GROUP  in /home/git/gitlab-satellites/* ;
      do  for PROJECT in $GROUP/* ;
              do ln -sf  $SHELL_HOOKS/post-receive  $PROJECT/.git/hooks/post-receive;
               ln -sf  $SHELL_HOOKS/pre-receive  /$PROJECT/.git/hooks/pre-receive
     done ;
done
```

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
