### ISSUE TITLE
502 bad gateway error from nginx when I compile gitlab 6.0.0

### ISSUE THREAD

**Issue by luke-nguyen** [gitlabhq/gitlabhq#7892]
I compiled gitlab 6.0.0 follow the instruction 
https://gitlab.com/gitlab-org/gitlab-ce/blob/v6.0.0/doc/install/installation.md

There is no instruction about setup mysql database in this manually so I decide use the instruction of gitlab 6.8.0
https://gitlab.com/gitlab-org/gitlab-ce/blob/v6.8.0/doc/install/database_mysql.md

This is a fresh install.

My setup information:

    System information
    System:		CentOS 6.5
    Current User:	git
    Using RVM:	no
    Ruby Version:	2.0.0p247
    Gem Version:	2.0.3
    Bundler Version:1.7.3
    Rake Version:	10.1.0
    
    GitLab information
    Version:	6.0.0
    Revision:	zzz
    Directory:	/home/git/gitlab
    DB Adapter:	mysql2
    URL:		http://xxx.xxx.xxx.xxx
    HTTP Clone URL:	http://xxx.xxx.xxx.xxx/some-project.git
    SSH Clone URL:	git@xxx.xxx.xxx.xxx:some-project.git
    Using LDAP:	no
    Using Omniauth:	no
    
    GitLab Shell
    Version:	1.7.0
    Repositories:	/home/git/repositories/
    Hooks:		/home/git/gitlab-shell/hooks/
    Git:		/usr/bin/git

Check result:

    Checking Environment ...
    
    Git configured for git user? ... yes
    Has python2? ... yes
    python2 is supported version? ... yes
    
    Checking Environment ... Finished
    
    Checking GitLab Shell ...
    
    GitLab Shell version >= 1.7.0 ? ... OK (1.7.0)
    Repo base directory exists? ... yes
    Repo base directory is a symlink? ... no
    Repo base owned by git:git? ... yes
    Repo base access is drwxrws---? ... yes
    post-receive hook up-to-date? ... yes
    post-receive hooks in repos are links: ... can't check, you have no projects
    
    Checking GitLab Shell ... Finished
    
    Checking Sidekiq ...
    
    Running? ... yes
    
    Checking Sidekiq ... Finished
    
    Checking GitLab ...
    
    Database config exists? ... yes
    Database is SQLite ... no
    All migrations up? ... yes
    GitLab config exists? ... yes
    GitLab config outdated? ... no
    Log directory writable? ... yes
    Tmp directory writable? ... yes
    Init script exists? ... yes
    Init script up-to-date? ... yes
    Projects have satellites? ... can't check, you have no projects
    Redis version >= 2.0.0? ... yes
    Your git bin path is "/usr/bin/git"
    Git version >= 1.7.10 ? ... yes (2.0.0)
    
    Checking GitLab ... Finished

There is some problems in setup progress. 

There is no gitlab.socket in /home/git/gitlab/tmp/sockets. 

When I try to start gitlab service. I just see "GitLab service started" but when I re-check status service I see "GitLab service is not running." I don't see any error in log files in /home/git/gitlab/log.

I find out many errors in /var/log/nginx/gitlab_error.log like that:

    [crit] 2402#0: *1 stat() "/home/git/gitlab/public/" failed (13: Permission denied), client: yyy.yyy.yyy.yyy, server: xxx.xxx.xxx.xxx, request: "GET / HTTP/1.1", host: "xxx.xxx.xxx.xxx"
    [crit] 2402#0: *1 stat() "/home/git/gitlab/public//index.html" failed (13: Permission denied), client: yyy.yyy.yyy.yyy, server: xxx.xxx.xxx.xxx, request: "GET / HTTP/1.1", host: "xxx.xxx.xxx.xxx"
    [crit] 2402#0: *1 stat() "/home/git/gitlab/public/.html" failed (13: Permission denied), client: yyy.yyy.yyy.yyy, server: xxx.xxx.xxx.xxx, request: "GET / HTTP/1.1", host: "xxx.xxx.xxx.xxx"
    [crit] 2402#0: *1 connect() to unix:/home/git/gitlab/tmp/sockets/gitlab.socket failed (13: Permission denied) while connecting to upstream, client: yyy.yyy.yyy.yyy, server: xxx.xxx.xxx.xxx, request: "GET / HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/", host: "xxx.xxx.xxx.xxx"
  
I also tried add nginx to git group by 

    usermod -aG git nginx

and do change other permission on /home/git

    chmod -R o+rx /home/git

It is no use. 

I think 502 gateway error because of there is no unix socket of gitlab but I am impossible to find out how to make it. I have no idea about the reason of permission denied error. I hope I provide enough information to troubleshoot. How can you help me ?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
