### ISSUE TITLE
wiki title cat not use chinese language

### ISSUE THREAD

**Issue by webluoye** [gitlabhq/gitlabhq#7893]
wiki title can not use chinese language 

choose markdown:
Encoding::CompatibilityError (incompatible character encodings: UTF-8 and ASCII-8BIT):
  app/models/project_wiki.rb:87:in `create_page'
  app/models/wiki_page.rb:179:in `save'
  app/models/wiki_page.rb:139:in `create'
  app/controllers/projects/wikis_controller.rb:57:in `create'

other:
NoMethodError (undefined method `escaped_url_path' for nil:NilClass):
  app/models/wiki_page.rb:172:in `set_attributes'
  app/models/wiki_page.rb:191:in `save'
  app/models/wiki_page.rb:139:in `create'
  app/controllers/projects/wikis_controller.rb:57:in `create'

**Comment by Razer6** [comment]
Duplicate of #3913
