### ISSUE TITLE
Run Spinach and RSpec separately in parallel on Semaphore

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#8000]
Before, if Spinach failed RSpec would also run since they were run in parallel.

Not both run in series, so:

- if Spinach fails (and if fails a lot because of random failures) we don't see the RSpec, so an unrelated failure on Spinach can hide real RSpec failures
- it takes twice as long

Can't we back to how it was before?

Now: https://semaphoreapp.com/gitlabhq/gitlabhq/branches/pull-request-7999/builds/1

Before: https://semaphoreapp.com/gitlabhq/gitlabhq/branches/pull-request-7782/builds/1

**Comment by Razer6** [comment]
It's pretty fast right now and tests are far more stable these days. Therefore closing.
