### ISSUE TITLE
Unable to change project visibility as admin if any restrictions are set in the config.

### ISSUE THREAD

**Issue by dreis2211** [gitlabhq/gitlabhq#8061]
Hey,

we experience the problem, that our admins can't change the visibility of projects anymore. We have restricted our users to only create internal projects. Admins should be still able to change those settings, though.

I think this was introduced with the following change 4967c087862e5c7c5009605000380d4451ce07ec

The validation on the database row shouldn't check against the config settings in my opinion. As the config setting states, the restricted_visibility_levels should only apply for non-admin users and therefore such a "low-level" check is not appropriate.

Cheers

**Comment by MappaM** [comment]
Same here. The doc says that admin users should be able to do it but even as root I can't.

**Comment by MappaM** [comment]
Just updated to last community version, bug is still there.

**Comment by dreis2211** [comment]
Any news on this!? It is rather inconvenient to change the project visibility in the database all the time.

**Comment by dreis2211** [comment]
Was fixed by 648f38cd98eed41ddf56613194f2d91c0e5b1fbb
