### ISSUE TITLE
Issues no longer being closed by commit after update to 7.3.2

### ISSUE THREAD

**Issue by LBHinchy** [gitlabhq/gitlabhq#8063]
We've been running GitLab 6.9 for months now. We updated to 7.3.2 to use the new label features, but now issues are no longer being closed by commits, even with simple commit messages like "closes #276".

**Comment by kh0r** [comment]
Not entirely sure, but: After upgrading to 7.6.2 I started the check command:
`sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production`. 
The output showed something about missing hooks and I ran the displayed command to generate them: `sudo -u git -H /home/git/gitlab-shell//bin/create-hooks`. 

-> It's working again

**Comment by mtlife** [comment]
Just upgraded to the omnibus 7.6.2 and it's still not working, mentioning is working if you edit the file ```/opt/gitlab/embedded/service/gitlab-rails/config/config.yml``` and change:

    issue_closing_pattern:

To:
    
    issue_closing_pattern: ([Cc]lose[sd]|[Ff]ixe[sd]) #(\d+)

But still no real closing of tickets via commit messages.

**Comment by kh0r** [comment]
Whats the output of `sudo gitlab-rake gitlab:check`?

**Comment by mtlife** [comment]
```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.4.0 ? ... OK (2.4.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ...
***CUT*** / ***CUT*** ... ok
***CUT*** / ***CUT*** ... repository is empty
***CUT*** / ***CUT*** ... repository is empty
***CUT*** / ***CUT*** ... repository is empty
***CUT*** / ***CUT*** ... ok
***CUT*** / ***CUT*** ... ok
***CUT*** / ***CUT*** ... ok
***CUT*** / ***CUT*** ... ok
Running /opt/gitlab/embedded/service/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
        /var/opt/gitlab/git-data/repositories: OK
        /var/opt/gitlab/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.2
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)
Server: ldapmain
      ***CUT***

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... skipped (omnibus-gitlab has no init script)
Init script up-to-date? ... skipped (omnibus-gitlab has no init script)
projects have namespace: ...
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
Projects have satellites? ...
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
***CUT*** / ***CUT*** ... yes
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.4)
Your git bin path is "/opt/gitlab/embedded/bin/git"
Git version >= 1.7.10 ? ... yes (2.0.5)

Checking GitLab ... Finished

**Comment by kh0r** [comment]
Looks ok. I had a long list of missing hooks per repo before this output.
Sorry, no clue.

**Comment by mtlife** [comment]
It looks to me as if it's a omnibus specific bug, can you confirm that you are NOT using the omnibus install?

**Comment by josejulio** [comment]
It happens to me and i'm using tye omnibus install, here is the output of ```sudo gitlab-rake gitlab:check```

```
Checking Environment ...

Git configured for git user? ... no
  Try fixing it:
  sudo -u git -H "/opt/gitlab/embedded/bin/git" config --global user.name  "GitLab"
  sudo -u git -H "/opt/gitlab/embedded/bin/git" config --global user.email "proyectos@aluxoft.com"
  sudo -u git -H "/opt/gitlab/embedded/bin/git" config --global core.autocrlf "input"
  For more information see:
  doc/install/installation.md in section "GitLab"
  Please fix the error above and rerun the checks.

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.2.0 ? ... OK (2.2.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
xxxx / zzzz-wwww ... ok
xxxx / xxx xxxx ... ok
yyyy / xxxx ... ok
yyyy / zzzz ... ok
Running /opt/gitlab/embedded/service/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/var/opt/gitlab/git-data/repositories: OK
	/var/opt/gitlab/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.2
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... skipped (omnibus-gitlab has no init script)
Init script up-to-date? ... skipped (omnibus-gitlab has no init script)
projects have namespace: ... 
xxxx / xxx... yes
xxxx / xxxx - yyyy ... yes
Projects have satellites? ... 
xxxx / xxx... yes
xxxx / xxxx - yyyy ... yes
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.4)
Your git bin path is "/opt/gitlab/embedded/bin/git"
Git version >= 1.7.10 ? ... yes (2.0.0)

Checking GitLab ... Finished
```

**Comment by kh0r** [comment]
> It looks to me as if it's a omnibus specific bug, can you confirm that you are NOT using the omnibus install?

No, I have a migrated 6.x installation without omnibus. Had the issue after upgrading to 7.0.
After creating the hooks it works like a charm.

**Comment by hack3p3t3r** [comment]
Same here, using scince gitlab v6.9, upgraded manually (not omnibus) to 7.7.1. 
gitlab-rake gitlab:check seems to be ok:

Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.4.1 ? ... OK (2.4.1)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ....
[...]
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:.
    /home/git/repositories: OK
    /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.4.14
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ....
[...]
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.2)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.10)

Checking GitLab ... Finished

**Comment by Trefex** [comment]
I also have this problem.

I'm on 7.7.2 using omnibus package

**Comment by Gnaarhub** [comment]
After having this issue almost after every upgrade from 7.4 onwards, I just noticed this in my sidekick log:
WARN: {
	...
	"args"=>[63, {
		...
		"commits"=>[{
			...
			"message"=>"Fixes #164\n", 
			...
		}], 
		"total_commits_count"=>1
	}], 
	"error_message"=>"Access denied to room `<room name>'", 
	"error_class"=>"HipChat::Unauthorized", 
	"failed_at"=>1426779531.3650763, 
	"retry_count"=>4, 
	"retried_at"=>1426779854.0832167
}

Could HipChat fail the script responsible for auto closing issues? Can I call the script to auto close issues manually?

**Comment by mouradsm** [comment]
Same Problem:

Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.5.4 ? ... OK (2.5.4)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
code-avengers / PrimeFaces-Skeleton ... ok
code-avengers / sarh-api ... ok
code-avengers / AplicacaoBaseZF ... ok
code-avengers / Tico-Tico ... ok
code-avengers / sigpes-dominio ... ok
code-avengers / ArquivoVerificadorDePermissoes ... ok
code-avengers / Relatorios ... ok
Diego Moura / api ... ok
code-avengers / Movimentacao ... ok
code-avengers / Reengajamento ... ok
code-avengers / Boletim ... ok
Running /opt/gitlab/embedded/service/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/var/opt/gitlab/git-data/repositories: OK
	/var/opt/gitlab/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.2
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... skipped (omnibus-gitlab has no init script)
Init script up-to-date? ... skipped (omnibus-gitlab has no init script)
projects have namespace: ... 
code-avengers / PrimeFaces-Skeleton ... yes
code-avengers / sarh-api ... yes
code-avengers / AplicacaoBaseZF ... yes
code-avengers / Tico-Tico ... yes
code-avengers / sigpes-dominio ... yes
code-avengers / ArquivoVerificadorDePermissoes ... yes
code-avengers / Relatorios ... yes
Diego Moura / api ... yes
code-avengers / Movimentacao ... yes
code-avengers / Reengajamento ... yes
code-avengers / Boletim ... yes
Projects have satellites? ... 
code-avengers / PrimeFaces-Skeleton ... yes
code-avengers / sarh-api ... yes
code-avengers / AplicacaoBaseZF ... yes
code-avengers / Tico-Tico ... yes
code-avengers / sigpes-dominio ... yes
code-avengers / ArquivoVerificadorDePermissoes ... yes
code-avengers / Relatorios ... yes
Diego Moura / api ... yes
code-avengers / Movimentacao ... yes
code-avengers / Reengajamento ... yes
code-avengers / Boletim ... yes
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.5)
Your git bin path is "/opt/gitlab/embedded/bin/git"
Git version >= 1.7.10 ? ... yes (2.0.5)

Checking GitLab ... Finished

**Comment by rumpelsepp** [comment]
I assume all of you have merged these commits into the master branch? Issue don't get closed when you push to another branch instead of the master branch.

**Comment by Gnaarhub** [comment]
I just retried on a new Project.
*Gitlab 7.9 Ubuntu 14.04
*Hipchat deactivated this time
*Created issue. Issue is listed as number 2
*pushed commit "Closes 2" to master.
*config/gitlab.yml contains `issue_closing_pattern: '([Cc]lose[sd]|[Ff]ixe[sd]) #(\d+)'`
*Commit gets mentioned in the issue but issue is still open

Nothing in the logs. (gitlab/log directory. nothing unusal at least)
:/

**Comment by mtlife** [comment]
I solved it for me, steps to fix it found [here](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/394).

**Comment by Razer6** [comment]
Seems to be solved. Let's colse this here
