### ISSUE TITLE
gitlab Access denied. fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by hzy00** [gitlabhq/gitlabhq#8106]
I'm using gitlab 6.7. There is a problem confused me:
  when i use http path, i can do any git operations using username and password.
  when i use ssh path, yeah, i can clone, pull, except push. It reports "Access denied. fatal: Could not read from remote repository." when i push. 
Anybody can help me?

**Comment by stanleylst** [comment]
博文一看就知道博主是有很多实战经验的资深专家了，看到友链不多， http://www.178linux.com 希望和博主互做友链,感兴趣可以联系站点管理员

**Comment by chenwdong** [comment]
后来呢？？？怎么结局的大侠
