### ISSUE TITLE
"Reset password token has expired" on user activation within hours

### ISSUE THREAD

**Issue by FunkMonkey** [gitlabhq/gitlabhq#8108]
Lately (I guess since we updated to  7.2.1) new users often can not activate their account, given the following message:
"Reset password token has expired, please request a new one".

This happens within hours of user creation. I tried it myself with another email-address, but "unfortunately" it worked seamlessly for me. 

I keep investigating...

**Comment by JoKeyser** [comment]
A workaround for users is to click on *forgot password?*, receive the reset-email and then just set their first password that way.

**Comment by luffyke** [comment]
our issue is someone missed to reset his first password and the link was expired later, 
worked by @JoKeyser 's method, but i think that it is necessary to add a 'resend' button in the admin area.

**Comment by vialcollet** [comment]
+1 on adding a reset button

**Comment by rmoreas** [comment]
+1 for resend button

**Comment by samyscoub** [comment]
+1 for resend or reset button

**Comment by Razer6** [comment]
Closing this as default is now 2 days. For resend button refer to http://feedback.gitlab.com

**Comment by zwidny** [comment]
+ 1 for resend or reset button
