### ISSUE TITLE
Web UI :: Cannot commit any files / "nothing to commit"

### ISSUE THREAD

**Issue by AiliDong** [gitlabhq/gitlabhq#8151]
Whenever using web ui to edit files, the following error appears:

"Your changes could not be committed. Maybe the file was changed by another process or there was nothing to commit?"

1) at first thought that it was due to issues with markdown.js, similar to https://github.com/gitlabhq/gitlabhq/pull/7530
Solved markdown.js by installing https://github.com/gitlabhq/gitlabhq/issues/7513, but the main issue with commitments was still presented 

2) in log/githost.log found following error

To /path_to_git_repository/name.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to '/path_to_git_repository/name.git'

seems to be somehow similar to:
https://github.com/gitlabhq/gitlabhq/issues/8045

tried to reinstall bundler as well as https://gitlab.com/cirosantilli/gitlab-shell/commit/660f1113775cd4e797eb4d31ff51eaec6ec2fa66
None of the above helped and from here not exactly sure which way need to proceed with the issue

Other related issues: https://github.com/gitlabhq/gitlabhq/issues/7729
https://gitlab.com/gitlab-org/gitlab-development-kit/issues/15

Ruby configs:

[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.

System information
System:		Ubuntu 14.04
Current User:	git
Using RVM:	no
Ruby Version:	2.1.2p95
Gem Version:	2.2.2
Bundler Version:1.7.4
Rake Version:	10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:	7.3.2
Revision:	f092e53
Directory:	/home/git/gitlab
DB Adapter:	mysql2
URL:		[######]
HTTP Clone URL:	[#####]/some-project.git
SSH Clone URL:	git@[####]:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.0.1
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git

other specs:
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.0.1 ? ... OK (2.0.1)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
1/1 ... ok
3/2 ... ok
2/3 ... ok
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/home/git/repositories/: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.4
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 
1/1 ... yes
3/2 ... yes
2/3 ... yes
Projects have satellites? ... 
1/1 ... yes
3/2 ... yes
2/3 ... yes
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.2)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.1)

Checking GitLab ... Finished
----------------------------
Other than this, everything else seems to work fine

Let me know if any other log files required to be posted

**Comment by Razer6** [comment]
Closing as a duplicate.
