### ISSUE TITLE
404 Error when creating Wiki page with spaces

### ISSUE THREAD

**Issue by demisx** [gitlabhq/gitlabhq#8166]
I know the hint says _don't use spaces_ when creating a new Wiki page, but if I forget about it and do use spaces, it gives me a 404 error page after clicking on "New page" button. A better UX approach would be to either allow spaces and then replace them with hyphens upon submission or show a validation error if spaces are present. A user should never get to the 404 page.

**Comment by demisx** [comment]
+1 Still happening in the latest 7.10 version. Need just basic form validation for now. Long term, we should be able to create pages with any name, of course.

**Comment by demisx** [comment]
This is still happening in 7.11. I've used `generate csr` as page slug.

**Comment by Razer6** [comment]
This will be available with 7.12
