### ISSUE TITLE
404 err when browsing files in an empty repo containing empty commits

### ISSUE THREAD

**Issue by CromFr** [gitlabhq/gitlabhq#8204]
When you have a repository with no files, and that contains some empty commits, trying to open the "files" tab leads to a 404 error.

Repository: https://git.thibautcharles.net/tcharl/test
404 error: https://git.thibautcharles.net/tcharl/test/tree/master

**Comment by bbodenmiller** [comment]
Also reported this at https://gitlab.com/gitlab-org/gitlab-ce/issues/1387.

**Comment by Razer6** [comment]
Closing this here. Thanks @bbodenmiller
