### ISSUE TITLE
sudo -u git -H bundle exec rake gitlab:setup RAILS_ENV=production error with rake-10.1.0

### ISSUE THREAD

**Issue by TheAcastus** [gitlabhq/gitlabhq#8255]
Following command not works:

sudo -u git -H bundle exec rake gitlab:setup RAILS_ENV=production

Putty shows me this error:
Could not find rake-10.1.0 in any of the sources
Run `bundle install` to install missing gems.

I know what does it mean, but I don't know how to fix it. Can you tell me how to fix it please?

Problem solved by google :)

**Comment by tonyzonghui** [comment]
how do you solve the problem?

**Comment by TheAcastus** [comment]
Hello, I did it before long time and I dont remember it, but it was something on Stackoverflow.com I think...

But if you are installing gitlab, folow instructions in this tutorial: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md


And I had no problem with installation :)
