### ISSUE TITLE
Sidekiq crashes with a segmentation fault under certain conditions

### ISSUE THREAD

**Issue by alitheg** [gitlabhq/gitlabhq#8262]
We're seeing pretty frequent crashes of Sidekiq, necessitating a restart of the service. We're not sure what the exact conditions are but it seems to be to do with a particular repository (the last job message in the Sidekiq log always lists the same repository as its target). It looks *very* like this issue:

https://github.com/libgit2/rugged/issues/384

Which makes me think that we've introduced a condition in our repository which trips up the version of rugged which was upgraded to in 7.2.

We're using 7.4.3.

**Comment by aiionx** [comment]
I guess this is the stacktrace you see:
https://github.com/libgit2/libgit2/issues/2857

I was seeing sidekiq crashing with segmentation fault

but this fixes it:
https://github.com/libgit2/rugged/pull/457/files

Until it is merged and have that ref at gitlab_git (which depends on rugged) I believe you will have to patch manually as I did.

**Comment by Razer6** [comment]
Closing because we use rugged 0.22.2 now
