### ISSUE TITLE
Markdown inside link like code or emphasis gets escaped instead of rendered

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#8263]
Input:

```
[`d`](d)
[*d*](d)
```

Output: `<code>d<code>` and `<em>d</em>` (HTML escaped)

The same problem has already been solved for images: <https://github.com/gitlabhq/gitlabhq/issues/2701>

Live: https://gitlab.com/cirosantilli/test/blob/f4fc9210be8def4e4595232a9da47e7ec6e8fe1c/markdown.md#markup-inside-link

GitHub does it properly: https://github.com/cirosantilli/test/blob/f4fc9210be8def4e4595232a9da47e7ec6e8fe1c/markdown.md#markup-inside-link

**Comment by Razer6** [comment]
Fixed in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/619 Will be available in 7.11.
