### ISSUE TITLE
error: Untracked working tree file '.hound.yml' would be overwritten by merge. when running 7.0 upgrade script

### ISSUE THREAD

**Issue by bjovas** [gitlabhq/gitlabhq#8282]
I have been following the upgrade path all the way up to 6.4, then running scripts/upgrade.rb

Then used manual upgrade to 7.0

Now that i am trying to use the new bin/upgrade.rb I am running into problems:

root@gitlab git/gitlab# ruby bin/upgrade.rb
GitLab 7 upgrade tool
Your version is 7.0.0
Latest available version for GitLab 7 is 7.4.3
Newer GitLab version is available
Do you want to upgrade (yes/no)? yes
Stash changed files
 -> git stash
No local changes to save
 -> OK
Get latest code
 -> git fetch
 -> OK
Switch to new version
 -> git checkout v7.4.3
error: Untracked working tree file '.hound.yml' would be overwritten by merge.
 -> FAILED
Failed to upgrade. Try to repeat task or proceed with upgrade manually

Using Turnkey Linux Gitlab 12.1

System information
System:         Debian 6.0.7
Current User:   git
Using RVM:      no
Ruby Version:   2.1.2p95
Gem Version:    2.2.2
Bundler Version:1.7.4
Rake Version:   10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:        7.0.0
Revision:       de9bf7d
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            ***
HTTP Clone URL: ****
SSH Clone URL:  *****
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.9.6
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git

**Comment by Razer6** [comment]
Yes. Thats possible.
