### ISSUE TITLE
During restore of gitlab-7.4.3-omnibus: "ERROR:  must be owner of extension plpgsql"

### ISSUE THREAD

**Issue by dandric-activevideo** [gitlabhq/gitlabhq#8292]
I'm attempting to migrate an Omnibus GitLab 7.4.3 hosted on CentOS6 to another CentOS6 machine, using backup and restore.  The source instance runs "gitlab-rake gitlab:backup:create" every night, and I copied the resulting tarball to the freshly installed destination instance, where I then tried:
```
gitlab-rake gitlab:backup:restore BACKUP=1415689405
```
This results in one error, and several warnings.  The error comes right at the start:
```
Unpacking backup ... done
Restoring database ...
Restoring PostgreSQL database gitlabhq_production ... SET
SET
SET
SET
SET
CREATE EXTENSION
psql:/var/opt/gitlab/backups/db/database.sql:22: ERROR:  must be owner of extension plpgsql
```
but this does not seem immediately fatal, it continues with printing database statements (why are these echo'd anyway?):
```
SET
CREATE SEQUENCE
ALTER TABLE
[...]
```
This goes on for some time, and after a while it prints these warnings:
```
[...]
ALTER TABLE
psql:/var/opt/gitlab/backups/db/database.sql:15761: WARNING:  no privileges could be revoked for "public"
REVOKE
psql:/var/opt/gitlab/backups/db/database.sql:15762: WARNING:  no privileges could be revoked for "public"
REVOKE
psql:/var/opt/gitlab/backups/db/database.sql:15763: WARNING:  no privileges were granted for "public"
GRANT
psql:/var/opt/gitlab/backups/db/database.sql:15764: WARNING:  no privileges were granted for "public"
GRANT
[DONE]
```
I saw something that looked like the "must be owner" error in #6067, but that issue appears to have been closed due to a timeout, without a real resolution.

Any idea whether the restored instance will now have a correct database?  The line 22 about which the error is reported just has:
```
COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
```
while lines 15761 through 15764 are:
```
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM "gitlab-psql";
GRANT ALL ON SCHEMA public TO "gitlab-psql";
GRANT ALL ON SCHEMA public TO PUBLIC;
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by duyunw** [comment]
==&gt; /var/log/gitlab/postgresql/current &lt;==
2017-12-04_03:18:52.16913 ERROR:  must be owner of schema public
2017-12-04_03:18:52.16917 STATEMENT:  COMMENT ON SCHEMA public IS 'standard public schema';
2017-12-04_03:18:52.18139 ERROR:  must be owner of extension plpgsql
2017-12-04_03:18:52.18143 STATEMENT:  COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
2017-12-04_03:18:52.18246 ERROR:  must be owner of extension pg_trgm
2017-12-04_03:18:52.18250 STATEMENT:  COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';
2017-12-04_03:18:59.02954 WARNING:  no privileges could be revoked for \"public\"
2017-12-04_03:18:59.04186 WARNING:  no privileges could be revoked for \"public\"
2017-12-04_03:18:59.04238 WARNING:  no privileges were granted for \"public\"
2017-12-04_03:18:59.04293 WARNING:  no privileges were granted for \"public\"
Also this error, now I cannot access the project, the web page report error 500, GitLab Community Edition 8.9.2 bf922fb
The company's old version does not upgrade, make a backup, prepare to upgrade the latest edition, report this mistake, the heart tired
