### ISSUE TITLE
wrong information in mentioned issue for cross project mentioning if project name contains underscore

### ISSUE THREAD

**Issue by koshuang** [gitlabhq/gitlabhq#8298]
I have two projects in same group, which are kos/admin-tool and kos/d2d_backend. When I mention *related to kos/admin-tool#105* in issue 195 of d2d_backend, 

The comment in issue 105 of admin-tool is *mentioned in issue kos/d2dbackend#195_*. It should be *kos/d2d_backend#195*.

**Comment by floatingLomas** [comment]
FYI: I'm getting the same thing here:

What should be:

> mentioned in issue [namespace/underscore_separated#60]() *(pointing to the issue in underscore_separated)*

Is coming up as:

> mentioned in issue namespace/underscoreseparated[#60_]() *(pointing to the issue in the current project by that number)*

**Comment by stanhu** [comment]
This was fixed in fad71576f and released in GitLab v7.10.

**Comment by floatingLomas** [comment]
My bad.  We're running 7.4.something.  Cheers!
