### ISSUE TITLE
Hide emails

### ISSUE THREAD

**Issue by HIGHWAY99** [gitlabhq/gitlabhq#8306]
looking for a way to hide email address when hovering over usernames in such places as dev who last commt'ed, even if there's only a title and no sub-message.

**Comment by scap1784** [comment]
I need this as well.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
