### ISSUE TITLE
Duplicate username already taken error messages

### ISSUE THREAD

**Issue by bbodenmiller** [gitlabhq/gitlabhq#8323]
When I try to add a user in the admin dashboard, and the username is already taken, I see two similar notices:

* `Username has already been taken`
* `Username already exists`

![image](https://cloud.githubusercontent.com/assets/1192780/5061166/c6da282a-6d3b-11e4-9bbd-bb4b3e762ee6.png)

### Steps to reproduce ###

Go to admin
Create user with username: john.doe
Try to create another user with username: john.doe

Similar issue as duplicate email message: https://github.com/gitlabhq/gitlabhq/issues/6123

**Comment by Razer6** [comment]
Fixed by https://github.com/gitlabhq/gitlabhq/commit/73918efb273b83b59f421557db2134973bb8eb53
