### ISSUE TITLE
Trying to delete a branch called 'origin/UserFirstTime'. Not working.

### ISSUE THREAD

**Issue by SteveyPugs** [gitlabhq/gitlabhq#8334]
The branch delete looks like it succeeds from the UI but it doesn't. In my error logs I get this:

```BASH
error: branch 'origin/UserFirstTime' not found.
```

**Comment by SteveyPugs** [comment]
Btw I figured out how to fix this. Closing

**Comment by Soullivaneuh** [comment]
@SteveyPugs I possibly have the same kind of issue, could you please explain your fix? Thanks! :+1:
