### ISSUE TITLE
Error 500 on json files from network and graphs tab

### ISSUE THREAD

**Issue by raphaelheitor** [gitlabhq/gitlabhq#8337]
I created a project in gitlab and pointed to an existing repository. Imported without problems, but when viewing network and graphs tabs nothing happens. Inspecting the firebug I could see that had occurred in the json file the error 500.

I tried to make some changes suggested in the issues from github project in model file commit.rb Without success!

My production.log follows:

Graphs page log:

>Started GET "/desenv/sistema-concessao-diarias/graphs/master" for 127.0.0.1 at 2014-11-17 15:37:23 -0400
>Processing by Projects::GraphsController#show as HTML
  Parameters: {"project_id"=>"desenv/sistema-concessao-diarias", "id"=>"master"}
Completed 200 OK in 174ms (Views: 147.7ms | ActiveRecord: 7.6ms)
Started GET "/desenv/sistema-concessao-diarias/graphs/master" for 127.0.0.1 at 2014-11-17 15:37:23 -0400
Processing by Projects::GraphsController#show as JSON
  Parameters: {"project_id"=>"desenv/sistema-concessao-diarias", "id"=>"master"}
Completed 500 Internal Server Error in 145ms

>JSON::GeneratorError (source sequence is illegal/malformed utf-8):
  app/controllers/projects/graphs_controller.rb:38:in `fetch_graph'
  app/controllers/projects/graphs_controller.rb:11:in `block (2 levels) in show'
  app/controllers/projects/graphs_controller.rb:8:in `show'

Network page log:

>Started GET "/desenv/sistema-concessao-diarias/refs/switch?utf8=%E2%9C%93&ref=master&destination=graph" for 127.0.0.1 at 2014-11-17 15:36:58 -0400
>Processing by Projects::RefsController#switch as HTML
  Parameters: {"utf8"=>"✓", "ref"=>"master", "destination"=>"graph", "project_id"=>"desenv/sistema-concessao-diarias"}
Redirected to http://gitlab.tce.ro.gov.br/desenv/sistema-concessao-diarias/network/master
Completed 302 Found in 24ms (ActiveRecord: 4.3ms)
Started GET "/desenv/sistema-concessao-diarias/network/master" for 127.0.0.1 at 2014-11-17 15:36:59 -0400
Processing by Projects::NetworkController#show as HTML
  Parameters: {"project_id"=>"desenv/sistema-concessao-diarias", "id"=>"master"}
Completed 200 OK in 60ms (Views: 30.6ms | ActiveRecord: 5.5ms)
Started GET "/desenv/sistema-concessao-diarias/network/master.json" for 127.0.0.1 at 2014-11-17 15:37:08 -0400
Processing by Projects::NetworkController#show as JSON
  Parameters: {"project_id"=>"desenv/sistema-concessao-diarias", "id"=>"master"}
Completed 500 Internal Server Error in 1141ms

>ActionView::Template::Error (source sequence is illegal/malformed utf-8):
  app/views/projects/network/show.json.erb:22:in `_app_views_projects_network_show_json_erb__4512994486324073835_115527620'

**Comment by DouweM** [comment]
A fix to this issue has been merged and will be in version 7.9. Please reopen this issue if the problem persists after upgrading to 7.9.
