### ISSUE TITLE
Deploy source maps for minified JS files

### ISSUE THREAD

**Issue by djc** [gitlabhq/gitlabhq#8344]
Here's an introduction on source maps:

http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

I recently had a case where a GitLab tab was causing very bad hangs in the Firefox UI. This has since been fixed in Firefox (see https://bugzilla.mozilla.org/show_bug.cgi?id=868139, apparently caused my having many timeouts set), but it was hard to see where in the GitLab code the bug was due to minified JavaScript. It would be nice to package source maps. I tried to look at the code, but I couldn't find out where the coffeescript is turned into JavaScript and minified. I did find this project:

https://github.com/markbates/coffee-rails-source-maps

Which might help with getting this done.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
