### ISSUE TITLE
No documentation of which paths are reserved

### ISSUE THREAD

**Issue by jacob-carlborg** [gitlabhq/gitlabhq#8352]
I tried to create a new project called "admin" using the API. This didn't work that well since apparently it's a reserved path. The response I got back was a 404, which is a bit strange. I wasted at least half an hour because of this response.

I see two issues here:

* No documentation of the reserved paths
* A 404 is returned instead of something like 400 (bad request)

BTW, is there a reason for this limitation? I can understand that you can't create a group that's called "admin", but projects? Aren't all projects namespaced either in a group or a user's namespace?

**Comment by Razer6** [comment]
Blacklist validation for project names is gone
