### ISSUE TITLE
Create new label/milestone give 404 on permission denied

### ISSUE THREAD

**Issue by robodude666** [gitlabhq/gitlabhq#8353]
When a user who doesn't have permission to create a new label or milestone clicks on the "Create new miilestone" or "Create new label" link next to the milestone/labels input fields on the "New Issue" or "Edit Issue" page, they are redirected to a 404 page instead of a "permission denied" page.

The "new" label/milestone pages should show a meaningful permission denied error when accessed without enough permissions, instead of a 404 to remove confusion (and prevent admins from being contacted unnecessarily that the website is broken.)

Preferably, also, if a user doesn't have permissions to create a new label or milestone, the links shouldn't even show up at all.

**Comment by tataranovich** [comment]
Same issue for me. I agree with @robodude666 - GitLab should not expose label creation if no permission available.

**Comment by tataranovich** [comment]
Checked on 7.11.4 - still gives 404 error.

**Comment by stanhu** [comment]
v7.11.4 hides the label and milestone creation if the user doesn't have permission. From `projects/_issuable_form.html.haml`:

```ruby
    - if can? current_user, :admin_label, issuable.project
      = link_to 'Create new label', new_namespace_project_label_path(issuable.project.namespace, issuable.project), target: :blank
```

What permissions does the user in question have (e.g. guest, reporter, etc.)? I believe the developer role has the ability to administer labels. Can you attach a screenshot where you are seeing the label/milestone link?

**Comment by tataranovich** [comment]
I added test user 'testuser' with role 'Reporter' to project. If I view login using 'testuser' I see labels menu and possibility to generate default set of labels. If I click on 'generate' link I get 404 error.

# Gitlab version 7.11.4
![gitlab_version](https://cloud.githubusercontent.com/assets/1963204/7915523/bf0491da-0886-11e5-9a9b-bf6c2c90ffef.png)

# Project members (owner view)
![gitlab_project_members](https://cloud.githubusercontent.com/assets/1963204/7915529/c6ac667e-0886-11e5-82a5-c9aa25ce4fc6.png)

# Project (testuser view)
![testuser_label_creation](https://cloud.githubusercontent.com/assets/1963204/7915532/cc2d4c12-0886-11e5-8681-eca3d09dc240.png)

**Comment by stanhu** [comment]
Thanks for the screenshots! This is very helpful. Fix has been submitted here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/752
