### ISSUE TITLE
No new Label/Milestone link on Merge Requests

### ISSUE THREAD

**Issue by robodude666** [gitlabhq/gitlabhq#8354]
Links for creating a new label or new milestone were added to the Issues new/edit pages recently, but none were added to the New Merge Requests and Edit Merge Requests pages.

Like mentioned in #8353, if a user doesn't have permissions for creating a new label or new milestone, the link shouldn't show.

**Comment by stanhu** [comment]
I think this is working now in v7.11:

![image](https://cloud.githubusercontent.com/assets/963826/7915069/f46724ac-082f-11e5-883b-f185c9037ec9.png)

/cc: @Razer6
