### ISSUE TITLE
Avatar not handled properly using relative path in 7.5.0.rc1 

### ISSUE THREAD

**Issue by darkxinyu** [gitlabhq/gitlabhq#8366]
I'm using relative path to serve gitlab and 7.4.2 worked well, after upgrading to 7.5.0.rc1, all my uploaded avatar has the following urls:
http://domain.com/gitlab//gitlab/uploads/user/avatar/xx/xxxxxx.jpg

**Comment by yoonyoungkim** [comment]
I want to know this problem is closing in 7.6.

**Comment by Razer6** [comment]
Clsong this as root cause has been reverted

**Comment by pierrebeitz** [comment]
please reopen, as it still does not work as of 7.10.2
