### ISSUE TITLE
Default target branch when forked should'nt be an archived repo

### ISSUE THREAD

**Issue by blackeyedboy** [gitlabhq/gitlabhq#8372]
GitLab 7.5.1 36679b5 tests full green.

Steps to reproduce :
* create a repository
* fork it
* archive it (the original one, not the fork)
* do something on the new fork
* open a MR
* BRRRRR : the default target branch points to an archived repo which cannot be committed !

See https://github.com/gitlabhq/gitlabhq/pull/5719 referenced in this suggestion http://feedback.gitlab.com/forums/176466-general/suggestions/5518180-smarter-merge-request-target-repo-and-branch-form

I obviously can understand and admit that, when you fork a repo, "most of the time and for most users" they just fork because they only have read access on the original repo and will open a MR from the fork to the original. So the new MR should by default open from fork to forked, if the assertion ("most of the time and for most users") is really true.

But it is not for us ! We don't care about being "minority" and having to adapt. But having to remember changing manually target branch each time we open a MR on a fork introduces frequent "ooops" (as usual when manual...).

In my opinion, to be enjoyable by everybody (most users and minority), this should be configurable on project settings, just a new line "this project has been forked, choose your default target branch :" and a selector like the "Default branch" one. I'm pleased to comment the existing suggestion right now for this parameter, see http://feedback.gitlab.com/forums/176466-general/suggestions/5890100-ability-to-select-the-default-merge-target-for-pro

Now, here is the issue. To avoid default target branch to the original forked repository, we tried to Archive the original repo. As a read-only, it can't be committed, so we imagined it will disappear from the target branch, but it does not !

**Comment by Akendo** [comment]
It's a problem for me as well.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
