### ISSUE TITLE
Provide meaningful release notes with releases

### ISSUE THREAD

**Issue by aheusingfeld** [gitlabhq/gitlabhq#8382]
Currently there are [120 releases](https://github.com/gitlabhq/gitlabhq/releases) without further information on what has been fixed, added or removed. It'd be of great help for people wondering whether an upgrade is necessary if you could at least link to - or better include the information from - the current changelog e.g. https://gitlab.com/gitlab-org/gitlab-ce/blob/7-5-stable/CHANGELOG

**Comment by Razer6** [comment]
Let's close this issue, since it is not a primary issue of GitLab. Blog posts are fine. They desribe most relevant features, link to the changelog and have an upgrade barometer
