### ISSUE TITLE
Always busy

### ISSUE THREAD

**Issue by alexchernyy** [gitlabhq/gitlabhq#8398]
sidekiq 2.17.0 [25 of 25 busy]

My GitLab version: GitLab 7.4.3, commit https://gitlab.com/gitlab-org/gitlab-ce/commit/353a98757850a37118bc5ff0718d8050f934bf90 

Symptoms: Activities not updating in feed (there is no branch in feed if I pushed branch for example); I can not create merge requests because branch is not in source list but pushed on server.

It looks like issue with hooks or sidekiq socket update but gitlab/check command completes without errors and only sidekiq looks strange because it gets 25 of 25 after 'service gitlab reload' . I raised up number of sidekiq workers to 75. 75 of 75 is busy after one working day.

How to debug slow operations? How to determine what blocks background jobs?

**Comment by Razer6** [comment]
Fix shipped in 7.6
