### ISSUE TITLE
Pushing to new branch does not deliver commits via webhook

### ISSUE THREAD

**Issue by nils-werner** [gitlabhq/gitlabhq#8401]
Whenever I push to a new branch (creating it on GitLab), GitLab does not show the push but only the create:

 - Activity wall shows the created branch
 - Activity wall **does not show** the pushed commit
 - Webhook for push **does not** contain commits

Instead I expect it to do:

 - Activity wall shows the created branch
 - Activity wall **shows** the pushed commit
 - Webhook for push **does** contains commits

**Comment by bloerwald** [comment]
This is also the case for built-in services: The "Emails on push" service sends nothing for these pushes. The kind of annoying workaround we use is pushing the empty branch, then pushing the branch itself, resulting in one mail triggered by the second push.

**Comment by vlovich** [comment]
FWIW, in this scenario GitHub pushes a "head_commit" field that contains the commit information for the first one.  This should provide enough information even if imperfect (i.e. doesn't contain the set of changes since whatever branch was forked off which is typically difficult to determine)

**Comment by antaflos** [comment]
This is still a problem in Gitlab 7.13.1. No emails are sent when pushing a new branch with commits (i.e. `git push -u origin my-new-feature-branch`) even though "Emails on push" is enabled for the project in question.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
