### ISSUE TITLE
Encoding::CompatibilityError (incompatible character encodings: ASCII-8BIT and UTF-8) in 7.5

### ISSUE THREAD

**Issue by rujews** [gitlabhq/gitlabhq#8408]
## Encoding::CompatibilityError (incompatible character encodings: ASCII-8BIT and UTF-8):
app/views/projects/tree/show.html.haml:10:in `_app_views_projects_tree_show_html_haml__715013101__550539858'
app/controllers/projects/tree_controller.rb:13:in `show'

> there has chinese in file path

## How to solve?

**Comment by DouweM** [comment]
A fix to this issue has been merged and will be in version 7.9. Please reopen this issue if the problem persists after upgrading to 7.9.
