### ISSUE TITLE
500 Encoding error when searching using UTF-8 characters within a specific project

### ISSUE THREAD

**Issue by cosmix** [gitlabhq/gitlabhq#8459]
To reproduce (requires existing projects):

1. search for a UTF-8 character-containing string
2. Click on 'Project:Any', choose a project from the drop down list
3. Repeat search within project.

Actual Results:

500 Encoding Error.

Expected Results:

Search results for UTF-8 string.

**Comment by DouweM** [comment]
A fix to this issue has been merged and will be in version 7.9. Please reopen this issue if the problem persists after upgrading to 7.9.
