### ISSUE TITLE
dependency on broken timfel-krb5-auth-0.8

### ISSUE THREAD

**Issue by hasufell** [gitlabhq/gitlabhq#8478]
The last commit of the project is almost 5 years old.

Building fails, because the linker line is wrong (-lcom_err is missing).

Fixing it seems to be almost impossible, because I don't have much control about what the bundler does.

```
# gem install timfel-krb5-auth -v '0.8'
Fetching: timfel-krb5-auth-0.8.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing timfel-krb5-auth:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby20 extconf.rb
checking for main() in -lc... yes
checking for krb5_init_context() in -lkrb5... yes
creating Makefile

make "DESTDIR="
compiling ruby_krb5_auth.c
linking shared-object krb5_auth.so
ruby_krb5_auth.o: In function `Krb5_register_error':
ruby_krb5_auth.c:(.text+0x138): undefined reference to `error_message'
collect2: error: ld returned 1 exit status
Makefile:231: recipe for target 'krb5_auth.so' failed
make: *** [krb5_auth.so] Error 1


Gem files will remain installed in /home/jule/.gem/ruby/2.0.0/gems/timfel-krb5-auth-0.8 for inspection.
Results logged to /home/jule/.gem/ruby/2.0.0/gems/timfel-krb5-auth-0.8/ext/gem_make.out
```

**Comment by skv-headless** [comment]
https://github.com/gitlabhq/gitlabhq/commit/15303bbfd76ae91fcba6202c5449425cb3c99829
in this commit added this dependency, @vsizov is it necessary?

**Comment by stefri** [comment]
+1
I'm running on OmniOS (Illumos-Distribution). I know this is not officially supported but this Kerberos dependency forces me to stay on 7.5

**Comment by limansky** [comment]
I think this issue is related with this pull request. https://github.com/timfel/krb5-auth/pull/6 
Seems like the new gem (0.8.2) was pushed.

**Comment by limansky** [comment]
I've changed version in Gemfile.lock, and successfully installed Gitlab 7.7.1 on Gentoo:

```diff
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -552,7 +552,7 @@ GEM
     thread_safe (0.3.4)
     tilt (1.4.1)
     timers (1.1.0)
-    timfel-krb5-auth (0.8)
+    timfel-krb5-auth (0.8.2)
     tinder (1.9.3)
       eventmachine (~> 1.0)
       faraday (~> 0.8)
```

**Comment by jacobvosmaer** [comment]
:+1: for bumping the timfel-krb5-auth version

**Comment by dblessing** [comment]
Is someone planning to submit a PR with this bump? @limansky would you be willing?

**Comment by limansky** [comment]
Ok, I'll try to push it today.

**Comment by limansky** [comment]
@dblessing , should I push it for master or for 7-7-stable or both?

**Comment by limansky** [comment]
I submitted a pull request for master #8661. The build has failed, but I don't think it related to this patch.
