### ISSUE TITLE
Server doesn't reboot

### ISSUE THREAD

**Issue by alexbagirov** [gitlabhq/gitlabhq#8514]
Hello!

I have installed omnibus Gitlab on empty Ubuntu 14.04 VPS. When I use something like 'sudo reboot', my server switches off and after that stop replying. When network administrator connects to it via interface, it says about memory check. After pushing something like "skip" it loads and works. It does so every time I try to reboot the system. Have you ever met such problem? How can I avoid it?

**Comment by Razer6** [comment]
Please head over to the omnibus tracker for this question: https://gitlab.com/gitlab-org/omnibus-gitlab
