### ISSUE TITLE
This request can't be merged with GitLab - all of the time

### ISSUE THREAD

**Issue by jbrooksuk** [gitlabhq/gitlabhq#8523]
Since upgrading to 7.6 I'm no longer able to merge requests via the web interface - even if there are no conflicts.

I've ran both check commands and they don't report anything out of the ordinary.

**Comment by jbrooksuk** [comment]
@Razer6 any idea? We're currently unable to merge branches at work, so we're pushing to `master` which is awful.

**Comment by jbrooksuk** [comment]
I've updated the Git installation on the server, nadda.

**Comment by jbrooksuk** [comment]
Ok, it turns out someone had pushed the changes from the branch into `master`, but left the original PR open. 

However, I've pushed a test branch to the project and still cannot merge to that one place.

**Comment by jbrooksuk** [comment]
Also I've just ran `git gc` on the offending repository, but it's still not working.

**Comment by Razer6** [comment]
In your logs you have two errors. Which on is related to the merge issue? The first or the latter? Is it project related? Do merges work on a test repository?

**Comment by jbrooksuk** [comment]
Well, both really. Yeah, I'm able to merge other repos.

It could be that the repository is 1000MB+. Unfortunately this is from an old project where a lot of images are stored in the same directory.

**Comment by Razer6** [comment]
Can you try to increase the timeout in https://github.com/gitlabhq/gitlabhq/blob/master/config/gitlab.yml.example#L282

**Comment by jbrooksuk** [comment]
I've set it to 90 and it's still not going, even though it times out way before that. Yes, I restarted the `gitlab` service.

**Comment by jbrooksuk** [comment]
Still no luck and this is making it impossible to work on this one project. I've just [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) and it's now about 1.6GB - is GitLab unable to handle that?

**Comment by Plonk42** [comment]
We ran in this issue multiple times, when a big commit has been pushed.
Usually, running `sudo -u git git fetch` in the satellite repo on the GitLab server solves the issue,
because there will be no time-out from a shell.

**Comment by jbrooksuk** [comment]
Woohoo thanks @Plonk42 that's worked!

**Comment by thomaslevesque** [comment]
I have one project where I always get the "This request can't be merged with GitLab" message, even though the merge should be a fast-forward. I never see it on other projects.

**Comment by thomaslevesque** [comment]
@Plonk42 's workaround doesn't work for me

But anyway, the problem happens for all merges, not just for big ones

**Comment by LittleSakana** [comment]
1. go to gitlab server
2. delete satellites folder
3. do a new push 
4. soluted
