### ISSUE TITLE
LDAP Authentication failures in 7.6.2

### ISSUE THREAD

**Issue by jchodakowski** [gitlabhq/gitlabhq#8530]
I'm getting the following in the production.log when trying to authenticate against a known good LDAP source:

```
Started POST "/users/auth/ldapmain/callback" for 74.121.197.77 at 2014-12-29 10:07:56 -0500
Processing by OmniauthCallbacksController#ldapmain as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"eOYz1AijHR78B99qav9ICTqkIwOocT634ZjpH05Loh0=", "username"=>"jasonc", "password"=>"[FILTERED]"}
Completed 500 Internal Server Error in 13ms
Processing by OmniauthCallbacksController#failure as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"eOYz1AijHR78B99qav9ICTqkIwOocT634ZjpH05Loh0=", "username"=>"jasonc", "password"=>"[FILTERED]"}
Redirected to https://gitlab.declivis.com/users/sign_in
Completed 302 Found in 4ms (ActiveRecord: 0.0ms)
Started GET "/users/sign_in" for 74.121.197.77 at 2014-12-29 10:07:56 -0500
Processing by SessionsController#new as HTML
Completed 200 OK in 15ms (Views: 9.4ms | ActiveRecord: 0.0ms)
```
There are no other messages on the server side that indicate what the server error actually is. On the client side you see this:

```
Could not authorize you from Ldapmain because "Undefined method 'provider' for nil:nilclass".
```

The LDAP connectivity is good and tests properly:

```
bundle exec rake gitlab:ldap:check RAILS_ENV=production
Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)
Server: ldapmain
	DN: uid=jasonc,ou=users,dc=declivis,dc=com	 uid: jasonc
	DN: uid=jenkins,ou=users,dc=declivis,dc=com	 uid: jenkins

Checking LDAP ... Finished
```

Can provide configurations on request, but honestly I think the configuration works, something else is wonky... which I'm willing to admin could be missing from the LDAP schema but a better error message on the server side would help.

**Comment by narfbg** [comment]
After two days of debugging the same problem, it turned out that for some reason, some users lack records in the `identities` table ...

I would've digged into the original cause for that, but I don't know Ruby and I didn't want to experiment on production, so as a temporary solution I just did a few manual INSERTs.

The following will be helpful in identifying the users who lack such recods:

    SELECT users.id, users.username, identities.user_id FROM identities RIGHT JOIN users ON identities.user_id = users.id GROUP BY users.id, users.username, identities.user_id HAVING identities.user_id IS NULL

You can then just take another `identities` record as an example and adjust accordingly (for the `extern_uid` field, the rest is pretty straightforward).

**Comment by 123Haynes** [comment]
@narfbg How were those users created initially?

**Comment by narfbg** [comment]
@123Haynes Added manually through the administration settings.

**Comment by jchodakowski** [comment]
My users were created in LDAP, but I tested with every sort - they all seem to have this issue.

**Comment by jchodakowski** [comment]
Issue persists in 7.7.0

**Comment by bashou** [comment]
This happen when nothing exist in 'identities' table.
If you try with users who exist un LDAP but not in Gitlab, it will work and create automatically the good entry in table 'identities'.

I wrote little script to fix this manually. It works for me but you will have to change some values like LDAP config or MySQL Gitlab config. For me, in LDAP, username is set in 'uid' and email in 'mail' so if it's different for you, change it.

https://gist.github.com/bashou/d9b6e91dbef9663d6dc1

**Comment by JonathonReinhart** [comment]
The same issue exists on Gitlab issue tracker: https://gitlab.com/gitlab-org/gitlab-ce/issues/946

**Comment by JonathonReinhart** [comment]
@bashou Thanks for tracking down the problem, and providing the script. I'm using the Omnibus install of GitLab, which uses Postgresql, and I'm authenticating against Active Directory, so it was a bit different for me.  I only have a few users so I inserted them manually.

First I [opened the psql console](http://blog.redbranch.net/2014/06/19/browsing-the-gitlab-omnibus-postgres-database).  Then `INSERT INTO identities (user_id, extern_uid, provider) VALUES ('jreinhart', 'CN=jreinhart,CN=Users,DC=example,DC=com', 'ldapmain')` and so on for each user.

It would be *really* nice if the developers could fix this.

**Comment by bashou** [comment]
@JonathonReinhart great ! i have more than 500 users so ... you understand why i did this script :+1: 

Maybe we can follow this to developers for 7.7.2.

**Comment by jchodakowski** [comment]
This problem appears fixed in 7.7.2

**Comment by twwheeler** [comment]
I wanted to leave a note for anyone else finding this issue even after upgrading past 7.7.2: make sure to set 'Default projects limit' under the gitlab Settings, otherwise the LDAP auto-create will not work. You'll also see "(OAuth) Error saving user: ["Projects limit can't be blank", "Projects limit is not a number"]" in /var/log/gitlab/gitlab-rails/application.log. Once I set the default limit, LDAP logins w/autocreate worked fine again.

**Comment by rjhornsby** [comment]
I realize this issue has been marked closed, but I just ran into the problem using version 7.14.1.  I was able to remedy the situation using @JonathonReinhart's fix above - https://github.com/gitlabhq/gitlabhq/issues/8530#issuecomment-72125771

However, the identities > user_id field is now(?) an integer (not a username string), which must be referenced from the users table.

**Comment by klandaika** [comment]
GitlLab-CE 8.0.4: The same error message is displayed if you have "Restricted domains for sign-ups" configured and the new user that is trying to login via LDAP does not have an email corresponding to those domains. 
Adding user's email domain to my restricted domains solved the issue and the LDAP user was automatically created in gitlab

**Comment by itomkins** [comment]
This error occurs if attempting to log in with a new LDAP user who does not have the email attribute set in their LDAP account. Adding the email address to the account fixes the issue.
It would be great if the system could fix this with a meaningful error message, or even better by prompting for missing information.

**Comment by joenguyen** [comment]
I'm seeing this regardless of having the email attribute in their profiles.  They are able to log in via LDAP the first time and it auto creates their profile.  For what ever reason, they are unable to log in months later with that error message.  The quick work around for me is to delete their user and have them log in again.  I have to re-add their repository permissions.  It's very annoying.
