### ISSUE TITLE
Markdown: Less than character ('<') hides rest of the line

### ISSUE THREAD

**Issue by tmxnst** [gitlabhq/gitlabhq#8535]
The less than character seems to work like a comment char in gitlab-rendered markdown. If one writes

    one < two, blah-blah

to a README.md, then everything after and including the '<' character is hidden, i.e. only 'one' is rendered in the output. The markdown spec pretty clearly states ( http://daringfireball.net/projects/markdown/syntax#autoescape ) that in this case '<' should be rendered as 

    &lt;

in the HTML.

I'm on gitlab 7.5.2.

**Comment by csware** [comment]
Cross-ref: https://gitlab.com/gitlab-org/gitlab-ce/issues/1015

**Comment by Razer6** [comment]
Fixed with https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/584
