### ISSUE TITLE
How to restart Gitlab server?

### ISSUE THREAD

**Issue by kithokit** [gitlabhq/gitlabhq#8537]
I install through https://about.gitlab.com/downloads/  Gitlab Omnibus package.

However, it doesn't provide init.d script by default. I don't know how to restart the server inorder to reconfigure some settings.

Any guides?

**Comment by Wachiwi** [comment]
`sudo gitlab-ctl restart`should be the command

**Comment by kithokit** [comment]
Thanks! It would be nice if this can be added into docs or inside above link!

**Comment by Razer6** [comment]
This is documented here: https://gitlab.com/gitlab-org/omnibus-gitlab#starting-and-stopping
