### ISSUE TITLE
Export issues to report

### ISSUE THREAD

**Issue by brunobatista** [gitlabhq/gitlabhq#8539]
Have any way to export the issues for a report document? Thanks :+1:

**Comment by Wachiwi** [comment]
Currently theres nothing implemented for achieving anything like that. You can create an feature request at https://feedback.gitlab.com.

**Comment by brunobatista** [comment]
Nice, thanks @Wachiwi :+1: 

https://feedback.gitlab.com/forums/176466-general/suggestions/6927872-export-issues
