### ISSUE TITLE
Fork error - NFS

### ISSUE THREAD

**Issue by jmjoly** [gitlabhq/gitlabhq#8544]
Hi everyone,

I'm consistently getting the following error when forking a project I have already forked and deleted from my namespace:
```
 Fork Error!
You tried to fork <namespace> / <project> but it failed for the following reason:
– Fork transaction failed.
```
My Gitlab runs in 2 instances (active and passive), using NFS storage for repositories.

To reproduce the problem, execute the following steps:
1. Fork a repository;
2. Delete the repository from your namespace;
3. Fork again the repository, it should then fail.

Gitlab doesn't succeed in removing all project folders, as some deleted files are still open (NFS protocol creates .nfs[0..9] files pointing to the inodes to be deleted). The fork error pops up when forking again, because the project folder already exists in the user namespace.

This issue also affects local storage! Even though the project folders can be removed, the deleted files are wasting disk space because the inodes are still being used by the application.

The error appears in GitLab 7.0.0, 7.4.3, 7.5.3, 7.6.2 (Gitlab-shell 2.2.0 and 2.4.0). Has anyone any workaround or solution for this issue? Thanks.

**Comment by iSpoony** [comment]
How do you delete your repo? via shell `rm` or gitlab `remove project`?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
