### ISSUE TITLE
Misstyped email upon signup

### ISSUE THREAD

**Issue by danielsokolowski** [gitlabhq/gitlabhq#8547]
I believe a contact of mine attempted to create a username on gitlab.com and misstyped the email as he never received it, the user is https://gitlab.com/stratus360, the email should have been the same as on this user account: https://gitlab.com/u/arvindaiah

How would we go about to correct the email? 

We tried password reset but he never gets an email for that account.

**Comment by JobV** [comment]
@danielsokolowski just create a new account =) Does it have to be the exact same username? 

I can destroy the old one if necessary.

**Comment by danielsokolowski** [comment]
Please destroy the old one - I'll pass on the info that he can re-sign up :) .

**Comment by JobV** [comment]
Destroyed :)
