### ISSUE TITLE
Limit 2000 commit

### ISSUE THREAD

**Issue by roramirez** [gitlabhq/gitlabhq#8548]
I am using Gitlab version 7.5.1. I have a repository around  2000~ commits, but  on graph commit stats page is limit to 2000.

https://github.com/gitlabhq/gitlabhq/blob/6f34d40436531029228e78d7a55a0e3982dbf89e/app/controllers/projects/graphs_controller.rb#L16

Is a technical reason?

I think this limit could set by config.

**Comment by roramirez** [comment]
Any update?

**Comment by cengizonkal** [comment]
Same problem.

**Comment by cengizonkal** [comment]
```
@commits = @project.repository.commits(nil, nil, 9000, 0, true)
```
Just changed the limit and it is working now.

**Comment by Razer6** [comment]
Technical limit to reduce the load.
