### ISSUE TITLE
[7.6] Dot in username or project name makes Project not found via API

### ISSUE THREAD

**Issue by vemod** [gitlabhq/gitlabhq#8553]
**Summary: **
Get Project details via API (http://doc.gitlab.com/ee/api/projects.html) returns ```{"message":"404 Not Found"}``` if username or project name has a "." (dot) in it. 

**Steps to reproduce: **
* Add dot into username OR add dot to project name.
* Make API call to get project details

**Observed behavior**
* **Good Request**
```curl "http://127.0.0.1:9292/api/v3/projects/testusername%2ftest-project/?private_token=MY_TOKEN"```
```{"id":11,"description":"","default_branch":null...}```

* **Bad Request**
```curl "http://127.0.0.1:9292/api/v3/projects/test.username%2ftest-project/?private_token=MY_TOKEN"```
```{"message":"404 Not Found"}```
```curl "http://127.0.0.1:9292/api/v3/projects/testusername%2ftest.project/?private_token=MY_TOKEN"```
```{"message":"404 Not Found"}```

**Expected behavior:**
Dot is a natural delimiter in user names especially when they get generated from LDAP Emails. So "." should not have same effect like "-" (no effect).

**Version info**
```bundle exec rake gitlab:env:info RAILS_ENV=production```

```
System information
Using RVM:      yes
RVM Version:    1.25.28
Ruby Version:   2.1.3p242
Gem Version:    2.2.2
Bundler Version:1.7.3
Rake Version:   10.3.2
Sidekiq Version:2.17.8

GitLab information
Version:        7.6.2
Revision:       43180c6
Directory:      /home/git/gitlab
DB Adapter:     mysql2

GitLab Shell
Version:        2.4.0
```

**Comment by falsecz** [comment]
@vemod try to replace `.` with `%2E`  like `/` with `%2F`

**Comment by vemod** [comment]
@falsecz Thank you. that worked out. 

But is more like a workaround isn't it? urlencode() doesn't replace `.` with `%2e`. So have to explicitly replace it after calling urlencode.
I suggest a fixing it server side where it would handle dots in the project or username correctly

**Comment by oxc** [comment]
Is this going to be fixed? Sure seems like a server-side bug, not one every API client should work-around.
(And a very annoying one for any "dot"-project owner.)

**Comment by dkarlovi** [comment]
I'm seeing this on 8.2.1 via Apache reverse proxy, but the %2E instead of dot thing is not working for me for some reason. I'm upgrading to 8.2.2 and have just updated my Apache config to latest from here: https://gitlab.com/gitlab-org/gitlab-recipes/blob/master/web-server/apache/gitlab-ssl-apache24.conf

**Comment by dkarlovi** [comment]
My problem is Apache-related, [reported at Gitlab.com](https://gitlab.com/gitlab-org/gitlab-recipes/issues/36).

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
