### ISSUE TITLE
Emoji Cheat Sheet Missing

### ISSUE THREAD

**Issue by al3x-edge** [gitlabhq/gitlabhq#8554]
Currently in the documentation, the emoji cheat sheet links to a missing file (https://www.dropbox.com/s/b9xaqb977s6d8w1/cheat_sheet.pdf) -- Is there an updated link? Would be glad to provide a PR if a new one exists.

**Comment by dosire** [comment]
@JobV Can you give @al3x-edge a link to the proper file so he can provide a PR? (thanks @al3x-edge )

**Comment by al3x-edge** [comment]
@dosire @Razer6 Looks like the URL has been fixed. Closing.

**Comment by Razer6** [comment]
@jobv The file is missing again!

**Comment by JobV** [comment]
Ohnoes! Let me see..

**Comment by JobV** [comment]
https://www.dropbox.com/s/tljphw6hqrdsbuw/cheat_sheet.pdf?dl=0

**Comment by Razer6** [comment]
Fixed in 7.9
