### ISSUE TITLE
Add user to network display

### ISSUE THREAD

**Issue by helgrind** [gitlabhq/gitlabhq#8557]
Would it be possible to prefix the user on merges in the network diagram so that merging two similarly named branches from a fork to an original repo doesn't look confusing? ie merged "forker/featurebranch" into "groupname/featurebranch"

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
