### ISSUE TITLE
Old URL in installation doc for debian/ubuntu

### ISSUE THREAD

**Issue by juangamnik** [gitlabhq/gitlabhq#8562]
The gitlab installation doc for debian/ubuntu points at `http://deb.pkgr.io/`, which is not reachable (I get *unknown host*). With `https://deb.packager.io/` everything works fine.

**Comment by Razer6** [comment]
@juangamnik Can you point to that file?

**Comment by juangamnik** [comment]
e.g. [here](https://gitlab.com/gitlab-org/gitlab-recipes/tree/4efadad826f69b1782956be5d322605333ed9aaa/install/pkgr).

**Comment by Razer6** [comment]
Fixed.
