### ISSUE TITLE
Preview option for wiki-pages/comments/...

### ISSUE THREAD

**Issue by juangamnik** [gitlabhq/gitlabhq#8563]
Like in GitHub it would be nice to be able to preview the markdown text written in a comment-field or wiki-page or similar text editors. 

Even nicer would be the integration of a nice split-screen editor like [Stackedit](http://stackedit.io) or if this is overkill, than the semi-WYSIWYG editor on the left of stackedit.

**Comment by Razer6** [comment]
Proeview in wiki implemented

**Comment by juangamnik** [comment]
In comments, too?

**Comment by Razer6** [comment]
yep.

**Comment by juangamnik** [comment]
Cool, thank you. I mixed up two things in this issue, therefore I opened a separate one here #8892
