### ISSUE TITLE
Wiki: Page Name with period 404s

### ISSUE THREAD

**Issue by VertigoRay** [gitlabhq/gitlabhq#8565]
# Components

```text
GitLab 7.6.2
GitLab Shell 2.4.0
GitLab API v3
Ruby 2.1.5p273
Rails 4.1.1
```

# Summary

When working with a page name with a period, the page cannot be found unless you include the `.markdown` extension

# Description

The list at my wiki pages list (ie: `https://gitlab.vertigion.com/project/repo/wikis/pages`) shows my documentation page: *MyApp.exe*. Clicking *MyApp.exe* will take you to: `https://gitlab.vertigion.com/project/repo/wikis/MyApp.exe`. This `/wikis/MyApp.exe` page brings up the creation page, as if the file doesn't exists. If you put anything in the field and click *Create Page*, you will get an error message: `Duplicate page: Cannot write //MyApp.exe.markdown, found //MyApp.exe.markdown.`.  Changing the URL to `MyApp.exe.markdown` displays the existing wiki article.

**Comment by sque** [comment]
I can also confirm the bug.

Nice workaround!
