### ISSUE TITLE
how to import github big code project manually?

### ISSUE THREAD

**Issue by detailyang** [gitlabhq/gitlabhq#8573]
Hi, our project have 1GB code size.i try import existing project by gitlab web ui , but it's failed.So i want to know how can i import project by manually.By the way , i can login my gitlab server:)

**Comment by Wachiwi** [comment]
If I understand you right [this](https://github.com/gitlabhq/gitlabhq/blob/master/doc/raketasks/import.md) could help you to import your bare repos.

**Comment by detailyang** [comment]
thx.
