### ISSUE TITLE
REPOS_PATH MUST NOT BE A SYMLINK!!! Why？

### ISSUE THREAD

**Issue by javacty** [gitlabhq/gitlabhq#8577]
REPOS_PATH MUST NOT BE A SYMLINK!!! Why？

**Comment by Wachiwi** [comment]
why should it be?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report. Please reformat your issue to conform to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
