### ISSUE TITLE
New merge requests always shows »You must select source and target branches«

### ISSUE THREAD

**Issue by paulmenzel** [gitlabhq/gitlabhq#8581]
Creating a new merge request (`https://gitlab.example.net/penguincorp/awesomeproject/merge_requests/new`) the warning `You must select source and target branches` is shown. Unfortunately, it’s not dynamic, that means, when the user actually selects these branches, the warning does not disappear causing confusion.

**Comment by Wachiwi** [comment]
This should be fixed in #8495

**Comment by Razer6** [comment]
Closing as duplicate
