### ISSUE TITLE
Old navigation in GitLab 7.7

### ISSUE THREAD

**Issue by YURSHAT** [gitlabhq/gitlabhq#8583]
hello
Is it possible to return to the old horizontal navbar in GitLab 7.7? New sidebar-nav looks terrible ![](http://static.skaip.su/img/emoticons/v2/ffffff/tmi.gif)

**Comment by maxlazio** [comment]
Thanks for raising an issue. I have a different  opinion than yours about the sidebar navigation. I found that it sped up my navigation around GitLab.

You can [read about what initiated this change here](https://about.gitlab.com/2015/01/16/pragmatic-redesign-for-gitlab/) and voice your opinion in the comments and follow the discussion there.

**Comment by emovere** [comment]
I like it, but theres a bug.
On my Macbook Air 11' I can't scroll the new navigation bar, only the sites content.
(Take a look at the attached screenshot, there are more elements after 'protected branches', but I can't get there because the resolution is too low/I can't scroll the navigation bar)
![screen shot 2015-01-20 at 10 27 03 pm](https://cloud.githubusercontent.com/assets/8715351/5826555/efcdd7c2-a0f3-11e4-9aa4-be020ca71a55.png)

**Comment by randx** [comment]
@emovere what is your screen resolution?

**Comment by emovere** [comment]
The full Macbook Air 11' Screen resolution (1366 x 768)
I have create 2 screenshots with full resolution, for comparison (in fullscreen mode I can see every item, see attached screenshots)

Anyway, it doesn't distract me very much, but it would be great if the new sidebar would be scrollable.
![screen shot 2015-01-20 at 11 33 18 pm](https://cloud.githubusercontent.com/assets/8715351/5827735/54d1c012-a0fd-11e4-8ebb-252f3d8a4f40.png)
![screen shot 2015-01-20 at 11 32 53 pm](https://cloud.githubusercontent.com/assets/8715351/5827736/54f6aada-a0fd-11e4-94ad-df138660df99.png)

**Comment by randx** [comment]
Thank you for 2 screenshots. Now I see the problem!

**Comment by Razer6** [comment]
Also on gitlab.com https://gitlab.com/gitlab-org/gitlab-ce/issues/980

**Comment by randx** [comment]
Fixed in 7.8 by separating settings from rest of menu

![settings](https://cloud.githubusercontent.com/assets/305940/6275024/d13959d6-b830-11e4-944f-601543955ce6.png)
