### ISSUE TITLE
Sign-up form visible on login page even when signup_enabled=false

### ISSUE THREAD

**Issue by zrax** [gitlabhq/gitlabhq#8586]
After updating to GitLab 7.7.0.rc2, the login page now contains the Sign Up form by default.  Even after setting `signup_enabled: false` in the config.yml and restarting sidekiq and Apache (I'm using Phusion Passenger rather than Nginx/unicorn), the sign-up form is still displayed.

For reference, this behavior was not seen in GitLab 7.6.0 on the same configuration.

**Comment by maxlazio** [comment]
Hi,

have you tried changing it from the Admin area -> Settings ? Does it work then?

**Comment by zrax** [comment]
Ah, yes it does; thanks.  The default setting here also didn't match what was in the config file -- does this mean the config file's copy of this setting is now deprecated in favor of the Admin settings' version?

**Comment by xperseguers** [comment]
Thanks as well. Yes, it seems some of those settings are now deprecated in favour of UI configuration.

**Comment by maxlazio** [comment]
In 7.7 we've moved some of the settings to the admin area. Our goal is to move away from the yml configuration to the admin section. 
The settings, by default, should pick up the setting from the yml file if the setting existed.

**Comment by xperseguers** [comment]
Then, what did not succeed is that this signup setting is said to be "false" by default (= undefined in yml) and it was active after the upgrade so previous default values are not taken into account.

**Comment by zrax** [comment]
Agreed.  Additionally, if the setting is now deprecated/moved, I feel it should be removed from the gitlab.yml.example file to avoid confusion.

**Comment by Latrell** [comment]
我翻遍大江南北，原来这个设置被放在`Admin area -> Settings`里了。。。

**Comment by Razer6** [comment]
Closing because settings are clarified now.
