### ISSUE TITLE
Github inspired issue tracker theme

### ISSUE THREAD

**Issue by simonzack** [gitlabhq/gitlabhq#8588]
I've always loved the github issue tracker theme, and I've [created](https://github.com/simonzack/gitlab_github_theme/blob/master/gitlab_github_theme.css) a github inspired theme for gitlab as an userstyle.

What do you think?

![screenshot](https://cloud.githubusercontent.com/assets/628500/5772589/0c886f6a-9da9-11e4-90e4-9b1721ad41b5.png)

Also, would it be nicer if the first post could be made like the others in the default theme, so a more uniform look can be achieved for custom themes? It took me lot of hacks to achieve that effect :)

**Comment by jbrooksuk** [comment]
This looks much better to me - it feels more polished.

**Comment by rumpelsepp** [comment]
I think the username needs a bit more gray. It is too dark.

**Comment by randx** [comment]
I dont feel good about idea of copying GitHub UI. I understand that our software is solving same problems but I think we should find our own way in UI.  Still thank you for proposal. I am open for new ideas in UI/UX improvemenets
