### ISSUE TITLE
Server error (500) when accessing admin/groups in 7-7-stable

### ISSUE THREAD

**Issue by pduersteler** [gitlabhq/gitlabhq#8590]
Visiting `/admin/groups` in 7-7-stable (recently upgraded from 6.9.2), I get a server error.

**Log**  
```
Started GET "/admin/groups" for 127.0.0.1 at 2015-01-16 10:07:37 +0100
Processing by Admin::GroupsController#index as HTML
Completed 500 Internal Server Error in 96ms

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    35:           = truncate group.description, length: 150
    36:       .clearfix
    37:         %p.light
    38:           #{pluralize(group.members.size, 'member')}, #{pluralize(group.projects.count, 'project')}
    39: 
    40: 
    41: = paginate @groups, theme: "gitlab"
  app/views/admin/groups/index.html.haml:38:in `block in _app_views_admin_groups_index_html_haml___66148943948900042_70333098814760'
  app/views/admin/groups/index.html.haml:18:in `_app_views_admin_groups_index_html_haml___66148943948900042_70333098814760'
```

**Comment by ACCBizon** [comment]
+1 same issue (clean install)

**Comment by maxlazio** [comment]
@ACCBizon If you managed to get the problem on clean install, can you tell us the steps on how to reporduce it? Do you have any groups created? If yes, can you access the groups from other sections in gitlab?

**Comment by ACCBizon** [comment]
@maxlazio, 
1. new droplet created on digitalocean, 
2. gitlab installed according to the [instructions](https://www.digitalocean.com/community/tutorials/how-to-set-up-gitlab-as-your-very-own-private-github-clone), 
3. logged into the admin, then chose the tab group (error 500), 
4.I created a test group and I can enter it from any other place but not form the group tab in the admin panel (error 500).

**Comment by Eijebong** [comment]
+1 Same here

**Comment by pweingardt** [comment]
Same here. Also the same error appears in "Explore -> Groups", just in a different file.

**Comment by 123Haynes** [comment]
@pweingardt Can you please post a log for your case as well?

**Comment by pweingardt** [comment]
Sure: http://sprunge.us/fiYe

**Comment by fedir** [comment]
+1 Upgrade from 6.4 using these instructions https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/6.x-or-7.x-to-7.7.md


All works except 500 error on group list page.

Ruby Ruby latest stable : 2.2.0p0 

```
Started GET "/admin/groups" for 127.0.0.1 at 2015-01-19 09:58:28 +0100 
Processing by Admin::GroupsController#index as HTML
Completed 500 Internal Server Error in 111ms 

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    35:           = truncate group.description, length: 150
    36:       .clearfix
    37:         %p.light
    38:           #{pluralize(group.members.size, 'member')}, #{pluralize(group.projects.count, 'project')}
    39:   
    40:   
    41: = paginate @groups, theme: "gitlab"
  app/views/admin/groups/index.html.haml:38:in `block in _app_views_admin_groups_index_html_haml___2757392080300126808_69914331370860'
  app/views/admin/groups/index.html.haml:18:in `_app_views_admin_groups_index_html_haml___2757392080300126808_69914331370860'
```

**Comment by 123Haynes** [comment]
Uhm... your ruby version might cause that error.
Gitlab currently only supports ruby 2.1.5

**Comment by fedir** [comment]
Looks like simple error, need to put conditions something in app/views/admin/groups/index.html.haml

**Comment by 123Haynes** [comment]
probably. But take a look at this:
https://github.com/gitlabhq/gitlabhq/issues/8608#issuecomment-70462475
Please test if downgrading ruby to 2.1.5 fixes this problem. 
If this is a ruby 2.2 issue then it will probably be fixed later.

**Comment by fedir** [comment]
@123Haynes Looks like You are right. In this case, I will keep Ruby 2.2.0 at the moment : it's faster, than 2.1.5.

Hope, Gitlab will be compatible with actual stable Ruby. Apparently, only minor adjustments are needed.

**Comment by ftlynx** [comment]
+1 same issue (clean install)

**Comment by fedir** [comment]
@ftlynx Your Ruby version ?

**Comment by randx** [comment]
If someone has issues on ruby 2.15 or lower - please mention. Right now I will update README to say that ruby 2.2.0 is not supported yet

**Comment by Razer6** [comment]
Closing this as seems to be a ruby 2.2 issue which is currently not supported
