### ISSUE TITLE
Feature: Implement pronto on merge requests

### ISSUE THREAD

**Issue by zedtux** [gitlabhq/gitlabhq#8593]
Having the [Pronto](https://github.com/mmozuras/pronto) gem running after the creation of a merge request and having it updating the merge request would be very nice.

The gem has already [a formatter for Gitlab](https://github.com/mmozuras/pronto/pull/50) so the final step is to trigger it with the right parameters (in a sidekiq job I guess).

**Comment by carlosbaraza** [comment]
+1

**Comment by Wachiwi** [comment]
:+1:

**Comment by zedtux** [comment]
Is it possible to assign this feature to a milestone @jvanbaarsen and @Razer6 ?

**Comment by Wachiwi** [comment]
@zedtux The problem is that the gitlab team doesn't use the github issue tracker for feature requests. There is an separate feature request forum at http://feedback.gitlab.com

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

**Comment by zedtux** [comment]
Thank you both. @carlosbaraza @Wachiwi please vote for http://feedback.gitlab.com/forums/176466-general/suggestions/7111707-implement-pronto-on-merge-requests :)
