### ISSUE TITLE
7.7 Ability to "minimize" new menu to icons and two other new menu related items

### ISSUE THREAD

**Issue by sashkab** [gitlabhq/gitlabhq#8597]
1. I would like to be able to minimize new navigation UI  to  just icons, like on mobile UI. I want to maximize horizontal space.

2. Why we have two navigation items on screen for Issues, Merge Request and Tags, but don't have Milestones on new menu? Do we need tabs there?

3. Clicking on Settings, should open and close sub-menu, not select General in the Settings sub-menu.

**Comment by kaystrobach** [comment]
the issues menu item should also behave like the settings item

![image](https://cloud.githubusercontent.com/assets/1185776/5870955/479dbe0c-a2d6-11e4-8ae5-8d33d39c4ec3.png)

**Comment by randx** [comment]
@Razer6 all 3 questions were addressed. I think we can close this one

**Comment by Razer6** [comment]
:heart:
