### ISSUE TITLE
UI suggestion: integrate the issue description into the discussion

### ISSUE THREAD

**Issue by simonzack** [gitlabhq/gitlabhq#8598]
Can I suggest that the issue description be made to look like other comments in the discussion? Some points I think are worth mentioning here:
- The issue description feels more like a part of the discussion instead of sitting alone at the top. The reason I use the word discussion, is that I think issues can be rather dynamic, and evolve through time. More recent comments can lead to more changes that aren't reflected in the initial post. For example performance bugs can lead to more fine grained test cases, and suggestions can lead to better ones, which aren't different enough to warrant a new issue.
- The timeline, including the avatars feels more consistent. You can immediately tell who raised the issue.
- With an edit button, the first post can be edited just like another other posts, and the mouse doesn't have to be dragged all the way to the top right.

I'm happy to work on this and submit a PR. Here are some mockups I've prepared:

Before:
![before](https://cloud.githubusercontent.com/assets/628500/5787602/9dfb688e-9e59-11e4-8c43-4288c15536d9.png)

After:
![after](https://cloud.githubusercontent.com/assets/628500/5787656/309a6cd8-9e5c-11e4-9bd4-ed606b313bfb.png)

What do you think?

**Comment by randx** [comment]
Thank you. But I think I already answered in similar issue - https://github.com/gitlabhq/gitlabhq/issues/8588#issuecomment-70287040

**Comment by simonzack** [comment]
Can you please take another look? I tried my best this time to retain the stock gitlab look. It's simply a re-arrangement of the title post, done in ms paint, so that it looks the same as the comments.

I don't think this arrangement is unique to github, bitbucket and forum software do it, for example.

**Comment by rumpelsepp** [comment]
> The issue description feels more like a part of the discussion instead of sitting alone at the top. The reason I use the word discussion, is that I think issues can be rather dynamic, and evolve through time. More recent comments can lead to more changes that aren't reflected in the initial post.

I think this does make sense.

**Comment by jasonblanchard** [comment]
Hey all,

I have a merge request in that is very similar to this UI: https://github.com/gitlabhq/gitlabhq/pull/8700

Feel free to review and make suggestions.

**Comment by simonzack** [comment]
@jasonblanchard Is that the right PR you're referring to? Your description says "adding in a link to the milestone" which is nice but a bit different to what I'm proposing.

**Comment by jasonblanchard** [comment]
@simonzack Sorry, n/m, I thought this was about something else.

My bad!

**Comment by randx** [comment]
I dont like idea separating issue title and description

**Comment by Razer6** [comment]
UI gets overhauled, let's close this for now.
