### ISSUE TITLE
developer can push on protected branch if include some tags

### ISSUE THREAD

**Issue by massimone88** [gitlabhq/gitlabhq#8599]
It's so weird but I found this issue in this way.
I created a project repository on gitlab using the GitFlow workflow (branches are master, developer, feature/*, release/*,, hotfix/*) and in my local machine I use SourceTree IDE for managing the workflow command (init a feature, finish a feature, ecc).
I set master as protected branch .
If a developer try to push a normal commit to master branch, the gitlab web server return a permission error code as expected.
If the developer start a new realease, commit something in this realease's branch and after all, finish the feature (in a nutshell merge the realease's branch to the develop branch and master branch) the push command is working!!!.

Gitlab is running on CentOS machine with a omnibus version 7.6.2.
I'm available to get some other informations (log,s screenshot) and collaborate to resolve this issue,
Any help is appreciated!

EDIT:
I try the same thing also in a ubuntu machine and i find this conclusion:
If you do some operations (also in a protected branch) in your local repository and some operations consists one or more tags, an then you try to push in you remote repository with a command "git push --tags" the operation is working without any error code. If you try to push without tags the operation ended unsuccesfully ( as expected).

Am I the only one that found this bug? Is a wrong configuration on gitlab server? Is otherwise a issue?

**Comment by massimone88** [comment]
![gitlab_bug](https://cloud.githubusercontent.com/assets/10571618/5793436/aa1be522-9f43-11e4-9347-92ea4c0110e1.jpg)

**Comment by massimone88** [comment]
up!

**Comment by Razer6** [comment]
@massimone88 Is this still reproducible? /cc @randx Might be a security issue

**Comment by randx** [comment]
@massimone88 what is your GitLab version?

**Comment by maxlazio** [comment]
I think this is a duplicate of this issue https://gitlab.com/gitlab-org/omnibus-gitlab/issues/405 so it is safe to close it.

**Comment by massimone88** [comment]
The issue was fixed with release 7.7.. I forgot ti close the issue.. Sorry
Il giorno mar 5 mag 2015 alle 08:05 Robert Schilling <
notifications@github.com> ha scritto:

**Comment by randx** [comment]
@massimone88 awesome! Thanks
