### ISSUE TITLE
open close issue

### ISSUE THREAD

**Issue by scap1784** [gitlabhq/gitlabhq#8600]
In the issue tab, when I close an issue and the reopen it the issue no longer shows up in open. It only shows up as assigned to me, created by me and all. When reopened it should show up in the open category.

**Comment by axilleas** [comment]
I cannot reproduce on gitlab.com. Can you provide your setup information and the steps to reproduce this?

**Comment by scap1784** [comment]
This is with a fresh install of the gitlab in a container using the turnkeylinux gitlab container. I then create an issue ticket with test for the subject and test in the message and close out the ticket and reopen it and then it doesn't show up in open issues. The only time is shows up in the open issues is when it is originally created.

**Comment by axilleas** [comment]
Sorry but I cannot reproduce it in gitlab 7.7rc. I see that turnkeylinux uses a [super old gitlab version (5.0)](https://github.com/turnkeylinux-apps/gitlab/blob/master/overlay/usr/local/src/gitlab.conf#L5). I recommend you to use the [official packages](https://about.gitlab.com/downloads/).
