### ISSUE TITLE
Error 500 on Groups overview (Admin area)

### ISSUE THREAD

**Issue by TD092854** [gitlabhq/gitlabhq#8608]
When i'm trying to view the groups in the admin area i get an internal server error.

Started GET "/admin/groups" for 127.0.0.1 at 2015-01-18 20:57:49 +0100
Processing by Admin::GroupsController#index as HTML
Completed 500 Internal Server Error in 17ms
ActionView::Template::Error (undefined method `name' for nil:NilClass):
35: = truncate group.description, length: 150
36: .clearfix
37: %p.light
38: #{pluralize(group.members.size, 'member')}, #{pluralize(group.projects.count, 'project')}
39:
40:
41: = paginate @groups, theme: "gitlab"
app/views/admin/groups/index.html.haml:38:in `block in _app_views_admin_groups_index_html_haml__753687198376570285_70042414265620'
app/views/admin/groups/index.html.haml:18:in `_app_views_admin_groups_index_html_haml__753687198376570285_70042414265620'

I have Gitlab running on Ubuntu 14.04 with 2GB of ram.
Gitlab: 7.7.0.rc4
Gitlab shell: 2.4.1
Ruby: 2.2.0p0

**Comment by nidiac** [comment]
I got the same error when try to view groups in admin area, but it work fine to view groups in profile area.
>OS Version:    Centos6.5
>Ruby Version:	2.2.0p0
>Gem Version:	2.4.5
>Bundler Version:1.7.12
>Rake Version:	10.3.2
>Sidekiq Version:2.17.8
>Gitlab Version:	7.6.2    16f0968
>GitLab Shell Version:	2.4.1

**Comment by nidiac** [comment]
I fix the error by change ruby to 2.1.5 version

**Comment by TD092854** [comment]
Thanks! @nidiac. It worked.
