### ISSUE TITLE
Wiki Preview Generates '414 Request-URI Too Large'

### ISSUE THREAD

**Issue by thelok** [gitlabhq/gitlabhq#8611]
The following error is generated when trying to 'preview' a wiki page that has alot of text content:

```
414 Request-URI Too Large
nginx
```

The URL is in the format:

https://[myserver.com]/[groupname]/[projectname]/markdown_preview?md_text=[my_entire_page_in_encoded_format]

This issue does not exist if the content being previewed has  a small amount of text.

In my specific case the text content is about 16,000 characters. I'm using the latest gitlab release 7.7.0.rc4

**Comment by akaihola** [comment]
I'm seeing the same symptom running the GitLab 7.6.2 [docker image](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/docker).

**Comment by akaihola** [comment]
It seems that the markdown content is transmitted as a GET parameter. Probably Nginx can be configured to handle longer URIs, but some browsers might still [have issues](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).

**Comment by thelok** [comment]
This should really be a POST instead of a GET

**Comment by maoueh** [comment]
@thelok I agree, +1 on my part. It seems for the wiki in GitLab handling is different because I was editing a very large document, clearly over 16000 characters and did not had this problem. I may be wrong however.

**Comment by bobrovnikov** [comment]
Same on GitLab 7.7.1
![markdown_preview](https://cloud.githubusercontent.com/assets/1423570/6069981/f5a68f10-ad99-11e4-8635-20448c412fe0.png)

**Comment by randx** [comment]
Fixed by 639c93b4f2bd492a214065b5fdc47da2f5d8614d
