### ISSUE TITLE
project import: HTTP scheme with unsupported registry part not handled

### ISSUE THREAD

**Issue by paulmenzel** [gitlabhq/gitlabhq#8616]
Creating a new project and, in the *Import existing git repo* field, entering an URL in HTTP scheme and with a registry part (by for example taking an URL in SSH scheme without removing the colon `:`) an internal server error triggered and the user sees a 500 error page.

        Completed 500 Internal Server Error in 31ms

        ActionView::Template::Error (the scheme http does not accept registry part: username:password@gitlab.com:company (or bad hostname?)):
            4:       %h2
            5:         %i.fa.fa-spinner.fa-spin
            6:         Import in progress.
            7:       %p.monospace git clone --bare #{hidden_pass_url(@project.import_url)}
            8:       %p Please wait while we import the repository for you. Refresh at will.
            9:       :javascript
           10:         new ProjectImport();
          app/helpers/projects_helper.rb:278:in `hidden_pass_url'
          app/views/projects/import.html.haml:7:in `_app_views_projects_import_html_haml__597848005956285849_69818793815300'

It’d be great, if an error message could be shown to the user.

**Comment by paulmenzel** [comment]
This is with GitLab 7.5.2.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
