### ISSUE TITLE
post-receive hook not triggered if new tag added via gitlab portal

### ISSUE THREAD

**Issue by mumblez** [gitlabhq/gitlabhq#8619]
works when committing and pushing via cli / git tools but if someone creates a new tag via gitlab's interface the post-receive hook is not executed.

Affects version 7.0 (possibly prior) and latest 7.6

Not sure if this is by design, if so can you suggest a way to trigger this on a per repo basis?

(gitlab community edition)

**Comment by minorOffense** [comment]
This is still an issue in 7.8.4. Tag push events aren't triggered for tags created through the UI.

**Comment by Razer6** [comment]
Duplicate of https://github.com/gitlabhq/gitlabhq/issues/7357
