### ISSUE TITLE
GitLab 7.6.2 - Exception 500 by trying to delete a project

### ISSUE THREAD

**Issue by rhazdon** [gitlabhq/gitlabhq#8621]
Hi Guys,

when I'm trying to delete a project, I get a 500 Exception. GitLab only removes all project members, but the project itself stil exsists (just without a owner).

I have to projects (one of them is empty). Both are undeleteable...

Did anybody get the same problem?

My bin/check result:

`Checking Environment ... `

`Git configured for git user? ... yes`

`Checking Environment ... Finished`

`Checking GitLab Shell ...`

`GitLab Shell version >= 2.4.0 ? ... OK (2.4.1)`
`Repo base directory exists? ... yes`
`Repo base directory is a symlink? ... no`
`Repo base owned by git:git? ... yes`
`Repo base access is drwxrws---? ... yes`
`Satellites access is drwxr-x---? ... yes`
`hooks directories in repos are links: ... `
`anyname / pmt ... ok`
`anyname / test ... repository is empty`
`Running /home/git/gitlab-shell/bin/check`
`Check GitLab API access: OK`
`Check directories and files: `
` 	/home/git/repositories/: OK`
` 	/home/git/.ssh/authorized_keys: OK`
`Test redis-cli executable: redis-cli 2.4.14`
`Send ping to redis server: PONG`
`gitlab-shell self-check successful`

`Checking GitLab Shell ... Finished`

`Checking Sidekiq ...`

`Running? ... yes`
`Number of Sidekiq processes ... 1`

`Checking Sidekiq ... Finished`

`Checking LDAP ...`

`LDAP is disabled in config/gitlab.yml`

`Checking LDAP ... Finished`

`Checking GitLab ...`

`Database config exists? ... yes`
`Database is SQLite ... no`
`All migrations up? ... yes`
`Database contains orphaned GroupMembers? ... no`
`GitLab config exists? ... yes`
`GitLab config outdated? ... no`
`Log directory writable? ... yes`
`Tmp directory writable? ... yes`
`Init script exists? ... yes`
`Init script up-to-date? ... yes`
`projects have namespace: ... `
`anyname / pmt ... yes`
`anyname / test ... yes`
`Projects have satellites? ... `
`anyname / pmt ... yes`
`anyname/ test ... can't create, repository is empty`
`Redis version >= 2.0.0? ... yes`
`Ruby version >= 2.0.0 ? ... yes (2.2.0)`
`Your git bin path is "/usr/bin/git"`
`Git version >= 1.7.10 ? ... yes (1.7.10)`

`Checking GitLab ... Finished`

Regards, Rhazdon

**Comment by Razer6** [comment]
We do not support ruby 2.2 right now. Please use 2.1.5
