### ISSUE TITLE
Request for a milestone button on an issue page

### ISSUE THREAD

**Issue by SheffieldKevin** [gitlabhq/gitlabhq#8623]
After editing or viewing issues that belong to a milestone I'd like a button that when clicked on takes me to the milestone that the issue belongs to. It would also be nice to have a button that takes you to the previous milestone the issue belonged to if the change to the issue was moving it from one milestone to another.

It might be too much to have both, but having a way to do both would be useful when reviewing issues and milestones.

**Comment by kaystrobach** [comment]
:+1:

**Comment by PowerPan** [comment]
+1

**Comment by maxlazio** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
