### ISSUE TITLE
Error while trying to view files

### ISSUE THREAD

**Issue by kgoedert** [gitlabhq/gitlabhq#8625]
Hi,

I just installed a GitLab 7.6.2 on a ubuntu 12.04 machine. I created a project, made some commits and when clicking on the Files link I get a 500 error. On the logs I found this:

Completed 500 Internal Server Error in 30ms
ActionView::Template::Error (invalid byte sequence in UTF-8):
29: %small.light
30: = link_to @commit.short_id, project_commit_path(@project, @commit)
31: &ndash;
32: = truncate(@commit.title, length: 50)
33: = link_to 'History', project_commits_path(@project, @id), class: 'pull-right'
34:
35: - if @path.present?
app/models/commit.rb:76:in `title'
app/views/projects/tree/_tree.html.haml:32:in `_app_views_projects_tree__tree_html_haml___2869660163285965848_42673040'
app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml__3420227725955077078_41362220'
app/controllers/projects/tree_controller.rb:13:in `show'

Can somebody help?

**Comment by DouweM** [comment]
A fix to this issue has been merged and will be in version 7.9. Please reopen this issue if the problem persists after upgrading to 7.9.
