### ISSUE TITLE
Missed some CSS rules in #8425

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8628]
In my pull request #8425 I missed some CSS rules which are used for highlighting anchors in the source code. IIRC it is this line https://github.com/gitlabhq/gitlabhq/blob/2b10520b306697d7cbae8f3f84ca30cacc821fa4/app/assets/stylesheets/highlight/dark.scss#L15 which is missing in the other themes. I will do a pull request for this in a few days unless no one else is faster than I am. :)

**Comment by Razer6** [comment]
@rumpelsepp Have you time to make a PR?

**Comment by rumpelsepp** [comment]
Currently I am moving to Munich and time is a little problem... Maybe I have an hour tomorrow or on wednesday.

**Comment by rumpelsepp** [comment]
see ##8816
