### ISSUE TITLE
Forced HTTPS validation on new "System OAuth applications"

### ISSUE THREAD

**Issue by rahul286** [gitlabhq/gitlabhq#8632]
I just upgraded to GitLab 7.7 and Gitlab CI to 5.4.

The new `OAuth applications` is forcing SSL requirement on URL. I think this validation is added in error and should be removed.

Please find attached screenshot below:

![admin_area___gitlab](https://cloud.githubusercontent.com/assets/4115/5862298/b1968838-a296-11e4-8d2e-07692586b954.png)

HTTPS is good but security should be optional. Going by above validation, I am allowed to run GitLab without HTTPS but for CI, HTTPS is forced!

**Comment by Stayallive** [comment]
If I'm not mistaken OAuth 2.0 requires the use of SSL/TLS for transport layer security to make it secure.

For reference: http://tools.ietf.org/html/rfc6749

**Comment by rahul286** [comment]
@Stayallive I believe it's a recommendation. Not compulsion. 

Our Gitlab uses Google Auth - http://git.rtcamp.com/ without HTTPS anywhere. We have many more sites where OAuth is used with HTTP callback URLs.

IMHO, from validation perspective, HTTP and HTTPS both should be allowed since both works in real life. 

I had to downgrade CI as it's forcing Gitlab OAuth which doesn't work with HTTP alone. :|

**Comment by StephenOTT** [comment]
:+1: please remove this requirement.  VERY annoying!  Github does not have this requirement.

Makes local development much more complicated as well.

**Comment by StephenOTT** [comment]
@axilleas

**Comment by Stayallive** [comment]
Already fixed (3h ago): https://about.gitlab.com/2015/01/23/gitlab-7-7-1-and-gitlab-ci-5-4-1-released/

**Comment by StephenOTT** [comment]
Woot!!! That was fast!  Thanks!!

**Comment by rahul286** [comment]
Thanks for quick fix. :-1:
