### ISSUE TITLE
Application Settings: Uploading Custom Images

### ISSUE THREAD

**Issue by vinkla** [gitlabhq/gitlabhq#8633]
**Feature request:** Add upload fields to the Application settings page were administrators can upload custom logos for the navbar and favicons to make it feel more personal.
![custom-logo](https://cloud.githubusercontent.com/assets/499192/5863623/2ff7bf6a-a27b-11e4-9bc7-6657d485c672.jpg)

Right now we set this up trough the virtual host file `/etc/nginx/sites-available/gitlab`.

````
location ~ ^/assets/favicon.*\.ico$ { alias /home/vinkla/assets/favicon.ico; }
location ~ ^/assets/login-logo.*\.png$ { alias /home/vinkla/assets/login-logo.png; }
location ~ ^/assets/logo-white.*\.png$ { alias /home/vinkla/assets/logo-white.png; }
location ~ ^/assets/logo-black.*\.png$ { alias /home/vinkla/assets/logo-black.png; }
location ~ ^/assets/brand_logo.*\.png$ { alias /home/vinkla/assets/brand_logo.png; }
``` 
Thoughts on this? Is this something you would consider adding?

**Comment by Wachiwi** [comment]
The gitlab team doesn't use the gitlab issue tracker for feature requests. If you want to submit a feature request you can do that at https://feedback.gitlab.com/. 
If you have submitted it post a link to your feature request inside this issue so others can vote for it :smile:.

:+1:

**Comment by vinkla** [comment]
Okay, sorry about that. Closing this.
