### ISSUE TITLE
Feature Request: Switch to Disable Pages

### ISSUE THREAD

**Issue by vinkla** [gitlabhq/gitlabhq#8634]
Adding the ability to switch pages on and off. For example; on our installation at work we don't use the snippets page. It would be great if we could disable/enable it on the Application Settings page.

**Comment by vinkla** [comment]
Okay, sorry about that. Closing this.

**Comment by Wachiwi** [comment]
You can do that inside your gitlab.yml config. See this [here](https://github.com/gitlabhq/gitlabhq/blob/master/config/gitlab.yml.example#L87).

**Comment by vinkla** [comment]
Is this configuration for projects only or for the main app as well?

**Comment by Wachiwi** [comment]
It is an default value for all projects. But you can enable it individually for some projects afterwards.

**Comment by vinkla** [comment]
Okay, I see why its still in the navigation then. Thanks for you feedback!
