### ISSUE TITLE
Encoding::CompatibilityError

### ISSUE THREAD

**Issue by itxx00** [gitlabhq/gitlabhq#8635]
When view source on gitlab page and click "Blame":
address: http://git.local.net/test/project/blame/master/test.java
then 500 error happened "Page can't be loaded because of an encoding error."
error logs in production.log:
```
Encoding::CompatibilityError (incompatible character encodings: UTF-8 and ASCII-8BIT):
  app/views/projects/blame/show.html.haml:48:in `block in _app_views_projects_blame_show_html_haml___2897909565570638113_109173220'
  app/views/projects/blame/show.html.haml:13:in `_app_views_projects_blame_show_html_haml___2897909565570638113_109173220'

```

**Comment by Razer6** [comment]
Fixed with https://gitlab.com/gitlab-org/gitlab-ce/commit/347ce399ab88de6c35a48365e7e8db00ae9aade1
