### ISSUE TITLE
there is an error when i setup gitlab on centOS 6.5

### ISSUE THREAD

**Issue by lizhecome** [gitlabhq/gitlabhq#8636]
[root@localhost ~]# sudo rpm -i gitlab-7.7.0_omnibus.5.4.0.ci-1.el6.x86_64.rpm
error: unpacking of archive failed on file /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-11.12.2/lib/chef/provider/package/yum.rb;54c1dae1: cpio: Digest mismatch

please check，thanks a lot

Conner.

**Comment by Razer6** [comment]
Please head over to the omnibus issue tracker at https://gitlab.com/gitlab-org/omnibus-gitlab /cc @maxlazio
