### ISSUE TITLE
v7.7.0 protected branches -- Error 500

### ISSUE THREAD

**Issue by irobayna** [gitlabhq/gitlabhq#8640]
Upgraded to latest version 7.7.0, I am running on Ubuntu + mysql

I am getting error 500 while trying to access from project `Settings` the menu item `Protected branches`.

If it helps any, this was working on 7.6.x
```
Started GET "/xyz/iws/protected_branches" for 127.0.0.1 at 2015-01-23 09:29:32 -0500
Processing by Projects::ProtectedBranchesController#index as HTML
Parameters: {"project_id"=>"xyz/iws"}
Completed 500 Internal Server Error in 32ms
```
Thanks!

**Comment by DasLampe** [comment]
Running ruby 2.2.0?
Looks like similar to #8647 and #8624.

Downgrade to ruby-2.1.5 should solve this problem.
2.2.0 is not supported by gitlab, yet

**Comment by irobayna** [comment]
@DasLampe I'm using ```ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]```

**Comment by irobayna** [comment]
It was my fault, discovered that the migrations did not fully run (using mysql)
Once I fix the bad migration, restarted and I am good now

Thanks!
