### ISSUE TITLE
Sort Commits per mail in Graph

### ISSUE THREAD

**Issue by t3mux** [gitlabhq/gitlabhq#8646]
Well, i have a simple question. Could you implement that commits can also be sorted per e-mail rather than per name in the commit graphs?

We have more than one developer whose name in the .gitconfig was not correctly set and now the graphs dont show the correct amount per "real" developer.

**Comment by rumpelsepp** [comment]
The most common way to do this is a `.mailmap` file: https://www.kernel.org/pub/software/scm/git/docs/git-shortlog.html#_mapping_authors

But I don't know whether gitlab already honors this file...

**Comment by nexus86** [comment]
No sadly not. I tried it out.

**Comment by marceloboeira** [comment]
It would be even nicer if it could honor the file, I guess it would englobe those "corner-cases".

**Comment by xeor** [comment]
A mailmap file would be perfect.
We have a repo with a bunch of mail-adresses, usernames combos and few "actual" people..
Our "graph" is a little messy, specially since this repo is a couple of years old...

**Comment by kakawait** [comment]
Consider upvote the following feedback to support `.mailmap` http://feedback.gitlab.com/forums/176466-general/suggestions/7320626-enable-git-use-of-mailmap-files-for-mapping-user-i

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
