### ISSUE TITLE
Upgrading from 7.5.3 to 7.7.1 auto re-enables Sign Up

### ISSUE THREAD

**Issue by teepsdonnelly** [gitlabhq/gitlabhq#8648]
Glad I caught this one. We have a private GitLab that we use for all internal projects, however accessible via the web so people can work from home. We had Sign Up disabled for this reason. Upgrading from 7.5.3 to 7.7.1 automatically re-enabled Sign Up and I had to go manually disable it again.

Not sure if this is expcted behavior, but just wanted to let you guys know in case no one has yet.

**Comment by Eijebong** [comment]
Hi,
the default changed in 7.7.0 so yes, it's the expected behaviour.

https://github.com/gitlabhq/gitlabhq/blob/master/CHANGELOG#L91

**Comment by arif-ali** [comment]
I would have thought that this would have been able to change from gitlab.yml to say signup_enabled: false, as shown in the example config file below

https://github.com/gitlabhq/gitlabhq/blob/master/config/gitlab.yml.example#L64

But that still shows the sign up page on the front page

**Comment by arif-ali** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/982, more info here, looks like you will need to go into the settings tab in the Admin page to fix it. I have tested this in the 2 implementations I manage, and this indeed has resolved the problem

**Comment by nneul** [comment]
This bit me as well... options need to be removed from the example config if they are no longer going to have any effect.

**Comment by Razer6** [comment]
Options are now removed.

**Comment by TigerWolf** [comment]
Is the only way to do this automatically to login to the database and change the value? I would like to turn off signup in my automatic deploy script. Create a new issue?

**Comment by kostyrevaa** [comment]
I'd like to know the answer to TigerWolf's question as well.

**Comment by nsu** [comment]
Another +1 for TigerWolf's question. I'd prefer to be able to store as much configuration as possible in files.

**Comment by rocktavious** [comment]
+1 for TigerWolf's questions.  Seems like one should beable to disable signup via initial configuration, for instance, you are implementing ldap auth and there is no need for signup.

**Comment by kojiromike** [comment]
I very much appreciate GitLab. Nevertheless, please support those of us using automated configuration. _Please_ don't require us to manage this setting by writing values directly into the database.

**Comment by gronke** [comment]
Like in the other comments above I'd love to see this options being re-applied. Once set in the `gitlab.rb` not even Administrators should be able to allow registration. There might be good reasons to prohibit external users entirely. IMO signups should be disabled by default too.

**Comment by b4ldr** [comment]
also +1 for having this option in the config
