### ISSUE TITLE
Fail to upgrade and precompile assets

### ISSUE THREAD

**Issue by kylekatarnls** [gitlabhq/gitlabhq#8649]
Hi,

I just upgraded my Gitlab from 7.1 to 7.7 and when came the assets precompile command it failed to find **chart-lib.min**:

    -> bundle exec rake assets:clean assets:precompile
    rake aborted!
    Sprockets::FileNotFound: couldn't find file 'chart-lib.min'
      (in /home/git/gitlab/app/assets/javascripts/application.js.coffee:25)

Someone see why?

**Comment by Razer6** [comment]
Is chart-lib.min on the filesystem? Should be in https://github.com/gitlabhq/gitlabhq/tree/master/vendor/assets/javascripts

**Comment by kylekatarnls** [comment]
No it wasn't. I added it manualy to be able to compile assets. But I suppose it shouldn't be needed.

**Comment by Razer6** [comment]
Then there is something wrong with your installation. This file is part of the repository.

**Comment by kylekatarnls** [comment]
It wasn't present in the 7.1. Are you sure the failure is not in the updater?

**Comment by Razer6** [comment]
On which revision are you? What does a `git show head | grep commit` tell you? Maybe you are not on the correct revision?

**Comment by kylekatarnls** [comment]
I obtain: `ambiguous argument 'head': unknown revision or path not in the working tree.` I search why.

`git status`:

    # HEAD detached at v7.7.1
    # Changes not staged for commit:
    #   (use "git add <file>..." to update what will be committed)
    #   (use "git checkout -- <file>..." to discard changes in working directory)
    #
    #       modified:   vendor/assets/javascripts/chart-lib.min.js
    #       modified:   vendor/assets/javascripts/highlight.pack.js
    #
    # Untracked files:
    #   (use "git add <file>..." to include in what will be committed)
    #
    #       bundle
    #       public/.htaccess
    #       vendor/plugins/

I added manualy chart-lib.min.js but I did nothing with highlight.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
