### ISSUE TITLE
Line width of new theme

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8651]
The new theme which was introduced in gitlab 7.7 has a problem with the line width (especially the help pages). It should be reduced for readability; it is much too broad.

![bildschirmfoto vom 2015-01-25 11 28 25](https://cloud.githubusercontent.com/assets/1961699/5891166/74467bfa-a485-11e4-8215-50ab8ca35d92.png)

**Comment by Wachiwi** [comment]
:+1:

**Comment by Razer6** [comment]
:+1:
