### ISSUE TITLE
User as guest

### ISSUE THREAD

**Issue by exromany** [gitlabhq/gitlabhq#8655]
I want to invite a user to my Specified project. 
But now if I create new user, he will be seeing all my Internal projects, not only Specified project.

So, I wish to have option 'Guest' in user settings, so user will see only those projects in which he is added.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
