### ISSUE TITLE
No more activity log after upgrade to 7.7.1

### ISSUE THREAD

**Issue by huglester** [gitlabhq/gitlabhq#8656]
Hello everyone!

I have upgraded from 7.1.1 to 7.7.1 yesterday, and now I see that if I push updates to different repos, I don't see any activity in 'Activity log'. I see those commits etc.

Is there a way to return it back? 

Thank you!

**Comment by Wachiwi** [comment]
Does [this](https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/7.6-to-7.7.md#things-went-south-revert-to-previous-version-76) help?

**Comment by huglester** [comment]
@Wachiwi you want mi to migrate down to 7.6?

**Comment by Wachiwi** [comment]
Oh I got you wrong. I thought you were looking for downgrade instructions.

**Comment by huglester** [comment]
no worries @Wachiwi  and thank you!

I run the `sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production` once again
and at the top it suggested me:
  sudo chmod u+rwx,g=rx,o-rwx /home/git/gitlab-satellites
and 
  sudo -u git -H "/usr/bin/git" config --global user.name  "GitLab"
  sudo -u git -H "/usr/bin/git" config --global user.email "gitlab@localhost"
  sudo -u git -H "/usr/bin/git" config --global core.autocrlf "input"


after this everything it ok, new messages started to show up!
