### ISSUE TITLE
gitlab-ctl reconfigure fails in docker CentOS 7 container

### ISSUE THREAD

**Issue by orodbhen** [gitlabhq/gitlabhq#8666]
I have a CentOS 7 container with systemd running successfully inside of it, and I want create a gitlab container from it. However, when I try to run gitlab-ctl reconfigure inside the container I get:

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of semodule -i /opt/gitlab/embedded/selinux/rhel/7/gitlab-7.2.0-ssh-keygen.pp ----
    STDOUT: 
    STDERR: semodule: SELinux policy is not managed or store cannot be accessed.
    ---- End output of semodule -i /opt/gitlab/embedded/selinux/rhel/7/gitlab-7.2.0-ssh-keygen.pp ----
    Ran semodule -i /opt/gitlab/embedded/selinux/rhel/7/gitlab-7.2.0-ssh-keygen.pp returned 1

    Resource Declaration:
    ---------------------
    # In /opt/gitlab/embedded/cookbooks/gitlab/recipes/selinux.rb

    20:   execute "semodule -i /opt/gitlab/embedded/selinux/rhel/7/#{ssh_keygen_module}.pp" do
    21:     not_if "semodule -l | grep '^#{ssh_keygen_module}\\s'"
    22:   end
    23: end

Is there a way to disable the selinux check, so this part doesn't run?

**Comment by orodbhen** [comment]
I was able to get past this error by changing /opt/gitlab/embedded/cookbooks/gitlab/recipes/selinux.rb to look like this:

    running_in_container = system ("awk -F'/' 'match($3, /^docker.*/)' /proc/self/cgroup | read")
    if node["platform_family"] == "rhel" && node["platform_version"] =~ /7\./ && running_in_container == false
    ssh_keygen_module = 'gitlab-7.2.0-ssh-keygen'
    execute "semodule -i /opt/gitlab/embedded/selinux/rhel/7/#{ssh_keygen_module}.pp" do
        not_if "semodule -l | grep '^#{ssh_keygen_module}\\s'"
    end
    end

However, now I'm getting this error: 

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '2'
    ---- Begin output of /opt/gitlab/embedded/bin/psql --port 5432 -d template1 -c "CREATE USER gitlab" ----
    STDOUT: 
    STDERR: psql: FATAL:  the database system is starting up
    ---- End output of /opt/gitlab/embedded/bin/psql --port 5432 -d template1 -c "CREATE USER gitlab" ----
    Ran /opt/gitlab/embedded/bin/psql --port 5432 -d template1 -c "CREATE USER gitlab" returned 2

**Comment by stratus-ss** [comment]
I had a similar issue with running in OpenVZ. Thanks for posting this. I did a similar edit disabling when running in openvz.

**Comment by traxanos** [comment]
same problem here, too

**Comment by panticz** [comment]
This may by same issue as this one:
https://gitlab.com/gitlab-org/omnibus-gitlab/issues/552

Try to manually increase kernel shared memory limit and reconfigure / restart GitLab:
```
echo 17179869184 > /proc/sys/kernel/shmmax
gitlab-ctl reconfigure
gitlab-ctl restart
```

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by orodbhen** [comment]
@panticz I already set shmmax higher, and resolved the issues associated with that.

@Razer6 I should note that, although reconfigure works now, I always have to run it twice. It consistently fails the first time. I'm fine with this issue being closed, as I don't have any more time to spend on it right now.

**Comment by Razer6** [comment]
@orodbhen Can you please head over to the omnibus issue tracker?
