### ISSUE TITLE
Merge Request title link bug

### ISSUE THREAD

**Issue by SSPkrolik** [gitlabhq/gitlabhq#8673]
If merge request is titled with a string of the next pattern: "#{id}", the title link leads to the issue with such id, and there's no way to open this merge request from `Merge requests`  page.

1) Such merge request title link

![merge_request_title_bug_1](https://cloud.githubusercontent.com/assets/372353/5939132/d4006412-a709-11e4-9e9d-d7f564ee7f5c.png)

2) ... leads to this:

![merge_request_title_bug_2](https://cloud.githubusercontent.com/assets/372353/5939134/d6891fa8-a709-11e4-8a30-a9486388370e.png)

**Comment by Razer6** [comment]
There is a pending PR for fixing that https://github.com/gitlabhq/gitlabhq/pull/8662

**Comment by SSPkrolik** [comment]
@Razer6 Is it better to close the issue?

**Comment by Razer6** [comment]
PR merged close it here
