### ISSUE TITLE
Task list should work with ordered lists, too

### ISSUE THREAD

**Issue by maliayas** [gitlabhq/gitlabhq#8678]
1. **Summary:** I know, documentation says task lists must be in unordered list but it would be nice to work also with ordered lists.
1. **Steps to reproduce:** Use tasks in an ordered list.
1. **Expected behavior:** Numbers should be displayed for the list and checkbox should work.
1. **Observed behavior** Numbers of the list are not shown and checkbox doesn't actually work.
1. **GitLab version**: 7.7.1

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
