### ISSUE TITLE
Collapsable left nav

### ISSUE THREAD

**Issue by jasonblanchard** [gitlabhq/gitlabhq#8684]
The left nav reduces important screen real estate and makes the UI feel very busy.

I propose adding a permanent  "collapse" button that keeps the left nave collapsed for all viewport sizes.

Thoughts?

**Comment by randx** [comment]
I think its a nice idea. We can use cookies for storing such setting.

**Comment by jasonblanchard** [comment]
Cool, I can work on this if no one else has taken it

**Comment by randx** [comment]
@jasonblanchard cool. Please do

**Comment by jasonblanchard** [comment]
@randx https://github.com/gitlabhq/gitlabhq/pull/8697
