### ISSUE TITLE
signin_enabled: false has no effect on GitLab 7.7.1

### ISSUE THREAD

**Issue by JonathonReinhart** [gitlabhq/gitlabhq#8689]
I'm using GitLab 7.7.1 omnibus, and want to force LDAP sign-in.

I've edited `/etc/gitlab/gitlab.rb` and specified `gitlab_rails['signin_enabled'] = false`, and re-configured. Indeed, I see that `/opt/gitlab/embedded/service/gitlab-rails/config/gitlab.yml` has the line `signin_enabled: false`, as expected.

However, after restarting GitLab (with `gitlab-ctl restart`), I still see the normal sign-in tab on the sign-in page, (along with LDAP sign-in).  I was expecting only the LDAP sign-in tab to be present.

**Comment by thwfreak** [comment]
Same problem with `gitlab_rails['gitlab_signup_enabled'] = false`

**Comment by JonathonReinhart** [comment]
I'm not seeing that. I have signup disabled successfully.

**Comment by thwfreak** [comment]
Hmm... what did you do exactly?
With `gitlab_rails['gitlab_signup_enabled'] = false` there is `signup_enabled: false` in `/var/opt/gitlab/gitlab-rails/etc/gitlab.yml`. Also I reconfigured and restartet with `gitlab-ctl`, but the Signup form is allready in the front page.

**Comment by arif-ali** [comment]
See #8648

You now have to do it from the Admin settings page

**Comment by robertd** [comment]
@arif-ali Thanks!

**Comment by thwfreak** [comment]
@arif-ali Thank you!

**Comment by robertd** [comment]
FYI... in v7.7.2 default option for signup_enabled is false. In current master it's true. L68

**Comment by nneul** [comment]
That option should probably be removed entirely from the config since it doesn't seem to have any effect.

**Comment by JonathonReinhart** [comment]
Yes, I agree. Both "signup" and "signin" have entries in the GUI now.

**Comment by thias** [comment]
+1 : Second time I get bitten by the setting being ignored after an upgrade, and digging through the code without understanding why...
