### ISSUE TITLE
Disable Travis service on GitHub repo

### ISSUE THREAD

**Issue by tsigo** [gitlabhq/gitlabhq#8694]
TravisCI was switched to Semaphore but the service hook is still active on the GitHub repo for GitLab, so it's still trying to build on every pull request. Could an admin please disable the hook?

**Comment by Razer6** [comment]
@dosire Can you do that please?

**Comment by dosire** [comment]
@Razer6 Right now I don't see a hook for travis.

**Comment by tsigo** [comment]
Hmm, apparently it was enabled on my fork. I'm not sure if that would cause it to build for pull requests to the official repo if it's disabled there.

Anyway, I deleted it. Closing this issue for now unless it builds again on my next PR.

**Comment by dosire** [comment]
@tsigo OK, no problem
