### ISSUE TITLE
Support Ruby 2.2

### ISSUE THREAD

**Issue by chulkilee** [gitlabhq/gitlabhq#8696]
This is a placeholder for issues on Ruby 2.2

- 500 when deleting a project: #8621 #8624 #8671
- 500 on admin/groups: #8590 #8685
- 500 when adding key or label: #8567

Common pattern is `undefined method `name' for nil:NilClass`

**Comment by fedir** [comment]
500 on Remove group

**Comment by MOZGIII** [comment]
:+1:

**Comment by Difrex** [comment]
:+1:

**Comment by MOZGIII** [comment]
Maybe just port to Rails 5+ at some point? It requires Ruby 2.2+.

**Comment by Razer6** [comment]
Closing this issue for now.

**Comment by fedir** [comment]
Actual stable Ruby is 2.2.3. Instead of closing the issue, should find the way to make Gitlab compatible with Ruby 2.2.x.

**Comment by Razer6** [comment]
Yes, ruby 2.2.3 is stable but 2.1.6 is stable either ;-) Of course we will update ruby in future, but right now we do not support 2.2. The ruby version requirements are stated in the docs - therefore I closed the issue.

**Comment by fedir** [comment]
On ruby's site, 2.1 is marked as "previous stable".

**Comment by simonzack** [comment]
:+1: Gitlab's the only package using the old ruby on my system.

**Comment by KingCrunch** [comment]
Tbh I am confused. I don't see, that the issue is solved and it is still relevant

**Comment by JobV** [comment]
We're doing this for GitLab 8.5: https://gitlab.com/gitlab-org/gitlab-ce/issues/3340
