### ISSUE TITLE
push troubles

### ISSUE THREAD

**Issue by Sayorus** [gitlabhq/gitlabhq#8703]
I use GitLab Version: 7.6.2

##### bundle exec rake gitlab:env:info RAILS_ENV=production

> System information
> System:
> Current User:   git
> Using RVM:      no
> Ruby Version:   2.0.0p598
> Gem Version:    1.8.30
> Bundler Version:1.7.12
> Rake Version:   10.3.2
> Sidekiq Version:2.17.8
> 
> GitLab information
> Version:        7.6.2
> Revision:       16f0968
> Directory:      /usr/home/git/gitlab
> DB Adapter:     postgresql
> URL:            http://gitlab.domain.com
> HTTP Clone URL: http://gitlab.domain.com/some-project.git
> SSH Clone URL:  git@gitlab.domain.com:some-project.git
> Using LDAP:     no
> Using Omniauth: no
> 
> GitLab Shell
> Version:        2.4.0
> Repositories:   /home/git/repositories/
> Hooks:          /home/git/gitlab-shell/hooks/
> Git:            /usr/local/bin/git

on FreeBSD 10.0-RELEASE #0 r260789

After completing setup I've understood that I'm not able to push anything

##### git push origin master

> Counting objects: 193, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (189/189), done.
> Writing objects: 100% (193/193), 3.31 MiB | 1.10 MiB/s, done.
> Total 193 (delta 11), reused 0 (delta 0)
> remote: GitLab: No such project
> To git@gitlab.domain.com:user/project.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@gitlab.domain.com:user/project.git'

Then I've run gitlab check

##### bundle exec rake gitlab:check RAILS_ENV=production

> Checking Environment ...
> 
> Git configured for git user? ... yes
> 
> Checking Environment ... Finished
> 
> Checking GitLab Shell ...
> 
> GitLab Shell version >= 2.4.0 ? ... OK (2.4.0)
> Repo base directory exists? ... yes
> Repo base directory is a symlink? ... no
> Repo base owned by git:git? ... yes
> Repo base access is drwxrws---? ... yes
> Satellites access is drwxr-x---? ... yes
> hooks directories in repos are links: ... 
> User / Project ... ok
> User / Project ... repository is empty
> User / Project ... repository is empty
> Running /home/git/gitlab-shell/bin/check
> Check GitLab API access: OK
> Check directories and files: 
>         /home/git/repositories/: OK
>         /home/git/.ssh/authorized_keys: OK
> Test redis-cli executable: redis-cli 2.8.19
> Send ping to redis server: PONG
> gitlab-shell self-check successful

> Checking GitLab Shell ... Finished

> Checking Sidekiq ...

> Running? ... no
>   Try fixing it:
>   sudo -u git -H RAILS_ENV=production bin/background_jobs start
>   For more information see:
>   doc/install/installation.md in section "Install Init Script"
>   see log/sidekiq.log for possible errors
>   Please fix the error above and rerun the checks.
> 
> Checking Sidekiq ... Finished
> 
> Checking LDAP ...
> 
> LDAP is disabled in config/gitlab.yml
> 
> Checking LDAP ... Finished
> 
> Checking GitLab ...
> 
> Database config exists? ... yes
> Database is SQLite ... no
> All migrations up? ... yes
> Database contains orphaned GroupMembers? ... no
> GitLab config exists? ... yes
> GitLab config outdated? ... no
> Log directory writable? ... yes
> Tmp directory writable? ... yes
> Init script exists? ... no
>   Try fixing it:
>   Install the init script
>   For more information see:
>   doc/install/installation.md in section "Install Init Script"
>   Please fix the error above and rerun the checks.
> Init script up-to-date? ... can't check because of previous errors
> projects have namespace: ... 
> User / Project ... yes
> User / Project ... yes
> User / Project ... yes
> Projects have satellites? ... 
> User / Project ... yes
> User / Project ... can't create, repository is empty
> User / Project ... can't create, repository is empty
> Redis version >= 2.0.0? ... yes
> Ruby version >= 2.0.0 ? ... yes (2.0.0)
> Your git bin path is "/usr/local/bin/git"
> Git version >= 1.7.10 ? ... yes (2.2.2)

> Checking GitLab ... Finished

I've noticed something weird, **gitlab:sidekiq:check** doesn't seem to detect Sidekiq being active, while it actually is

> root@dev:/home/git/gitlab # cat tmp/pids/sidekiq.pid 
> 57165
> root@dev:/home/git/gitlab # ps ax | grep 57165
> 57165  -  Ss       0:22.12 ruby20: sidekiq 2.17.8 gitlab [0 of 25 busy] (ruby20)

I've decided to try to run it manually

##### bundle exec rake sidekiq:start --trace

> rake aborted!
> LoadError: cannot load such file -- coveralls/rake/task
> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'

> /usr/home/git/gitlab/lib/tasks/test.rake:9:in `< top (required)>'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `block in load'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/railties-4.1.1/lib/rails/engine.rb:654:in `block in run_tasks_blocks'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/railties-4.1.1/lib/rails/engine.rb:654:in `each'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/railties-4.1.1/lib/rails/engine.rb:654:in `run_tasks_blocks'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/railties-4.1.1/lib/rails/application.rb:362:in `run_tasks_blocks'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/railties-4.1.1/lib/rails/engine.rb:449:in `load_tasks'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `public_send'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `method_missing'

> /usr/home/git/gitlab/Rakefile:7:in `< top (required)>'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load_rakefile'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/application.rb:687:in `raw_load_rakefile'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/application.rb:94:in `block in load_rakefile'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/application.rb:93:in `load_rakefile'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/application.rb:77:in `block in run'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/gems/rake-10.3.2/bin/rake:33:in `< top (required)>'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/bin/rake:23:in `load'

> /usr/home/git/gitlab/vendor/bundle/ruby/2.0/bin/rake:23:in `< main>'

Could somebody help me?

**Comment by Razer6** [comment]
It seems you're not invoking the sidekiq script in production mode.

**Comment by Sayorus** [comment]
I'm sorry but what you mean???
Because i trying to run
**bundle exec rake sidekiq:start RAILS_ENV=production**
but in logs I see
> 2015-02-09T10:19:59Z 8770 TID-7wg5hik INFO: Shutting down
> 2015-02-09T10:20:00Z 8770 TID-7xph33c INFO: Shutting down 25 quiet workers
> Sidekiq shut down gracefully.
> 2015-02-09T10:20:12Z 8812 TID-7wg5hik INFO: Booting Sidekiq 2.17.8 with redis options {:url=>"unix:/usr/local/var/run/redis/redis.sock", :namespace=>"resque:gitlab"}
> 2015-02-09T10:20:12Z 8812 TID-7wg5hik INFO: Running in ruby 2.0.0p598 (2014-11-13 revision 48408) [amd64-freebsd10]
> 2015-02-09T10:20:12Z 8812 TID-7wg5hik INFO: See LICENSE and the LGPL-3.0 for licensing details.

**Comment by ex-troll** [comment]
**+1** for this Issue. This is true story about sidekiq..
I have identical problem.

>FreeBSD 10.1-RELEASE
>GitLab v7.7.2

Web face work very well.
I can create and pull repos. But i can't to push.

**Comment by ex-troll** [comment]
This bug **specified for FreeBSD**.
Edit configs *gitlab/config/gitlab.yml* and *gitlab-shell/config.yml*. Replace **/home** to **/usr/home**, because **/home is a symlink**..

**Comment by ex-troll** [comment]
I think you can close this issue.

**Comment by Sayorus** [comment]
Thanks all))

**Comment by marcoleung** [comment]
Thanks all ^^

**Comment by DavidVentura** [comment]
I had this issue today, and this solved it ( /home/ was a symlink) thanks for pointing it out

**Comment by jhollowayj** [comment]
+1 on FreeBSD!  Thanks.  :D
