### ISSUE TITLE
Incorrect ruby environment

### ISSUE THREAD

**Issue by vbezruchkin** [gitlabhq/gitlabhq#8707]
Hey guys,

I have the following problem. I suppose it's more related to RVM rather than gitlab. Anyhow, I'd better ask here in case anyone else used to have similar problem.

```sh
intellia@XXX.com [~]# sudo -u git -H /home/git/gitlab-shell/bin/check
[sudo] password for intellia:
/usr/bin/env: ruby: No such file or directory
```
This path is used in gitlab-shell files, and when I changed the path in each of the files in /home/git/gitlab-shell/bin to absolute paths everything worked fine:

```sh
intellia@XXX.com [~]# sudo -u git -H /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
        /home/git/repositories: OK
        /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.4.10
Send ping to redis server: PONG
```

I don't like this solution and I'm absolutely sure it's not a way to go :)
So if you know how to make system see env ruby this I would really appreciate your advice.

Thanks in advance.

**Comment by vbezruchkin** [comment]
Here is more information on this:
```sh
intellia@XXX.com [~]# sudo -u git -H ruby -v
sudo: ruby: command not found
intellia@XXX.com [~]# sudo su -c 'printenv PATH' git
/sbin:/bin:/usr/sbin:/usr/bin
intellia@XXX.com [~]# sudo su -l git -c 'printenv PATH'
/home/git/.rvm/gems/ruby-2.1.5/bin:/home/git/.rvm/gems/ruby-2.1.5@global/bin:/home/git/.rvm/rubies/ruby-2.1.5/bin:/usr/local/jdk/bin:/usr/local/rvm/gems/ruby-1.9.3-p547/bin:/usr/local/rvm/gems/ruby-1.9.3-p547@global/bin:/usr/local/rvm/rubies/ruby-1.9.3-p547/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/usr/src/git/bin:/home/git/.rvm/bin:/home/git/bin
```

I suspect it's all about incorrect path var for my account. Sorry for asking, what would be the best way to fix this. 

Thanks!

**Comment by Razer6** [comment]
GitLab does not support RVM which is stated in the installation documentation.

**Comment by vbezruchkin** [comment]
Hi,
Yep it was posted long ago and I managed to install GitLab with RVM. It's working fine for me, so no worries. There is one problem though - I need to change hooks manually and use absolute path to ruby version binary every time I update the package.

Thanks for the great software!
