### ISSUE TITLE
Update from 6.0.0 to 7.6.2, Merge Requests showing error 500

### ISSUE THREAD

**Issue by chrislapa** [gitlabhq/gitlabhq#8717]
Hi,

I just updated our Bitnami Gitlab installation from v6.0.0 to v7.6.2. I did this by restoring a backup of our v6.0.0 stack to a newly installed v7.6.2 stack. I followed this (guide)[https://wiki.bitnami.com/Applications/BitNami_GitLab#How_to_upgrade_Gitlab.3f].

Its mostly worked. However when we try view some old merge requests Gitlab will fail to display with a 500 error.

I checked the production.log and its showing this error for one of the broken merge requests:
```
Started GET "/**removed**/**removed**/merge_requests/99" for 172.28.67.70 at 2015-02-03 16:45:21 +1100
Processing by Projects::MergeRequestsController#show as HTML
  Parameters: {"project_id"=>"**removed**/**removed**", "id"=>"99"}
Completed 500 Internal Server Error in 214ms

ActionView::Template::Error (undefined method `short_id' for nil:NilClass):
     8:     %div
     9:       = link_to_member(@project, note.author, avatar: false)
    10:       started a discussion on commit
    11:       = link_to(note.noteable.short_id, project_commit_path(note.project, note.noteable), class: 'monospace')
    12:     .last-update.hide.js-toggle-content
    13:       - last_note = discussion_notes.last
    14:       last updated by
  app/views/projects/notes/discussions/_commit.html.haml:11:in `_app_views_projects_notes_discussions__commit_html_haml__2845132147773347950_70011764747100'
  app/views/projects/notes/_discussion.html.haml:13:in `_app_views_projects_notes__discussion_html_haml__4139911571170084056_70011764545480'
  app/views/projects/notes/_notes.html.haml:7:in `block in _app_views_projects_notes__notes_html_haml__3180357081038837234_70011764373560'
  app/views/projects/notes/_notes.html.haml:2:in `each'
  app/views/projects/notes/_notes.html.haml:2:in `_app_views_projects_notes__notes_html_haml__3180357081038837234_70011764373560'
  app/views/projects/notes/_notes_with_form.html.haml:2:in `_app_views_projects_notes__notes_with_form_html_haml__1836016726415457532_70011764235460'
  app/views/projects/merge_requests/_show.html.haml:33:in `_app_views_projects_merge_requests__show_html_haml__1144872974554681124_70011765318520'
  app/views/projects/merge_requests/show.html.haml:1:in `_app_views_projects_merge_requests_show_html_haml__3128752638493311084_70011765271720'
  app/controllers/projects/merge_requests_controller.rb:30:in `show'
```

I've looked in the mysql database and I can see in the merge_requests table theres an entry with iid 99 with the correct title and other info. I'm happy to post more info, I'm just not sure what at this point in time :/

Thanks,
Chris

**Comment by akzhan** [comment]
Dup of #8732 (sulution in comment - migrate iids).

**Comment by chrislapa** [comment]
@akzhan Its not a duplicate of #8732. Whilst it is the same problem, the error in the production log is different. I have followed the update procedure, hence I have already ran:
```bundle install --without development test postgres --deployment
bundle exec rake db:migrate RAILS_ENV=production
bundle exec rake migrate_iids RAILS_ENV=production
bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=production```

I also ran the checker to find any problems: 
```bundle exec rake gitlab:check RAILS_ENV=production
```
However it returned fine.

Will it hurt to try run the migrate_iids step again?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
