### ISSUE TITLE
[Proposal] Merge Request redesign

### ISSUE THREAD

**Issue by jvanbaarsen** [gitlabhq/gitlabhq#8727]
Since the new redesign some elements on the MergeRequest page feels a little disconnected.
I tried to clean this up a little with the following proposal:

**Proposal one:**
![screenshot 2015-02-03 19 00 05](https://cloud.githubusercontent.com/assets/1362793/6025992/1818818a-abd7-11e4-923d-d9938b855cd0.png)

**Proposal two:**
![screenshot 2015-02-03 20 02 03](https://cloud.githubusercontent.com/assets/1362793/6027052/97da4c84-abdf-11e4-99b8-d55549696080.png)

When doing it this way we have all the room we need for the diff to be shown, since the right sidebar will be gone when on the Commits or Change page. We also have the option to have that menu scroll with the discussion, so you always have the commands at your fingertips to assign the MR or select a milestone.

Looking forward in hearing your ideas on this!

---

So far ([last comment count](https://github.com/gitlabhq/gitlabhq/issues/8727#issuecomment-74890509)): 

Proposal | Votes 
----|-----
1st | 5
2nd | 6

**Comment by jubianchi** [comment]
:+1: for the first proposal!

I would just have moved the "from `source` into `dest`" message under the MR title to keep it visible on all tabs.

**Comment by Wachiwi** [comment]
:+1:  for the second one

**Comment by Mandragora2** [comment]
:+1: for the 1st proposal

**Comment by boeserwolf91** [comment]
I prefer the second proposal. I just miss the "from branch into branch" message.

**Comment by duduribeiro** [comment]
:+1:  the 2nd proposal.. But like @boeserwolf91 said, it's missing the `from branch into branch` message.

**Comment by sashkab** [comment]
:+1 for second

**Comment by busuttil** [comment]
for the first proposal!

**Comment by bGaetan** [comment]
:+1: for the 1st proposal

**Comment by esion** [comment]
+1 for 1st proposal

less scroll when reviewing would be better

**Comment by fpgentil** [comment]
:+1: for the 2nd proposal

**Comment by Soullivaneuh** [comment]
:+1: for the second proposal

**Comment by dosire** [comment]
I think the accept button should always be visible, so 2nd is better than 1st.

**Comment by jvanbaarsen** [comment]
@dosire in the second the accept button will disappear when you scroll down. What about moving that to the sidebar as well?

**Comment by dosire** [comment]
@jvanbaarsen that could get pretty crowded since there is a lot of information associated with the button. I'm not sure about a solution

**Comment by jvanbaarsen** [comment]
What if we make the assignee and milestone not a direct dropdown, but jsut a text and when you click on it it will becomes the dropdown? And also maybe move the voting bar?

**Comment by randx** [comment]
@jvanbaarsen thank you for your proposal. If you dont mind I will bring some criticism to this thread: 

Proposal number 1 

* does not allow you to accept merge request without going to discussion tab
* makes description almost unnoticable and disconnected from title 

Proposal number 2 

* makes impossible affix sidebar with assignee and milestone
* does not work if you dont have a description in merge request

**Comment by Razer6** [comment]
Generally, in both proposals, I find the MR description is a bit lost within the white. There is no separation of the description to other content.

**Comment by randx** [comment]
@jvanbaarsen what can work is actually moving accept MR widget to discussion block:

### OLD

![widget1](https://cloud.githubusercontent.com/assets/305940/6681606/ac5a6cfe-cc26-11e4-9ba5-5fd631dc7f1e.png)

### NEW

![widget2](https://cloud.githubusercontent.com/assets/305940/6681607/ac5be1ce-cc26-11e4-9a50-4fca4c5f1290.png)

### NEW with description

![widget3](https://cloud.githubusercontent.com/assets/305940/6681605/ac58f6f8-cc26-11e4-9a28-936ca0ce50ad.png)



It looks cleaner for me but has disadvantage: it does not allow you to accept merge request without going to discussion tab.

**Comment by boeserwolf91** [comment]
I don't like this. First the assignee and milestone should be related to the headline and description. This way it feels like it's a little unrelated. Therefore it should be in the right of the description to my mind. 
Second the accept button should be accessible from all three tabs. Often I accept MRs from the "changes" tab.

----

I still prefer the second proposel from @jvanbaarsen. For me it's nearly perfect. It just misses the "from branch into branch" message.

**Comment by jvanbaarsen** [comment]
@randx That does already lookbetter

**Comment by randx** [comment]
@jvanbaarsen ok we can try it for 7.10 to see if it will work.

**Comment by jvanbaarsen** [comment]
@randx Yes, but first moment I have time would porbably be thursday. I'll try to finish it earlier.

**Comment by randx** [comment]
@jvanbaarsen i am not in hurry. We are busy with 7.9 release :smile:

**Comment by jvanbaarsen** [comment]
@randx Ah yeah, I think I was one release ahead already xD haha

**Comment by Razer6** [comment]
@jvanbaarsen Can this be closed?

**Comment by jvanbaarsen** [comment]
@Razer6 Yeah I think so
