### ISSUE TITLE
Commits attributed to the wrong user on events page (and in events table)

### ISSUE THREAD

**Issue by emergentcypher** [gitlabhq/gitlabhq#8728]
We upgraded from Gitlab 6 -> 7 and imported our old users and projects.

Now for some reason, two of our user accounts have somehow gotten mismatched.

When userA commits, the events log (dashboard) shows userB having made the commit.

When userB commits, the events log (dashboard) shows userA having made the commit.

Viewing the commit itself, or viewing `git log`, shows that the name and e-mail associated with the commit is correct. We each have the correct emails and SSH keys associated with our users in the gitlab admin (and in the postgres database). But for some reason the wrong user_id and username are going into the events table.

**Comment by k4k** [comment]
Hi, I just wanted to chime in that we're seeing a very similar behavior. Commits are being attributed to the wrong user on the Project's "Activity" tab. If you click on the commit, however, it shows up as the correct user. I have two users, UserA and UserB. In my case, however, UserA has his commits showing correctly in the "Activity" tab, but UserB's commits are also showing up as having been from UserA. This is only in the "Activity" tab, however. The commits themselves still show as being from the correct user if I click on the commit hash.

**Comment by k4k** [comment]
A follow-up to my previous comment. We were able to resolve this issue by removing the key under the affected user's profile, generating a completely new key on his workstation and uploading the corresponding new public key to Gitlab. Hope this helps!

**Comment by emergentcypher** [comment]
Thanks! I can confirm that this (removing all keys, generating a new one, adding it to my user) fixes the problem for us.

**Comment by Razer6** [comment]
Closing as fix is provided.
