### ISSUE TITLE
application.js is taking too much time

### ISSUE THREAD

**Issue by ivancp** [gitlabhq/gitlabhq#8729]
Hello,
I have installed gitlab_7.7.2-omnibus.5.4.2.ci-1_amd64.deb and one file is taking too much time to respond and when I hit [ESC] on browser all page appears instantly

This is the file:
http://localhost:8080/assets/application-5f3c67da81199dd3da676a30746cf17f.js

Note: I disabled the nginx

**Comment by Emirii** [comment]
I'm having the same problem. I have upgraded my gitlab from 7.3->7.4->7.5->7.7 since original installation, non omnibus version. Only now today when I upgraded to 7.7 do I have this problem. Pretty much everything I have is default aside from using port 8081.

http://67.79.239.166:8081/assets/application-d00afb4f3f811f9e780adbb12691482a.js (public for you to see)
"The connection was reset"

Nothing in NGINX error log. 

all tests pass in gitlab check.

My gitlab production.log is filled with this, which may or may not be useless.
```
Started GET "/assets/application-d04c1b1d332c4b1b80714e6e5828f12b.css" for 67.79.239.166 at 2015-02-05 14:33:28 -0600
Started GET "/assets/print-05b72ab1cf0c8441d4dca5bf6e17d26f.css" for 67.79.239.166 at 2015-02-05 14:33:28 -0600
Started GET "/assets/application-d00afb4f3f811f9e780adbb12691482a.js" for 67.79.239.166 at 2015-02-05 14:33:28 -0600
Started GET "/explore/projects" for 67.79.239.166 at 2015-02-05 14:38:13 -0600
Processing by Explore::ProjectsController#index as HTML
Completed 200 OK in 2066ms (Views: 1999.2ms | ActiveRecord: 10.6ms)
Started GET "/assets/application-d04c1b1d332c4b1b80714e6e5828f12b.css" for 67.79.239.166 at 2015-02-05 14:38:16 -0600
Started GET "/assets/print-05b72ab1cf0c8441d4dca5bf6e17d26f.css" for 67.79.239.166 at 2015-02-05 14:38:16 -0600
Started GET "/assets/application-d00afb4f3f811f9e780adbb12691482a.js" for 67.79.239.166 at 2015-02-05 14:38:16 -0600
Started GET "/assets/" for 67.79.239.166 at 2015-02-05 14:38:38 -0600
Processing by NamespacesController#show as HTML
  Parameters: {"id"=>"assets"}
Completed 404 Not Found in 39ms (Views: 4.1ms | ActiveRecord: 2.2ms)
Started GET "/static.css" for 67.79.239.166 at 2015-02-05 14:38:38 -0600
Processing by NamespacesController#show as HTML
  Parameters: {"id"=>"static.css"}
Completed 404 Not Found in 5ms (Views: 0.5ms | ActiveRecord: 0.6ms)
Started GET "/assets/application-d00afb4f3f811f9e780adbb12691482a.js" for 67.79.239.166 at 2015-02-05 14:38:47 -0600
Started GET "/assets/application-d00afb4f3f811f9e780adbb12691482a.js" for 67.79.239.166 at 2015-02-05 14:41:17 -0600
Started GET "/assets/application-d00afb4f3f811f9e780adbb12691482a.js" for 67.79.239.166 at 2015-02-05 14:41:42 -0600
Started GET "/assets/application-d00afb4f3f811f9e780adbb12691482a.js" for 67.79.239.166 at 2015-02-05 14:43:45 -0600
Started GET "/assets/application-d00afb4f3f811f9e780adbb12691482a.js" for 67.79.239.166 at 2015-02-05 14:43:56 -0600
Started GET "//api/v3/internal/check" for 67.79.239.166 at 2015-02-05 14:47:01 -0600
Started GET "/" for 67.79.239.166 at 2015-02-05 14:47:29 -0600
Processing by DashboardController#show as HTML
Completed 200 OK in 196ms (Views: 122.0ms | ActiveRecord: 15.4ms)
Started GET "/assets/print-05b72ab1cf0c8441d4dca5bf6e17d26f.css" for 67.79.239.166 at 2015-02-05 14:47:30 -0600
Started GET "/assets/application-d04c1b1d332c4b1b80714e6e5828f12b.css" for 67.79.239.166 at 2015-02-05 14:47:30 -0600
Started GET "/assets/application-d00afb4f3f811f9e780adbb12691482a.js" for 67.79.239.166 at 2015-02-05 14:47:30 -0600
```

**Comment by Emirii** [comment]
I've fixed it (it bugged me enough) It is a configuration issue:

1. Refollow steps for nginx configuration here: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md#7-nginx (the file must be in sites-enabled, NOT just sites-available)
2. Restart nginx FIRST, then gitlab. If you get a port in use error when starting gitlab, change the port in unicorn.rb to something else other than what you want to access gitlab through nginx. (i was apparently bypassing nginx and just using the unicorn webserver on 8080)
3. Remove assets folder in /home/git/gitlab/public and then recompile with these command:
```
sudo -u git -H bundle exec rake assets:clean RAILS_ENV=production
sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production RAILS_RELATIVE_URL_ROOT=/gitlab
sudo -u git -H bundle exec rake cache:clear RAILS_ENV=production
```
if your icons dont appear after re-run 2nd command without the RAILS_RELATIVE_URL_ROOT=/gitlab

**Comment by Razer6** [comment]
Closing as fix is provided.

**Comment by anjain** [comment]
i have the same problem with MERN stack using reactjs
