### ISSUE TITLE
Showing Overflow

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#8734]
**Information:**
Whenever you expand setting in a certain project, then you press the `<` to hide the text. For some reasons it display this scroll on the right side of the icons.

**ScreenShots:**
![image](https://cloud.githubusercontent.com/assets/4362134/6041949/c9879a84-acbb-11e4-80e6-a5b9cde43125.png)

**Comment by duduribeiro** [comment]
What version are u using?

At `master`, mine worked fine.. 

Thanks =D
[]'s

![image](http://i.imgur.com/aTRClfq.png)

**Comment by MrKeiKun** [comment]
@duduribeiro 

that looks outdated

**Comment by duduribeiro** [comment]
@MrKeiKun, now I see.. 

![error](http://i.imgur.com/ALo32EX.png)

**Comment by duduribeiro** [comment]
Maybe changing the item padding (red mark) from `10px 15px` to `8px 10px` and the top from the sidebar (blue mark) from `45px` to `28px` resolve this problem

before:
![before](http://i.imgur.com/FIFaGVV.png)
after:
![after](http://i.imgur.com/O2O914Z.png)

**Comment by duduribeiro** [comment]
I proposed a pull request: https://github.com/gitlabhq/gitlabhq/pull/8747
Maybe the team can approve it =)

thanks
[]'s
