### ISSUE TITLE
make gitlab users ssh public keys visible in the UI, for everyone

### ISSUE THREAD

**Issue by ssbarnea** [gitlabhq/gitlabhq#8736]
Please make the registered public keys of the users visible in the UI of gitlab. I think this used to be visible but was removed at some point.

Here is the use case: we are using gitlab to exchange ssh keys, so when you want to give access to a user to a specific machine, you know where to get his key from. 

Now this is possible only via API which makes the entire process to complex. 

Public keys are supposed to be public, so please make them public.

**Comment by Wachiwi** [comment]
The  Gitlab team does not use the github issue tracker for feature requests. They have a specific [feature request forum](https://feedback.gitlab.com) for this purpose. Please post your idea there and post the link of your submited idea here so others can vote for it.

**Comment by ssbarnea** [comment]
Are you aware about the fact that the link to https://feedback.gitlab.com/ doesn't work due to SSL certificate mismatch?!

**Comment by Wachiwi** [comment]
yeah but i prefer https instead of http links.

**Comment by ssbarnea** [comment]
An https server with bad certificates is worse than an unsecured http one
and with newer browsers almost impossible to access.

**Comment by dosire** [comment]
@ssbarnea This is because it is hosted on UserVoice. Did you type the url yourself or was it linked somewhere?

**Comment by Wachiwi** [comment]
@dosire  I linked it in my post above

**Comment by ssbarnea** [comment]
Are these screenshots relevant for you? I am sure that 99% of people trying to go to this URL will have the same bad experience.

https://www.dropbox.com/s/02i64sp07jl86m6/Screenshot%202015-02-06%2017.50.06.png?dl=0
https://www.dropbox.com/s/ahkkyf45aj2prgu/Screenshot%202015-02-06%2017.50.37.png?dl=0

**Comment by dosire** [comment]
@Wachiwi can you change the link to http:// ?

**Comment by Wachiwi** [comment]
Done

**Comment by dosire** [comment]
@Wachiwi Thanks!

**Comment by ssbarnea** [comment]
Added as a feature request http://feedback.gitlab.com/forums/176466-general/suggestions/9053494-make-user-public-keys-visible-on-their-gitlab-prof
