### ISSUE TITLE
Left nav tooltips for small viewports

### ISSUE THREAD

**Issue by fbrennen** [gitlabhq/gitlabhq#8738]
With the new UI, certain viewport sizes force the collapse of the left nav, especially on smaller screens. In such cases it's not possible to tell which button is which if you don't already know what the icons mean. It would be really nice to add tooltips to these to tell them apart. It would be even nicer to make those tooltips in the same style as those used in the top nav.

![image](https://cloud.githubusercontent.com/assets/7421357/6063635/b0e34bbe-ad50-11e4-9e24-23ff77b5c02f.png)

**Comment by Razer6** [comment]
Fixed in on master
