### ISSUE TITLE
Network graph shows incorrect merge history when merge parent timestamps are later than merge

### ISSUE THREAD

**Issue by Hooksie** [gitlabhq/gitlabhq#8744]
When a merge commit is performed that references a merge parent with a timestamp that is later than the merge commit itself, the network graph displays that the merge parent is the **latest commit on the parents branch that occurs before the merge commit**, which is incorrect.

This can occur when a client has a system clock set in the future, relative to the Gitlab server, and a commit is made to a branch shortly before it is merged in (either through a merge request or by another user) AND when the source branch still exists at the last commit in the branch.

Incorrect behavior: The network graph marks 49945e4 as one of 19eda68's parents.

Example:
![gitlabnetwork](https://cloud.githubusercontent.com/assets/1211530/6083956/d12f7fa0-adfa-11e4-8959-c8f44ddd5608.png)

> commit 19eda6824321d5dbf1d75e52fa1943850d34ae93
> Merge: 16ca233 660c6db
>  Author: ***
>  Date:   Thu Feb 5 18:12:26 2015 -0500
> ...

> commit 660c6db94e234d7f3f3f786fc24103029984ee9f
> Author: ***
> Date:   Thu Feb 5 18:14:38 2015 -0500
> ...

> commit 49945e44f26b8dc270f287b162e59519b48cadc5
> Author: ***
> Date:   Thu Feb 5 18:09:51 2015 -0500
> ...

Proper behavior: The merge arrow from branch `b1` should occur *after* 660c6db.

You can recreate this problem in a fresh repository by:

1. `git init`
2. `touch file1; git add -A; git commit -m "Initial commit"`
3. `git checkout -b branch1`
4. `touch file2; git add -A; git commit -m "Commit on branch1"`
5. `touch file3; git add -A; git commit -m "Incorrect system time commit"`
6.  ``GIT_COMMITTER_DATE="$((`git log -1 --pretty=format:%at\` + 3600))" git commit --amend --no-edit --date="$((`git log -1 --pretty=format:%at` + 3600))"`` (Alter the previous commit to occur one hour in the future)
7. `git checkout master`
8. `touch file4; git add -A; git commit -m "Correct system time commit"` 
9. `git merge branch1`
10. Add your Gitlab remotes and push master, THEN push branch1.  Notice that after pushing master the network graph is correct, but **after pushing branch1** the network graph is incorrect, as below:

After pushing master (*correct*):
![image](https://cloud.githubusercontent.com/assets/1211530/6084917/632a8758-ae03-11e4-99ed-11f45c054d8e.png)

After pushing branch1 (*incorrect*):
![image](https://cloud.githubusercontent.com/assets/1211530/6084898/29d0a94c-ae03-11e4-902e-9b8fdbe8be27.png)

Found on 7.7.1.

**Comment by Hooksie** [comment]
It's probably worth noting that `git gui` visualizes this properly.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
