### ISSUE TITLE
Task List in Wiki markdown

### ISSUE THREAD

**Issue by cjbrowne** [gitlabhq/gitlabhq#8745]
It seems one cannot use the task list syntax for a wiki page.  This is a bit unfortunate, as it'd be quite good to add them to, for example, our Roadmap page.  We're also using a wiki page to outline what steps need to be taken before we can begin development on the project, again task lists would be useful there.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
