### ISSUE TITLE
GitLab 7.7, manually change settings.

### ISSUE THREAD

**Issue by BnMcG** [gitlabhq/gitlabhq#8746]
I just upgraded to 7.7, and was playing with the new settings in the admin panel - I unfortunately disabled sign in, logged out, and cannot sign back in to change the setting back to enable sign in.

Is it possible to manually change this setting in 7.7? I tried adding it to gitlab.rb and reconfiguring + restarting but it didn't change any settings. 

Is there a way to manually change this setting back, or otherwise login?

**Comment by Razer6** [comment]
This can be changed in the database AFAIK. Closing this as a duplicate of #9103
