### ISSUE TITLE
Mentions being parsed inside code tags

### ISSUE THREAD

**Issue by cvsguimaraes** [gitlabhq/gitlabhq#8764]
I've got wrong mentions when updating an issue with some hex colors in the description.
For exemple color `#9AA` generated a mention to issue `9`. 

The color were inside markdown "code tag" \` so I'd personally think this is a bug. Probably happens with code blocks \`\`\` and `@` mentions as well.

**Comment by Razer6** [comment]
This happens with @-mentions also. Live at https://gitlab.com/gitlab-org/gitlab-ce/issues/1109 The user `@gitlab.com` is parsed.

Probably when switching to html-pipeline this gets fixed.

**Comment by stanhu** [comment]
I have a merge request for this:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/365

**Comment by Razer6** [comment]
MR merged, close this one
