### ISSUE TITLE
Upgrade to 7.7 limits Milestone issue filter functionality

### ISSUE THREAD

**Issue by timmyjimi** [gitlabhq/gitlabhq#8765]
Once I select a Milestone filter on the Issue list, I can’t select a different Milestone until I revert back to an “all” view.

**Comment by Razer6** [comment]
Closing as a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/1035

**Comment by timmyjimi** [comment]
Thanks, but that link doesn't work for me.

**Comment by Razer6** [comment]
@timmyjimi How does this link not work?

**Comment by timmyjimi** [comment]
"This webpage is not available"

**Comment by Razer6** [comment]
That is strange. Can you access https://gitlab.com /cc @dosire

**Comment by dosire** [comment]
@Razer6 Thanks for the ping but I don't know what to do here.

**Comment by timmyjimi** [comment]
No luck.
