### ISSUE TITLE
relative_url_root not working for project issues

### ISSUE THREAD

**Issue by recursive-madman** [gitlabhq/gitlabhq#8767]
I have `relative_url_root` set to `"/gitlab"`.

Now in the sidebar on `/gitlab/<group>/<project>` all links have the proper prefix, **except** for the "Issues" link, which is missing the prefix.

**Comment by recursive-madman** [comment]
This is what I use locally now to fix the problem:

```diff
diff --git a/app/models/project_services/gitlab_issue_tracker_service.rb b/app/models/project_services/gitlab_issue_tracker_service.rb
index 25e3998..ee860c4 100644
--- a/app/models/project_services/gitlab_issue_tracker_service.rb
+++ b/app/models/project_services/gitlab_issue_tracker_service.rb
@@ -26,11 +26,11 @@ class GitlabIssueTrackerService < IssueTrackerService
   end
 
   def project_url
-    project_issues_path(project)
+    "#{Gitlab.config.gitlab.relative_url_root}#{project_issues_path(project)}"
   end
 
   def new_issue_url
-    new_project_issue_path project_id: project
+    "#{Gitlab.config.gitlab.relative_url_root}#{new_project_issue_path project_id: project}"
   end
 
   def issue_url(iid)
```

**Comment by DouweM** [comment]
@recursive-madman Good catch! Could you post a pull request? Please use `Gitlab.config.gitlab.url` to be in line with `#issue_url`.

**Comment by dosire** [comment]
So the url would be something like URI::join(Gitlab.config.gitlab.url, project_issues_path(project))

**Comment by dosire** [comment]
Fixed in https://github.com/gitlabhq/gitlabhq/commit/c2788e4aa9444e7c1c91475050751ab987de64ee
