### ISSUE TITLE
Remember side-by-side diff choice

### ISSUE THREAD

**Issue by Grokzen** [gitlabhq/gitlabhq#8777]
Right now when i want to review code i have to choose side-by-side diff each time i open a Merge Request because that choice is not stored/saved anywhere.

Either store my last choice/change of viewer globally somewhere and use it on all diff views from that point on. Or let me have a config option on my account where i can specify my preferred choice.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
