### ISSUE TITLE
Specs failing when changing a model

### ISSUE THREAD

**Issue by jvanbaarsen** [gitlabhq/gitlabhq#8781]
When I run a spec file for the first time the results are green, when I then change something in a arbitrary model and rerun the specs they are red. When I then run `$ spring stop` and rerun the same spec its green again.

**Steps to reproduce**

1. `$ spring stop` Make sure spring is stopped
1. `$ rspec spec/requests/api/merge_requests_spec.rb` Run the spec
1. Comment out line `543` in `models/user.rb` (`notification_service.new_user(self, @reset_token)`
1. `$ rspec spec/requests/api/merge_requests_spec.rb` Run the spec again
1. You now get a lot of failing tests, with the main error being: 

  ```
Failure/Error: let(:user) { create(:user) }
     LoadError:
       Unable to autoload constant Gitlab::Popen, expected /Users/jeroen/Development/gitlab-development-kit/gitlab/lib/gitlab/popen.rb to define it
  ```
1. `$ spring stop` Stop Spring again
1. `$ spec spec/requests/api/merge_requests_spec.rb` Tests are green again

/cc @randx / @maxlazio

**Comment by jvanbaarsen** [comment]
It seems that setting `config.cache_classes` in `environment/test.rb` to false fixes the issue. Currently running the full test suite to see if that messes anything else up.

**Comment by Razer6** [comment]
Closing because PR merged

**Comment by jvanbaarsen** [comment]
@Razer6 Thanks!
