### ISSUE TITLE
Email notification for own comments

### ISSUE THREAD

**Issue by oscx** [gitlabhq/gitlabhq#8807]
Working around some gitlab search limitations, most of our gitlab team members search their email notifications for quickly finding information from issues/comments by keywords.

However, this notification is not 100% complete since it's usually missing the user's own comments. 

How can we enable email notifications for comments written by others but also by ourself, to finally collect them all in the email inbox?

Thanks for a tip how to use this.

**Comment by mathstuf** [comment]
+1 I'd really like this as well.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
