### ISSUE TITLE
Gitlab Issue Management: Project vs. Team Management

### ISSUE THREAD

**Issue by oscx** [gitlabhq/gitlabhq#8808]
We appreciate all the simplifications (in a positive way) and advantage of gitlab's issue management.

Regarding project and (large) team management, the team "leader" has some limitation. He only can check each team member's tasks per project and doesn't have _one_ overall overview per user.

E.g. for checking the current tasks with a team size of 10 members and 50 projects, it's necessary to step in each single project, e.g. for checking the current tasks and load of team team members, the "master" is required to check 50 projects, one-by-one to find out the 10 people's current tasks in progress/queue/completed which is pretty inefficient.

That's why we currently workaround with a very ugly DB query to get a full list of tasks, sorted by team memers, building the deeplink to the issues in sql, appending labels for priority in the sql output. 

This works for short-term and saves us lots of time. (as long as alternative is checking 50 projects manually)

Is there another approach or implementation which allows cross-user overviews at least for admins? 

Btw. I think that that's still one of the reasons why some teams prefer jira/redmine integration in gitlab although gitlab's own issue management is very advanced, too. only missing few powerful and necessary features like the project and team manager overview...

**Comment by Wachiwi** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
