### ISSUE TITLE
Documentation not working on gitlab.com

### ISSUE THREAD

**Issue by Trefex** [gitlabhq/gitlabhq#8813]
https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/update.md returns 500 internal server error.

Something went wrong?

**Comment by Razer6** [comment]
Working like a charm :)

**Comment by Trefex** [comment]
OK, for me it's still 500. Strange

**Comment by Eijebong** [comment]
Same as #8637 I think.

@Razer6 try to log out before viewing the file.

**Comment by Razer6** [comment]
@Eijebong Reproduced.

**Comment by Razer6** [comment]
Fixed. Let's close it
