### ISSUE TITLE
6.X to 7.8 migration error

### ISSUE THREAD

**Issue by aubinlorieux** [gitlabhq/gitlabhq#8817]
I there i've try to upgrade 6.X to 7.8 with the documentatin available [here](https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/6.x-or-7.x-to-7.8.md)

but i got this error when i try to migrate ; 

```
sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production
== 20140907220153 SerializeServiceProperties: migrating =======================
-- add_column(:services, :properties, :text)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate column name 'properties': ALTER TABLE `services` ADD `properties` text/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:301:in `query'
```

**Comment by tripflex** [comment]
I got this same error going from 7.0 to 7.8

**Comment by alex-sherwin** [comment]
I get the same error trying to go from 7.0 to 7.8

**Comment by alex-sherwin** [comment]
I'm not sure why, but when this migration runs:

https://github.com/gitlabhq/gitlabhq/blob/7371c9e2f453c6bd910aa1335a278743bbf827bf/db/migrate/20140907220153_serialize_service_properties.rb

It fails because the `services.template` column doesn't exist, which wasn't added until some time later here:

https://github.com/gitlabhq/gitlabhq/blob/1d9e9c1b920c01122924afe86a949bc97678f06e/db/migrate/20150211172122_add_template_to_service.rb

I was able to manually work around it by first manually adding the `services.template` column, for ex in postgresql:

`alter table services add column template boolean default false;`

Then re-run `sudo gitlab-ctl reconfigure` to let the `db:migrate` task re-run.  Now it passes the previous error point, but later fails on the 20150211172122_add_template_to_service.rb (linked above) since the `services.template` column was added manually, so then delete the column:

`alter table services drop column template;`

And re-run `sudo gitlab-ctl reconfigure` one more time to finish completely

Then I was able to fully upgrade from 7.0 to 7.8

**Comment by luckyinva** [comment]
My attempt to upgrade our environment failed yesterday with the same issue.  
I attempted the upgrade 2 times.   
Following this document
https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/6.x-or-7.x-to-7.8.md
GitLab 6.5.1 6f6f158 - 7.7 and 7.8 both failed at the same point.

Error Begins here 

== 20140730111702 AddIndexToLabels: migrated (0.0488s) ========================

== 20140903115954 MigrateToNewShell: migrating ================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Failed to rewrite gitlab-shell hooks in repositories/home/git/gitlab/db/migrate/20140903115954_migrate_to_new_shell.rb:7:in `change'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:595:in `exec_migration'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:578:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:577:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:752:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:1040:in `ddl_transaction'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:953:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `each'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:807:in `up'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/migration.rb:785:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/gems/activerecord-4.1.1/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

Error Ends Here

Only thing during upgrade that is unexpected yet consistent is the following.


gitlab-shell]$ git checkout v2.4.1
error: Your local changes to the following files would be overwritten by checkout:
        hooks/update
Please, commit your changes or stash them before you can switch branches.
Aborting
[git@SERVER gitlab-shell]$ git stash
Saved working directory and index state WIP on (no branch): 083eb8c Version 1.8.0
HEAD is now at 083eb8c Version 1.8.0

While I didn't expect this error previous upgrades have completed in test without issue following executing the git stash command.

Thanks for any information regarding resolution.

**Comment by ibab** [comment]
Just fixed our migration from 6.2 to 7.8 thanks to @alex-sherwin.
I had to do the following:

- Add the `template` column
- Drop the `properties` column (or it will complain that it already exists)
- Continue the migration task
- Drop the `template` column at the next error
- Continue the migration

**Comment by maxlazio** [comment]
We are looking into solution for this

**Comment by yaplej** [comment]
We tried to upgrade form 7.3.2 to 7.8.0 and also to 7.8.1 both result in the same problem in the database migration.

This also happened when manually running the migration after the initial "gitlab-ctl reconfigure".

If we are the service without this the UI produces a bunch of 500 & 502 errors.

```
Running handlers:
[2015-02-25T06:55:14-08:00] ERROR: Running exception handlers
Running handlers complete

[2015-02-25T06:55:14-08:00] ERROR: Exception handlers complete
[2015-02-25T06:55:14-08:00] FATAL: Stacktrace dumped to /opt/gitlab/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 48 resources updated in 45.459803642 seconds
[2015-02-25T06:55:14-08:00] ERROR: bash[migrate gitlab-rails database] (gitlab::database_migrations line 19) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20150225-43422-hm5sno" ----
STDOUT: rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `template' for #<SlackService:0x00000005cff4b8>
NameError: undefined local variable or method `template' for #<SlackService:0x00000005cff4b8>

Tasks: TOP => db:migrate
(See full trace by running task with --trace)
== 20140125162722 AddAvatarToProjects: migrating ==============================
-- add_column(:projects, :avatar, :string)
   -> 0.0624s
== 20140125162722 AddAvatarToProjects: migrated (0.0625s) =====================

== 20140914113604 AddMembersTable: migrating ==================================
-- create_table(:members)
   -> 0.1258s
-- add_index(:members, :type)
   -> 0.0122s
-- add_index(:members, :user_id)
   -> 0.0105s
-- add_index(:members, :access_level)
   -> 0.0120s
-- add_index(:members, [:source_id, :source_type])
   -> 0.0124s
== 20140914113604 AddMembersTable: migrated (0.1732s) =========================

== 20140914145549 MigrateToNewMembersModel: migrating =========================
-- execute("INSERT INTO members ( user_id, source_id, source_type, access_level, notification_level, type ) SELECT user_id, group_id, 'Namespace', group_access, notification_level, 'GroupMember' FROM users_groups")
   -> 0.0027s
-- execute("INSERT INTO members ( user_id, source_id, source_type, access_level, notification_level, type ) SELECT user_id, project_id, 'Project', project_access, notification_level, 'ProjectMember' FROM users_projects")
   -> 0.0021s
== 20140914145549 MigrateToNewMembersModel: migrated (0.0050s) ================

== 20140914173417 RemoveOldMemberTables: migrating ============================
-- drop_table(:users_groups)
   -> 0.0108s
-- drop_table(:users_projects)
   -> 0.0039s
== 20140914173417 RemoveOldMemberTables: migrated (0.0148s) ===================

== 20141006143943 MoveSlackServiceToWebhook: migrating ========================
STDERR:
---- End output of "bash"  "/tmp/chef-script20150225-43422-hm5sno" ----
Ran "bash"  "/tmp/chef-script20150225-43422-hm5sno" returned 1
[2015-02-25T06:55:14-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by DouweM** [comment]
Thanks for reporting @yaplej, we're working on a fix.

**Comment by Razer6** [comment]
fixed on master

**Comment by ccarrascal** [comment]
Getting this error from 6.9.2 to 8.05
Solved it by:

<code>alter table services add column template boolean default false;</code>

Execute again db:migrate

<code>alter table labels add column template boolean default false;</code>

Execute again db:migrate

<code>alter table services drop column template;</code>

Execute again db:migrate

<code>alter table labels drop column template;</code>

Execute again db:migrate


Pray to god everything went well
