### ISSUE TITLE
Update asciidoctor gem

### ISSUE THREAD

**Issue by jirutka** [gitlabhq/gitlabhq#8827]
[Gemfile](https://github.com/gitlabhq/gitlabhq/blob/v7.8.0.rc3/Gemfile#L102) strictly specifies version 0.1.4 which is 1.5 years old and very outdated. Please update it to the most recent version, for better use experience with AsciiDoc.

**Comment by Razer6** [comment]
@jirutka It's pinned, because the gem is used by github-markup and they pin it to 0.1.4: https://github.com/github/markup/blob/master/Gemfile#L12

Maybe you can make an issue on their tracker?

**Comment by Razer6** [comment]
Just saw it, there is an open PR  https://github.com/github/markup/pull/427

**Comment by Razer6** [comment]
Updated. Close this here
