### ISSUE TITLE
gmail bounces gitlab new user emails

### ISSUE THREAD

**Issue by sandrodz** [gitlabhq/gitlabhq#8839]
I've noticed that gmail bounces gitlab new user emails specifically, for the content.

Postfix log file says:

vps postfix/smtp[5327]: E72EF24640FF: to=<-------@gmail.com>, relay=gmail-smtp-in.l.google.com[2607:f8b0:400e:c02::1a]:25, delay=1.3, delays=0/0/0.36/0.92, dsn=5.7.1, status=bounced (host gmail-smtp-in.l.google.com[2607:f8b0:400e:c02::1a] said: 550-5.7.1 [2604:180:1::2609:edb3      12] Our system has detected that this 550-5.7.1 message is likely unsolicited mail. To reduce the amount of spam sent 550-5.7.1 to Gmail, this message has been blocked. Please visit 550-5.7.1 http://support.google.com/mail/bin/answer.py?hl=en&answer=188131 for 550 5.7.1 more information. zh4si5810344pac.179 - gsmtp (in reply to end of DATA command))

Email needs to be reworked, so it doesn't trigger this reaction.

**Comment by rumpelsepp** [comment]
Is your DNS setup ok? You could test it e.g. here: http://mxtoolbox.com/

**Comment by sandrodz** [comment]
Yes, I can send normal messages to gmail accounts. It is only gitlab new user mail that is bounced back.

vps.idev.ge you can check yourself.

**Comment by Razer6** [comment]
@maxlazio Has this been resolved. I remember there was something..

**Comment by maxlazio** [comment]
@Razer6 There were number of fixes since February but I don't know if this specific one was covered. Furthermore, this is the only report of this problem I've seen so far.

**Comment by Razer6** [comment]
Ok. Then we close it for now and let people open a new issue with current version if there still occurs.
