### ISSUE TITLE
gitlab-ce 7.8, dashboard sidebar not correctly showing assignee:any Merge Requests

### ISSUE THREAD

**Issue by halberom** [gitlabhq/gitlabhq#8844]
Summary:
The dashboard sidebar does not correctly show assignee:any Merge Requests for projects that you're a member of.

To reproduce
- create some Merge Requests in a project you are a member of
- do not assign them
- navigate to the main dashboard

Expected
- the Merge Requests count increases to the number of existing MRs
- when selecting Merge Requests, it shows all existing MRs under assignee: any

Actual
- the Merge Requests count stays at 0
- selecting Merge Requests, it displays no MRs.
![selected_dashboard_mr](https://cloud.githubusercontent.com/assets/1328095/6328725/3963438a-bb62-11e4-9e27-155aceddc650.png)
- selecting the assignee: any drop down, and selecting 'any' refreshes and correctly displays the MRs.  However the Merge Requests count still displays 0
![selecting_assignee_any](https://cloud.githubusercontent.com/assets/1328095/6328729/3e0c24c4-bb62-11e4-94cc-cbaba8eed9ae.png)
![mr_now_listed](https://cloud.githubusercontent.com/assets/1328095/6328731/40a41e12-bb62-11e4-95a8-60151d17469b.png)

If selecting the project, the project sidebar correctly displays the number of MRs and if selected, they are correctly listed.
![mr_in_project_correctly_listed](https://cloud.githubusercontent.com/assets/1328095/6328759/98ff7890-bb62-11e4-9f64-69cb50388239.png)

**Comment by TurkeyMan** [comment]
We just ran into this issue in our office.
Is this a regression? Did it work correctly in prior releases?

**Comment by halberom** [comment]
I don't know when it occurred, I upgraded from 7.5.1 (old UI) directly to 7.8 (new UI).  Certainly in the old UI, there was no count against the Merge tab, but selecting the Merge tab correctly listed all MRs immediately - no need to select filters to force a refresh.

**Comment by TurkeyMan** [comment]
I'm having to select 'Any' to force a refresh (as described), and the counter is always 0.

**Comment by OsiJr** [comment]
+1 Issue as described.

**Comment by brugidou** [comment]
+1 same issue here

**Comment by jedav** [comment]
+1, and the Issues sidebar item also has the same problem/behavior in our 7.8 install.

**Comment by jvanbaarsen** [comment]
Fixed in newer version
