### ISSUE TITLE
Warning about need to set password is wrong for LDAP users

### ISSUE THREAD

**Issue by dserodio** [gitlabhq/gitlabhq#8846]
We use LDAP for authentication, omniauth is disabled and `signin_enabled` is set to false. After upgrading to 7.8.0, I started receiving a warning that "You won't be able to pull or push project code via HTTP" but that's not true. I'm able to push code just fine.

This was introduced in 25e44d05 and apparently it doesn't handle LDAP users correctly.

**Comment by Razer6** [comment]
I linked this to the [regression issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/1100)

**Comment by DouweM** [comment]
Thanks @dserodio, I'll check it out.

**Comment by rev138** [comment]
This seems to be a problem for omniauth users as well.
