### ISSUE TITLE
Ignore white space option in diff

### ISSUE THREAD

**Issue by TurkeyMan** [gitlabhq/gitlabhq#8849]
Can we have a checkbox at the top of a diff (in PR review's) to ignore whitespace in the diff?
That'll be really handy when you're forced into environments where people don't care about whitespace >_<

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
