### ISSUE TITLE
Nitpick: Make avatar images larger in commit history

### ISSUE THREAD

**Issue by TurkeyMan** [gitlabhq/gitlabhq#8850]
In the commit history view, the avatar images appear as 16x16-ish to the left of the author name.
It would be better if they appeared larger (48x48-ish) to the left of the commit body, ie, the hash and author would both appear to the right of the avatar image.

As is, avatar images are too small to visually make sense of the detail in the images. It's almost impossible to distinguish users if their avatar images are similar colours.

**Comment by Razer6** [comment]
Will be so in GitLab 8.0
