### ISSUE TITLE
Project and group avatars should be cached by browser

### ISSUE THREAD

**Issue by pnull** [gitlabhq/gitlabhq#8857]
Project and group avatars are freshly loaded each time i open the dashboard. Maybe that's because the images are piped through rails using special nginx location?!

**Comment by pnull** [comment]
![screen shot 2015-02-25 at 00 26 16](https://cloud.githubusercontent.com/assets/872019/6361691/0ac7bca8-bc85-11e4-9c07-2c2a493bc8d3.png)

**Comment by Wachiwi** [comment]
:+1:

**Comment by 123Haynes** [comment]
@pnull Thank you for reporting this. It's a nice thing to fix during the community weekend that's starting tomorrow :)

**Comment by jvanbaarsen** [comment]
I like this improvement, but its not on the direct roadmap. Since this is not an issue I'll be closing for now. Feel free to submit a PR.
