### ISSUE TITLE
Project avatar "Choose File..." doesn't work

### ISSUE THREAD

**Issue by edsonschleiwabion** [gitlabhq/gitlabhq#8860]
Project avatar "Choose File ..." doesn't work 

Open Project Settings and click on "Chose File ..."
The Open File dialog doesn't popup. 

version: GitLab 7.8.1 e2d785c 

I saw that the "gitlab.com" works OK "GitLab Enterprise Edition 7.8.1-ee 992a936"

**Comment by Razer6** [comment]
**Cannot** confirm. Works as expected on GitLab 7.8.1 e2d785c

**Comment by edsonschleiwabion** [comment]
Exists any kind of configuration that should be done at the server to allow the project avatar ?

**Comment by kfrankperson** [comment]
Have you tried clearing you browser cache ?

**Comment by edsonschleiwabion** [comment]
Sorry, the problem is somewhere else, i test it clean the cache, using a incognito user, and with another browser (Firefox), the "choose File ..." doesn't work :-(.
The Group avatar "Choose File ..." works OK.

**Comment by Leryan** [comment]
Doesnt now work with 7.8.4 cleaned cache, rebuilt assets, not working. But only when you want to assign an avatar to a group you are creating (url : /admin/groups/new )

**Comment by spacattac** [comment]
ditto the fail on 7.8.4

**Comment by edsonschleiwabion** [comment]
The problem was on the assets cache, the sollution is, clean and precompile the new assets files:

cd /home/git/gitlab
sudo -u git -H bundle exec rake cache:clear RAILS_ENV=production
service gitlab stop
redis-cli FLUSHALL
sudo -u git -H bundle exec rake assets:clean RAILS_ENV=production
sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production
service gitlab start
sudo service nginx restart

I think that the assets:clean and assets:precompile should be in the update steps.
