### ISSUE TITLE
Project avatar for older project does not show up.

### ISSUE THREAD

**Issue by eyecreate** [gitlabhq/gitlabhq#8868]
New projects I created(or one made in last few versions of gitlab) have proper project avatars. Older projects from 6.x that were migrated will seem to upload the avatar, but will still show just the large letter. I checked the logs and it only shows 200s when uploading. I also see the avatar in the /tmp folder, so it looks like it got to the server, but something is still wrong.
```
Started PATCH "/group/project" for 74.60.225.185 at 2015-02-25 22:36:07 +0000
Processing by ProjectsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"tokenwashere", "project"=>{"name"=>"Project Name", "description"=>"", "default_branch"=>"master", "visibility_level"=>"0", "tag_list"=>"", "issues_enabled"=>"1", "merge_requests_enabled"=>"1", "wiki_enabled"=>"1", "snippets_enabled"=>"1", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x00000001f6b188 @tempfile=#<Tempfile:/tmp/RackMultipart20150225-14159-18rxpm>, @original_filename="avatar.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"project[avatar]\"; filename=\"avatar.png\"\r\nContent-Type: image/png\r\n">}, "id"=>"group/project"}
Completed 200 OK in 85ms (Views: 39.8ms | ActiveRecord: 11.5ms)
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
