### ISSUE TITLE
commits calendar is empty when primary email is not the same as in public key.

### ISSUE THREAD

**Issue by dccmx** [gitlabhq/gitlabhq#8871]
While commits from web based operations were counted in calendar. And email in public key was added in settings page (just not setted as primary email).
According to profile settings page, all email addresses will be used to identify your commits. So this might be a bug.

**Comment by 123Haynes** [comment]
@dccmx for now the commit calendar only supports the primary mail address.  
We'll have to test how the performance of the calendar behaves if it has to search for all email addresses.  
I'll add it to my TODO list for 7.9.  
We will work quite a bit on the calendar until the next release.

**Comment by ReDetection** [comment]
Am I right that it's 7.10 already but not fixed? Maybe milestone should be changed

**Comment by 123Haynes** [comment]
no that was fixed for 7.9.
And 7.10 isn't officially released yet.
But the rc is available on gitlab.com and we changed how the calendar worked quite a lot.
Check out https://gitlab.com/u/dzaporozhets for an example.
When you click on a date you'll see the actions that user did :)
