### ISSUE TITLE
gitlab update not working for ubuntu 14.04

### ISSUE THREAD

**Issue by ashwin31** [gitlabhq/gitlabhq#8875]
Hi,

I have installed gitlab ce 7.7.2 on Ubuntu 14.04 server and not able update it to 7.8 using https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/7.7-to-7.8.md

can anyone verify the same.

**Comment by Razer6** [comment]
Thanks for the issue report. Please reformat your issue to conform to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines). What happens exactly?

**Comment by ashwin31** [comment]
**Summary:** I tried to update 
**Steps to reproduce:** Install gitlab using these steps https://about.gitlab.com/downloads/ on Ubuntu 14.04. Then try to upgrade as per https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/7.7-to-7.8.md
**Expected behavior:** I expected it to update normally
**Observed behavior : **
Output of checks
Results of GitLab Application Check
```
sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production SANITIZE=true
sudo: bundle: command not found
```
```
sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production
sudo: bundle: command not found
```
```
sudo service gitlab stop
gitlab: unrecognized service
```

**Comment by Razer6** [comment]
So you installed via omnibus? Like the following:

```
wget https://downloads-packages.s3.amazonaws.com/ubuntu-14.04/gitlab_7.8.1-omnibus-1_amd64.deb
sudo dpkg -i gitlab_7.8.1-omnibus-1_amd64.deb
```

If so, you took the wrong update guide. The correct one is https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/update.md

**Comment by ashwin31** [comment]
Thank you @Razer6 It did work this way, I was trying the wrong method for few months and recently I created new server and migrated to it because I was not able to update.

Thank you very much.

**Comment by SaimonL** [comment]
ashwin31

Do you know what you did. I did a standard install using doc from:
https://about.gitlab.com/downloads/#ubuntu1404

When I try to do bundle install I get error bundle command not found

```bash
sudo -u git -H bundle install --deployment --without development test postgres aws kerberos
sudo: bundle: command not found
```
