### ISSUE TITLE
gitlabci oauth2 ok login redirect not working

### ISSUE THREAD

**Issue by geki007** [gitlabhq/gitlabhq#8877]
logout on gitlabci and gitlab
go to gitlabci and press logon with gitlab
now you are on the gitlab logon page ... logon
--> now you should be redirected to the gitlabci page ... but you won't

i use:
gitlab + ci 7.8.1 CE
ldap
signup disabled
signin disabled

**Comment by Razer6** [comment]
Wil be fixed with GitLab 8.0 in which CI and GitLab are one app.
