### ISSUE TITLE
user with developer permission cannot push to internal project

### ISSUE THREAD

**Issue by t3mux** [gitlabhq/gitlabhq#8879]
Some users of our gitlab instance cannot push to an internal project on some projects. They have developer rights in a group that owns these projects. If i change to rights to master they can push to the project. 

They also have developer rights in other groups and can push to projects of these groups. In addition other member with developer rights in the problem groups can push to the projects.

The problem occurs on some projects not all and has nothing to do with the ssh keys. I checked that already.

**Comment by 123Haynes** [comment]
@t3mux is it possible that the branch they are trying to push to is a protected branch?  
(Project->Settings->Protected branches)

**Comment by t3mux** [comment]
No it's not and strange is that other developers can push to the project.

**Comment by t3mux** [comment]
@123Haynes THANKS it is a protected branch because by default the master branch is a protected.branch.

**Comment by 123Haynes** [comment]
@t3mux Glad you solved your problem. You can change that default on the settings page in the admin area.
