### ISSUE TITLE
repo without 'master' uses 'master' as default branch when cloning

### ISSUE THREAD

**Issue by mathstuf** [gitlabhq/gitlabhq#8883]
A repository with multiple branches, one of which is the default (according to the web UI) without a master branch, it seems the remote HEAD refers to an invalid commit (the repo has never had a 'master' branch).

Using 7.8.1.

**Comment by mathstuf** [comment]
It seems that switching the default branch to another branch and then back works. This problem only seems to appear if the repo never had a master branch to start.

**Comment by rhymoid** [comment]
I can reproduce this on 7.7.2 and had this issue on 7.1.1 as well.

---

To reproduce:

* Create a project on GitLab.
* Create a Git repository.

      mkdir my-awesome-project
      cd my-awesome-project
      git init
      git remote add origin https://gitlab.example.com/my-awesome-project.git

* Push a branch named `develop`.

      echo hello > greeting.txt
      git add -A
      git checkout -b develop
      git commit -m 'Initial commit'
      git push origin develop

* Push a branch named `bugfix-1-adieu`

      echo bye > greeting.txt
      git checkout -b bugfix-1-adieu
      git commit -am 'Fixed the greeting'
      git push origin bugfix-1-adieu

Expected outcome:

* The branch `develop` is the default branch.

Actual outcome:

* The branch `bugfix-1-adieu` is the default branch.

Note that:

* Until a default branch is explicitly picked through the settings panel, the default branch will be the most recent branch pushed.
* Cloning from `https://gitlab.example.com/my-awesome-project.git` without an explicitly named branch to check out (through the `-b` flag) results in a "warning: remote HEAD refers to nonexistent ref, unable to checkout."

**Comment by Razer6** [comment]
This has been fixed by https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/614
