### ISSUE TITLE
endless loops in active_record

### ISSUE THREAD

**Issue by lifeofguenter** [gitlabhq/gitlabhq#8894]
see: https://bugs.ruby-lang.org/issues/10872
see: http://pastebin.com/4WbfXpTk

really frustrating.

**Comment by lifeofguenter** [comment]
turns out gitlab does not like Debian 7 32bit - migrated to Ubuntu 14.04 64Bit and so far no problems.

**Comment by Razer6** [comment]
Cool, closing if it seems to be fixed.
