### ISSUE TITLE
[RFE] Separate repo quotas for forks

### ISSUE THREAD

**Issue by mathstuf** [gitlabhq/gitlabhq#8895]
It would be nice to allow users to fork repos without also allowing arbitrary repo creation. Relaxing quota counts (or adding an alternative quota options) such that forks don't count towards it would be nice.

**Comment by adaiguoguo** [comment]
I agreed with you any more.This feature will also limit the increase of storage use.How to manage  those unclaimed forks is still admin ‘s worries

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
