### ISSUE TITLE
Cannot diff changes in wiki history

### ISSUE THREAD

**Issue by EmteZogaf** [gitlabhq/gitlabhq#8899]
I did not find any option to compare two revisions in the history of a wiki page. Did I miss something?

**Comment by ykyuen** [comment]
+1

**Comment by popofr13** [comment]
+10 (all our team ;))

**Comment by chauthai** [comment]
+1

**Comment by DanielSWolf** [comment]
:+1: That's a basic feature for every Wiki.

**Comment by jose-pleonasm** [comment]
+1

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
