### ISSUE TITLE
Syntax highlighting for Drupal PHP files no longer works

### ISSUE THREAD

**Issue by minorOffense** [gitlabhq/gitlabhq#8900]
Previous versions of the syntax highlighting properly detected the PHP inside Drupal .module, .inc, .profile etc. files. That highlighting no longer works.

Screenshot from GitLab Enterprise Edition 7.8.1-ee 992a936

![screen shot 2015-03-02 at 11 30 42 am](https://cloud.githubusercontent.com/assets/871728/6445068/bc4a6162-c0cf-11e4-8867-6ca3ad828685.png)

**Comment by rumpelsepp** [comment]
Should be an easy fix. I will add this tonight/tomorrow.

**Comment by rumpelsepp** [comment]
@minorOffense Can you provide a list of the relevant file extensions for me?

**Comment by minorOffense** [comment]
Sure. The extensions aren't unique to Drupal through so checking for the php tag would be a good second check. 

.module
.inc
.profile
.install
.test

That should be all of them. Anything else would already use .php or aren't php files (.info, .js, .make)

**Comment by rumpelsepp** [comment]
Thx. I will see what I can do. :)

**Comment by rumpelsepp** [comment]
Should be fixed with this [push](https://gitlab.sevenbyte.org/rumpelsepp/rugments/compare/82b928950aee8f0390e9932caf448b532df3942c...4b6c5cacf3135ddbcacec0f3feebd3f754984d31)
