### ISSUE TITLE
Feature request: Download Git bundle

### ISSUE THREAD

**Issue by JonathonReinhart** [gitlabhq/gitlabhq#8901]
I work with Git bundles a lot.  It would be awesome to have a "Download .bundle" option here:

![image](https://cloud.githubusercontent.com/assets/1916566/6448809/7519594a-c0ea-11e4-92fa-d16d43373edb.png)

In the most basic case, it would download the entire repo as a .bundle.

In a more advanced scenario, a dialog would be presented, prompting the user for the *basis* from which to create the bundle.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

**Comment by JonathonReinhart** [comment]
Sorry about that, I didn't realize.  I posted a [feature request here](http://feedback.gitlab.com/forums/176466-general/suggestions/7166347-enable-download-of-git-bundle).
