### ISSUE TITLE
Issue aside disappearing after collapse

### ISSUE THREAD

**Issue by jasonblanchard** [gitlabhq/gitlabhq#8904]
Steps to reproduce:
1. Visit the issue#show page for an issue
2. Change the window size to a small viewport
3. Click the `show-aside` button to show the aside info
4. Click the `show-aside` button again to show the main issue content
5. Change the window size back to a large viewport

Expected behavior: The aside info goes back to its original position next to the main issue content
![screen shot 2015-03-02 at 6 03 15 pm](https://cloud.githubusercontent.com/assets/1238532/6452853/708fcf1e-c106-11e4-8523-eb71da80f774.png)

Observed behavior: The aside info box stays hidden:
![screen shot 2015-03-02 at 5 59 31 pm](https://cloud.githubusercontent.com/assets/1238532/6452861/7b0e808e-c106-11e4-87bc-1948cf340bed.png)

Same behavior if you leave the aside visible in the small viewport. Refreshing the page fixes it.

**Comment by Razer6** [comment]
Still in 7.14

**Comment by Razer6** [comment]
FIxed in GitLab 8.0
