### ISSUE TITLE
Docs have wrong link

### ISSUE THREAD

**Issue by mathstuf** [gitlabhq/gitlabhq#8912]
At the bottom of [the docs](http://doc.gitlab.com/ce/):

```
Generated from https///gitlab.com/gitlab-org/gitlab-ce at Tue Mar 3 14:20:18 2015, please submit improvements.
```

Note the `///` instead of `://`.

**Comment by Razer6** [comment]
Closing as a duplicate of https://gitlab.com/gitlab-com/doc-gitlab-com/issues/13
