### ISSUE TITLE
Append domain in auto-created users from LDAP login

### ISSUE THREAD

**Issue by godlike64** [gitlabhq/gitlabhq#8916]
Hello,

I had previously set up Gitlab 7.7 (.1 I think) and I configured it to authenticate against my LDAP directory. A thing to note here is that I'm running a custom LDAP scheme (not any of the known, widely used ones), so I could accomodate more easily multiple domains. This same LDAP tree is authenticating several other services (mail-related, Jabber, etc).

So today I bumped into a particular issue: I have two users whose mail address is the same, except for the domain part (let's call them user@example.com and user@foo.bar). Whichever user logged in first, got the 'user' entry created in the users table, and its corresponding LDAP mapping in identities. However, when the other user wanted to login, he got an error similar to #8530. 

So I updated to 7.8 to see if it was fixed, and indeed it is. Now the first user that logs in gets its username set as 'user1', and the second one, 'user2'. While this fixes the problem nicely, it might result in a bit of awkwardness for other people. Namely, when I search for a user to add to a project/group, I get his name (which is correctly gotten from the LDAP, but in many cases like this, might be the same name across several domains) and his username, both of which do not tell me much if I don't already know which is which.

So my suggestion is, instead of appending an incremental integer to the username, to append the domain name. I don't know If dots cannot be used here, but it could be something like

user-examplecom

or

user.example.com

Let me know if this is feasible/possible/desired/unwanted/risky

Cheers

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
