### ISSUE TITLE
Inconsistent issue links

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8920]
The activity stream has some consistency issues, see screenshot.

![screenshot 2015-03-05 22 11 14](https://cloud.githubusercontent.com/assets/1961699/6514733/e48cedcc-c384-11e4-9003-04a540b9f70c.png)

**Comment by rumpelsepp** [comment]
I have tried to solve this problem and unify these links. I have used the cross reference ids; maybe it also helps to help users getting familiar with these cross referencing ids.

Interested in a pull request?

![screenshot from 2015-03-31 23-17-18](https://cloud.githubusercontent.com/assets/1961699/6929574/196d75e4-d7fc-11e4-8999-39b51d39efd5.png)

**Comment by jvanbaarsen** [comment]
Issue has been fixed in newer version
