### ISSUE TITLE
mensioned commit message is not listed in the issue page.

### ISSUE THREAD

**Issue by joicemjoseph** [gitlabhq/gitlabhq#8922]
![gl](https://cloud.githubusercontent.com/assets/672445/6519407/620c473a-c3d9-11e4-8ae6-65cd1912dd6f.png)

Not showing the exact commit message, instead of that, showing  'mentioned' .
if the commit message is there, it will be easy to differenciate what he had contributed while checking the issues.

**Comment by jvanbaarsen** [comment]
I think it would not be great to have the commit message show here. Since a commit message can be quite a long message. Closing this issue for now

**Comment by joicemjoseph** [comment]
I was thinking that making github like open platform.

**Comment by jvanbaarsen** [comment]
@joicemjoseph I'm not sure what you mean?

**Comment by joicemjoseph** [comment]
Currently Bitbucket is having the feature of showing the complete commit message in the issue page, if there is a issue id is mentioned in a commit. I think it is so much helpful. while working on a project, It is easy to understand what happened in that commit.

**Comment by jvanbaarsen** [comment]
I don't think this will help with how easy the page is to scan. For now I don't think we will plan on adding this.
