### ISSUE TITLE
Broadcast message cannot be deleted

### ISSUE THREAD

**Issue by Trefex** [gitlabhq/gitlabhq#8923]
I am using GitLab 7.8.2 via omnibus and it seems that broadcast messages can not be deleted.

As an admin, when trying to delete an active broadcast, the call is rejected with a 403 Access Denied.

Request URL:      https://mydomain/admin/broadcast_messages/2
Request Method: DELETE
Status Code:403 Access Denied

I could not find anything of relevance in the logs.

**Comment by Trefex** [comment]
This seems to be because we are behind an `Apache Traffic Server` which does not allow `DELETE` requests.

Does anybody have experience with that and how to not get a broken gitlab instance behind a proxy?

Thanks,

**Comment by Razer6** [comment]
Closing this here, because we do not support `Apache Traffic Server` officially.
