### ISSUE TITLE
[Issue tracker] Reply counter should ignore system notes

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8929]
When I update an issue usually system notes are created like this:

![screenshot from 2015-03-06 20 27 55](https://cloud.githubusercontent.com/assets/1961699/6534645/4f002290-c43f-11e4-909b-80aa22485def.png)

These messages are considered in the number of replies on the issue table:

![screenshot from 2015-03-06 20 26 39](https://cloud.githubusercontent.com/assets/1961699/6534665/6f7138e8-c43f-11e4-99b4-51785bf9ccd4.png)

That does not make sense. We should ignore system notes and just count the "real" replies in the discussion.

**Comment by Razer6** [comment]
Fixed with https://github.com/gitlabhq/gitlabhq/commit/2bb4ea854228c3c9660d5cb55f59e2cafd1f33ec
