### ISSUE TITLE
commits calendar doesn't count commits made to branches

### ISSUE THREAD

**Issue by pratapvardhan** [gitlabhq/gitlabhq#8933]
On lines with #8931,

commits calendar doesn't count commits which are made to branches of own projects. Also, the case, when commits are made to branches of forked project.

**Comment by 123Haynes** [comment]
this has been fixed with 7.9.
But in 7.10 the calendar will change quite a lot.
See https://gitlab.com/gitlab-org/gitlab-ce/commit/e24da35984c13132e204ff923e4b75600ebed56e
