### ISSUE TITLE
duplicated error message on failed login with github

### ISSUE THREAD

**Issue by luzfcb** [gitlabhq/gitlabhq#8937]
Sign-in failed because `email has already been taken`, `email has already been taken.`

See

![gitlab](https://cloud.githubusercontent.com/assets/807599/6555282/30905f72-c643-11e4-9e21-7de3bea7759d.png)

**Comment by Razer6** [comment]
fixed by https://github.com/gitlabhq/gitlabhq/commit/73918efb273b83b59f421557db2134973bb8eb53
