### ISSUE TITLE
GitLab 7.5 -> 7.83 (Latest Version) Update Error

### ISSUE THREAD

**Issue by x1hash** [gitlabhq/gitlabhq#8944]
Hi GitLab,

I've recently upgraded from 7.5.3 using the upgrade instructions located here: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/upgrader.md

Sidekiq wont actually start after the upgrade -- see below:

root@git:/home/git/gitlab# service gitlab restart
Shutting down Unicorn.
GitLab is not running.
Starting both the GitLab Unicorn and Sidekiq..............................Waited 30s for the processes to write their pids, something probably went wrong.

**log/sidekiq.log**

    undefined method `merge' for #<String:0x007f34079fb720>
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:357:in `parse_config'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:207:in `setup_options'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:38:in `parse'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/bin/sidekiq:7:in `<top (required)>'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/sidekiq:23:in `load'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/sidekiq:23:in `<main>'

**Environment check**

> root@git:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production

> System information
> System:         Debian 7.8
> Current User:   git
> Using RVM:      no
> Ruby Version:   2.1.2p95
> Gem Version:    2.2.2
> Bundler Version:1.6.5
> Rake Version:   10.3.2
> Sidekiq Version:3.3.0

> GitLab information
> Version:        7.8.3
> Revision:       abea070
> Directory:      /home/git/gitlab
> DB Adapter:     mysql2
> URL:            https://git.hidden.com
> HTTP Clone URL: https://git.hidden.com/some-project.git
> SSH Clone URL:  git@git.hidden.com:some-project.git
> Using LDAP:     no
> Using Omniauth: no

> GitLab Shell
> Version:        2.5.4
> Repositories:   /home/git/repositories/
> Hooks:          /home/git/gitlab-shell/hooks/
> Git:            /usr/bin/git

**Thorough Environment check**

> root@git:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
> Checking Environment ...

> Git configured for git user? ... yes

> Checking Environment ... Finished

> Checking GitLab Shell ...

> GitLab Shell version >= 2.5.4 ? ... OK (2.5.4)
> Repo base directory exists? ... yes
> Repo base directory is a symlink? ... no
> Repo base owned by git:git? ... yes
> Repo base access is drwxrws---? ... yes
> Satellites access is drwxr-x---? ... yes
> hooks directories in repos are links: ... 
> HIDDEN ... ok
> HIDDEN  ... ok
> Running /home/git/gitlab-shell/bin/check
> Check GitLab API access: OK
> Check directories and files: 
>         /home/git/repositories: OK
>         /home/git/.ssh/authorized_keys: OK
> Test redis-cli executable: redis-cli 2.4.14
> Send ping to redis server: PONG
> gitlab-shell self-check successful

> Checking GitLab Shell ... Finished

> Checking Sidekiq ...

> **Running? ... no**
>   Try fixing it:
>   sudo -u git -H RAILS_ENV=production bin/background_jobs start
>   For more information see:
>   doc/install/installation.md in section "Install Init Script"
>   see log/sidekiq.log for possible errors
>   Please fix the error above and rerun the checks.

> Checking Sidekiq ... Finished

> Checking LDAP ...

> LDAP is disabled in config/gitlab.yml

> Checking LDAP ... Finished

> Checking GitLab ...

> Database config exists? ... yes
> Database is SQLite ... no
> All migrations up? ... sudo -u git -H RAILS_ENV=production bin/background_jobs start
> yes
> Database contains orphaned GroupMembers? ... no
> GitLab config exists? ... yes
> GitLab config outdated? ... no
> Log directory writable? ... yes
> Tmp directory writable? ... yes
> Init script exists? ... yes
> Init script up-to-date? ... yes
> projects have namespace: ... 
> HIDDEN ... yes
> HIDDEN ... yes
> Projects have satellites? ... 
> HIDDEN ... yes
> HIDDEN  ... yes
> Redis version >= 2.0.0? ... yes
> Ruby version >= 2.0.0 ? ... yes (2.1.2)
> Your git bin path is "/usr/bin/git"
> Git version >= 1.7.10 ? ... yes (1.7.10)

> Checking GitLab ... Finished

I can revert back to 7.5.3 from the backup created, however I just simply can't upgrade as it keeps failing to start Sidekiq due to the above error.

Any advice or help would be greatly appreicated.

**Comment by stanhu** [comment]
It looks like Sidekiq is having issues loading its configuration file. Somehow the loading of the config YAML is returning a string rather than a hash. Perhaps adding `puts` debug statements around line 357  may help?

```/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb```

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
