### ISSUE TITLE
Merge requests should not show commits of master branch after rebase

### ISSUE THREAD

**Issue by forki** [gitlabhq/gitlabhq#8945]
* Create a feature branch from master
* Create a Merge Request from feature branch into master
* Wait some time (master moves forward)
* Rebase your feature branch on master
* Force push

In the discussion page you now have references to all commits of the master branch that came with the rebase:

![image](https://cloud.githubusercontent.com/assets/57396/6613836/90478098-c892-11e4-81ba-9e7635e46b2d.png)

It would be nice if you would exclude this information (like github does) and just show the commits that are really on the feature branch and not on master.

**Comment by stanhu** [comment]
I believe this is resolved by 7dadd423d5279a67cad6d7919370432931deee3e.

**Comment by jvanbaarsen** [comment]
Issue has been solved in a newer version
