### ISSUE TITLE
Improved messaging for failed pushes on protected branches.

### ISSUE THREAD

**Issue by wdamien** [gitlabhq/gitlabhq#8948]
When developers with no access rights attempt a push to a protected branch a vague message is returned:

```remote: GitLab: No such project```

Debugging this is difficult since it gives no context to whats actually happening.
A message like  ```remote: Gitlab: You don't have access rights on this branch to push.``` would help debugging push issues faster.

**Comment by maxmeyer** [comment]
:+1:

**Comment by Razer6** [comment]
@DouweM Didn't you implement this?

**Comment by DouweM** [comment]
@Razer6 I sure did!

@wdamien It'll be in 7.10, due to be released on April 22nd!

**Comment by Razer6** [comment]
@DouweM Wasn't sure. Perfect :+1:

**Comment by maxmeyer** [comment]
Thanks a lot! :smile:
