### ISSUE TITLE
`go get` for public and private repositories

### ISSUE THREAD

**Issue by mattes** [gitlabhq/gitlabhq#8949]
Thought that https://github.com/gitlabhq/gitlabhq/pull/7693 would be available since 7.8. It was merged but is not available?

**Comment by mattes** [comment]
https://github.com/gitlabhq/gitlabhq/commit/d513ca584aaed7ca2a1de2d2fbd2192422f13d81#diff-9b454209a2f1343b7b950c8c1b867133

@DouweM

**Comment by DouweM** [comment]
@mattes Your implementation was replaced by the one in 3702c4ad80614d71fc5ac3ea1af7c3789ec8146d which doesn't require changes to nginx config. It will be in 7.9.
