### ISSUE TITLE
Search API 'Scope: All' only works for Admins

### ISSUE THREAD

**Issue by StephenOTT** [gitlabhq/gitlabhq#8950]
After reviewing the GitLab Ruby API Wrapper, testing, and reviewing the GitLab documentaiton it appears that the Search API have scopes of Owned or All.  Owned being the repos that the authenticated user owns, and All for All repos.  But All is only usable by "Admins".  So how does one use the Search API to search GitLab for all public projects and projects that are private but the user has access to?

GitLab Ruby API Reference: https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/projects.rb#L13

Example use case: I want to search GitLab.com for all projects with the name: "GitLab" in it.

**Comment by StephenOTT** [comment]
I could settle for being able to search using the actual Namespace/ProjectName, but that feature has seemed to be removed from the Api as well.

Thoughts on path forward?

**Comment by StephenOTT** [comment]
Anyone able to help with this??

**Comment by NARKOZ** [comment]
`GET /projects` with `search` param should return a list of projects accessible by the authenticated user. That includes public projects too.
