### ISSUE TITLE
Support Emoji List?

### ISSUE THREAD

**Issue by StephenOTT** [gitlabhq/gitlabhq#8951]
Is there a list of supported Emoji for GitLab?

There does not seem to be support for :clock1: (`:clock1:`) and various other emoji

**Comment by Azaret** [comment]
There is in the help section of gitlab http://doc.gitlab.com/ce/markdown/markdown.html#emoji

**Comment by StephenOTT** [comment]
@Azaret so it appears there is either a bug, or the emoji list cheatsheet is incorrect/out of date:
https://gitlab.com/StephenOTT/Steve/issues/1
![screen shot 2015-03-17 at 12 21 12 pm](https://cloud.githubusercontent.com/assets/1994838/6691975/3d76ed88-cca0-11e4-9191-675d4c8acb46.png)

The Clock emoji will not appear in issues.  Thoughts?

**Comment by maxlazio** [comment]
GitLab.com is running 7.8.4 and the documentation is updated to contain the upcoming changes in 7.9. In 7.9, GitLab will start using EmojiOne. You will be able to see the change in the next 24hours when 7.9.0rc1 gets deployed to GitLab.com.

**Comment by StephenOTT** [comment]
Ah!! Thank you!
