### ISSUE TITLE
Unable to subscribe activity feed

### ISSUE THREAD

**Issue by cvsguimaraes** [gitlabhq/gitlabhq#8952]
I believe that I'm unable to subscribe the activity feed when the feed validation is more "aggressive".
For instance by typing in slack:
```
/feed subscribe https://gitlab.company.com/groups/my-group.atom?private_token=XXXX
```
I receive:

> Sorry, 'https://gitlab.company.com/groups/my-group.atom?private_token=XXXX' doesn't look like a feed url. Try again?

So I've checked and [W3C validator](http://validator.w3.org/feed/) which give me some errors:
![screen shot 2015-03-13 at 4 28 25 pm](https://cloud.githubusercontent.com/assets/1047033/6645774/06cab58a-c99e-11e4-9c60-ea2c0d1edf10.png)

**Comment by cvsguimaraes** [comment]
Despite the errors in the validator, the private token is missing in the self reference.

**Comment by cvsguimaraes** [comment]
The subscription process was successful after fixing the following:
* Used absolute URL to the self and alternative reference
* Added the private token to the URL
* Added a slash at end of image tags (probably mandatory in all self-closing tags)

**Comment by Razer6** [comment]
Mismatched tags fixed with  https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/344

**Comment by cvsguimaraes** [comment]
Issue [moved to gitlab](https://gitlab.com/gitlab-org/gitlab-ce/issues/1237).
