### ISSUE TITLE
Commits calendar does not show right

### ISSUE THREAD

**Issue by xiaopeng163** [gitlabhq/gitlabhq#8957]
hi 

I found an issue about the `commits calendar`. from the picture below, you can find there are no commit histories on Mar 15 from the commit calendar, but from the user activity, you can find there are many commit records on that day

![11](https://cloud.githubusercontent.com/assets/5743757/6659545/b964f5cc-cbc2-11e4-98d7-ebcaad6518ff.png)

is this a bug?

**Comment by xiaopeng163** [comment]
My version is GitLab 7.8.0 825919a

**Comment by Azaret** [comment]
Having the issue too but only on some people.
After trying to know why some and not others, my best guess is that the calendar only show commit on internal and public repositories, not on the privates ones.

**Comment by 123Haynes** [comment]
This should be fixed with 7.9.
But in 7.10 the calendar will change quite a lot.
See https://gitlab.com/gitlab-org/gitlab-ce/commit/e24da35984c13132e204ff923e4b75600ebed56e
