### ISSUE TITLE
Change git_data_dir to mounted cifs share resolves in error.

### ISSUE THREAD

**Issue by mengine23** [gitlabhq/gitlabhq#8959]
Hi there,

i recently tried to set up a gitlab server and wanted the git_data_dir to be on a mounted windows share. So here are the steps i made:

*mount a share with help of cifs-tools (added to /etc/fstab)
//8.8.8.8/xxx/GIT-Repos /media/gitrepos cifs uid=git,gid=git,credentials=/home/xxx/.smbcredentials,iocharset=utf8,dir_mode=0770,sec=ntlm 0 0

*Change git_data_dir the mounted folder & run gitlab-ctl reconfigure
This does not lead to any errors. Everything seems to be fine. The folder "gitlab-satellites" & "repositories" are created properly.

Now i tried to create a new project via web interface. This always lead to the error message "Failed to create repository". I checked the logs, but there is no entry or hint that something went wrong. I post the related lines from production.log:

Started GET "/projects/new" for 127.0.0.1 at 2015-03-16 12:29:24 +0100
Processing by ProjectsController#new as HTML
Completed 200 OK in 85ms (Views: 56.7ms | ActiveRecord: 10.8ms)
Started POST "/projects" for 127.0.0.1 at 2015-03-16 12:34:01 +0100
Processing by ProjectsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"WFF01LII0r8HC4EoPUKczdnISHaO9tEWNkzyqNCI90A=", "project"=>{"path"=>"test", "namespace_id"=>"1", "import_url"=>"", "description"=>"", "visibility_level"=>"0"}}
Completed 200 OK in 857ms (Views: 70.9ms | ActiveRecord: 17.9ms)

When i now peek inside the mounted folder, the repo has been created. So im confused about what can lead to that error?!

**Comment by GrandFlo** [comment]
I have the same Issue. Do you have a solution? 
In my case the folder "projectxxx.git" is created but not the folder "projectxxx.wiki.git"

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
