### ISSUE TITLE
Broadcast message timmey wimmey

### ISSUE THREAD

**Issue by Azaret** [gitlabhq/gitlabhq#8961]
Hello,

It looks like broadcast message doesn't end at the given time : 
![image](https://cloud.githubusercontent.com/assets/1201743/6684271/e8195d86-cc8f-11e4-93cd-7ebee4c8bf8c.png)

**Comment by duduribeiro** [comment]
Can you check if it isn't considering the timezone? 
If your broadcast message stop at 11:00 (because your timezone is +1), probably when save the broadcast message is not considering the actual timezone.

Thanks :smile:

**Comment by Azaret** [comment]
It does looks like a timezone issue, I'll try to do some test. We did remove the broadcast message before it disappears.

**Comment by duduribeiro** [comment]
:+1: 
Later I will execute some tests too.. 
Maybe the solution is to transforme the params sent to controller to the current Timezone before create the model.

**Comment by Azaret** [comment]
`Confirmed`

I set up a broadcast message until 10 am and it did disappears at 11 am, considering our GMT+1 timezone, it looks more than a coincidence.

**Comment by chengweiv5** [comment]
+1 on this issue, is there any plan to fix this?

**Comment by duduribeiro** [comment]
Hi.. I tested here and It is working as expected. 
You only need to configure your timezone in the `application.rb` because the default is `UTC`.

Like I configured mine:
application.rb
```
module Gitlab
   class Application < Rails::Application
      ...
         config.time_zone = 'Brasilia'
      ...
   end
end
```

@Azaret I think this Issue can be closed, what you think? :smile:

**Comment by chengweiv5** [comment]
Hi @duduribeiro , which version are you looking at? I'm using 7.9.2 release and has timezone configured to "Asia/Shanghai" (UTC+08), but the broadcast message doesn't take timezone into account.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
