### ISSUE TITLE
Edit in fullscreen

### ISSUE THREAD

**Issue by Azaret** [gitlabhq/gitlabhq#8963]
If the textarea is resized, then switching to fullscreen won't fit the textarea to full height.

**Comment by zertrin** [comment]
I can confirm that with Gitlab 7.8.2 dbdc1a6 (omnibus install) and Firefox 36.0.1.

Moreover, I don't know if is normal or not, but I never have full width in fullscreen mode while editing the wiki.

If the textarea has not been resized, then fullscreen mode goes full height (but not full width). 

![i8963_1](https://cloud.githubusercontent.com/assets/1447163/6691172/5ffdcbc2-ccc5-11e4-941e-07aae7777d07.png)

![i8963_2](https://cloud.githubusercontent.com/assets/1447163/6691178/66922e38-ccc5-11e4-9df6-b67e819753db.png)

If it has been resized (through the browser), then the fullscreen mode

![i8963_3](https://cloud.githubusercontent.com/assets/1447163/6691185/6f45e0e2-ccc5-11e4-983e-935f954fb923.png)

![i8963_4](https://cloud.githubusercontent.com/assets/1447163/6691202/959f0ff2-ccc5-11e4-916b-22efc05bc00c.png)

**Comment by Razer6** [comment]
Fix proposed in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1248
