### ISSUE TITLE
"Cancelling" creating a new file leads to a 404 on empty repositories

### ISSUE THREAD

**Issue by kaime** [gitlabhq/gitlabhq#8967]
1. Go to an empty repository (the message "The repository for this project is empty" shows)
2. Click on the "Add a file" button. It takes you to `.../new/master`.
3. Click on "Cancel" button. The URL changes to `../tree/master`, which makes a 404, because the `master` branch does not exists.

**Comment by duduribeiro** [comment]
What version are you using? 
I'm with the master e7e329d and it is working fine
:smile: 
Thaanks. []'s

**Comment by duduribeiro** [comment]
![demo](http://zippy.gfycat.com/EachRegularFruitfly.gif)

**Comment by kaime** [comment]
Sorry, didn't realize I was using "GitLab 7.8.1 e2d785c". Maybe it's been already fixed.

**Comment by duduribeiro** [comment]
I tested and I saw that was fixed in v7.9.0.rc1 Can u update to this version? 

Thanks,

**Comment by Razer6** [comment]
Tested on 7.9ee and works as expected.
