### ISSUE TITLE
Cannot change account email at gitlab.com

### ISSUE THREAD

**Issue by renkun-ken** [gitlabhq/gitlabhq#8972]
I'm not sure why I cannot change my email account in gitlab.com. When I go to settings and change my email to an alternative that has been showing in the list of my verified email accounts, an error occurs like
![gitlab-account-email-error](https://cloud.githubusercontent.com/assets/4662568/6722042/19bf5bb2-ce0f-11e4-9e92-62c2e699216c.png)

**Comment by duduribeiro** [comment]
Maybe the email that you are trying to use is already in use, try another.
I made a local test in the gitlab code, and when the email that I'm trying to set is in use, I receive this message too.

**Comment by renkun-ken** [comment]
Thanks a lot, @duduribeiro! Just as you pointed out, I found the problem is when my email I want to change to already appears in my Emails list, I cannot change my account email to that. I need to remove that email address from the list first, and then change my account email which is no longer in use. Go to my inbox and verify the email. Then this email will automatically added to the email list.

**Comment by duduribeiro** [comment]
No problem @renkun-ken =D.
Thanks for all
:smile:
