### ISSUE TITLE
Could not authorize you from LDAP, because "undefined method 'provider' for nil:nilclass"

### ISSUE THREAD

**Issue by jayenne01** [gitlabhq/gitlabhq#8973]
Logging in via LDAP fails with above message and following log entries, if a user has already signed-up locally with an identical username:

Started GET "/users/sign_in" for 127.0.0.1 at 2015-03-18 16:28:47 +0100
Processing by SessionsController#new as HTML
Completed 200 OK in 47ms (Views: 30.8ms | ActiveRecord: 4.5ms)
Started POST "//api/v3/internal/allowed" for 127.0.0.1 at 2015-03-18 16:28:49 +0100
Started POST "//api/v3/internal/allowed" for 127.0.0.1 at 2015-03-18 16:28:54 +0100
Started POST "/users/auth/ldap/callback" for 127.0.0.1 at 2015-03-18 16:29:06 +0100
Processing by OmniauthCallbacksController#ldap as HTML
Parameters: {"utf8"=>"â", "authenticity_token"=>"+HOLgg=", "username"=>"XXXXX", "password"=>"[FILTERED]"}
Completed 500 Internal Server Error in 236ms

Version is 7.7.2

![gitlabproblem](https://cloud.githubusercontent.com/assets/11503608/6723325/97e9350e-cde6-11e4-9ebb-26f2a4fc0eca.png)

**Comment by vsizov** [comment]
Please update GitLab.

**Comment by vsizov** [comment]
#8530

**Comment by jayenne01** [comment]
Thank you for your time and help, it's always appreciated!
I've been scanning through the changelogs before posting this and haven't found an explicit fix in 7.8 nor 7.9. 
Your linked issue #8530 (https://github.com/gitlabhq/gitlabhq/issues/8530) mentions it apparently being fixed for 7.7.2 which happens to be the running version here. Has there been a fix in 7.8.x?

**Comment by MichaelAlt** [comment]
Are you using special charakters in your distinguishedName Name, e.g. commas?

Had the same error and fixed it with #8995

**Comment by jayenne01** [comment]
Thank you for your hint, but no, there are no special chars apart from a hyphen in the domain name. Our DN is built from the uid without spaces and other special characters.

**Comment by jayenne01** [comment]
I've now created a test environment and upgraded to 7.9. 
Trying to log-in via ldap after signing up with the same uid before seems to work now, so 7.9 (or 7.8) seem to fix this issue. The LDAP-User gets a trailing number on its uid if the uid derived from the dn is already locally taken. 
Thanks for your help.
