### ISSUE TITLE
Commits Calendar only shows commits that were also pushed by the user?

### ISSUE THREAD

**Issue by Codelica** [gitlabhq/gitlabhq#8980]
Not sure if this is by design, or if we have some other oddity, but it looks like the Commits Calendar only shows commits that were also pushed by the user.  

We have some automated processes that push daily commits from remote repos using a "bot" type account.  None of the developer commits that come in through those bot pushes show up in the Commits Calendar or User Activity.

**Comment by Razer6** [comment]
Related to #8931
