### ISSUE TITLE
Syntax highlight not working for Haxe

### ISSUE THREAD

**Issue by kevinresol** [gitlabhq/gitlabhq#8982]
Sample: https://gitlab.com/louisbl/Ash-HaXe/blob/master/src/ash/GenericListIterator.hx

**Comment by rumpelsepp** [comment]
You are welcome to provide a lexer for it. :)
https://github.com/rumpelsepp/rugments

Please open an issue on the rugments github page.

**Comment by Razer6** [comment]
Closing this here.
