### ISSUE TITLE
Package nodejs is not available in Debian Wheezy

### ISSUE THREAD

**Issue by xperseguers** [gitlabhq/gitlabhq#8984]
The upgrade documentation from 7.8 to 7.9 step 4 (https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/7.8-to-7.9.md#4-install-libs-migrations-etc) tells us to install nodejs using:

```
sudo apt-get install nodejs
```

According to https://packages.debian.org/wheezy-backports/nodejs it implies that `/etc/apt/source.list` (or equivalent) is configured to fetch from wheezy-backports.

**Comment by xperseguers** [comment]
Documentation should instruct:

    Add this line

        deb http://http.debian.net/debian wheezy-backports main

    to your sources.list (or add a new file with the ".list" extension to /etc/apt/sources.list.d/).

    Refresh the list of available package and install nodejs:

        sudo apt-get update
        sudo apt-get install nodejs

**Comment by chulkilee** [comment]
#9019 is actual PR for this proposal. See #8996 for alternative.

**Comment by Razer6** [comment]
Fixed in linked MRs.
