### ISSUE TITLE
Updating comment with thumbs up emoji fails

### ISSUE THREAD

**Issue by johnou** [gitlabhq/gitlabhq#8986]
When updating a comment with ":+1:" an error occurs and the ajax refresh fails.

Started PUT "/xxx/xxx/notes/4" for 193.64.35.129 at 2015-03-20 12:38:53 +0200
Processing by Projects::NotesController#update as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxx", "note"=>{"note"=>":+1:"}, "commit"=>"Save Comment", "project_id"=>"xxx/xxx", "id"=>"4"}
Completed 500 Internal Server Error in 96ms

```
ActionView::Template::Error (undefined method `each' for nil:NilClass):
    28:         %span.note-last-update
    29:           = note_timestamp(note)
    30:
    31:         - if note.superceded?(@notes)
    32:           - if note.upvote?
    33:             %span.vote.upvote.label.label-gray.strikethrough
    34:               %i.fa.fa-thumbs-up
  app/models/note.rb:495:in `superceded?'
  app/views/projects/notes/_note.html.haml:31:in `_app_views_projects_notes__note_html_haml___3629060394487211255_121248620'
  app/controllers/projects/notes_controller.rb:71:in `note_to_html'
  app/controllers/projects/notes_controller.rb:103:in `render_note_json'
  app/controllers/projects/notes_controller.rb:39:in `block (2 levels) in update'
  app/controllers/projects/notes_controller.rb:38:in `update'
```

**Comment by stanhu** [comment]
This is fixed [here](https://github.com/gitlabhq/gitlabhq/commit/b8c9257fb1dc70cd65a14cb7dec62455ea54e394) in GitLab v7.9, which will be released on March 22.

**Comment by johnou** [comment]
@stanhu thanks a lot!
