### ISSUE TITLE
Support for external services

### ISSUE THREAD

**Issue by cdenneen** [gitlabhq/gitlabhq#8989]
Should be option with installer to support external services like Postgresql, Redis, etc.
This would allow use of existing services elsewhere in enterprise and avoid having to install unnecessary software.

**Comment by Razer6** [comment]
I think this belongs to [omnibus](https://gitlab.com/gitlab-org/omnibus-gitlab). However, it supports non-packaged postgresql and redis. This is documented in the readme.
