### ISSUE TITLE
[7.9.0.rc] View of branch with slashes leads to 404

### ISSUE THREAD

**Issue by stefan-it** [gitlabhq/gitlabhq#8990]
Hi,

after upgrading from *6.6.x* to the latest *7.9-pre* version I found a strange behaviour when clicking on a branch with contains a slash, e.g. `feature/issue-378` on the "Project" view.

Clicking on such a branch lead to a *404* (Object not found error). The *URL* is:

```
..project/commits/feature%2Fissue-378
``` 

On the commit -> branch menu the link will lead to:

```
..project/tree/feature/issue-378
```

So I guess there's something wrong with escaping the slash on "Project" view?! Tested on `7.9.0.rc2 e716e43`

Thanks in advance,

Stefan

**Comment by maxlazio** [comment]
Thanks for the report @stefan-it , this is fixed and will be in 7.9
