### ISSUE TITLE
Calendar commits are slightly skewed

### ISSUE THREAD

**Issue by arif-ali** [gitlabhq/gitlabhq#8992]
![snapshot1](https://cloud.githubusercontent.com/assets/628790/6763045/569fab2a-cf65-11e4-87d2-40876a3bc267.png)

The above image shows that the little icons are skewed to the left

This is also visible in gitlab.com, as seen here https://gitlab.com/u/dzaporozhets

**Comment by 123Haynes** [comment]
@arif-ali what browser are you using?

**Comment by arif-ali** [comment]
Chromium (41.0.2272.76 Ubuntu 14.10 (64-bit)) is good
Firefox (36.0.1) has issues

**Comment by arif-ali** [comment]
This issue still exists in 7.10.0

Or is gitlab only supported in chrome/chromium and not firefox?

**Comment by arif-ali** [comment]
Seems like this has been resolved with new version of Firefox 38.0 + Gitlab 7.11.3
