### ISSUE TITLE
gemnasium-gitlab-service 0.2.5 isn't compatible with ruby 2.0

### ISSUE THREAD

**Issue by anthonyryan1** [gitlabhq/gitlabhq#8998]
The Gemfile specifies that any 0.2 version is acceptable, but the upstream released 0.2.5 without compatibility for ruby 2.0. Since this hit bundler it's now failing to allow gitlab to run on ruby 2.0.

I would propose locking the Gemfile to a known good 0.2.x version until the upstream resolves their issue.

[Upstream bug report](https://github.com/gemnasium/gemnasium-gitlab-service/issues/1).

**Comment by dblessing** [comment]
Fixed in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/433.
