### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by qeremy** [gitlabhq/gitlabhq#9005]
Hi,

Gitlab seems working well, accepting commits etc. But in web view, when I try to open an URL like `/foo/tree/master/library/class` giving "500 Internal Server Error". But I can receive URL's like `/foo/tree/master/library/class/Autoload.php`.

I suppose, causing if route ends with `class` word.

Here is the `gitlab-ctl tail` logs;

<pre>
==> /var/log/gitlab/gitlab-rails/production.log
Started GET "/qeremy/foo/tree/master/library/class" for ****** at 2015-03-22 22:40:44 +0000
Processing by Projects::TreeController#show as HTML
  Parameters: {"project_id"=>"qeremy/foo", "id"=>"master/library/class"}
Completed 500 Internal Server Error in 111ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: - tree, commit = submodule_links(submodule_item)
    2: %tr{ class: "tree-item" }
    3:   %td.tree-item-file-name
    4:     %i.fa.fa-archive
  app/models/repository.rb:162:in `method_missing'
  app/models/repository.rb:228:in `submodule_url_for'
  app/helpers/submodule_helper.rb:6:in `submodule_links'
  app/views/projects/tree/_submodule_item.html.haml:1:in `_app_views_projects_tree__submodule_item_html_haml__736031347953229344_21913860'
  app/helpers/tree_helper.rb:19:in `render_tree'
  app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml__3751095614754975011_29378540'
  app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml___2226454669748656175_30116540'
  app/controllers/projects/tree_controller.rb:13:in `show'
</pre>

**UPDATE**

I updated it to `GitLab 7.9.1 6f6c5f1` and seems no error  such it anymore.

Thank you!

**Comment by Razer6** [comment]
@qeremy On which version are you? Can you provide a test-repo on gitlab.com?

**Comment by qeremy** [comment]
@Razer6 Here is /help page result: GitLab 7.6.2 16f0968

**Comment by elboletaire** [comment]
Same here! These are my current gitlab installation details:

    GitLab 7.9.1
    GitLab Shell 2.6.0
    GitLab API v3
    Ruby 2.1.2p95
    Rails 4.1.9

**Comment by elboletaire** [comment]
Exactly this has been reported before in #8881

**Comment by qeremy** [comment]
Up!
