### ISSUE TITLE
GitLab is crashing while booting up

### ISSUE THREAD

**Issue by patschi** [gitlabhq/gitlabhq#9015]
After upgrading from 7.8.x to 7.9 GitLab is completely borken.
When I try to start GitLab, it just doesn't work:
<pre>root@git-ce:/home/git/gitlab/log# sudo service gitlab start
Removing stale Unicorn web server pid. This is most likely caused by the web server crashing the last time it ran.
Removing stale Sidekiq job dispatcher pid. This is most likely caused by Sidekiq crashing the last time it ran.
Starting both the GitLab Unicorn and Sidekiqmaster failed to start, check stderr log for details

The GitLab Unicorn web server is not running.
The GitLab Sidekiq job dispatcher with pid 13815 is running.
</pre>

The log lines from the sidekiq.log file (all other log files are empty):
<pre>2015-03-24T18:03:13.332Z 13815 TID-osc5g3tz8 INFO: Booting Sidekiq 3.3.0 with redis options {:url=>"unix:/var/run/redis/redis.sock", :namespace=>"resque:gitlab"}
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require': /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/gemnasium-gitlab-service-0.2.5/lib/gemnasium/gitlab_service/client.rb:17: syntax error, unexpected ',' (SyntaxError)
...oad_files(files, project_slug:, branch_name:, commit_sha:)
...                               ^
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/gemnasium-gitlab-service-0.2.5/lib/gemnasium/gitlab_service/client.rb:60: syntax error, unexpected keyword_end, expecting end-of-input
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/gemnasium-gitlab-service-0.2.5/lib/gemnasium/gitlab_service/pusher.rb:1:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/gemnasium-gitlab-service-0.2.5/lib/gemnasium/gitlab_service.rb:2:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/app/models/project_services/gemnasium_service.rb:20:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:348:in `require_or_load'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:307:in `depend_on'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:225:in `require_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/engine.rb:467:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/engine.rb:467:in `block in eager_load!'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/engine.rb:465:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/engine.rb:465:in `eager_load!'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/engine.rb:346:in `eager_load!'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/application/finisher.rb:58:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:180:in `each'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
        from /home/git/gitlab/config/environment.rb:5:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:236:in `boot_system'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:50:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.3.0/bin/sidekiq:8:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/bin/sidekiq:23:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.0.0/bin/sidekiq:23:in `<main>'</pre>

**Comment by stecman** [comment]
I'm seeing a different error from the same file after upgrading:

```
... /gemnasium/gitlab_service/client.rb:60: syntax error, unexpected keyword_end, expecting end-of-input
```

**Comment by stanhu** [comment]
Are you installing from source? You may want to read:

https://gitlab.com/gitlab-org/gitlab-ce/issues/1269

**Comment by maxlazio** [comment]
7.9.1 patch release will be out on 25th of March with a fix for this issue.

**Comment by Razer6** [comment]
Closing this for now. Please report back if the error still exists in 7.9.1
