### ISSUE TITLE
7.9 Can't edit "Your changes could not be committed, because the file has been changed"

### ISSUE THREAD

**Issue by DmACKGL** [gitlabhq/gitlabhq#9017]
Error: Your changes could not be committed, because the file has been changed
Build: 7.9
GitHost.Log:
<code>
March 24, 2015 21:22 -> ERROR -> Command failed [127]: /usr/local/bin/git --git-dir=/home/git/gitlab-satellites/root/GHand/.git --work-tree=/home/git/gitlab-satellites/root/GHand checkout -b __parking_branch
</code>

Thx

**Comment by Razer6** [comment]
Fixed in GitLab 8.0 where satellites are removed.
