### ISSUE TITLE
Add Hall project service

### ISSUE THREAD

**Issue by wolf99** [gitlabhq/gitlabhq#9024]
Could someone add a project service for the Hall chat application?
https://hall.com/docs/integrations/generic/

Or maybe even just a Zapier service: https://zapier.com/developer/documentation/

If I could, I'd do it myself but I haven't enough of a notion to be even able to manage integration through the web hooks interface!
Ta!

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
