### ISSUE TITLE
Custom "Reply To"

### ISSUE THREAD

**Issue by tstorch** [gitlabhq/gitlabhq#9027]
Hi there,
we need to have a custom "reply to" for our emails. Currently we use [this](https://github.com/cvut/gentoo-overlay/blob/master/www-apps/gitlabhq/files/gitlabhq-6.5.1-email-custom-reply_to.patch) Patch. Is there any chance this will be part of mainline?

We would like to use the omnibus packages and this is the only piece missing.

**Comment by NARKOZ** [comment]
There is a pull request #8753
