### ISSUE TITLE
Show merge request author [7.9]

### ISSUE THREAD

**Issue by iiSeymour** [gitlabhq/gitlabhq#9028]
I would be nice to see the author of the merge request in the merge request view.

**Comment by jbruggem** [comment]
+1

**Comment by rumpelsepp** [comment]
This has been already included: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests
/cc @jvanbaarsen: I think you can close this. :)

**Comment by iiSeymour** [comment]
Just upgraded.. looks great  :+1:

**Comment by jvanbaarsen** [comment]
@rumpelsepp Thanks for noticing :)

**Comment by rumpelsepp** [comment]
youre welcome, but razor6 was faster. :D

**Comment by jvanbaarsen** [comment]
:joy:
