### ISSUE TITLE
Bitnami Gitlab:push android soruce code project fails with HTTP code = 500

### ISSUE THREAD

**Issue by edisonrf** [gitlabhq/gitlabhq#9033]
First I clone android srouce code, which size is more than 11GB:
  $git clone https://android.googlesource.com/device/lge/hammerhead-kernel

then update remote origin to our own gitlab server and push:
  $ git push -u origin master

and failed with below output:

Username for 'http://git.xx.com': myname
Password for 'http://myname@git.xx.com':
Counting objects: 2287, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2000/2000), done.
Writing objects: 100% (2287/2287), 11.02 GiB | 4.85 MiB/s, done.
Total 2287 (delta 112), reused 2287 (delta 112)
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

I searched many posts and tried below solutions:
1,http.postbuffer=26843545600 #set to 25GB

2,apache setting:
Timeout 36000
KeepAlive On
MaxRequestsPerChild 2048
ServerLimit 1000
MaxClients 500
LimitRequestFields 0
LimitRequestFieldSize 80000000
LimitRequestLine 80000000
LimitXMLRequestBody 0

PassengerTempDir /data/tmp_passenger
PassengerUploadBufferDir /data/buffer_passenger

3,gitlab.yml setting:
max_size: 26843545600 # 25GB
timeout: 36000  #10 hours

4,unicorn.rb setting
timeout 36000  #10 hours

unfortunately, the error still exists. I tried Bitmani Gitlab version 6.9.2 and 7.8.1.

it is easy to reproduce this issue, does anyone meet this or have a solution? 
thanks in advance.

**Comment by Razer6** [comment]
Fixed in GitLab 8.0 with a new git-http-server.
