### ISSUE TITLE
Preserve trailing new lines at the end of file

### ISSUE THREAD

**Issue by chulkilee** [gitlabhq/gitlabhq#9035]
Related: #5936

- GitLab 7.9.1
- Firefox 36.0.4 on Mac

When I create or edit a text file via web editor, it removes the last new line. For example, when I put three new blank lines, only two lines are saved.

**Comment by kylekatarnls** [comment]
This works well for me: #9422

**Comment by Razer6** [comment]
Closing as seems to be fixed

**Comment by eddiemonge** [comment]
This isn't fixed yet as that PR is still open. Can this stay open until then? Also fine with keeping it closed as a duplicate of #8706

**Comment by Razer6** [comment]
Thanks for clarification. Then leave it closed as a duplicate of #8706 because this one was open before.
