### ISSUE TITLE
[7.9.0-7.9.1] How to configure Google Analytics ID ?

### ISSUE THREAD

**Issue by mahnunchik** [gitlabhq/gitlabhq#9054]
How to configure Google Analytics ID?

There is no required key: https://github.com/gitlabhq/gitlabhq/blob/master/app/models/application_setting.rb

**Comment by stanhu** [comment]
It looks like it's not documented anywhere, but if you're using the omnibus version, you can add this line to `/etc/gitlab/gitlab.yml`:

```
gitlab_rails['extra_google_analytics_id'] = '_your_tracking_id'
```

Then run `sudo gitlab-ctl reconfigure`.

See:

https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L126

**Comment by mahnunchik** [comment]
@stanhu Thank you! It helps me.

I think it should be documented.

**Comment by Razer6** [comment]
Documentation for this can be found [here](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/gitlab.yml.md). Closing this here :)

**Comment by adamlaz** [comment]
This should be more noteable in the documentation... 

Also... I'd love to be able to add user-id tracking for google analytics! 
`ga('set', 'userId', {{USER_ID}}); // Set the user ID using signed-in user_id.`
