### ISSUE TITLE
Can not add members to group beside myself on master:HEAD

### ISSUE THREAD

**Issue by darix** [gitlabhq/gitlabhq#9057]
as the title says ... the auto complete only lists myself.

I am the only admin on this gitlab instance.

**Comment by darix** [comment]
https://github.com/gitlabhq/gitlabhq/blob/master/app/controllers/autocomplete_controller.rb#L10

This code doesnt make any sense... If i pass a group_id, it will only list members of that group. how should one add a member to a group that way?

**Comment by darix** [comment]
@randx i think d6c8eefb5d0298f0c733ac4880e1e64f2a37b24c broke this

**Comment by randx** [comment]
Thank you. I will take a look

**Comment by randx** [comment]
Fixed by b7e2be2

**Comment by darix** [comment]
Thank you for the quick fix.

**Comment by randx** [comment]
You are welcome. Thank for reporting and mentioning me

**Comment by darix** [comment]
JFYI: the admin panel view is still broken. ```/admin/groups/<groupname>```

**Comment by randx** [comment]
@darix thank you. We will fix it and report back

**Comment by randx** [comment]
Fixed by 2940de43a5aba532e67022e03eb6d5772625c248
