### ISSUE TITLE
 ! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by thelordsaves** [gitlabhq/gitlabhq#9060]
my gitlab version is 7.6.2
I created a new repo and pushed the latest code to it,
then I changed the URL of the repo, for example:
from
git@git.testcompany.com:AAA-dev/icer2.git
to
git@git.testcompany.com:BBB-dev/icer2.git
and then I used " git remote set-url " command to change my remote setting, and everything is ok,
but this time , when I push my modification to the repo, there is an error:

Counting objects: 40, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (16/16), done.
Writing objects: 100% (26/26), 1.89 KiB | 0 bytes/s, done.
Total 26 (delta 8), reused 0 (delta 0)
remote: GitLab: You don't have permission
To git@git.mexdia.com:mexdia-dev/icer2.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@git.mexdia.com:mexdia-dev/icer2.git'

**Comment by rhymoid** [comment]
Is the `master` branch protected?

**Comment by TahirMehmood** [comment]
i have same issue using heroku on mac, heroku Activity tab
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.0.0
-----> Installing dependencies using 1.9.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       You have added to the Gemfile:
       * ruby (= 2.0.0)
       * pg (= 0.17.1)
       Bundler Output: You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       
       You have added to the Gemfile:
       * ruby (= 2.0.0)
       * pg (= 0.17.1)
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app

terminal
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/depot8082.git'

**Comment by rhymoid** [comment]
That's a very different issue. Your error message is related to Bundler and explains exactly what to do. @thelordsaves' error message is related to GitLab permissions.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
