### ISSUE TITLE
ActionView::Template::Error on project/services pages with GitlabIssueTrackerService.

### ISSUE THREAD

**Issue by jarpy** [gitlabhq/gitlabhq#9069]
I'm getting this issue for some of my project home pages after upgrading from 7.6.2 to 7.9.1.

The output of `gitlab-ctl reconfigure`, `gitlab-rake db:migrate` and `gitlab-rake gitlab:check` show no errors.

```
Started GET "[REDACTED]" for 127.0.0.1 at 2015-04-01 13:59:55 +1100
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"[REDACTED]"}
Completed 500 Internal Server Error in 158ms

ActionView::Template::Error (The single-table inheritance mechanism failed to locate the subclass: 'GitlabIssueTrackerService'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Service.inheritance_column to use another column for that information.):
    62:             - else
    63:               #{link_to @project.owner_name, @project.owner}
    64: 
    65:           - @project.ci_services.each do |ci_service|
    66:             - if ci_service.active? && ci_service.respond_to?(:builds_path)
    67:               - if ci_service.respond_to?(:status_img_path)
    68:                 = link_to ci_service.builds_path do
  app/models/project.rb:325:in `ci_services'
  app/views/projects/show.html.haml:65:in `_app_views_projects_show_html_haml__3484415254094103639_39488400'
  app/controllers/projects_controller.rb:69:in `block (2 levels) in show'
  app/controllers/projects_controller.rb:62:in `show'
```

**Comment by jarpy** [comment]
Similar error on "Services" page for the affected projects.

```
ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'GitlabIssueTrackerService'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Service.inheritance_column to use another column for that information.):
  app/models/project.rb:308:in `block in build_missing_services'
  app/models/project.rb:307:in `each'
  app/models/project.rb:307:in `build_missing_services'
  app/controllers/projects/services_controller.rb:11:in `index'
```
Other pages such as "Network" render OK.

**Comment by jarpy** [comment]
Restored service with this SQL statement:
`delete from services where type = 'GitlabIssueTrackerService';`

**Comment by chryb** [comment]
I'm getting this error in the production.log when I try to open a specific project.

`Completed 500 Internal Server Error in 1446ms
ActionView::Template::Error (The single-table inheritance mechanism failed to locate the subclass: 'BuildkiteService'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Service.inheritance_column to use another column for that information.):
2: .commit-row-title
3: = link_to truncate_sha(commit[:id]), namespace_project_commit_path(project.namespace, project, commit[:id]), class: "commit_short_id", alt: ''
4: &nbsp;
5: = gfm event_commit_title(commit[:message]), project`

I use gitlab omnibus version 7.9.0 on a raspberry pi 2. Can someone help me?

**Comment by chryb** [comment]
I have fixed it with renaming the column `type` in the table `services`.

**Comment by stanhu** [comment]
I just ran into this. I'm not sure how this ever worked.

**Comment by stanhu** [comment]
Oh, I accidentally downgraded from gitlab-ee to gitlab-ce, which caused Rails not to be able to find `JenkinsService`.

**Comment by stanhu** [comment]
FYI, renaming `type` or removing `GitlabIssueTrackerService` is not the answer.

**Comment by ssbarnea** [comment]
How it comes that this is closed without having a solution, neither a workaround. What we are supposed to to do with this?

**Comment by dfguo** [comment]
fixed by executing this in rails console

```sql="DELETE FROM services 
WHERE type='JenkinsService' OR type='JenkinsDeprecatedService';"
ActiveRecord::Base.connection.execute(sql)
```
