### ISSUE TITLE
Can't import submodule content

### ISSUE THREAD

**Issue by angezanetti** [gitlabhq/gitlabhq#9088]
I'm running GitLab 7.3.2 f092e53, and try to add the vendor of my Symfony2 application into gitlab.

It works well for all of them execpt one, the link of the submodule seems to be broken:

![submodule](https://cloud.githubusercontent.com/assets/291512/6981427/7c3ec95a-da01-11e4-8878-810acf701290.png)

I tried to import different branches of that modules, or different commit number, but the link is still broken on the UI…

I have all the files on my local pc, but i can't send them to the gitlab server and if i try to deploy the code to another server it can't find the vendor's files as well...

**Comment by Razer6** [comment]
This is fixed on master. Report back if the error still exists in the next release
