### ISSUE TITLE
Unnecessarily long URL text paths in projects sidebar

### ISSUE THREAD

**Issue by minorOffense** [gitlabhq/gitlabhq#9095]
When viewing the list of projects in a group, the project names are cut off because the project names have the group names appended.

There's no real need to put the group name in the path when viewing from within the group already. All it does is make it impossible to tell which project you're looking at.

![biotalent canada gitlab](https://cloud.githubusercontent.com/assets/871728/7004679/4073093e-dc3d-11e4-9999-e6006544c62b.png)

The older version of GitLab (7.8.x and earlier) didn't have this issue.

![biotalent gitlab](https://cloud.githubusercontent.com/assets/871728/7004685/560d8d50-dc3d-11e4-8896-69f9e8bef896.png)

**Comment by StephenOTT** [comment]
:+1:

**Comment by Razer6** [comment]
Fixed in new design for GitLab 8.0
