### ISSUE TITLE
Help links are broken in master

### ISSUE THREAD

**Issue by darix** [gitlabhq/gitlabhq#9099]
"https://git.example.com/groups/somegroup/group_members" the help link points to "https://git.example.com/help/permissions.permissions".

what you actually want is: "https://git.example.com/help/permissions/permissions.md"

Additionally when you go to "https://git.example.com/help/" and click on documentation links they actually append and you end up with broken things like "https://git.example.com/help/help/permissions/permissions.md". If you visit the documentation page via "https://git.example.com/help" all links are working.

**Comment by duduribeiro** [comment]
Same here.. 
I think that other links is broken too.. Like http://localhost:3000/admin/hooks .
When I click in `System Hooks` link it redirect me to an invalid route.

**Comment by duduribeiro** [comment]
The actual route of help controller, accept one parameter:
`get 'help/:filepath'        => 'help#show', as: :help_page, constraints: { filepath: /[^\.]+/ }`
But when the help_page_path helper is called, like here: `help_page_path("permissions", "permissions")`, it generates a route in the format: `/help/permissions.permissions`.

My proposal is to return the old route format, to receive two parameters: `category` and `file`.
```
diff --git i/app/controllers/help_controller.rb w/app/controllers/help_controller.rb
index fbd9e67..c7e7481 100644
--- i/app/controllers/help_controller.rb
+++ w/app/controllers/help_controller.rb
@@ -3,7 +3,9 @@ class HelpController < ApplicationController
   end
 
   def show
-    @filepath = params[:filepath]
+    @category = params[:category]
+    @file = params[:file]
+    @filepath = "#{@category}/#{@file}"
     @format = params[:format]
 
     respond_to do |format|
diff --git i/config/routes.rb w/config/routes.rb
index c1b85b0..d49f4d4 100644
--- i/config/routes.rb
+++ w/config/routes.rb
@@ -41,7 +41,8 @@ Gitlab::Application.routes.draw do
   get 'help'                  => 'help#index'
   get 'help/shortcuts'
   get 'help/ui'               => 'help#ui'
-  get 'help/:filepath'        => 'help#show', as: :help_page, constraints: { filepath: /[^\.]+/ }
+  get 'help/:category/:file' => 'help#show', as: :help_page, defaults: {format: 'md'}
   #
   # Global snippets
```

OR, in a `before_filter` at helper_controller, we replace the dot (.) with a slash on @filepath.

What you guys thinks? Please correct me if am I wrong :smile: 

Thanks

**Comment by darix** [comment]
system hooks works for me. that sounds more like a problem on your side with a wrong setting in gitlab.yml.

**Comment by duduribeiro** [comment]
@darix Your system hooks link work when you enter in `http://localhost:3000/admin/hooks` ??
Thaanks

**Comment by darix** [comment]
make sure your port and everything matches what you have on top of your gitlab.yml

**Comment by 123Haynes** [comment]
/cc @DouweM Can you take a look?
I think I've seen a bugreport about this before, but I'm not sure.

**Comment by DouweM** [comment]
Yep, it's been reported and @rspeicher is working on it.

**Comment by tsigo** [comment]
Fixed in latest master.

**Comment by darix** [comment]
On 2015-04-19 11:07:13 -0700, Robert Speicher wrote:
> Fixed in latest master.

git push missing?

**Comment by tsigo** [comment]
> git push missing?

It'll be pushed to GitHub later.
