### ISSUE TITLE
Gitlab hooks paths broken when migrating from original to omnibus

### ISSUE THREAD

**Issue by cookacounty** [gitlabhq/gitlabhq#9101]
I migrated my server to omnibus following:
http://theterminallife.com/migrating-gitlab-to-gitlab-omnibus/

The only problem is, all the hooks directories:
```
/var/opt/gitlab/git-data/repositories/
```
Still point back to 
```
/home/git
```

For example:
```
# ls $PWD/hooks -la
lrwxrwxrwx 1 git git 28 Oct 22 16:42 /var/opt/gitlab/git-data/repositories/lcbu/cds6libs.git/hooks -> /home/git/gitlab-shell/hooks
```

Is there a simple way to update all the hooks paths to the new location?

**Comment by cookacounty** [comment]
I put together this command to clean up my links, run in the repositories folder:

```
find . -lname /home/git/gitlab-shell/hooks -exec sh -c 'ln -snf /opt/gitlab/embedded/service/gitlab-shell/hooks $0' {} \;

```

**Comment by marcelaraujo** [comment]
+1

**Comment by mcharris** [comment]
OH MY GOODNESS THANK YOU!!!!!!!! @cookacounty

**Comment by Razer6** [comment]
For the omnibus package please head over to the omnibus repository: https://gitlab.com/gitlab-org/omnibus-gitlab

**Comment by cookacounty** [comment]
Why did you close this? I was using the omnibus packages.
Just to be clear, I started with a gitlab server I had manually installed on a different computer, then migrated to a new server installed using omnibus. After restoring the backups, the links to the submodules were all broken.

**Comment by Razer6** [comment]
This issue/solution is related to the migration to the ****omnibus package. Therefore plead head over to the omnibus repo. This is not a particular issue of the GitLab codebase. When raising this in the omnibus repo, you make sure the right guys here that.

**Comment by soyuka** [comment]
Thanks @cookacounty! Had the same issue after migrating to omnibus and postgres.

**Comment by rufinus** [comment]
+1 thanks

**Comment by poldixd** [comment]
Thank you @cookacounty!

**Comment by maxlazio** [comment]
In case users didn't notice, with https://github.com/gitlabhq/gitlabhq/commit/e063c8f3e2c5faa8c92c898c4390e616e90926b0 in GitLab 7.12 hooks will be auto created on backup restore.

**Comment by poldixd** [comment]
my source installation backup version was 7.11.x. So i restored it with the omnibus install 7.11.x and then i updated it to 7.12

**Comment by wonkaba** [comment]
@cookacounty Still relevant. Jut upgraded from 7.10 source to 10.4 omni and ran into the same problem. Thanks for the solution.
