### ISSUE TITLE
dpkg-deb: error: `gitlab_7.9.2-omnibus-1_amd64.deb' is not a debian format archive

### ISSUE THREAD

**Issue by bingeh** [gitlabhq/gitlabhq#9102]
I install gitlab following steps like here 'https://about.gitlab.com/downloads/' on ubuntu 14.04, but when I run  `sudo dpkg -i gitlab_7.9.2-omnibus-1_amd64.deb`, it shows following:

dpkg-deb: error: `gitlab_7.9.2-omnibus-1_amd64.deb' is not a debian format archive
dpkg: error processing archive gitlab_7.9.2-omnibus-1_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 gitlab_7.9.2-omnibus-1_amd64.deb

so how to fix it?

**Comment by stanhu** [comment]
Are you sure the download completed? You may want to retry. It may be useful to run `md5sum` and compare:

```
$ md5sum gitlab_7.9.2-omnibus-1_amd64.deb 
ce58f147ffc155f8ac1be54eab38103b  gitlab_7.9.2-omnibus-1_amd64.deb
```

**Comment by bingeh** [comment]
@stanhu mine is
60a1978613b5bd082a40a4c6fcfcfc5f  gitlab_7.9.2-omnibus-1_amd64.deb

**Comment by urbandroid** [comment]
with rm delete it then get it again with wget after u updated and upgraded your server.
No problem.

**Comment by bingeh** [comment]
@urbandroid still doesn't work

**Comment by Razer6** [comment]
For the omnibus package please head over to the omnibus repository: https://gitlab.com/gitlab-org/omnibus-gitlab
