### ISSUE TITLE
Git Push

### ISSUE THREAD

**Issue by Padmanaresh** [gitlabhq/gitlabhq#9106]
Counting objects: 294, done.
Delta compression using up to 4 threads.
Total 223 (delta 156), reused 24 (delta 1)
fatal: The remote end hung up unexpectedly
fatal: recursion detected in die handler
error: RPC failed; result=18, HTTP code = 200
Everything up-to-date
Done

**Comment by Padmanaresh** [comment]
git config --global http.postBuffer 524288000 tried this on client side but that didnt fix the issue

**Comment by Razer6** [comment]
Please increase your nginx buffer size
