### ISSUE TITLE
Possibility to add comment on a snippet a-la code review

### ISSUE THREAD

**Issue by allan-simon** [gitlabhq/gitlabhq#9107]
Snippet are pretty nice to share code, but it will really bring it to the next level if it was possible to comment on lines as we do for merge request, especially when consulting with 'rookie' teams they often share piece of code to me, on which we need to discuss and comment specific point before including them in the actual code.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
