### ISSUE TITLE
Improve user feedback in UI when update hook declines a push

### ISSUE THREAD

**Issue by artlepool** [gitlabhq/gitlabhq#9111]
GitLab v7.9.1
GitLab Shell 2.6.0
GitLab API v3

Hi
I have added an update hook into my repo via the file system (custom_hooks/update).
It checks to see if you have included the string "[ref: 1234]" in the commit message. If you haven't, it returns 1 and therefore declines the commit, returning a message to the committer about why its been declined - "[POLICY] Your message is not formatted correctly"

When using the command-line to commit and push with a commit message that is unsuitable, the hook declines the commit and the decline reason message is shown to the user so all works well as expected.

If you edit a file in the UI and save it there, the push is still declined as you would hope, but the message shown to the user is far from clear and is very generic, ie a red bar at the top of the page saying "Your changes could not be committed. Maybe the file was changed by another process?"

The githost.log file on the server records the behind-the-scenes output of attempting to push via the UI:

```
April 09, 2015 20:58 -> ERROR -> Command failed [1]: /usr/local/bin/git --git-dir=/home/git/gitlab-satellites/ChrisWilson/my-project/.git --work-tree=/home/git/gitlab-satellites/ChrisWilson/my-project push origin master:master

remote: Checking commit message
remote: [POLICY] Your message is not formatted correctly
remote: error: hook declined to update refs/heads/master
To /home/git/repositories/ChrisWilson/my-project.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to '/home/git/repositories/ChrisWilson/my-project.git'
```

Is there any way the error message to the user could be improved in the UI to alert them as to the fact that, in this case, the hook has declined the commit, and the reason for it?

thanks!
Chris

**Comment by artlepool** [comment]
I just noticed the following in the API docs for "Update existing file in repository":

```
If the commit fails for any reason we return a 400 error with a non-specific error message. Possible causes for a failed commit include:

the file_path contained /../ (attempted directory traversal);
the new file contents were identical to the current file contents, i.e. the user tried to make an empty commit;
the branch was updated by a Git push while the file edit was in progress.
Currently gitlab-shell has a boolean return code, preventing GitLab from specifying the error.
```

Is there a specific reason for the error not being returned? Or is it just that the feature hasn't been implemented yet?

I would have thought that in most cases it would be very useful for the user to know what has gone wrong so that they can try and do something to make their next attempt at pushing successful?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
