### ISSUE TITLE
Page slug allows characters such as "/" but encoding won't allow page to be correctly open/edited

### ISSUE THREAD

**Issue by marcelolebre** [gitlabhq/gitlabhq#9113]
## Description
When I was creating a page I tried to create a custom path by writing a slug like "path_to/page_name".
The page was created but can't be opened, edited or deleted as it shows a 404. The reason for this is that "path_to/page_name" is encoded into "path_to%2Fpage_name" and as this page doesn't exist it won't be found.

## Steps to reproduce
1. Go to project's Wiki
2. Click on "New Page"
3. On the page slug text box insert "path_to/page_name"
4. Press "Build"
5. Collect your tears

Thanks guys :)

**Comment by stanhu** [comment]
This was fixed in f3f856029bc5f966c5a7ee24cf7efefdd20e6019 and will be released in GitLab v7.10 on April 22.

**Comment by marcelolebre** [comment]
Cool, thank you.
