### ISSUE TITLE
Adding applications through API rather than through UI

### ISSUE THREAD

**Issue by StephenOTT** [gitlabhq/gitlabhq#9127]
Is there a way to add applications through the API rather than having to navigate through the UI?

Thanks

**Comment by sylus** [comment]
This would be beneficial to me so I could run GitLab with Drone.io using a single docker-compose run rather then having to issue multiple commands with one manual step. :)

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
