### ISSUE TITLE
Fetch satellites with --prune flag to avoid satellite corruption

### ISSUE THREAD

**Issue by aiionx** [gitlabhq/gitlabhq#9149]
I don't see a reason for satellites to keep tracking old deleted branches on the remote.

Actually it can cause issues.

For example, if a branch called
    `a/b`
is deleted on the remote and then a branch called
    `a/b/c`
is created.

The satellite will fail to fetch since it is already tracking `a/b`
Making it impossible to now track branch `a/b/c`

That is because If branch `a/b` exists, no branch named `a/b/anything` can be created.

The satellite becomes useless since it can't fetch no more.

Fetching with `--prune` flag
    $ git fetch --prune
will fetch while pruning untraceable branches.

**Comment by aiionx** [comment]
Setting
`git config remote.origin.prune true`
at system level can fix this.

It would be useful to add it in the installation manual.

**Comment by Razer6** [comment]
Satellites are removed with the upcoming GitLab 8.0.
