### ISSUE TITLE
Side-by-side / parallel view buttons link to JSON output instead of HTML

### ISSUE THREAD

**Issue by bradmerlin** [gitlabhq/gitlabhq#9158]
If navigating to a merge request, and then heading to the Changes tab, the inline/side-by-side view buttons link to JSON output. Something like this:

`https://git.example.com/company/repo/merge_requests/123/diffs.json?view=inline`

instead of what should be:

`https://git.example.com/company/repo/merge_requests/144/diffs?view=inline`

This problem disappears if navigating back from the incorrectly linked JSON.

**Comment by duduribeiro** [comment]
@bradmerlin What version? 

Seems normal here on master :smiley: 

Thanks []'s

**Comment by stanhu** [comment]
This was fixed in 546dab6da, which will be released in GitLab v7.10 on April 22.

**Comment by Razer6** [comment]
Then close it here
