### ISSUE TITLE
User creation through API doesn't prompt password reset email

### ISSUE THREAD

**Issue by scamargo** [gitlabhq/gitlabhq#9163]
This is a feature / improvement request

Current Behaviour: (v7.9.1)
When creating a user through the API, the user confirmation email does not ask users to do a password reset. This leads to a usability issue since users that have accounts created for them may not know their current username and password, and even if they know the username they may not think to log out and click "reset password".

Desired Behaviour:
When creating a user through the API, the user email generated asks users to reset their password -- as it occurs when creating a user from the admin console.

Please let me know if more information is needed.

**Comment by bbodenmiller** [comment]
Related to https://github.com/gitlabhq/gitlabhq/pull/4805, https://github.com/gitlabhq/gitlabhq/pull/7681, https://github.com/gitlabhq/gitlabhq/issues/6888.

**Comment by bbodenmiller** [comment]
Also might be listed at http://feedback.gitlab.com/.

**Comment by scamargo** [comment]
Have added to feedback tool [here](http://feedback.gitlab.com/forums/176466-general/suggestions/7666299-password-reset-email-sent-out-when-creating-users). Should I remove from issue tracker?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by scamargo** [comment]
Thanks for the heads up. Dont think it's still an issue. Thanks.

El sábado, 7 de noviembre de 2015, Jeroen van Baarsen <
notifications@github.com> escribió:

> We are currently in the process of closing down the issue tracker on
> GitHub, to prevent duplication with the GitLab.com issue tracker. Since
> this is an older issue I'll be closing this for now. If you think this is
> still an issue I encourage you to open it on the GitLab.com issue tracker
> <https://gitlab.com/gitlab-org/gitlab-ce/issues>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitlabhq/gitlabhq/issues/9163#issuecomment-154757923>.
>


-- 
Sergio Camargo
sergio.camargo@utexas.edu <sergiochidalgo@gmail.com>
(813) 380-0641

**Comment by jvanbaarsen** [comment]
@scamargo Thanks for reporting back! :cake:
