### ISSUE TITLE
only line number without code

### ISSUE THREAD

**Issue by markgeek** [gitlabhq/gitlabhq#9165]
![download](https://cloud.githubusercontent.com/assets/888252/7268118/ef4e3bec-e8f7-11e4-9f9b-ab6f91b14491.png)

**Comment by markgeek** [comment]
sometimes I refresh the page, the code was shown. and there is no any js errors in chrome console.

**Comment by markgeek** [comment]
and I also discover it shows part of the code sometimes, not all

**Comment by Razer6** [comment]
@markgeek Is this reproducible on gitlab.com?

**Comment by markgeek** [comment]
@Razer6 no, btw, I installed the 7.10

**Comment by Razer6** [comment]
@markgeek That's strange, because gitlab.com is currently on a release candidate of 7.10

**Comment by markgeek** [comment]
@Razer6 it's only happed when rendering large files as shown above , the code file is 85.2K, perhaps it's something wrong with my configuration.
