### ISSUE TITLE
500 error when sending a webhook to https

### ISSUE THREAD

**Issue by mekanics** [gitlabhq/gitlabhq#9167]
I'm getting a 500 error, when I'm trying to send a webhook to an url with https

production.log
```
Started GET "/testnamespace/theproject/hooks/14/test" for 152.146.17.73 at 2015-04-22 11:36:46 +0200
Processing by Projects::HooksController#test as HTML
  Parameters: {"namespace_id"=>"testnamespace", "project_id"=>"theproject", "id"=>"14"}
Completed 500 Internal Server Error in 55ms

OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: (null)):
  app/models/hooks/web_hook.rb:36:in `execute'
  app/services/test_hook_service.rb:4:in `execute'
  app/controllers/projects/hooks_controller.rb:28:in `test'
```

Here our system informations
```
System information
System:		Debian 6.0.10
Current User:	git
Using RVM:	no
Ruby Version:	2.1.2p95
Gem Version:	2.2.2
Bundler Version:1.6.5
Rake Version:	10.4.2
Sidekiq Version:3.3.0

GitLab information
Version:	7.9.4
Revision:	b10de29
Directory:	/home/git/gitlab
DB Adapter:	mysql2
Using LDAP:	yes
Using Omniauth:	no

GitLab Shell
Version:	2.6.0
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git
```

Am I making something wrong or is it really a bug?

**Comment by stanhu** [comment]
This looks like either an issue with the SSL protocol negotiation or certificate. You may want to test this:

http://stackoverflow.com/a/17895328/1992201

**Comment by stanhu** [comment]
Just ran into a similar issue today. You may need to check your system's certificates file (cacert.pem). You can find the location by running this Ruby command:

```ruby
require 'openssl'
puts OpenSSL::X509::DEFAULT_CERT_FILE
```

For example, the omnibus version stores this file in `/opt/gitlab/embedded/ssl/certs`. Assuming the path of cacert.pem is in /opt/gitlab/You can verify that your certificates work by doing this:

```
openssl s_client -showcerts -connect <SOME HOSTNAME>:443 -CApath /opt/gitlab/embedded/ssl/certs/
```

**Comment by mekanics** [comment]
@stanhu: thx for your help. 

We have a manual installation here. 
the certs are located under `/usr/lib/ssl`

I tried the command above and I'm getting `Verify return code: 21 (unable to verify the first certificate)` 

Does this mean that we have a problem on the end point and not on gitlab?

**Comment by stanhu** [comment]
@mekanics This error means that OpenSSL wasn't able to verify the server's certificate, most likely  because the server hasn't provided the necessary intermediate certificates in the bundle that it sends to the client. If the endpoint is using a self-signed certificate, then you may need to add that certificate into your list of trusted hosts.

**Comment by mekanics** [comment]
@stanhu thank you for your help :beer: 

looks like the intermediate certificate was missing...
