### ISSUE TITLE
Fork transaction error when user has no namespace appears after migration

### ISSUE THREAD

**Issue by Phr33d0m** [gitlabhq/gitlabhq#9169]
Hello, I stumbled upon an issue when I was trying to fork a repo. Googling up the issue I found at least about 4-5 reported issues about it.

I found a super easy solution posted by @pincoded at #5315. Looking up a bit further I found another reference at #6837 by @archony (and #4016) which says [this pull-req](https://github.com/gitlabhq/gitlabhq/pull/5294/files) should have fixed it (in February), but I'm having this issue now with Gitlab 7.9.4.

To the point, this happened **after** migrating our Gitlab installation from one server to another (both running Ubuntu 14.04), so I guess this might be showing up only after a migration.

We were using Gitlab 7.9.2 on our old server (and created the backup using that version) and installed 7.9.2 on the new server, after a couple of days we upgraded to 7.9.4 if this information matters in any way.

This user existed before the migration, so it might be a backup & restore issue?

```
E, [2015-04-22T15:44:44.855541 #10491] ERROR -- : fork-project failed: destination namespace </var/opt/gitlab/git-data/repositories/denis> does not exist.
E, [2015-04-22T15:44:53.030071 #10505] ERROR -- : fork-project failed: destination namespace </var/opt/gitlab/git-data/repositories/denis> does not exist.
E, [2015-04-22T15:46:06.588876 #10695] ERROR -- : fork-project failed: destination namespace </var/opt/gitlab/git-data/repositories/denis> does not exist.
E, [2015-04-22T15:47:21.136222 #10830] ERROR -- : fork-project failed: destination namespace </var/opt/gitlab/git-data/repositories/denis> does not exist.
E, [2015-04-22T15:52:00.180292 #16979] ERROR -- : fork-project failed: destination namespace </var/opt/gitlab/git-data/repositories/denis> does not exist.
E, [2015-04-22T15:52:35.815113 #17175] ERROR -- : fork-project failed: destination namespace </var/opt/gitlab/git-data/repositories/denis> does not exist.
E, [2015-04-22T15:54:12.328755 #17418] ERROR -- : fork-project failed: destination namespace </var/opt/gitlab/git-data/repositories/denis> does not exist.
```

Regards.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
