### ISSUE TITLE
Buttons don't match rest of the interface theme

### ISSUE THREAD

**Issue by Zyphrax** [gitlabhq/gitlabhq#9173]
It would be nice if the buttons match the color of the theme:

![gitlab](https://cloud.githubusercontent.com/assets/966500/7291833/cb2ac4ce-e9d8-11e4-94f6-3f1c091764a2.png)

**Comment by randx** [comment]
We are working on UI redesign. This issue is outdated - lets close it :smile:

**Comment by Razer6** [comment]
@randx I know - and I love the direction :heart: Let's close another issue :)
