### ISSUE TITLE
"GitLab as an OAuth2 client" is kind of weird

### ISSUE THREAD

**Issue by belerweb** [gitlabhq/gitlabhq#9174]
I am reading the "GitLab as an OAuth2 client"(http://doc.gitlab.com/ce/api/oauth2.html) document. It seems the document talking about GitLab as an OAuth2 provider not a client.
For example: If gitlab is a client, gitlab will send request to the oauth2 provider, then oauth2 provider redirect to gitlab. But the document was talking about send request to "http://localhost:3000/oauth/authorize?client_id=APP_ID&redirect_uri=REDIRECT_URI&response_type=code" and the redirect "your app".
So I am a little confused. So would you please improve document?

**Comment by Razer6** [comment]
No, there is a dedicated provider documentation.
