### ISSUE TITLE
cannot add user to group

### ISSUE THREAD

**Issue by xego** [gitlabhq/gitlabhq#9177]
I've Gitlab 7.10 CE with LDAP integration.
Trying to add a new user to a group doesn't work.
The only users prompted are the ones that are already members of the group.
Looking at the ajax calls I've saw that the GET is like that:

http://gitlab/autocomplete/users.json?search=123&per_page=20&active=true&group_id=11

filtered on the group members, removing the group_id param i receive a json with all the matching users as expected.

I'm missing something ?

**Comment by arif-ali** [comment]
confirmed

if you go to http://<hostname>/admin/groups<group_name>, then adding the user to the group doesn't work, whereas if you do it from http://<hostname>/groups/<group_name>/group_members, it works

**Comment by arif-ali** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/1480

**Comment by xego** [comment]
patching users_select.js.coffee seems to me solving the issue, I'm making a merge req

**Comment by dmaslakov** [comment]
Looking to what requests are sent from page `/admin/groups/group_name` I see requests `https://hostname/autocomplete/users.json?search=user_name_search&per_page=20&active=true&group_id=3`.

Note that the group ID is passed so that autocomplete searches for users in the group only. If I get the URL and remove group filter, the return is correct.

(Suggested warkaround helped. Thanks, @arif-ali.)

**Comment by tuminoid** [comment]
Confirming too.

**Comment by frdmn** [comment]
+1

**Comment by merzilla** [comment]
I can confirm that the auto-complete does not work to add members to a group.

**Comment by saily** [comment]
confirmed

**Comment by simongareste** [comment]
confirmed

**Comment by randx** [comment]
Please try this patch - https://github.com/gitlabhq/gitlabhq/commit/f21e26966805a24f777352fe441f51db1ba6e96a

**Comment by xilin** [comment]
confirmed

**Comment by frdmn** [comment]
Anyone already tried @randx' patch?

**Comment by simongareste** [comment]
@frdmn: yes, set it up yesterday, worked fine, I can add users to groups correctly

**Comment by frdmn** [comment]
I just added the changes of this PR and now I stuck with a 500 error if I try to access `http://[gitlab]/admin/groups/[git-group]`:

![bildschirmfoto 2015-05-07 um 10 45 27](https://cloud.githubusercontent.com/assets/944459/7511585/373e785e-f4a6-11e4-90e4-a45cae4026ff.png)

**Comment by simongareste** [comment]
@frdmn Did you restart  your gitlab?

**Comment by frdmn** [comment]
@simongareste Yeah, I've stopped it before I started with the rake tasks.

**Comment by frdmn** [comment]
I think I just wait for a new release that includes this fix.

**Comment by Sevyls** [comment]
using omniauth-shibboleth as a provider, i am getting the same problem.

**Comment by robertd** [comment]
For users stuck at GitLab 7.10.1 just go to group/repo members page and add it there. You will not be able to do it through admin panel.

**Comment by th3m4ri0** [comment]
As @robertd said, go to https://git.domain.com/groups/yourgroup/group_members to add people. This is a workaround.

**Comment by dosire** [comment]
This is fixed in 7.11
