### ISSUE TITLE
Global Slack service channel field not be stored

### ISSUE THREAD

**Issue by likol** [gitlabhq/gitlabhq#9181]
when I settings slack in Admin area, channel field always empty.
but when I settings in project service, it's work.

Version: GitLab 7.9.4 b10de29

**Comment by stanhu** [comment]
Oh, I see the issue. It looks like the permitted settings in `admin/services_controller.rb` does not include some fields in `project_services/services_controller.rb`.

@DouweM, should we just make these two controllers share the same list of fields given that it's easy to forget to update in both places?

**Comment by DouweM** [comment]
@stanhu Yes, they should. It's probably easiest to make it a constant on `Projects::ServicesController`, since that where contributors will be looking. On a similar note, part of these two controllers' `_form` partials should go into `view/shared`.

**Comment by stanhu** [comment]
@DouweM, good idea. I'll work on this.
