### ISSUE TITLE
hipchat service for git integration no longer works

### ISSUE THREAD

**Issue by joejoseph00** [gitlabhq/gitlabhq#9182]
our admins upgraded to 7.10 last night and since then our hipchat service integration no longer works.

**Comment by stanhu** [comment]
Please tell your admin to upgrade. This was fixed last night:https://about.gitlab.com/2015/04/23/gitlab-7-dot-10-dot-0-omnibus-patch-release/

**Comment by joejoseph00** [comment]
Yes, that works, they applied the temporary fix and it's working thanks!
