### ISSUE TITLE
Sidebar overlaps commit statistics

### ISSUE THREAD

**Issue by Axure** [gitlabhq/gitlabhq#9188]
![2015-04-24 19 51 03](https://cloud.githubusercontent.com/assets/3424317/7318283/b3124a26-eabc-11e4-89fd-6ef366c323de.png)
At the zoom level of 150%, rMBP 13 at 1680*1050.

At 125%, there is overlap. At 175%, the sidebar contracts.

**Comment by Razer6** [comment]
This has been fixed with GitLab 8.0
