### ISSUE TITLE
'Comment & close' button sends two distinct email notifications

### ISSUE THREAD

**Issue by danseely** [gitlabhq/gitlabhq#9190]
Users who are subscribed to an issue are notified via email (if email notifications are set up) when events on the issue fire -- including both new comments and the issue being marked as closed. Currently, when a comment is made by using  the 'comment & close' button to simultaneously leave the comment and close the issue, any subscribed users receive two distinct email notifications: one each for the comment and the issue being closed.

It would be helpful if these two notifications could be consolidated into one when the 'comment & close' button is used.

**Comment by Razer6** [comment]
This is in the works.
