### ISSUE TITLE
Alignment issues of selects on the issue page

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#9192]
![screenshot from 2015-04-24 20-15-38](https://cloud.githubusercontent.com/assets/1961699/7325482/c1ff2c28-eabe-11e4-9823-e315fe913f4b.png)

**Comment by csware** [comment]
This is a regression of 7.10.

**Comment by dreis2211** [comment]
This will be fixed with the next release. See https://gitlab.com/gitlab-org/gitlab-ce/issues

For further information, take a look here:
#9243
#9244

Cheers
