### ISSUE TITLE
Merge Request takes like 2 seconds

### ISSUE THREAD

**Issue by tonicbupt** [gitlabhq/gitlabhq#9198]
I run Gitlab on my server and data is stored within an SSD volume, but I found it takes like 2 seconds to accept an merge request even the repository is very small and contains only 5 files. Then I look into code and print the time takes for each function, I found

    merge_repo.git.push(default_options, :origin, merge_request.target_branch)

 [here](https://github.com/gitlabhq/gitlabhq/blob/master/lib/gitlab/satellite/merge_action.rb#L33) takes 2 seconds. It's only a push and runs on SSD, shouldn't take this much time. Please help me find out reason.

P.S. I found that `Grit` is no longer maintained and the author suggests [rugged](https://github.com/libgit2/rugged) instead, I'm not sure if this is because of the actions of `Grit`.

**Comment by Razer6** [comment]
Likely to be fixed in GitLab 8.0 where we use rugged instead of grit with satellites.
