### ISSUE TITLE
GitLab 7.10.0 line numbers not lining up

### ISSUE THREAD

**Issue by johnjelinek** [gitlabhq/gitlabhq#9202]
![word-count_word-count_js_at_master___gitlab](https://cloud.githubusercontent.com/assets/873610/7333562/9d35da7e-eb39-11e4-9ae0-a7af2cc478b3.png)

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
