### ISSUE TITLE
View is broken after upgrade 7.10

### ISSUE THREAD

**Issue by jigsawIV** [gitlabhq/gitlabhq#9205]
I upgraded from 7.2 to 7.10 and after that my view is broken.
Any ideas? Or is it a bug?

![bildschirmfoto 2015-04-26 um 19 25 03](https://cloud.githubusercontent.com/assets/5776577/7338369/01cbf368-ec4a-11e4-82d7-f5918e553d85.png)

**Comment by m-a-r-c-o** [comment]
Did you try to reload the page with CTRL+F5 (e.g. Chrome or Firefox). Could be possible that the old css styles (delivered by 7.2) are cached by the browser.

Only an idea...

**Comment by jigsawIV** [comment]
I tried this but unfortunately this does not fix the problem.
Is there a way to fix this? Rerun the upgrade script? 

Thanks

**Comment by stanhu** [comment]
Are you using the omnibus version or a source install?

**Comment by jvanbaarsen** [comment]
@jigsawIV Did you empty the cache of your browser? Is the problem also present on other machines?

**Comment by jigsawIV** [comment]
@stanhu: source install
@jvanbaarsen: yes, I deleted the cache and tried other browsers too

**Comment by stanhu** [comment]
@jigsawIV Did you try to clear the assets and recompile?

```
sudo -u git -H bundle exec rake assets:clobber RAILS_ENV=production
sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production
```

**Comment by jigsawIV** [comment]
It hat gotten worse
![bildschirmfoto 2015-04-28 um 20 42 42](https://cloud.githubusercontent.com/assets/5776577/7377536/3c52f416-ede7-11e4-9d3b-e005135a082e.png)

**Comment by stanhu** [comment]
It looks like the CSS files are not available. Can you check your browser's network activity (e.g. Inspect Element -> Network) and see what files it is trying to request? Then you should check your filesystem if they do. You may need to flush your browser's cache too.

How are you running GitLab? Are you running it in production or development mode?

**Comment by jigsawIV** [comment]
I used the upgrade script. Is there a way to downgrade back to another version? I'm desperate :(

**Comment by jigsawIV** [comment]
I flushed the cache. It looks like some files are missing

GET https://gitlab.barrynorman.de/assets/application-37986e7132260a85f26fd17881eef504.css 
sign_in:13 GET https://gitlab.barrynorman.de/assets/application-d78e3aebfdf9aa068bc71234b2bfea02.js 404 (Not Found)
sign_in:33 GET https://gitlab.barrynorman.de/assets/logo-white-96c5cdf684c799df72c830d36ecc7fec.png 404 (Not Found)
sign_in:12 GET https://gitlab.barrynorman.de/assets/print-1df3ea9b8ff148a6745321899e0cb213.css 404 (Not Found)

**Comment by stanhu** [comment]
Can you find the assets directory in your deployment? If they exist, you may need to check the permissions. You may want to try compiling the assets again:

https://github.com/gitlabhq/gitlab-public-wiki/wiki/Trouble-Shooting-Guide
https://github.com/gitlabhq/gitlabhq/issues/1598

**Comment by jigsawIV** [comment]
I found this in the nginx log and many more

*1591 open() "/home/git/gitlab/public/assets/print-1df3ea9b8ff148a6745321899e0cb213.css" failed (2: No such file or directory)

**Comment by jigsawIV** [comment]
I can't find those files, but the assets are there

application-82ad898e8638ec932704fd2f4b13cee5.css	   icon_sprite-bc1d85aea6973bdd6c6e55294354a644.png
application-82ad898e8638ec932704fd2f4b13cee5.css.gz	   images-77127109e3b8cce6bd33f7f7df911770.png
application-99eaa5fd184a74a5aff87acc087a9b62.js		   jquery-ui
application-99eaa5fd184a74a5aff87acc087a9b62.js.gz	   logo-white-0b53cd4ea06811d79b3acd486384e047.png
authbuttons						   manifest-4408829e97e200b3d7c6b85155468644.json
bg_fallback-696eadba7863f22baeab1d095aa0decf.png	   monokai-scheme-preview-fef16a6466f84289d7513b842d9e6c7d.png
bg-header-6654293c9981a5694da5c8bc12fc9348.png		   move-b11a372f4906b45d6bf0c36bd1fa4630.png
bootstrap						   no_avatar-fd406ccede8cb1881f20921c8bfa169b.png
brand_logo-83a5201d76d99b08d6ee58076626a452.png		   no_group_avatar-4ca5090e0234343b193d40a0509ad4af.png
chosen-sprite-cd8ea45b9fab540876a0c22bffd75824.png	   onion_skin_sprites-fb7f0b4bac7d68b5c67459cf7bdec26e.gif
dark-scheme-preview-db1d59f3d00616e123ad54419ac7b33b.png   print-a6a4a821dcebd88fd948e412660d1424.css
diff_note_add-2612ba2e18b421e2025d095374dd65aa.png	   print-a6a4a821dcebd88fd948e412660d1424.css.gz
doorkeeper						   progress_bar-55c3bbf6e4a7233afc3d85ec086d64dc.gif
emoji							   select2-221e01348131f54ea33a7a5f6e2b686b.png
favicon-d6aa61c7c265900a7d4c45d3ac2b461f.ico		   select2-spinner-cb8785807f863e310841ba5272a95a7c.gif
FontAwesome-a59e461c692c4fee8b72779b93d6fde1.otf	   select2x2-47a0b51b434a832dd65b47f2240cc6be.png
fontawesome-webfont-23fd64af69bb51b265085d0517fcb8b9.woff  slider_handles-27654dc156fd552582b50895d6f2c124.png
fontawesome-webfont-2bd78e146d2c39c68fec379032fb4572.eot   solarized-dark-scheme-preview-9507a88c30756616f01369f47a98603d.png
fontawesome-webfont-4f2d979184ad52d024b355b94be5ae55.svg   solarized-light-scheme-preview-37a35971920b6fd66a9a47a481de2fe4.png
fontawesome-webfont-760cf8e00e269dc08fb693871c542203.ttf   swipemode_sprites-3698c0d95f9bfdcf08623b7e1a69a94a.gif
gitorious-logo-black-48c94a358e5f47735f3e291c380445f6.png  switch_icon-511aba5c7b6266dbba165777c9eab92d.png
gitorious-logo-blue-96c891e73bbe7a99b25f01cfd6a18a55.png   trans_bg-a3555e272524c4a00c47124afb9ef0fb.gif
icon-link-27898e926c21156aa4dbdbb756d23f1c.png		   white-scheme-preview-0d2d57afe04ebc7de64a30a97b972dfe.png
icon-search-9c687809297849275d45a3836f801f18.png

**Comment by jigsawIV** [comment]
Puhh... Thanks to everyone, who helped me :)
I have no idea what I did, but after restarting gitlab, nginx and precompiling the assets, its no working again :+1:

**Comment by stanhu** [comment]
Glad to hear it. I've had similar issues with Rails assets compiling not working the first time. I suspect the server cache has something to do with it, since the browser may have been trying to serve the old CSS that were deleted in the clobber step.

**Comment by jigsawIV** [comment]
Thanks @stanhu for your help. I really appreciate it :)
