### ISSUE TITLE
issue assignee select missing after 7.9.1 to 7.10.0 upgrade

### ISSUE THREAD

**Issue by nazrhyn** [gitlabhq/gitlabhq#9218]
We have already had to revert to our 7.9.1 snapshot, so I don't have a screenshot of this, but it's like the issue edit view in the screenshot, below, from 7.9.1, except that the select for assignee is missing.

![image](https://cloud.githubusercontent.com/assets/1672405/7371534/9923cf38-ed8f-11e4-98e0-feb0c4021d93.png)

For new issue creation, the "Assign to Me" button is present, spaced over by its left margin, but no select there either. As an aside, in the views for adding users to groups and projects, the user selects are properly rendered and functional.

I'm not sure if this is an issue with our upgrade or if this is an actual issue. I'm sure some folks will chime in to say whether or not they're seeing it in their installs. Given how easy the upgrade process for the filesystem is, it seems unlikely it had something to do with that. I wonder if it was something with the database migration?

Any ideas would be appreciated! Thanks for the hard work and for a fantastic product!

**Comment by stanhu** [comment]
@nazrhyn I'm not seeing this in v7.10 omnibus version. Are you using a source install? If so, did you recompile the static assets?

```
sudo -u git -H bundle exec rake assets:clobber RAILS_ENV=production
sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production
```

**Comment by nazrhyn** [comment]
Our base install was using the Bitnami image, but since that, we've been performing manual incremental upgrades. After we perform the fetch andcheckout, this is what we have been doing:

```sudo -u git -H bundle install --without development test postgres --deployment
sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production
sudo -u git -H bundle exec rake assets:clean RAILS_ENV=production
sudo -u git -H bundle exec rake cache:clear RAILS_ENV=production```

Is `clean` different than `clobber -> recompile`? Thanks for the response!

**Comment by stanhu** [comment]
Yes, I don't think `clean` recompiles the assets. I think you may want to run the `precompile` step. Here's the difference between `clean` and `clobber`:

http://www.dixis.com/?p=735

**Comment by nazrhyn** [comment]
Great, we will give this a try and I'll update this with the results. Thanks.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by nazrhyn** [comment]
I apologize; the resource who performs the updates never updated me and it slipped my mind. It appears that this has been fixed either by the suggested rake commands or a following upgrade.

Thanks for checking back in and for a great product!
