### ISSUE TITLE
Deny non-fast-forward push for developers

### ISSUE THREAD

**Issue by choehwanjin** [gitlabhq/gitlabhq#922]
Current gitlab implementation adds a developer with "RW+" gitolite permission.
According to the gitolite manual, "RW+" permission allows ref deletion.
This means every "developer" in gitlab can delete history of their project.

In my opinion, this behavior is dangerous.
I suggest to use "RW" permission for developers and "RW+" for project masters.

**Comment by zba** [comment]
so why it closed ?

**Comment by dosire** [comment]
@zba Since you asked I'll reopen it.

**Comment by connorshea** [comment]
@zba @dosire We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues).

Apologies for the inconvenience!
