### ISSUE TITLE
Email does not take port into account

### ISSUE THREAD

**Issue by tedostrem** [gitlabhq/gitlabhq#9225]
I have to run gitlab on port 5000 due to lack of an ICP license on our chinese staging
server.

The activation email that is sent to users after registration is not taking this into account
and does not append the port to the url.

**Comment by stanhu** [comment]
How are you configuring this port? Are you running the omnibus or source install?

**Comment by tedostrem** [comment]
I noticed that the problem I'm encountering is due to something else so I have closed this issue and opened the following new one:
https://github.com/gitlabhq/gitlabhq/issues/9230
