### ISSUE TITLE
Wrong timezone used in project RSS entries

### ISSUE THREAD

**Issue by gentakojima** [gitlabhq/gitlabhq#9226]
The last updated time on the RSS shows fine in UTC, but the entries show the time as UTC, when they are actually in local time.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
  <title>Group feed - citius</title>
  <link href="/groups/citius.atom" rel="self" type="application/atom+xml"/>
  <link href="/groups/citius" rel="alternate" type="text/html"/>
  <id>https://xxx.es/projects</id>
  <updated>2015-04-29T08:46:08Z</updated>
  <entry>
    <id>tag:gitlab.citius.usc.es,2015-04-29:3371</id>
    <link href="https://xxx.es/citius/thesis-template/commit/bd11a9c2239e673da8042906241e8a265c517b71"/>
    <title>Jorge Suárez de Lis pushed to project branch master at citius / thesis-template</title>
    <updated>2015-04-29T10:46:08Z</updated>
    <media:thumbnail width="40" height="40" url="https://secure.gravatar.com/avatar/47b642348d639a6e21a1506dbf085479?s=40&amp;d=identicon"/>
    <author>
```

It says `<updated>2015-04-29T10:46:08Z</updated>`, but it should be `<updated>2015-04-29T10:46:08CET</updated>` or `<updated>2015-04-29T08:46:08Z</updated>`

Please note the global RSS `updated` time is ok.

**Comment by jeffi7** [comment]
@gentakojima I saw exactly the same issue with GitLab CE v7.9.4 and now found it was fixed in v7.11.0.

https://github.com/gitlabhq/gitlabhq/commit/dfb58234a1b2b354d82f936086737f9f3073b68e Fix bug with default timezone en RSS gitlab events

**Comment by maxlazio** [comment]
@jeffi7 Thanks for linking that! @gentakojima in light of the above comment I am going to close this issue but if you encounter it in the latest version feel free to reopen this issue.

**Comment by gentakojima** [comment]
Thank you guys! It seems fixed indeed :)
