### ISSUE TITLE
Can't specify port 5000 in external_url

### ISSUE THREAD

**Issue by tedostrem** [gitlabhq/gitlabhq#9230]
I need to run gitlab on port 5000 due to lack of ICP license on a chinese server and when I do the following change to gitlab.rb the server becomes inaccessible
external_url 'http://vhost.mydomain.cn:5000'

If I change it to port 80 gitlab runs fine except that notification emails being sent out are
omitting the port and assumes port 80 and thus the URL in the emails is wrong.

I'm using the genezys/gitlab docker image which means that the server is running on port 80 inside of the container with a nginx reverse proxy on port 5000 in front.

**Comment by stanhu** [comment]
If you set the config to 'http://vhost.mydomain.cn:5000', then GitLab will listen on port 5000 unless you override the port with the `listen_port` option:

https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/nginx.md#setting-the-nginx-listen-port

**Comment by tedostrem** [comment]
Thanks for such a fast reply.
My config now contains:
```
external_url 'http://vhost.mydomain.cn:5000'
nginx['listen_port'] = 80
```
But I'm getting the same error after restaring gitlab: 502 Bad Gateway

**Comment by stanhu** [comment]
What version are you running? It looks like the genezys/gitlab image only has v7.8.4. What does `netstat -a` show in your Docker image?

**Comment by tedostrem** [comment]
```
root@a776f202ebe5:/# netstat -a
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 localhost:43272         *:*                     LISTEN
tcp        0      0 localhost:http-alt      *:*                     LISTEN
tcp        0      0 *:http                  *:*                     LISTEN
tcp        0      0 *:ssh                   *:*                     LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
udp6       0      0 localhost:44939         localhost:44939         ESTABLISHED
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     221257   /tmp/.s.PGSQL.5432
unix  2      [ ACC ]     STREAM     LISTENING     221127   /var/opt/gitlab/redis/redis.socket
unix  2      [ ACC ]     STREAM     LISTENING     221450   /var/opt/gitlab/gitlab-rails/sockets/gitlab.socket
unix  3      [ ]         STREAM     CONNECTED     221579
unix  3      [ ]         STREAM     CONNECTED     221666   /var/opt/gitlab/redis/redis.socket
unix  3      [ ]         STREAM     CONNECTED     221658
unix  3      [ ]         STREAM     CONNECTED     221693   /var/opt/gitlab/redis/redis.socket
unix  3      [ ]         STREAM     CONNECTED     221687
unix  3      [ ]         STREAM     CONNECTED     221777
unix  3      [ ]         STREAM     CONNECTED     221601   /tmp/.s.PGSQL.5432
unix  3      [ ]         STREAM     CONNECTED     221390
unix  3      [ ]         STREAM     CONNECTED     221694
unix  3      [ ]         STREAM     CONNECTED     221663
unix  3      [ ]         STREAM     CONNECTED     221599   /var/opt/gitlab/redis/redis.socket
unix  3      [ ]         STREAM     CONNECTED     221577
unix  3      [ ]         STREAM     CONNECTED     221692
unix  3      [ ]         STREAM     CONNECTED     221688   /tmp/.s.PGSQL.5432
unix  3      [ ]         STREAM     CONNECTED     221778   /var/opt/gitlab/redis/redis.socket
unix  3      [ ]         STREAM     CONNECTED     221659   /tmp/.s.PGSQL.5432
unix  3      [ ]         STREAM     CONNECTED     221580   /var/opt/gitlab/redis/redis.socket
unix  3      [ ]         STREAM     CONNECTED     221389
unix  3      [ ]         STREAM     CONNECTED     221578   /var/opt/gitlab/redis/redis.socket
unix  3      [ ]         STREAM     CONNECTED     221664   /var/opt/gitlab/redis/redis.socket
unix  3      [ ]         STREAM     CONNECTED     221665
unix  3      [ ]         STREAM     CONNECTED     221695   /var/opt/gitlab/redis/redis.socket
unix  3      [ ]         STREAM     CONNECTED     221598
unix  3      [ ]         STREAM     CONNECTED     221600
```

**Comment by tedostrem** [comment]
I'm also getting a lot of 500 errors when doing different actions in the GUI. like for instance adding a SSH key. Maybe the docker image is just poorly configured?

**Comment by stanhu** [comment]
Does this mean that you can access GitLab now? Does `/var/log/gitlab/gitlab-rails/production.log` show any error messages?

**Comment by tedostrem** [comment]
I can access gitlab as long as my external_url is pointing to port 80. (Which is undesirable due to the links generated)

Looking at the log and I'm actually seeing the cause of my 500 errors here.
```
Completed 500 Internal Server Error in 90ms

Errno::ENOMEM (Cannot allocate memory - ssh-keygen):
  lib/gitlab/popen.rb:23:in `popen'
  app/models/key.rb:89:in `block in generate_fingerprint'
  app/models/key.rb:86:in `generate_fingerprint'
  app/controllers/profiles/keys_controller.rb:20:in `create'
```

Running on an ec2 micro instance at the moment. Possible that memory is not enough?

**Comment by stanhu** [comment]
Yes, you'll need more memory. See the requirements:

https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/requirements.md#memory

What version of GitLab are you using? When you switch `external_url` to 5000, what does the `netstat -a` output show? I have a feeling you are using an older version of GitLab that does not support the `listen_port` option.

**Comment by tedostrem** [comment]
Thanks a lot for your help Stan. I modified the docker file to use the latest version of gitlab
and reinstalled everything. Email notifications are working fine and my 500 errors seems to be gone.
I'm gonna close this issue now. Thank you !

**Comment by stanhu** [comment]
@tedostrem Glad to hear it!
