### ISSUE TITLE
7.9 -> 7.10 upgrade docs are missing

### ISSUE THREAD

**Issue by robertd** [gitlabhq/gitlabhq#9231]
It looks like there is no 7.9 -> 7.10 upgrade docs...

**Comment by robertd** [comment]
Cl0osing this since @jverdeyen created one... thanks.

**Comment by robertd** [comment]
Do we need to add this into upgrade guide?
```
 sudo -u git -H bundle exec rake acts_as_taggable_on_engine:install:migrations RAILS_ENV=production
```

**Comment by stanhu** [comment]
I think there are some conflicts with pulling in all those migrations. See:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/577
