### ISSUE TITLE
Wrong backup right

### ISSUE THREAD

**Issue by Soullivaneuh** [gitlabhq/gitlabhq#9235]
Seems the commit which restrict backup file permissions (https://github.com/gitlabhq/gitlabhq/commit/61c06c5#diff-4db7b038f22384efaa49af8c74b8a4f4R21), I have the following backup list (since "avril 27 02:00"):

```bash
~/server-backup$ ls -l gitlab/
total 7015560
-rw-r--r-- 1 git git 247992320 avril 22 02:00 1429660853_gitlab_backup.tar
-rw-r--r-- 1 git git 248023040 avril 23 02:00 1429747251_gitlab_backup.tar
-rw-r--r-- 1 git git 248023040 avril 24 02:00 1429833655_gitlab_backup.tar
-rw-r--r-- 1 git git 248023040 avril 25 02:01 1429920071_gitlab_backup.tar
-rw-r--r-- 1 git git 248023040 avril 26 02:00 1430006452_gitlab_backup.tar
-rw------- 1 git git 248094720 avril 27 02:00 1430092845_gitlab_backup.tar
-rw------- 1 git git 248207360 avril 28 02:00 1430179253_gitlab_backup.tar
-rw------- 1 git git 248207360 avril 29 02:00 1430265655_gitlab_backup.tar
-rw------- 1 git git 248268800 avril 30 02:01 1430352076_gitlab_backup.tar
-rw------- 1 git git 248289280 mai    1 02:01 1430438462_gitlab_backup.tar
-rw------- 1 git git 248442880 mai    2 02:00 1430524845_gitlab_backup.tar
-rw------- 1 git git 248442880 mai    2 11:25 1430558732_gitlab_backup.tar
```

That's a big issue cause all my scripts that upload backup on another server fails, caused by permissions restrict.

Please take care about that, it's pretty sensitive. We can't change permissions of this kind of file without expect any side effect.

Could be possible to permit to change permissions settings on gitlab.yml or, at least, revert the commit?

Thanks.

**Comment by Soullivaneuh** [comment]
I can maybe work on a PR about that, but can it be merge on 7.10 for a patch version?

**Comment by huglester** [comment]
I think that's the main case, that backups should not be readable by everyone by default. so something like setting probably would be a good thing.

**Comment by Soullivaneuh** [comment]
> that backups should not be readable by everyone by default

I understand the point of view. But changing this kind of things can completely brake external processes.

It should be modified with care and, at least, be more visible on upgrade notices. (including upgrader doc).

> something like setting probably would be a good thing

I fully agree for that. :+1:

**Comment by thelok** [comment]
+1, we're manually changing the permissions for now since it broke our cron schedulers due to permissions but a setting would be great.

**Comment by stanhu** [comment]
Added support here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/756

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
