### ISSUE TITLE
Markdown does not support style

### ISSUE THREAD

**Issue by netroby** [gitlabhq/gitlabhq#9242]
```
<table>
<tr>
<td style="vertical-align:middle" rowspan="4" > <a href="versionCheck/home">版本检查</a></td>
<td> <a href="versionCheck/home#ios-user-app-version-check">versionCheck/iosuserapp</a></td>
<td> IOS用户app版本检查 </td>
</tr>
<tr>
<td> <a href="versionCheck/home#ios-company-app-version-check">versionCheck/ioscorpapp</a>  </td>
<td> IOS商家app版本检查 </td>
</tr>
<tr>
<td> <a href="versionCheck/home#android-user-app-version-check">versionCheck/androiduserapp</a></td>
<td> Android用户app版本检查 </td>
</tr>
<tr>
<td> <a href="versionCheck/home#android-company-app-version-check">versionCheck/androidcorpapp</a> </td>
<td> Android商家app版本检查 </td>
</tr>
</table>
```

The html have one style attr
```
<td style="vertical-align:middle" rowspan="4" > 
```

but it not working at all

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

**Comment by thiagoarrais** [comment]
Any updates on this? I'm seeing something like it in 8.10.6 (didn't test against master yet).

[The feature request forum][1] link doesn't work any longer (leads to a generic about page) and [searching for "markdown style"][2] in the issue tracker doesn't yield anything obviously related.

 [1]: http://feedback.gitlab.com/
 [2]: https://gitlab.com/search?utf8=%E2%9C%93&snippets=&scope=issues&search=markdown+style
