### ISSUE TITLE
Admins should not have access to project/repository if they are not member of the project

### ISSUE THREAD

**Issue by zimmski** [gitlabhq/gitlabhq#9251]
(I asked this question in the IRC but did not get any response. Internally, we marked this as a security bug.)
All our projects are "private". Therefore an admin user cannot see these projects in the "explore" views but an admin user can see them in the administration area. This is afaik OK. However, if an admin user knows the group and project name the user can use the usual URIs to access the projects information. Furthermore the user can clone these repositories.
We think that this should be changed, or at least it should be changeable via a configuration setting. Even an admin user should not have access (beyond the admin area) to a project if the user is not a member of the project/group of the project.

**Comment by maxlazio** [comment]
How would an admin be able to administer the instance? For example, user complains that they cannot clone and they say it is broken. Admin cannot verify if it is the instance that is broken or something misconfigured on the users side. Making this configurable is also questionable, if they are an admin, what is stopping them from turning this on?

Also, this question is for the [feedback tracker](http://feedback.gitlab.com) so could you move the discussion there?

**Comment by zimmski** [comment]
OK, http://feedback.gitlab.com/forums/176466-general/suggestions/7847967-admins-should-not-have-access-to-project-repositor

This is not an unusual request as this is e.g. implemented within Atlassian products like Jira. My concern is the default accessibility of content.
An admin would still have access through the admin area -> "/admin/projects/..." So the general project configuration is accessible by an admin. However the **content** is not, as an admin is currently not by default a member of the project. The described problems are therefore still debuggable by explicitly adding an admin as a member to the project. An example security issue that arises by not securing the content of a project by default is that a compromised ssh key of an admin can clone every repository even though the admin is not a member of any project.
