### ISSUE TITLE
Question: Why is my GitLab after update looks broken?

### ISSUE THREAD

**Issue by Piioo** [gitlabhq/gitlabhq#9266]
New version GitLab 7.10.2 ecd8dc8

The css is not working well and i got this in the browser console:

Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 144dpi)

![bildschirmfoto 2015-05-08 um 11 35 12](https://cloud.githubusercontent.com/assets/4640423/7533991/65516492-f576-11e4-838a-e0940539017a.png)

**Comment by stanhu** [comment]
Are you using the omnibus or installing from source?

If you are doing the latter, you may need to recompile your assets:

```
# Clean up assets and cache
sudo -u git -H bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=production
```

**Comment by KaiSoellch** [comment]
same problem here - i used omnibus package

**Comment by NemoOudeis** [comment]
have the same problem, installed gitlab via omnibus package

**Comment by Razer6** [comment]
Please head over to the omnibus tracker for issues related to the full stack install.
