### ISSUE TITLE
How can I change email if didn't get confirm email?

### ISSUE THREAD

**Issue by jsveron23** [gitlabhq/gitlabhq#9274]
![screenshot 2015-05-10 17 41 36](https://cloud.githubusercontent.com/assets/156895/7553595/997e137e-f73c-11e4-9352-b2989702f122.png)

I just installed Gitlab and log Admin. But I couldn't change my default email, because I didn't get confirm email.

**Comment by stanhu** [comment]
You can request a new confirmation e-mail at the login screen:

![image](https://cloud.githubusercontent.com/assets/963826/7554609/668b63d0-f6e3-11e4-94ca-c3ab141f6f90.png)

See bottom right. We should probably add a link in that screen to do the same.

**Comment by jsveron23** [comment]
ah... I should do sign out,  thank you.

**Comment by masedos** [comment]
How to get a new resend confirmation e-mail for how write a wrong e-mail, I should write masedos@gmail.com than I wrote masedos@gmail.co
anyone can help me.

**Comment by masedos** [comment]
How to get a new resend confirmation e-mail for ho wrote a wrong e-mail, I should write masedos@gmail.com than I wrote masedos@gmail.co
anyone can help me.
