### ISSUE TITLE
Enabling gitlab ci causes nginx error

### ISSUE THREAD

**Issue by DazWorrall** [gitlabhq/gitlabhq#9279]
On an omnibus install, I enabled gitlabci in gitlab.rb according to the docs (setting `ci_external_url`), ran `gitlab-ctl reconfigure` without error but I couldn't reach the CI server. Checking the logs, nginx failed to reload with the following error:

    2015-05-11_08:38:52.94967 2015/05/11 09:38:52 [emerg] 937#0: could not build the server_names_hash, you should increase server_names_hash_bucket_size: 32

I put `server_names_hash_bucket_size 64;` into `/var/opt/gitlab/nginx/conf/nginx.conf` and manually sent a `HUP` and that solved it. 2 issues then: 

1. The default bucket size is too small
2. The failure to reload nginx didnt raise an error when I ran `gitlab-ctl reconfigure`

**Comment by clodo** [comment]
Hola @DazWorrall,
I had the same problem and solved it by putting this line ```nginx['custom_nginx_config'] = "server_names_hash_bucket_size 64;"``` in the config file ```/etc/gitlab/gitlab.rb``` and then ran ```gitlab-ctl reconfigure```, that way the setting persist and the nginx starts normally.
Saludos!

**Comment by Razer6** [comment]
This will be fixed in GitLab 8.0 in which CI and GitLab are one single package.

**Comment by schmidp** [comment]
If you enable mattermost, the same issue appears again.

**Comment by kostyrevaa** [comment]
@schmidp +1
