### ISSUE TITLE
cannot add line comment using Side-by-Side diff

### ISSUE THREAD

**Issue by shlimp** [gitlabhq/gitlabhq#9283]
using inline diff, if you hover over the row you have the option to add line comment.
it's not possible using Side-by-Side diff

**Comment by kobymeir** [comment]
+1

**Comment by rockneverdies55** [comment]
:+1:

**Comment by Zaba999** [comment]
:+1:

**Comment by stanhu** [comment]
Proposed changes to support this here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/810

**Comment by stanhu** [comment]
FYI, this will probably make it in GitLab v7.13 on July 22, not the next release (v7.12).
