### ISSUE TITLE
Gitlab 7.10.4 Forbidden Error

### ISSUE THREAD

**Issue by nixdaemon** [gitlabhq/gitlabhq#9297]
After upgrading to Gitlab v7.10.4 i am getting Forbidden error. If i go ahead and do "flushall" in redis database it works for a while and then after some time it gives me "Forbidden" error. Also the UI looks broken. I have restarted my redis instance after the upgrade and gitlab and nginx. I am pretty much sure its not a nginx error because if i go ahead and try to run the application on local port it does the same thing. Any help would be appreciated.

Thanks,
Robin

**Comment by stanhu** [comment]
This sounds like a Rack Attack ban on the IP due to excessive number of invalid login attempts or failed git logins. Are your nginx logs showing lots of 401 errors? This thread talks about issues with false positives:

https://gitlab.com/gitlab-org/gitlab-ce/issues/1171

**Comment by nixdaemon** [comment]
There were no errors logged in the nginx error log file for gitlab but definitely it was rack attack. Thanks for pointing that out.

**Comment by stanhu** [comment]
That's odd. There should also be error messages printing in the /var/log/gitlab/gitlab-rails/production.log indicating that an IP was banned. Out of curiosity, how did you resolve this? Did you just disable Rack Attack?

**Comment by nixdaemon** [comment]
Yes, i disabled the Rack Attack.

**Comment by zhuima** [comment]
@robintiwari  How to prohibit
