### ISSUE TITLE
Gitlab does not handle ssh url and/or ssh keys private/internal projects

### ISSUE THREAD

**Issue by doekia** [gitlabhq/gitlabhq#9303]
When trying to fetch/pull a project gitlab still asking for password when project are not public.
This may be related to issue #8979 

Client system, proper ssh private/public key
Gitlab deploy key for the project is copy of the client public key

**Repo is public**
git pull / git fetch / git clone over https://gitlabserver/owner/project.git works as expected (no pass/user question)
v v v v v
local repo is properly synchronized 

**Repo is private or internal**
git pull / git fetch / git clone over https://gitlabserver/owner/project.git  credential is requested
git pull / git fetch / git clone over https://owner@gitlabserver/owner/project.git  credential is requested
git pull / git fetch / git clone over git@gitlabserver:owner/project.git  credential is requested
v v v v v
If credential provided local repo is synchronized

**Repo is public**
git pull / git fetch / git clone over git@gitlabserver:owner/project.git  
v v v v v v
debug1: Connecting to gitlabserver [1.1.1.1] port 22.
debug1: Host 'gitlabserver' is known and matches the ECDSA host key
debug1: Offering RSA public key: /var/www/clients/client1/web43/.ssh/gitlab.key
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: read PEM private key done: type RSA
debug1: Authentication succeeded (publickey).
Authenticated to gitlabserver ([1.1.1.1]:22).
debug1: Sending command: git-upload-pack 'owner/project.git'
debug1: Exit status 1
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
