### ISSUE TITLE
[Security vulnerability] Enable SSL peer verification for webhooks

### ISSUE THREAD

**Issue by harbulot** [gitlabhq/gitlabhq#9304]
This is a follow up of #6162.

Commit 317362666be9358a8fccb4e0e9c4640bb1a2ef71 disabled peer verification when using a webhook with SSL/TLS.

Unfortunately, this makes the connection vulnerable to MITM attacks. The new behaviour of HTTParty was addressing this problem. Re-introducing a potential vulnerability explicitly when it has been fixed by an underlying library doesn't seem great.

Although this has been refactored since, this security vulnerability is still present in the latest code (commit 35729671fb3a123ddeb7b2b1cda446fd661bd4e6), in a couple of places in this file at least:

https://github.com/gitlabhq/gitlabhq/blob/master/app/models/hooks/web_hook.rb#L42

Please don't use `verify: false`, it introduces a security vulnerability.

This isn't an issue that requires a specific code sample and debugging code. Rather, it has to do with making sure HTTPS is used correctly. More background about this general problem can be found here: http://security.stackexchange.com/questions/22965/what-is-the-potential-impact-of-these-ssl-certificate-validation-vulnerabilities

**Comment by jvanbaarsen** [comment]
@jacobvosmaer What do you think about this?

**Comment by vsizov** [comment]
In my opinion it should be optional. Maybe we should add one more checkbox? https://www.dropbox.com/s/oc3qu0671ulgwx4/Screenshot%202015-05-18%2011.14.20.png?dl=0

**Comment by jvanbaarsen** [comment]
@vsizov Hm ok, and the default for new installations would be enabled?

**Comment by harbulot** [comment]
I'd say it should be made secure by default, simply because many users wouldn't go out of their way to turn it on explicitly, by lack of awareness. Users generally assume (rightly or wrongly) that the software they get has sensible default security settings out of the box.

However, this could cause problems with people who use webhooks on HTTPS services that use self-signed certificates or certificates from a custom CA (one that wouldn't be part of the bundle used by default).
I'm not familiar with HTTParty, but it looks like this could be configurable using the `ssl_ca_file` and `ssl_ca_path` options. In general, as for anything that uses SSL/TLS, it wouldn't be a bad idea to let the user configure the allowed cipher suites and protocols as well (`ssl_version` and `ciphers` options).

**Comment by jacobvosmaer** [comment]
We turned peer verification on for webhooks a while ago and quickly disabled it again because so much stuff broke for users.

- always on: bad idea
- checkbox, default true, turn on for existing webhooks: bad idea
- checkbox, default true, don't touch existing webhooks: maybe
- document (text in the UI) that/when peer verification is disabled: good idea

I think the fact that it is not obvious that webhooks omit peer verification is the biggest issue. We should fix that first.

**Comment by harbulot** [comment]
@jacobvosmaer I understand that turning it on can break stuff for some users, but it's how to do it properly that should be documented, not the fact that it is not secure (especially if it can't be made secure).

If necessary, introduce the required parameters (`ssl_ca_file`, `ssl_ca_path`, `ciphers` and `ssl_version`) and keep the verification off by default for a few versions, but with some noticeable warning, and eventually make it secure by default after a transition period.

**Comment by stanhu** [comment]
I agree with @harbulot. Actually, the "Test" Web hook button does do SSL verification, but it looks like the actual hook does not. In #9167, the user actually had a misconfigured SSL bundle, which would have been missed had SSL verification been disabled completely.

**Comment by ttasanen** [comment]
Happy to finally see some progress with this: bafffb2d14e1924154d5b7c74c7b3cbcf8c898fd and ce4defaf2f9195df4680823d8c9f0f49bbced21b

I think these commits fixed this issue and corrected the default value for SSL verification but still leaving the option for the user to shoot himself in the foot.

**Comment by bbodenmiller** [comment]
@jacobvosmaer @jvanbaarsen I think this can be closed now since there is a checkbox on web hooks to either do SSL verification or not. I do think there is a different bug though since a test webhook will give a 500 error if it fails SSL verification.
