### ISSUE TITLE
Unable remove branch with `/` char in version 7.10+

### ISSUE THREAD

**Issue by freaz** [gitlabhq/gitlabhq#9306]
Hi,

I'am not able to remove branch from GitLab UI.

The issues seems to be similar to [https://gitlab.com/gitlab-org/gitlab-ce/issues/1534]().

Here is example of communication:
![screen shot 2015-05-18 at 10 12 25](https://cloud.githubusercontent.com/assets/959390/7676697/71091c58-fd46-11e4-85f1-743721ea6acf.png)

And environment versions:
![screen shot 2015-05-18 at 10 13 27](https://cloud.githubusercontent.com/assets/959390/7676719/970b732e-fd46-11e4-90a1-56b37556178b.png)

**Comment by stanhu** [comment]
I just had a chance to test this out on the omnibus version of GitLab v7.11, and deleting a branch named `feature/git-flow-naming` through the GitLab UI worked fine for me. 

Are you using another Web server in front of GitLab? If you are using Apache or Passenger, you may need to enable the `AllowEncodedSlashes` option.

**Comment by freaz** [comment]
Hi, thank you enabling ```AllowEncodedSlashes``` helped.
