### ISSUE TITLE
the init script of gitlab is not workable

### ISSUE THREAD

**Issue by stevenkaiwang** [gitlabhq/gitlabhq#9307]
Hi, 
When i used the gitlab init scrip, i met the below issue:
Hope to get your help to fix this issue.
Thanks in advance!

OS: centos 7
gitlab: 7.10.4

# systemctl start gitlab
/etc/rc.d/init.d/gitlab:line 171: bin/web: No such file or directory
/etc/rc.d/init.d/gitlab:行178: bin/background_jobs: No such file or directory

gitlab init script is below:
cp /opt/gitlab/embedded/service/gitlab-rails/lib/support/init.d/gitlab /etc/init.d/gitlab 
 vi /etc/init.d/gitlab :

 # Then check if the service is running. If it is: don't start again.
  if [ "$web_status" = "0" ]; then
    echo "The Unicorn web server already running with pid $wpid, not restarting."
  else
    # Remove old socket if it exists
    rm -f "$socket_path"/gitlab.socket 2>/dev/null
    # Start the web server
    RAILS_ENV=$RAILS_ENV bin/web start  #171
  fi

  # If sidekiq is already running, don't start it again.
  if [ "$sidekiq_status" = "0" ]; then
    echo "The Sidekiq job dispatcher is already running with pid $spid, not restarting"
  else
    RAILS_ENV=$RAILS_ENV bin/background_jobs start &  #178
  fi

BR,
Steven

**Comment by rlucian** [comment]
@stevenkaiwang did you find a fix for this?
I am having the exact problem now, after trying to restart the gitlab service...

**Comment by stevenkaiwang** [comment]
@rlucian i did not find solution, so just re-install again, it works.

**Comment by rlucian** [comment]
actually, i was trying with 
```service gitlab restart```
when in fact it seems it works with 
```gitlab-ctl restart```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
