### ISSUE TITLE
Running GitLab alongside Node?

### ISSUE THREAD

**Issue by timbur** [gitlabhq/gitlabhq#9309]
My primary app is built using Node, supports WebSockets, etc., but I would like to run GitLab on the same server within a subdirectory.  I've put off making this issue for more than a day, trying to figure something out on my own, but apparently the omnibus package doesn't support (and has no plans to support) setting the `relative_url_root`.  So now I've uninstalled the omnibus package and am going with the custom installation, and running into some issues along the way, probably due the previous omnibus installation.

Surely running GitLab on the same server and domain as other services is a really common use-case, so how is everyone else doing it?  I can't seem to find anything on this specifically.  Maybe I'm not looking in the right places.

After the custom installation (for `relative_url_root` support), the approach I was planning on going with was either A) use [`node-http-proxy`](https://github.com/nodejitsu/node-http-proxy) and point to unicorn's port 8080 for `http://localhost/gitlab` or B) use a different port for the node app and update GitLab's nginx configuration to act as a reverse proxy to that port for any URLs outside of `http://localhost/gitlab`.

**Comment by stanhu** [comment]
As far as I know, most people are using a separate hostname or a virtual host to run GitLab. I believe relative URL support is implemented but not officially supported:

http://feedback.gitlab.com/forums/176466-general/suggestions/4102121-relative-url-support

**Comment by timbur** [comment]
Yeah this is really frustrating.  I don't like that I just installed ridiculous amounts of stuff just for the `relative_url_root` suppport and still running into problems because of the previous omnibus installation.  I think I'm going to format now (yay) to get rid of all this bloat from the custom installation, and it looks like we'll either have to go with the omnibus installation on a subdomain or just not use gitlab at all.

**Comment by stanhu** [comment]
I agree it's frustrating. Given that many of the changes for supporting relative URLs seem to be in place, making [omnibus-gitlab](https://gitlab.com/gitlab-org/omnibus-gitlab) work with it doesn't seem like it would be too difficult. You're welcome to take a look there and see if you can make it work. For example, the changes would require making `external_url` parse the path and do the right thing with it (e.g. use it in the nginx configuration).

**Comment by timbur** [comment]
I think what I'll do is the easiest solution of putting it on a subdomain, disabling gitlab's nginx configuration, and use https://github.com/nodejitsu/node-http-proxy to point the subdomain towards unicorn (port 8080).

Thanks for the help!
