### ISSUE TITLE
Manage subscriptions for issue

### ISSUE THREAD

**Issue by blackst0ne** [gitlabhq/gitlabhq#9310]
I would like to have an ability to manage subscriptions to an issue.
Say, I create an issue and I want to subscribe some users, assigned to current project, to the issue.

At this moment, only users themselves can subscribe to issues.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

**Comment by cdaigle** [comment]
If you can edit the issue, you can @mention the people you want to
subscribe in the description, which will subscribe them.

At least that works in merge requests.
