### ISSUE TITLE
Incorrect MySQL client library version! This gem was compiled for 5.1.73 but the client library is 5.3.12-MariaDB.

### ISSUE THREAD

**Issue by tonymadbrain** [gitlabhq/gitlabhq#9313]
Hi, im installing gitlab with omnibus-ctl, and trying to upgrade mysql from 5.6 to mariadb-10. In unicorn err log i see:
```
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require': Incorrect MySQL client library version! This gem was compiled for 5.1.73 but the client library is 5.3.12-MariaDB.
```
I know how to resolve this:
```
$ gem uninstall mysql2
$ bundle config build.mysql2 --with-mysql-config=/usr/bin/mysql_config
$ bundle install
```
But how i can do it for gitlab omnibus installation? 
My configuration:
* Centos 6.6
* mysql  Ver 15.1 Distrib 10.0.19-MariaDB
* gitlab-ce-7.10.4~omnibus-1.x86_64

**Comment by stanhu** [comment]
I don't believe this is a supported configuration, but you could run the same commands except prefix them with `/opt/gitlab/embedded/bin`. For example:

```
sudo /opt/gitlab/embedded/bin/gem uninstall mysql2
```

**Comment by stanhu** [comment]
Since this is not a supported configuration at the moment, I'm going to close this out.
