### ISSUE TITLE
Issues page: Firefox renders incorrect layout

### ISSUE THREAD

**Issue by blackst0ne** [gitlabhq/gitlabhq#9314]
![screenshot_gitlab_1](https://cloud.githubusercontent.com/assets/1610813/7717958/9f4f0e84-fee4-11e4-8b03-11bc709cd455.png)

Pay attention to dropdown lists.
It's Firefox 38.0 that renders that page.

At the same time, Google Chrome and Internet Explorer render everything just fine.

Reproduced on three different PCs.
Cache and cookies were cleared.

**Comment by dreis2211** [comment]
This will be fixed with the next release. See https://gitlab.com/gitlab-org/gitlab-ce/issues

For further information, take a look here:
https://github.com/gitlabhq/gitlabhq/issues/9243
https://github.com/gitlabhq/gitlabhq/pull/9244

Cheers

**Comment by blackst0ne** [comment]
Thank you.
