### ISSUE TITLE
GitLab 7.10.4 - 500 error in groups/XXX/milestones page

### ISSUE THREAD

**Issue by n2odnb** [gitlabhq/gitlabhq#9315]
Please help! :)

production.log

Processing by Projects::IssuesController#show as HTML
  Parameters: {"namespace_id"=>"XXX", "project_id"=>"XXX", "id"=>"22"}
Completed 200 OK in 223ms (Views: 174.5ms | ActiveRecord: 7.4ms)
Started GET "/groups/XXX/milestones" for x.x.x.x at 2015-05-20 11:33:48 +0300
Processing by Groups::MilestonesController#index as HTML
  Parameters: {"group_id"=>"XXX"}
Completed 500 Internal Server Error in 95ms

ActionView::Template::Error (No route matches {:action=>"show", :controller=>"groups/milestones", :format=>nil, :group_id=>#<Group id: 24, name: "XXX", path: "XXX", owner_id: nil, created_at: "2015-05-14 12:53:23", updated_at: "2015-05-14 16:05:50", type: "Group", description: "XXX project", avatar: "o_b11da8d0c773652f-0.png">, :id=>"", :milestone=>{:state_event=>:close}, :title=>"релиз"} missing required keys: [:id]):
    4:       - if milestone.closed?
    5:         = link_to 'Reopen Milestone', group_milestone_path(@group, milestone.safe_title, title: milestone.title, milestone: {state_event: :activate }), method: :put, class: "btn btn-sm btn-grouped btn-reopen"
    6:       - else
    7:         = link_to 'Close Milestone', group_milestone_path(@group, milestone.safe_title, title: milestone.title, milestone: {state_event: :close }), method: :put, class: "btn btn-sm btn-close"
    8:   %h4
    9:     = link_to_gfm truncate(milestone.title, length: 100), group_milestone_path(@group, milestone.safe_title, title: milestone.title)
   10:   .row
  app/views/groups/milestones/_milestone.html.haml:7:in `_app_views_groups_milestones__milestone_html_haml__4000946572473785658_70307700684220'
  app/views/groups/milestones/index.html.haml:21:in `block in _app_views_groups_milestones_index_html_haml__3795436627044772478_70307701103660'
  app/views/groups/milestones/index.html.haml:20:in `each'
  app/views/groups/milestones/index.html.haml:20:in `_app_views_groups_milestones_index_html_haml__3795436627044772478_70307701103660'

**Comment by euforia** [comment]
Does the namespace_id contain a dot in it?

**Comment by jmickle** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/1665

**Comment by n2odnb** [comment]
euforia:
No! :(
jmickle:
same error 500 after applied patch

new log:
Started GET "/groups/XXX/milestones" for x.x.x.x at 2015-05-21 11:10:31 +0300
Processing by Groups::MilestonesController#index as HTML
  Parameters: {"group_id"=>"XXX"}
Completed 500 Internal Server Error in 29ms

ActionView::Template::Error (No route matches {:action=>"show", :controller=>"groups/milestones", :format=>nil, :group_id=>#<Group id: 24, name: "XXX", path: "XXX", owner_id: nil, created_at: "2015-05-14 12:53:23", updated_at: "2015-05-14 16:05:50", type: "Group", description: "XXX project", avatar: "o_b11da8d0c773652f-0.png">, :id=>"", :milestone=>{:state_event=>:close}, :title=>"релиз"} missing required keys: [:id]):
    4:       - if milestone.closed?
    5:         = link_to 'Reopen Milestone', group_milestone_path(@group, milestone.safe_title, title: milestone.title, milestone: {state_event: :activate }), method: :put, class: "btn btn-sm btn-grouped btn-reopen"
    6:       - else
    7:         = link_to 'Close Milestone', group_milestone_path(@group, milestone.safe_title, title: milestone.title, milestone: {state_event: :close }), method: :put, class: "btn btn-sm btn-close"
    8:   %h4
    9:     = link_to_gfm truncate(milestone.title, length: 100), group_milestone_path(@group, milestone.safe_title, title: milestone.title)
   10:   .row
  app/views/groups/milestones/_milestone.html.haml:7:in `_app_views_groups_milestones__milestone_html_haml__838050455636257631_69948838563740'
  app/views/groups/milestones/index.html.haml:21:in `block in _app_views_groups_milestones_index_html_haml___3483507458038565434_69948838799840'
  app/views/groups/milestones/index.html.haml:20:in `each'
  app/views/groups/milestones/index.html.haml:20:in `_app_views_groups_milestones_index_html_haml___3483507458038565434_69948838799840'

**Comment by n2odnb** [comment]
Anyone ?

**Comment by stanhu** [comment]
Is `XXX` using Unicode characters? The matching route from `rake routes` is:

```ruby
group_milestones GET      /groups/:group_id/milestones(.:format) 
groups/milestones#index {:group_id=>/[a-zA-Z.0-9_\-]+(?<!\.atom)/}
```

I could see and issue if `group_id` isn't matching this constraint.

**Comment by n2odnb** [comment]
Yes XXX is using unicode characters...

**Comment by stanhu** [comment]
I just tried to create a group with unicode characters, but I got this message:

![image](https://cloud.githubusercontent.com/assets/963826/7814384/b96dbbbc-0376-11e5-98d3-75902e5d858e.png)

How did you manage to set this?

You could try temporarily remove the constraints in `config/routes.rb` to see if that helps:

```
resources :groups, constraints: { id: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ } do
```

**Comment by n2odnb** [comment]
Sorry my mistake, groupname has only unicode letters...

On which line i need to change something ?

**Comment by n2odnb** [comment]
Thats good!
Removing constraints helped me...
But maybe its dangerous now ?

**Comment by stanhu** [comment]
How did you create a group with unicode letters? Did you import this code from another repository?

**Comment by n2odnb** [comment]
I create group with name of default word like "groupname" no any speacial characters...

**Comment by stanhu** [comment]
Can you clarify? I thought you said your group name (`XXX`) had Unicode characters, and that relaxing the constraints solved the problem. I don't understand how it was possible to create a group name with Unicode characters unless you edited the database directly, somehow renamed the group, or imported it through some tool.

**Comment by n2odnb** [comment]
My group id was "GROUPNAME" not any speacial characters in unicode, just letters. But i still got the error 500. when i removed constraints my "GROUPNAME" didnt work perfectly. But constraints  must allow to use this group id. I dont know why error comes out ...

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
