### ISSUE TITLE
The redesigned project page shows "New issue" and "New milestone" buttons even if they are disabled for the project

### ISSUE THREAD

**Issue by qcz** [gitlabhq/gitlabhq#9324]
The new project page shows the "New issue" and "New milestone" buttons even if these functions are disabled for the project. Clicking on the buttons result in a 404 error.

**Steps to reproduce:** always, even for new projects

**Expected behavior:** these buttons are not visible when the functions they belong to are disabled in the project settings.

**Comment by stanhu** [comment]
A proposed fix for this is here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/691

**Comment by stanhu** [comment]
This can be closed now. See: 9bcd363

/cc: @Razer6
