### ISSUE TITLE
Error while previewing Markdown of Milestone Edit.

### ISSUE THREAD

**Issue by praveenscience** [gitlabhq/gitlabhq#9325]
1. **Summary:** Markdown preview in the Edit Milestone doesn't work for https://gitlab.com/.

2. **Steps to reproduce:**
   1. Go to your project, mine's a Private Project. (https://gitlab.com/username/project)
   2. Click on Milestones, existing one. (milestones) (milestones/1)
   3. Click on Edit. (milestones/1/edit)
   4. Click on Preview after writing any text.
3. **Expected behavior:** Should show the preview after processing with GFM.

4. **Observed behavior:** It throws an error:  

        Uncaught Error: Syntax error, unrecognized expression: .zennable input[type=checkbox]##md-preview-holder.

5. **Relevant logs and/or screenshots:**

   ![gitlab](https://cloud.githubusercontent.com/assets/1830380/7785094/cc9ff6be-0178-11e5-8e27-23004263b01a.png)

6. **Output of checks:** This is in the production version of the GitLab, and the bug is present at the time of posting this issue.

7. **Possible fixes:** Looks like a JavaScript DOM query error, and since the code is minified, I am not able to find the exact solution.

**Comment by praveenscience** [comment]
@randx Has this been pushed to the prod?

**Comment by Razer6** [comment]
No, this will be available with GitLab 7.12 released at 22 of June.
