### ISSUE TITLE
Gitlab 7.11.1 - clone URL loses selection after click

### ISSUE THREAD

**Issue by creker** [gitlabhq/gitlabhq#9326]
When I click on clone URL it gets selected but then selection immediately disappears. In order to copy the URL I need to manually select it. Same thing on gitlab.com. Tested on latest versions of Safari and Chrome.

**Comment by stanhu** [comment]
I was able to replicate this on Safari but not on Chrome. It looks like 92544df appears to be causing the problem. `focusin` is fired once in Safari but not again.

/cc: @dmedvinsky

**Comment by stanhu** [comment]
Proposed fix here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/698

**Comment by creker** [comment]
Tested on Chrome 43.0.2357.65

**Comment by stanhu** [comment]
Ah, right. It worked fine in Chrome 42.0.2311.152, but it does not work in 43.0.2357.65. The fix seems to work in Chrome too.

**Comment by dmedvinsky** [comment]
@stanhu I actually kind of snatched the implementation from github.com and it seems to behave this way there, too, if I understood the problem correctly.
