### ISSUE TITLE
/api/v3/namespaces is for admins only?!

### ISSUE THREAD

**Issue by tristanlins** [gitlabhq/gitlabhq#9328]
It seems, that `/api/v3/namespaces` is only accessible by admins. As regular user I get a `403 Forbidden`. But I dont see a reason why a regular user should not list namespaces by the api, he has access to?!

**Comment by stanhu** [comment]
Added support with these changes:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/708

**Comment by tristanlins** [comment]
Good to know, thx
