### ISSUE TITLE
Ability to set fix version when resolving issues with JIRA

### ISSUE THREAD

**Issue by johnou** [gitlabhq/gitlabhq#9331]
Being able to set the fix version when resolving issues via commit message would save a lot of time.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
