### ISSUE TITLE
502 Bad Gateway freshly installed

### ISSUE THREAD

**Issue by Blaxtor** [gitlabhq/gitlabhq#9334]
Hello, after installing GitLab on my server, i've been encountering the 502 bad Gateway error, I searched for different fixes (like time out to 300) but couldn't fix it with any of the solution found on the different posts. It should'nt be server's specs (like memory since i have > 50 G)

![image](https://cloud.githubusercontent.com/assets/10464149/7833106/6cb96bc4-0464-11e5-894b-ea4b5e3e12f7.png)

Moreover, my git version seems to be outdated (<1.7.10) but when i check mine is 2.1.4

I did follow the installation guide ( https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md )

Thanks in advance

**Comment by ex-troll** [comment]
which system?

**Comment by Blaxtor** [comment]
Debian 8 sorry

I Could'nt instal through Omnibus package it said it couldn't recognize the OS.

**Comment by stanhu** [comment]
Debian 8 is supported. Are you using the 32-bit or 64-bit version? Only 64-bit is available:

https://about.gitlab.com/2015/05/01/gitlab-on-debian-8/

You'll be much happier running the omnibus version.

**Comment by Blaxtor** [comment]
guess it's a 32 one, (not able to connect to server right now) but i really
couldn't instal through omnibus since i directly got an "system not
recognized" error

2015-05-27 19:07 GMT+02:00 stanhu <notifications@github.com>:

**Comment by stanhu** [comment]
Looks like you have to manually install the package:

https://gitlab.com/gitlab-org/omnibus-gitlab/issues/567#note_1268189

**Comment by Blaxtor** [comment]
great thanks for the info @stanhu , I'll go that way when they'll solve the
problem, but still, (now for personnal knowledge) does anyone has an idea
about the problem i encountered ?


2015-05-28 2:05 GMT+02:00 stanhu <notifications@github.com>:

**Comment by stanhu** [comment]
What is the output of the following?

```
which git
/usr/local/bin/git --version
```

**Comment by Blaxtor** [comment]
As a response from the command I get

"
-bash: /usr/local/bin/git: No such file or directory
"

2015-05-29 15:07 GMT+02:00 stanhu <notifications@github.com>:

**Comment by stanhu** [comment]
It seems you skipped the step about building git from source (see step 1):

http://doc.gitlab.com/ce/install/installation.html

Again, use the omnibus version to save yourself trouble. :)

**Comment by stanhu** [comment]
Or you can fix your `gitlab.yml` to use /usr/bin instead of /usr/local/bin:

```
 ## Git settings
  # CAUTION!
  # Use the default values unless you really know what you are doing
  git:
    bin_path: /usr/bin/git
```

**Comment by Blaxtor** [comment]
great ! i'll give a shot to both solution on monday, and i'll keep you up

Thanks you again for your help !


2015-05-29 15:48 GMT+02:00 stanhu <notifications@github.com>:

**Comment by Blaxtor** [comment]
well, after checking my server is a 64 one (x86_64).

anyway, still have troubles with that install, might definitely go back to
try with omnibus package

Do you know if i need to uninstall everything i did, or just running the
omnibus installation should be fine ?

2015-05-29 16:17 GMT+02:00 Mathieu Cocuelle <mathieu.cocuelle@gmail.com>:

**Comment by stanhu** [comment]
omnibus installation should install everything in `/opt/` and `/var/opt/`, so you might be able to get away with not cleaning up everything you did before. I'd still recommend uninstalling if you can.

**Comment by Blaxtor** [comment]
any known and approved "uninstalling" documentation/guide ?

I do have gitlab folders in /opt & /var/opt, feeling like i do have to clean everything.

Once again thank you for your time and your help stanhu, you rock !

**Comment by stanhu** [comment]
Sorry, @Blaxtor, don't think there's a standardized way of uninstalling a source installation, aside from working backwards and undoing the installation steps.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
