### ISSUE TITLE
Push Event should contain branch info

### ISSUE THREAD

**Issue by qiluo** [gitlabhq/gitlabhq#9338]
I want to identify which branch received commit in `push event` web hook, otherwise I would have to write and deploy custom post-receive-hook on the server. The latter is not quite easy and tedious.

**Comment by stanhu** [comment]
Isn't this information in the `ref` field?

https://github.com/gitlabhq/gitlabhq/blob/master/doc/web_hooks/web_hooks.md#push-events

**Comment by qiluo** [comment]
okay, I missed that part, thanks
