### ISSUE TITLE
Hard Tabs are not displayed in code

### ISSUE THREAD

**Issue by leepa** [gitlabhq/gitlabhq#9345]
Particularly a problem with golang code where that uses hard tabs for formatting. You end up with everything with no spacing.

**Comment by leepa** [comment]
(specifically in the commit view rather than the file view)

**Comment by stanhu** [comment]
Do you have an example? The commits here look fine:

https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/commits/master

**Comment by papisz** [comment]
I've got the same problem with golang code in Chromium 45.0.2454.101 Ubuntu 14.04 (64-bit) (both in commit code and in file view).
Firefox and Google Chrome seems to handle the tabs properly.

**Comment by stanhu** [comment]
Confirmed that this is a regression in 8.1: https://gitlab.com/gitlab-org/gitlab-ce/issues/3220#note_2616143

Closing this issue in favor of that discussion.
