### ISSUE TITLE
GitLab only returns 'forbidden'

### ISSUE THREAD

**Issue by KennethWussmann** [gitlabhq/gitlabhq#9346]
Everytime I visit my GitLab instance, it just returns forbidden. 
GitLab is running since some weeks, but now i only get forbidden.
I think it is something with my ip-address, when I visit GitLab over VPN it works until I try to clone a project or after 1-3 clicks on links. 

After 4-5 Minutes waiting GitLab works again, but clicking links and cloning projects causes forbidden again.

I know there is the [Issue #1158](https://github.com/gitlabhq/gitlabhq/issues/1158#issuecomment-7390383) but it does not fix my problem.

**Comment by stanhu** [comment]
This could be related to Rack Attack banning your IP for some reason. Do the nginx logs show 401s?

See: https://gitlab.com/gitlab-org/gitlab-ce/issues/1171
