### ISSUE TITLE
Upgrader version checker not getting last version

### ISSUE THREAD

**Issue by Soullivaneuh** [gitlabhq/gitlabhq#9348]
```bash
~/gitlab$ ruby bin/upgrade.rb
GitLab 7 upgrade tool
Your version is 7.11.3
Latest available version for GitLab 7 is 7.9.4
You are using the latest GitLab version
```

I has the same message on 7.10 and had to do the upgrade manually.

**Comment by maxlazio** [comment]
Did you check the update [on the upgrader doc](https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/upgrader.md#gitlab-upgrader) ?

**Comment by Soullivaneuh** [comment]
@maxlazio Oh, sorry didn't see the notice.

Can I ask why it's deprecated ? This script was useful IMO. :/

**Comment by Razer6** [comment]
Could you try https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/695 ?

**Comment by Soullivaneuh** [comment]
I can't on production. Will simulate on local if I got some time.

**Comment by Razer6** [comment]
Closing because fix is merged.
