### ISSUE TITLE
Feature request: Add RELEASE NOTES tab to project home view

### ISSUE THREAD

**Issue by AndrewBurdyug** [gitlabhq/gitlabhq#9351]
It would be great to have one extra tab "News" or "Release Notes" like #2826. 
**Logic**: _if project has a file RELEASE-NOTES.md, then his content will show on the extra tab "Release Notes"._

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
