### ISSUE TITLE
Readme tab VS Readme.md

### ISSUE THREAD

**Issue by yellowmonster** [gitlabhq/gitlabhq#9358]
I'm using GitLab and just have one question I can't find answer to....
Why there are a difference in the project readme tab and readme.md and how to prevent it?
![readmetab_small](https://cloud.githubusercontent.com/assets/12759457/8002063/eaadb98c-0b6b-11e5-87f2-f11552d952c9.jpg)
![readmemd_small](https://cloud.githubusercontent.com/assets/12759457/8002071/f512c5f2-0b6b-11e5-8f53-f987a7cf871b.jpg)

Thanks for helping!
GitLab 7.9.0.rc3

**Comment by yellowmonster** [comment]
Nobody with same kind of problem?

**Comment by tsigo** [comment]
Very odd. I haven't been able to reproduce it.

Both of those places should be rendering the document the exact same way, as far as I know. Could you perhaps try creating a private Snippet on gitlab.com and pasting the README there to see if it renders as expected?

**Comment by Razer6** [comment]
Most likely a caching issue. Try
```bash
cd /home/git/gitlab
sudo -u git -H bundle exec rake cache:clear RAILS_ENV=production
```
