### ISSUE TITLE
Issue closing pattern on non-default branches

### ISSUE THREAD

**Issue by stefan-it** [gitlabhq/gitlabhq#9363]
Hi,

when using the "git flow" (that means: `master`, `develop` and feature branches), is there any way to get the issue closing pattern work with a non-default branch? 

For example:

I implement a feature on `feature/issue-42` and then I create a MR which includes the pattern "Closes #42". This MR goes into `develop`. After merging it into `develop` it would be awesome if the corresponding issue would be closed automatically.

So can anyone please give me some hints how this can be implemented? 

Thanks many in advance,

Stefan

**Comment by stanhu** [comment]
At the moment, no. [This line](https://github.com/gitlabhq/gitlabhq/blob/master/app/services/git_push_service.rb#L83) ensures that only issues are closed from commits on the default branch. You could comment out this behavior if you really wanted to be able to close from any branch.

**Comment by stanhu** [comment]
I'm going to close this one because I doubt this feature will be supported in the near future.
