### ISSUE TITLE
[Docker] sytse/gitlab-data not found

### ISSUE THREAD

**Issue by stefan-it** [gitlabhq/gitlabhq#9364]
Hi,

the offical Docker `README.md` points to `sytse/gitlab-data` which can not be found on Docker hub.

Instead it should be:

```bash
sytse/gitlab_data
```

with an underscore. See it on [Docker Hub](https://registry.hub.docker.com/u/sytse/gitlab_data/).

With the corrected version a `docker pull` succeeds:

```bash
docker pull sytse/gitlab_data
latest: Pulling from sytse/gitlab_data
cf2616975b4a: Pull complete 
6ce2e90b0bc7: Pull complete 
8c2e06607696: Pull complete 
516ca650d586: Pull complete 
f4c5d5e8c350: Pull complete 
60517059c711: Pull complete 
4a6cc7af9219: Already exists 
Digest: sha256:4dfca72e5dfe97fa83cc71736609c26db91b60d373019ce07542e3e18aec7997
Status: Downloaded newer image for sytse/gitlab_data:latest
```

Whereas the "old" version:

```bash
docker pull sytse:gitlab-data
Pulling repository sytse
FATA[0001] Error: image library/sytse:gitlab-data not found
```

I'm using Docker in version:

```bash
docker --version
Docker version 1.6.1, build 97cd073
```

Should I create a PR for that? 

/cc @dosire

**Comment by dosire** [comment]
@stefan-it can you make a PR to switch everything to use `-` (get rid of all the underscores)?

**Comment by stefan-it** [comment]
Merged, so I'm closing now :)

**Comment by dosire** [comment]
Thanks @stefan-it
