### ISSUE TITLE
[7.11.4] Issue closing pattern not working with cross project reference issue number

### ISSUE THREAD

**Issue by stefan-it** [gitlabhq/gitlabhq#9365]
Hi,

I'm not sure if this a bug or a "feature request", which is not yet implemented.

The issue closing pattern works perfectly, e.g. when you use "Closes #1" in a commit message on `master` branch.

But: when you use the cross project reference number for the same issue, like: `username/project#1` like it is shown on the issue page it does not work. Tested on GitLab *7.11.4*.

Thanks many in advance,

Stefan

**Comment by maxlazio** [comment]
Closing issues by using cross project reference is not supported. You can see the documentation about this [here](http://doc.gitlab.com/ce/customization/issue_closing.html). This would be a feature request you can raise at feedback.gitlab.com.

**Comment by stefan-it** [comment]
Thanks for your reply :) I created a new feature request [here](http://feedback.gitlab.com/forums/176466-general/suggestions/8365512-issue-closing-pattern-with-cross-project-reference) containing a small "fix" for supporting cross project reference issues :)
