### ISSUE TITLE
"Reload with full diff" button on a MR links to a JSON diff file

### ISSUE THREAD

**Issue by rousisk** [gitlabhq/gitlabhq#9367]
Hi all,

When there are too many changes for the full diff to be displayed on the *Changes* tab of a MR, a button allows to *Reload with full diff*.

This links to the JSON representation of the diff, as in `project/merge_requests/3/diffs.json?force_show_diff=true`. Upon clicking the user is presented with a JSON file.

When I remove the `.json` part form the URL everything seems to work as expected.

I've encountered the following issue on **GitLab 7.11.0 e3e3292**.

I would be happy to prepare a MR, just let me know.

**Comment by Yety** [comment]
I do also experience the same issue.

**Comment by Yety** [comment]
I just saw, that this is supposed to be fixed: https://gitlab.com/gitlab-org/gitlab-ce/commit/3302888cec220443a06e23b3f8d29f5080bc86ab 
But in which gitlab version?

**Comment by maxolasersquad** [comment]
I am seeing this problem when using the button from the "Changes" tab. If I open up a specific commit then the button works as expected.

**Comment by Razer6** [comment]
This has been fixed in 7.10
