### ISSUE TITLE
Getting username in custom hooks

### ISSUE THREAD

**Issue by ibmkaga** [gitlabhq/gitlabhq#9379]
Is there a way to get hold of the username which is performing the current operation in custom hooks. I read somewhere about GL_ID but in SSH case this has the key-<running number> and there seems to be no api to get the username from the key-<running-number>. I am using GitLab 7.7.1.

**Comment by bozaro** [comment]
I create PR #9591: Add API method for get user by ID of an SSH key

**Comment by bozaro** [comment]
Coming soon: https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/keys.md

**Comment by Razer6** [comment]
Then we can close this issue. @bozaro Thank you for the implementation.
