### ISSUE TITLE
"Your account is locked"

### ISSUE THREAD

**Issue by thelinuxlich** [gitlabhq/gitlabhq#9381]
A user is trying to access the web UI and is getting this message(latest Gitlab version), I can't found anywhere on the user administration section a way to unlock it, what should I do?

**Comment by zenati** [comment]
An account is locked if the user couldn't signin and entered wrong password 10 times.
The account will stay locked for 10 minutes.

```
  # /config/initializers/devise.rb
  config.unlock_strategy = :time

  # Number of authentication tries before locking an account if lock_strategy
  # is failed attempts.
  config.maximum_attempts = 10

  # Time interval to unlock the account if :time is enabled as unlock_strategy.
  config.unlock_in = 10.minutes
```
