### ISSUE TITLE
FileUtils.rm_rf(path) not working , path is a nfs parted disk

### ISSUE THREAD

**Issue by kesin** [gitlabhq/gitlabhq#9385]
our repositories is stored in a nfs parted disk
and repositories directory is a sympol link
why FileUtils.rm_rf(path) does not working???
is there any solution instead of FileUtils?

**Comment by stanhu** [comment]
Where are you seeing the failure with `FileUtils.rm_rf? It is used for a number of tasks. Is it failing due to lack of permissions?

**Comment by kesin** [comment]
no, now I think it is a nfs async problem ， I am trying to check it out

**Comment by kesin** [comment]
i find out why we can not delete the repo dir, there is a .nfs******  file，but i do not know which process accessed it

**Comment by stanhu** [comment]
You might want to read:

http://nfs.sourceforge.net/#faq_d2
http://serverfault.com/questions/201294/nfsxxxx-files-appearing-what-are-those

**Comment by kesin** [comment]
@stanhu thx,that`s what i looked before，i`m trying to figure out which process is still being accessed it.
