### ISSUE TITLE
Icon not shown correctly

### ISSUE THREAD

**Issue by LazyParanoid** [gitlabhq/gitlabhq#9386]
In our gitlab server (running version `7.11.2`), the icons are correct in the `commit` page, but not it is still the gravatar icons in the `network` page.

**Comment by stanhu** [comment]
Can you include screenshots to illustrate what you are seeing?

**Comment by LazyParanoid** [comment]
For example, I have pushed a commit to `local` branch today.

On the Commit Panel, my icon is shown correctly
![commit](https://cloud.githubusercontent.com/assets/7665007/8195343/d628db6c-1436-11e5-94a4-f278dd8fbb44.png)

However, on the Network panel, my icon is still shown as the default one from gravatar
![network](https://cloud.githubusercontent.com/assets/7665007/8194843/2a827f46-1433-11e5-9150-792f211a65a0.png)

I have to remove most of the content on the page, but I think these two screen shots make my point clear enough.

**Comment by tdwire** [comment]
I have the same issue. Using 7.12.0
![image](https://cloud.githubusercontent.com/assets/8257692/8481198/701c4778-20a7-11e5-9ee2-db5e1a0bb1c5.png)


![image](https://cloud.githubusercontent.com/assets/8257692/8481133/208d3af0-20a7-11e5-9d2a-2b5cdea59e37.png)

![image](https://cloud.githubusercontent.com/assets/8257692/8481170/46707872-20a7-11e5-989a-ca41b1bd7f51.png)

**Comment by stanhu** [comment]
I think this is working in GitLab 8.0, but if this is still a problem please re-open the issue.
