### ISSUE TITLE
[Plesk] Gitlab take over the Server

### ISSUE THREAD

**Issue by UnDeadClank** [gitlabhq/gitlabhq#9390]
Hallo, 
i am using Debian 7 with Plesk.

After installing Gitlab and restarting my Server. 
Gitlab shows up on every Domain and Subdomain.

http://dreistwiekeiner.de/forum
http://wi.dreistwiekeiner.de

I only change the external_url to 'git.dreistwiekeiner.de' in /etc/gitlab/gitlab.rb
Maybe i have to change some more settings in gitlab.rb.

I try out this:
http://stackoverflow.com/questions/24684434/installing-gitlab-on-vps-running-parallels-plesk
  -> for omnibus installation

**Comment by UnDeadClank** [comment]
Ok i remove Gitlab, because my Community needs Forum. 
Maybe someone can write me what i did wrong.

**Comment by axilleas** [comment]
GitLab uses a bundled nginx server. If you want to use GitLab on a shared server you have to use an external one. See https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/nginx.md#using-a-non-bundled-web-server
