### ISSUE TITLE
How to check if a user use Two-factor Authentication?

### ISSUE THREAD

**Issue by luthur** [gitlabhq/gitlabhq#9391]
/users/{user_id} did not output such infomation

**Comment by stanhu** [comment]
Currently it's not supported. I think it would just take adding `:opt_required_for_login` to one of these lines:

https://github.com/gitlabhq/gitlabhq/blob/ce5928f4df1ebdac1fbc319fd1dbd15585f5da9e/lib/api/entities.rb#L22

**Comment by tsigo** [comment]
Fixed by merge request: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/881
