### ISSUE TITLE
Recommended approach for a client to receive notifications

### ISSUE THREAD

**Issue by valeriomazzeo** [gitlabhq/gitlabhq#9393]
What would be the best way to provide 3rdparty client's users with notifications?

In theory it should be possible to set up some project(s) `Web Hooks` and send them to a centralise server (managed by the 3rdparty client owner) that can then dispatch notifications to the appropriate clients.

`gitlab -> notification server -> clients`

However, there can be many `gitlab` hosts where people can connect to and this makes it impossible for the `notification server` to be able to find out the correct set of registered clients that should receive such notifications.

Each client may register for a defined `host` after login, but hosts may not be unique.
For example someone may host gitlab on a private network `192.168.0.1` and that hostname may collide with someone else.

It should be possible to secure the `incoming` connection side of things using `OAuth2` registering the host to the `notification server` which can then return an auth token to use in the web hook, but still it wouldn't be enough for it to match the corresponding users.

It would be interesting to know what are your thoughts and how this could be achieved.

Thanks.

**Comment by dosire** [comment]
For context @valeriomazzeo makes the iOS app that has to work with GitLab.com and all on-premises servers.

@valeriomazzeo how do other applications solve this?

/cc @randx @DouweM

**Comment by valeriomazzeo** [comment]
Normally, you'll work on a single domain and providing the backend (gitlab in this case) with an `application id`.

The backend dispatch notifications to all the clients which are registered within a single `application id` which is hardcoded in the app. 

The app can then register to receive a certain groups of notifications using for example a tag mechanism that can be implemented either in the backend or (and this is the case) on a different service. This would reside on the above mentioned `notification server`.

The problem here is that we are on a cross domain level and we may need another layer of abstraction on top of it, to be able to register the client to a specific `global` or `on-premises server` for the problems mentioned above.

**Comment by valeriomazzeo** [comment]
I think adding an instance id that is unique to any gitlab server may solve the problem.

It could be sent in the headers within every request.

The notification server at that point can be able to recognise who is sending the request.

Clients can register to the instance id after login and receive the appropriate notifications.

There are some concerns about security in terms of who can send notifications (anyone could modify the header and the instance id won't be secret) and who can receive them.

For the latter, it won't be any safer than any other system around because other information like project id, notification level, etc have to be provided in order to receive such notifications and this values even when obfuscated can be sniffed.

For the former, the notification server can provide authentication token to be sent within the web hooks, but a push configuration at a system level would be more handy and won't require any gitlab user (master/owner)  to register with the notifications server and manually add web hooks to every single project.

Do you guys think you can help with this? @dosire @randx

**Comment by randx** [comment]
Adding application id can be possible. But looking at your problem I am not sure how it can help you from security perspective since this application id would become a public information. You can use domain name for same purposes.

**Comment by valeriomazzeo** [comment]
It would solve the problem of private hosts which are not unique. Therefore, will avoid collisions.

Security concerns are still there both ways, but at least one problem will be solved.

Would you completely exclude the idea of a `per-instance` configuration to ease the setup?

Something like:

Dispatch notifications to:

**Comment by randx** [comment]
Feel free to propose implementation of Project service for it

**Comment by valeriomazzeo** [comment]
Projects are not unique identifiable on a cross domain basis. Example: project_id = 3456 is not unique when considering different hosts.

Would it be possible to have something like `System services` which span across the whole gitlab instance?

**Comment by dosire** [comment]
@valeriomazzeo There are system hooks but these can be set only by an administrator.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
