### ISSUE TITLE
Cannot add deploy key show error 500

### ISSUE THREAD

**Issue by manhnv85** [gitlabhq/gitlabhq#9395]
When trying to add deploy key to a project I get a 500 error trying to click save.
I see this error in production.log

Errno::ENOENT (No such file or directory - ssh):
  lib/gitlab/popen.rb:23:in `popen'
  lib/gitlab/key_fingerprint.rb:42:in `explicit_fingerprint_algorithm?'
  lib/gitlab/key_fingerprint.rb:21:in `block in fingerprint'
  lib/gitlab/key_fingerprint.rb:15:in `fingerprint'
  app/models/key.rb:85:in `generate_fingerprint'
  app/controllers/admin/deploy_keys_controller.rb:20:in `create'

I'm new gitlap
My sytem 
GitLab 7.11.4
GitLab Shell 2.6.3
GitLab API v3
Ruby 2.1.6p336
Rails 4.1.9

Please help me!

**Comment by stanhu** [comment]
GitLab is reporting an error because it can't run `ssh`. Are you installing from source? Do you have `openssh-client` installed?

**Comment by manhnv85** [comment]
Thanks :) I have not installed openssh-client
