### ISSUE TITLE
open() "/home/git/gitlab/public/assets/application-a057590240c75e48c08b4361e8acbd30.js" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by dayiguizhen** [gitlabhq/gitlabhq#9398]
I install gitlab secceed and I can sign in.
But it looks like that.

![pic][1]

I check this in [gitlab][2] and I also didn't found this directory.

[1]:http://7rfh5s.com1.z0.glb.clouddn.com/gitlaberror.jpg
[2]:https://github.com/gitlabhq/gitlabhq/tree/master/public

**Comment by stanhu** [comment]
Have you installed from source or are you using the omnibus version? If the former, then try to recompile the assets:

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/raketasks/maintenance.md#precompile-the-assets

**Comment by stanhu** [comment]
I'm going to close this issue as this seems to be an issue with assets not being compiled.
