### ISSUE TITLE
hi,when I click the wiki history,it doesn't work

### ISSUE THREAD

**Issue by qishibo** [gitlabhq/gitlabhq#9399]
Then I find that the param "version_id" was not appended to the url...
If I added the param manually,it shows the history data,but when I wanted to edit it ,is doesn't work eventhough I added the "version_id" param,[still the latest wiki,not the history]
I can't write ruby,how to fix it??
![image](https://cloud.githubusercontent.com/assets/5136418/8247110/51cb4ac8-167d-11e5-9049-536c1c03b820.png)

![image](https://cloud.githubusercontent.com/assets/5136418/8247118/716ae79e-167d-11e5-8fa5-d60b20a3afff.png)

**Comment by stanhu** [comment]
Thanks, submitted a fix here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1232

**Comment by RustJason** [comment]
:+1:
