### ISSUE TITLE
Merge Request action between two branches always defaults to Master branch as target branch

### ISSUE THREAD

**Issue by layer3switch** [gitlabhq/gitlabhq#9402]
Gitlab 7.12rc2
Ruby 2.1.6

After creating merge request via Gitlab UI button, changing target branch other than master will always default to Master branch regardless of changing to other branch.

After creating merge request, manually changing target branch and saving the change is the only way to avoid merging to Master branch.

Our developers advised that either CSS/JS change to carry "target branch" be part of URI request during "Merge Request" API call.

Please advise.

**Comment by stanhu** [comment]
Thanks--this issue was reported here:

https://gitlab.com/gitlab-org/gitlab-ce/issues/1830

A proposed fix is here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/846
