### ISSUE TITLE
Syntax highlighting for React JSX files

### ISSUE THREAD

**Issue by jbbr** [gitlabhq/gitlabhq#9403]
XML'ish syntax of Reacts JSX is displayed wrong inside of *.js files.
Also files with the ending "*.jsx" don't get any syntax highlighting (Not even for JavaScript).

It would be great to have proper highlighting for JSX inside *.js and *.jsx files. Github does support JSX

Tested with: Latest Gitlab 7.11.4 and gitlab.com

**Comment by stanhu** [comment]
GitLab currently relies on a fork of [rouge](https://github.com/jneen/rouge) for syntax highlighting. Could you file an issue there?

**Comment by jbbr** [comment]
Done: https://github.com/jneen/rouge/issues/275

**Comment by nhll** [comment]
JSX is now supported on rogue's master branch.

**Comment by stanhu** [comment]
GitLab 8.12 will support JSX!
