### ISSUE TITLE
'Submit comment' keyboard shortcut does not work after editing a comment

### ISSUE THREAD

**Issue by fishermand46** [gitlabhq/gitlabhq#9404]
STR:
1. Create a comment
2. Edit a comment
3. Hit Command + Enter (on Mac)

Expected: Saves comment
Actual: Doesn't save comment

**Comment by stanhu** [comment]
This seemed to work fine for me in GitLab v7.12. Did you have trouble commenting in any particular place (e.g. commit, merge request, etc.)? 

If you can reproduce the problem again, can you check the JavaScript console via the "Inspect Element" button to see if there were any errors that may have prevented the shortcut from firing?

**Comment by fishermand46** [comment]
This is happening when I try to edit a comment or a MR. Not sure about anywhere else. I checked the console, and there are no JS errors when I hit Command + Enter.

GitLab: v7.11.4
Chrome: v43.0.2357.130
OS X : v10.10.13 (Yosemite)

**Comment by stanhu** [comment]
Perhaps it was fixed in GitLab v7.12 via a68eabd.
