### ISSUE TITLE
Should declare VOLUME after COPY

### ISSUE THREAD

**Issue by 3meeb** [gitlabhq/gitlabhq#9407]
In docker/data/Dockerfile the volumes are declared before the copy which means that the copy won't persist to the volume.

**Comment by stanhu** [comment]
This seemed to work fine for me in GitLab v7.12. Did you have trouble commenting in any particular place (e.g. commit, merge request, etc.)? 

If you can reproduce the problem again, can you check the JavaScript console via the "Inspect Element" button to see if there were any errors that may have prevented the shortcut from firing?

**Comment by stanhu** [comment]
Sorry, commented on the wrong issue. Can you explain the issue here? I'm not sure I follow the reasoning here.

**Comment by 3meeb** [comment]
The COPY command copies a file into /etc/gitlab/ which is specified as a VOLUME.

What will happen during docker build is that the gitlab.rb will be copied into the volume of a temporary container which will then be discarded.

I found this to be very helpful when working with Docker volumes:
http://container-solutions.com/understanding-volumes-docker

Check out the "Permissions and Ownership" section for a clearer explanation than mine :)

**Comment by stanhu** [comment]
I think this is now handled in the latest Dockerfile:

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/docker/Dockerfile

Right, @ayufan?

**Comment by ayufan** [comment]
Yes. Omnibus installation creates `/etc/gitlab/gitlab.rb` before `VOLUME` declaration.
