### ISSUE TITLE
can't add new project after update to 7.12 on raspberry pi 2

### ISSUE THREAD

**Issue by yangxuan8282** [gitlabhq/gitlabhq#9408]
after update from 7.9 to 7.12 ,always get error 500 when try to create new project

OS:minibian (a minimal Raspbian-based Linux )

previous **gitlab_7.9.0-omnibus.pi-1_armhf.deb** running quite well on minibian  after **dpkg -i**

but after update to  **gitlab-ce_7.12.0~omnibus+20150622131235-1_armhf.deb**

always get error 500 when i attempt to add new project or check diffs

not found any useful tips in *production.log*，but something like this:

    ActionView::Template::Error (): (execjs):1

**Comment by stanhu** [comment]
A workaround for this issue is to install nodejs:

```
sudo apt-get install nodejs-legacy
```

There is a discussion about this isssue here:

https://gitlab.com/gitlab-org/gitlab-ce/issues/1861

**Comment by maxlazio** [comment]
@yangxuan8282 Can you try [this omnibus-gitlab package](https://downloads-packages.s3.amazonaws.com/raspberry-pi/gitlab-ce_7.12.2~omnibus%2B20150708233719-1_armhf.deb)?

**Comment by yangxuan8282** [comment]
@maxlazio ok,i'll try it

**Comment by yangxuan8282** [comment]
@maxlazio I have installed this version on a new system,it won't work until
 **sudo gitlab-ctl reconfigure** twice 
after that,everything run quite good

I used to get same issues in **gitlab_7.9.0-omnibus.pi-1_armhf.deb**
but not occur  in **gitlab-ce_7.12.0~omnibus+20150622131235-1_armhf.deb**

and the issues #9408 mentioned in this post have been solved

My RPI 2:
- Operating System :  2015-02-18-wheezy-minibian
- Linux Kernel : Linux raspberrypi 4.0.7-v7+ #802 SMP PREEMPT Wed Jul 8 18:01:25 BST 2015 armv7l GNU/Linux  
- File System :  f2fs

**Comment by yangxuan8282** [comment]
@maxlazio  i found that this version will take much more memory than before
  
only one user(myself)
no GUI,only with samba and cifs service
and the Gitlab will never take advantage of swap

in last version used to have 300M+ free memory    

    pi@raspberrypi:~$ free -m

                 total       used       free     shared    buffers     cached
    Mem:           973        967          6          0          0        142
    -/+ buffers/cache:        824        148
    Swap:         1023          0       1023

**Comment by maxlazio** [comment]
@yangxuan8282 Memory management is something that is out of package building scope that I do. Using swap is not even GitLab's task but it is something that operating system handles.

**Comment by yangxuan8282** [comment]
@maxlazio I did mention swap in my reply
but seems like that you just notice this,rather than other feedback
ignore installation and other issues 
I saw you need somebody try the new version,so I take time to try it and post issues here
and I wish I could give useful feedback to improve it,instead of just have flame wars
I am not a expert,but I am trying to give useful feedback as possible as I can

**Comment by maxlazio** [comment]
@yangxuan8282 I am sorry that you feel I ignored something. I read your response which says:

> and the issues #9408 mentioned in this post have been solved

so I thought it is resolved and there is no action I can take related to the package. When you mentioned memory management I've responded with what I know about it. Did I miss something else?
