### ISSUE TITLE
Can't clone repo over HTTP with LDAP authorization

### ISSUE THREAD

**Issue by UnderGreen** [gitlabhq/gitlabhq#9410]
Hello.

I have installed Gitlab server 7.11.4. It is connected with AD over LDAP. Authentication in browser works perfectly. `bundle exec rake gitlab:ldap:check RAILS_ENV=production` say - All OK. But when I try to clone over http I have problem with authorization:
```
git clone http://gitlab.xxx.local/bizaccount/bizaccount-deploy.git
Cloning into 'bizaccount-deploy'...
Username for 'http://gitlab.xxx.local': s.antipov
Password for 'http://s.antipov@gitlab.xxx.local': 
fatal: Authentication failed for 'http://gitlab.xxx.local/bizaccount/bizaccount-deploy.git/'
```

**Comment by UnderGreen** [comment]
In application.log I did't see any errors.

**Comment by Arvur** [comment]
I'm having the same problem with 7.12.0
Did you find any solution?

**Comment by jesseydesu** [comment]
Have same problem on Gitlab 7.13.2 from Omnibus package

**Comment by ramateur** [comment]
The same problem. Web sign in with LDAP auth works well, but http clone fails. Tried https as well with no luck. Result: "fatal: Authentication failed for 'http://..."

# gitlab-rake gitlab:env:info

System information
System:
Current User:   git
Using RVM:      no
Ruby Version:   2.1.6p336
Gem Version:    2.2.5
Bundler Version:1.5.3
Rake Version:   10.4.2
Sidekiq Version:3.3.0

GitLab information
Version:        7.13.4
Revision:       7c3e8bc
Directory:      /opt/gitlab/embedded/service/gitlab-rails
DB Adapter:     postgresql
URL:            http://git.srv.local
HTTP Clone URL: http://git.srv.local/some-project.git
SSH Clone URL:  git@git.srv.local:some-project.git
Using LDAP:     yes
Using Omniauth: no

GitLab Shell
Version:        2.6.3
Repositories:   /var/opt/gitlab/git-data/repositories
Hooks:          /opt/gitlab/embedded/service/gitlab-shell/hooks/
Git:            /opt/gitlab/embedded/bin/git

**Comment by jesseydesu** [comment]
Now we decided to use public key auth, which works perfectly.

**Comment by bozaro** [comment]
I have a same problem with:
```
System information
System: Ubuntu 12.04
Current User: git
Using RVM: no
Ruby Version: 2.0.0p451
Gem Version: 2.0.14
Bundler Version:1.5.3
Rake Version: 10.4.2
Sidekiq Version:3.3.0

GitLab information
Version: 7.12.2
Revision: 30bffd5
Directory: /var/git/engine/gitlab
DB Adapter: postgresql
URL: https://w1-git.mail.msk
HTTP Clone URL: https://git.local/some-project.git
SSH Clone URL: git@git.local:some-project.git
Using LDAP: yes
Using Omniauth: no

GitLab Shell
Version: 2.6.3
Repositories: /var/git/repositories/
Hooks: /var/git/hooks/
Git: /usr/bin/git
```

LDAP users can't authenticate for ```git clone``` and GitLab API.

Authentication in browser works perfectly and non-LDAP users can authenticate for ```git clone``` and GitLab API.

**Comment by ramateur** [comment]
Found some workaround.
Completely removed installed GitLab. Deleted /opt/gitlab and /var/opt/gitlab catalogs. Then installed gitlab version 7.11.4, configured it and checked that clone with LDAP auth was working. After that updated GitLab to version 7.14.3, clone with LDAP auth still worked. Finally updated it to the current version from Ububtu repo 8.0.1 and clone works fine.
If clean install latest version from repo (8.0.1) and configure it, clone with LDAP auth will not work.

**Comment by foxdalas** [comment]
Git push with LDAP Auth not working... Login via Web Ui working fine.

**Comment by zhang-xin** [comment]
It seems this issue also blocks using LFS on latest Gitlab 8.2 with LDAP users, since LFS requires HTTP authentication, not public key auth?

**Comment by bozaro** [comment]
@zhang-xin 
I don't see, how implemented LFS on latest GitLab 8.2.
In base scenario LFS client get token for SSH uses via executing git-lfs-authenticate command. And this token used for HTTP authentication.

**Comment by asavartsov** [comment]
Updated to gitlab 8.2 from 7 with package gitlab-ce on ubuntu 14.04. Now authentication fails for LDAP users when cloning via http. Cloning via ssh works fine, local users (e.g. root) can clone both using http and ssh. LDAP users successfully logs in using web interface.

**Comment by UnderGreen** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/13440
