### ISSUE TITLE
GIT push fails with  message "error: failed to push some refs to" and  "error: git-remote-https died of signal 13"

### ISSUE THREAD

**Issue by kingshuk-chakraborty** [gitlabhq/gitlabhq#9412]
All,

I have been using cvs2git tool to migrate several projects from cvs to github repository. Most of the projects succeeded. But 3 of them failed with the below message when I am running

[root@nj09mhe5384 tdc-misc]# git push --all origin
Counting objects: 8586, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3015/3015), done.
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'https://github.com/kingshuk-chakraborty/tdc-misc2.git'
error: git-remote-https died of signal 13

Having no clue on where to start I tried to run 

GIT_TRANSPORT_HELPER_DEBUG=1 git push --all origin to get a clue about it.
got the below message

Debug: Remote helper: Waiting...
Counting objects: 8586, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3015/3015), done.
Debug: Remote helper quit.8/8586)
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'https://github.com/kingshuk-chakraborty/tdc-misc2.git'
Debug: Disconnecting.
error: git-remote-https died of signal 13

Then I ran with strace -f  and in log found broken pipe error.

[pid 13473] poll([{fd=3, events=POLLOUT}], 1, 1000) = 1 ([{fd=3, revents=POLLERR|POLLHUP}])
[pid 13473] poll([{fd=3, events=POLLOUT}], 1, 0) = 1 ([{fd=3, revents=POLLERR|POLLHUP}])
[pid 13473] write(3, "\25\3\1\0 &(\351\343\305g\16Z4\27t\"\25\334\333U\376\35\317\271\30B\2343\371\364\240"..., 37) = -1 EPIPE (Broken pipe)
[pid 13473] --- SIGPIPE (Broken pipe) @ 0 (0) ---
Process 13473 detached

Having no clue whatsoever. If anyone can give some pointer it will be of immense help. Please note that they don't have any file which is larger than 50mb.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
