### ISSUE TITLE
Commit messages not visible if emoji is present

### ISSUE THREAD

**Issue by jonathanwiesel** [gitlabhq/gitlabhq#9413]
I noticed something odd with the new release(s), if the commit message has an emoji, it's not rendered on the file explorer. 

![screen shot 2015-06-25 at 2 39 56 pm](https://cloud.githubusercontent.com/assets/1326781/8363374/4efcaa92-1b48-11e5-8ca8-91fd62532485.png)

**Comment by NKMR6194** [comment]
Same problem is occurred on list of commits.

![2015-07-22 22 33 33](https://cloud.githubusercontent.com/assets/4254002/8826529/24016014-30c2-11e5-8d67-fe30797ae909.png)

**Comment by jonathanwiesel** [comment]
Any news on this?

**Comment by Razer6** [comment]
Everything after the emoji is truncated. Reproduced in 7.14 on gitlab.com /cc @tsigo

**Comment by tsigo** [comment]
Related: https://gitlab.com/gitlab-org/gitlab-ce/issues/2349

**Comment by Razer6** [comment]
Then I close it here. Continue discussion on GitLab.
