### ISSUE TITLE
Commit validation script

### ISSUE THREAD

**Issue by vinz243** [gitlabhq/gitlabhq#9416]
Hey, I would like to know if it's possible to create some sort of scrit, maybe using webhook, that validate commit given the list of file changed (I would like to forbidden already existing file change). The repo is rather large, 10 Gb, we might not have a lot of RAM, and all files are binary

**Comment by Razer6** [comment]
You may wan to to use git-annex for large binary files. Right now you could try implementing this as a git hook on the server.
