### ISSUE TITLE
API - Email not appearing as group member data

### ISSUE THREAD

**Issue by khrizt** [gitlabhq/gitlabhq#9421]
Hi,

I'm trying to get the info of the owners of a group and the API documentation says that the result will look like this

```
[
        {
          "id": 1,
          "username": "raymond_smith",
          "email": "ray@smith.org",
          "name": "Raymond Smith",
          "state": "active",
          "created_at": "2012-10-22T14:13:35Z",
          "access_level": 30
        },
        {
          "id": 2,
          "username": "john_doe",
          "email": "joh@doe.org",
          "name": "John Doe",
          "state": "active",
          "created_at": "2012-10-22T14:13:35Z",
          "access_level": 30
        }
      ]
```

But in my Gitlab the email or creation date does not appear in the results, is that a bug? Maybe something in the settings that I can't find?

Thanks

**Comment by m4tthumphrey** [comment]
Copied from my response in the PHP issue:

> I've just done a raw request on one of my gitlab installs at `/users` and `/users/1` and the email address is included. Are you an admin of the gitlab your using? If you look [here](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/users.md) you only get the minimum information if you're not an admin...

**Comment by khrizt** [comment]
Ok, it was a user role thing. Thanks
