### ISSUE TITLE
Unable to restore from from MySQL to Postgres conversion

### ISSUE THREAD

**Issue by Tuckie** [gitlabhq/gitlabhq#9423]
Currently following [These instructions](https://gitlab.com/gitlab-org/gitlab-ce/blob/7-12-stable/doc/update/mysql_to_postgresql.md#converting-a-gitlab-backup-file-from-mysql-to-postgres) to conver from a MySQL install to Postgres.

Everything goes fine until I attempt to [restore the modified backup](https://gitlab.com/gitlab-org/gitlab-ce/blob/7-12-stable/doc/raketasks/backup_restore.md#omnibus-installations). I'm getting the error:

```
sudo gitlab-rake gitlab:backup:restore BACKUP=mybackup
Restoring database ...
Restoring PostgreSQL database gitlabhq_production ... START TRANSACTION
SET
SET
SET CONSTRAINTS
psql:/var/opt/gitlab/backups/db/database.sql:28: ERROR:  collation "utf8_unicode_ci" for encoding "UTF8" does not exist
LINE 7:     "sign_in_text" text collate utf8_unicode_ci,
```

Any ideas why this is failing?

For further debugging, here is the first bit of my converted sql dump:

```
-- Converted by db_converter
START TRANSACTION;
SET standard_conforming_strings=off;
SET escape_string_warning=off;
SET CONSTRAINTS ALL DEFERRED;

CREATE TABLE "application_settings" (
    "id" integer NOT NULL,
    "default_projects_limit" integer default NULL,
    "signup_enabled" int4 default NULL,
    "signin_enabled" int4 default NULL,
    "gravatar_enabled" int4 default NULL,
    "sign_in_text" text collate utf8_unicode_ci,
    "created_at" timestamp with time zone default NULL,
    "updated_at" timestamp with time zone default NULL,
    "home_page_url" varchar(510) collate utf8_unicode_ci default NULL,
    "default_branch_protection" integer default '2',
    "twitter_sharing_enabled" int4 default '1',
    "restricted_visibility_levels" text collate utf8_unicode_ci,
    "version_check_enabled" int4 default '1',
    "max_attachment_size" integer NOT NULL default '10',
    "default_project_visibility" integer default NULL,
    "default_snippet_visibility" integer default NULL,
    "restricted_signup_domains" text collate utf8_unicode_ci,
    "user_oauth_applications" int4 default '1',
    "after_sign_out_path" varchar(510) collate utf8_unicode_ci default NULL,
    PRIMARY KEY  ("id")
);
```

Edit: I'm currently running 7.12.0 from source on the original machine & 7.12.0 omnibus on the destination box.

**Comment by shijij** [comment]
Me too.
Many syntax errors while restore the backup. and I have to reinstall Gitlab to get it back to work.

.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
