### ISSUE TITLE
Would it Support Customize Permission?

### ISSUE THREAD

**Issue by luthur** [gitlabhq/gitlabhq#9426]
It would be great that I can customize permission for `Guest Reporter Developer Master Owner`

**Comment by maxlazio** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
