### ISSUE TITLE
can add international language?

### ISSUE THREAD

**Issue by bubifengyun** [gitlabhq/gitlabhq#9427]
i want to introduce gitlab to my friend, but they don't know English very much. Can fork an i18n? May we translate to other language？
Thank you.

**Comment by stanhu** [comment]
There is a long discussion about how best to support internationalization. You may want to read the discussion:

http://feedback.gitlab.com/forums/176466-general/suggestions/3337748-internationalization-add-translations

**Comment by stanhu** [comment]
I'm going to close out this issue for now. Please feel free to add to the discussion in that link.
