### ISSUE TITLE
can tell which version ruby needed while installing?

### ISSUE THREAD

**Issue by bubifengyun** [gitlabhq/gitlabhq#9429]
My Linux, ruby version is 1.9.1. The install-note tell me, reinstall ruby greater than 2.1.6.
could you give us the lowest version of ruby? My net speed is very very slow when download ruby2.1.6. more than ten minute only 0.1% was download. if my ruby 1.9.1 is enough, can i not install higher ruby?

**Comment by stanhu** [comment]
You need Ruby v2.1.6:

https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/installation.md#2-ruby

If at all possible, we recommend that you use the omnibus version instead of installing from source.
