### ISSUE TITLE
sidekiq.log is empty after rm  in omnibus

### ISSUE THREAD

**Issue by adaiguoguo** [gitlabhq/gitlabhq#9437]
After  I rm -rf /opt/gitlab/embedded/service/gitlab-rails/log/sidekiq.log,sidekiq.log has just one line:Logfile created on XXXXXX.
My version is 7.8.1

**Comment by stanhu** [comment]
Are you saying after you remove the file, the file still exists with a log entry? Is it possible that Sidekiq just recreated the file after you removed it?

**Comment by adaiguoguo** [comment]
I mean after I removed the file, then it create one line but no flush any more

**Comment by adaiguoguo** [comment]
I open this issue in gitlab.com,close
