### ISSUE TITLE
GitLab: No user or key was provided

### ISSUE THREAD

**Issue by Asakrua** [gitlabhq/gitlabhq#9439]
# git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 6834, done.
Delta compression using up to 3 threads.
Compressing objects: 100% (5339/5339), done.
Writing objects: 100% (6833/6833), 13.52 MiB | 18.85 MiB/s, done.
Total 6833 (delta 1370), reused 6833 (delta 1370)
remote: GitLab: No user or key was provided.

**Comment by stanhu** [comment]
This error may occur if you try to push to a repository with a user that has a deploy key as the SSH credentials. Can you make sure this is not the case, and that your user's SSH key is part of your profile?

**Comment by Asakrua** [comment]
GitLab: Public deploy leys (0)
Administrator's SSH key (root): 
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAjf/nD1f3KaCZT+sJZlpiuAO7vsFU/Zp+4bYwX4OxevkxcQSkJ29Oxdsro14zTp6AnNosB8flL+OqUVjcYzsw74Gw7Aw5elK3iRAqwj2lYlb0mUvVLu6o254hyE3aAVrnEh8kWfuy1yn82ykvfW4zxNtMVlDQixZksL4sxmW1eIy4aoYSN5pkZa4MXa8ChHeVYQPpLTP5IUEPgqi/0wXsEq8M8W6ImJYMX/jyU4raAJwJCc9i+FfFe4YFrzFUP9pQHpIkIo2Q2Qg90zXtInEYymfu3WaGsjX7AeiTOSaE5uv200YeSv7D4Tz22GdE8LsZaI0U1WiiOrtZph4mMTasSQ== rsa-key-20150708 

cat /home/git/.ssh/authorized_keys
command="/home/git/gitlab-shell/bin/gitlab-shell key-5",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAjf/nD1f3KaCZT+sJZlpiuAO7vsFU/Zp+4bYwX4OxevkxcQSkJ29Oxdsro14zTp6AnNosB8flL+OqUVjcYzsw74Gw7Aw5elK3iRAqwj2lYlb0mUvVLu6o254hyE3aAVrnEh8kWfuy1yn82ykvfW4zxNtMVlDQixZksL4sxmW1eIy4aoYSN5pkZa4MXa8ChHeVYQPpLTP5IUEPgqi/0wXsEq8M8W6ImJYMX/jyU4raAJwJCc9i+FfFe4YFrzFUP9pQHpIkIo2Q2Qg90zXtInEYymfu3WaGsjX7AeiTOSaE5uv200YeSv7D4Tz22GdE8LsZaI0U1WiiOrtZph4mMTasSQ== rsa-key-20150708

**Comment by stanhu** [comment]
What version of GitLab are you running?

I would enable debugging in your `~/.ssh/config` value to see if your git client is presenting the right key:

http://stackoverflow.com/questions/25388499/how-can-i-run-git-push-pull-commands-with-ssh-verbose-mode

**Comment by Asakrua** [comment]
Ubuntu 15.04
Apache2
GitLab 7.12.0
GitLab Shell 2.6.3
GitLab API v3
Ruby 2.2.2p95
Rails 4.1.1

cat /root/.ssh/config
Host myhost.ru
HostName myhost.rucat /
User git
Port 22
IdentityFile ~/.ssh/openssh

cat /home/git/.ssh/config
host localhost
hostname 127.0.0.1
user git
hort 22
IdentityFile ~/.ssh/openssh

**Comment by stanhu** [comment]
Can you run `sudo gitlab-rake gitlab:check` to make sure your GitLab `authorized_keys` is synched properly?

**Comment by Asakrua** [comment]
sudo gitlab-rake gitlab:check
sudo: gitlab-rake: command not found

 sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
....
Check directories and files:
        /home/git/repositories: OK
        /home/git/.ssh/authorized_keys: OK
....

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
