### ISSUE TITLE
What is the release for 13.0 

### ISSUE THREAD

**Issue by dexterddit** [gitlabhq/gitlabhq#9442]
Could you please tell me the dat as i`m waiting for this release , because it will fix an issue that i have with LDAP OUs

**Comment by maxlazio** [comment]
If you mean the release date, GitLab is released  on every 22nd of the month.

This is also shown [on the README page](https://github.com/gitlabhq/gitlabhq#gitlab-release-cycle).

**Comment by dexterddit** [comment]
Ok thanks a lot
