### ISSUE TITLE
Cloning returns "SSL certificate problem: unable to get local issuer certificate"

### ISSUE THREAD

**Issue by kminehart** [gitlabhq/gitlabhq#9443]
My gitlab.rb:
(I got rid of all of the comments to clean it up.)

```ruby
## Url on which GitLab will be reachable.
## For more details on configuring external_url see:
## https://gitlab.com/gitlab-org/omnibus-gitlab/blob/629def0a7a26e7c2326566f0758d4a27857b52a3/README.md#configuring-the-external-url-for-gitlab
external_url 'https://example.com:6443'


## Note: configuration settings below are optional.
## Uncomment and change the value.
############################
# gitlab.yml configuration #
############################
gitlab_rails['gitlab_email_from'] = 'gitlab@example.com'
gitlab_rails['gitlab_email_display_name'] = 'Gitlab'
gitlab_rails['gitlab_email_reply_to'] = 'noreply@example.com'


################################
# GitLab email server settings #
################################

gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "localhost"
gitlab_rails['smtp_port'] = 456
gitlab_rails['smtp_user_name'] = "gitlab@example.com"
gitlab_rails['smtp_password'] = "O5WNASInGW"
gitlab_rails['smtp_domain'] = "example.com"
gitlab_rails['smtp_authentication'] = "login"
gitlab_rails['smtp_enable_starttls_auto'] = true

################
# gitlab-shell #
################

# gitlab_shell['audit_usernames'] = false
gitlab_shell['http_settings'] = { user: 'username', password: 'password', ca_file: '/etc/ssl/certs/cert.pem', ca_path: '/etc/pki/tls/certs/gitlab', self_signed_cert: false}
gitlab_shell['log_level'] = 'DEBUG'
# gitlab_shell['log_directory'] = "/var/log/gitlab/gitlab-shell/"

##################
# GitLab Unicorn #
##################
unicorn['port'] = 6080

################
# GitLab Nginx #
################
## see: https://gitlab.com/gitlab-org/omnibus-gitlab/tree/629def0a7a26e7c2326566f0758d4a27857b52a3/doc/settings/nginx.md
nginx['ssl_certificate'] = "/home/admin/conf/web/ssl.example.com.crt"
nginx['ssl_certificate_key'] = "/home/admin/conf/web/ssl.example.com.key"
```

the ssl.example.com.crt / ca / key / pem is a signed certificate issued by a CA, not a self-signed certificate.

/etc/ssl/certs/cert.pem is the a copied / pasted one 

The contents of "/etc/pki/tls/certs/gitlab is:
```bash
[root@example gitlab]# ls /etc/pki/tls/certs/gitlab
cert.ca  cert.crt  cert.key  cert.pem  COMODORSAAddTrustCA.crt  COMODORSADomainValidationSecureServerCA.crt  externalCAroot.crt
```

and it appears to me that the https connection between any browser I've tried and nginx is successful, I'm still not sure why git doesn't like my certificates.

I've tried using the .key instead of the .pem, I've tried using the crt instead, I've tried manually configuring /var/opt/gitlab/gitlab-shell/config.yml with every crt, ca, .pem, and .key.  I've got nothing else to try.  I'm running gittlab-ctl reconfigure every time I change gitlab.rb, too.

**Comment by stanhu** [comment]
It sounds like you are using the omnibus version. SSL certificates should go into /opt/gitlab/ssl. See:

https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/nginx.md#enable-https

**Comment by shijij** [comment]
@stanhu:

@kminehart has already overwrite the SSL setting for Nginx in the configuration file.

@kminehart : 

Which CA are you using? (I mean things like Comodo Positive SSL, Rapid SSL, etc..)

Make sure you declare your intermediate cert in the config file.

Some times browsers work fine without intermediate cert but others don't.

**Comment by kminehart** [comment]
@stanhu 
@shijij 

It's Comodo Positive SSL.  nginx works fine, all browsers accept the SSL certificate.
I think my issue is I'm using the wrong certificate file for the gitlab-shell.  Should I extract the public key from the private key file and use that one when gitlab-shell asks for the "ca"?  I interpret CA as meaning certificate authority.

So really what certificate file do I use for gitlab-shell's CA?  I think that would fix my problem, since the only SSL related issue i'm having is when I try to do anything, my git on my local machine does not recognize an ssl certificate on the remote repository.

**Comment by shijij** [comment]
@kminehart  What do you mean by "Cloning"?

Clone your project from server to PC?

OR

Setup a Project by cloning an existing project from  third party like github?

**Comment by stanhu** [comment]
Oh, right, I didn't realize you had overridden the config file with your custom paths. That should work.

Have you verified that your site actually has the right intermediate certificates? Browsers may be more forgiving.

```
openssl s_client -showcerts -connect www.domain.com:443
```

Or use a Web site such as:

https://www.sslshopper.com/ssl-checker.html

The Positive SSL Web site includes the intermediate bundle:

https://www.positivessl.com/cert-install.php

**Comment by kminehart** [comment]
@shijij That'd be cloning a project from my server to my PC.

@stanhu sslhopper.com gave me this:

`The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. You can fix this by following Comodo's Certificate Installation Instructions for your server platform (use these instructions for InstantSSL). Pay attention to the parts about Intermediate certificates.`

So the issue is now that my intermediate certificate was not installed correctly?

**Comment by stanhu** [comment]
Yes, see:

https://gist.github.com/bradmontgomery/6487319

https://www.positivessl.com/ssl-certificate-support/cert_installation/apache-ssl.php

> You will need to install the chain certificate (intermediates) in order for browsers to trust your certificate. As well as your SSL Certificate (yourdomainname.crt) three other certificates, named UTN-USERFirst-Hardware.crt, AddTrustUTNServerCA.crt and PositiveSSLCA.crt, are also attached to the email from Positive SSL. Apache users will only require the intermediates AddTrustUTNServerCA.crt and PositiveSSLCA.crt certificates.

> Firstly, create a 'bundle' file. To do this you will need to open the certificates with a text editor and add both of the certificate texts to that file, first the PositiveSSLCA.crt then the AddTrustUTNServerCA.crt and save this file as ca.txt

**Comment by shijij** [comment]
Create a Chained cert.(combine your cert and intermediate cert)
```
$ cat www.example.com.crt intermediate.crt > www.example.com.chained.crt
```

If there is more than one intermediate;

```
$ cat www.example.com.chained.crt intermediate.crt > www.example.com.chained.crt
```

and then use  www.example.com.chained.crt for nginx['ssl_certificate']

**Comment by kminehart** [comment]
Awesome!  So I have an inexpensive SSL certificate from NameCheap, which is a resold COMODO positive SSL certificate.

It came with these files:
`AddTrustExternalCARoot.crt`
`COMODORSAAddTrustCA.crt`
`COMODORSADomainValidationSecureServerCA.crt`
and then I have my `example.com.crt`

I created my ssl-bundle.crt by issuing the folling command:
`[root@example.com ssl]# cat example.com.crt COMODORSAAddTrustCA.crt COMODORSADomainValidationSecureServerCA.crt AddTrustExternalCARoot.crt > ssl-bundle.crt`

The order was important, I tried putting my `example.com.crt` at the end and nginx did not recognize it as a valid pair with my private key.

And then I pointed `nginx['ssl_certificate']` to `ssl-bundle.crt`, and the private key stayed the same as it was earlier.

I ran `gitlab-ctl reconfigure` and now I am cloning via. https correctly, and I don't have to tell git to allow self-signed certificates!  Thanks for pointing me in the right direction @shijij @stanhu

**Comment by stanhu** [comment]
Glad that worked! Yes, it's important to get the right order for the bundle.

**Comment by oneautomate** [comment]
@kminehart It works perfectly, but please note gitlab will cache the SSL cert;
In my case, I have to change it back to use http( "sudo gitlab-ctl reconfigure"), then change it to use https again(with cert chain in customer.domain.com.crt). 
Woo-hoo! It now works with the new cert.

To verify:
openssl s_client -showcerts -connect customer.domain.com:443

It returned 4 certs in my case;
**If it returns only 1 cert, it means gitlab is not using the bundled cert.**

**Comment by lequy1010** [comment]
If you don't use ssl so you can disable it.
`git config --global http.sslVerify false`
