### ISSUE TITLE
Cloning over HTTP failing

### ISSUE THREAD

**Issue by princejoseph** [gitlabhq/gitlabhq#9446]
Cloning over HTTP is giving us this error:

`git clone http://code.example.com/user/cp.git`
`Cloning into 'cp'...`
`remote: Not Found`
`fatal: repository 'http://code.example.com/user/cp.git/' not found`

`bundle exec rake gitlab:env:info RAILS_ENV=production` gives this output

System information
===============
System: Ubuntu 14.04
Current User: git
Using RVM: no
Ruby Version: 2.1.6p336
Gem Version: 2.2.3
Bundler Version:1.10.4
Rake Version: 10.4.2
Sidekiq Version:3.3.0

GitLab information
==============
Version: 7.12.0
Revision: 9852183
Directory: /mnt/datavolume/home/git/gitlab
DB Adapter: mysql2
URL: http://code.example.com
HTTP Clone URL: http://code.example.com/some-project.git
SSH Clone URL: git@code.example.com:some-project.git
Using LDAP: yes
Using Omniauth: no

GitLab Shell
=========
Version: 2.6.3
Repositories: /home/git/repositories/
Hooks: /home/git/gitlab-shell/hooks/
Git: /usr/bin/git

SSH cloning is working fine.

Please help!!!!

**Comment by stanhu** [comment]
Can you run `sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production`?

https://github.com/gitlabhq/gitlab-public-wiki/wiki/Trouble-Shooting-Guide#general

**Comment by princejoseph** [comment]
Checking GitLab Shell ...

GitLab Shell version >= 2.6.3 ? ... OK (2.6.3)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
user2 / dummy-experiments ... repository is empty
user1 / test_1 ... repository is empty
user2 / dummy-experiments-2 ... ok
user3 / test ... repository is empty
user3 / sample ... repository is empty
user4 / my-awesome-project ... repository is empty
user3 / test ... repository is empty
user3 / myproject ... ok
...........
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/home/git/repositories/: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.4
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)
Server: ldapmain
	DN: uid=cino,ou=People,dc=ldap,dc=example,dc=com	 uid: cino
	.............
        .............
Checking LDAP ... Finished

Checking GitLab ...

Git configured with autocrlf=input? ... yes
Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 
user1 / dummy-experiments ... yes
user2 / test_1 ... yes
..........
..........
Projects have satellites? ... 
user1 / dummy-experiments ... yes
user2 / test_1 ... yes
user3 / dummy-experiments-2 ... yes
......
......
user3 / cp ... can't create, repository is empty
user4 / test ... can't create, repository is empty
user1 / graph-demo-import ... can't create, repository is empty
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.6)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.1)
Active users: 9

Checking GitLab ... Finished

**Comment by OscarOrSomething** [comment]
Try https?

**Comment by princejoseph** [comment]
We need http to work first.

**Comment by stanhu** [comment]
Have you tried doing an HTTP clone with a public project?

**Comment by princejoseph** [comment]
yes, public project also fails with the same error.

**Comment by stanhu** [comment]
My only guess is that your Web server is intercepting HTTP Git requests and directing them elsewhere. Do your logs show anything? Is there a reason you are installing from source rather than use the omnibus version?

**Comment by princejoseph** [comment]
When we try to clone the repo using HTTP source, we are getting this on the `tail -f production.log`:

`Started GET "/user1/cp.git/info/refs?service=git-upload-pack" for 202.88.244.19 at 2015-07-13 08:09:47 +0000`

When we access that URL in the browser, we get a page with only `Not Found` written on it. When we access the URL from the browser also, we get the `Started GET` in the production log tail. But only that much is written in the log.

**Comment by princejoseph** [comment]
nginx log (gitlab_access.log) shows this:

`x.x.x.x - - [13/Jul/2015:08:09:01 +0000] "GET /user1/cp.git/info/refs?service=git-upload-pack HTTP/1.1" 404 19 "-" "git/1.8.3.2"`

**Comment by Razer6** [comment]
This will likely be fixed with GitLab 8.0 with a new git-http-server.
