### ISSUE TITLE
Merge request API state=closed do not return expected results

### ISSUE THREAD

**Issue by valermor** [gitlabhq/gitlabhq#9453]
When GET /projects/:id/merge_requests?state=opened is used, the API returns a list of 'opened' AND 'reopened'. Makes sense.

When GET /projects/:id/merge_requests?state=closed is used, the API returns a list of 'closed' and 'merged'. This makes the API unusable since I only need 'closed' MR and need to parse all the history of merge requests to filter only the 'closed' one. Moreover, the question would also be what state=merged in the API is for.

Can we get the API only return MRs that are closed and not merged through state=closed?

**Comment by stanhu** [comment]
Internally it looks like a lot of GitLab code intentionally uses the `closed` term to mean `closed` or `merged` for merge requests. It's easy enough to add something like `closed_only`, but I'm not sure if that will add more confusion. 

I also think that the API is hardly "unusable" if you can still write a simple filter to remove the `closed` entries. Obviously it's not ideal, but it'll work.

What do you think about adding a `closed_only` parameter, @randx?

**Comment by stanhu** [comment]
Perhaps `closed_and_unmerged` is a better term.

**Comment by valermor** [comment]
Thanks for feedback @stanhu. Both proposal would sound ok.
Filtering is an option I have considered. However, it is less simple than it looks (I reckon unusable was a bit strong :-) here). _merged_ requests are the majority and the _/projects/:id/merge_requests_ API results are paginated. This means scanning and processing all the pages back in the history. It would be awesome if the API could just return the _closed_ ones.

**Comment by stanhu** [comment]
Actually, I think 7524d7c0822b9aef962163272874e648ef3bdcff fixes this issue, which will be released in GitLab v7.13 to be released on July 22. `closed` really means just "Closed" now.
