### ISSUE TITLE
default protected branch setting gets ignored

### ISSUE THREAD

**Issue by brightdroid** [gitlabhq/gitlabhq#9460]
With "gitlab-ce-7.12.2~omnibus-1.x86_64" the global admin setting "Default branch protection" is ignored. So Developers can push to the master branch!

It works as expected when I'll add "master" as a protected branch in the repo.

**Comment by stanhu** [comment]
It looks like the "Default branch protection" is only meant to set the default behavior **if** a protected branch is designated in a repository, not as a global parameter to prevent users from pushing to master. Yes, you still have to add `master` as a protected branch. I was a little confused by that too. 

I'll close this issue out for now.

/cc: @CyBeRoni

**Comment by CyBeRoni** [comment]
In fact, it only sets the protection of the first branch pushed (which is designated default) of a new repo at the time of that push. It has no effect after that moment.

**Comment by shinarg** [comment]
Hi,

I'm using version 8.2.3 and still developers can push to master. I have removed the default master branch from protected branches and re added it but still no luck preventing developers from pushing to master.
Moving that same user from developer to reporter indeed blocking him from pushing to master (just to make sure that I really work with this user while using the ssh protocol).

**Comment by CyBeRoni** [comment]
That is not something for this issue. Also, there's a setting called 'developers can push to this branch' which you should disable for that behaviour to work like you want it to.

If you have that disabled and 'developer' users can still push, I'd call that a bug and you should open a new issue.
