### ISSUE TITLE
External milestones

### ISSUE THREAD

**Issue by bostjan** [gitlabhq/gitlabhq#9463]
Hi,

when external/custom issue tracker is used, it would be useful if milestones would link to issue tracker's milestones url too.

I assume this is my preference, and someone else might prefer having milestones in gitlab even if external issue tracker is used, thus I would not bind this functionality to external issue tracker, albeit it would make the most sense that way (at least on the first glance).

I checked the code, it is doable, but I would like your opinion on the matter first, as chances of accepting pull request are higher this way.

Tnx for comments,
b.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
