### ISSUE TITLE
Do not show labels if external issue tracker is used

### ISSUE THREAD

**Issue by bostjan** [gitlabhq/gitlabhq#9464]
Hi,

if merge requests are disabled, and external issue tracker is used, there is little point of having "Labels" and "Milestones" links in the left (project) menu.

The "Milestones" link is actually debatable, see #9463.

The patch is a one-liner:

==============================
--- projects_helper.rb.ORIG	2015-07-18 23:47:27.866332516 +0000
+++ projects_helper.rb	2015-07-18 23:55:00.330617565 +0000
@@ -160,7 +160,7 @@
       nav_tabs << feature if project.send :"#{feature}_enabled"
     end
 
-    if project.issues_enabled || project.merge_requests_enabled
+    if (project.issues_enabled && !project.external_issue_tracker) || project.merge_requests_enabled
       nav_tabs << [:milestones, :labels]
     end
 
==============================

I can create a pull request for this, if you want.

b.

PS: Do you prefer issues and pull requests on GitHub or on Gitlab.com?

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

/cc We prefer them on GitLab.com
