### ISSUE TITLE
Update from 7.4 404 for page /oauth/token

### ISSUE THREAD

**Issue by msahuc** [gitlabhq/gitlabhq#9468]
I manually updated gitlab from 7.4.3 to 7.12.2
I also manually updated gitlab ci to same version
The page gitlab ci calls to get oauth token on gitlab return a 404 code
The url is logged to be processed by ProhectsController
Other oauth url are logged to be processed by Oauth::AuthorizationsController

How can i correct this problem ?

**Comment by stanhu** [comment]
Can you include the relevant logs from `/var/log/gitlab/gitlab-rails/production.log`?

**Comment by msahuc** [comment]
Here the production log when connecting first time from gitlab-ci

- Gitlab production log

`Started GET "/ecv/webtool-dashboard.git/info/refs?service=git-upload-pack" for 127.0.0.1 at 2015-07-22 11:10:08 +0200
Started GET "/oauth/authorize?client_id=ad07b990df37eeac9c8e0f6fd6ae2c7c3bb024ca75a152df8f466af191bb082e&redirect_uri=http%3A%2F%2Fci.ecocenter.fr%2Fuser_sessions%2Fcallback&response_type=code" for 127.0.0.1 at 2015-07-22 11:11:20 +0200
Processing by Oauth::AuthorizationsController#new as HTML
  Parameters: {"client_id"=>"ad07b990df37eeac9c8e0f6fd6ae2c7c3bb024ca75a152df8f466af191bb082e", "redirect_uri"=>"http://ci.ecocenter.fr/user_sessions/callback", "response_type"=>"code"}
Completed 200 OK in 218ms (Views: 185.4ms | ActiveRecord: 10.2ms)
Started POST "/oauth/authorize" for 127.0.0.1 at 2015-07-22 11:11:22 +0200
Processing by Oauth::AuthorizationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "client_id"=>"ad07b990df37eeac9c8e0f6fd6ae2c7c3bb024ca75a152df8f466af191bb082e", "redirect_uri"=>"http://ci.ecocenter.fr/user_sessions/callback", "state"=>"", "response_type"=>"code", "scope"=>"api"}
Redirected to http://ci.ecocenter.fr/user_sessions/callback?code=e849eae78cc447c869b15636f24c6e6b27daa85af40420b2673d4ef84ab63af2
Completed 302 Found in 15ms (ActiveRecord: 3.4ms)
`


- Gitlab ci production log 

`Started GET "/user_sessions/auth" for 127.0.0.1 at 2015-07-22 11:11:19 +0200
Processing by UserSessionsController#auth as HTML
Redirected to http://git.ecocenter.fr/oauth/authorize?client_id=ad07b990df37eeac9c8e0f6fd6ae2c7c3bb024ca75a152df8f466af191bb082e&redirect_uri=http%3A%2F%2Fci.ecocenter.fr%2Fuser_sessions%2Fcallback&response_type=code
Completed 403 Forbidden in 7ms (ActiveRecord: 0.2ms)
Started GET "/user_sessions/auth" for 127.0.0.1 at 2015-07-22 11:11:19 +0200
Processing by UserSessionsController#auth as HTML
Redirected to http://git.ecocenter.fr/oauth/authorize?client_id=ad07b990df37eeac9c8e0f6fd6ae2c7c3bb024ca75a152df8f466af191bb082e&redirect_uri=http%3A%2F%2Fci.ecocenter.fr%2Fuser_sessions%2Fcallback&response_type=code
Completed 302 Found in 5ms (ActiveRecord: 0.2ms)
Started POST "//api/v1/builds/register.json" for 127.0.0.1 at 2015-07-22 11:11:20 +0200
Started GET "/user_sessions/callback?code=e849eae78cc447c869b15636f24c6e6b27daa85af40420b2673d4ef84ab63af2" for 127.0.0.1 at 2015-07-22 11:11:21 +0200
Processing by UserSessionsController#callback as HTML
  Parameters: {"code"=>"e849eae78cc447c869b15636f24c6e6b27daa85af40420b2673d4ef84ab63af2"}
Completed 500 Internal Server Error in 93ms (ActiveRecord: 0.2ms)

OAuth2::Error ( ...html 404 content... ):
  app/controllers/user_sessions_controller.rb:18:in `callback`
`

**Comment by stanhu** [comment]
This looks like some error in the GitLab CI OAuth callback handler. @ayufan, any ideas what's going on here?

**Comment by msahuc** [comment]
DO i need to create an issue on gitlab ci if the problem is there ?
Is the page seeked by gitlab ci an old version one ?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
