### ISSUE TITLE
LDAP users require a "mail" field set, but is not documented anywhere.

### ISSUE THREAD

**Issue by sean-clayton** [gitlabhq/gitlabhq#9471]
**Steps to Reproduce:**
1. Setup LDAP on GitLab like normal
2. Have an LDAP user *not* have their "mail" field set (or any other email-like field)
3. Sign into GitLab with that user
4. Observe that you are asked to change your email to complete your profile, but you can't because LDAP users have their email field disabled

**Steps to fix:**
1. Make the user have a "mail" field set

Related: #8575

**Comment by schaffino** [comment]
+1 on this issue. 
It seems ldap auth is not very flexible on this front. We have a slow turn around on getting attributes added for users in ldap and even as an admin its not possible to modify email for a user in a persistent way. The end result is users unable to access the site until their ldap attributes have been modified.

**Comment by axilleas** [comment]
@sean-clayton I'm not too familiar with LDAP. Is this somehting you can turn into a PR? Where in the docs should this be stated? Thanks!

**Comment by sean-clayton** [comment]
@axilleas I'll talk to my sysadmin on what he'd expect to see in the docs. Would it be best to do a pull request on gitlab.com or here on GitHub?

**Comment by axilleas** [comment]
Preferably on GitLab.com since we are slowly migrating the issue tracker there :)

But we can continue the discussion here as well. On GitLab.com I am `axil` if you want to ping me.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
