### ISSUE TITLE
update to 7.13 resulting in 500 error

### ISSUE THREAD

**Issue by ashwin31** [gitlabhq/gitlabhq#9474]
Just now, I have updated my gitlab instance from 7.12.2 to 7.13.

now its opening perfectly and displaying activity and other pages but resulting 500 when i try to open any git project.
![something went wrong 500](https://cloud.githubusercontent.com/assets/365610/8829860/9bd301b2-30b6-11e5-81fb-41c463967a37.png)

How can i give you more info on this.

**Comment by vsizov** [comment]
please check your logs. What do they say?

**Comment by ashwin31** [comment]
@vsizov where do i check logs? can you tell me the path.

**Comment by vsizov** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/2052 Fix for it already exists. It will be available with the patch release. Probably tomorrow.

**Comment by vsizov** [comment]
I'll close it as a duplicate.

**Comment by ashwin31** [comment]
@vsizov Thank you
