### ISSUE TITLE
Force Push to non protected branches by  Developer or Owner fails

### ISSUE THREAD

**Issue by mmilkin** [gitlabhq/gitlabhq#9478]
```
git checkout -b 'test_branch'
vi test.file
git branch
git add test.file 
git commit -m "adding file"
git push origin test_branch 
git rebase origin/master 
....
git push origin +test_branch


Counting objects: 240, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (219/219), done.
Writing objects: 100% (240/240), 45.70 KiB | 0 bytes/s, done.
Total 240 (delta 155), reused 21 (delta 21)
remote: error: denying non-fast-forward refs/heads/test_branch (you should pull first)
To git@host.com:app/app.git
 ! [remote rejected] test_branch -> test_branch (non-fast-forward)
error: failed to push some refs to 'git@host.com:app/app.git'
```

It looks like GitLab 7.12.2 30bffd5 has a bug where owner or developer can not push the branch

**Comment by jweede** [comment]
Having a similar issue also on 7.12.2 omnibus

 - User in question has 'Owner' privilege
 - Branch in question is not "protected"
 - User is unable to force push, but is able to delete and re-create the branch

Ran `gitlab-rake gitlab:check` as docs suggest. Only clue is:

    Checking GitLab Shell ...
    
    GitLab Shell version >= 2.6.3 ? ... OK (2.6.3)
    Repo base directory exists? ... yes
    Repo base directory is a symlink? ... no
    Repo base owned by git:git? ... no
      User id for git: 997. Groupd id for git: 1228400016
      Try fixing it:
      sudo chown -R git:git /var/opt/gitlab/git-data/repositories
      For more information see:
      doc/install/installation.md in section "GitLab Shell"
      Please fix the error above and rerun the checks.
    Repo base access is drwxrws---? ... yes
    Satellites access is drwxr-x---? ... yes

This is a little odd since we override the git group in `gitlab.rb` to be a different gid (1004), but the user remains the same.

**Comment by jweede** [comment]
Took a closer look over the weekend. For us this issue is because we imported repos with `receive.denyNonFastForwards true` in the `config` file.

This seems to override gitlab hooks. Perhaps the import rake task could be modifed to account for this.

**Comment by javabrett** [comment]
I suffered the same problem on 9.5.5 68ed509 .

- I am _Master_ in the project, which was forked from another project.
- The branch is _not_ protected
- On `push -f ...` I get: Cannot push: `remote: error: denying non-fast-forward`
- I can delete the branch with `git push origin :branchname` then perform a normal push.  This is the workaround.

> Took a closer look over the weekend. For us this issue is because we imported repos with receive.denyNonFastForwards true in the config file.

I suspect that in my case I don't have access to inspect or modify the remote `config`.  Can this be done through any command-line or UI?  I don't have shell-level access to the hosted repo.

Can anything else be done other than delete/re-push?
