### ISSUE TITLE
Merge request change assignee

### ISSUE THREAD

**Issue by klausbayrhammer** [gitlabhq/gitlabhq#9482]
After a gitlab upgrade from 7.12 to 7.13 we are facing two issues concerning assignees for merge requests:
* it isn't possible to change assignees for existing merge requests 
* the assignee/milestone select boxes where missing when creating a new merge request.

We found out that the problem only occured on projects where gitlab's issue tracking is disabled - so as a workaround we activated gitlab's issue tracking for all projects although we don't use it.

**Comment by stanhu** [comment]
This should be fixed by 31dc5e703 and will be released in 7.13.2.
