### ISSUE TITLE
Approve new user by admin for not authorize from email

### ISSUE THREAD

**Issue by first087** [gitlabhq/gitlabhq#9483]
My private server can't send email for authorize account.

In pass version (~7.9). Admin can edit new account, it will authorize pass. But newer version not pass.

Please add feature for approve new user by admin for not authorize from email.

Thank

**Comment by stanhu** [comment]
You can always edit the user's password via the Admin page (Admin -> Users -> select user -> Edit):

/admin/users/newuser/edit
![image](https://cloud.githubusercontent.com/assets/963826/8875357/8402b6a0-31cd-11e5-8d14-1eb03268fe53.png)

**Comment by first087** [comment]
Before edit **New user**
![newuser](https://cloud.githubusercontent.com/assets/6030102/8900628/e277d77e-346b-11e5-857c-043f8da5184f.jpg)

After edit **New user** (in password field), Confirmed status not change.
![editnewuser](https://cloud.githubusercontent.com/assets/6030102/8900629/e55f334c-346b-11e5-82b8-bb71c4847817.jpg)

**Please add feature for approve new user by admin for not authorize from email.**
