### ISSUE TITLE
Passenger error #2 after upgrade from 7.12.2 to 7.13.1

### ISSUE THREAD

**Issue by CobbleCity** [gitlabhq/gitlabhq#9486]
Hi, 

ich have installed the update to 7.13.1 over apt-get (it's was a omnibus installation at the past).

dpkg is failing the installation by an chef configure error.
![bildschirmfoto 2015-07-24 um 21 12 04](https://cloud.githubusercontent.com/assets/1919646/8882618/b11f8034-3248-11e5-8dcf-0f134bdf4584.png)

Output of /opt/gitlab/embedded/cookbooks/cache/chef-stacktrace.out
![bildschirmfoto 2015-07-24 um 21 13 36](https://cloud.githubusercontent.com/assets/1919646/8882645/e8ee5878-3248-11e5-92bd-414419dda2ee.png)

I have restarted the apt-get process and the installation is now successfully and chef ist correct executed in my second try. My Apache show this error since the installation, when the css or js files are loading.
![bildschirmfoto 2015-07-24 um 21 17 00](https://cloud.githubusercontent.com/assets/1919646/8882711/742c571e-3249-11e5-9269-0bab590d2dd0.png)

(See: git.cobblecity.de)

**Comment by maxlazio** [comment]
See https://gitlab.com/gitlab-org/omnibus-gitlab/issues/680#note_1681607

**Comment by CobbleCity** [comment]
This fixes the issue, thanks :)
