### ISSUE TITLE
Readme.md availability on project page not updated when changing the default branch

### ISSUE THREAD

**Issue by qcz** [gitlabhq/gitlabhq#9492]
In one of our repositories there are two brances, X and Y. X (the default branch) is an older version and does not have a Readme.md file. Y is newer and has one. To make the the Readme file appear on the project page, I changed the default branch to Y, but the Readme was still not visible (the project page still displayed the "This project does not have README yet" message.

**Steps to reproduce:**
* Create two branches, one (the default branch) without Readme.md, and an other one with Readme.md
* Change the default branch to the one with Readme.md

**Expected behavior:** After changing to the branch with Readme.md, the readme should be displayed on the project page.

**Observed behavior:** After changing to the branch with Readme.md, the readme still not displayed on the project page.

After a commit has been made to the Y branch, the Readme is displayed on the project page, but this should not be a requirement.
Also the reversed process behaves the same way: if we change the default branch from a branch with a Readme to a branch without a Readme, the readme of the previous branch is still displayed.

**GitLab version:** CE 7.13.1 omnibus

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
