### ISSUE TITLE
about repository backup

### ISSUE THREAD

**Issue by dayiguizhen** [gitlabhq/gitlabhq#9493]
I've try to backup my gitlab manually(backup repositories and database.sql) instead of using command `sudo -u git -H bundle exec rake gitlab:backup:create RAILS_ENV=production` But it was different between two way.

When I backup using command `sudo -u git -H bundle exec rake gitlab:backup:create RAILS_ENV=production` It was well.
![qq 20150727200557](https://cloud.githubusercontent.com/assets/9543865/8905699/0ba40648-349b-11e5-9feb-683fda4411c0.jpg)

But when I backup manually (backup repositories and database.sql) ,There are shmething wrong.This project haven't `commit`.`file`and`network`

![qq 20150727201159](https://cloud.githubusercontent.com/assets/9543865/8905931/e87b5778-349c-11e5-9cc5-75fbf38f146a.jpg)

What's wrong in my operation?

**Comment by stanhu** [comment]
First, you're on different pages: the first screenshot is on the project page, and the second is on the dashboard.

**Comment by dayiguizhen** [comment]
This screenshot is on the project page (backup manually).

![qq 20150727200606](https://cloud.githubusercontent.com/assets/9543865/8922201/86a5ccba-3512-11e5-80e1-4c08fcf0a9a4.jpg)

**Comment by stanhu** [comment]
For some reason, GitLab thinks your repository is empty. Are you sure you backed up and restored the bare repositories to the proper location?

**Comment by dayiguizhen** [comment]
Yes , I found the error.
The repositories privilege is root.So GitLab couldn't read this repository.
