### ISSUE TITLE
Branch names with single quotes breaks Network view

### ISSUE THREAD

**Issue by cinderblock** [gitlabhq/gitlabhq#9500]
Branch names are not getting escaped when passed to a javascript object in the Project Network view.

**Steps to reproduce:**
1. Create a branch with a single quote in the branch name: `Test's-Test`
2. Push to gitlab
3. Look at Project's Network view

**Expected Result:**
Page loads, no errors

**Actual Result:**
Network graph never loads, inspector console shows `Uncaught SyntaxError: Unexpected identifier`

See (https://gitlab.com/cinderblock/Test/network/Test's-Test)

**Comment by stanhu** [comment]
Thanks. Proposed fix here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1063
