### ISSUE TITLE
[Reminder] Gitlab HTML formatter can be dropped with rouge 2.0

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#9501]
This issue is just a reminder for this comment: https://github.com/rumpelsepp/gitlabhq/commit/22d60e30342e9e954bba1d601c8df512c4c9408e#commitcomment-12413239

With rouge 2.0 we will be able to drop some code, which is a good thing!

**Comment by stanhu** [comment]
@rumpelsepp I noticed with the `HTMLGitlab` formatter, mutli-line comments didn't work. I naively switched the formatter to the standard `Html` formatter (and renamed `cssclass` to `css_class`), and everything looked fine. For example:

![image](https://cloud.githubusercontent.com/assets/963826/8986483/401e54bc-3691-11e5-8a8f-35e123679deb.png)

What is `HTMLGitlab` formatter doing that the built-in one isn't?

**Comment by rumpelsepp** [comment]
IIRC it adds `<span>` tags in every line to ensure the line anchors work.

**Comment by stanhu** [comment]
It looks like line anchors work fine. We recently made changes in the JavaScript to grab the closest line. Is that all it does differently?

**Comment by stanhu** [comment]
Oh, the only thing it doesn't seem to do is highlight the line when clicking on it. I'm not sure why that should be dependent on the formatter.

**Comment by rumpelsepp** [comment]
> Oh, the only thing it doesn't seem to do is highlight the line when clicking on it.

That's because the `<span class="line">`s are missing.

**Comment by stanhu** [comment]
Ok, I see that now. It also looks like the `HTMLGitlab` formatter closes off any `<span>` blocks on each line, which breaks multi-line comments.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by rumpelsepp** [comment]
As this is a reminder, which is imo still valid, this issue should be reopened on gitlab.com
