### ISSUE TITLE
renaming namespace breaks projects partial

### ISSUE THREAD

**Issue by jurrack** [gitlabhq/gitlabhq#9505]
I was just renaming a group and also adjusting the namespace.
Something like:

```
https://gitlab.my.domain/old_namespace/project1
```

to 

```
https://gitlab.my.domain/new_namespace/project1
```

All projects are available under the new path, but the projects list within the group is still displaying the old namespace, so browsing to those projects isn't possible in the UI.

Is this a Cache problem or is there any way to trigger a renewal?

was working on GitLab 7.9.3 7ff7e28

**Comment by jurrack** [comment]
Cleaning the Rails Cache helped with this issue.

``` 
Rails.cache.clear 
```

**Comment by Razer6** [comment]
Fixed with https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1101
