### ISSUE TITLE
Incorrect 302 is served for non-authed users when using a subdomain on hostname without a path

### ISSUE THREAD

**Issue by shampine** [gitlabhq/gitlabhq#9506]
Incorrect:
http://git.example.com => 302 => http://example.com  

Working correctly:
http://git.example.com/xyz => 302 => htt://git.example.com/users/sign_in  

Steps to reproduce:

1) GitLab is running on a subdomain
2) Log out
3) Attempt to go to base url without any path
4) Redirected to root domain instead of subdomain + sign in

This does not happen when there is a path, only when it is a pathless subdomain. This is a regression as it did not happen in 7.12. Config is the defaults outside of the subdomain url. Nginx (bundled) is seen serving the 302 and the proper 302 in the logs when this happens.

**Comment by stanhu** [comment]
Do you have a Home page URL set in the Application Settings?

**Comment by shampine** [comment]
Well done. I didn't know that setting even existed. Yes it was set incorrectly. Closing issue as resolved. Cheers.
