### ISSUE TITLE
Recalculate commits? [clear cache?]

### ISSUE THREAD

**Issue by patschi** [gitlabhq/gitlabhq#9509]
I just noticed on my personal GitLab installation that all my projects have 0 commits in the "Explode projects" (/explore/projects) site, even if the projects have more than zero commits.

![2015-07-30_110157-7zel9](https://cloud.githubusercontent.com/assets/2029878/8979508/7ce33232-36aa-11e5-8226-643a690c50a1.png)

Neither clearing the cache with rake nor restarting the GitLab instance does clear the cache to initiate a recalculate a re-count of the commits.

When I pushed a new commit on one of the projects, the correct commit number shows up again. But I don't want to send commits on all my projects just because the count.

Is there any other solution to clear the cache?
Thanks for any help!

Regards,
Patrik

**Comment by fzoske** [comment]
Hi Patrik,
the commits are now stored in the database and gets only updated when you push to the repo.

With GitLab 7.13.2 a rake task was introduced to calculate all commit counts.

gitlab-rake 'gitlab:update_commit_count'

Regards,
Fabian

**Comment by patschi** [comment]
Did work fine, thank you!

But I'm still using the source installation (migration to omnibus is planned in the next time), so I used this command (just if anyone else is in the same situation as me):
<pre>$ cd /home/git/gitlab
$ sudo -u git bundle exec rake gitlab:update_commit_count RAILS_ENV=production
11 projects need to be updated. This might take a while.
Do you want to continue (yes/no)? yes
[...]</pre>

(Just took about two or three seconds.)
