### ISSUE TITLE
Error 500 on merge request with bitnami gitlab 7.12.2

### ISSUE THREAD

**Issue by Matrix-Zhang** [gitlabhq/gitlabhq#9511]
the production.log is :

Started GET "/matrix/SC9830_Android5.1/merge_requests/new?utf8=%E2%9C%93&merge_request%5Bsource_project_id%5D=17&merge_
Processing by Projects::MergeRequestsController#new as HTML
  Parameters: {"utf8"=>"✓", "merge_request"=>{"source_project_id"=>"17", "source_branch"=>"master", "target_project_id"
Completed 500 Internal Server Error in 30441ms (ActiveRecord: 14.2ms)

NoMethodError (undefined method `commits' for false:FalseClass):
  app/services/merge_requests/build_service.rb:27:in `execute'
  app/controllers/projects/merge_requests_controller.rb:79:in `new'

**Comment by stanhu** [comment]
Did `target_project_id` get cut off from the log message? Can you run `sudo gitlab-rake gitlab:check` first?

**Comment by Matrix-Zhang** [comment]
Started GET "/matrix/SC9830_Android5.1/merge_requests/new?utf8=%E2%9C%93&merge_request%5Bsource_project_id%5D=18&merge_request%5Bsource_branch%5D=master&merge_request%5Btarget_project_id%5D=11&merge_request%5Btarget_branch%5D=L601A_rel" for 192.168.8.66 at 2015-07-31 10:50:49 +0800
Processing by Projects::MergeRequestsController#new as HTML
  Parameters: {"utf8"=>"鉁?, "merge_request"=>{"source_project_id"=>"18", "source_branch"=>"master", "target_project_id"=>"11", "target_branch"=>"L601A_rel"}, "namespace_id"=>"matrix", "project_id"=>"SC9830_Android5.1"}
Completed 500 Internal Server Error in 30188ms (ActiveRecord: 9.9ms)

NoMethodError (undefined method `commits' for false:FalseClass):
  app/services/merge_requests/build_service.rb:27:in `execute'
  app/controllers/projects/merge_requests_controller.rb:79:in `new'

-------------------------------------------------------------------------------------

sorry, the above is the whole log....

and the gitlab-rake gitlab:check, the command not found ....

**Comment by stanhu** [comment]
Have you installed GitLab from source? See [these instructions](https://github.com/gitlabhq/gitlab-public-wiki/wiki/Trouble-Shooting-Guide#general) for how to run the check on your system.

**Comment by Matrix-Zhang** [comment]
for convenience, i have used the bitnami gitlab stack....

i was run rake command as the doc https://wiki.bitnami.com/Applications/BitNami_GitLab#How_to_run_rake_commands.3f


root@sw-code:/opt/gitlab-7.12.2-0/apps/gitlab/htdocs# ruby bin/rake gitlab:check RAILS_ENV=production
 Warning 
  You are running as user root, we hope you know what you are doing.
  Things may work/fail for the wrong reasons.
  For correct results you should run this as user git.

Checking GitLab Shell ...

GitLab Shell version >= 2.6.3 ? ... OK (2.6.3)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... no
  Try fixing it:
  sudo chmod -R ug+rwX,o-rwx /opt/gitlab-7.12.2-0/apps/gitlab/repositories/
  sudo chmod -R ug-s /opt/gitlab-7.12.2-0/apps/gitlab/repositories/
  find /opt/gitlab-7.12.2-0/apps/gitlab/repositories/ -type d -print0 | sudo xargs -0 chmod g+s
  For more information see:
  doc/install/installation.md in section "GitLab Shell"
  Please fix the error above and rerun the checks.
Satellites access is drwxr-x---? ... no
  Try fixing it:
  sudo chmod u+rwx,g=rx,o-rwx /opt/gitlab-7.12.2-0/apps/gitlab/gitlab-satellites
  For more information see:
  doc/install/installation.md in section "GitLab"
  Please fix the error above and rerun the checks.
hooks directories in repos are links: ... 
zhi-tech-dev / SC9830_Android5.1 ... ok
zhi-tech-dev / SC9830_Android4.4 ... ok
zhi-tech-dev / SC7731_Android5.1 ... ok
Matrix / SC9830_Android5.1 ... ok
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/opt/gitlab-7.12.2-0/apps/gitlab/repositories: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 3.0.2
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... no
  Try fixing it:
  sudo -u git -H RAILS_ENV=production bin/background_jobs start
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  see log/sidekiq.log for possible errors
  Please fix the error above and rerun the checks.

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Git configured with autocrlf=input? ... Trying to fix Git error automatically. ...Failed
  Try fixing it:
  sudo -u git -H "/opt/gitlab-7.12.2-0/git/bin/git" config --global core.autocrlf "input"
  For more information see:
  doc/install/installation.md in section "GitLab"
Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... no
  Try fixing it:
  Install the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.
Init script up-to-date? ... can't check because of previous errors
projects have namespace: ... 
zhi-tech-dev / SC9830_Android5.1 ... yes
zhi-tech-dev / SC9830_Android4.4 ... yes
zhi-tech-dev / SC7731_Android5.1 ... yes
Matrix / SC9830_Android5.1 ... yes
Projects have satellites? ... 
zhi-tech-dev / SC9830_Android5.1 ... yes
zhi-tech-dev / SC9830_Android4.4 ... yes
zhi-tech-dev / SC7731_Android5.1 ... yes
Matrix / SC9830_Android5.1 ... yes
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.0.0)
Your git bin path is "/opt/gitlab-7.12.2-0/git/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.5)
Active users: 6

Checking GitLab ... Finished

**Comment by stanhu** [comment]
Note the error with the permissions on the satellites:

```
Satellites access is drwxr-x---? ... no
Try fixing it:
sudo chmod u+rwx,g=rx,o-rwx /opt/gitlab-7.12.2-0/apps/gitlab/gitlab-satellites
```

**Comment by Matrix-Zhang** [comment]
3ks a lot. it fixed.....
