### ISSUE TITLE
Import Tickets from Bitbucket

### ISSUE THREAD

**Issue by NiklasMerz** [gitlabhq/gitlabhq#9519]
I used the import script https://github.com/gitlabhq/gitlab-recipes/blob/master/import/bitbucket/bitbucket2gitlab.rb and it imported the tickets exactly the wrong way. So my first ticket was in Gitab the one with the highest number.

**Comment by stanhu** [comment]
Thanks for reporting the issue. Proposed fix here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1226
