### ISSUE TITLE
Gitlab-CI status badge missing

### ISSUE THREAD

**Issue by tmaczukin** [gitlabhq/gitlabhq#9523]
Hi,

After adding changes in the layout of project dashboard in 7.13 version you've lost integration with gitlab-ci status badge.

It's not an critical issue, but this badge was very usable. I could open the project page in gitlab and check if the tests for current git ref are green. Now i must go to gitlab-ci, find my project (the status badge was also a link - and now i must remember URL or find it manually on gitlab-ci dashboard), open a project dashboard and find last build for the git ref. It's annoying ;)

I know, that i can insert link to the badge in my README file. But that mean that I should change the "?ref=" parameter in README on each branch and tag. Previously it was done automatically by gitlab.

I noticed that a method which generates gitlab-ci badge URL is still in model - you've only deleted its usage (the 'aside' partial for old template of project dashboard). It would be very nice if you can bring this badge back. I think that the project dashboard is the best place for it.

**Comment by futurekill** [comment]
+1 for this.

**Comment by fr3dm4n** [comment]
+1
I absolutely admit to tmaczukin. Just updated from 7.12 to 7.13. 
It would be really nice, if somebody could bring the badge back :+1:

**Comment by jaffacake** [comment]
+1 I was wondering where it had disappeared to, definitely miss it :(

**Comment by Wolfium** [comment]
Same for me :+1:

If possible would be great to get it back... :smile:

**Comment by Razer6** [comment]
Will be added when GitLab CI comes into GitLab

**Comment by hobarrera** [comment]
> Will be added when GitLab CI comes into GitLab

Since this issue has been closed, where exactly can we track this?

**Comment by Razer6** [comment]
Here you go https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1204

**Comment by hobarrera** [comment]
Thank you. :)

**Comment by tmaczukin** [comment]
@Razer6 Thanks for your answers

**Comment by daniel-simpson** [comment]
+1
