### ISSUE TITLE
I cannot Enter Chinese title in wiki inside gitlab

### ISSUE THREAD

**Issue by jstdoit** [gitlabhq/gitlabhq#9524]
I cannot Enter Chinese title in wiki inside gitlab

**Comment by Razer6** [comment]
Chinese titles are not supported as https://github.com/gitlabhq/gitlabhq/pull/9319 invalidates them

**Comment by jstdoit** [comment]
It is designed not to support Chinese or any reason else?

**Comment by Razer6** [comment]
Yes. AFAIK the underlying gollum lib does not support chinese filenames in their pages.

**Comment by jstdoit** [comment]
But It is not that good, as we all know.
