### ISSUE TITLE
Allow rename filename in web UI

### ISSUE THREAD

**Issue by andytruong** [gitlabhq/gitlabhq#9525]
We can now edit, delete code file right in the web UI like Github, but can't rename. I think this is a missing feature.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

**Comment by andytruong** [comment]
Oh! I am sorry http://feedback.gitlab.com/forums/176466-general/suggestions/9174371-allow-rename-filename-in-web-ui
