### ISSUE TITLE
asana service template does not inherit api key to asana service on project

### ISSUE THREAD

**Issue by i-chess** [gitlabhq/gitlabhq#9531]
Hello
I configured asana service template with asana API key
then I went to enable the asana service on the project, and it can't inherit or remember the asana API key.
I assumed that the idea of service template is to easily apply this on the project.

**Comment by i-chess** [comment]
gitlab instance at gitlab.ichess.co.il:10080

**Comment by stanhu** [comment]
Unfortunately, currently only new projects will pick up the new settings in the service templates. I verified that if you create a new project with the Asana API, the project does get this key. Perhaps there would be a way to populate the settings if the service has never been configured, but that is not supported at the moment.
