### ISSUE TITLE
Every merge request claims conflcits

### ISSUE THREAD

**Issue by d3athrow** [gitlabhq/gitlabhq#9532]
just switched to gitlab, every merge request so far has claimed it has conflicts and on manually merging it shows that it does not have any conflicts. whats up with that.

**Comment by fr3dm4n** [comment]
I just faced the same problem. It seems to be something is wrong with the satellites.
The problem occured after a merge per CLI.

Following made it work für me: 

```bash
cd /home/git/gitlab-satellites
mv <repository-name> <repository-name>-backup
cd /home/git/gitlab
sudo -u git -H bundle exec rake gitlab:satellites:create RAILS_ENV=production
```

Also you might take a look at the file owner. All files musst belong to the git-user

**Comment by Razer6** [comment]
Satellites are removed with the upcoming GitLab 8.0.
