### ISSUE TITLE
Restore from old files

### ISSUE THREAD

**Issue by mcmonkey4eva** [gitlabhq/gitlabhq#9534]
I have a dead old machine with no recent enough backups available, and a new machine running an empty gitlab instance - how do I restore my Gitlab **users**, **repositories**, and hopefully comments/issues/etc. though that last bit isn't really required.

In theory, it's just a matter of copying over the correct files... but I imagine it's going to be a bit more complicated.

(Note: I have the full original harddrive, just... no way to boot it at the moment. Worst case scenario is I might be able to attach to a different machine in a week or so, and then perform a backup from that and transfer that over?)

**Comment by stanhu** [comment]
Was your old instance using a source install or omnibus?

You're probably best off [running the backup task](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/raketasks/backup_restore.md) on the old instance, installing the same omnibus version, and then doing a restore with the archive.

**Comment by mcmonkey4eva** [comment]
Omnibus. And, again - I can't boot the old instance. At all. It is damaged.

**Comment by stanhu** [comment]
Can you still access the files? I would copy everything from:

1. /opt/gitlab
1. /var/opt/gitlab
1. /etc/gitlab

**Comment by mcmonkey4eva** [comment]
I can! However that doesn't account for SQL/etc. stored information.

... But I did just convince the beast to boot through some extreme cheating involving spare pieces of hardware. I successfully made a backup and an preparing for a 'proper' transfer :D

**Comment by stanhu** [comment]
Great! If you are using the omnibus version of PostgreSQL, then all the database data should be stored in /var/opt/gitlab.
