### ISSUE TITLE
Show correct help for merge request with conflicts

### ISSUE THREAD

**Issue by 2ndkauboy** [gitlabhq/gitlabhq#9536]
When a merge request as a conflict, there is a link to show a modal on how to resolve it on the command line. But the modal is showing the following hint:

> Step 1. Update the repo and checkout the branch we are going to merge
> 
> git fetch origin
> git checkout -b feature-branch origin/feature-branch
> 
> Step 2. Merge the branch and push the changes to GitLab
> 
> git checkout master
> git merge --no-ff feature-branch
> git push origin master

This hint is wrong, as it would not resolve the conflict on the branch, but merges the branch into master. A step 2 like the following would be correct:

```
git merge master
git push origin feature-branch
```

or even 

```
git rebase master
git push --force
```

But the first solution is probably better for unexperienced users.

**Comment by axilleas** [comment]
I believe the instructions are for manually merging the MR without using GitLab UI. They are not intended for the user that created the MR but the one that will eventually merge it.

But I see your point and we may need to clarify this.

**Comment by 2ndkauboy** [comment]
Yes, it's the exact same text as in the modal for merging the MR manually. Maybe you even got a correct text but you show the wrong one.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
