### ISSUE TITLE
Some sort of audit

### ISSUE THREAD

**Issue by Alexhha** [gitlabhq/gitlabhq#9539]
Hello we are using gitlab-7.6.2_omnibus.5.3.0.ci.1-1 on CentOS 6. And my colleagues ask me an interesting question. Is it possible to know who had an access to specific repository and what command has been used. For example something like the following

    ip user_name CLONE gitlab.example.com/group1/project11.git
    ip user_name PUSH gitlab.example.com/group2/project21.git

Thanks in advance

**Comment by Razer6** [comment]
Yes Enterprise edition supports audit events. See http://doc.gitlab.com/ee/administration/audit_events.html#audit-events Clone/Push events are not yet supported. You may want to raise a feature request at http://feedback.gitlab.com
