### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory 

### ISSUE THREAD

**Issue by guoyoujin** [gitlabhq/gitlabhq#9542]
How do you do when I install the following error

root@iZ94w9irr4pZ:/opt/gitlab/embedded/cookbooks/gitlab/recipes# sudo gitlab-ctl reconfigure
[2015-08-09T01:24:31+08:00] FATAL: Errno::ENOMEM: Cannot allocate memory - fork(2)
root@iZ94w9irr4pZ:/opt/gitlab/embedded/cookbooks/gitlab/recipes#

**Comment by axilleas** [comment]
That means your machine needs more RAM.
