### ISSUE TITLE
Login Error 500

### ISSUE THREAD

**Issue by lipg** [gitlabhq/gitlabhq#9548]
7.10.1CE,
Well before, today will not be able to log in.

<img width="717" alt="2015-08-10 2 31 19" src="https://cloud.githubusercontent.com/assets/7782635/9160454/85be90d4-3f6c-11e5-9629-5b775263169b.png">

**Comment by Razer6** [comment]
Fixed with https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1170
