### ISSUE TITLE
GitLab Flavoured Markdown: render UML diagrams by adding 'Syntax Highlightning' for PlantUML

### ISSUE THREAD

**Issue by janklostermann** [gitlabhq/gitlabhq#9550]
### now 
there is syntax highlightning for some languages (Ruby, Python, etc.) using
```
 '''language
 code
 '''
```
(using apostrophes for the backticks here)

### wanted
to add [PlantUML](http://plantuml.com/) to the languages 
to gain:
`'''plantuml`
for code fencing
-> with the difference that the output is not a beautified code, but a UML diagram. The PlantUML text (http://plantuml.com/PlantUML_Language_Reference_Guide.pdf) is replaced by the UML diagram's graphic.

### expected result
getting the power of UML inside the markdown documents without the cost of unmaintainable inserted graphics

### how
replacing the pygments highlightner by the PlantUML renderer in case of 'plantuml' as language

**Comment by Razer6** [comment]
You may want to raise a feature request at https://github.com/jneen/rouge, which is the used syntax highlighter.

**Comment by janklostermann** [comment]
@Razer6 : I do not believe, that Rouge will feel responsible for this, as syntax highlighning is something very different to interpreting it.
They might be interested in syntax highlight the Plant-UML text, but not in the conversion into a graphic.
Furthermore it would probably spoil their interface, that for syntax highlighning just needs to return text... (not a graphics file)

Therefore I would suggest a switch at the point where you (Gitlab) invoke [rouge](https://github.com/jneen/rouge). For some specific languages like PlantUML (or Graphviz, etc.), which are textual markup for graphics, the respective markup-interpreter could be invoked and return the graphic to be displayed.

There could be even a further parameter to the interpreter, in case of Plantuml: png, svg, text (default (without that parameter) would be png). E.g.

    ''' plantuml svg   

    <plantUML-code> 

    '''   

with ''' replaced with 3 back-ticks, to get the graphic returned as svg.

Therefore I would like to ask you to reopen this issue again. Thanks for considering it.

**Comment by Razer6** [comment]
I see what you mean. Interesting feature request, you may want to raise one at http://feedback.gitlab.com

**Comment by jqueraltmo** [comment]
It's already there, I added it a few days ago: http://feedback.gitlab.com/forums/176466-general/suggestions/9493548-gitlab-flavoured-markdown-render-uml-diagrams-by

Thank you.

**Comment by janklostermann** [comment]
Cool. Thank you!

Jan

Von unterwegs gesendet. Sent from my phone. 

-------- Ursprüngliche Nachricht --------
Von: Joan Queralt <notifications@github.com> 
Datum:06.09.2015  17:47  (GMT+01:00) 
An: gitlabhq/gitlabhq <gitlabhq@noreply.github.com> 
Cc: janklostermann <jk@janklostermann.de> 
Betreff: Re: [gitlabhq] GitLab Flavoured Markdown: render UML diagrams by
  adding 'Syntax Highlightning' for PlantUML (#9550) 

It's already there, I added it a few days ago: http://feedback.gitlab.com/forums/176466-general/suggestions/9493548-gitlab-flavoured-markdown-render-uml-diagrams-by

Thank you.

**Comment by DracoBlue** [comment]
:+1: 

Would be very nice!

**Comment by devcurmudgeon** [comment]
+1

**Comment by a-komarev** [comment]
That would be one of the most valued features for development workflow.

**Comment by vazyzy** [comment]
+1

**Comment by Master-Wang** [comment]
Why closed, could you tell me? @janklostermann

**Comment by janklostermann** [comment]
GitLab did not feel responsible, then saw the point. Someone else then 
created the feature request, suggested by the GitLab team. I checked on 
this one about a week ago, but could not find it anymore. So I do not 
know, what the current status is. :-(

Just have a look at the issue's thread, there you can see what happened...


Am 2016-05-11 um 07:40 schrieb wangyifan:
>
> Why closed, could you tell me? @janklostermann 
> <https://github.com/janklostermann>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gitlabhq/gitlabhq/issues/9550#issuecomment-218366707>
>

-- 
Jan Klostermann
- The Agile Management Sounding-Board -
Systems Engineer & Mediator
Am Isarkanal 24/15
81379 München

Tel.: +49-89/74563382
Mobil: +49-179/4628819
Sip: +49-89/21551663 <sip:08921551663@sipgate.de>
Skype: jan.klostermann <callto://jan.klostermann/>
Threema: P58VSJUY <threema://add?id=P58VSJUY>
Email: jk@janklostermann.de <mailto:jk@janklostermann.de>
Netzwerke: Xing <https://www.xing.com/profile/Jan_Klostermann>, LinkedIn 
<http://de.linkedin.com/in/janklostermann>

**Comment by jqueraltmo** [comment]
This is the issue at GitLab.org: https://gitlab.com/gitlab-org/gitlab-ce/issues/4048
@janklostermann @Master-Wang

**Comment by danielslcdevshop** [comment]
+1

**Comment by thalesfsp** [comment]
So?

**Comment by DracoBlue** [comment]
There is an active MR here https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8588

**Comment by mattwilliamson** [comment]
+1

**Comment by cnadiminti** [comment]
+1  
I like to have this feature.

**Comment by axd1967** [comment]
+1

**Comment by axilleas** [comment]
This is already implemented https://docs.gitlab.com/ee/administration/integration/plantuml.html.
