### ISSUE TITLE
Make contributions calendar optional via configuration flag

### ISSUE THREAD

**Issue by artem-sidorenko** [gitlabhq/gitlabhq#9552]
Currently the contributions calendar in the user profile can't be disabled via settings in the admin interface. In some cases it might be better to have a way to disable it (ideally together with a graph function) because of some possible requirements from instances like workers council in big organisations.

Would you accept a merge request which adds a new option in the settings to disable the contributions calendar?

**Comment by JobV** [comment]
@artem-sidorenko is this something that would be interesting for your organisation? I've never heard this from any org. before.

**Comment by artem-sidorenko** [comment]
@JobV welcome in the world of big German companies (or even government structures) :)

I would like to explain a background a bit here: "performance tracking" of employees is such structures is a typical no-go to protect the employees in person (yes, this is in deed a quite common thing in German big organisations with a strong workers counsel or employee unions).

The entire data in this case are stored in Git(lets call it RAW data) and this contribution calendar provides an aggregated view from this RAW data very simple (just with one click). Exactly here is the point, this feature can be used very easy by employer to do performance tracking of employees (like developers). The main difference in my eyes between the aggregated information and RAW data is the effort to aggregate it, as here you get it directly.

Please don't get me wrong, I understand that I'm discussing about a feature which is useful and used everywhere. I don't want to discuss the reasons about a such "no-go" requirement, it's more or less a fact for me and I have to deal with it somehow. So I would like to have a way to disable such features just to avoid/prevent such discussions in my organisation (and possible blockers to use gitlab only because of that).

Right now my solution looks like:
 - The access to the "Graphs" functions is blocked with an according message via regexp in nginx
 - I'm constantly maintaining a patch to remove "contributions calendar" from a profile view

Thats why I would like to ship a patch with a possibility to disable the "contributions calendar"(but to keep it on by default) to get rid of this patch maintenance in the future

**Comment by JobV** [comment]
Thanks for the explanation @artem-sidorenko, I wasn't aware of this requirement for German companies. Very interesting.

I understand that it is annoying for you to have to manage this.

That said, I'm not sure we're likely to accept such a merge request. Making any part of GitLab configurable has consequences:

- it's more likely to break when changes are made
- the burder of support and documentation is added
- we're less flexible in making changes to this and surrounding parts
- the above in turn makes us unable to move very fast in our development, which is something we want to hang on as much as possible

For this feature and the fact that this is the first time I hear about this, I think these consequences are too heavy. If more customers come to us about this, we can always go back on that decision.

@randx what do you think? Should we accept merge requests that make the contribution calendar visibility configurable? I think no. I've also not heard about this before from any of our customers.

**Comment by artem-sidorenko** [comment]
@JobV I can completely follow your reasons and understand this :)
But just to give you another reference(yeah, in English!), I'm talking not only about my employer:

http://www.taylorwessing.com/globaldatahub/article_negotiating_dp_policies_germany.html

As a consequence, employee data protection in Germany is still regulated under general statutory provisions, ranging from provisions in the Federal Data Protection Act (“Bundesdatenschutzgesetz”) to respective provisions in the Works Constitution Act (“Betriebsverfassungsgesetz”). This situation is often quite confusing for employers running businesses in the German jurisdiction, especially when companies from foreign jurisdictions enter the German market.
....
In general, the works councils have the right to co-determination in matters affecting organisational structure, personnel decisions, and policies regulating workplace and individual conduct within the company (works councils would, for example, have to be involved in the supervision of evaluation of employee performance, e.g. for the purposes of salary calculations). This means that any proposed policy or general measure of the employer must first be approved by the works council in order to be implemented by the company.

**Comment by randx** [comment]
I agree with @JobV. We try to avoid extra configuration except the cases when it absolutely necessary or requested by a lot of organisations. 

@artem-sidorenko maybe you can talk to layer to find out if it can be a legal problem or not. And if yes - just make a patch which hide user calendar. In future if we get such request from more organisations - we re-think our decision.

**Comment by artem-sidorenko** [comment]
@randx @JobV as I already said, its a problem for us (and will be a point for other big German enterprises). But Ok, I understand your reasons and will continue to maintain the patch

**Comment by artem-sidorenko** [comment]
Thx anyway;)

**Comment by randx** [comment]
@artem-sidorenko thanks for understanding :)

**Comment by asrmchq** [comment]
Hi @randx & @JobV we are have the same problem as @artem-sidorenko.

We are moving away from cvs to git and looking at a gitlab server for which we will
also need to get workers council approval. We have not started the approval process
yet but at the minute it looks as if we will need to disable the "contributors graph",  the
"contributions calendar" and eventually the "cycle-analytics" (when the teams are too  
small). Again its about employee data protection and employer monitoring and evaluation
and the workers council can prohibit us from using gitlab and that would be a bit of a shame.

**Comment by artem-sidorenko** [comment]
@asrmchq regarding contribution calendar: I removed [this](https://gitlab.com/gitlab-org/gitlab-ce/blob/35142a097865b1083ddea95c8507aab07e52a4ed/app/views/users/show.html.haml#L103-107)

And graphs were blocked via nginx regexp pattern
