### ISSUE TITLE
Make project import functionality be configurable from admin interface

### ISSUE THREAD

**Issue by artem-sidorenko** [gitlabhq/gitlabhq#9553]
In some setups not all possible project import sources are used(and configured).
The idea is to add options to the admin settings interface, there some sources can be disabled/enabled, e.g. to allow import from Github, but not from Bitbucket.

Would you accept a MR providing this functionality?

**Comment by stanhu** [comment]
Again, I'll defer to @JobV for this. :)

**Comment by JobV** [comment]
@artem-sidorenko unless there is a good reason to disable them, probably not.

I think we would accept MRs that would clean the UI up by hiding them / making it a single button with multiple options if done.

**Comment by artem-sidorenko** [comment]
@JobV I provided the reasons in the MR #9563 and there is the current WIP implementation with screenshots. May you please have a look if its reasonable and the implementation looks good for you?

**Comment by artem-sidorenko** [comment]
Resolved by #9563

**Comment by JobV** [comment]
Thanks @artem-sidorenko! +1 for cleaning up!
