### ISSUE TITLE
v7.13.3 has removed all ability to manage issues

### ISSUE THREAD

**Issue by poolski** [gitlabhq/gitlabhq#9555]
Having upgraded to v7.13.3, I've found that for some reason, despite being an administrator, I can't create and modify issues or labels on *any* projects. 

Anyone else have this problem?

**Comment by vsizov** [comment]
I can't reproduce.

**Comment by poolski** [comment]
It may well be something that's irrevocably screwed in my installation. I'll need to dig further.

**Comment by jvanbaarsen** [comment]
Since we can't reproduce, I'm closing this issue
