### ISSUE TITLE
Project Activity Page is Blank When Filtered by Team

### ISSUE THREAD

**Issue by demisx** [gitlabhq/gitlabhq#9559]
I am on 7.13.4 and clicking on "Activity" nav link for each project results in blank page (see image below). I do not see any errors in the `production.log`.

![screen shot 2015-08-13 at 8 30 52 pm](https://cloud.githubusercontent.com/assets/4452412/9266750/369bc6c6-41fa-11e5-89bc-a16d2b514286.png)

**Comment by stanhu** [comment]
Does clicking on any of the filter buttons change anything? Can you run "Inspect Element" in your browser to see if there are any errors on the JavaScript console or the Network page?

![image](https://cloud.githubusercontent.com/assets/963826/9266828/428ab932-41fb-11e5-9613-f202a5191047.png)

**Comment by demisx** [comment]
Yes, if I click on "Push Events" or any other filter, I can see the activity log. It's blank only when I have the "Team" filter selected. Don't see any errors in the Javascript console.

**Comment by stanhu** [comment]
I think this may be intentional. The "Team" filter only shows events of members joining/leaving projects.

**Comment by demisx** [comment]
I see. Then, I believe showing a sentence explaining that in lieu of the blank page I think would be a good UX move. Otherwise, it appears broken.

**Comment by jvanbaarsen** [comment]
This problem has been resolved in a newer version
