### ISSUE TITLE
gitlab keep sending same email forever

### ISSUE THREAD

**Issue by i-chess** [gitlabhq/gitlabhq#9560]
Hello
I configured the "Email on push" service with email list of
ichess@ichess.co.il ; maor@ichess.co.il
and then after a commit (call it commit A) was made, for some reason from now on this commit email are sent again and again forever
I "fixed" the list to be seperated by colon :
ichess@ichess.co.il ,maor@ichess.co.il
and the problem is gone for the next commits.
so I keep getting the commit A emails on and on forever.
I'm using sendmail configuration as follows :
```
gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "localhost"
gitlab_rails['smtp_port'] = 8025
# gitlab_rails['smtp_user_name'] = "gitlab"
# gitlab_rails['smtp_password'] = "gitlab"
gitlab_rails['smtp_domain'] = "ichess.co.il"
gitlab_rails['smtp_authentication'] = false
gitlab_rails['smtp_enable_starttls_auto'] = false
gitlab_rails['smtp_tls'] = false
# gitlab_rails['smtp_openssl_verify_mode'] = 'none' # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
# gitlab_rails['smtp_ca_path'] = "/etc/ssl/certs"
# gitlab_rails['smtp_ca_file'] = "/etc/ssl/certs/ca-certificates.crt"

gitlab_rails['gitlab_email_from'] = 'gitlab@ichess.co.il'
gitlab_rails['gitlab_email_reply_to'] = 'noreply@ichess.co.il'
```
If you can also please instruct me how to flush outgoing email queue...

Thanks
Ran

**Comment by i-chess** [comment]
my gitlab instance is at 
http://gitlab.ichess.co.il:10080/
and I can grant root access for developers to debug, or provide logs, etc

**Comment by i-chess** [comment]
here is some sample log from the admin area, background jobs, Retries section :

about 8 hours from now	13	default	EmailsOnPushWorker	
1, "ichess@ichess.co.il ; maor@ichess.co.il", {"object_kind"=>"push", "before"=>"4ff0576733647c6632807feaf4c65f0bf8b662d4", "after"=>"a88c0041ff5b18136ac1e787dd5e42bde01e619e", "ref"=>"refs/heads/master", "checkout_sha"=>"a88c0041ff5b18136ac1e787dd5e42bde01e619e", "message"=>nil, "user_id"=>2, "user_name"=>"Ran Berenfeld", "user_email"=>"ichess@ichess.co.il", "project_id"=>1, "repository"=>{"name"=>"ichess-il", "url"=>"git@gitlab.ichess.co.il:root/ichess-il.git", "description"=>"", "homepage"=>"http://gitlab.ichess.co.il:10080/root/ichess-il", "git_http_url"=>"http://gitlab.ichess.co.il:10080/root/ichess-il.git", "git_ssh_url"=>"git@gitlab.ichess.co.il:root/ichess-il.git", "visibility_level"=>0}, "commits"=>[{"id"=>"a88c0041ff5b18136ac1e787dd5e42bde01e619e", "message"=>"ant version 1.9.6\nhttps://app.asana.com/0/45478884761328/45478884761330\n", "timestamp"=>"2015-08-13T19:12:43+03:00", "url"=>"http://gitlab.ichess.co.il:10080/root/ichess-il/commit/a88c0041ff5b18136ac1e787dd5e42bde01e619e", "author"=>{"name"=>"Ran Berenfeld", "email"=>"ichess@ichess.co.il"}}], "total_commits_count"=>1}, {"send_from_committer_email"=>false, "disable_diffs"=>false}
Net::SMTPFatalError: 550 5.1.1 <

**Comment by rumpelsepp** [comment]
Please use code blocks like this

```
code
```

use three backticks for this. :)

**Comment by i-chess** [comment]
thanks ! done

**Comment by stanhu** [comment]
You may be able to [flush the Redis cache](https://github.com/gitlabhq/gitlabhq/blob/master/doc/raketasks/maintenance.md#clear-redis-cache) to remove that job.

**Comment by i-chess** [comment]
well I removed the job from the background tasks...
still I think there is a bug there. probably since the list was email1 ; email2 there was some error that triggered a task retry, however email1 was already sent

**Comment by stanhu** [comment]
Yeah, I added a merge request to discard incorrect/invalid e-mail addresses:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1163

**Comment by i-chess** [comment]
I think its also best to put some example list of addresses in the "email on push" service page.
