### ISSUE TITLE
blob.text blob.image  Why？

### ISSUE THREAD

**Issue by bigsurge** [gitlabhq/gitlabhq#9566]
- if blob.text?
      = render "text", blob: blob
    - elsif blob.image?
      = render "image", blob: blob
    - else
      = render "download", blob: blob

**Comment by bigsurge** [comment]
blob = user_project.repository.blob_at(commit.sha, file_path)
获取的blob对象里没有text image方法，但从页面代码看是有这些属性的
请问到底这两个属性是怎么来的？

**Comment by Razer6** [comment]
this is fixed AFAIK
