### ISSUE TITLE
except master branch,other branch blame redirect to 500

### ISSUE THREAD

**Issue by dayiguizhen** [gitlabhq/gitlabhq#9568]
If I was on master branch ,watch blame view is fine.

![qq 20150819181829](https://cloud.githubusercontent.com/assets/9543865/9353901/980911cc-469e-11e5-9c49-4f8a935e5c19.jpg)

![qq 20150819181845](https://cloud.githubusercontent.com/assets/9543865/9353902/9a9466b2-469e-11e5-8d17-5c1d8fdb3098.jpg)

but when I checkout on other branch,I get 500 view

![qq 20150819180432](https://cloud.githubusercontent.com/assets/9543865/9353910/b679f9b4-469e-11e5-90a7-67b9697d7206.jpg)
![qq 20150819180448](https://cloud.githubusercontent.com/assets/9543865/9353911/b904b598-469e-11e5-8564-0ed169a4d921.jpg)

info:
    
    System information
    System:		Ubuntu 14.04
    Current User:	git
    Using RVM:	no
    Ruby Version:	2.1.5p273
    Gem Version:	2.2.2
    Bundler Version:1.10.6
    Rake Version:	10.3.2
    Sidekiq Version:2.17.0
    
    GitLab information
    Version:	7.5.3
    Revision:	b656b85
    Directory:	/home/git/gitlab
    DB Adapter:	mysql2
    URL:		http://10.1.0.91:8088
    HTTP Clone URL:	http://10.1.0.91:8088/some-project.git
    SSH Clone URL:	ssh://git@10.1.0.91:29418/some-project.git
    Using LDAP:	no
    Using Omniauth:	no
    
    GitLab Shell
    Version:	2.2.0
    Repositories:	/home/git/repositories/
    Hooks:		/home/git/gitlab-shell/hooks/
    Git:		/usr/bin/git

**Comment by stanhu** [comment]
I noticed you're using an old version of GitLab. Would you be able to upgrade to 7.13?

**Comment by dayiguizhen** [comment]
@stanhu 

I'm used `sudo -u git -H ruby -Ilib -e 'require "gitlab/upgrader"' -e 'class Gitlab::Upgrader' -e 'def latest_version_raw' -e '"v7.13.5"' -e 'end' -e 'end' -e 'Gitlab::Upgrader.new.execute'` command but get the error

    Migrate DB
     -> bundle exec rake db:migrate
    rake aborted!
    ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.5.2/lib/execjs/runtimes.rb:48:in `autodetect'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.5.2/lib/execjs.rb:5:in `<module:ExecJS>'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.5.2/lib/execjs.rb:4:in `<top (required)>'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/coffee-rails-4.1.0/lib/coffee-rails.rb:1:in `<top (required)>'
    /home/git/gitlab/config/application.rb:6:in `<top (required)>'
    /home/git/gitlab/Rakefile:5:in `require'
    /home/git/gitlab/Rakefile:5:in `<top (required)>'
    (See full trace by running task with --trace)
     -> FAILED
    Failed to upgrade. Try to repeat task or proceed with upgrade manually

What's wrong with that?

If I only use `app/views/projects/blame/show.html.haml` newer replace older,is this helpful?

**Comment by maxlazio** [comment]
You are missing nodejs, install that and run again.

**Comment by dayiguizhen** [comment]
@maxlazio 
When I want upgrade gitlab again,it tell I already latest GitLab version

    root@2124c6a3543f:/home/git/gitlab# sudo -u git -H ruby -Ilib -e 'require "gitlab/upgrader"' -e 'class Gitlab::Upgrader' -e 'def latest_version_raw' -e '"v7.13.5"' -e 'end' -e 'end' -e 'Gitlab::Upgrader.new.execute'
    GitLab 7 upgrade tool
    Your version is 7.13.5
    Latest available version for GitLab 7 is 7.13.5
    You are using the latest GitLab version

**Comment by dayiguizhen** [comment]
I'm upgrade secceed.The gitlab works will
