### ISSUE TITLE
Tag count differs depending on where I am on the site

### ISSUE THREAD

**Issue by linagee** [gitlabhq/gitlabhq#9569]
I'm using many many tags. It seems like the code is using two different styles of counting tags. One count appears to show my many tags nearly instantly. The other count appears to only show it correctly after some time. (Perhaps some process in the background hasn't ran yet?) Is this on purpose to have two different tag counts like this? (They are *usually* the same.)

I'm using package manager installed (debian) GitLab 7.13.5, but I see that on the master branch these lines are exactly the same.

Here are the files: (and the line that I think is doing this strangeness.)

/opt/gitlab/embedded/service/gitlab-rails/app/views/projects/show.html.haml
```
24         = pluralize(number_with_delimiter(@repository.tag_names.count), 'tag')
```

/opt/gitlab/embedded/service/gitlab-rails/app/views/projects/commits/_head.html.haml
```
22       %span.badge.js-totaltags-count= @repository.tags.length
```

(It looks like you can strip off the /opt/gitlab/embedded/service/gitlab-rails/ from the above to get the gitlabhq/gitlabhq "github hosted" location.)

Also, if you use lightweight (not annotated) tags, they appear to not ever be included in the count for app/views/projects/show.html.haml

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
