### ISSUE TITLE
Restoring Backups is Broken

### ISSUE THREAD

**Issue by NeilBetham** [gitlabhq/gitlabhq#9571]
I'm currently in the process of trying to migrating one server to another using a backup. However during the process of restoring the rake task was unable to unpack the database dump because it is getting deleted when the backup::database class is initialized. I believe that [these lines](https://github.com/gitlabhq/gitlabhq/blob/master/lib/backup/database.rb#L10-L14) are responsible for the problem.

**Comment by stanhu** [comment]
@jacobvosmaer This seems bad--looks like the `rm` can't be done at init time?

**Comment by jacobvosmaer** [comment]
I am looking into this.

**Comment by jacobvosmaer** [comment]
Confirmed. This problem exists only in the 7.14 release candidates. Thanks for finding it @NeilBetham !!

This fixes it:

```
diff --git a/lib/backup/database.rb b/lib/backup/database.rb
index 939f28f..ce75476 100644
--- a/lib/backup/database.rb
+++ b/lib/backup/database.rb
@@ -7,14 +7,15 @@ module Backup
     def initialize
       @config = YAML.load_file(File.join(Rails.root,'config','database.yml'))[Rails.env]
       @db_dir = File.join(Gitlab.config.backup.path, 'db')
+    end
+
+    def dump
       FileUtils.rm_rf(@db_dir)
       # Ensure the parent dir of @db_dir exists
       FileUtils.mkdir_p(Gitlab.config.backup.path)
       # Fail if somebody raced to create @db_dir before us
       FileUtils.mkdir(@db_dir, mode: 0700)
-    end
 
-    def dump
       success = case config["adapter"]
       when /^mysql/ then
         $progress.print "Dumping MySQL database #{config['database']} ... "
```

**Comment by jacobvosmaer** [comment]
MR: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1182

**Comment by NeilBetham** [comment]
No worries!
