### ISSUE TITLE
Is there a function similair to the closing of issues available for creating new issues?

### ISSUE THREAD

**Issue by timkoers** [gitlabhq/gitlabhq#9574]
GitLab is very powerful with the 'auto close' feature that scans the commit message for issues that need to be closed (etc.)

But is such a feature available for the creation of issues as well? That would be very handy.

**Comment by stanhu** [comment]
Not at the moment. I'm not quite sure how this would even work, but if you do please feel free to add a feature request here: 

http://feedback.gitlab.com/forums/176466-general
