### ISSUE TITLE
Wiki search results point to raw source instead of HTML Web page

### ISSUE THREAD

**Issue by demisx** [gitlabhq/gitlabhq#9581]
Wiki links showing up in the search results currently point directly to the markdown files (e.g. `https://git.colddata.com/reports/productA-com-reports/wikis/SQL-queries.md`). Clicking on such link takes you to a raw text version of the Wiki page instead of HTML (see images below). For UX purposes, it should link to the corresponding Wiki HTML page, so markdown is shown formatted instead of a raw source.

![screen shot 2015-08-25 at 11 26 08 am](https://cloud.githubusercontent.com/assets/4452412/9475537/1cbf542c-4b1c-11e5-9ce4-97c36c1da0c3.png)

![screen shot 2015-08-25 at 11 28 44 am](https://cloud.githubusercontent.com/assets/4452412/9475591/795c7e76-4b1c-11e5-9291-900d7e98aacf.png)

**Comment by liquidstate** [comment]
:+1: 

This is a real pain as we use the built-in wiki for a lot of our documentation.

**Comment by andyjeffries** [comment]
:+1:

Please fix, the same as @liquidstate we currently have a lot of documentation and want to use this properly.

**Comment by nchapon** [comment]
:+1: 
Same as @andyjeffries

**Comment by liquidstate** [comment]
Can anyone suggest a better test?  The current test reports as passing.  This might help throw some focus on getting this bug fixed!

https://github.com/gitlabhq/gitlabhq/blob/master/features/steps/project/wiki.rb
```
  step 'I search for Wiki content' do
    fill_in "Search in this project", with: "wiki_content"
    click_button "Search"
  end

  step 'I should see a link with a version ID' do
    find('a[href*="?version_id"]')
  end
```

**Comment by hiroponz** [comment]
I have created MR https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3138.
