### ISSUE TITLE
Use git and gitattributes for show diff in binary files

### ISSUE THREAD

**Issue by JohnBat26** [gitlabhq/gitlabhq#9583]
Hello.
I'd like to see diff between binary files in web interface of gitlab.
I set up several useful utilities and created file  gitattributes with next content:

~~~
*.doc diff=catdoc
*.xls diff=xls2csv
*.xlsx diff=xlsx
*.docx diff=pandoc
*.pdf diff=pdf2txt
*.odt diff=odt2txt
*.ods diff=odt2txt
*.odp diff=odt2txt
*.png diff=exif
*.jpg diff=exif
*.gif diff=exif
~~~

But, how I understood, Gitlab use Diffy gem for this goal.
Can Gitlab use git diff with gitattributes for binary files?

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
