### ISSUE TITLE
Search Option needed in Branches

### ISSUE THREAD

**Issue by Petchimuthu** [gitlabhq/gitlabhq#9593]
Hi,

     Unable to search/select a branch in the Branches page. We need to travel page by page and need to check branches one by one.

Please provide an option to search. Its already available in the commits page.

Thanks,
Muthu.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
