### ISSUE TITLE
[IE issue] file name is cracked when download from gitlab (korean only)

### ISSUE THREAD

**Issue by darkrasid** [gitlabhq/gitlabhq#9595]
When download some file which named in Korean, file name is cracked in IE.

![cracked_korean](https://raw.githubusercontent.com/darkrasid/test/master/cracked_korean.JPG)

This problem is because of filename option from send_data of RawController.   
When I remove 20 line on RawController it works well.(filename: @blob.name)  
I test it gitlab 7-14-stable.

**Is there any problem when I remove filename? **  
I test IE10, chrome, firefox but I cannot find any trouble. 

But I guess there is some reason that the filename option is added.
I am worried about deleting the code so I want to ask you guys.  
Any idea?

**Comment by stanhu** [comment]
I think the filename is just a hint, so it may not be absolutely necessary. However, it would still be useful to know why the encoding is not working here.

Can you cut and paste the text of the filename so that somebody can reproduce it?

**Comment by yms9654** [comment]
+1

**Comment by darkrasid** [comment]
Thank you for your opinion.  

You can test any word in Korean.
For example..

`한글한글.pptx`
`한글파일.md`

Thank you.

**Comment by stanhu** [comment]
It looks like this issue fails also on IE11 when you click the "Raw" button:

![image](https://cloud.githubusercontent.com/assets/963826/9622720/cbf72f26-50eb-11e5-8603-16c03eaae898.png)

Interestingly enough, the network browser seems to interpret the filename fine:

![image](https://cloud.githubusercontent.com/assets/963826/9622725/debdf28e-50eb-11e5-8467-d580b191e555.png)

**Comment by stanhu** [comment]
It looks like the `Content-Disposition` is the culprit:

http://blogs.msdn.com/b/ieinternals/archive/2010/06/07/content-disposition-attachment-and-international-unicode-characters.aspx

![image](https://cloud.githubusercontent.com/assets/963826/9622759/6cdadaf0-50ec-11e5-88c0-637f65214b3a.png)

**Comment by darkrasid** [comment]
Now I understand why this problem happen.

And I think it's better way to remove filename and set disposition to 'inline' or 'attachment'.
Because blob.name would same as name of file from path and inline or attachment will be mapping it.
So I guess without blob.name it give same result.

Thank you :)

**Comment by stanhu** [comment]
I came to the same conclusion after reading this:

http://greenbytes.de/tech/tc2231/

**Comment by stanhu** [comment]
Submitted a fix here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1235
