### ISSUE TITLE
Suggest: add setting to customize date/time format

### ISSUE THREAD

**Issue by simone-sanfratello** [gitlabhq/gitlabhq#9600]
Hi, I've quickly search on open issues but I did not found it; sorry if duplicate.
I suggest to add in personal settings and/or in general configuration (/etc/gitlab/gitlab.rb) a field for customize date and time format

thank you

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
