### ISSUE TITLE
Lost comment due to lack of connection

### ISSUE THREAD

**Issue by jpillora** [gitlabhq/gitlabhq#9603]
I wrote a long long comment on a pull request, hit send, it disappears, nothing happens. I realize I'm not on the work VPN. Tried to undo. Nothing. Please change it so it waits for a `200` before deleting the comment :disappointed:.

**Comment by Razer6** [comment]
@DouweM When are comments store din the browser?

**Comment by jpillora** [comment]
@Razer6 I looked into it. They get put in local storage as you type though get deleted instantly with the comment when you click send.

**Comment by Razer6** [comment]
@DouweM Could this be changed to delete them when there is a response?

**Comment by DouweM** [comment]
I had the same problem at some point, and changed the code to only reset when the `ajax:success` event is fired: https://github.com/gitlabhq/gitlabhq/commit/351e61f4b27f287778cf778a41f1a4e4cef977e2 I haven't had the issue since, and am not sure why you are.

**Comment by Razer6** [comment]
@jpillora On what version are you?

**Comment by jpillora** [comment]
Ahhh `GitLab 7.9.1 6f6c5f1` will attempt an upgrade tonight. Thanks guys
