### ISSUE TITLE
Comment directly on file@revision

### ISSUE THREAD

**Issue by hwinkel** [gitlabhq/gitlabhq#9606]
For reviewing whole Documents like markdown documetation or starting to review existing projects it would be good to be able to comment directly on the files at a particular revision.

I.e. phabricator is able to do so.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

/cc @JobV
