### ISSUE TITLE
SSH keys not blocked when LDAP-user blocked

### ISSUE THREAD

**Issue by ax2m** [gitlabhq/gitlabhq#9608]
When you lock a user in LDAP, he can work with git via ssh. When user blocked in LDAP, how can automatically delete or lock the ssh-keys?

**Comment by Difrex** [comment]
+1

**Comment by w1r0x** [comment]
+1

**Comment by vitek16** [comment]
I confirm that this situation is reproduced. Please take all possible measures to address potential vulnerabilities in the product.

**Comment by just-bank** [comment]
+1

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
