### ISSUE TITLE
gitlab-shell v2.6.5

### ISSUE THREAD

**Issue by dukex** [gitlabhq/gitlabhq#9616]
Hi everybody,
Thanks for doing this awesome project.

I'm updating the gitlab and I notice the gitlab-shell v2.6.5 bumped by @tsigo on https://github.com/gitlabhq/gitlabhq/commit/4d6f8a6aee345d12d81f03f8dc1dfdfc2e3bd777 isn't released yet in https://github.com/gitlabhq/gitlab-shell, so what's wrong the commit or the gitlab-shell?

**Comment by stanhu** [comment]
I've synched gitlab-shell on GitHub and pushed the latest tag. Everything should be there now.

**Comment by tsigo** [comment]
My fault, neglected to push the tag to the GitHub mirror.

Thanks @stanhu!

**Comment by dukex** [comment]
Thank you guys!
