### ISSUE TITLE
install gitlab-ce_7.12.2~omnibus-1_amd64.deb fail

### ISSUE THREAD

**Issue by Matrix-Zhang** [gitlabhq/gitlabhq#9619]
Starting Chef Client, version 12.4.0.rc.0
resolving cookbooks for run list: ["gitlab"]
Synchronizing Cookbooks:
  - package
  - gitlab
  - runit
Compiling Cookbooks...
Recipe: gitlab::default
  * directory[/etc/gitlab] action create (up to date)
  
  ================================================================================
  Recipe Compile Error in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/default.rb
  ================================================================================
  
  NoMethodError
  -------------
  undefined method `[]' for nil:NilClass
  
  Cookbook Trace:
  ---------------
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:177:in `block (2 levels) in read_gitlab_secrets'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:175:in `each'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:175:in `block in read_gitlab_secrets'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:174:in `each'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:174:in `read_gitlab_secrets'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/gitlab.rb:70:in `generate_secrets'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/gitlab.rb:285:in `generate_config'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/default.rb:37:in `from_file'
  
  Relevant File Content:
  ----------------------
  /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:
  
  170:      if File.exists?("/etc/gitlab/gitlab-secrets.json")
  171:        existing_secrets = Chef::JSONCompat.from_json(File.read("/etc/gitlab/gitlab-secrets.json"))
  172:      end
  173:  
  174:      existing_secrets.each do |k, v|
  175:        v.each do |pk, p|
  176:          # Note: Specifiying a secret in gitlab.rb will take precendence over "gitlab-secrets.json"
  177>>         Gitlab[k][pk] ||= p
  178:        end
  179:      end
  180:    end
  181:  
  182:    def self.write_to_gitlab_secrets
  183:      secret_tokens = {
  184:                        'gitlab_shell' => {
  185:                          'secret_token' => Gitlab['gitlab_shell']['secret_token'],
  186:                        },
  
  
  Running handlers:
[2015-09-11T13:27:22+08:00] ERROR: Running exception handlers
  Running handlers complete
[2015-09-11T13:27:22+08:00] ERROR: Exception handlers complete
[2015-09-11T13:27:22+08:00] FATAL: Stacktrace dumped to /opt/gitlab/embedded/cookbooks/cache/chef-stacktrace.out
  Chef Client failed. 0 resources updated in 1.714481982 seconds
[2015-09-11T13:27:23+08:00] ERROR: undefined method `[]' for nil:NilClass
[2015-09-11T13:27:23+08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
-------------------------------------------------------------------------------------------------------------------------------
I was used bitnami-gitlab stack before, but it upgrade so diffcuty...

so i want to try gitlab-ce, when i installed the newest verison 7.14, and restore the backup....

it told me the version is mismatch....

so i try to install the 7.12.2, but it failed.....

**Comment by Matrix-Zhang** [comment]
the /opt/gitlab/embedded/cookbooks/cache/chef-stacktrace.out

Generated at 2015-09-11 13:27:22 +0800
NoMethodError: undefined method `[]' for nil:NilClass
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:177:in `block (2 levels) in read_gitlab_secrets'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:175:in `each'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:175:in `block in read_gitlab_secrets'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:174:in `each'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helper.rb:174:in `read_gitlab_secrets'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/gitlab.rb:70:in `generate_secrets'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/gitlab.rb:285:in `generate_config'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/default.rb:37:in `from_file'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/run_context.rb:174:in `load_recipe'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/run_context.rb:97:in `load'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/client.rb:256:in `setup_run_context'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/client.rb:454:in `run'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application.rb:259:in `fork'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application.rb:259:in `fork_chef_client'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application.rb:213:in `run_chef_client'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application/client.rb:392:in `loop'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application/client.rb:382:in `run_application'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/lib/chef/application.rb:60:in `run'
/opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.0.rc.0/bin/chef-client:26:in `<top (required)>'
/opt/gitlab/embedded/bin/chef-client:23:in `load'
/opt/gitlab/embedded/bin/chef-client:23:in `<main>'

**Comment by Matrix-Zhang** [comment]
delete /etc/gitlab/gitlab-secrets.json ok,,,,

**Comment by Matrix-Zhang** [comment]
close

**Comment by stanhu** [comment]
This is fixed in GitLab 7.14.2:

https://gitlab.com/gitlab-org/omnibus-gitlab/commit/ef76c81d7b71f72d6438e3458d61ecaef8965e17

**Comment by utamas** [comment]
deleting worked for me, thank you

**Comment by TestSmirk** [comment]
this work for me too, and other trouble with me. sad..
