### ISSUE TITLE
Debate: Current navigation system

### ISSUE THREAD

**Issue by matejkramny** [gitlabhq/gitlabhq#9623]
The current navigation system, while its OK, it presents some UX difficulties over the old navigation system.

![screen shot 2015-09-14 at 11 28 44](https://cloud.githubusercontent.com/assets/797608/9847844/e408711e-5ad3-11e5-9d10-4e715c8e1e58.png)

- The language I speak and write (English) is Left-to-right. It means that systematically I read the page from left to right. The first thing I see then is the navigation, and its not *content* therefore it shouldn't really be there.
- The page loses about 30% of width. I know its not an issue for users who have a fullscreen chrome with 1920x1080 resolution, but as most pages are designed 1024px wide I keep my chrome around the same size. This then presents an issue because the page thinks my display is small, and only displays icons in the navigation bar.
- The nav icons are hard to read and i have to guess to know what page they lead to.
- If this design were so good, Github would have implemented it (way before Gitlab was popular). The fact that they have not makes me think that there is a better way to navigate the page.

**Comment by craftbyte** [comment]
:+1:

**Comment by maxlazio** [comment]
@askyruler Can you comment?

> If this design were so good, Github would have implemented it 

FWIW I don't agree with this and I am not sure I prefer githubs design.

**Comment by matejkramny** [comment]
examples of some services i know of:

- Bitbucket uses the same design, but it looks a lot clearer now and they seem to be shifting away from it by putting navigation on the top again.
- Mailchimp used to have two columns of the vertical navigation on the left of the page. [Old](http://www.digitalmarketinghq.com/wp-content/uploads/2013/05/mailchimp-get-api-keys-for-plugin.jpg) vs [new](https://dbfv8p2wljo34.cloudfront.net/web/brand-assets/MC_Reports.png)
- Pingdom has recently done an overhaul of their design, it now looks (imho) terrible. [old](http://torquemag-hhvm.s3.amazonaws.com/uploads/2013/04/pingdom-real-user-monitoring-summary-600x428.png) vs [new](https://cloud.githubusercontent.com/assets/797608/9849126/cf46fabe-5adf-11e5-8fea-ae3542e05a15.png)

**Comment by skyruler** [comment]
@matejkramny Thank you for the ideas that you shared, we are working really hard to deliver the best possible experience to our product, however as a modern web app with lots of features and actions we need to keep our navigation pattern as simple as possible to minimise the confusion, also we can reduce scrolling by giving the content more heigh to work with.

**Comment by matejkramny** [comment]
I understand. Is there a thread on this topic I can read through?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
