### ISSUE TITLE
getting 405 Method not allowed when trying to update 'body' in merge request note

### ISSUE THREAD

**Issue by valermor** [gitlabhq/gitlabhq#9624]
When I try to change 'body'
PUT /projects/:id/merge_requests/:merge_request_id/notes/:note_id

I am getting 405 Method not allowed:

Content-Type: text/plain 
Transfer-Encoding: chunked 
Connection: keep-alive
Status: 405 Method Not Allowed
Allow: OPTIONS, GET, HEAD 
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Access-Control-Expose-Headers:
Access-Control-Max-Age: 1728000
Access-Control-Allow-Credentials: true
Vary: Origin 
Cache-Control: no-cache 
...

Is the method supported?

**Comment by stanhu** [comment]
As far as I can tell, the API method you want is this:

https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/notes.md#modify-existing-issue-note

**Comment by valermor** [comment]
@stanhu the link you sent applies to *issues*. I need to change notes in *merge requests*. A bit below in the same page of the documentation. https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/notes.md#modify-existing-merge-request-note
Or am I missing anything?

**Comment by stanhu** [comment]
Sorry, I got confused by the `rake routes` output since the notes API is not listed. Looking at the API code, the merge request note endpoint should be available. It looks like an admin user is required to access the PUT endpoint, though. Are you using the right user?

**Comment by valermor** [comment]
Is a *Master* not enough to edit notes? Above that, only *Owner* would exist.

**Comment by valermor** [comment]
Update. I have tried with a user which is *Owner* and that also gets a 405 Method Not Allowed.

**Comment by stanhu** [comment]
Yeah, Master access should be sufficient.

I just tried this on my development system, and the update worked:

```
 curl -X PUT --header "PRIVATE-TOKEN: <MY API KEY>" "http://localhost:3000/api/v3/projects/gitlab-org%2Fgitlab-test/merge_requests/30/notes/611?body=hello"
```

**Comment by valermor** [comment]
Hi Stan. Tried just after upgrading to 7.14.3 (it was 6.x before) and the issue has disappeared.
It looks as if that could be a hidden issue.
Cheers!
