### ISSUE TITLE
Gitlab issue number

### ISSUE THREAD

**Issue by mattseymour** [gitlabhq/gitlabhq#9626]
Is there a simple way to start gitlab ticket numbers from value `X`? We are currently using trac for ticketing and want to move across to gitlab. We do not mind loosing the tickets from trac but we do NOT want duplicate ticket numbers for our project.

I would like gitlab ticketing numbers to start from 1000

**Comment by ttasanen** [comment]
Create a "dummy" issue in your project and after that change the `iid` of that issue to 999 in your  `issues` database table. Then the next issue created will have the `iid` of 1000.

**Comment by vicvega** [comment]
You should migrate issues from trac to gitlab
Take a look at http://eric.van-der-vlist.com/blog/2013/11/06/from-trac-to-gitlab/

**Comment by stanhu** [comment]
@mattseymour There isn't a supported way out of the box, but you should be able to follow @ttasanen's instructions. You can also play with the [sequence numbers of the database](https://www.scriptscribe.org/databases/the-postgres-equivalent-of-mysqls-auto_increment/), but that is for expert users.
