### ISSUE TITLE
GitLab CE Omnibus installation doesn't work

### ISSUE THREAD

**Issue by vaziuok** [gitlabhq/gitlabhq#9636]
### Summary
GitLab package server doesn't work, I should be able to download the package over the bash.

### Steps to reproduce
```bash
curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
```

### Expected behaviour
I followed the documentation (https://about.gitlab.com/downloads/#debian8) and when I try to install the package, I'll get always an error. The error is:
```
Unable to download repo config from: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.list?os=debian&dist=sid&name=hostname&source=script
```
Operation system is Debian 8. When I try to request this page with the browser, I'll get an error message, that the page doesn't exist.

![screencapture-packages-gitlab-com-install-repositories-gitlab-gitlab-ce-config_file-list-1442408918132](https://cloud.githubusercontent.com/assets/4311489/9905372/e5b5a27c-5c84-11e5-89fb-fb34ecfa8077.png)

This issue has to be fixed asap, the installation doesn't work and the only alternative is to do everything manually.

**Comment by JosepEscobar** [comment]
I have same problem

**Comment by vaziuok** [comment]
@JosepEscobar Thanks, that worked for me! But still for other people this issue isn't solved.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
