### ISSUE TITLE
Asana service is broken!

### ISSUE THREAD

**Issue by nalilord** [gitlabhq/gitlabhq#9637]
The Asana service is broken,

from the log:

Started GET "/name/repo/services/asana/test" for 127.0.0.1 at 2015-09-16 10:59:34 +0200
Processing by Projects::ServicesController#test as HTML
  Parameters: {"namespace_id"=>"name", "project_id"=>"repo", "id"=>"asana"}
Completed 500 Internal Server Error in 945ms

ActiveResource::ResourceNotFound (Failed.  Response code = 404.  Response message = Not Found.):
  app/models/project_services/asana_service.rb:112:in `block in check_commit'
  app/models/project_services/asana_service.rb:111:in `each'
  app/models/project_services/asana_service.rb:111:in `check_commit'
  app/models/project_services/asana_service.rb:94:in `block in execute'
  app/models/project_services/asana_service.rb:93:in `each'
  app/models/project_services/asana_service.rb:93:in `execute'
  app/controllers/projects/services_controller.rb:41:in `test'

I also tried to update the asana gem from 0.0.6 to the latest 0.3.0 but this doesn't work either, i guess they changed something essential, log output:

Started GET "/name/repo/services/asana/test" for 127.0.0.1 at 2015-09-16 15:15:57 +0200
Processing by Projects::ServicesController#test as HTML
  Parameters: {"namespace_id"=>"name", "project_id"=>"repo", "id"=>"asana"}
Completed 500 Internal Server Error in 40ms (ActiveRecord: 5.1ms)

NoMethodError (undefined method `configure' for Asana:Module):
  app/models/project_services/asana_service.rb:75:in `execute'
  app/controllers/projects/services_controller.rb:41:in `test'

So I leave it to you guys ;)

**Comment by stanhu** [comment]
@j0k3r, do you know anything about this?

**Comment by j0k3r** [comment]
1. Which version of Gitlab are you using?
1. Did you made any changes in the `asana_service.rb` ? Because reported lines aren't the same as in the repo.
1. Does the token is valid for you Asana project?
1. Does the user associated to this token has access to the target project in Asana?

As a side note, we are using Gitlab 7.14.1 and every thing works great.

**Comment by nalilord** [comment]
Jep, I changed the message for the comment, but that's not the reason I believe, I also tried it with the official version, it's the same:

Started GET "/name/repo/services/asana/test" for 127.0.0.1 at 2015-09-16 17:09:16 +0200
Processing by Projects::ServicesController#test as HTML
  Parameters: {"namespace_id"=>"name", "project_id"=>"repo", "id"=>"asana"}
Completed 500 Internal Server Error in 701ms (ActiveRecord: 7.4ms)

ActiveResource::ResourceNotFound (Failed.  Response code = 404.  Response message = Not Found.):
  app/models/project_services/asana_service.rb:111:in `block in check_commit'
  app/models/project_services/asana_service.rb:110:in `each'
  app/models/project_services/asana_service.rb:110:in `check_commit'
  app/models/project_services/asana_service.rb:93:in `block in execute'
  app/models/project_services/asana_service.rb:92:in `each'
  app/models/project_services/asana_service.rb:92:in `execute'
  app/controllers/projects/services_controller.rb:41:in `test'

Our file can you view here: http://pastebin.com/73CptFyr
Our used version is: gitlab-ce 7.11.4-omnibus

and the API key is valid as far as i know, since the account setup we never changed it, but I will double check it is this can be the reason.

Thanks :)

**Comment by j0k3r** [comment]
Let me know for the token before I plan to dig deeper :)

**Comment by nalilord** [comment]
That's strange, really seems to be related to the API key, I checked it and it is correct, but then I tried my personal one from my account and not the GitLab user account and it works. 

So I guess it is an asana problem. So this is no longer a code problem but maybe do you know what can cause this?

Sorry for the inconvenience, but it seemed to us that something is broken :/

**Comment by j0k3r** [comment]
I've never seen something like that. I've checked my log files too because few days ago the Gitlab user in Asana doesn't have access to a new project. I found no error like you had. Even if it seems to be the same case (user doesn't have access to Asana project).

I've checked my Asana account and it seems they introduce personal token since last time I checked. Are you using this token ? Because the Asana integration use the Api Token (just below the personal token).

Did you try with a different token from someone in your team? Just to be sure it's related to the Gitlab user.

**Comment by nalilord** [comment]
Okay the key is definitely the correct API key not the user token key, I checked it again.

First I thought also it was a rights problem, I added the asana Git user to the task and the project but this changed nothing.

The behavior is really strange, after a commit with an including asana task number it did not comment on the task, I went to services and checked it again, after clicking the test button it added the comments of all commits again.

I only tried it with my API key and the Git users API key but it can try it with another one too.

**Comment by machwatt** [comment]
This night Asana integration stopped working. Tried to figure out why, the access token still works via cmc curl -u api:token: https://app.asana.com/api/1.0/users/me but there are no comments on asana tickets anymore (and no closes). 
Did not found any logs to look into, if there are any connectivity issues.

Asana seems to made a redesign this night (at least it looks new ;) ), hopefully gem version 0.0.6 didnt stop working.

Furthermore:
I saw that API tokens are deprecated and will stop working (https://asana.com/developers/feed/api-key-deprecation), are there any plans on that?

**Comment by j0k3r** [comment]
@machwatt which version of Gitlab are you using? We are still on 7.14.1 and every thing works great.

About Api Key deprecation, it should be interesting to jump on _Personal Access Tokens_ instead.

**Comment by machwatt** [comment]
@j0k3r we set up GitLab last week and are currently running 8.0.2. Everything worked fine until this morning, we did not change anything at first. Tried different API tokens, with different access rights in Asana but nothing seems to work.

Maybe with *Personal Access Tokens* it would be a nice feature to set up a token for every user, so the comments would be "personalized".

**Comment by machwatt** [comment]
@j0k3r Suddenly commits start working again... Not changed anything ... Maybe i can find any reason for that....

**Comment by nalilord** [comment]
Hey Guys,

we updated the version to gitlab 8.0.3 on our server and it seems to work now. Strange... it is!

Regards
Daniel

**Comment by stanhu** [comment]
I'll close this issue for now then. Please re-open if you're still having issues.

**Comment by wzrdtales** [comment]
Ran into the same issue on 8.3.0, currently updating to 8.3.1 and looking if this is fixing it.

**Comment by wzrdtales** [comment]
@stanhu Upgraded to 8.3.1 but it is still broken:

```
2015-12-29T09:49:01.726Z 17996 TID-ovzsj675k WARN: NoMethodError: undefined method `configure' for Asana:Module
2015-12-29T09:49:01.726Z 17996 TID-ovzsj6jqw WARN: NoMethodError: undefined method `configure' for Asana:Module
2015-12-29T09:49:01.727Z 17996 TID-ovzsj1dzo WARN: /home/git/gitlab/app/models/project_services/asana_service.rb:75:in `execute'
/home/git/gitlab/app/workers/project_service_worker.rb:8:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
2015-12-29T09:49:01.727Z 17996 TID-ovzsj57g0 WARN: /home/git/gitlab/app/models/project_services/asana_service.rb:75:in `execute'
/home/git/gitlab/app/workers/project_service_worker.rb:8:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
2015-12-29T09:49:01.728Z 17996 TID-ovzsj5yxg WARN: /home/git/gitlab/app/models/project_services/asana_service.rb:75:in `execute'
/home/git/gitlab/app/workers/project_service_worker.rb:8:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
2015-12-29T09:49:01.728Z 17996 TID-ovzsj675k WARN: /home/git/gitlab/app/models/project_services/asana_service.rb:75:in `execute'
/home/git/gitlab/app/workers/project_service_worker.rb:8:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
2015-12-29T09:49:01.728Z 17996 TID-ovzsj6jqw WARN: /home/git/gitlab/app/models/project_services/asana_service.rb:75:in `execute'
/home/git/gitlab/app/workers/project_service_worker.rb:8:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by wzrdtales** [comment]
Just checked against it, there has nothing changed in app/models/project_services/asana_service.rb for many versions.

**Comment by j0k3r** [comment]
I think it's related to the asana gem update (https://github.com/gitlabhq/gitlabhq/commit/91c0aa5e982ee5e3299e6b8c899bfc396fe51279) which are part for 8.3.x now. I've no idea why @tsigo updated it since the issue related in the commit message doesn't seems to be related to asana at all.

I guess recent update from this gem are related to the comment from @machwatt : https://github.com/gitlabhq/gitlabhq/issues/9637#issuecomment-144316518

The Asana service need to be updated to use _Personal Access Tokens_ instead of _API Keys_

**Comment by wzrdtales** [comment]
Ok,


```
2015-12-29T09:56:24.966Z 21973 TID-os0taguhg WARN: NoMethodError: undefined method `configure' for Asana:Module
2015-12-29T09:56:24.966Z 21973 TID-os0tag5z8 WARN: NoMethodError: undefined method `configure' for Asana:Module
2015-12-29T09:56:24.966Z 21973 TID-os0tag6ck WARN: NoMethodError: undefined method `configure' for Asana:Module
2015-12-29T09:56:24.966Z 21973 TID-os0t7a6ag WARN: NoMethodError: undefined method `configure' for Asana:Module
2015-12-29T09:56:24.966Z 21973 TID-os0t7a5js WARN: /home/git/gitlab/app/models/project_services/asana_service.rb:75:in `execute'
/home/git/gitlab/app/workers/project_service_worker.rb:8:in `perform'
```

This tells that there is no such method configure in Asana executed from here:

```
    Asana.configure do |client|
      client.api_key = api_key
    end
```
But this method should come from the inheritance Service, it seems that here something wents terribly wrong.

**Comment by wzrdtales** [comment]
@j0k3r Ok I will give this a try

**Comment by wzrdtales** [comment]
@j0k3r unfortunately, this does not change anything

**Comment by j0k3r** [comment]
@wzrdtales Did you update the Asana service too?
Because, with the new version the current code doesn't work (and it give the error you have).

You have to do (from [the Asana gem README](https://github.com/asana/ruby-asana#personal-access-token)):

```ruby
Asana::Client.new do |c|
  c.authentication :access_token, 'personal_access_token'
end
```

**Comment by wzrdtales** [comment]
No I did not yet, trying this next.

**Comment by wzrdtales** [comment]
That seems to need a greater rework...

Now it runs into:

```
2015-12-29T10:23:34.929Z 32431 TID-ow3wb5eb8 WARN: NoMethodError: undefined method `find' for Asana::Resources::Task:Class
```

I guess that for this service do not exist any tests?

**Comment by j0k3r** [comment]
When I've added this service, I also added some tests:

https://github.com/gitlabhq/gitlabhq/blob/master/spec/models/project_services/asana_service_spec.rb

**Comment by wzrdtales** [comment]
Yeah but unfortunately It does not seem like they would have failed through this breaking change.
Thank you for your help so far btw.

**Comment by j0k3r** [comment]
I think the whole Asana service should be updated, not only changing lines for the authentication.
Also, we'll need to inform user that the service has been updated and that they need to update each service on their Gitlab instance with the new personal token.

**Comment by wzrdtales** [comment]
@j0k3r Yes this is true, should be part of the upgrade guide.

**Comment by wzrdtales** [comment]
Ok, tried to just downgrade the asana lib and this fails with:

```
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- active_resource (LoadError)
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/asana-0.0.6/lib/asana.rb:1:in `<top (required)>'
```

May be this is the reason for the update...
With this gitlab 8.3.x is completely broken for me now...

**Comment by wzrdtales** [comment]
Ok, have taken a bit time as we really need that module and checked which methods have changed in which way, this is the current patch:

```
diff --git a/app/models/project_services/asana_service.rb b/app/models/project_services/asana_service.rb
index e6e1605..e3c55d5 100644
--- a/app/models/project_services/asana_service.rb
+++ b/app/models/project_services/asana_service.rb
@@ -72,8 +72,8 @@ automatically inspected. Leave blank to include all branches.'
   def execute(data)
     return unless supported_events.include?(data[:object_kind])
 
-    Asana.configure do |client|
-      client.api_key = api_key
+    $_asana = Asana::Client.new do |c|
+      c.authentication :access_token, api_key
     end
 
     user = data[:user_name]
@@ -108,19 +108,19 @@ automatically inspected. Leave blank to include all branches.'
 
     # post commit to every taskid found
     task_list.each do |taskid|
-      task = Asana::Task.find(taskid[0])
+      task = $_asana.tasks.find_by_id(taskid[0])
 
       if task
-        task.create_story(text: push_msg + ' ' + message)
+        task.add_comment(text: push_msg + ' ' + message)
       end
     end
 
     # close all tasks that had 'fix(ed/es/ing) #:id' in them
     close_list.each do |taskid|
-      task = Asana::Task.find(taskid.last)
+      task = $_asana.tasks.find_by_id(taskid.last)
 
       if task
-        task.modify(completed: true)
+        task.update(completed: true)
       end
     end
   end
```

This needs of course an upgrade to the new keys

**Comment by j0k3r** [comment]
@wzrdtales you should submit a PR :)

**Comment by wzrdtales** [comment]
@j0k3r Will do later.

**Comment by stanhu** [comment]
@tsigo Perhaps we should rollback 21003c0cb2 for 8.3.x and aim for the upgrade in 8.4?

**Comment by wzrdtales** [comment]
@j0k3r @stanhu PR open at https://github.com/gitlabhq/gitlabhq/pull/9937 also it currently fails the CI, but as stated in the PR itself, I'm not going to go into this any further as the actual error does not seem to make sense.

The rest is up to you guys.

**Comment by stanhu** [comment]
Asana fix was merged in 8de1f715 and will be shipping in GitLab 8.3.3 soon. Thanks for your patience!

**Comment by stanhu** [comment]
FYI, GitLab 8.3.3 was released today and GitLab.com and has been updated:

https://about.gitlab.com/2016/01/11/gitlab-8-dot-3-dot-3-released/

**Comment by wzrdtales** [comment]
Yes thank you!
