### ISSUE TITLE
secrets.yml missing

### ISSUE THREAD

**Issue by ykram** [gitlabhq/gitlabhq#9641]
The documentation for upgrading from 7.14 to 8.0 stable (https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/7.14-to-8.0.md) states in section 6 to copy the secrets.yml:

> sudo -u git -H cp config/secrets.yml.example config/secrets.yml
> sudo -u git -H chmod 0600 config/secrets.yml

However, the 'secrets.yml.example' file doesn't exist in the repo.

**Comment by hebbet** [comment]
it is available on branch 8-0-stable at least. are you on that branch?

https://github.com/gitlabhq/gitlabhq/blob/8-0-stable/config/secrets.yml.example

**Comment by ykram** [comment]
I swear I'm not making it but it wasn't there when I checked it out. Sorry about the erroneous bug report :(
