### ISSUE TITLE
MergeRequestsController thrown a Error 500 when you delete the assiociated milestone

### ISSUE THREAD

**Issue by ArKam** [gitlabhq/gitlabhq#9643]
Hi team, I've just detected a quite strange behavior on my current installation of GitLab.

Is that normal that if you delete a milestone attached to a list of merge requests the complete view goes on the ERROR 500 Realm?

I mean, don't gitlab should either deny any remove of the milestone if there is some items still attached to?

For now, if I go to my merge_requests view, I've got a Error 500 with the following message showing on the production.log file:

https://gist.github.com/ArKam/339ab337c075f855a6ff

Is there a workaround to find out what was the removed milestone ID/Title and then reinject it on the database?

**Comment by stanhu** [comment]
Thanks for reporting this. This is a bug in the milestone removal, and I've submitted [a fix](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1348). 

The way to recover from this would be to remove the `milestone_id` field from this specific merge request in the database. I  think you can figure this out by doing a SELECT in the database. For example:

```
$ sudo -u gitlab-psql psql -h /var/opt/gitlab/postgresql -d gitlabhq_production
psql (9.3.5, server 9.2.10)
Type "help" for help.

gitlabhq_production-# SELECT * FROM merge_requests where milestone_id NOT IN (SELECT id FROM merge_requests)
```

Then I would use UPDATE to set the `milestone_id` to `NULL` for the matching merge requests. Sorry for the trouble.

**Comment by stanhu** [comment]
I've also submitted a migration to clean up the database of any dangling milestones:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1350

**Comment by ArKam** [comment]
@stanhu All right that perfect!!! Thanks a lot!
