### ISSUE TITLE
Gitlab v8.0.0.rc1 https pull/clone/... fails

### ISSUE THREAD

**Issue by P-EB** [gitlabhq/gitlabhq#9647]
Hey,

I recently upgraded to gitlab v8.0.0rc1, and since then, HTTPS pull/clone/push/... fail.

As for an example, I've got a script project which is public on my gitlab
```
.-(16:57:29)-(/usr/scripts)----------------(git)-[scripts/master]-(becue@zamok)-
`---> git pull
Username for 'https://gitlab.xxxxxx': becue
Password for 'https://becue@gitlab.xxxxxx': 
Your configuration specifies to merge with the ref 'master'
from the remote, but no such ref was fetched.
```

With ssh, it works like a charm

```
.-(16:57:46)-(/usr/scripts)----------------(git)-[scripts/master]-(becue@zamok)-
`--[1]-> git pull gitlab master
Depuis gitlab.xxxxxx:xxxxxx/scripts
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

It does that on two gitlab installs I've got. When I make a git clone, it prompts for my login/password and says that I've cloned an empty repo.

Did some git update-server-info, but didn't change anything.

Should I look to some specific place? Is this bug known? Is this really a bug?

**Comment by axilleas** [comment]
With GitLab 8.0, for http requests you have to install gitlab-git-http-server as stated in the installation guide

* step one: https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/installation.md#3-go
* step two: https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/installation.md#install-gitlab-git-http-server

Also make sure you pick the latest nginx config.

**Comment by P-EB** [comment]
I can confirm there was nothing about this in the update guide.

Why did you make such a change? Having to install go and yet another program seems a bit surprising regarding the fact that http pull/push was working well before.

**Comment by axilleas** [comment]
It was a decision made by the devs. You can read why in this blog post https://about.gitlab.com/2015/08/22/gitlab-7-14-released/
