### ISSUE TITLE
Error msg when I push

### ISSUE THREAD

**Issue by JoseNondi** [gitlabhq/gitlabhq#9648]
Hi,

I'm getting this failure error msg when I'm trying to push new commits.

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/dushoff/TZ_clinics.git/'

Pushing to https://github.com/dushoff/TZ_clinics.git

Completed with errors, see above.

Help please.

Joseph.

**Comment by axilleas** [comment]
Hello!

Please follow my comment and the discussion in https://github.com/gitlabhq/gitlabhq/issues/9647#issuecomment-141797019
