### ISSUE TITLE
upgrading from 8.0.0.rc2 to 8.0.1 failed on RPI2

### ISSUE THREAD

**Issue by yangxuan8282** [gitlabhq/gitlabhq#9659]
The following packages will be upgraded:
      gitlab-ce
    1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Need to get 337 MB of archives.
    After this operation, 124 kB of additional disk space will be used.
    Do you want to continue [Y/n]? y
    Get:1 https://packages.gitlab.com/gitlab/raspberry-pi2/debian/ wheezy/main gitlab-ce armhf 8.0.1+20150922172700-ce.0 [337 MB]
    Fetched 337 MB in 28min 31s (197 kB/s)
    (Reading database ... 84797 files and directories currently installed.)
    Preparing to replace gitlab-ce 8.0.0+20150921073557-rc2.ce.1 (using .../gitlab-ce_8.0.1+20150922172700-ce.0_armhf.deb) ...
    gitlab preinstall: Backing up GitLab SQL database (excluding Git repositories, uploads)
    Dumping database ...
    rake aborted!
    Errno::EACCES: Permission denied @ dir_s_mkdir - /var/opt/gitlab/ci-backups
    /opt/gitlab/embedded/service/gitlab-rails/lib/backup/database.rb:15:in `dump'
    /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:66:in `block (4 levels) in <top (required)>'
    /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:11:in `block (3 levels) in <top (required)>'
    Tasks: TOP => gitlab:backup:db:create
    (See full trace by running task with --trace)
    gitlab preinstall:
    gitlab preinstall: Backup failed! If you want to skip this backup, run the following command and
    gitlab preinstall: try again:
    gitlab preinstall:
    gitlab preinstall:   sudo touch /etc/gitlab/skip-auto-migrations
    gitlab preinstall:
    dpkg: error processing /var/cache/apt/archives/gitlab-ce_8.0.1+20150922172700-ce.0_armhf.deb (--unpack):
     subprocess new pre-installation script returned error exit status 1
    gitlab: Thank you for installing GitLab!
    gitlab: To configure and start GitLab, RUN THE FOLLOWING COMMAND:
    
    sudo gitlab-ctl reconfigure
    
    gitlab: GitLab should be reachable at http://raspberrypi
    gitlab: Otherwise configure GitLab for your system by editing /etc/gitlab/gitlab.rb file
    gitlab: And running reconfigure again.
    gitlab:
    gitlab: For a comprehensive list of configuration options please see the Omnibus GitLab readme
    gitlab: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md
    gitlab:
    Errors were encountered while processing:
     /var/cache/apt/archives/gitlab-ce_8.0.1+20150922172700-ce.0_armhf.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by stanhu** [comment]
Somehow the permissions are wrong. Who owns `/var/opt/gitlab/ci-backups`? In my installation, `gitlab-ci` appears to own that. Is the script run as a different user?

@maxlazio, any ideas if this is a RPI2-specific issue or something that's seen in other omnibus installations?

**Comment by yangxuan8282** [comment]
@stanhu  same user

**Comment by maxlazio** [comment]
@stanhu Thanks for pinging me. There is no reason for this to be RPI2 specific. 

I think this was a bug that emerged after release and caused few subsequent fixes in omnibus-gitlab.
@yangxuan8282 Do you have CI running too? Maybe you can relax the permissions on ci-backups directory until you upgrade to 8.0.2

**Comment by yangxuan8282** [comment]
@maxlazio what do you mean by 'Do you have CI running too?' Continuous Integration?
I just have one Gitlab installed
and below is what happen when I am trying to upgrade to 8.0.2

    Do you want to continue [Y/n]? y
    Get:1 https://packages.gitlab.com/gitlab/raspberry-pi2/debian/ wheezy/main gitlab-ce armhf 8.0.2+20150925225808-ce.1 [337 MB]
    Fetched 337 MB in 43min 37s (129 kB/s)
    (Reading database ... 84797 files and directories currently installed.)
    Preparing to replace gitlab-ce 8.0.0+20150921073557-rc2.ce.1 (using .../gitlab-ce_8.0.2+20150925225808-ce.1_armhf.deb) ...
    gitlab preinstall: Backing up GitLab SQL database (excluding Git repositories, uploads)
    Dumping database ...
    rake aborted!
    Errno::EACCES: Permission denied @ dir_s_mkdir - /var/opt/gitlab/ci-backups
    /opt/gitlab/embedded/service/gitlab-rails/lib/backup/database.rb:15:in `dump'
    /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:66:in `block (4 levels) in <top (required)>'
    /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:11:in `block (3 levels) in <top (required)>'
    Tasks: TOP => gitlab:backup:db:create
    (See full trace by running task with --trace)
    gitlab preinstall:
    gitlab preinstall: Backup failed! If you want to skip this backup, run the following command and
    gitlab preinstall: try again:
    gitlab preinstall:
    gitlab preinstall:   sudo touch /etc/gitlab/skip-auto-migrations
    gitlab preinstall:
    dpkg: error processing /var/cache/apt/archives/gitlab-ce_8.0.2+20150925225808-ce.1_armhf.deb (--unpack):
     subprocess new pre-installation script returned error exit status 1
    gitlab: Thank you for installing GitLab!
    gitlab: To configure and start GitLab, RUN THE FOLLOWING COMMAND:
    
    sudo gitlab-ctl reconfigure
    
    gitlab: GitLab should be reachable at http://raspberrypi
    gitlab: Otherwise configure GitLab for your system by editing /etc/gitlab/gitlab.rb file
    gitlab: And running reconfigure again.
    gitlab:
    gitlab: For a comprehensive list of configuration options please see the Omnibus GitLab readme
    gitlab: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md
    gitlab:
    Errors were encountered while processing:
     /var/cache/apt/archives/gitlab-ce_8.0.2+20150925225808-ce.1_armhf.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by maxlazio** [comment]
@yangxuan8282 Yes, I asked if you have GitLab CI running too but I will assume that you don't according to your answer.
In this case there are two options:

1. Skip the backup  with "sudo touch /etc/gitlab/skip-auto-migrations", install the new package and then remove the skip file "sudo rm /etc/gitlab/skip-auto-migrations"
2. Just create the directory and make sure it is owned by the correct user:
```
sudo mkdir -p /var/opt/gitlab/ci-backups
sudo chown git:git /var/opt/gitlab/ci-backups
````
and then install the package

I would advise you to do the second option.

**Comment by yangxuan8282** [comment]
it works
thanks
