### ISSUE TITLE
[Bug] Refs Not Found

### ISSUE THREAD

**Issue by vinkla** [gitlabhq/gitlabhq#9662]
After upgrading to 8.0 yesterday we are not able to perform clone with HTTP. It returns the following message:
```bash
fatal: http://example.com/group/project.git/info/refs not found: did you run git update-server-info on the server?
```
We have installed GitLab from source and are still updating as in the `docs` directory.

**Comment by stanhu** [comment]
Sounds like you may need to install gitlab-git-http-server:

http://doc.gitlab.com/ce/install/installation.html#install-gitlab-git-http-server

**Comment by vinkla** [comment]
We already installed it as in the documentation. All tests turned green after the upgrade.

**Comment by vinkla** [comment]
We solved it, the path was wrong to the repositories. Thanks anyway!
