### ISSUE TITLE
git push failing via http with error 22 - gitlab 8.0

### ISSUE THREAD

**Issue by dfduarte** [gitlabhq/gitlabhq#9663]
Good Morning,

Yesterday, we've installed the Gitlab 8.0 within a server of mine here. I've used the Chef Cookbook from AtomicPenguins, and I've changed the git_branch for 8-0-stable.

Everything is working as expected, including the commit/push throught SSH. However, the commit via http is not work properly, and returns the following error: 

Password for 'http://dfduarte@ec2-54-233-89-237.sa-east-1.compute.amazonaws.com:8090': 
error: Cannot access URL http://ec2-54-233-89-237.sa-east-1.compute.amazonaws.com:8090/dfduarte/projecthttp.git/, return code 22
fatal: git-http-push failed

The "production.log", shows the following error output:

Completed 200 OK in 363ms (Views: 317.2ms | ActiveRecord: 7.1ms)
Started GET "/dfduarte/projecthttp.git/info/refs?service=git-receive-pack" for 177.69.196.17 at 2015-09-23 13:26:15 -0300
Started GET "/dfduarte/projecthttp.git/info/refs?service=git-receive-pack" for 177.69.196.17 at 2015-09-23 13:26:19 -0300
Started GET "/dfduarte/projecthttp.git/info/refs?service=git-receive-pack" for 177.69.196.17 at 2015-09-23 13:26:19 -0300
Started GET "/dfduarte/projecthttp.git/info/refs?service=git-receive-pack" for 177.69.196.17 at 2015-09-23 13:26:21 -0300
Started GET "/dfduarte/projecthttp.git/info/refs?service=git-receive-pack" for 177.69.196.17 at 2015-09-23 13:26:25 -0300
Started GET "/dfduarte/projecthttp.git/info/refs?service=git-receive-pack" for 177.69.196.17 at 2015-09-23 13:26:28 -0300
Started GET "/dfduarte/projecthttp.git/info/refs?service=git-receive-pack" for 177.69.196.17 at 2015-09-23 13:26:28 -0300
Started GET "/dfduarte/projecthttp.git/HEAD" for 177.69.196.17 at 2015-09-23 13:26:28 -0300
Started PROPFIND "/dfduarte/projecthttp.git/" for 177.69.196.17 at 2015-09-23 13:26:28 -0300

ActionController::RoutingError (No route matches [PROPFIND] "/dfduarte/projecthttp.git"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/request_store-1.2.0/lib/request_store/middleware.rb:8:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
<and someelse more errors>

What we're doing wrong here? Or there is a chance this can be a bug?

Doing some search on Google, I found that the propfind error is related to webdav, but I don't have this error on version 7 of Gitlab with the current Nginx configuration.

**Comment by stanhu** [comment]
It looks like the git HTTP request is being routed to the GitLab Rails controller instead of gitlab-git-http-server, which was just introduced in 8.0. You may want to check your nginx config has this block and other lines relating to gitlab-git-http-server:

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/support/nginx/gitlab#L116

**Comment by hersche** [comment]
i've got the same issue in my system, but it was solveable for me, thanks to stanhu's comment. my system is ubuntu 14.04 with omnibus-package. my steps to solve:
1. apt-get install runit
2. /opt/gitlab/service/gitlab-git-http-server/run & # temporary command, not shure if it would autostart with runit
3. the nginx-config from stanhu, but the socketline would be 

server unix:/var/opt/gitlab/gitlab-git-http-server/socket fail_timeout=0;
@ https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/support/nginx/gitlab#L42

now it seems to work fine again.. thx for the report!

**Comment by dfduarte** [comment]
Thanks guys.

I'm closing the issue by myself, since it's not a GitLab problem, itself...
