### ISSUE TITLE
Using Jira for issues, can't close Gitlab MR with commit

### ISSUE THREAD

**Issue by eddiemonge** [gitlabhq/gitlabhq#9666]
We are using Jira for our issue tracker and have Gitlab setup to use that. When we try to close a merge request from a commit message, it doesn't work.

Tried `Closes #122321` and `Closes !122321`. Is that the proper syntax?

**Comment by stanhu** [comment]
I thought the JIRA syntax included the project name, e.g. `Closes MYPROJECT-1`.

**Comment by eddiemonge** [comment]
It does. When I go to the commit, and then click the issue number it takes me to Jira. I get a 404 though since it tries to take me somewhere random.

**Comment by stanhu** [comment]
Have you configured the `Issues URL` setting in the JIRA service properly to take you to the right project?

**Comment by eddiemonge** [comment]
Yes but that is not the issue. The issue is I can't close gitlab merge requests from the commit message anymore.

**Comment by stanhu** [comment]
Oh, I wonder if this is a regression in GitLab EE. In EE,`close_service.rb` has special JIRA handling for issues but not merge requests. Perhaps it would be a good idea to file this with GitLab EE support?

**Comment by eddiemonge** [comment]
We are using CE. Would the change have trickled into there?

**Comment by stanhu** [comment]
I'm confused; JIRA support is only offered in EE. Are you using the GitLab internal issue tracker?

**Comment by eddiemonge** [comment]
No. We have Jira enabled through the Project Services tab.

**Comment by stanhu** [comment]
Oh, right, I didn't realize CE came with the ability to configure JIRA as an issue tracker.

Did closing MRs from a JIRA Issue ever work in CE? As far as I know, closing issues from JIRA is an EE-only issue:

```
Support for referencing commits and automatic closing of Jira issues directly from GitLab is available in GitLab EE.
```

**Comment by eddiemonge** [comment]
No idea. Im trying to close MRs from a commit, not from Jira.

**Comment by jtheoof** [comment]
Closing JIRA issues from commits has never worked with Gitlab CE. At least not for us ;) But linking JIRAs works. So we can at least navigate from gitlab to JIRA when referencing issues.

**Comment by eddiemonge** [comment]
Again, missing the point. Let me try a different way.

I have my gitlab repo linked to Jira. Meaning, 
 * Clicking the Issues link in the project opens Jira
 * Jira cannot close gitlab issues or commits and gitlab cannot close Jira issues. They are not integrated like that at all. Clicking an issue number in a Merge Request or commit will take the user to the Jira issue
 * I commit some code and make a Merge Request. The MR ticket number is 122321. It looks and works exactly like it is supposed to.
 * I make a new commit and add `Closes #122321` in the message. I push that up and somehow it gets in to the default branch for the project (in a Merge Request or pushing directly to the default branch).

If Jira was not a part of this at all, that commit would close that 122321 Merge Request because of the commit message. However, this is not what is happening. What is currently happening is nothing. The Merge Request does not get closed.

**Comment by jtheoof** [comment]
_The MR ticket number is 122321_... What does this mean? Is `122321` a JIRA ticket or the MR id?

**Comment by eddiemonge** [comment]
Stop thinking that there is a Jira ticket involved. The only way Jira is involved is that I turned on the Jira service hook. Other than that, it is not involved at all. That is the id of the new Merge Request.

**Comment by jtheoof** [comment]
Weird attitude... Just trying to help. You seem to have something wrong in your flow. So what you create some commits create a MR and then when your team is happy you add one last commit that will close that MR?? This does not make sense. The simple fact that someone will close that MR to merge the code to the central repo will by definition close that MR. What's the point of having an extra commit to do that?

**Comment by eddiemonge** [comment]
Its not a weird attitude, I'm trying to keep the ticket focused since some people aren't seeing the exact issue I'm having so I'm trying to keep that clear.

Doesn't really matter what the use case is when its a bug to begin with. I'll give you two use cases for this though:

1. A person did some changes, did a merge request. There were some problems with the commit message, the commits themselves, a small typo, basically anything that needs to be fixed. Instead of requiring that person to fix the changes themselves and force push to clean up the commit, the person reviewing/merging the code decides to do it for them. They pull locally, fix the changes and then merge that fixed version to master and push it up. They mention in the commit to close the merge request. It saved having to go back to the merge request and close it manually.

2. Someone does a merge request. Someone else does a similar merge request and puts a close message in the commit to close that first one. If the second one is then merged, the first should get closed because of that message.

**Comment by jvanbaarsen** [comment]
@eddiemonge JIRA Support is now also included in CE, should work for you now!
