### ISSUE TITLE
gitlab installation final config check complains on gitlab-shell

### ISSUE THREAD

**Issue by hsafe** [gitlabhq/gitlabhq#9667]
Hi
I am trying to follow the instruction in:
https://github.com/gitlabhq/gitlab-recipes/blob/0cfe5c98bd41fe6f2cbf73cc7f583eeb973e98f0/install/centos/README.md
to install gitlab on a centos6.7 bare VM. Am pretty sure that all the configs are thoroughly followed and correct. However at the last stage and running the test by:
$ sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
The error  is here:
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: /home/git/gitlab-shell/lib/gitlab_net.rb:122:in `read': No such file or directory @ rb_sysopen - /home/git/gitlab-shell/.gitlab_shell_secret (Errno::ENOENT)
	from /home/git/gitlab-shell/lib/gitlab_net.rb:122:in `secret_token'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:79:in `get'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:39:in `check'
	from /home/git/gitlab-shell/bin/check:11:in `<main>'
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /home/git/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.

How could I fix this? Can you please help? Thanks
P/S I pretty much followed line by line of the recipe

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
