### ISSUE TITLE
Option to choose default view when logging in

### ISSUE THREAD

**Issue by jacargentina** [gitlabhq/gitlabhq#9678]
In my team we loved the default dashboard where you can see all latest reported issues, commits, etc.

Now the default is a list of project, which for us, is always the same (not very useful).

May be there is some way to make the old "all activity dashboard" the default again, and i cant find it? Or really there is no way, and i hope somebody would realize the mistake on doing this change (or at least not providing the option to choose which is the default)

**Comment by jacargentina** [comment]
Mmmm, sorry for not looking at latest code: i think v8.1.0 would have this option?

**Comment by stanhu** [comment]
Yes, this should be available in 8.1 via ac34ce8648f.
