### ISSUE TITLE
Upgrade to 8-0-stable Error

### ISSUE THREAD

**Issue by cnzx219** [gitlabhq/gitlabhq#9680]
Now It has not upgrade script in doc/update.
I upgrade my gitlab from 7.14.3 to 8.0. 

It always show 'empty repo...' when i clone repo via https.
Browser always show '403 forbidden' . the address is like this 'https://xxx.example.cn/hiro/test.git'.

Something wrong config when i upgrade?

**Comment by Armstrong1992** [comment]
Apache or Nginx? 

See: https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/7.14-to-8.0.md#new-nginx-configuration or https://github.com/gitlabhq/gitlab-recipes/tree/master/web-server/apache

**Comment by cnzx219** [comment]
Great!

i use nginx. i'll try it right now.

thx!

**Comment by cnzx219** [comment]
Resolved~ 

thx very much
