### ISSUE TITLE
Disabling "Edit comment" option

### ISSUE THREAD

**Issue by matm** [gitlabhq/gitlabhq#9681]
When writing issue comments, it is possible to edit a comment afterwards, which may be annoying sometimes. A comment describing some specs can be updated anytime, no comment history is available.

Is there a simple way to disable this "Edit comment" option (system-wide, project-wide)?

**Comment by stanhu** [comment]
Unfortunately, there isn't a way at the moment. I think it's doubtful that there will be anytime soon. Perhaps a  comment history feature may be supported down the road.

**Comment by FlippieCoetser** [comment]
Is there a way to limit changes to commit by the author of the comment only. We see from time to time changes being made to previous comments which obviously impacts the history of the issues and discussion around it.

**Comment by daira** [comment]
This is a serious concern for security-focused projects (e.g. https://github.com/zcash/zcash). We're quite unhappy about the unreliability of comments in providing an audit trail of how security decisions were made, or what review was done on code that might be found to be vulnerable.

**Comment by FlippieCoetser** [comment]
It would be awesome when the author of a comment has a couple of min to edit his/her comment before locking the comment forever... Many platforms take this approach... By doing so you can use Github comments as a full audit record.

**Comment by luca-nardelli** [comment]
Came here from a google search. I completely agree, it would be a very interesting feature for a project that needs an audit trail

**Comment by matm** [comment]
Yes, that feature is really needed! Could be enabled per project by admin.

/cc @stanhu

**Comment by savy-91** [comment]
This would be extremely helpful for medical devices project as well!

**Comment by ZJvandeWeg** [comment]
We don't use this issue tracker anymore, feature requests over at the [gitlab-ce](https://gitlab.com/gitlab-org/gitlab-ce/issues/new) projects are considered. I would propose opening an issue there.
