### ISSUE TITLE
MR is associated with SHA ID but not to branch name

### ISSUE THREAD

**Issue by fmvin** [gitlabhq/gitlabhq#9682]
After upgrading to 8.0 MR become to work in different way than 7.x.
In 7.x version if MR has been created to a branch and later commit was amended and repushed on server (really created new commit with new SHA ID) the MR accepted on the commit which marked with this branch (it means repushed commit).
But in 8.0 MR always accepted on commit created first. It doesn't matter if branch points to another commit (amended, for example). 
Moreover, if I do merge manually in this case the MR stays in open state.

**Comment by stanhu** [comment]
This seems to work for me. Can you replicate this issue on gitlab.com?

This may not be working if for some reason the Git hooks are not running. Can you run `sudo gitlab-rake gitlab:check` (if you're using the omnibus version)?

**Comment by fmvin** [comment]
[This issue on gitlab](https://gitlab.com/gitlab-org/gitlab-ce/issues/2926)

**Comment by stanhu** [comment]
Actually, I meant if you push new commits to a repository on GitLab.com, do you see the same issue described?

**Comment by stanhu** [comment]
Closing this discussion in favor of the one in GitLab.com.
