### ISSUE TITLE
can't clone repo via https after upgrade 8.0

### ISSUE THREAD

**Issue by cnzx219** [gitlabhq/gitlabhq#9686]
i clone my repo via https, like this `https://code.xxx.cn/cnzx219/test`.It always show the following error:

```
Cloning into 'xxx'...
remote: Not Found
fatal: repository 'https://code.xxx.cn/g_xxx/xxx.git/' not found
```

nginx access log:

```
121.40.87.95 - cnzx219 [02/Oct/2015:05:19:46 +0800] "GET /g_xxx/xxx.git/info/refs?service=git-upload-pack HTTP/1.1" 404 10 "-" "JGit/unknown"
```

finnally, i found the gitlab-git-http-server startup script:

```
$ ps -ax | grep gitlab
 1532 ?        Ssl    0:00 /home/git/gitlab/../gitlab-git-http-server/gitlab-git-http-server -listenUmask 0 -listenNetwork unix -listenAddr /home/git/gitlab/tmp/sockets/gitlab-git-http-server.socket -authBackend http://127.0.0.1:8080 /home/git/repositories
```

gitlab-git-http-server read the repo path which is `/home/git/repositories`. 

but in my `gitlab.yml` it is `repos_path: /my/git/repositories/`

i have use soft link to resolve. hope that it will be fix in next version

**Comment by jerbob92** [comment]
You can configure the repositories path for the http server in ```/etc/default/gitlab```, change the value of ```gitlab_git_http_server_repo_root```

**Comment by cnzx219** [comment]
@jerbob92  this value is in `/etc/init.d/gitlab`

i use ubuntu

**Comment by jerbob92** [comment]
I use Ubuntu too, installed from source though, might be different in omnibus.

**Comment by jerbob92** [comment]
@cnzx219 
Just checked, the /etc/init.d/gitlab is the startup file, it has some defaults, but after the defaults it executes the following:
```
# Read configuration variable file if it is present
test -f /etc/default/gitlab && . /etc/default/gitlab
```

I'd edit ```/etc/default/gitlab``` to prevent my changes being overwritten on upgrade.
If you don't have ```/etc/default/gitlab```, you can copy it from ```lib/support/init.d/gitlab.default.example```

**Comment by joshuaspence** [comment]
I am also seeing this issue.

**Comment by danielksan81** [comment]
Same here...

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
