### ISSUE TITLE
User account creation reset token sent by email expires immediately. 

### ISSUE THREAD

**Issue by edouard-lopez** [gitlabhq/gitlabhq#9687]
> When I create a new user, the reset token expires immediately showing "Your password reset token has expired.", after redirecting to http://g.apertron.net/users/password/new?user_email=
>
> Thanks!

cross-report from [GitLab Community Edition # 2750](https://gitlab.com/gitlab-org/gitlab-ce/issues/2750).

**Comment by stanhu** [comment]
I'm going to close this in favor of the discussion in GitLab.com. Thanks!
