### ISSUE TITLE
Changing namespace results in bad links from Commits page

### ISSUE THREAD

**Issue by XenoPhage** [gitlabhq/gitlabhq#9689]
I changed the namespace of a project earlier today, moving it from one group to another.  After the move it appears that the links in the Commits section still reference the original namespace.  Other areas such as the Network page will properly point to the new namespace.

Gitlab CE Omnibus 8.0.3, CentOS 6.x

**Comment by stanhu** [comment]
See:

* https://gitlab.com/gitlab-org/gitlab-ce/issues/88 
* https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1498

Feel free to comment.

**Comment by stanhu** [comment]
Actually, I got confused with a different issue. You can work around the issue by running `sudo gitlab-rake cache:clear`. The fix is here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1497

**Comment by XenoPhage** [comment]
Sweet, the cache:clear worked wonderfully.  Thanks!
