### ISSUE TITLE
gitlab api for products pagination returns items multiple times and not always returns 10 items at once

### ISSUE THREAD

**Issue by do3cc** [gitlabhq/gitlabhq#9694]
Hi,

we sorely miss cc.xml support in gitlab so we wrote a script to generate it via the api.
After the upgrade to 8.0 we only get back ten results. I suspected that you might have added pagination and indeed, adding my pagination support code to query projects returned more results.
But now the second page (page=1) returns the same 10 results. Further page queries return more results, but now not always ten items per page.
I played with the order_by parameter, now I order by id and the page results are ordered but over all pages the results seem to be random

**Comment by do3cc** [comment]
cc @saily

**Comment by saily** [comment]
You have to put this bug-report to gitlab issue tracker.
https://gitlab.com/gitlab-org/gitlab-ce/issues

**Comment by do3cc** [comment]
I did not read the guidelines :-(
Here is the issue in gitlab, I close this one.
https://gitlab.com/gitlab-org/gitlab-ce/issues/2933
