### ISSUE TITLE
Make unicorn optional

### ISSUE THREAD

**Issue by func0der** [gitlabhq/gitlabhq#9698]
Hey there,
since there are a lot of possible alternatives out there to host the web site to Gitlab (Apache, nginx and what not) making Unicorn an optional asset to Gitlab would be a really good idea.

Especially the init script should be freed from unicorn related stuff. So the file stays update compatible. Right now you have to remove all unicorn related stuff from there to use it properly.
Maybe we could integrate webserver specific defaults which are then loaded from `/etc/defaults/gitlab`

What do you think about it?

func0der

**Comment by jvanbaarsen** [comment]
We currently have no plans in supporting such feature.

**Comment by func0der** [comment]
Why not?
This is not something impossible to do, but something that helps a lot of people who do not want dozens of different web servers running on their system, because each and every one of them could be a possible security breach.

If you do not want to support other web servers right now, could you at least separate unicorn by wrapping it in a script that is called from the init script so that it is easier to disable?
