### ISSUE TITLE
undefined method `namespace' for nil:NilClass

### ISSUE THREAD

**Issue by KittBlog** [gitlabhq/gitlabhq#9700]
As soon as I want to open the notification area in my profile settings I get a 500 server error and the following error message in the `production.log`:
```
Started GET "/profile/notifications" for 79.209.197.185 at 2015-10-06 19:44:37 +0200
Processing by Profiles::NotificationsController#show as HTML
Completed 500 Internal Server Error in 81ms (ActiveRecord: 3.7ms)

ActionView::Template::Error (undefined method `namespace' for nil:NilClass):
     9:     - if membership.kind_of? GroupMember
    10:       = link_to membership.group.name, membership.group
    11:     - else
    12:       = link_to_project(membership.project)
    13:   .pull-right
    14:     = form_tag profile_notifications_path, method: :put, remote: true, class: 'update-notifications' do
    15:       = hidden_field_tag :notification_type, type, id: dom_id(membership, 'notification_type')
  app/helpers/projects_helper.rb:11:in `link_to_project'
  app/views/profiles/notifications/_settings.html.haml:12:in `_app_views_profiles_notifications__settings_html_haml___1632414390763284649_69823403984940'
  app/views/profiles/notifications/show.html.haml:79:in `block in _app_views_profiles_notifications_show_html_haml___2873072603207954877_69823404655400'
  app/views/profiles/notifications/show.html.haml:77:in `_app_views_profiles_notifications_show_html_haml___2873072603207954877_69823404655400'
```

I already checked the database, especially the namespaces to projects references and they seem to be fine.

Does anyone know what happened here and how to resolve this issue?

System information:
Debian Jessie
Latest 8.0.x release
Installed from source

**Comment by oelmekki** [comment]
I have the same problem using gitlab-ce_8.3.0-ce.0_amd64.deb, installed 
using dpkg. Same backtrace.

Let me know if I can provide any more information.

**Comment by aegiap** [comment]
I have also have this exact backtrace when I click on the profile notification config : */profile/notifications*.
Setup is using the 8.6.1-ce installed with deb package.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
