### ISSUE TITLE
Update to 8.0.4 fail on Debian 8

### ISSUE THREAD

**Issue by valentin2105** [gitlabhq/gitlabhq#9701]
Hi !

I use GitLab with Omnibus Packages on Debian 8,

All my precedents update works fines, but the last (from  8.0.3 to  8.0.4) fail,

I give you some output :

```
down: postgresql: 1s, normally up, want up; run: log: (pid 413) 499679s
down: postgresql: 1s, normally up, want up; run: log: (pid 413) 499680s
down: postgresql: 1s, normally up, want up; run: log: (pid 413) 499681s


Failed to start postgresql for migrations
dpkg: error processing package gitlab-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 gitlab-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Thanks a lot for Gitlab, I wait on 8.0.3 ;)

=)

**Comment by stanhu** [comment]
PostgreSQL is not starting for some reason. Do you see any errors in `/var/log/gitlab/postgresql/current`?

**Comment by valentin2105** [comment]
Thanks a lot, no enough disk's space (300M..).
Sorry, can I close it ?
