### ISSUE TITLE
LDAP Authentication failures in 8.0.4

### ISSUE THREAD

**Issue by klandaika** [gitlabhq/gitlabhq#9703]
When a new LDAP user attempts to login and user's email domain is not on the **Restricted domains for sign-ups** list, the following error is be displayed:
> Could not authorize you from Ldapmain because "Undefined method 'provider' for nil:nilclass".

It would be nice to have the message say that user's domain is not authorized instead, as the above message is cryptic and not representative of the issue at all. It made me feel that there is  a problem with LDAP config or something along those lines, when in reality it was as simple as adding the domain to restricted sign-ups list.

**Comment by muyufan** [comment]
I meet same issue , @klandaika  , what do you mean "Restricted domains for sign-ups list" ? how can I avoid this error ,is it a bug or I need some more config on LDAP?

**Comment by klandaika** [comment]
In the admin area -> settings there are Sign-in Restrictions. I had to list my LDAP domain there for it to start working.

![image](https://cloud.githubusercontent.com/assets/6818055/11184213/55dbee96-8c44-11e5-80d5-210536b47303.png)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
