### ISSUE TITLE
API search case sensitive

### ISSUE THREAD

**Issue by Hito01** [gitlabhq/gitlabhq#9706]
Hi,

Is it normal that the search method on projects are case sensitive ? I don't know if it's easy to workaround but in my opinion, search should not be case sensitive. What do you think ?

Regards

**Comment by sealexer** [comment]
Agree. 
Hit into this issue with 8.0. Our integration made for 7.8 has stopped working. Has search been case-insensitive in 7.8?

**Comment by Hito01** [comment]
Works as expected after a Gitlab update.
