### ISSUE TITLE
Can I use Activity view on the default dashboard (main page)?

### ISSUE THREAD

**Issue by Senorsen** [gitlabhq/gitlabhq#9713]
Hi, Can I use Activity view on the default dashboard (main page)? Many users (and I) were used to this, but after the upgrade to `8.0.4` `1ff385d`, we find that the default dashboard can only display projects, instead of the activity view as it was.

How can I use activity view on the main page **by default**, and (better) use this option by default **for newly registered users**?

P.S. One of the reasons: many users want to see the activity of others (or the projects they starred), and the projects view is often unchanged and with no fun. :laughing:  

Thanks a lot!

**Comment by stanhu** [comment]
You should be able to do this in GitLab 8.1 (to be released October 22) via ac34ce864.

**Comment by Senorsen** [comment]
Thanks.

**Comment by Senorsen** [comment]
@stanhu And can I use "Your Projects' Activity" option as global default?

**Comment by Senorsen** [comment]
Ah, I mean that can I set an option as global default?

**Comment by stanhu** [comment]
No, at the moment it's a user-configurable setting.

**Comment by bigplum** [comment]
I also need to use the project activity as default dashboard.

**Comment by Razer6** [comment]
With GitLab 8.1 you can configure your default view on the dashboard

**Comment by Senorsen** [comment]
But can I (site admin) configure the global default value for all users?

**Comment by Razer6** [comment]
No, this is a user preference. The use can change this in the profile settings. You can also read [here](https://about.gitlab.com/2015/11/05/feature-highlight-user-preferences/) about this.
