### ISSUE TITLE
Emails no longer generated for merge request comments created from the API

### ISSUE THREAD

**Issue by cxfinnag** [gitlabhq/gitlabhq#9715]
We upgraded our gitlab from 6.2 to 8.0.3, and got some regressions.
Version: v8.0.3 ( 1d1c5c1e873cb3d )

When creating a merge request comment through the API,
e.g. POST "/api/v3/projects/3/merge_request/4390/comments" , emails are not sent to whoever watches the merge request. The comment still appears in the merge request comments though.

Merge request comments written in the GUI (by the same user using the API) still generate emails as before though.

**Comment by stanhu** [comment]
I'm not sure how this ever worked. :) Thanks for reporting. I've submitted a fix for this:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1560

**Comment by cxfinnag** [comment]
Thanks, I can confirm that with this fix, our gitlab installation sends emails for merge request notes created with the API.
