### ISSUE TITLE
<code> font size is different for regular and strong contexts in comments

### ISSUE THREAD

**Issue by jankuca** [gitlabhq/gitlabhq#9716]
Consider the following comment content:

```
Isn't `this` **a `lovely` day**?
```

The font size of the `<code>` containing "this" is different than the font size of the `<code>` containing "lovely". This strong content is correctly set to 90% font size (to fit nicely to the rest of the text) while the regular content is set to `inherit`.

Here is a screenshot of how strange the rendering is:

![screen shot 2015-10-09 at 4 42 19 pm](https://cloud.githubusercontent.com/assets/367262/10396895/354e23e0-6ea5-11e5-9d88-86e988e71ac4.png)

**Comment by stanhu** [comment]
I reproduced this on 8.0.3, but as far as I can tell on master this has been fixed:

![image](https://cloud.githubusercontent.com/assets/963826/10398053/c1d04ffa-6e5f-11e5-956b-671453200076.png)

I think this was fixed in 9103602620 and should be available in GitLab 8.1 on October 22.
