### ISSUE TITLE
Mailroom can't access gmail-Account with correct credentials

### ISSUE THREAD

**Issue by maxigs** [gitlabhq/gitlabhq#9717]
I just upgraded the awesome gitlab to the latest version (from source) to use the reply-by-email feature. Unfortunately after 2 days of trying i still can't get it to work and don't know where else to look anymore.

Here is what i get:

```
bundle exec rake gitlab:incoming_email:check RAILS_ENV=production
Checking Reply by email ...

Address formatted correctly? ... yes
MailRoom config exists? ... yes
IMAP server credentials are correct? ... no
  Try fixing it:
  Check that the information in config/mail_room.yml is correct
  For more information see:
  doc/incoming_email/README.md
  Please fix the error above and rerun the checks.
Init.d configured correctly? ... yes
MailRoom running? ... yes

Checking Reply by email ... Finished
```

I'm absolutely sure the credentials are correct. Using them for SMTP works, using them in an IMAP client also works.

Here is what i have:

```
$ cat config/mail_room.yml
mailboxes:
  -
    # IMAP server host
    host: "imap.gmail.com"
    # IMAP server port
    port: 993
    # Whether the IMAP server uses SSL
    ssl: true
    # Whether the IMAP server uses StartTLS
    start_tls: false
    # Email account username. Usually the full email address.
    email: "gitlab@maxigs.de"
    # Email account password
    password: "--REMOVED--"
    # The name of the mailbox where incoming mail will end up. Usually "inbox".
    name: "inbox"
    # Always "sidekiq".
    delivery_method: "sidekiq"
    # Always true.
    delete_after_delivery: true
    delivery_options:
      # The URL to the Redis server used by Sidekiq. Should match the URL in config/resque.yml.
      redis_url: redis://localhost:6379
      # Always "resque:gitlab".
      namespace: resque:gitlab
      # Always "incoming_email".
      queue: incoming_email
      # Always "EmailReceiverWorker"
      worker: EmailReceiverWorker
```

Mailbox is a google-apps account that i have been using forever. Allowing log-in from less secure apps is activated globally for the google-apps-account as well as the user of the mailbox used for gitlab.

Is there any further way to debug the issue? I don't see any logs showing up in log/mail_room.log also.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
