### ISSUE TITLE
Wiki searching doesn't view the file nicely

### ISSUE THREAD

**Issue by andyjeffries** [gitlabhq/gitlabhq#9721]
https://github.com/gitlabhq/gitlabhq/pull/7695 is great, but it means that searching for Wiki pages doesn't take you to the nice view.

For example, here's a video of a project with a "Hello World" wiki page. When viewing it through the menu it looks great, but when you search for it and then click the link it shows just the plain file (which some Chrome extension I have installed displays with line numbers), rather than the rendered output.

![2015-10-12 16_23_55](https://cloud.githubusercontent.com/assets/22904/10431598/e0eba5a6-70fd-11e5-9a5f-76bc720faa54.gif)

If someone wants to point me to roughly were this code is and any advice on how to get a dev GitLab up and working quickly (Vagrantfile maybe), then I'll be happy to have a whack at a PR to fix this.

**Comment by liquidstate** [comment]
Dupe of #9581 ?

**Comment by andyjeffries** [comment]
Yep, I couldn't find the issue when searching for it.
