### ISSUE TITLE
Get merge_requests patch 500

### ISSUE THREAD

**Issue by adaiguoguo** [gitlabhq/gitlabhq#9738]
Request url is :
http://url/group/repo/merge_requests/171.patch

Log is:
Processing by Projects::MergeRequestsController#show as PATCH
Parameters: {"namespace_id"=>"group", "project_id"=>"repo", "id"=>"171"}
Completed 500 Internal Server Error in 552ms (ActiveRecord: 66.4ms)
Rugged::InvalidError (Commit d87401bf08144546468cbf1db4da5b1c31720f1c is a merge commit):
app/models/repository.rb:165:in `method_missing'
app/models/merge_request.rb:271:in `to_patch'
app/controllers/projects/merge_requests_controller.rb:53:in `block (2 levels) in show'
app/controllers/projects/merge_requests_controller.rb:49:in `show'

**Comment by stanhu** [comment]
Closing in favor of the discussion here: https://gitlab.com/gitlab-org/gitlab-ce/issues/3103
