### ISSUE TITLE
Comments on outdated diffs in merge requests sometimes disappear from UI

### ISSUE THREAD

**Issue by ziima** [gitlabhq/gitlabhq#9746]
We have encountered more than a few cases of comments disappearing from merge request UI. The comments are always linked to the obsolete diffs, usually they're new comments in the thread. We haven't been able to set up working reproduction process, but it looks like the Gitlab has troubles with comments added in the open merge request window, after new commits were pushed to the branch.

There are several ways the comments are missing, here is one of them:
 - Pn merge request open in browser the old diff and old comments are shown with false note about outdated diff beneath them.
![screenshot from 2015-10-19 13 38 28](https://cloud.githubusercontent.com/assets/331955/10576872/0a17ef70-7667-11e5-9e8f-0f48bf09f6b7.png)
 - When the allegedly outdated diff is shown, the new diff appears but without any comments.
![screenshot from 2015-10-19 13 39 13](https://cloud.githubusercontent.com/assets/331955/10576875/0ee24938-7667-11e5-8a94-6d915671fd79.png)

But all the comments are listed in the Gitlab API.

**Comment by stanhu** [comment]
I suspect [this proposed fix](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1675) might help this issue.

**Comment by ziima** [comment]
I'm not sure, what it should do, but it didn't helped us. The patch has no effect on the display of broken comments.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
