### ISSUE TITLE
mattermost['gitlab'] setting not applied correctly

### ISSUE THREAD

**Issue by 3rdcycle** [gitlabhq/gitlabhq#9764]
It seems that at least `Secret` and `Id` in `mattermost['gitlab']` do not get transferred to mattermosts `config.json`. This causes authentication to fail after a reauthorization.

I'm running 8.1 btw.

**Comment by maxlazio** [comment]
How does your configuration look? It is is hard to conclude anything without it.

**Comment by 3rdcycle** [comment]
I'll happily provide my configuration even though I'm not sure it is relevant. I have attached the *mattermost* section, if you need the rest of it too please let me know. Also I replaced company specifics with 'example.com' and 'xxx' respectively).

I just noticed that any change I make to the *mattermost* section gets transferred to *config.json* with `gitlab-ctl reconfigure` **except** changes to the `mattermost['gitlab']` entry. AFAIR this used to be `mattermost['oauth']` but [apparently](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L665-790) this has changed in 8.1.

If I change id/secret in mattermost's *config.json* manually, SSO works as expected but then the next `gitlab-ctl reconfigure` will set the values back to their default.

``` ini
#####################
# GitLab Mattermost #
#####################

mattermost_external_url 'https://chat.example.com'
#
mattermost['enable'] = true
# mattermost['username'] = 'mattermost'
# mattermost['group'] = 'mattermost'
# mattermost['home'] = '/var/opt/gitlab/mattermost'
# mattermost['database_name'] = 'mattermost_production'

mattermost['service_use_ssl'] = true
mattermost['service_port'] = "8065"

# mattermost['service_maximum_login_attempts'] = 10
# mattermost['service_segment_developer_key'] = nil
# mattermost['service_google_developer_key'] = nil
# mattermost['service_enable_incoming_webhooks'] = true
# mattermost['service_enable_post_username_override'] = false
# mattermost['service_enable_post_icon_override'] = false
# mattermost['service_enable_testing'] = false
# mattermost['service_enable_security_fix_alert'] = true

mattermost['team_site_name'] = "Team Chat"
# mattermost['team_max_users_per_team'] = 150
mattermost['team_enable_team_creation'] = true
# mattermost['team_enable_user_creation'] = true
# mattermost['team_allow_public_link'] = true
# mattermost['team_allow_valet_default'] = false
# mattermost['team_default_color'] = '#2389D7'
# mattermost['team_restrict_creation_to_domains'] = "example.com"

# mattermost['sql_driver_name'] = 'mysql'
# mattermost['sql_data_source'] = "mmuser:mostest@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8"
# mattermost['sql_data_source_replicas'] = ["mmuser:mostest@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8"]
# mattermost['sql_max_idle_conns'] = 10
# mattermost['sql_max_open_conns'] = 10
# mattermost['sql_trace'] = false

# mattermost['log_file_directory'] = '/var/log/gitlab/mattermost'
# mattermost['log_console_enable'] = true
# mattermost['log_console_level'] = 'INFO'
mattermost['log_enable_file'] = true
# mattermost['log_file_level'] = 'INFO'
# mattermost['log_file_format'] = nil


mattermost['gitlab'] = {'Enable' => true, 'Secret' => "xxx", 'Id' => "xxx", "AuthEndpoint" => "https://gitlab.example.com/oauth/authorize", "TokenEndpoint" => "https://gitlab.example.com/oauth/token", "UserApiEndpoint" => "https://gitlab.example.com/api/v3/user", "Scope" => "" }
# mattermost['aws'] = {'S3AccessKeyId' => '123', 'S3SecretAccessKey' => '123', 'S3Bucket' => 'aa', 'S3Region' => 'bb'}

mattermost['email_enable_sign_up_with_email'] = false
# mattermost['email_send_email_notifications'] = false
# mattermost['email_require_email_verification'] = false
# mattermost['email_smtp_username'] = nil
# mattermost['email_smtp_password'] = nil
# mattermost['email_smtp_server'] = nil
# mattermost['email_smtp_port'] = nil
# mattermost['email_connection_security'] = nil
# mattermost['email_apple_push_server'] = nil
# mattermost['email_apple_push_cert_public'] = nil
# mattermost['email_apple_push_cert_private'] = nil

# mattermost['file_driver_name'] = "local"
# mattermost['file_directory'] = "/var/opt/gitlab/mattermost/data"
# mattermost['file_enable_public_link'] = true
# mattermost['file_thumbnail_width'] = 120
# mattermost['file_thumbnail_height'] = 100
# mattermost['file_preview_width'] = 1024
# mattermost['file_preview_height'] = 0
# mattermost['file_profile_width'] = 128
# mattermost['file_profile_height'] = 128
# mattermost['file_initial_font'] = 'luximbi.ttf'
# mattermost['file_amazon_s3_access_key_id'] = nil
# mattermost['file_amazon_s3_bucket'] = nil
# mattermost['file_amazon_s3_secret_access_key'] = nil
# mattermost['file_amazon_s3_bucket'] = nil


# mattermost['ratelimit_enable_rate_limiter'] = true
# mattermost['ratelimit_per_sec'] = 10
# mattermost['ratelimit_memory_store_size'] = 10000
# mattermost['ratelimit_vary_by_remote_addr'] = true
# mattermost['ratelimit_vary_by_header'] = nil

# mattermost['privacy_show_email_address'] = true
# mattermost['privacy_show_full_name'] = true
```

**Comment by it33** [comment]
It looks like the config above is trying to use settings from GitLab 8.0/Mattermost v0.7-beta (e.g. use_ssl) that need to be updated for GitLab 8.1/Mattermost v1.1.1. Here are instructions and documentation on how to update: https://github.com/mattermost/platform/blob/master/doc/install/Upgrade-Guide.md.

**Comment by 3rdcycle** [comment]
So does that mean that I should adjust *config.json* directly? 

Note that I use omnibus so I usually only touch *gitlab.rb*.

The settings I used above are based on [omnibus-gitlab/files/gitlab-config-template/gitlab.rb.template](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L665-790) in the master branch. I would have expected `gitlab-ctl reconfigure` to translate those to the right keys in *config.json* automatically.

**Comment by it33** [comment]
Hi @3rdcycle, 

Good question, going from Mattermost 0.7.1-beta in GitLab 8.0 to Mattermost v1.1.1 in GitLab 8.1 involved a large number of changes in Mattermost config to create a stable platform for future development. 

We didn't think it appropriate for GitLab omnibus to attempt and automated configuration so we provided an upgrade guide for GitLab users to achieve this. It's relatively straight forward to update the non-default settings in most Mattermost deployments, whereas automation just would be too complex. 

In future, there shouldn't be anything near the scale of change that happened between beta and 1.0. 

Updated the guide to make this more clear: https://github.com/mattermost/platform/blob/master/doc/install/Upgrade-Guide.md

So this could mean updating the `config.json` file without automation.  

Does this help?

**Comment by 3rdcycle** [comment]
Yes that helps, thanks. 

The issue that remains though, is that `gitlab-ctl reconfigure` does seem to set a value for *id* and *secret* in the *config.json* file which effectively reverses any changes I make there manually. I have no idea where the values for these two keys are coming from but it is not from gitlab.rb.

**Comment by it33** [comment]
[Here are instructions on how to get those values from GitLab](https://github.com/mattermost/platform/blob/master/doc/integrations/Single-Sign-On/Gitlab.md#configuring-gitlab-single-sign-on) for your `config.json` file. 

Maybe try those steps manually and see if the automation is providing the correct values? If so, then you can trust it's doing the right thing, if not, you should be able to use the new values you found to connect?

**Comment by 3rdcycle** [comment]
These steps are exactly what I did. However, as I said before, `gitlab-ctl reconfigure` will replace the id and secret from step 3 with some magic numbers that don't seem to be working.

**Comment by it33** [comment]
Hi @3rdcycle, just curious, would you recall the message you got when authentication failed? I'm wondering if [this issue is related](https://gitlab.com/gitlab-org/gitlab-mattermost/issues/35#note_2570488)? 

I wasn't sure if you are upgrading from previous Mattermost instance or just running a new one. If it's fresh it should be straight forward. 

We tested GitLab Omnibus 8.1 RC2 and it worked for us when we set it up...

**Comment by 3rdcycle** [comment]
The message I get is "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.". To reiterate, this only happens after `gitlab-ctl reconfigure` replaces id and secret in config.json. If I go back and set the correct values manually, everything works fine again.

I upgraded from a previous version. I'm suspecting that `gitlab-ctl reconfigure` picks up those non-working values from a previous version somewhere and writes them to config.json. I just don't know exactly where they come from... Is there a way to make the output of `gitlab-ctl reconfigure` more verbose?

**Comment by it33** [comment]
Hi @3rdcycle, sorry, not sure on `gitlab-ctl` options, propose searching https://gitlab.com/gitlab-org/omnibus-gitlab/issues to see if there's a way to get the output more verbose?

**Comment by ben-page** [comment]
I'm having this exact issue @3rdcycle is describing. I can get mattermost working by manually editing the config.json manually. But my settings from gitlab.rb are not copied.

**Comment by ben-page** [comment]
I figured it out. The documentation for configuring mattermost in gitlab is totally wrong. I commented on 
this bug report with the right gitlab.rb settings.
https://gitlab.com/gitlab-org/gitlab-mattermost/issues/34

**Comment by 3rdcycle** [comment]
Thanks @ben-page, using `mattermost['gitlab_secret']` and `mattermost['gitlab_id']` instead of `mattermost['gitlab']` fixed it! Docs/template should be updated.

**Comment by it33** [comment]
Thanks @3rdcycle! Highly appreciate the fix!!
