### ISSUE TITLE
fatal: unable to access 'http://gitlab-ci-token:xxxxxx@gitlabserver/gitlabuser@gitlabserver:group/project.git/': The requested URL returned error: 503

### ISSUE THREAD

**Issue by Soullivaneuh** [gitlabhq/gitlabhq#9768]
I got a strange error without any clue to resolve it:

```bash
gitlab-ci-multi-runner 0.6.2 (3227f0a)
Using Docker executor with image tetraweb/php:5.6 ...
Pulling docker image tetraweb/php:5.6 ...

Pulling docker image mysql:5.6 ...
Starting service mysql:5.6 ...
Waiting for services to be up and running...
Pulling docker image gitlab/gitlab-runner:service ...
Running on runner-f746bee8-project-1-concurrent-0 via sd-xxxxx...

Cloning repository...
Cloning into '/builds/group/project'...
fatal: unable to access 'http://gitlab-ci-token:xxxxxx@gitlabserver/group/project.git/': The requested URL returned error: 503
The requested URL returned error: 503

ERROR: Build failed with: exit code 1
```

I don't know if it's a bug or a misconfiguration... any idea?

Running GitLab 8.1.0.

Thanks.

**Comment by Soullivaneuh** [comment]
Seems to be an error related to http clone:

```bash
$ git clone https://git.domain.com/group/project.git
Cloning into 'project'...
fatal: unable to access 'https://git.domain.com/group/project.git/': The requested URL returned error: 503
```

But can't find any relevant log.

**Comment by Soullivaneuh** [comment]
I find a clue. The git-http-server is launched like this on your init script:

```bash
/home/git/gitlab/../gitlab-git-http-server/gitlab-git-http-server -listenUmask 0 -listenNetwork unix -listenAddr /home/git/gitlab/tmp/sockets/gitlab-git-http-server.socket -authBackend http://127.0.0.1:8080 /home/git/repositories
```

This use socket.

If I run it without option (defaults):

```bash
/home/git/gitlab/../gitlab-git-http-server/gitlab-git-http-server
```

It works.

But I don't understand. Even if this use a socket, it should be accessible through 127.0.0.1:8181, isn't it?

Seems not.

Note: I use apache reverse proxy with config file found on your recipes.

**Comment by Soullivaneuh** [comment]
Additional information: If I call the server running socket with a simple curl, I got this:

```bash
$ curl http://127.0.0.1:8181
curl: (7) couldn't connect to host
```

**Comment by Chiruclan** [comment]
If it runs on a socket, it doesn't run on 127.0.0.1:8181.
So you can either configure your webserver to connect to the unix socket, or change the gitlab-git-http-server startup parameters to bind to 127.0.0.1:8181.
That being said, i have to admit that i'm not sure if apache is able to connect to unix sockets.

Therefore:
https://gitlab.com/gitlab-org/gitlab-git-http-server/blob/master/README.md pretty much explains the startup parameters.

**Comment by perryfaro** [comment]
Also make sure that your gitlab.config contains the following two options with true:

```
upload_pack: true
    receive_pack: true
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
