### ISSUE TITLE
Getting error when try git push locally

### ISSUE THREAD

**Issue by visnupriya** [gitlabhq/gitlabhq#9772]
Hi,
I installed gitlab for contribution and clone gitlab, git-shell locally and tried to run in development mode.
I set-up gitlab in my local system instead "git" system and changed the "default" name in gitlab and git-shell.

I can run gitlab at http://localhost:3000 and configured ssh key and created sample project and cloned it using the following command
```
git clone visnupriya@localhost:/home/visnupriya/git/repositories/visnupriya/test-public-project.git

```
and tried to push code and getting following error 
```
visnupriya@localhost's password: 
Counting objects: 3, done.
Writing objects: 100% (3/3), 207 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: /home/visnupriya/git/gitlab-shell/lib/gitlab_net.rb:16:in `check_access': undefined method `join' for #<Enumerator:0x00000001d1f118> (NoMethodError)
remote: 	from /home/visnupriya/git/gitlab-shell/lib/gitlab_access.rb:23:in `exec'
remote: 	from hooks/pre-receive:13:in `<main>'
To visnupriya@localhost:/home/visnupriya/git/repositories/visnupriya/test-public-project.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'visnupriya@localhost:/home/visnupriya/git/repositories/visnupriya/test-public-project.git'

```

Any idea?

**Comment by axilleas** [comment]
Are you familiar with https://gitlab.com/gitlab-org/gitlab-development-kit ?

This is used for the official GitLab development.

**Comment by visnupriya** [comment]
Thank you Axilleas. Will check it

**Comment by Razer6** [comment]
I close this issue here. If you find any issues in the GDK, please report on their tracker.

**Comment by visnupriya** [comment]
Sure
