### ISSUE TITLE
Can't checkout merge request

### ISSUE THREAD

**Issue by maxraab** [gitlabhq/gitlabhq#9773]
Hi there, I just updated GitLab to version 8.1. When i try to checkout a merge request, Git says that the repo does not exitsts or I shout check my access rights. The main repo is internal and the fork of these is private. With reference to the release information (https://about.gitlab.com/2015/10/22/gitlab-8-1-released/) I should be able to checkout - even its from a fork and i haven't rights.

**Comment by jvanbaarsen** [comment]
@maxraab Can you post logs here? We need a bit more information in order to help you.

**Comment by maxraab** [comment]
There is a button "Checkout" on the merge request page. If I click on it, i can see the instructions to checkout the branche with I should merge to my repository. But when I follow these instructions, I'll get an error, that the repository doesn't exits or I did not have enough rights to visit them.

```
fatal: 'git@domain.tld/user.name/repo.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by grigorig** [comment]
I have the same issue. The merge request comes from a repository that is normally private. But I should have access to the affected branch anyway when a merge request is assigned to me, right? That would make sense, at least.

I have to add to this that the merge request includes a large number of changes (reformatting/refactoring) in one commit, so much that GitLab can't load the diff! So currently there is no way for me to review the MR.

**Comment by grigorig** [comment]
In other words, is it really sensible to allow the creation of merge requests when others can't access the branch that is to be merged? I think GitLab should either just disallow this or override the project permissions.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
