### ISSUE TITLE
merge request returns 500 Internal Server Error

### ISSUE THREAD

**Issue by gregster85** [gitlabhq/gitlabhq#9777]
We have 2 merge requests that return this error in the gitlab production.log:

```
Started GET "/x/x/merge_requests/321" for x.x.x.x at 2015-10-27 11:39:17 +0100 Processing by Projects::MergeRequestsController#show as HTML Parameters: {"namespace_id"=>"x", "project_id"=>"x", "id"=>"321"} Completed 500 Internal Server Error in 267ms (ActiveRecord: 10.7ms)
ActionView::Template::Error ((): control characters are not allowed at line 1 column 1): 50: = link_to diffs_namespace_project_merge_request_path(@project.namespace, @project, @merge_request), data: {target: '#diffs', action: 'diffs', toggle: 'tab'} do 51: = icon('list-alt') 52: Changes 53: %span.badge= @merge_request.diffs.size 54: 55: .tab-content 56: #notes.notes.tab-pane.voting_notes app/models/merge_request_diff.rb:48:in diffs'
  app/models/merge_request.rb:42:indiffs' app/views/projects/merge_requests/show.html.haml:53:in `block in app_views_projectsmerge_requestsshow_html_haml1316813672979675922_70095945581860' app/helpers/application_helper.rb:258:in link_to'
app/views/projects/merge_requests/_show.html.haml:50:inapp_views_projectsmerge_requestsshow_html_haml_1316813672979675922_70095945581860' app/views/projects/merge_requests/show.html.haml:1:in `app_views_projects_mergerequests_show_html_haml266120151584497111_70095945629440' app/controllers/projects/merge_requests_controller.rb:50:in `show'
```

How can this be fixed? Our gitlab version is 7.12.2.

**Comment by jvanbaarsen** [comment]
@gregster85 can you give more information? What is the namespace name? Is there some unicode character in there? Also I woud advise you to upgrade to latest version and see if the problem is still there.

We need some way to reproduce otherwise we aren't able to help you.

**Comment by gregster85** [comment]
Parameters: {"namespace_id"=>"developmentteamphp", "project_id"=>"control-panel", "id"=>"314"}

I'll update to 7.14 and check

**Comment by gregster85** [comment]
I have updated to 7.14.3 but the problem remains.
Is there a (dirty) way to remove these 2 merge requests?

**Comment by stanhu** [comment]
It sounds like the merge request diff has some control characters. Can you look in your DB to see what the contents are? You may have to do something like:

```
sudo gitlab-rails dbconsole
SELECT * from merge_request_diffs where merge_request_id = 321
```

**Comment by gregster85** [comment]
`
gitlabhq_production=# SELECT * from merge_request_diffs where merge_request_id = 321;
 id  |   state   |                          st_commits                          |                                                               st_diffs                                                               | merge_request_id |       created_at       |       updated_at
-----+-----------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+------------------+------------------------+------------------------
 315 | collected | ---                                                         +| ---                                                                                                                                 +|              321 | 2014-11-19 09:48:26+01 | 2014-11-19 09:48:26+01
     |           | - :id: !binary |-                                           +| - :diff: ! "--- a/app/modules/default/controllers/IndexController.php\n+++ b/app/modules/default/controllers/IndexController.php\n@@+|                  |                        |
     |           |     NzkxOWE1YjI2MDdkYWQ4YWY2M2RjNGZhOGVkYzJlM2JkZmQ0YmM3NQ==+|     -304,5 +304,9 @@ class IndexController extends Myc_Controller_Action\n             exit('Invalid                                +|                  |                        |
     |           |   :message: Fix BlankAction error                           +|     request');\r\n         }\r\n     }\r\n+\r\n+    public function blankAction()\r\n+                                              +|                  |                        |
     |           |   :parent_ids:                                              +|     \   {\r\n+    }\r\n }\r\n \r"                                                                                                   +|                  |                        |
     |           |   - !binary |-                                              +|   :new_path: app/modules/default/controllers/IndexController.php                                                                    +|                  |                        |
     |           |     YzkxMGYyYmIyZTEzZjU0NTI1ODI1ZjczYjc3ODA0YWVmNDcwYTYxNQ==+|   :old_path: app/modules/default/controllers/IndexController.php                                                                    +|                  |                        |
     |           |   :authored_date: 2014-11-19 10:46:30.000000000 +01:00      +|   :a_mode:                                                                                                                          +|                  |                        |
     |           |   :author_name: Bram		                               +|   :b_mode: !binary |-                                                                                                               +|                  |                        |
     |           |   :author_email: bram@x.com		                       +|     MTAwNzU1                                                                                                                        +|                  |                        |
     |           |   :committed_date: 2014-11-19 10:46:30.000000000 +01:00     +|   :new_file: false                                                                                                                  +|                  |                        |
     |           |   :committer_name: Bram	                               +|   :renamed_file: false                                                                                                              +|                  |                        |
     |           |   :committer_email: bram@x.com	                       +|   :deleted_file: false                                                                                                              +|                  |                        |
     |           |                                                              |                                                                                                                                      |                  |                        |
(1 row)
`

**Comment by gregster85** [comment]
I have pasted the output here: http://pastebin.com/raw.php?i=nRpgmVP5

**Comment by stanhu** [comment]
I don't see anything obvious in the actual database entry, but perhaps I'm not seeing it. Perhaps you could enable extended mode in PostgreSQL? Simply type `\x` before the `SELECT` statement.

Is it possible one of these files is corrupted?

* `/opt/gitlab/embedded/service/gitlab-rails/app/views/projects/merge_requests/show.html.haml` 
* `/opt/gitlab/embedded/service/gitlab-rails/app/views/projects/merge_requests/_show.html.haml`

You may want to reinstall the files or upgrade GitLab if that's the case.

**Comment by gregster85** [comment]
Those files are not corrupt, I compared them to the the git repo origin/7-14-stable.
The extended mode output query from postgresql is available on http://pastebin.com/raw.php?i=xiFQqq7G

**Comment by jvanbaarsen** [comment]
@gregster85 Please update to latest version which is 8.1.2

**Comment by gregster85** [comment]
I have updated to 8.1.2 8c8af7b. The problem remains the same. Error message on web is still 500 internal server error, and error message in production.log is the same.
Is there a way to delete the 2 merge requests?

**Comment by gregster85** [comment]
I have deleted this merge request from the merge_requests postgres table
