### ISSUE TITLE
Rugged::OdbError: Object not found - failed to find pack entry 

### ISSUE THREAD

**Issue by manasbala** [gitlabhq/gitlabhq#9779]
I am having this error for a specific project.

```
ERP / biznet ... rake aborted!
Rugged::OdbError: Object not found - failed to find pack entry (079ec8fc48936ea44c9d3f53920ec52976527e62)
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:56:in `target'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:56:in `block in branches'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:55:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:55:in `map'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:55:in `branches'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:50:in `branch_names'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:109:in `discover_default_branch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:33:in `initialize'
/home/git/gitlab/app/models/repository.rb:8:in `new'
/home/git/gitlab/app/models/repository.rb:8:in `initialize'
/home/git/gitlab/app/models/project.rb:224:in `new'
/home/git/gitlab/app/models/project.rb:224:in `repository'
/home/git/gitlab/lib/tasks/gitlab/check.rake:500:in `block in check_repos_hooks_directory_is_link'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in `block (2 levels) in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in `block in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:125:in `find_in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:51:in `find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/querying.rb:9:in `find_each'
/home/git/gitlab/lib/tasks/gitlab/check.rake:498:in `check_repos_hooks_directory_is_link'
/home/git/gitlab/lib/tasks/gitlab/check.rake:359:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => gitlab:check => gitlab:gitlab_shell:check
```

If I try to browse the project in browser it gives 500 error.

**Comment by jvanbaarsen** [comment]
@manasbala What version of GitLab? What OS?When do you get the error?

**Comment by manasbala** [comment]
@jvanbaarsen I am using 7.7.1
and I get this when run gitlab:check
also projct not browsable in browser. get a 500 error. And in log file I see the same error. 

```
Object not found - failed to find pack entry (079ec8fc48936ea44c9d3f53920ec52976527e62)
```

**Comment by Razer6** [comment]
This has been fixed in a newer version AFAIK. Please update to the latest version and report back if he error still exits.

**Comment by paralikar** [comment]
Hello,

We are completely new to GIT as well as GITLAB. Not sure whats happening, but we are receiving similar errors with our installation. Below is the output from the gitlab check command.

We used the DEB package to install gitlab as that was the simplest way to do it. Everything was working fine but not sure how something went wrong and this error started popping up.

Here is the command output:
root@etggitsrv:/opt/gitlab/bin# gitlab-rake gitlab:gitlab_shell:check --trace
** Invoke gitlab:gitlab_shell:check (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute gitlab:gitlab_shell:check
Checking GitLab Shell ...

GitLab Shell version >= 2.5.3 ? ... OK (2.5.3)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
tservices / tservices ... ok
vf / vfgds ... ok
mf / S_App ... repository is empty
mf / DP2014 ... repository is empty
TMS / TMS ... rake aborted!
Rugged::OdbError: Object not found - failed to find pack entry (6991c7455382180039a6a87e29ecff2211a570f2)
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:56:in `target'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:56:in `block in branches'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:55:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:55:in `map'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:55:in `branches'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:50:in `branch_names'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:109:in `discover_default_branch'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-7.0.0.rc14/lib/gitlab_git/repository.rb:33:in `initialize'
/opt/gitlab/embedded/service/gitlab-rails/app/models/repository.rb:8:in `new'
/opt/gitlab/embedded/service/gitlab-rails/app/models/repository.rb:8:in `initialize'
/opt/gitlab/embedded/service/gitlab-rails/app/models/project.rb:248:in `new'
/opt/gitlab/embedded/service/gitlab-rails/app/models/project.rb:248:in `repository'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:500:in `block in check_repos_hooks_directory_is_link'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in `block (2 levels) in find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:52:in `block in find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:125:in `find_in_batches'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/batches.rb:51:in `find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/querying.rb:9:in `find_each'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:498:in `check_repos_hooks_directory_is_link'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:359:in `block (3 levels) in <top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/gitlab/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `load'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => gitlab:gitlab_shell:check
====================================

We thought its a repo issue, hence we tried moving out TMS repo from GIT and tried it. But the error is still same. Dont know how to check and repair the DB.
@Razor6 - I am not sure what is AFAIK. Hence any more details to resolve this will be helpful.

Thanks,

**Comment by Razer6** [comment]
What version of GitLab are you using. Have you tried updating to the newest version of GitLab?

**Comment by paralikar** [comment]
I am using gitlab- 7.8.0-omnibus-1. I haven't tried to upgrade as I am not sure if the upgrade will break the current repos and the user mapping, as there seems to be some serious errors. I am not sure if we can just run the upgrade as is without compromising the current GIT and its repo data.

**Comment by paralikar** [comment]
@Razer6, I browsed through the net and also gitlab. But I didnt find any help regarding upgrading of Gitlab using the DEP package method. There are resources for upgrading using source code but not using the installation packages. 

Can you please guide us through and also confirm, if the upgrade will not break anything in the current setup.

**Comment by paralikar** [comment]
I have upgraded the GitLab to the latest version 8.2.x.  Followed the method given for upgrade in Gitlab site. The upgrade went on well and completed without any errors.  Below is the output from DPKG command.

root@gitsrv:/home/gitadmin# dpkg -l|grep gitlab
rc  gitlab                       7.8.0-omnibus-1   amd64        The full stack of gitlab
ii  gitlab-ce                    8.2.1-ce.0            amd64        GitLab Community Edition and GitLab

But the error still remains the same. 

root@gitsrv:/home/gitadmin# gitlab-rake gitlab:gitlab_shell:check --trace
** Invoke gitlab:gitlab_shell:check (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute gitlab:gitlab_shell:check
Checking GitLab Shell ...

GitLab Shell version >= 2.6.8 ? ... OK (2.6.8)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
hooks directories in repos are links: ...
tservices / tservices ... ok
vf / vfgds ... ok
mf / S_App ... repository is empty
mf / DP2014 ... repository is empty
TMS / TMS ... rake aborted!
Rugged::OdbError: Failed to inflate loose object.

CAN SOMEONE HELP PLZ?

**Comment by foux** [comment]
I've got the same issue on a 8.6.5 installation, with the error : 
```
Rugged::OdbError: Failed to inflate loose object.
```
The project can't be deleted. Any way around this?

**Comment by roshan3133** [comment]
Getting same error in gitlab 7.1.2 any update

**Comment by roshan3133** [comment]
http://stackoverflow.com/questions/36546774/gitlab-repository-corrupted-showing-500-error-on-frontend/36599198#36599198
