### ISSUE TITLE
Accept Merge request is not working

### ISSUE THREAD

**Issue by CroessMe** [gitlabhq/gitlabhq#9784]
At batnami gitlab（7.14.3） ， when merge request ，happen Accept Merge request is not working

**Comment by Razer6** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
