### ISSUE TITLE
Ability for scaling runners into a cluster, by allowing a configuration of the REGISTER_TOKEN.

### ISSUE THREAD

**Issue by cusspvz** [gitlabhq/gitlabhq#9789]
We are trying to deploy runners (using **gitlab-ci-multi-runner**) into our dev cluster, happens that we have 4 gitlab instances into the GitLab service and all of them have different runner register tokens.

When we deploy a **gitlab-ci-multi-runner** service, we cannot know which GitLab instance runner will hit. (In fact we could, but it won't meet our HA scheme standards since scaling would fail in case that specific GitLab instance goes down, and a Health Check failure is enough to replace that failing instance by a new one).

As so, I'm proposing to add a config statement for the [REGISTRATION_TOKEN](https://github.com/gitlabhq/gitlabhq/blob/master/config/initializers/4_ci_app.rb#L5) constant.
I can also contribute with a PR if the *GitLab Team* agree with the proposal.

Thanks,
José Moreira

**Comment by cusspvz** [comment]
Sorry for being intrusive, we have this marked internally has high priority.
Can anyone point me a person of the team to address a discussion on this issue?

/ping @maxlazio @axilleas @ayufan @dblessing @dosire @DouweM @jacobvosmaer @jameswritescode @JobV @jvanbaarsen @NARKOZ @randx @Razer6 @stanhu @tsigo

**Comment by ayufan** [comment]
@cusspvz You can pick this issue and create MR for it: https://gitlab.com/gitlab-org/gitlab-ce/issues/2854
