### ISSUE TITLE
7.2 to 8.0 – Shutting down gitlab-git-http-server hangs

### ISSUE THREAD

**Issue by phanan** [gitlabhq/gitlabhq#9792]
I'm using an installed-from-source Gitlab – Omnibus wasn't an option 3 years ago :( After upgrading from 7.2 to 8.0 today, there's this issue when I tried to (re)start Gitlab service:

```
$ service gitlab restart
Shutting down GitLab Unicorn
Shutting down GitLab Sidekiq
Shutting down gitlab-git-http-server
.......................................................(to infinity and beyond)^C
Session terminated, killing shell... ...killed.
```

As you can see, the number of dots just keeps increasing to infinity. Now I'll kill it manually and start the service again:

```
$ service gitlab start
Removing stale gitlab-git-http-server pid. This is most likely caused by gitlab-git-http-server crashing the last time it ran.
Starting GitLab Unicorn
Starting gitlab-git-http-server
bundler: command not found: unicorn_rails
Install missing gem executables with `bundle install`
The Sidekiq job dispatcher is already running with pid 21214, not restarting
..............................Waited 30s for the processes to write their pids, something probably went wrong.
.........................
```

Another try you say?

```
$ service gitlab start
Starting GitLab Unicorn
bundler: command not found: unicorn_rails
Install missing gem executables with `bundle install`
The Sidekiq job dispatcher is already running with pid 21214, not restarting
The gitlab-git-http-server is already running with pid 21214, not restarting
..............................Waited 30s for the processes to write their pids, something probably went wrong.
```

And of course, nginx returns a beautiful 502 error. 

Anyone can give me a clue what's going on here?

**Comment by phanan** [comment]
Also, it might be worth noting that starting Unicorn manually with the `gitlab` user works just fine:

```
$ bundle exec unicorn -c config/unicorn.rb -E production -D
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
