### ISSUE TITLE
Gitlab 8.1.2 Lint validate works only once

### ISSUE THREAD

**Issue by baarthor** [gitlabhq/gitlabhq#9795]
for a second validate refresh of the page is necessary.

**Comment by jacob-carlborg** [comment]
Still present in latest 8.3.4.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
