### ISSUE TITLE
Mattermost SSO not working

### ISSUE THREAD

**Issue by warroyo** [gitlabhq/gitlabhq#9797]
After upgrading to 8.1.2 for 8.0.0 Mattermost seems to be having some issues. When trying to login I am getting the following error. `The redirect URI included is not valid.` I am using SSL and it looks like in the url it is trying to use non SSL(`&redirect_uri=http%3A%2F%2Fmattermost.gitlab.mydomain.com...`) Is there  a new setting in the gitlab.rb file that I need to update?

**Comment by axilleas** [comment]
Hi! Please direct any issues with mattermost at https://gitlab.com/gitlab-org/gitlab-mattermost/issues where its developers will help you.
