### ISSUE TITLE
Build the embedded nginx with sub_filter support (--with-http_sub_module)

### ISSUE THREAD

**Issue by weijianwen** [gitlabhq/gitlabhq#9801]
Hi,

I use gitlab's embedded nginx as my default web server to support not only GitLab, but also some other sites. It works well for PHP-backend sites and static sites, however it misses the "sub_filter" feature. Is it possible to build sub_filter into nginx in GitLab's next release?

Best,

**Comment by stanhu** [comment]
Unless there's a compelling reason to add sub_filter for GitLab, I doubt this will happen. The embedded nginx is intended to support GitLab only and cannot support every use case. I'm closing this issue for now.
