### ISSUE TITLE
GitLab CI gets enabled when pushing .gitlab-ci.yml

### ISSUE THREAD

**Issue by maxraab** [gitlabhq/gitlabhq#9809]
Hello, 

if I fork a repo that has GitLab CI enabled and the .gitlab-ci.yml in the repository, it auto enables CI for my fork. My fork did not have runners by default so every commit ends with a status "pending" becouse  there is no runner that can do the build-process.

Is it possible to change the behaviour to not auto-enabling GitLab CI, if there was a .gitlab-ci.yml pushed to the repo?

**Comment by MauriceMohlek** [comment]
Why don't you just turn off GitLab CI for your fork?
On your project (fork) : Settings > Services > GitLab CI

It will only affect your fork.

I don't see any need to disable that behavior by default.

**Comment by maxraab** [comment]
Its 'fixed' in GitLab Version 8.2 - the autorunners gets auto enabled too.
