### ISSUE TITLE
Users with developer privileges can't approve MRs

### ISSUE THREAD

**Issue by stephenpascoe** [gitlabhq/gitlabhq#9810]
Using GitLab Enterprise Edition 7.14.1-ee 6794482

We want to code review amongst our team, including those without master privileges, but this appears not possible.  If I set the MR approvers to 2 users, one with master and one with developer privileges only the first can approve the MR.

To me it makes sense that only masters can merge the MR but developers should be able to approve.

**Comment by axilleas** [comment]
\cc @DouweM @tsigo

**Comment by DouweM** [comment]
cc @vsizov You implemented MR approvals, could you verify if this is an issue or "working as expected"?

**Comment by vsizov** [comment]
It was fixed two release ago I think. Please make sure that you have fresh version before create an issue.
