### ISSUE TITLE
An issue should also be considered 'updated' when someone comments on it

### ISSUE THREAD

**Issue by liquidstate** [gitlabhq/gitlabhq#9823]
An issue only seems to be "updated" when it is edited.  It would be preferable if its update timestamp was also updated when a comment is made against the issue.  In particular, I would like to be able to find stale issues - e.g. those that haven't seen any changes, comments, etc.

**Comment by stanhu** [comment]
See: https://gitlab.com/gitlab-org/gitlab-ce/issues/2027

Closing this issue in favor of that one.
