### ISSUE TITLE
Cross-Site Scripting Warning in app/controllers/projects/merge_requests_controller.rb

### ISSUE THREAD

**Issue by fdizile** [gitlabhq/gitlabhq#9824]
Discovery date: 
------
2015-11-12
Source:
------
static code analysis
Confidence level:
------
Medium

Issue:
------

Unescaped model attribute rendered inline in app/controllers/projects/merge_requests_controller.rb:54

Project.find_with_namespace([params[:namespace_id], "/", params[:id]].join("")).merge_requests.find_by!(:iid => params[:id]).to_patch(current_user)

SOLUTION: fix the issue in app/controllers/projects/merge_requests_controller.rb

NOTES: XSS occurs when a user-manipulatable value is displayed on a web page without escaping it, allowing someone to inject Javascript or HTML into the page.

**Comment by fdizile** [comment]
Automagically generated by fdizile! Your ruby friend!

**Comment by randx** [comment]
I dont understand this report. 

> Unescaped model attribute rendered inline in app/controllers/projects/merge_requests_controller.rb:54

line 54 is `render :text`. There is no possible XSS there

**Comment by fdizile** [comment]
This report was by a bot that was early in development.

It has been disabled on your repos.

Thanks,
Fdizile

On Thursday, November 12, 2015, Dmitriy Zaporozhets <
notifications@github.com> wrote:

> I dont understand this report.
>
> Unescaped model attribute rendered inline in
> app/controllers/projects/merge_requests_controller.rb:54
>
> line 54 is render :text. There is no possible XSS there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitlabhq/gitlabhq/issues/9824#issuecomment-156088553>.
>


-- 


  *Max Tuchman*
------------------------------------------
------------------------------------------
Contact me:
me@mbtuchman.com
hire@mbtuchman.com
fdizile@gmail.com

*DISCLAIMER:*
The information contained in this e-mail and its attachments are intended
solely for the use of the individual(s) to whom it is addressed and
contains information that is confidential. If the reader of this e-mail is
not the intended recipient, you are hereby notified that any dissemination,
distribution, or copying of this e-mail is strictly prohibited. If you have
received this e-mail in error, please immediately notify the sender and
destroy the e-mail. Thank You.

**Comment by fdizile** [comment]
Report marked as false positive.
