### ISSUE TITLE
Provide Context in Comment Notification Mail

### ISSUE THREAD

**Issue by fwilhe** [gitlabhq/gitlabhq#9826]
I would love to have some lines of code for context in mails that notify me about comments for merge requests. This would improve my workflow because I don't need to follow the link in many cases and can just get the necessary information from the mail.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
