### ISSUE TITLE
Undocumented work in progress prefix

### ISSUE THREAD

**Issue by valermor** [gitlabhq/gitlabhq#9828]
Officially marking a merge request as a work in progress is done by pre-fixing the title by _WIP:_ or _[WIP]_. However, prefixing the title with _WIP_ followed by a blank also makes the the merge request a work in progress.
It looks like a little issue but it turned out into a quite big problem in our pipeline.

**Comment by axilleas** [comment]
Agreed, I noticed it the other day myself.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
