### ISSUE TITLE
Markdown files length

### ISSUE THREAD

**Issue by FWoelffel** [gitlabhq/gitlabhq#9829]
Hi there,

I'm writing an essay in markdown files. Those files have become quite long and I can no longer read them on Gitlab. Instead of the nice HTML output, Gitlab only shows the download link.

![screen shot 2015-11-15 at 00 32 07 2](https://cloud.githubusercontent.com/assets/5467696/11166362/60258354-8b30-11e5-9376-f4c7895aa011.png)

Is there any way to increase the size limit to render such files ?

Thanks for reading,
Fred

**Comment by Razer6** [comment]
There should be no limitation on the file name. Was the rendered HTML output working with the same file when it was smaller? /cc @tsigo

**Comment by FWoelffel** [comment]
Yes it was working before my last commits which only added 3kb of text to this file.

**Comment by Razer6** [comment]
Is this reproducible on GitLab.com?

**Comment by Razer6** [comment]
I cannot. I added a test repo with a 20k-filesize readme and it is rendered. https://gitlab.com/test-repositories/testmarkup-filesize/blob/master/README.md

**Comment by FWoelffel** [comment]
Well. Where can I find any logs that could help us ?

**Comment by FWoelffel** [comment]
I reproduced this on GitLab.com. Have a look at my PR

**Comment by tsigo** [comment]
> I reproduced this on GitLab.com. Have a look at my PR

Where?

**Comment by Razer6** [comment]
@tsigo https://gitlab.com/woelffel-f/testmarkup-filesize/blob/master/01%20-%20Présentation%20de%20l'entreprise.md

**Comment by tsigo** [comment]
So it's not actually the filesize that's the problem -- we don't perform any checks for large text files. It appears that the file isn't being detected as text for some reason. Perhaps bad encoding?

**Comment by FWoelffel** [comment]
This file is encoded with UTF-8.

**Comment by stanhu** [comment]
The `charlock_holmes` gem interprets that file as binary--and it's certainly confident!

```ruby
{:type=>:binary, :confidence=>100}
```

Result from:

```ruby
require 'charlock_holmes/string'

contents = File.read('test.md')
detection = CharlockHolmes::EncodingDetector.detect(contents)
puts detection
```

**Comment by stanhu** [comment]
`grep` also thinks this is a binary file. Somewhere in that file you must have a non-standard character:

http://userguide.icu-project.org/conversion/detection

**Comment by stanhu** [comment]
Hah, the last part of the file has a null character. From hexdump:

```
000044d0  61 6c 2e 0a 00 0a                                 |al....|
000044d6
```

Removing that makes it a text file again. :)
