### ISSUE TITLE
Subtree and issues

### ISSUE THREAD

**Issue by dalcacer** [gitlabhq/gitlabhq#9831]
Hi,
when using git-subtrees the referenced issues in the commit message refers to all repositories in use.
e.g. `closes #1` closes the issues for the major repository and each and every used subtree.

Is there a server side way to identify those subtrees, e.g. in terms of of post-commit-hooks, and to solve this issue?

Kind Regards
Dorian

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
