### ISSUE TITLE
star count in project partials don't update after toggling star

### ISSUE THREAD

**Issue by hxx** [gitlabhq/gitlabhq#9834]
star count in project partials will not update after toggling star, 

I think that caused by

https://github.com/gitlabhq/gitlabhq/blob/master/app/views/shared/projects/_project.html.haml#L8

```ruby
= cache [project.namespace, project, controller.controller_name, controller.action_name, 'v2.2'] do
```
which didn't include project.star_count in cache.

**Comment by axilleas** [comment]
@randx git blames you :p

**Comment by randx** [comment]
oh thanks. @axilleas can you please create an issue on gitlab.com and mention me?

**Comment by axilleas** [comment]
Ok let's continue in https://gitlab.com/gitlab-org/gitlab-ce/issues/3513

@hxx thanks for the report! Also we are slowly deprecating the GitHub tracker so please open any upcoming issues at https://gitlab.com/gitlab-org/gitlab-ce/issues
