### ISSUE TITLE
Can commit to Protected Branch via web interface

### ISSUE THREAD

**Issue by rek** [gitlabhq/gitlabhq#9836]
If you edit a file from the web interface edit view, you can save the changes and the commit will be made, even though the branch is protected and you do not have access to push to it. Should protected branches also prevent this?

**Comment by stanhu** [comment]
Yes, I think this should be the case, and it looks like it's still a bug.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
