### ISSUE TITLE
502 error on user pages

### ISSUE THREAD

**Issue by nikolas** [gitlabhq/gitlabhq#9842]
I can't see any user pages on gitlab:
https://gitlab.com/u/mcfiredrill
https://gitlab.com/u/nikolas

They both stall for a minute, then show:

502

Whoops, GitLab is taking too much time to respond.

**Comment by j0k3r** [comment]
It works here.

**Comment by nikolas** [comment]
Working for me now too, but still slow.

**Comment by Razer6** [comment]
This is a known issue in the release candidate and will be fixed for the stable version.
