### ISSUE TITLE
Removing a project redirects to the project edit page

### ISSUE THREAD

**Issue by duffn** [gitlabhq/gitlabhq#9844]
Removing a project redirects to the project edit page which 404s.

- Create a new empty project
- Remove a project from the project settings page
- The project is successfully deleted, but the user is redirected to https://gitlab.com/user/project/edit

**Comment by tuminoid** [comment]
:+1:

**Comment by stanhu** [comment]
Thanks. Fix is here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1916
