### ISSUE TITLE
LDAP Config prefers "uid" for populating "username" field when new LDAP user logs in

### ISSUE THREAD

**Issue by badloop** [gitlabhq/gitlabhq#9845]
"uid" value from Active Directory is being used to populate the "username" field in the omnibus package.  This is less than desirable as we would prefer to have the username be either the sAMAccountName or the first part of the email address.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
