### ISSUE TITLE
7.14 dashboard not updating

### ISSUE THREAD

**Issue by andyzasl** [gitlabhq/gitlabhq#9848]
The problem rised after upgrade from 5.xx. (it was made about month ago)
Our system: 
```
bundle exec rake gitlab:env:info RAILS_ENV=production
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: already initialized constant Rouge::Lexers::Shell::KEYWORDS
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: previous definition of KEYWORDS was here
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: already initialized constant Rouge::Lexers::Shell::BUILTINS
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: previous definition of BUILTINS was here

System information
System:		CentOS 6.2
Current User:	git
Using RVM:	no
Ruby Version:	2.1.6p336
Gem Version:	2.2.3
Bundler Version:1.10.6
Rake Version:	10.4.2
Sidekiq Version:3.3.0

GitLab information
Version:	7.14.3
Revision:	d321305
Directory:	/home/git/gitlab
DB Adapter:	mysql2
URL:		https://git:80
HTTP Clone URL:	https://git:80/some-group/some-project.git
SSH Clone URL:	git@git:some-group/some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.6.5
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git

```

I've tried assets recompiling with no success. 

How to make it work back?

**Comment by andyzasl** [comment]
An update hook is exists in repos, and it is a symink to gitlab-shell/hooks/update

**Comment by andyzasl** [comment]
I've updated to 7.14, issue doent't fixed.

**Comment by stanhu** [comment]
Please try running `gitlab:check`:

```
bundle exec rake gitlab:check RAILS_ENV=production
```

**Comment by andyzasl** [comment]
'''
bundle exec rake gitlab:check RAILS_ENV=production
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: already initialized constant Rouge::Lexers::Shell::KEYWORDS
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: previous definition of KEYWORDS was here
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: already initialized constant Rouge::Lexers::Shell::BUILTINS
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: previous definition of BUILTINS was here
Checking GitLab Shell ...

GitLab Shell version >= 2.6.5 ? ... OK (2.6.5)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ...
<skipped projects with ok>
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
	/home/git/repositories: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.2
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Git configured with autocrlf=input? ... yes
Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ...
<all yes>
Projects have satellites? ...
<all yes>
Redis version >= 2.0.0? ... yes
Ruby version >= 2.1.0 ? ... yes (2.1.6)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.12)
Active users: 23

Checking GitLab ... Finished
'''

**Comment by stanhu** [comment]
I can't tell from this log whether the repositories have the right symlinks. Check that `hooks` points to `/home/git/gitlab-shell/hooks` directory.

**Comment by andyzasl** [comment]
It is

**Comment by andyzasl** [comment]
Updated 1st comment and title

**Comment by stanhu** [comment]
Can you check your Sidekiq log to see if the `PostReceive` task is even running after a push? Are there errors in any other log?

**Comment by andyzasl** [comment]
I've made: 
cat sidekiq.log | grep PostReceive

and got no output.

About errors:
the only error I see:

ActionView::Template::Error (wrong number of arguments (1 for 0)):
    1: %h4.prepend-top-20
    2:   %span.light Contributions for
    3:   %strong #{@calendar_date.to_s(:short)}
    4:
    5: %ul.bordered-list
    6:   - @events.sort_by(&:created_at).each do |event|
  app/views/users/calendar_activities.html.haml:3:in `to_s'
  app/views/users/calendar_activities.html.haml:3:in `_app_views_users_calendar_activities_html_haml___857401262_135087200'
  app/controllers/users_controller.rb:47:in `calendar_activities'

@production.log, and it seems to be not related to my issue

**Comment by stanhu** [comment]
It sounds like for some reason the post-receive hook isn't firing. Maybe there's a permission or executable error. I'm not sure if I can help any further. There is a lot more that can go wrong with source installations. If you can't debug the problem, I suggest converting to the omnibus version of GitLab.

**Comment by andyzasl** [comment]
A Hooks firectory of any repo is a symlink to 
/home/git/gitlab-shell/hooks
and there is 3 files: 

post-receive
pre-receive
update

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
