### ISSUE TITLE
ruby > 2.0 support in the update docu

### ISSUE THREAD

**Issue by vpaul** [gitlabhq/gitlabhq#9849]
I had been doing 7.x to 8.x update. According to update docu ruby 2.0 is still supported:

https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/6.x-or-7.x-to-7.14.md

"If you are you running Ruby 2.0.x, you do not need to upgrade ruby, but can consider doing so for performance reasons."

Though, I was getting ruby version caution message on running tests.

In the following 7.x->8.0 and 8.x pages ruby version is not mentioned but there was still the caution.

I stayed on 2.0 till 8.1 and things went just fine. But got it broken on 8.1->8.2 with a syntax issue in active support gem or so. 

Upgrade ruby to 2.1.x solved but I guess it should be mentioned in the docu 2.0.x support has been  dropped.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
