### ISSUE TITLE
Update to `v8.2.0.rc2`

### ISSUE THREAD

**Issue by waghanza** [gitlabhq/gitlabhq#9851]
I have downloaded `v8.0.2rc2`. When I run
~~~ruby
RAILS_ENV=production bundle exec rake db:migrate
~~~~
I have

~~~ruby
rake aborted!
LoadError: cannot load such file -- net/ssh
/home/git/gitlabhq/config/application.rb:6:in `<top (required)>'
/home/git/gitlabhq/Rakefile:5:in `require'
/home/git/gitlabhq/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
~~~

I have to manually add the `gem` **net-ssh** to my `Gemfile`

Regards,

PS : This is not an **issue* just a report :wink:

**Comment by stanhu** [comment]
Thanks. I think there is a pending fix for this:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1937
