### ISSUE TITLE
API should return more detailed data in JSON

### ISSUE THREAD

**Issue by danielyewright** [gitlabhq/gitlabhq#9852]
There should be a way to use the API to generate more detailed data in the returned JSON, such as:

- getting all projects and labels from milestones, and getting a milestone's percentage
- getting what project namespace an issue belongs to, not just the project id
- getting the milestone for each project and issue
- getting ALL projects, issues, and milestones across ALL users using a special private token
- getting all issues from any given project or milestone

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
