### ISSUE TITLE
I push new branch at VM but it not appers at dropdownmenu

### ISSUE THREAD

**Issue by dayiguizhen** [gitlabhq/gitlabhq#9853]
At first, I push new branch abcd.
![qq 20151125173947](https://cloud.githubusercontent.com/assets/9543865/11393589/7dfc282e-939b-11e5-9378-0f7fc368b8cc.jpg)

It was apper at http://gitlab.example.com/user/project/branches
![qq 20151125174026](https://cloud.githubusercontent.com/assets/9543865/11393623/b79454b2-939b-11e5-8760-20c64fe8ddf7.jpg)

But it doesn't appear at http://gitlab.example.com/user/project/tree/master dropdownmenu
![qq 20151125174041](https://cloud.githubusercontent.com/assets/9543865/11393677/035e43ee-939c-11e5-9416-87857e487e8b.jpg)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
