### ISSUE TITLE
File Finder Feature

### ISSUE THREAD

**Issue by koreamic** [gitlabhq/gitlabhq#9854]
I've been using Gitlab and I think it is awesome!!!.

As I know, Gitlab has no 'file finder' feature like Github
(https://github.com/blog/793-introducing-the-file-finder)

I read the following old article in your feedback.
(http://feedback.gitlab.com/forums/176466-general/suggestions/4987909-add-file-finder-fuzzy-input-in-files-tab-to-ju)

Using not the fuzzy logic but the regular expression, I developed the feature.

If I create a pull request, review my pull request?

**Comment by yms9654** [comment]
I think It is a very convenient feature.
I can find a file quick and instantly.

**Comment by stanhu** [comment]
@koreamic Yes, please submit a PR for this!
