### ISSUE TITLE
How to set header From in 'Emails on push' service

### ISSUE THREAD

**Issue by Alexhha** [gitlabhq/gitlabhq#9856]
Hello,

I'm currently using Gitlab 8.2.0 on CentOS 6. I have enabled 'Emails on push' service in project settings. When someone push changes to the project I receives email notification but in mail header FROM i see strange value - 'Administrator '. I'm not using 'Send from committer' options in the 'Emails on push' service.

```
Date: Wed, 25 Nov 2015 17:25:58 +0000
From: Administrator <example@example.net>
Reply-To: noreply@example.net
To: user@example.com
Message-ID: <5655ef266a5a3_4c7b133c8306186@ci.example.net.mail>
Subject: [Git][email/notifications-test][develop] 123
```

I have the following gitlab.rb settings
```
gitlab_rails['gitlab_email_enabled'] = true
gitlab_rails['gitlab_email_from'] = 'example@example.net'
gitlab_rails['gitlab_email_display_name'] = 'GITLAB-INFO'
gitlab_rails['gitlab_email_reply_to'] = 'noreply@example.net'
```

Is it possible to get in FROM header something like the following?
```
From: GITLAB-INFO <example@example.com>
```

Thanks in advance

**Comment by Alexhha** [comment]
Any advice?

**Comment by stanhu** [comment]
At the moment, this is not possible. The e-mail display name is always overwritten here by the name of the user who pushed the commit:

https://github.com/gitlabhq/gitlabhq/blob/master/app/mailers/notify.rb#L49

I think we could fix this by moving that line into the `if` block.

**Comment by stanhu** [comment]
At the same time, I can see why an admin would want to have the user's name in the "From" part of the address but hide the e-mail address, which is what GitLab does at the moment. I'm not sure a config option is warranted for this, though.

**Comment by Alexhha** [comment]
> The e-mail display name is always overwritten here by the name of the user who pushed the commit:
in such case what is purpose of the 'Send from committer' option? I mean what is difference between default behavior and with this option.

**Comment by stanhu** [comment]
This option includes the actual e-mail address of the committer. The default option may add something like `gitlab@domain`.

**Comment by Alexhha** [comment]
I got it. I think it would be great have ability to configure FROM header via gitlab.rb for example

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
