### ISSUE TITLE
Gem::LoadError in docker image gitlab-ce:latest(IMAGE ID ab7d0c35a701)

### ISSUE THREAD

**Issue by dayiguizhen** [gitlabhq/gitlabhq#9859]
1.docker run this image
2.config /etc/gitlab/gitlab.rb

     gitlab_rails['db_adapter'] = "mysql2"

3.docker restart gitlab

4.docker logs gitlab

error message:

    ==> /var/log/gitlab/unicorn/unicorn_stderr.log <==
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/connection_specification.rb:190:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)

**Comment by stanhu** [comment]
GitLab CE doesn't include MySQL support. I believe you either have to install from source or upgrade to EE.
