### ISSUE TITLE
Registering new user with email address matching the server email cause infinite sent emails

### ISSUE THREAD

**Issue by AkramBerkawy** [gitlabhq/gitlabhq#9862]
I have GitLab installed on local server, with email configured to Gmail SMTP.
I have registered new user with email address same as the GitLab server one, this has caused infinite email messages being sent from/to the email.
I have changed the user email from the web UI, but the email messages still being sent.
my second try was to restart the server, but it still sending the messages.
The massage:
> Subject: [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] [Rejected] Account was created for you
> "Unfortunately, your email message to GitLab could not be processed.
> We couldn't figure out what the email is in reply to. Please create your comment through the web   interface."

![image](https://cloud.githubusercontent.com/assets/3511510/11424468/2529ed1a-9456-11e5-8444-ed2feae233f0.png)

**Comment by Aymarick** [comment]
+1

**Comment by kitanata** [comment]
+1

**Comment by NicoJuicy** [comment]
+1

This is probably imap implementation behaviour / checks to map a user to an email. If i filter on myusername+gitlab+{key}@gmail.com then the emails on myusername@gmail.com are also getting "mapped" to gitlab. Which probably shouldn't be happening.

Then this error occurs.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Comment by boeserwolf** [comment]
+1
