### ISSUE TITLE
Commits listed in the wrong order on MR pages

### ISSUE THREAD

**Issue by rasapetter** [gitlabhq/gitlabhq#9863]
It seems the "Commits" tab on merge request pages can list the commits in the wrong order. Example: below is a screengrab from the page in question. Notice the hash on the commit named "bar", which according to the list should be the parent commit of "foo"
![Commit list in merge request](https://cloud.githubusercontent.com/assets/1532681/11426642/b5e3d468-945d-11e5-9201-346a793a4062.png)

... now let's check the hash of the actual parent of "foo":
![Actual parent](https://cloud.githubusercontent.com/assets/1532681/11426650/c3e3a002-945d-11e5-9c57-3187a0919226.png)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
