### ISSUE TITLE
API set number of approvals 

### ISSUE THREAD

**Issue by Dtsr** [gitlabhq/gitlabhq#9864]
Hello

Is there any way to set the number of approvers via API?

I need to update hundreds of projects every week and It would be great if it were possible via APi .

Thank you!

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
