### ISSUE TITLE
Cannot create merge request because it is already there..But nothing shows up in Merge requests

### ISSUE THREAD

**Issue by shravanshandilya** [gitlabhq/gitlabhq#9866]
But the Merge request is not there
![gitlab](https://cloud.githubusercontent.com/assets/6094424/11434849/436a67f2-94f9-11e5-8eb4-08aa114bd9c6.PNG)

**Comment by stanhu** [comment]
Is this a fork of another project? Are you sure you are looking at the merge requests for the target project?

**Comment by shravanshandilya** [comment]
Sorry..I was looking at the wrong project. Thanks for helping out !!
