### ISSUE TITLE
Can't backup?

### ISSUE THREAD

**Issue by vinkla** [gitlabhq/gitlabhq#9867]
I'm using GitLab CE 8.1.2 on a Debian system. While making a backup before updating to the latest version it failed. The first 20 projects worked just fine but then this happened: 
```bash
 * group/project_name ... [FAILED]
failed: tar -cf /data/tmp/backups/repositories/group/project_name.bundle -C /data/git/repositories/group/project_name.git .
tar: ./objects/1d/9ebd4b8440b1ad089609b0c7d8a3e7e29279eb: Cannot stat: Input/output error
tar: Exiting with failure status due to previous errors
Backup failed
```
This has never happened before. Have I done something wrong?

**Comment by stanhu** [comment]
It looks like the tar failed due to some disk/filesystem issue. Can you check if you can read that 9ebdxxx file?

**Comment by vinkla** [comment]
Thanks for getting back. Where is the file located? In the current directory? I can't find it there.

**Comment by stanhu** [comment]
It looks like in `/data/git/repositories/group/project_name.git`?

**Comment by vinkla** [comment]
When I try to `cat` it I get this in return:

```sh
$ cat ./objects/1d/9ebd4b8440b1ad089609b0c7d8a3e7e29279eb
cat: ./objects/1d/9ebd4b8440b1ad089609b0c7d8a3e7e29279eb: Input/output error
```

**Comment by stanhu** [comment]
Yes, that sounds like a disk or filesystem problem. You may want to run a scan (e.g. http://linoxide.com/how-tos/inputoutput-error-bad-blocks-how-to-restart-linux/).

**Comment by stanhu** [comment]
I'm going to close this issue because I don't think this is a GitLab-specific problem. Feel free to re-open if you find otherwise.

**Comment by vinkla** [comment]
Okay, thanks. I'll try it out.
