### ISSUE TITLE
Init-script says "everything up and running" even with gitlab-workhorse down.

### ISSUE THREAD

**Issue by okin** [gitlabhq/gitlabhq#9869]
The init-script says "everything up and running" even with gitlab-workhorse down.

To reproduce you need to make sure that the gitlab-workhose does not get started.

I would have expected that the final error message would not show that everything is up and running because the workhorse does not start.

It does say everything is "up and running" instead.

    # /etc/init.d/gitlab status
    The GitLab Unicorn web server with pid 10767 is running.
    The GitLab Sidekiq job dispatcher with pid 10826 is running.
    The gitlab-workhorse is not running.
    GitLab and all its components are up and running.

I am running v8.2.1 - e53c0c557275641210d596da0fd3bd3ac6f0bae2. This installation was created from source.

**Comment by okin** [comment]
For easy reproduction: Delete /home/git/gitlab-workhorse.
Then try to (re)start gitlab and let it report the status to you:

    # /etc/init.d/gitlab restart
    # /etc/init.d/gitlab status

**Comment by stanhu** [comment]
Thanks for reporting this. Does [this patch](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1969/diffs) solve the problem for you?

**Comment by okin** [comment]
@stanhu tested it and it works for me as expected.
Thank you!
