### ISSUE TITLE
Gitlab 8.2.1 - service is Down

### ISSUE THREAD

**Issue by starnetwork** [gitlabhq/gitlabhq#9870]
Hi,
I just installed gitlab in CentOS server, and it's working well
after we restart the gitlab service, it's up again, and after few hours / day, it's down again and need additional restart
[root@git1 ~]# service gitlab status
The GitLab Unicorn web server with pid 23939 is running.
The GitLab Sidekiq job dispatcher with pid 24008 is running.
The gitlab-workhorse with pid 23988 is running.
GitLab and all its components are up and running.
but still give 502 error
after: 
[root@git1 ~]# service gitlab restart
it's work again.

any suggestion?

**Comment by stanhu** [comment]
Can you check the logs in `/var/log/gitlab` to see if there are any reasons for the 502 error?

**Comment by starnetwork** [comment]
This is what I see in production.log:
Started GET "/" for 80.178.11.11 at 2015-11-30 07:43:40 -0500
Processing by RootController#index as HTML
no other relevant log, I will look for something in the next down (it's happen)

**Comment by starnetwork** [comment]
Hi,
now I got
E, [2015-12-01T10:25:17.009853 #13444] ERROR -- : worker=1 PID:13481 timeout (61s > 60s), killing
E, [2015-12-01T10:25:17.303090 #13444] ERROR -- : reaped #<Process::Status: pid 13481 SIGKILL (signal 9)> worker=1
web browser show 502
Whoops, GitLab is taking too much time to respond.
[root@git1 log]# service gitlab status
The GitLab Unicorn web server with pid 13444 is running.
The GitLab Sidekiq job dispatcher with pid 13526 is running.
The gitlab-workhorse with pid 13503 is running.
GitLab and all its components are up and running.

[root@git1 log]# service gitlab restart
and everything is working again
any Idea?

**Comment by stanhu** [comment]
For some reason, the GitLab worker is taking longer than 60 seconds to finish a request. Is there some sort of network or disk issue occurring?

**Comment by starnetwork** [comment]
1. no any network or disk issue, I check that
2. restart the gitlab service solve the issue so it's not network or disk
there is any way to restart each Unicorn / Sidekiq / gitlab-workhorse to isolate the issue?

Regards,

**Comment by stanhu** [comment]
Yes, if you are using omnibus you can run `gitlab-ctl restart sidekiq` to restart Sidekiq, for example.

Can you see if there is a specific request that is stalling out?

**Comment by starnetwork** [comment]
Hi,
1. it's installed from source, so
[root@git1 ~]# gitlab-ctl restart sidekiq
-bash: gitlab-ctl: command not found
2. no special request, just try to enter the login / main page of the git

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
