### ISSUE TITLE
Add changeset API 

### ISSUE THREAD

**Issue by apanasevich** [gitlabhq/gitlabhq#9871]
Gitlab CE supports diff API - /projects/:id/repository/commits/:sha/diff. It can be used to get changes.

But diff can has a very big size. For example i have a commit with diff more than 1G (.uasset files from Unreal Engine). When I try to find out wich files were changed I getting 504 Gateway Time-out (even via web UI, not only via API). I can't use .gitattributes due to https://gitlab.com/gitlab-org/gitlab-ce/issues/2315

It would be very useful to have API which allows to get list of changes files without dif.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
