### ISSUE TITLE
Impersonating blocked user logs you off

### ISSUE THREAD

**Issue by Baertierchen** [gitlabhq/gitlabhq#9872]
When trying to impersonate a user that is currently blocked, you end up being logged off. After logging back in with your own credentials, the button to stop impersonation appears even though you are logged in as yourself at this time.
Would be nicer if you were simply told that you can't impersonate blocked users and remain logged in.
That's on 8.2.1 tag.

**Comment by atomaka** [comment]
How about #9873 to fix this?  Along with alerting when a post request is made to impersonate a user, it prevents display of the Impersonate button altogether when a user is blocked.

**Comment by stanhu** [comment]
#9873 seems like a sensible approach.
