### ISSUE TITLE
User should be informed when personal project limit reached

### ISSUE THREAD

**Issue by vellamike** [gitlabhq/gitlabhq#9874]
When the personal project limit on gitlab is reached the '+' symbol for a new project simply disappears. The + symbol should remain and user should be informed that they can't add a new project and need to inform their admin. Otherwise it's pretty confusing to understand why you can't add a new personal project.

**Comment by atomaka** [comment]
I've implemented something close to your suggestion in #9876, @vellamike.  I'm not much of a designer so I'd love suggestions!

**Comment by atomaka** [comment]
This was resolved in #9876, @stanhu.

**Comment by Razer6** [comment]
Thanks
