### ISSUE TITLE
Storage analysis for repos

### ISSUE THREAD

**Issue by thorian93** [gitlabhq/gitlabhq#9875]
Hello there.
I have a feature request: 
I had the idea whether it would be a good idea to implement a way to analyse the storage consumption of files in a repository or at least of all the repositories on the server. This could be an user feature or maybe more fitting an admin feature to enable admins to spot storage-hungry repositories and investigate why they use that much storage.
I have no idea how hard it could be to implement such a feature but my research showed no results for a rejected or accepted issue on this topic so I just want to make this suggestion.
Thank you for your attention ;)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
