### ISSUE TITLE
Approval notifications

### ISSUE THREAD

**Issue by iiSeymour** [gitlabhq/gitlabhq#9877]
When a user is set as an approver for a merge request the number of open merge requests do not increment in the main nav or show up under the `/dashboard/merge_requests?assignee_id=<ID>` view. 

Can these views include both types of merge requests?

**Comment by dblessing** [comment]
Hi @iiSeymour 

We agree there needs to be more visibility in to merge requests that need approval. We have several proposals currently:

1. Send email notifications when your approval is needed.
1. Have a notification center/dashboard that shows assigned items, plus approvals.
1. Add a filter to merge request dashboard view to include approvals (as you request above). 

We will probably implement several, or all 3 of the above. There are at least 2 issues for this:

https://gitlab.com/gitlab-org/gitlab-ce/issues/3467
https://gitlab.com/gitlab-org/gitlab-ee/issues/42

We look forward to your input. Also, it appears you are an EE subscriber so don't hesitate to reach out to us using the support email address. You'll get faster response time and we will keep you updated on the progress of these features.

**Comment by iiSeymour** [comment]
I've been getting emails already about approval requests. I like the sound of option 2.

As this is an issue that affects all user *(all users using the approval feature that is)* and not just our gitlab instance I thought raising it here was more appropriate.

Thanks @dblessing.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
