### ISSUE TITLE
Relative Referencing in GitLab Flavor Markdown Problem in 8.x Release

### ISSUE THREAD

**Issue by Balgardner** [gitlabhq/gitlabhq#9878]
Updated GitLab from 7.x to current 8.x version recently and noticed a behaviour change in how relative references in links in Gitlab Flavor Markdown documents.

Some context... we have "wiki" projects that are simply normal projects in GitLab as opposed to the actual Wiki that may be created as a component of a regular project. 

Here is the typical structure for such a wiki project.

```
|- wiki-project
              |
              |- README.md (#1)
              |
              |- howtos (folder)
                 |
                 |- README.md (#2
                 |
                 |- howto-do-something (folder)
                    |
                    |- README.md (#3)
```

And in 'README.md' (#3) we have a line at the top of the file as follows:

```
[Home](/README.md) | [Howtos](/howtos/README.md) | [Howto Do Something](/howtos/howto-do-something/README.md)
```

In the 7.x GitLab this top line would produce a 'breadcrumb' menu to help the wiki-reader to navigate back up the document tree. Clicking on the 'Home' link would take them back to 'README.md' (#1).

In the 8.x GitLab clicking on the 'Home' link now takes the user to the 'README.md' (#3) instead. This is not the desired or expected behaviour and seems to be against the guidelines for how the GitLab Flavoured Markup should work.

Am thus raising this as a potential issue here.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
