### ISSUE TITLE
User do not add to owner when create new project

### ISSUE THREAD

**Issue by majeeddl** [gitlabhq/gitlabhq#9879]
when I create new project, I can not be owner of new project.would you help me?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
