### ISSUE TITLE
Can not push locally

### ISSUE THREAD

**Issue by IngwiePhoenix** [gitlabhq/gitlabhq#9880]
I have a Gitlab Omnibus setup sitting at the same server where I deploy. As a 1-coder-army, I don't need much more as of right now.

Previously I had set my remote to be the actual bare git repository path. Unfortunately, when I tried to push, I got the "No user or key provided" error. So I tried to use the HTTP method, but it would tell "code 22 returned" and stop.

I'd really like to be able to push locally too. Any help here? This is really confusing.

It's the same maschine as Gitlab, where my deploy is. I am at school and edited something in the remote setup and wanted to push the changes into the repo to pull them down later on my home laptop.

**Comment by IngwiePhoenix** [comment]
It works via SSH though...

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
