### ISSUE TITLE
can not create a global milestone with a chinese title 

### ISSUE THREAD

**Issue by LeoQuote** [gitlabhq/gitlabhq#9881]
Version : 8.2.2 
Installation : rpm

log comes as follow:

```
Started GET "/groups/ops-dev/milestones" for 127.0.0.1 at 2015-12-04 11:39:43 +0800
Processing by Groups::MilestonesController#index as HTML
  Parameters: {"group_id"=>"ops-dev"}
Completed 500 Internal Server Error in 301ms (ActiveRecord: 10.0ms)

ActionView::Template::Error (No route matches {:action=>"show", :controller=>"groups/milestones", :group_id=>#<Group id: 48, name: "ops-dev", path: "ops-dev", owner_id: nil, created_at: "2015-11-15 08:55:30", updated_at: "2015-12-02 06:23:26", type: "Group", description: "", avatar: "sha1.c71e73d51af1865c1bbbf6208e10044d46c9bb93.png", public: false>, :id=>"", :title=>"肯定不是中文的问题"} missing required keys: [:id]):
    2:   .row
    3:     .col-sm-6
    4:       %strong
    5:         = link_to_gfm truncate(milestone.title, length: 100), group_milestone_path(@group, milestone.safe_title, title: milestone.title)
    6:     .col-sm-6
    7:       .pull-right.light #{milestone.percent_complete}% complete
    8:   .row
  app/views/groups/milestones/_milestone.html.haml:5:in `_app_views_groups_milestones__milestone_html_haml___1698692825769553139_84176360'
  app/views/groups/milestones/index.html.haml:23:in `block in _app_views_groups_milestones_index_html_haml___3177571411688284649_85021260'
  app/views/groups/milestones/index.html.haml:22:in `each'
  app/views/groups/milestones/index.html.haml:22:in `_app_views_groups_milestones_index_html_haml___3177571411688284649_85021260'
```

I think it could be an error during searching process.

**Comment by stanhu** [comment]
Unfortunately, Milestone IDs/titles are only allowed to match the regexp `[a-zA-Z.0-9_\-]+(?<!\.atom)`, but no check was done when creating this global milestone. I think until full Unicode support can be made, the input form should reject that milestone title. In the meantime, you may have to go into the database and modify the invalid milestone title to get around the Error 500.

**Comment by stanhu** [comment]
Actually, I think you found a bug in the routing config. Milestones can have any character; it's just that group milestones have the wrong constraint. I think I have a fix.

**Comment by stanhu** [comment]
It looks like my first suspicion was correct. Global milestones are referenced via a sanitized title ( `title.parameterize`), which effectively only retains a-z, 0-9, or -.

**Comment by LeoQuote** [comment]
But I can create a milestone with a Chinese  title in every single project , but those milestones could be reached by milestone id like ``/milestones/1`` 
Thanks for your reply

**Comment by stanhu** [comment]
I think I figured it out:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1983
