### ISSUE TITLE
Animate progress-bar of milestone on drag and drop

### ISSUE THREAD

**Issue by flash1293** [gitlabhq/gitlabhq#9883]
It would be really nice if the progress bar in the milestone-view (project/milestones/1) would be animated to the new position when the user drags an issue into the completed column.

**Comment by phecho** [comment]
:+1:

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
