### ISSUE TITLE
changing unicorn port does not work

### ISSUE THREAD

**Issue by kilmarnock** [gitlabhq/gitlabhq#9885]
try this: 
nano /etc/gitlab/gitlab.rb
unicorn['port'] = 3456
sudo gitlab-ctl reconfigure
reboot as much as you can
nano /var/opt/gitlab/gitlab-rails/etc/unicorn.rb
listen "127.0.0.1:8080", :tcp_nopush => true

8080 is default and wrong

(ubuntu 14.4.3, installed today)

**Comment by kilmarnock** [comment]
works now gitlab 8.4.4-ce

**Comment by tholu** [comment]
Does not work in 8.5.1-ce, please reopen.

**Comment by kilmarnock** [comment]
Reopening the issue because tholu says so.
I would like to say that it would be helpful, if the (commented) value of the unicorn port would be the same as the used one. It is common to map the default port. No one wants to find out about communication of  a unicorn, we (the user) wants gitlab.

**Comment by kilmarnock** [comment]
I concern the bug as serious, because gitlab is broken every update, the error message does not point in this direction. The only reason you do not get a shitstorm is because most people use the default port. (do not run tomcat)

**Comment by maxlazio** [comment]
Have you seen the comment in https://github.com/gitlabhq/gitlabhq/issues/10060#issuecomment-190933339 ? The bug report was invalid.

**Comment by tholu** [comment]
Yeah, sorry about that, can be closed. Works fine (in 8.5.1-ce).
