### ISSUE TITLE
500 when editing the slack ci service

### ISSUE THREAD

**Issue by BridgeAR** [gitlabhq/gitlabhq#9886]
If I try to edit our slack service I'll always receive a 500 error. This issue exists for round about 4-8 weeks now.

You can reproduce the error by going into the project => settings => ci-services => slack => 500.

Our components are up to date:
```
GitLab 8.2.2
GitLab Shell 2.6.8
GitLab API v3
Ruby 2.1.7p400
Rails 4.1.12
```

```
Started GET "/A/B/ci_services/slack/edit" for nnn.nnn.nnn.nnn at 2015-12-04 16:19:38 +0100
Processing by Projects::CiServicesController#edit as HTML
Parameters: {"namespace_id"=>"A", "project_id"=>"B", "id"=>"slack"}
Completed 500 Internal Server Error in 29ms (ActiveRecord: 3.0ms)
ActionView::Template::Error (missing attribute: template):
50: .form-actions
51: = f.submit 'Save', class: 'btn btn-save'
52: &nbsp;
53: - if @service.valid? && @service.activated? && @service.can_test?
54: = link_to 'Test settings', test_namespace_project_ci_service_path(@project.namespace, @project, @service.to_param), class: 'btn'
app/models/service.rb:56:in `template?'
app/models/service.rb:41:in `block in <class:Service>'
app/views/projects/ci_services/_form.html.haml:53:in `block in _app_views_projects_ci_services__form_html_haml__1973048268800335643_62628600'
app/views/projects/ci_services/_form.html.haml:10:in `_app_views_projects_ci_services__form_html_haml__1973048268800335643_62628600'
app/views/projects/ci_services/edit.html.haml:2:in `_app_views_projects_ci_services_edit_html_haml___4067473617123527819_62600840'
```

**Comment by Razer6** [comment]
I cannot reproduce this issue on GitLab.com, which runs on 8.2.3. Can you ensure all migrations are up to date?. What's the output of the [status checks](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines)?

**Comment by mortzu** [comment]
https://gist.github.com/mortzu/b94004d94ce3aea24c85

**Comment by mortzu** [comment]
https://gist.github.com/mortzu/bb1bca727c36ef0e0528

**Comment by stanhu** [comment]
Can you check whether your `services` table in your DB has a `template` field? I wonder if somehow [this migration](https://github.com/gitlabhq/gitlabhq/blob/master/db/migrate/20150211172122_add_template_to_service.rb) didn't apply for some reason.

**Comment by mortzu** [comment]
template              | boolean                  | default false                                         | plain    |              |

**Comment by stanhu** [comment]
That's odd. I just tested this on omnibus GitLab 8.2.3 and had no issues. Have you tried a full reconfigure and restart of GitLab?

**Comment by mortzu** [comment]
Yes

**Comment by stanhu** [comment]
I would also run this on your database:

```sql
SELECT * FROM ci_services;
```

I'm particularly interested in knowing whether `type` is `CI::SlackService` for the service ID in question.

**Comment by mortzu** [comment]
https://gist.github.com/mortzu/7906a45e0cd2a5a7c633

**Comment by stanhu** [comment]
Somehow you are missing the migration (`20151210125232_migrate_ci_slack_service.rb`) that converts `SlackService` to `SlackService`. Have you made sure your database is up-to-date with all the migrations?

**Comment by stanhu** [comment]
Actually, the migration I mentioned doesn't actually move `SlackService` to `Ci::SlackService`. I'm curious how your database got into that state. I guess I would just run:

```sql
 UPDATE ci_services SET type = 'Ci::SlackService' where type = 'SlackService';
```

@ayufan, any ideas how this might have happened?

**Comment by mortzu** [comment]
Helped. Thanks a lot
