### ISSUE TITLE
Does Gitlab support Git LFS on raspberrypi?

### ISSUE THREAD

**Issue by yangxuan8282** [gitlabhq/gitlabhq#9887]
According to help documents in Gitlab, Git LFS is supported in GitLab starting with version 8.2.
And enabled by:

    Omnibus packages
    
    In /etc/gitlab/gitlab.rb:
     gitlab_rails['lfs_enabled'] = false
     gitlab_rails['lfs_storage_path'] = "/mnt/storage/lfs-objects"

But it seems like no such content on raspberry pi

**Comment by Razer6** [comment]
As far as i know there are no special limitations on for the RPi. @maxlazio Do you know any limitiations?

**Comment by yangxuan8282** [comment]
@Razer6 But I have not find **git lfs** in **gitlab.rb**

**Comment by tuminoid** [comment]
I also cannot enable LFS on an Ubuntu server, by following the documentation.
Clean install via omnibus package into a VM, plus following config at `/etc/gitlab/gitlab.rb`:

``` 
gitlab_rails['lfs_enabled'] = true
gitlab_rails['lfs_storage_path'] = "/opt/gitlab-lfs/lfs-objects"
```
followed by `gitlab-ctl reconfigure`.

Pushes result into:
```
$ git push
Git LFS: (0 of 1 files) 0 B / 2.19 MB                                                                                              
exit status 1
error: failed to push some refs to 'git@10.0.3.234:root/test.git'
```
Error message is exactly same whether LFS is enabled or not.

Using git 2.7.1 and git-lfs 1.1.1 on Trusty.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
