### ISSUE TITLE
404 on removing a project

### ISSUE THREAD

**Issue by glmax** [gitlabhq/gitlabhq#9890]
When you want to remove a project in its settings (`/<owner>/<project>/edit`) and confirm the pop-up (where you have to enter the project's name), the project is deleted but you're not redirected to a different site automatically. Since the project is gone, the current site `/<owner>/<project>/edit` does not exist anymore so you're getting a 404.

I think you should be redirected to `/<owner>` or the dashboard.

**Comment by Razer6** [comment]
This has been fixed with [8.2.3](https://github.com/gitlabhq/gitlabhq/blob/master/CHANGELOG#L19)
