### ISSUE TITLE
Add number of attempts to webhooks

### ISSUE THREAD

**Issue by SteveEdson** [gitlabhq/gitlabhq#9893]
We currently have an issue with our webhooks. 

They are time sensitive, but when they do not get a 200 response, they seem to be backing off and trying again at a later time.

It would be useful to have the time of the first webhook, and the number of attempts, available in the payload, so that we can tell if the webhook is too old to do anything with.

Unless there is a way of disabling the queued webhooks behaviour altogether?

Thanks.

**Comment by stanhu** [comment]
There isn't a way out of the box to disable Sidekiq's retry mechanism, but you could do it if you were willing to [patch the workers](https://github.com/mperham/sidekiq/wiki/Error-Handling#configuration).

If your Web hook handler takes more than 10 seconds to respond, the retry will happen. You can increase this timer via the `webhook_timeout` option. It's probably a better practice to make your handler return 200 right away, however.
