### ISSUE TITLE
Add git.io-like short urls

### ISSUE THREAD

**Issue by hellboy81** [gitlabhq/gitlabhq#9895]
Please add short `url`s support (aka `git.io`) for links to comment notes

```
http[s]://gitlab.xxx.yyy/path/to/gitlab/project/commit/da39a3ee5e6b4b0d3255bfef95601890afd80709#note_NNNN
```

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
