### ISSUE TITLE
Using "apache" syntax highlighting in markdown corrupts the HTML converted output

### ISSUE THREAD

**Issue by m47z0r** [gitlabhq/gitlabhq#9896]
When using the "apache" syntax highlighting modifier in code blocks:

    ~~~apache

..., what should look like this:

~~~apache
<Location /srv/bla>
    #Enable Subversion
	DAV svn
    AuthType Basic
    AuthBasicProvider ldap
    Require valid-user
</Location>
~~~

... will become this in Gitlab HTML converted markdown:
~~~apache
<Location /srv/bla>
    #Enable Subversion
     svn
    AuthType Basic
     ldap
    Require valid-user
</Location>
~~~

As you can see, some words are just cut off instead of being highlighted.

Tried with Gitlab v8.2.0 and v8.2.2 installed from https://packages.gitlab.com/gitlab/gitlab-ce on CentOS 7.

**Comment by Razer6** [comment]
GitLab is using [rouge](https://github.com/jneen/rouge) for syntax highlighting. Since this is a bug is within rouge, please open an issue on their tracker. I reproduced this using rouge [here](http://rouge.jneen.net/pastes/qO3)
