### ISSUE TITLE
There doesn't appear to be a way to create public snippets that can be viewed without a user having to login

### ISSUE THREAD

**Issue by BrianGilbert** [gitlabhq/gitlabhq#9899]
**Summary:** When you create a public snippet, a user accessing the link is still prompted to log into the gitlab instance, this isn't what I would expect public to mean.  
  

**Steps to reproduce:** Make a public snippet, navigate to /explore/snippets as an un-authenticated user and you will see the snippet listed, when you click on the link to view the snippet you will be asked to sign in.  

  
**Expected behavior:** clicking a public snippet link displays the snippet without having to log in  

  
**Observed behavior:** Currently public snippets still require login to access  

  
**Notes:**  
Remaining issues from the original implementation..  

- We'd really like to see the ability to get a public url without using a user based token, it's really annoying to have to create a read only user and add the user to every repo just so you can have public snippet links out in the wild that aren't using the token from your own personal account.  
https://github.com/gitlabhq/gitlabhq/issues/1031#issuecomment-6930063  

- there doesn't appear to be a way to have a global token without adding a user to every project  
https://github.com/gitlabhq/gitlabhq/issues/1031#issuecomment-7386201

**Comment by axilleas** [comment]
Closing in favor of https://gitlab.com/gitlab-org/gitlab-ce/issues/3982
