### ISSUE TITLE
Options like Sign-up enabled or Sign-in enabled are not saved

### ISSUE THREAD

**Issue by JrCs** [gitlabhq/gitlabhq#9901]
Hi,
i'am using the omnibus version of gitlab-ce 8.2.2, and when i change the options (the checkboxes) of **Sign-up enabled** or **Sign-in enabled** in the admin/settings page then click to the save button the options are not saved: they stay always enabled.

![gitlab-issue2](https://cloud.githubusercontent.com/assets/83008/11713263/97564af0-9f32-11e5-9ab2-4109c09a28b5.png)

**Comment by bensagardoy** [comment]
I have the same issue with a brand new omnibus version of gitlab on a VPS (Ubuntu 14.04)

**Comment by stanhu** [comment]
This was fixed in GitLab 8.2.3:

https://about.gitlab.com/2015/12/10/gitlab-8-dot-2-dot-3-released/
