### ISSUE TITLE
No workhorse socket. The requested URL returned error: 502

### ISSUE THREAD

**Issue by MelonSmasher** [gitlabhq/gitlabhq#9902]
When I try to pull or clone over https I get a 502 error.

```shell
root@gitlab:gitlab:# ls tmp/sockets/
gitlab-git-http-server.socket  gitlab.socket
```

```shell
root@gitlab:gitlab:# cat /etc/nginx/conf.d/gitlab-ssl.conf
## GitLab
##
...
upstream gitlab {
  server unix:/home/git/gitlab/tmp/sockets/gitlab.socket fail_timeout=0;
}

upstream gitlab-workhorse {
  server unix:/home/git/gitlab/tmp/sockets/gitlab-workhorse.socket fail_timeout=0;
}
...
```

I've noticed that nginx is looking for a socket that does not exist how do I fix this. I went through the update docs again and still no workhorse socket.

I've also got this issue open on [gitlab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues/4003)

**Comment by vinkla** [comment]
+1 I'm having the same issue?

**Comment by vinkla** [comment]
I've just pointed it against the old socket file for the time being.

```
upstream gitlab-workhorse {
  server unix:/home/git/gitlab/tmp/sockets/gitlab-git-http-server.socket fail_timeout=0;
}
```

Now it works fine but it doesn't match the documentation.

**Comment by stanhu** [comment]
Closing this issue in favor of the discussion on https://gitlab.com/gitlab-org/gitlab-ce/issues/4003.

**Comment by vinkla** [comment]
@stanhu :+1:
