### ISSUE TITLE
Gitlab support crowd sso?

### ISSUE THREAD

**Issue by surmountli** [gitlabhq/gitlabhq#9903]
I can login in gitlab from crowd .But sso is not working.The crowd.token_key is not sent to crowd .
if login jira first, gitlab auth dos not use crowd.token_key .
Gitlab 7.12 
omniauth_crowd (2.2.3)
crowd 2.7

**Comment by songnous** [comment]
surmountli,you solved? now.I face this problem,can you give some suggestion?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
