### ISSUE TITLE
Branches view showing "merged" when the branch hasn't been merged

### ISSUE THREAD

**Issue by artlepool** [gitlabhq/gitlabhq#9908]
I've created a branch from master, but I've not created a merge request yet.  I've not committed anything to the branch yet either.

However, as per attached screenshot (I've blanked bits of the text out), the branches list has a "merged" tag next to the name of the branch, which I'm finding very confusing..

Why would it say "merged" if I haven't even created a merge request?  And should it offer me the opportunity to create a Merge Request anyway (via the button) if it is saying that the branch has already been merged?

Thanks!

![image](https://cloud.githubusercontent.com/assets/8647257/11785244/bfe2e660-a278-11e5-852b-a838ef06bf0d.png)

**Comment by artlepool** [comment]
So I've just pushed a commit to my branch, and the confusing "merged" tag has disappeared. 

It looks like it is incorrectly reporting "merged" when it is a new branch and there haven't been commits.  At this point the branch is effectively the same as master so maybe this is confusing GitLab?

**Comment by stanhu** [comment]
Yes, this is confusing GitLab. The "merged" tag appears when both `master` and your branch have the same merge base, which is true in this case. I'm not sure how you would distinguish a branch that has just been merged versus one that was just pushed, though.

**Comment by stanhu** [comment]
Closing this for now unless someone has ideas how to solve this.
