### ISSUE TITLE
With the introduction of 'award emojis' merge request listing no longer shows approvals

### ISSUE THREAD

**Issue by brejoc** [gitlabhq/gitlabhq#9909]
Before the introduction of award emojis in version 0.8.3, the merge request listing also listed the number of approvals/votes the specific merge request received. Now you have to open the merge request to see if the number of approvals is met.
With a large number of merge requests this is a very tedious task.

**Comment by stanhu** [comment]
Yes, this is planned for 8.5. Closing in favor of this issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/3673
