### ISSUE TITLE
Administrator cannot add oneself to an exist group

### ISSUE THREAD

**Issue by gaoyifan** [gitlabhq/gitlabhq#9916]
When a administrator add oneself to an exist group, it shows success, but have no effect.

GitLab 8.2.3
GitLab Shell 2.6.8
GitLab API v3
Ruby 2.1.7p400
Rails 4.1.12

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
