### ISSUE TITLE
Creating Repository using ssh

### ISSUE THREAD

**Issue by tm-linkwerk** [gitlabhq/gitlabhq#9919]
Sometimes I have only a shell with my ssh keys and want to quickly create a project in gitlab. I do not want to open the browser and login to create a project or need to figure out how to securely handle an api key. 

Is there already a way to create a project with only my ssh keys as credentials?

**Comment by stanhu** [comment]
You could create a project within your user's namespace/group. Would that work?

**Comment by tm-linkwerk** [comment]
How can I do that with ssh?

**Comment by stanhu** [comment]
Can you use `curl` in your SSH session? Then you could use the API:

http://doc.gitlab.com/ce/api/projects.html

**Comment by tm-linkwerk** [comment]
Then I would have to securely handle the api key somehow, what I want to avoid, as I already have SSH credentials. 
I thought of something like ssh git@gitlab --exec create-repo namespace/project.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
