### ISSUE TITLE
API for Label Ids

### ISSUE THREAD

**Issue by LutherBaker** [gitlabhq/gitlabhq#9920]
I'd like to track when LABELS are changed. Unfortunately, the REST endpoint for PROJECT LABELS doesn't seem to include label ids. On the flip side, when changing labels or tags on a issue, the REST endpoint for NOTES returns something like _Added ~114 and removed ~113 labels_ - which, I assume are LABEL ids.

Is there anyway to determine, with the API, when labels are applied and removed without first, identifying and hard-coding LABEL ids?

**Comment by stanhu** [comment]
At the moment, there isn't a way of doing this. You could argue that that there should be an API endpoint that returns both plain and Markdown versions of the text (e.g. https://developer.github.com/v3/markdown/).

**Comment by LutherBaker** [comment]
Thanks Stan. While it certainly seems odd to me that LABELS are impossible to track within a project via the API, I have no real context from which to understand the direction of the API so I don't think I will formalize the functionality request.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
