### ISSUE TITLE
Notes inconsistency with updating

### ISSUE THREAD

**Issue by stevepeak** [gitlabhq/gitlabhq#9923]
When updating notes, without providing `Content-Type: multipart/form-data`, the `PUT` results in `400` missing body argument (even when provided).

Here is how you replicate using Python.

```python
# Failes
import requests
res = requests.put('https://gitlab.com/api/v3/projects/187725/merge_requests/59639/notes/3006211', 
                   headers={'Authorization': 'Bearer TOKEN'}, data='body=hello+world')
print res.text
>>> {"message":"400 (Bad request) \"body\" not given"}

# Works
res = requests.put('https://gitlab.com/api/v3/projects/187725/merge_requests/59639/notes/3006211', 
                   headers={'Authorization': 'Bearer TOKEN', 'Content-Type': 'multipart/form-data'}, data='body=hello+world')
print res.status_code
>>> 200
```

GitLab API's should assume `multipart/form-data` when no `Content-Type` header is provided. The API does accept requests from other endpoints when no `Content-Type` header is provided, as far as I've experienced it is only the **Update Notes** endpoint.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Comment by stevepeak** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/17954
