### ISSUE TITLE
Highlighting of comment in SQL snippet is incorrect if comment is on last line

### ISSUE THREAD

**Issue by duffn** [gitlabhq/gitlabhq#9925]
If there is a comment in a SQL snippet on the last line of the snippet, the comment is highlighted as regular code and not as a comment.

https://gitlab.com/snippets/11711

GitLab Enterprise Edition 8.3.0.rc3-ee d7313ff at gitlab.com

![screen shot 2015-12-21 at 2 00 07 pm](https://cloud.githubusercontent.com/assets/3457341/11941223/3fb87f9a-a7eb-11e5-9f80-54db110aee8f.png)

**Comment by stanhu** [comment]
This looks like a bug in [Rouge](https://github.com/jneen/rouge). I just tested this [here](http://rouge.jneen.net/). Can you file an issue there?

**Comment by duffn** [comment]
You were able to replicate this on the Rouge test site? It appears to work there.
http://rouge.jneen.net/pastes/GzY

**Comment by stanhu** [comment]
Interesting: without the newline, I see the same issue:

![image](https://cloud.githubusercontent.com/assets/963826/11980289/b2acf3aa-a94e-11e5-8c95-4d511b81c934.png)

**Comment by duffn** [comment]
You're right, it's only without a newline. I've opened the issue with Rouge.

https://github.com/jneen/rouge/issues/360
