### ISSUE TITLE
incorrect display of the control buttons in issues list

### ISSUE THREAD

**Issue by blackprojects** [gitlabhq/gitlabhq#9926]
This bug when you in project issues (not when you in list with all projects issues)

Chrome 47.0.2526.106
Firefox 42.0
IE 11

![1](https://cloud.githubusercontent.com/assets/9135963/11951901/2adcfe20-a8ae-11e5-9585-cdf9e75c3c05.png)
![2](https://cloud.githubusercontent.com/assets/9135963/11951900/2adc9cb4-a8ae-11e5-8fe6-b119a1ff9c0e.png)

**Comment by stanhu** [comment]
Looks like this happens when you shrink the width of the browser. I think the right behavior is to hide some of the dropdowns (e.g. Weight, Label) when the width becomes too small.

/cc: @jschatz1

**Comment by blackprojects** [comment]
my resolution of monitor is 1366, i think it is not small ...

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
