### ISSUE TITLE
GitLab VM Page goes to 404

### ISSUE THREAD

**Issue by praveenscience** [gitlabhq/gitlabhq#9927]
Hi,

I was planning to get the GitLab installation on my Vagrant. But when I came across: https://github.com/gitlabhq/gitlabhq/wiki/VirtualBox-Image, the link doesn't exists and navigates to 404 page of GitHub. Kindly advice.

Cheers,
**Praveen Kumar**

**Comment by phecho** [comment]
+1
I have the same problem.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
