### ISSUE TITLE
Provide info if MR is approvable in API response

### ISSUE THREAD

**Issue by Great-Antique** [gitlabhq/gitlabhq#9929]
We have own integration system and one of the steps in our integration work flow is a creating build from MR last version and a testing it. So we need to know is MR is approvable or has a merging conflicts to start or not to start a build creating and/or change issue status.

Maybe is it possible to checkout locally MR? Like from github https://gist.github.com/piscisaureus/3342247

**Comment by stanhu** [comment]
The API currently doesn't support this, but I think you could easily add a variable to `lib/api/entities.rb` to export the `check_if_can_be_merged` flag in the given merge request.

Checking out a local MR is a good idea. That's supported at the moment, however, and would probably involve more work.

**Comment by Great-Antique** [comment]
@stanhu thanks for answering. I will try to add that variable.

You wrote `That's supported at the moment...`, so this functionality is present in GitLab now, isn't it? If yes - please provide me a link to docs. I can't find anything about it. As I see GitLab CI runs a build creating on MR creating and every push to the source branch, but GitLab CI is unsuitable for us.

**Comment by stanhu** [comment]
@Great-Antique Sorry, I meant it's not supported at the moment.

**Comment by Great-Antique** [comment]
PR #9994 

I think in this case `mergeable?` param is better than `check_if_can_be_merged` because you can't merge MR if it's not mergeable (you will get `405 Method Not Allowed` even if MR passes `check_if_can_be_merged`)

**Comment by rymai** [comment]
@Great-Antique This has been added to the [MergeRequest API](http://doc.gitlab.com/ce/api/merge_requests.html#get-single-mr) as a new `merge_status` attribute: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2756 (it'll be shipped in `8.5.0` and is already available in `8.5.0-rc1`)!

I think that should cover your use-case, if not, feel free to re-open this issue. :)

**Comment by b0nd0** [comment]
guys, i am using GitLab Community Edition 8.13.2, and the issue still there. Can you reopen this, or should i create new issue?
