### ISSUE TITLE
Wikilinks does not work in preview

### ISSUE THREAD

**Issue by MDXDave** [gitlabhq/gitlabhq#9930]
<s>I am on a subpage with the following address: 
__``http://gitlab.example.com/group/project/wikis/APIv2/foo``__

If I add an links to an wiki article: ``[Link description](APIv2/bar)`` the link points to __``http://gitlab.example.com/group/project/blob/master/APIv2.1/bar``__</s>

Wikilinks does not work in Preview

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
