### ISSUE TITLE
How does GitLab CI caching work?

### ISSUE THREAD

**Issue by kahwee** [gitlabhq/gitlabhq#9933]
I'm a little confused how cache works and am not able to take advantage of it well. Can you see if I did anything wrong?

I previously cache (with untracked set to true) two directories at global level -- `node_modules/` and `dist/`

Subsequently, I decided that cache `dist/` is a bad idea and removed it.

Now, when I push an update and a rebuild occurs, I noticed `dist/` is always in the cache together with `node_modules` no matter what.

Is there any way I can get rid of `dist/` being cached?

Thanks.

**Comment by grzesiek** [comment]
Hi @kahwee. Thanks for the report. I think that this is a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/5540. Can you take a look? We will track issue on GitLab, so subscribe to issue 5540 on GitLab to be notified about solution.

**Comment by kahwee** [comment]
Thanks @grzesiek I'll close this.
