### ISSUE TITLE
User calendar contribution not updated for imported project

### ISSUE THREAD

**Issue by magic890** [gitlabhq/gitlabhq#9934]
Using GitLab 8.2.3 CE the user calendar contribution doesn't update for imported project.
How can this be fixed?

**Comment by magic890** [comment]
Same behaviour also on GitLab 8.3.1 CE.

**Comment by stanhu** [comment]
You would have to modify the importer to populate the `events` table. You could also write a separate rake script that did this.

**Comment by magic890** [comment]
Ok I'll try to do this.
I'm having a first look into this project. Can you kindly point me out where the importer is implemented and where is the current implementation to populate the `events` table after a post-receive action?

**Comment by stanhu** [comment]
The Sidekiq worker that imports projects is in `app/workers/repository_import_worker.rb`. `app/services/event_create_service.rb` handles the creation of new events. You can see how the latter is used in `app/services/git_push_service.rb`.

**Comment by JaviSabalete** [comment]
Same issue here with Gitlab 8.3.4 CE

**Comment by jfarsen** [comment]
Is this non-updating of the contribution calendar also standard behavior for gitlab.com ?

**Comment by magic890** [comment]
@jfarsen I think so, it's the same software running.

**Comment by magic890** [comment]
@stanhu If I've used [Import Any repo by URL](https://github.com/gitlabhq/gitlabhq/blob/master/lib/gitlab/import_sources.rb#L23), where is the related importer? Is it `lib/gitlab/git/hook.rb`?

I can figure out that the other importers are located under `lib/gitlab/IMPORTERNAME_import/`.

I've looked through the sources, I saw that you [generate an Event inside a Service class](https://github.com/gitlabhq/gitlabhq/blob/master/app/services/git_push_service.rb#L55), so I think that the best approach is to generate an event inside the `Importer` class, where the task is run. In this case I've to modify all the importers. Do you think there will be a better approach?

I can use the available events, like [CREATED and PUSHED](https://github.com/gitlabhq/gitlabhq/blob/master/app/models/event.rb#L21) or create a new one `IMPORTED`. According to this creating also the a new method `import_project` inside the [EventCreateService](https://github.com/gitlabhq/gitlabhq/blob/master/app/services/event_create_service.rb#L65)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
