### ISSUE TITLE
How can i add updater name in mail body?

### ISSUE THREAD

**Issue by imkevinyang** [gitlabhq/gitlabhq#9935]
since gitlab doesn't support exchange server to show updater display name (support in IMAP mode or non-exchange server), i want to add updater name in mail body as following:

    Kevin Yang says:
        make some changes in issue.
        add label 'feature'

i try to edit \app\views\layouts\notify.html.haml, add '#{@updated_by.name}', but updated_by is not recognized. How can i do that?

**Comment by stanhu** [comment]
This change was reverted in d60047bb312.

**Comment by imkevinyang** [comment]
May i ask why? i dont know why is this commit reverted?? exchange server doesnt support 'display name in sender field, so we can only fallback to display name in mail body.

**Comment by stanhu** [comment]
The commit was reverted mostly because it had unnecessary quotes, but for most users the `From:` part of the e-mail already contained the author of the issue.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
