### ISSUE TITLE
Image check version GitLab in Admin Area not working on Safari

### ISSUE THREAD

**Issue by magic890** [gitlabhq/gitlabhq#9940]
Due to this problem:

    [Error] Failed to set referrer policy: The value 'origin-when-cross-origin' is not one of 'no-referrer', 'origin', 'no-referrer-when-downgrade', or 'unsafe-url'. Defaulting to 'no-referrer'. (admin, line 7)`

the image `check.png` is not displayed (`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (check.png, line 0)`)

![Screen shot GitLab check version image broken on Safari](https://cloud.githubusercontent.com/assets/1352670/12063130/84190176-afa9-11e5-93cf-7c0c424bfc15.png)

**Comment by tsigo** [comment]
Closing in favor of https://gitlab.com/gitlab-org/gitlab-ce/issues/5609
