### ISSUE TITLE
Gitlab docker: SSL connection error

### ISSUE THREAD

**Issue by sisso19** [gitlabhq/gitlabhq#9944]
I am deploying a gitlab on my private server and have deployed it successfully but only with http.
Today I have been trying to set up a https connection with gitlab but it has been unsuccessfull

I followed the step by step instructions [as described here](https://github.com/sameersbn/docker-gitlab#ssl)

my docker compose file looks like this:

    postgresql:
      restart: always
      image: sameersbn/postgresql:9.4-11
      environment:
        - DB_USER=usr
        - DB_PASS=pass
        - DB_NAME=temporary_stuff
      volumes:
        - /var/docker/gitlab/postgresql:/var/lib/postgresql
    gitlab:
      restart: always
      image: sameersbn/gitlab:8.3.2
      links:
        - redis:redisio
        - postgresql:postgresqli
      external_links:
        - mailserver_mail_1:maili
      ports:
        - "10080:80"
        - "10443:443"
        - "10022:22"
      environment:
        - DEBUG=true
        - TZ=GMT
        - GITLAB_TIMEZONE=GMT
        - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
        - GITLAB_HOST=myHost
        - GITLAB_PORT=10443
        - GITLAB_SSH_PORT=10022
        - GITLAB_RELATIVE_URL_ROOT=
       # I added these two lines to the docker-compose file
        - GITLAB_HTTPS=true
        - SSL_SELF_SIGNED=true
    # to here
        - DB_ADAPTER=postgresql
        - DB_HOST=postgresqli
        - DB_NAME=temporary_stuff
        - DB_USER=usr
        - DB_PASS=pass
        - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
        - GITLAB_NOTIFY_PUSHER=false
        - GITLAB_EMAIL=notifications@example.com
        - GITLAB_EMAIL_REPLY_TO=noreply@example.com
        - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com
        - GITLAB_BACKUP_SCHEDULE=daily
        - GITLAB_BACKUP_TIME=01:00
        - SMTP_ENABLED=true
        - SMTP_DOMAIN=www.google.com
        - SMTP_HOST=smtp.gmail.com
        - SMTP_PORT=587
        - SMTP_USER=myemail@myemail.com
        - SMTP_PASS=mypass
        - SMTP_STARTTLS=true
        - SMTP_AUTHENTICATION=login
        - IMAP_ENABLED=false
        - IMAP_HOST=imap.gmail.com
        - IMAP_PORT=993
        - IMAP_USER=mailer@example.com
        - IMAP_PASS=password
        - IMAP_SSL=true
        - IMAP_STARTTLS=false
      volumes:
        - /var/docker/gitlab/gitlab:/home/git/data
    redis:
      restart: always
      image: sameersbn/redis:latest
      volumes:
        - /var/docker/gitlab/redis:/var/lib/redis

I tried to find some logs but the docker-compose logs did not have any information.
Please let me know if you need more information. I will provide them
Any help is appreciated.

**Comment by stanhu** [comment]
Please file any questions with Sameer's docker-gitlab in that repo. That Docker image is not officially supported by GitLab here.

**Comment by sisso19** [comment]
Thank you. will do
