### ISSUE TITLE
LDAP multiple domain, not server, login error

### ISSUE THREAD

**Issue by illuminated** [gitlabhq/gitlabhq#9947]
I run a Kolab service on a separate VM from GitLab and have set multiple dev domains there.
I cannot configure GitLab to search the login user in several domains on the same Kolab Groupware server, i.e. ou=People,dc=mydomain1,dc=com and ou=People,dc=mydomain2,dc=com. 
I have tried with setting only 'ou=People', putting wildcards, using LDAP search operator (|(ou=...,dc=..)(ou...)) and many other things, but without luck.
This is the current configuration that works with one domain (which is also the main, parent domain of the Kolab configuration):

```
gitlab_rails['ldap_enabled'] = true
gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' # remember to close this block with 'EOS' below
  main: # 'main' is the GitLab 'provider ID' of this LDAP server
    label: 'LDAP'
    host: 'my.host.com'
    port: 389
    uid: 'mail'
    method: 'plain' # "tls" or "ssl" or "plain"
    bind_dn: 'uid=kolab-service,ou=Special Users,dc=mydomain1,dc=com'
    password: 'mypassword'
    active_directory: false
    allow_username_or_email_login: false
    block_auto_created_users: false
    base: 'ou=People,dc=mydomain1,dc=com'
    user_filter: ''
```

Is there any way to set the 'base' parameter so I could login with users from multiple domains (but on the same LDAP server)?

**Comment by illuminated** [comment]
In the meantime, I have tried with different bind_dn credentials (using Kolab's cn=Directory Manager), leaving the base dn blank with user filter set, but no success yet,

Is there an option to use wildcards (variables) in defining the base dn and how?

There are applications utilising Kolab's multidomain authentication by defining the base dn as "ou=People,%dc", or similar, but none of those seem to work with omniauth. When I check the Kolab's log file on LDAP I see that GitLab sends the entire string as set in config.

**Comment by just-bank** [comment]
Make base to be empty:
```base: ''```
And set a user_filter by specifing attribute all users have. Like:
```user_filter: '(accountStatus=active)'```
It will search entire directory (all dcs), so if you have multiple domains it will run through all of them until it finds a correct one.
I have domain.com and domain.net - some users using .com as main and .net as alias, and some users other way around - both can login and gitlab picks up correct record.

**Comment by illuminated** [comment]
Unfortunately, it doesn't work with Kolab... My domains have all the same tld, but the second level is different.

**Comment by dnepangue** [comment]
@just-bank how about for your bind_dn: ? what dc= did you used?. Sorry this is an old thread but I just came across with this issue. Thanks

**Comment by just-bank** [comment]
@dnepangue our LDAP server is Zimbra mail server, so bind_dn:
``bind_dn: 'uid=zimbra,cn=admins,cn=zimbra'``
and it have no domain, as uid zimbra is unique and have global admin privs.

**Comment by dnepangue** [comment]
@just-bank I followed your suggestion to make base empty. But im quite confused as to what my bind_dn: would be. Here is what i have tried.

`host: '192.168.1.1'
        port: 636
        uid: 'uid'
        method: 'ssl' 
        bind_dn: 'CN=Manager,DC=companyA,DC=com'
        password: 'secret'

       allow_username_or_email_login: true
       base: ' '
       user_filter: '(accountStatus=active)'
`

For the dc, i do both have DC=companyA,DC=com and DC=companyB,DC=com.

**Comment by just-bank** [comment]
You have to have a "global admin" which can be found without specifying the "DC" part.

So for you it should look like something like this:
```
host: '192.168.1.1'
        port: 636
        uid: 'uid'
        method: 'ssl' 
        bind_dn: 'uid=globaladmin,cn=Manager'
        password: 'secret'

       allow_username_or_email_login: true
       base: ''
       user_filter: '(accountStatus=active)'
```
Where `uid=` will have a UID for your admin which have access to both companies.
You will have to provide a full path, here is my "zimbra" admin with the tree:

![zimbra_tree](https://cloud.githubusercontent.com/assets/2356834/14811594/68ac716c-0ba1-11e6-9177-c79e20b0d904.png)

In bind_dn I specify it like: `bind_dn: 'uid=zimbra,cn=admins,cn=zimbra'`
And it have a full access to all domains (1 - dot com, 2 - dot io, 3 - dot online).

**Comment by dnepangue** [comment]
Thank you @just-bank I'll try it.

**Comment by dnepangue** [comment]
@just-bank I think this will not work in my case, I have a separated ldap database per domain. In your setup it's just on one database right?

**Comment by just-bank** [comment]
> In your setup it's just on one database right?

Yeap.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
