### ISSUE TITLE
ActionView::Template::Error (undefined method `title' for nil:NilClass)

### ISSUE THREAD

**Issue by rujews** [gitlabhq/gitlabhq#9948]
giltab：7.14.3
url ：/gitlab/android/MyMoney/merge_requests

这个错误和merge request列表数据有关，有的会出现这个错误，有的不会。
我该怎么修复数据，进而修复这个问题？

the error log ：
```
ActionView::Template::Error (undefined method `title' for nil:NilClass):
    42:       &nbsp;
    43:       %span
    44:         %i.fa.fa-clock-o
    45:         = merge_request.milestone.title
    46:     - if merge_request.tasks?
    47:       %span.task-status
    48:         = merge_request.task_status
  app/views/projects/merge_requests/_merge_request.html.haml:45:in `_app_views_projects_merge_requests__merge_request_html_haml___654517899785029668_69986447076400'
  app/views/projects/merge_requests/_merge_requests.html.haml:3:in `_app_views_projects_merge_requests__merge_requests_html_haml__3166995607600430249_69986443199900'
  app/views/projects/merge_requests/index.html.haml:14:in `_app_views_projects_merge_requests_index_html_haml__186508081203370897_69986441374200'
  app/controllers/projects/merge_requests_controller.rb:36:in `index'
```

**Comment by rujews** [comment]
是因为丢失了两个milestones导致出现了问题，修复了就好了，现关了这个issue

**Comment by lydiadai** [comment]
请问您是怎么解决的啊？我也出现了相同的问题。。这是我的error log
ActionView::Template::Error (undefined method `title' for nil:NilClass):
    16:       <% @posts.each do |post| %>
    17:         <tr>
    18:           <td> <%= post.content %> </td>
    19:           <td> <%= post.group.title %> </td>
    20:           <td> <%= post.updated_at %> </td>
    21:           <td> <%= link_to('Edit', edit_group_post_path(post.group, post), class: "btn btn-default btn-xs") %></td>
    22:           <td> <%= link_to('Delete', group_post_path(post.group, post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-xs") %></td>
