### ISSUE TITLE
When initilazing with the gui a new project, no info on how to start, clone etc come

### ISSUE THREAD

**Issue by dummys** [gitlabhq/gitlabhq#9951]
Hi,

When I create a new empty project with create empty bare repositiory, I have not the informational page who explain how to connect to this repo, how to clone and how to push code inside.
Where can I find log if something is wrong ? I checked in the log folder but get no error. No error is displayed on the page. in production.log:

==> production.log <==
Completed 200 OK in 58ms (Views: 29.2ms | ActiveRecord: 4.3ms)
Started POST "/dummys/test/repository" for 127.0.0.1 at 2016-01-06 14:22:32 +0100
Processing by Projects::RepositoriesController#create as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "namespace_id"=>"dummys", "project_id"=>"test"}
Redirected to http://127.0.0.1:10000/dummys/test
Completed 302 Found in 839ms (ActiveRecord: 2.9ms)
Started GET "/dummys/test" for 127.0.0.1 at 2016-01-06 14:22:33 +0100
Processing by ProjectsController#show as HTML
  Parameters: {"namespace_id"=>"dummys", "id"=>"test"}
Completed 200 OK in 69ms (Views: 39.6ms | ActiveRecord: 4.5ms)

No error in nginx too.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
