### ISSUE TITLE
Webhook accepted HTTP response status code

### ISSUE THREAD

**Issue by Bonscho** [gitlabhq/gitlabhq#9956]
Webhooks should not only accepts status code 200 in HTTP responses but the whole range between 200 and 299 – 200, 201 and 202 minimum.

**Comment by narfbg** [comment]
Would you believe it - I encountered this issue yesterday and came here to report it, only to see someone beat me to it an hour ago, lol.

+202 ;)

**Comment by stanhu** [comment]
Submitted a fix for this: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2332
