### ISSUE TITLE
Editing labels for a merged merge request requires manual URI editing

### ISSUE THREAD

**Issue by sharwell** [gitlabhq/gitlabhq#9965]
Suppose you have a merge request which gets merged. You now want to change the label(s) associated with the merge request. Unfortunately, after the merge request is merged, the Edit button is no longer present, so changes to labels requires the following steps:

1. Observe that the merge request URI is https://{server}/{user}/{project}/merge_requests/{id}
2. Manually navigate to https://{server}/{user}/{project}/merge_requests/{id}/edit (I added `/edit` to the end of the previous URI)
3. Assign the labels

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
