### ISSUE TITLE
Error executing action `run` on resource 'bash[migrate gitlab-rails database]'

### ISSUE THREAD

**Issue by MattMuffin** [gitlabhq/gitlabhq#9966]
Hello,

While trying to upgrade from 8.1.2 to8.2.2 or 8.3.3 or 8.3.4, i get the following error:

Recipe: gitlab::unicorn
  * service[unicorn] action restart
    - restart service service[unicorn]
Recipe: gitlab::sidekiq
  * service[sidekiq] action restart
    - restart service service[sidekiq]
Recipe: gitlab::gitlab-rails
  * execute[clear the gitlab-rails cache] action run
    - execute /opt/gitlab/bin/gitlab-rake cache:clear
Recipe: gitlab::database_migrations
  * bash[migrate gitlab-rails database] action run
    

Error executing action `run` on resource 'bash[migrate gitlab-rails database]'
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "bash"  "/tmp/chef-script20160112-25385-17vq5ed" ----
    STDOUT: rake aborted!
    StandardError: An error has occurred, this and all later migrations canceled:
    
    Index name 'index_tags_on_name' on table 'tags' already exists/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/schema_statements.rb:800:in `add_index_options'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/schema_statements.rb:438:in `add_index'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:413:in `method_missing'
    /opt/gitlab/embedded/service/gitlab-rails/db/migrate/20150425164648_add_missing_unique_indices.acts_as_taggable_on_engine.rb:4:in `up'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:565:in `up'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:605:in `exec_migration'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
    ArgumentError: Index name 'index_tags_on_name' on table 'tags' already exists
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/schema_statements.rb:800:in `add_index_options'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/schema_statements.rb:438:in `add_index'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:413:in `method_missing'
    /opt/gitlab/embedded/service/gitlab-rails/db/migrate/20150425164648_add_missing_unique_indices.acts_as_taggable_on_engine.rb:4:in `up'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:565:in `up'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:605:in `exec_migration'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
    /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
    Tasks: TOP => db:migrate
    (See full trace by running task with --trace)
    == 20150425164648 AddMissingUniqueIndices: migrating ==========================
    -- add_index(:tags, :name, {:unique=>true})
    STDERR: 
    ---- End output of "bash"  "/tmp/chef-script20160112-25385-17vq5ed" ----
    Ran "bash"  "/tmp/chef-script20160112-25385-17vq5ed" returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/definitions/migrate_database.rb
    
     19:   bash "migrate #{params[:name]} database" do
     20:     code <<-EOH
     21:       set -e
     22:       log_file="/tmp/#{params[:name]}-db-migrate-$(date +%s)-$$/output.log"
     23:       umask 077
     24:       mkdir $(dirname ${log_file})
     25:       #{params[:command]} 2>& 1 | tee ${log_file}
     26:       exit ${PIPESTATUS[0]}
     27:     EOH
     28:     action params[:action]
     29:     params[:restarts].each do |svc|
     30:       notifies :restart, svc, :immediately
     31:     end
     32:   end
     33: end'
    
    Compiled Resource:
    ------------------
    # Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/definitions/migrate_database.rb:19:in `block in from_file'
    
    bash("migrate gitlab-rails database") do
      params {:command=>"/opt/gitlab/bin/gitlab-rake db:migrate", :action=>:nothing, :restarts=>["service[unicorn]", "service[sidekiq]"], :name=>"gitlab-rails"}
      action [:nothing]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      command "migrate gitlab-rails database"
      backup 5
      returns 0
      code "      set -e\n      log_file=\"/tmp/gitlab-rails-db-migrate-$(date +%s)-$$/output.log\"\n      umask 077\n      mkdir $(dirname ${log_file})\n      /opt/gitlab/bin/gitlab-rake db:migrate 2>& 1 | tee ${log_file}\n      exit ${PIPESTATUS[0]}\n"
      interpreter "bash"
      declared_type :bash
      cookbook_name "gitlab"
      recipe_name "database_migrations"
    end
    

Running handlers:
[2016-01-12T22:20:58+01:00] ERROR: Running exception handlers
Running handlers complete
[2016-01-12T22:20:58+01:00] ERROR: Exception handlers complete
Chef Client failed. 14 resources updated in 15.0634757 seconds
[2016-01-12T22:20:58+01:00] FATAL: Stacktrace dumped to /opt/gitlab/embedded/cookbooks/cache/chef-stacktrace.out
[2016-01-12T22:20:58+01:00] ERROR: bash[migrate gitlab-rails database] (gitlab::database_migrations line 19) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20160112-25385-17vq5ed" ----
STDOUT: rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_tags_on_name' on table 'tags' already exists/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/schema_statements.rb:800:in `add_index_options'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/schema_statements.rb:438:in `add_index'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:413:in `method_missing'
/opt/gitlab/embedded/service/gitlab-rails/db/migrate/20150425164648_add_missing_unique_indices.acts_as_taggable_on_engine.rb:4:in `up'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:565:in `up'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:605:in `exec_migration'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
ArgumentError: Index name 'index_tags_on_name' on table 'tags' already exists
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/schema_statements.rb:800:in `add_index_options'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/schema_statements.rb:438:in `add_index'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:413:in `method_missing'
/opt/gitlab/embedded/service/gitlab-rails/db/migrate/20150425164648_add_missing_unique_indices.acts_as_taggable_on_engine.rb:4:in `up'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:565:in `up'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:605:in `exec_migration'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
== 20150425164648 AddMissingUniqueIndices: migrating ==========================
-- add_index(:tags, :name, {:unique=>true})
STDERR: 
---- End output of "bash"  "/tmp/chef-script20160112-25385-17vq5ed" ----
Ran "bash"  "/tmp/chef-script20160112-25385-17vq5ed" returned 1
[2016-01-12T22:20:59+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
dpkg: error processing package gitlab-ce (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 gitlab-ce

I've tried installing through the repo and through the manual download of the .deb file.

I'm on Ubuntu 15.04 (vivid) and installed the trusty packages

**Comment by MattMuffin** [comment]
A precision: I've ran some tests on a dedicated VM. I installed v8.1.2 from .deb file and then installed 8.3.4 also from .deb file: no issue.

I recreated a VM, reinstalled v8.1.2 from .deb, restored a v8.1.2 backup, installed the 8.3.4 from .deb and was able to reproduce the error.

My conclusion: there is some field in the backup DB that triggers the error. How can I solve this issue?

**Comment by daald** [comment]
Exactly the same error here, while trying to upgrade from 7.14.3-ce.1 to 8.4.4-ce.0. The problem exists already longer, I set gitlab package on hold when 8.1.? was out because of this error. Reason is probably a mysql->pgsql migration, the 32bit to 64bit migration or this earlier bug which was never solved: #2412

**Comment by daald** [comment]
I solved my issue by manually deleting the index:

    sudo -u gitlab-psql /opt/gitlab/embedded/bin/psql -h /var/opt/gitlab/postgresql/ gitlabhq_production
    drop index index_tags_on_name;
    \q

Then, manually start the migration

    sudo gitlab-rake db:migrate RAILS_ENV=production

test the installation:

    sudo gitlab-rake gitlab:check

**Comment by MattMuffin** [comment]
Hello daal,

Thanks for the hint. Here is what I've got:

# sudo -u gitlab-psql /opt/gitlab/embedded/bin/psql -h /var/opt/gitlab/postgresql/ gitlabhq_production 
could not change directory to "/root"
psql (9.2.10)
Type "help" for help.

gitlabhq_production=# help
You are using psql, the command-line interface to PostgreSQL.
Type:  \copyright for distribution terms
       \h for help with SQL commands
       \? for help with psql commands
       \g or terminate with semicolon to execute query
       \q to quit
gitlabhq_production=# drop index index_tags_on_name;
ERROR:  index "index_tags_on_name" does not exist
gitlabhq_production=# \q

Any idea how to solve this issue?

**Comment by MattMuffin** [comment]
Hello,

FWIW, I've solved the issue by doing the following:

 sudo -u gitlab-psql /opt/gitlab/embedded/bin/psql -h /var/opt/gitlab/postgresql/ gitlabhq_production 
 drop index taggings_idx;
 alter table tags drop taggings_count;
 \q

then

 sudo gitlab-rake db:migrate RAILS_ENV=production

I hope it helps ! Thanks daald for pointing me out in the right direction

**Comment by daald** [comment]
@MattMuffin Are you sure you deleted the right index? The exception above shows a different name..

**Comment by MattMuffin** [comment]
@daald true, but when i did it with 8.4.4, it was not the same name as previously shown.
