### ISSUE TITLE
MRs created from UI and API are different

### ISSUE THREAD

**Issue by klausbayrhammer** [gitlabhq/gitlabhq#9967]
When creating a merge request with an empty description the behavior is different whether this is done via the gitlab UI or the REST-API.

If I create the MR via the UI and query `https://gitlab.com/api/v3/projects/1/merge_request/1?private_token=xxxx` the description is an empty string.
If I create the MR via the REST-API and do not set the description param e.g.
```bash
 curl -X POST --data-urlencode "source_branch=$currentBranch" \
        --data-urlencode "target_branch=master" \
    --data-urlencode "title=$lastCommitsSubject" \
    --data-urlencode "private_token=$privateToken" \
    https://gitlab.com/api/v3/projects/$projectId/merge_requests
```
and query the MR with `https://gitlab.com/api/v3/projects/1/merge_request/1?private_token=xxxx` the description is null.

It would be nice if the behavior would be the same in both cases - since this also causes problems in jenkinsci/gitlab-plugin#179

Gitlab version: Gitlab 8.2.2-ee

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
