### ISSUE TITLE
Search issues with unicode uppercase symbols

### ISSUE THREAD

**Issue by mr-dxdy** [gitlabhq/gitlabhq#9971]
Example:

```
issue = create(:issue, title: "привет")
Issue.search('Привет').count
# => 0
```

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
