### ISSUE TITLE
Editing then cancel throws a 404

### ISSUE THREAD

**Issue by CJStroud** [gitlabhq/gitlabhq#9972]
I edited a readme on a project then pressed cancel and it threw a 404 error.

On this project I don't have write access to the project so it set the target branch as patch-1. When I pressed cancel it tried to go to {project-name}/blob/patch-1/readme.md, however obviously patch-1 isn't a branch because I cancel the edit.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
