### ISSUE TITLE
Link to a patch download in issue comment is damaged

### ISSUE THREAD

**Issue by fcelda** [gitlabhq/gitlabhq#9973]
When a link to a commit formatted as a patch is inserted into an issue comment, the link gets damaged. For instance, if I insert the following plain text as a comment:

```
Please, try the following patch:
https://gitlab.com/gitlab-org/gitlab-ce/commit/710659fc1fe73e4feffdb3fbb14f4098bb58046c.patch
```

I will get something like this:
```
Please, try the following patch: 710659fc1.patch
```

The commit ID is a link, the .patch isn't. The link points to the location without the .patch suffix:
`https://gitlab.com/gitlab-org/gitlab-ce/commit/710659fc1fe73e4feffdb3fbb14f4098bb58046c`

Adding the link explicitly using `[url](url)` doesn't work as well.

I'm using GitLab Community Edition 8.3.4 5916670.

**Comment by oerdnj** [comment]
Probably applies to .diff links as well.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
