### ISSUE TITLE
Automatically create issues from code review commit comments

### ISSUE THREAD

**Issue by stepan-romankov** [gitlabhq/gitlabhq#9974]
Is to some how possible to code reviewer to track comments for commit? My proposal is to have an option which can automatically create issues from comments and assign them to committer.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
