### ISSUE TITLE
relative_url_root doesn't recompile assets under new root

### ISSUE THREAD

**Issue by jbaxley** [gitlabhq/gitlabhq#9975]
after configuring everything as per the documentation, using the omnibus package just fyi, I'm able to see the webpages and even the CSS sheets are being pulled properly - however the icons are nothing but squares and when I look at the developer tools for chrome I can see that the url used to retreive the fonts didn't include the new root path.

**Comment by maxlazio** [comment]
Omnibus-gitlab package will support relative_url starting with 8.5 packages. All packages prior to that one do not support it. Let us know if you experince issues after install ing the 8.5 package in [the omnibus-gitlab issue tracker](https://gitlab.com/gitlab-org/omnibus-gitlab/issues).
