### ISSUE TITLE
Registering to GitLab with GitHub account lead to 404 route + posting an issue leads to 422

### ISSUE THREAD

**Issue by petetnt** [gitlabhq/gitlabhq#9979]
Crossposting from https://github.com/dear-github/dear-github/issues/56#issuecomment-171905394 //cc @DouweM 

I went on to register to GitLab.com with my GitHub account. When chose to register with my GitHub account it lead me to GitHub.com's `Authorize application` OAUTH page as expected. When I allowed the application, it redirected me to an route on GitLab.com that had something do with my avatar. 

The URL was something like like `https://gitlab.com/oauth/avatar/foo/bar/765432.png`, which was a 404 page / route. I don't have the exact URL at hand because it didn't get tagged to my browser history for some reason. When I went to GitLab.com again, however, I was successfully logged in as `petetnt`.

I went on to create an issue about it to https://gitlab.com/gitlab-com/support-forum/issues/ (Which I hope was the correct repo...), but everytime I clicked Submit an issue it lead me to an 422 page (?) that had no further explanations why. 

Thanks for the prompt feedback @DouweM :+1:

**Comment by DouweM** [comment]
Thanks @petetnt! The first issue sounds like a faulty redirect-after-sign-in, but I'm not sure why an avatar path would end up being saved as such. I will look into it.

The second issue I can't explain. As you can see on https://gitlab.com/gitlab-com/support-forum/issues, other people managed to submit an issue as little as 27 minutes ago. Could you try again and share the request and response header with me?

**Comment by petetnt** [comment]
@DouweM tried it again and now the issue went through just fine: 
https://gitlab.com/gitlab-com/support-forum/issues/503

I think there might have been some other issues in general at that time, I mentioned on dear-github/dear-github#56 and navigating with history lead me to an broken state where the site wasn't responding to at all but the `history.state` changed correctly. After I refreshed couple of times everything seemed to be back to normal. :ghost: 

Sorry for the vague descriptions with everything, those were kinda one off situations that are rather hard to replicate.

**Comment by petetnt** [comment]
Now that I think about it I might not have added my password yet before trying to post the issue if that could be culprit?

**Comment by DouweM** [comment]
> Now that I think about it I might not have added my password yet before trying to post the issue if that could be culprit?

That shouldn't matter, OAuth accounts (like those that login using GitHub) don't require a password. It is only required if you want to use Git-over-HTTP.

> Sorry for the vague descriptions with everything, those were kinda one off situations that are rather hard to replicate.

Yeah :) I'll look into the avatar-redirect issue, and we'll pretend those other things didn't happen until we can replicate it and get some more information on the circumstances.

**Comment by petetnt** [comment]
Sounds good to me :+1:

**Comment by DouweM** [comment]
@petetnt Since it sounds like you're trying out GitLab for the first time, I would really appreciate it if you would take the time to report anything that you think can be improved on https://gitlab.com/gitlab-org/gitlab-ce/issues :)

**Comment by petetnt** [comment]
Will do! I am sort of familiar with the layout as I have browsed repos before on GitLab but I hadn't registered until today.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
