### ISSUE TITLE
Close merge request  button doesn't work

### ISSUE THREAD

**Issue by jlgasparrini** [gitlabhq/gitlabhq#9981]
I use [gitlab.com](gitlab.com) and when try to close the merge request, this doesn't work!
Please check that!

![screen shot 2016-01-15 at 2 26 29 pm](https://cloud.githubusercontent.com/assets/4787484/12360041/3d9a95e2-bb94-11e5-94d6-73747f9a54b3.png)

Thanks advance.

**Comment by duduribeiro** [comment]
Worked here for me, 
<img width="805" alt="screen shot 2016-01-24 at 3 26 26 am" src="https://cloud.githubusercontent.com/assets/771411/12534852/5aa3dc18-c24a-11e5-8ca3-2419fb3cfd76.png">

Can u check the console/network log from your browser?  Maybe it is something strange on the requests :)

**Comment by axilleas** [comment]
Hey people! This is fixed in latest 8.4 and also in GitLab.com :)

**Comment by jlgasparrini** [comment]
I really appreciate it ^^

Thanks
