### ISSUE TITLE
Configuration values containing a single quote break the app

### ISSUE THREAD

**Issue by narfbg** [gitlabhq/gitlabhq#9982]
I don't know if this is only relevant to omnibus packages (that's what I use, and every other help resource refers to gitlab.yml instead of gitlab.rb), but the LDAP password I have to use happens to contain the single quote character.

I've tried escaping it via a backslash, or using double quotes around the value, but no matter what I put into /etc/gitlab.rb, after running `gitlab-ctl reconfigure`, the resulting (already parsed) string value is just shoved into */opt/gitlab/embedded/service/gitlab-rails/config/gitlab.yml* with a single quote on each side and nothing else.

For example, if I were to do this:

    # /etc/gitlab.rb
    gitlab_rails['ldap_password'] = "foo'bar"

I would get this:

    # /opt/gitlab/embedded/service/gitlab-rails/config/gitlab.yml
      ldap:
        password: 'foo'bar'

Naturally, that triggers a syntax error ...

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
