### ISSUE TITLE
raw snippets in dos format

### ISSUE THREAD

**Issue by port22** [gitlabhq/gitlabhq#9983]
snippets downloaded via curl/wget etc are saved in dos format, which is a problem when you want to execute the snippet as a bash script for example:

> bash: ./script.sh: /bin/bash^M: bad interpreter: No such file or directory

Is there any way within gitlab to change/configure that?
The later use of dos2unix is not really applicable when use automatic scripting and multiple scripts.

github gists will be downloaded correctly in unix format, btw.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
