### ISSUE TITLE
errors while restoring on CentOS7

### ISSUE THREAD

**Issue by sandrodz** [gitlabhq/gitlabhq#9985]
Hi, my ubuntu server died (hardware failure) so I'm reinstalling everything. This time I've decided to try centOS.

In any case, restore: ```sudo gitlab-rake gitlab:backup:restore BACKUP=1452369792``` seems to have finished successfully, but I see some errors in the log:

```
DROP INDEX
DROP INDEX
ERROR:  index "index_on_users_lower_username" does not exist
ERROR:  index "index_on_users_lower_email" does not exist
ERROR:  index "index_on_projects_lower_path" does not exist
ERROR:  index "index_on_namespaces_lower_path" does not exist
DROP INDEX
DROP INDEX
DROP INDEX
```

```
DROP SEQUENCE
DROP TABLE
ERROR:  must be owner of extension plpgsql
ERROR:  must be owner of schema public
ERROR:  schema "public" already exists
ALTER SCHEMA
ERROR:  must be owner of schema public
CREATE EXTENSION
ERROR:  must be owner of extension plpgsql
SET
SET
```

```
CREATE INDEX
WARNING:  no privileges could be revoked for "public"
REVOKE
WARNING:  no privileges could be revoked for "public"
REVOKE
WARNING:  no privileges were granted for "public"
GRANT
WARNING:  no privileges were granted for "public"
GRANT

```

can these be ignored? or is this something serious?

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
