### ISSUE TITLE
FreeBSD: can't modify frozen ActiveSupport::HashWithIndifferentAccess at setup

### ISSUE THREAD

**Issue by t-zuehlsdorff** [gitlabhq/gitlabhq#9986]
Hello,

i am porting GitLab to FreeBSD and we did major progress in the last month. But we have one problem left, the above error message. Here with a trace:

```
Adding limits to schema.rb for mysql
** Invoke setup_postgresql (first_time)
** Invoke environment 
** Execute setup_postgresql
-- execute("CREATE INDEX CONCURRENTLY index_on_namespaces_lower_path ON namespaces (LOWER(path));")
   -> 0.0040s
-- execute("CREATE INDEX CONCURRENTLY index_on_projects_lower_path ON projects (LOWER(path));")
   -> 0.0134s
-- execute("CREATE INDEX CONCURRENTLY index_on_users_lower_username ON users (LOWER(username));")
   -> 0.0029s
-- execute("CREATE INDEX CONCURRENTLY index_on_users_lower_email ON users (LOWER(email));")
   -> 0.0231s
** Invoke db:seed_fu (first_time)
** Invoke environment 
** Execute db:seed_fu

== Seed from /usr/local/www/gitlab/db/fixtures/production/001_admin.rb
rake aborted!
can't modify frozen ActiveSupport::HashWithIndifferentAccess
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:46:in `eval'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/hash_with_indifferent_access.rb:227:in `delete'
/usr/local/lib/ruby/gems/2.1/gems/default_value_for-3.0.0.1/lib/default_value_for.rb:169:in `block in set_default_values'
/usr/local/lib/ruby/gems/2.1/gems/default_value_for-3.0.0.1/lib/default_value_for.rb:152:in `each'
/usr/local/lib/ruby/gems/2.1/gems/default_value_for-3.0.0.1/lib/default_value_for.rb:152:in `set_default_values'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:228:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `block in call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `each'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_initialize_callbacks'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/core.rb:284:in `initialize'
/usr/local/lib/ruby/gems/2.1/gems/default_value_for-3.0.0.1/lib/default_value_for.rb:142:in `initialize'
/usr/local/lib/ruby/gems/2.1/gems/devise-3.5.3/lib/devise/models/confirmable.rb:57:in `initialize'
/usr/local/lib/ruby/gems/2.1/gems/state_machines-activerecord-0.3.0/lib/state_machines/integrations/active_record.rb:454:in `initialize'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/inheritance.rb:61:in `new'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/inheritance.rb:61:in `new'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:80:in `find_or_initialize_record'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:62:in `seed_record'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:36:in `block (2 levels) in seed'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:36:in `map'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:36:in `block in seed'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/seeder.rb:35:in `seed'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/active_record_extension.rb:32:in `seed'
(eval):9:in `block (2 levels) in run_file'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:46:in `eval'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:46:in `block (2 levels) in run_file'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:58:in `block in open'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:57:in `open'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:57:in `open'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:36:in `block in run_file'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:35:in `run_file'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:26:in `block in run'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:25:in `each'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:25:in `run'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/seed-fu.rb:29:in `seed'
/usr/local/lib/ruby/gems/2.1/gems/seed-fu-2.3.5/lib/tasks/seed_fu.rake:36:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/www/gitlab/lib/tasks/gitlab/setup.rake:20:in `setup_db'
/usr/local/www/gitlab/lib/tasks/gitlab/setup.rake:4:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:seed_fu
```

I do not have any further ideas how to deal with this error. Or fix it. Can someone please help? 

Greetings,
Torsten

**Comment by t-zuehlsdorff** [comment]
Hello,

this problem still stands, which is sad, because it is the only blocker to get GitLab to FreeBSD :(

What is needed to get somebody a look at it? I can provide a test-server with root-access if you misses FreeBSD (but sadly only with IPv6), documentation is up to date and many persons want to help. 

So i am pushing the topic ;)

Greetings,
Torsten

**Comment by stanhu** [comment]
This doesn't look like a FreeBSD-specific issue. It looks like the seed_fu module is attempting to create a default admin account but somehow failing. Can you add debug statements (e.g. `puts "start1") to see where exactly it's failing in `/usr/local/www/gitlab/db/fixtures/production/001_admin.rb`? What version of ruby are you using?

**Comment by stanhu** [comment]
Looks similar to this issue: https://github.com/mbleigh/acts-as-taggable-on/issues/580

**Comment by t-zuehlsdorff** [comment]
Hello Stan,

i'm sorry for the delay. I'm currently in vacation but back on monday.

In short to your questions:
The failing statement is the line: "admin = User.create( .."
Ruby Version is 2.1.8.

How could i debug this further to help you?

Greetings,
Torsten

**Comment by t-zuehlsdorff** [comment]
Hello Stan,

back from vacation i go through the similar issues, the trace and some more. Good news: the error is gone! :)
After upgrading default_value_for from 3.0.0.1 to 3.0.1 the setup works correctly. 

Finally - this was a show-stopper for the last 2 month. :(

BTW: i'm working to get GitLab integrated into FreeBSD since last August. I'm not the first one, but the first with a working solution. Is there anybody at gitlab.org i can speak to as maintainer for Gitlab-FreeBSD?
I would like to ask some basic questions about configuration. Also it is easier to prepare future changes if i already know them. Or if i get a notice about a new version, etc.

There is already a documentation to get GitLab work on FreeBSD:
https://github.com/t-zuehlsdorff/gitlabhq/blob/8-5-docu/doc/install/installation-freebsd.md

If there is anyway to make FreeBSD a full supported platform in the future this would be very good.

Greetings,
Torsten

**Comment by stanhu** [comment]
@t-zuehlsdorff Great, glad you got that to work. There is no official support or maintainer for GitLab-FreeBSD yet. Given the limited number of users who currently use FreeBSD, I have a feeling that won't change anytime soon. If you have any general questions about configuration, you can try the GitLab IRC channel or post issues on GitLab.com.

I'll close this issue out unless you have further issues.

**Comment by t-zuehlsdorff** [comment]
@stanhu 
I did not express myself correct:
From the point of FreeBSD i am the maintainer of GitLab. I would like to work together with the GitLab team to add official support for FreeBSD. There are quite a number of persons interested in getting GitLab on FreeBSD and some users and developers are already participating into GitLab to make this work.

But thanks for the pointer. I will have a look at the IRC channel in time.

**Comment by stanhu** [comment]
@t-zuehlsdorff Oh, I misunderstood your message. Thanks for volunteering. I'll refer you to @dosire and @JobV; perhaps you can discuss this further.

**Comment by JobV** [comment]
Interesting @t-zuehlsdorff! Any place we can follow your work? cc @maxlazio

**Comment by stanhu** [comment]
This looks like a good place:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202468

**Comment by t-zuehlsdorff** [comment]
@JobV  @maxlazio 

@stanhu provided already the correct link:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202468

Also after i did get GitLab running yesterday i started a "call for testers" at the mailinglist:
https://lists.freebsd.org/pipermail/freebsd-ports/2016-February/102209.html

I already get some feedback via email and fix some errors, which are already incorporated in the PR linked above.

If you want to see my work in progress you can also follow my gitlab-project:
https://github.com/t-zuehlsdorff/freebsd-ports/
There is a special branch "gitlab". This project is the freebsd-portstree and will allow a user installing gitlab with a simple "make install" and much less configuration than the original source installation.

You will see the difference when comparing:
https://github.com/gitlabhq/gitlabhq/blob/v8.5.0/doc/install/installation.md
and
https://github.com/t-zuehlsdorff/gitlabhq/blob/8-5-docu/doc/install/installation-freebsd.md

Most work is done automatically :)

Feel also free to contact my via email at ports@toco-domains.de

Greetings,
Torsten

**Comment by dosire** [comment]
Thanks for working on this Torsten!

**Comment by maxlazio** [comment]
@t-zuehlsdorff Cool! If you require some assistance please raise an issue on [GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce) and mention me. I have notification filters for emails from there so  when mentioned I can respond (eventually) :)

**Comment by t-zuehlsdorff** [comment]
@JobV  @dosire  @stanhu  @maxlazio 
Just for your information: since yesterday there is a native support in FreeBSD:
http://www.freshports.org/www/gitlab
:)

It is currently 8.5, but just for the reason we want to get gitlab into the quartly-branch and did not have enough time for testing 8.6. I'm already working on the next version, which will follow soon :) It need some more testing and documentation and will follow next week.

I think this news are worth a blog post. ;)

**Comment by stanhu** [comment]
@t-zuehlsdorff Thanks for the update! Great work! @nearlythere may blog about this indeed.

**Comment by dosire** [comment]
Great! I made an issue for the blog post https://gitlab.com/gitlab-com/blog-posts/issues/193

**Comment by dosire** [comment]
I added it to our website with https://gitlab.com/gitlab-com/www-gitlab-com/commit/a9540192b6e99b5ce7aad4d6915ea01c65541916 and linked from the wiki https://github.com/gitlabhq/gitlab-public-wiki/wiki/Unofficial-Installation-Guides

**Comment by nearlythere** [comment]
@t-zuehlsdorff Hello Torsten! Would you be interested in writing a blog post? You don't have to fear any issues with writing or English, we help you along the way. We also pay for contribution to the blog. https://about.gitlab.com/community/writers/

**Comment by t-zuehlsdorff** [comment]
@nearlythere Hello Heather, yes, i could write a blog post. What should i write about, how long should it be, etc? You can write this at ports@toco-domains.de (or at this to the issue created by dosire?).

**Comment by nearlythere** [comment]
@t-zuehlsdorff Awesome! I will email now!
