### ISSUE TITLE
Display diff in a treeview

### ISSUE THREAD

**Issue by ralf57** [gitlabhq/gitlabhq#9987]
It would be great to have a merge request diff to be displayed in a treeview (à la Bitbucket).
This makes much easier and convenient to see and check the changes without having to scroll the page long way down

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
