### ISSUE TITLE
Search for 'NOT' labels

### ISSUE THREAD

**Issue by msmith1114** [gitlabhq/gitlabhq#9989]
I'd love the ability to search for issues that DO NOT contain X label. For example merge requests will often auto-close the related issue but until it is tested I don't mark it with a 'resolved' label until after it goes through QA.

So I would love the ability to search for issues in closed status that ARE NOT labeled with 'resolved' for instance.

(could someone mark this with a feature request label. Thanks!)

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
