### ISSUE TITLE
Missing documentation for HTTP_X_GITLAB_LFS_TMP (for Git LFS)

### ISSUE THREAD

**Issue by schmurfy** [gitlabhq/gitlabhq#9990]
I migrated from an old gitlab release to enable lfs on our servers, for various reasons I installed it from sources instead of the omnibus packages and so far eveyrthing is working as it was but for some reasons lfs refuse to work, after digging in the gitlab sources I ame accross this:

( from `lib/gitlab/lfs/router.rb#put_response` )
```
tmp_file_name = sanitize_tmp_filename(@request.env['HTTP_X_GITLAB_LFS_TMP'])
```

What I can't figure out is where this HTTP header is supposed to come from and what it should contain, when searching the gitlabhq repository only this line and its test comes out and while the test partly shows what this header should contain it does not says anything about where it comes from xD

**Comment by maxlazio** [comment]
This header gets sent over by gitlab-workhorse, separate daemon which handles all the heavy lifting like creating archives, serving and processing large file downloads and uploads. Header gets set [at this line](https://gitlab.com/gitlab-org/gitlab-workhorse/blob/0.6.0/internal/lfs/lfs.go#L81).

**Comment by schmurfy** [comment]
thanks !

**Comment by schmurfy** [comment]
I changed the code to make it works without the proxy since for our use case it is no needed, it works fine.
