### ISSUE TITLE
Internal links to other page section links have strange formatting

### ISSUE THREAD

**Issue by deephoot** [gitlabhq/gitlabhq#9991]
**Repeatable in Gitlab CE 8.14 with chrome 47**

Assume you have two pages in a project : pageone and pagetwo 
Within pagetwo, you have a section (say a H3) which can be linked to directly at https://gitlab.mydomain.com/group/project/wikis/pagetwo#section

If you go directly to the link, the section appears below the page header as expected.
If you have a link to the section from pageone, either relative (pagetwo#section) or absolute url, and open in a new tab you get the same expected behaviour.
However, if you open it in the same tab by just clicking it, the section appears to be slightly hidden behind the page header as if the section was loaded at the top of the page and the header then overlaid.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
