### ISSUE TITLE
Random Internal API error 

### ISSUE THREAD

**Issue by bornxbackwards** [gitlabhq/gitlabhq#9992]
I am experiencing random API error when using Gitlab. The error happens on both a Gitlab instance on Ubuntu 14.04 and one instance on RedHat 6.5. Once in a while, the git client would get:

GitLab: Failed to authorize your Git request: internal API unreachable fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

log in /var/log/gitlab/gitlab-shell/gitlab-shell.log:

WARN -- : Failed to connect to internal API : #

I do not see any other error message. The error happens few times a day. We set-up monitoring doing a git pull on a small repo every 15 minutes, and I would get the error on average 3-4 times a day. There is no load on the server and no error message. Switches show no error. The RedHat one is actually brand new and only has that one repo. Feels like a bug?

**Comment by dcty** [comment]
the same problem,any updates ?

**Comment by bornxbackwards** [comment]
I feel a little less alone.

No one else has the issue?

**Comment by grzesiek** [comment]
@bornxbackwards This issue tracker has been closed, we now use issue tracker at gitlab.com/gitlab-org/gitlab-ce, please resubmit there. Thanks!

**Comment by bornxbackwards** [comment]
@grzesiek Thank you for the information. The ticket already exist there https://gitlab.com/gitlab-org/gitlab-ce/issues/3998 with no anwser.

**Comment by grzesiek** [comment]
@bornxbackwards Thanks for submitting this. Let's keep track on issue in GitLab tracker. I'm closing this one here.
