### ISSUE TITLE
Gitlab docker does not store data on mounted volumes

### ISSUE THREAD

**Issue by maxa4e** [gitlabhq/gitlabhq#9993]
Using below config according to the documentation http://doc.gitlab.com/omnibus/docker/
One would expect according to the docs that;

```
/srv/gitlab/data mounted as /var/opt/gitlab in the container is used for storing application data
/srv/gitlab/logs mounted as /var/log/gitlab in the container is used for storing logs
/srv/gitlab/config mounted as /etc/gitlab in the container is used for storing configuration
```

Would store the data, this is not working. 
The volumes on the host OS are empty and the /var/log/gitlab folders inside the docker container are non existant.  Is the documentation out of date? How to store all gitlab data outside the docker container in a persistant way on the host os?

```
docker run --detach \
--hostname gitlab.ourhost.com \
--publish 443:443 --publish 80:80 --publish 222:222 \
--name gitlab \
--restart always \
--volume /srv/gitlab/config:/etc/gitlab \
--volume /srv/gitlab/logs:/var/log/gitlab \
--volume /srv/gitlab/data:/var/opt/gitlab \
--env GITLAB_OMNIBUS_CONFIG=" external_url 'https://gitlab.ourhost.com/'; gitlab_rails['lfs_enabled'] = true; nginx['redirect_http_to_https'] = true;" \
gitlab/gitlab-ce:latest
```

**Comment by stanhu** [comment]
That should work. Does your Docker user have permissions to mount and write to `/srv/gitlab`?

**Comment by maxa4e** [comment]
This seems related specific to OSX an gitlab and is not a real gitlab issue. will close
