### ISSUE TITLE
Problems installing fresh gitlab on Ubuntu 12.04

### ISSUE THREAD

**Issue by rnveach** [gitlabhq/gitlabhq#9995]
I am on Ubuntu 12.04 32 bit.
I am using the instructions at https://github.com/gitlabhq/gitlabhq/blob/8-4-stable/doc/install/installation.md .

I have completed everything up to number 5, and am on number 6, installing Redis.
I ran `sudo ./install_server.sh` and it failed because it couldn't find the redis executable.
````
Please select the data directory for this instance [/var/lib/redis/6379] 
Selected default - /var/lib/redis/6379
Please select the redis executable path [] 
Mmmmm...  it seems like you don't have a redis executable. Did you run make install yet?
````

Since there was nothing in the instructions about this, I followed what the program said and ran `sudo make install` instead of what the instructions said `make` and this is what happened.

````
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23$ sudo make install
cd src && make install
make[1]: Entering directory `/tmp/redis-2.8.23/src'

Hint: It's a good idea to run 'make test' ;)

    INSTALL install
    INSTALL install
    INSTALL install
    INSTALL install
    INSTALL install
make[1]: Leaving directory `/tmp/redis-2.8.23/src'
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23$ cd utils
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23/utils$ sudo ./install_server.sh
Welcome to the redis service installer
This script will help you easily set up a running redis server

Please select the redis port for this instance: [6379] 
Selecting default: 6379
Please select the redis config file name [/etc/redis/6379.conf] 
Selected default - /etc/redis/6379.conf
Please select the redis log file name [/var/log/redis_6379.log] 
Selected default - /var/log/redis_6379.log
Please select the data directory for this instance [/var/lib/redis/6379] 
Selected default - /var/lib/redis/6379
Please select the redis executable path [/usr/local/bin/redis-server] 
Selected config:
Port           : 6379
Config file    : /etc/redis/6379.conf
Log file       : /var/log/redis_6379.log
Data dir       : /var/lib/redis/6379
Executable     : /usr/local/bin/redis-server
Cli Executable : /usr/local/bin/redis-cli
Is this ok? Then press ENTER to go on or Ctrl-C to abort.
Copied /tmp/6379.conf => /etc/init.d/redis_6379
Installing service...
 Adding system startup for /etc/init.d/redis_6379 ...
   /etc/rc0.d/K20redis_6379 -> ../init.d/redis_6379
   /etc/rc1.d/K20redis_6379 -> ../init.d/redis_6379
   /etc/rc6.d/K20redis_6379 -> ../init.d/redis_6379
   /etc/rc2.d/S20redis_6379 -> ../init.d/redis_6379
   /etc/rc3.d/S20redis_6379 -> ../init.d/redis_6379
   /etc/rc4.d/S20redis_6379 -> ../init.d/redis_6379
   /etc/rc5.d/S20redis_6379 -> ../init.d/redis_6379
Success!
Starting Redis server...
Installation successful!
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23/utils$ sudo cp /etc/redis/redis.conf /etc/redis/redis.conf.orig
cp: cannot stat `/etc/redis/redis.conf': No such file or directory
````

As you can see, the next instruction's command failed as the file doesn't exist. The only file in that directory is '6379.conf'.
I am lost on how to continue and need some guidance.

**Comment by stanhu** [comment]
You may want to try making a symlink:

```
ln -s /etc/redis/6379.conf /etc/redis/redis.conf
```

Then resume the instructions.

**Comment by rnveach** [comment]
@stanhu 
I ran your command.
I manually did `sed 's/^port .*/port 0/' /etc/redis/redis.conf.orig | sudo tee /etc/redis/redis.conf` because `redis.conf.orig` didn't exist.
I got down to `chown redis:redis /var/run/redis` and run into the next error, saying the user doesn't exist. Is my ubuntu missing a redis package or something?

````
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23/utils$ echo 'unixsocket /var/run/redis/redis.sock' | sudo tee -a /etc/redis/redis.conf
unixsocket /var/run/redis/redis.sock
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23/utils$ echo 'unixsocketperm 770' | sudo tee -a /etc/redis/redis.conf
unixsocketperm 770
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23/utils$ mkdir /var/run/redis
mkdir: cannot create directory `/var/run/redis': Permission denied
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23/utils$ chown redis:redis /var/run/redis
chown: invalid user: `redis:redis'
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23/utils$ sudo mkdir /var/run/redis
ricky@ricky-PowerEdge-840:/tmp/redis-2.8.23/utils$ chown redis:redis /var/run/redis
chown: invalid user: `redis:redis'
````

**Comment by stanhu** [comment]
Sorry, those instructions may not be completely right since GitLab upgraded to Redis 2.8. You may need to add a redis user. Or you can always use the PPA for Ubuntu:

https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server

**Comment by rnveach** [comment]
@stanhu 
For now I created the user (`sudo adduser --disabled-login --gecos 'redis' redis
`) and finished the redis commands. I will continue on.

**Comment by stanhu** [comment]
@axil, my Redis build instructions don't seem to be quite right. Do you think you can revise?

**Comment by rnveach** [comment]
@stanhu 
I am now inside 'Initialize Database' on the command `sudo -u git -H bundle exec rake gitlab:setup RAILS_ENV=production`.
It fails with the following trace:
````
== Seed from /home/git/gitlab/db/fixtures/production/001_admin.rb
rake aborted!
Errno::EACCES: Permission denied - connect(2) for /var/run/redis/redis.sock
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/seed-fu-2.3.5/lib/seed-fu/runner.rb:46:in `eval'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:180:in `connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:209:in `connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:323:in `establish_connection'
````
`redis.sock` is owned by `root` with permission 'srwxrwx---'. In the first post, when I installed redis it would only complete as root otherwise I got permission errors.
Should I add global r/w permissions? I don't think chowning to redis user would help since the user was created after the initial install.

**Comment by stanhu** [comment]
Great, thanks for the update. I apologize for the trouble; I should have gone through and re-tested the entire flow for Redis 2.8.

**Comment by axilleas** [comment]
@stanhu I just saw your mention. I created https://gitlab.com/gitlab-org/gitlab-ce/issues/12686

@rnveach thanks for your updates. I will revise the installation doc ASAP. Closing this for now.

**Comment by robertd** [comment]
@axilleas Do you know when will Redis section be updated?

**Comment by axilleas** [comment]
Sorry, I just crafted a fix (and tested) in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2839. Use the installation guide that is in master https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md#6-redis

**Comment by stanhu** [comment]
@axilleas Oh, wow, I didn't realize Ubuntu 14.04 had updated Redis to 2.8. Great news!

**Comment by robertd** [comment]
@axilleas Thanks

**Comment by axilleas** [comment]
@stanhu yeah, that simplified things a LOT! http://packages.ubuntu.com/trusty/redis-server
