### ISSUE TITLE
Ubuntu 14.04 start on boot

### ISSUE THREAD

**Issue by peterSa** [gitlabhq/gitlabhq#9996]
I installed gitlab 8.4 from source using this guide - http://doc.gitlab.com/ce/install/installation.html on Ubuntu 14.04 and I'm having trouble getting it started on boot.

I used these commands from the tutorial to make the init script and run it on boot.
    sudo cp lib/support/init.d/gitlab /etc/init.d/gitlab
    sudo cp lib/support/init.d/gitlab.default.example /etc/default/gitlab
    sudo update-rc.d gitlab defaults 21

sudo service gitlab start works just fine but when the server is rebooted, gitlab wont start and nginx shows 502 Bad Gateway in browser.

What could be the problem?

**Comment by stanhu** [comment]
Is there a reason you're not installing via the omnibus package?

https://about.gitlab.com/installation/

You'll save yourself a lot of time and trouble.

Otherwise, you'll have to check the logs to see if all the processes are running properly.

**Comment by peterSa** [comment]
Yeah, my bad. I did not install but upgraded gitlab from version 5 to version 8.4.

Omnibus package only supports 64bit OS right?

**Comment by stanhu** [comment]
Yes.
