### ISSUE TITLE
Tag deletion using the API doesn't work (404)

### ISSUE THREAD

**Issue by gpocentek** [gitlabhq/gitlabhq#9998]
When trying to delete a tag using the API I get a 404 error. The request I'm using is:

`````
curl -H "PRIVATE-TOKEN: $TOKEN" -X DELETE http://localhost:8080/api/v3/projects/1/repository/tags/1.0
`````
The 1.0 tag has been created using the web interface. I am missing something, or could it be a bug?

Thanks.

**Comment by duduribeiro** [comment]
Hey @gpocentek.. What version of gitlab are u using?

I tried here with master and deleted the tag.

```
➜  ~  curl --header "PRIVATE-TOKEN: 1WWJC816aV5xxKv12pqV" -X GET "http://localhost:3000/api/v3/projects/9/repository/tags/"
[{"name":"v0.9.3","message"...................
➜  ~  curl --header "PRIVATE-TOKEN: 1WWJC816aV5xxKv12pqV" -X DELETE "http://localhost:3000/api/v3/projects/9/repository/tags/v0.9.3"
{"tag_name":"v0.9.3"}%
➜  ~  curl --header "PRIVATE-TOKEN: 1WWJC816aV5xxKv12pqV" -X DELETE "http://localhost:3000/api/v3/projects/9/repository/tags/v0.9.3"
{"message":"No such tag"}%
```

**Comment by gpocentek** [comment]
@duduribeiro 

I'm using gitlab 8.3.4, installed from packages.gitlab.com. The API docs in the 8.3-stable branch says it's already available. I'll test with 8.4.0 and see if it works.

**Comment by gpocentek** [comment]
It works with gitlab 8.4.0. Maybe the docs should be updated for branches older than 8.4-stable?

**Comment by duduribeiro** [comment]
But the 8.3-stable doc does not shows the `delete tag` action.. 
https://github.com/gitlabhq/gitlabhq/blob/8-3-stable/doc/api/tags.md

Where did u see the delete tag for 8.3?

thaanks =)

**Comment by gpocentek** [comment]
I guess I imagined things... Sorry for the noise and thanks for checking!
