### ISSUE TITLE
How to enable Git LFS ?

### ISSUE THREAD

**Issue by hoandang** [gitlabhq/gitlabhq#9999]
I followed this tut http://doc.gitlab.com/ce/workflow/lfs/lfs_administration.html, but it doesn't work? FYI, I did ***sudo gitlab-ctl restart***.

Thanks

**Comment by axilleas** [comment]
Try to do a `sudo gitlab-ctl reconfigure`. See http://doc.gitlab.com/ce/administration/restart_gitlab.html#omnibus-gitlab-reconfigure
